### ISSUE TITLE
Editing a commit message does not re-sign the commit

### ISSUE THREAD

**Issue by victorluft** [sublimehq/sublime_merge#1]
**Version info**

 - OS: Linux (4.18.8, Arch current)
 - Build: 1060

**Description**

When editing a commit message, with gpg signing enable, the edited commit is not signed.

**Steps to reproduce**

1. Enable GPG signing in your gitconfig
2. Create a repository, create a file in the repository, commit it
3. `git log --show-signature` to verify commit was signed
4. Edit the commit message (right-click commit in Sublime Merge, Edit Commit -> Edit Commit Message)
5. `git log --show-signature` and see an unsigned commit

**Expected behavior**

I would expect editing the message to behave identically to `git commit --amend -m "new message"`, which does re-sign the commit.

**Comment by LukasKalbertodt** [comment]
Still true in Build 1084. 

Curiously, using the "Amend Previous Commit" button does not have this problem: when using it, the previous commit stays signed.

**Comment by victorluft** [comment]
Yup. You can work around it currently by using `Edit Commit Contents` instead of `Edit Commit Message`, which will recreate (and resign) that & subsequent commits.

**Comment by wjwwood** [comment]
I just noticed this too.

**Comment by BenjaminSchaaf** [comment]
This has been fixed since build 1202

**Comment by jiping-s** [comment]
The problem is now back for build 2056, system git.

Normal commits are signed, but "Edit Commit Message" removes the signature, while "Edit Commit Contents" works. "git commit --amend" works.

**Comment by dpjohnst** [comment]
Hi @jiping-s,

Thanks for letting us know - when you get a chance could you share your Sublime Merge debug information with us.
This can be accessed in Sublime Merge via `Help > Debug Information`.

Before sharing this information with us, take a moment to remove any information you feel is sensitive (i.e. file paths, email addresses, remotes etc).

Cheers,
\- Dylan

**Comment by jiping-s** [comment]
@dpjohnst 

```
=== App Version Information ===
Build: 2056

=== Git Version Information ===
Using Git: git (system)
git version 2.30.1 (Apple Git-130)
PATH: /Users/some-user/.cargo/bin:/Users/some-user/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/some-user/.go/bin:/bin (from shell)
environment variables loaded using: /usr/local/bin/bash -l (1 skipped due to non-utf8 data)

=== Browse Page Information ===
HEAD: aa04aad8fe19b3fafdaf67f57d132f67cfca0e12
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===

=== Git Config Information ===
branch.autosetupmerge=always
branch.new-branch.merge=refs/heads/new-branch
branch.new-branch.remote=origin
branch.old-branch.merge=refs/heads/master
branch.old-branch.remote=.
branch.master.merge=refs/heads/master
branch.master.remote=origin
commit.gpgsign=true
core.bare=false
core.commentchar=;
core.excludesfile=/Users/some-user/.gitignore_global
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
credential.helper=osxkeychain
format.signoff=true
log.showsignature=true
pull.rebase=true
push.default=simple
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@github.com:some-group/project-1.git
user.email=some-user@dotcom
user.name=Some User

=== Our Config Information ===
Git Config Path Information
Using config path: /etc/gitconfig
Using config path: /Users/some-user/.config/git/config
Using config path: /Users/some-user/.gitconfig
Using config path: /Users/some-user/Public/some-group/project-1/.git/config

Our config output is different to the Git config output
branch.autosetupmerge=always
branch.new-branch.merge=refs/heads/new-branch
branch.new-branch.remote=origin
branch.old-branch.merge=refs/heads/master
branch.old-branch.remote=.
branch.master.merge=refs/heads/master
branch.master.remote=origin
commit.gpgsign=true
core.bare=false
core.commentchar=;
core.excludesfile=/Users/some-user/.gitignore_global
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
pull.rebase=true
push.default=simple
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@github.com:some-group/project-1.git
user.email=some-user@dotcom
user.name=Some User

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 0
```

I guess the git comes from Xcode 12.5.1, on OS/X 11.4
