### ISSUE TITLE
core.excludesFile setting not using correct defaults

### ISSUE THREAD

**Issue by stevenkaras** [sublimehq/sublime_merge#10]
**Version info**

 - OS: macOS 10.13.6
 - Build: 1062

**Description**

Git specifies the `core.excludesFile` setting, with the following description from the git-config manpage:

> Specifies the pathname to the file that contains patterns to describe paths that are not meant to be tracked, in addition to .gitignore (per-directory) and .git/info/exclude. Defaults to $XDG_CONFIG_HOME/git/ignore. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/ignore is used instead. See gitignore(5).

However, it appears that Sublime Merge is looking for a different path, or ignoring this altogether. Considering that many development environments include compiled files inside the repo, this can mean that Sublime Merge is effectively unusable for even simple repos (e.g. python produces pyc files, mypy creates a large .mypy_cache folder in the repo root, C object files, etc).

**Steps to reproduce**

1. Open repository ...
2. Have a global exclude file with patterns to exclude files
3. See unstaged files that should be ignored by the global excludes

**Expected behavior**

The global excludes file should be used for also ignoring files to be staged.

**Comment by wbond** [comment]
Do you happen to have the Help > Debug Information from a Sublime Merge window that is not respecting the ignore rules you have set up?

**Comment by stevenkaras** [comment]
Attached (renamed to work around github restrictions), along with my gitignore file, normally located at `~/.config/git/ignore`:

* [smerge.debug.txt](https://github.com/sublimehq/sublime_merge/files/2426682/smerge.debug.txt)
* [ignore.txt](https://github.com/sublimehq/sublime_merge/files/2426686/ignore.txt)

**Comment by jskinner** [comment]
Thanks for the report, this is fixed in dev build 1063 at https://www.sublimemerge.com/dev
