### ISSUE TITLE
Unix sockets show up under untracked files

### ISSUE THREAD

**Issue by victorluft** [sublimehq/sublime_merge#100]
**Version info**

 - OS: Linux 4.14.74 (Arch latest)
 - Build: 1069

**Description**

When there's a unix socket in a repo, Sublime Merge will show it as an untracked file. `git` will not.

**Steps to reproduce**

1. Open a repository currently in a clean state
2. Create a unix socket (an easy way to do this is to use `socat unix-recv:socket stdout`)
3. `git status` within the repo should have it as still clean
4. Sublime Merge shows `socket` as an untracked file. Adding it does nothing. (`git add socket` also does nothing and doesn't error)

**Expected behavior**

Sublime Merge should not include sockets in the untracked files list.

**Comment by jskinner** [comment]
Thanks for the report, this should be fixed in dev build 1071 - please reopen this if it's not.
