### ISSUE TITLE
Cannot customise submenus; missing "id" keys in default .sublime-menu files

### ISSUE THREAD

**Issue by howeaj** [sublimehq/sublime_merge#1000]
**Version info**

 - OS: Windows 10
 - Build: 2039

**Description**

[This page](https://www.sublimemerge.com/docs/menus#adding_to_submenus) explains that you're supposed to be able to extend submenus by referencing their id, and to look for the id in the Default.sublime-package\*.sublime-menu files.
[This page](https://www.sublimemerge.com/docs/menus#entries) corroborates that indeed, the "id" key is supposed to be

> Used for menu entries with "children" to allow adding additional child entries.

`Default.sublime-package\Commit.sublime-menu` does not contain any such "id" keys for its submenus.
I haven't checked any other sublime-menu files in that package, but I'd imagine others have the same issue.

**Steps to reproduce**

1. Open `C:\Program Files\Sublime Merge\Packages\Default.sublime-package\Commit.sublime-menu`
2. There aren't any "id" keys on any entries with children
3. It's not possible to override default menus with a user package [as documented](https://www.sublimemerge.com/docs/menus#adding_to_submenus)

**Expected behavior**

All default menu entries with children should have "id" keys, so that they can be extended by the user as described in [the documentation](https://www.sublimemerge.com/docs/menus#adding_to_submenus)

**Comment by dpjohnst** [comment]
Hi @howeaj,

Thank you for reporting this issue - currently the only menu using ids is the main menu bar ("Main.sublime-menu").
I will be adding ids to all other menus with children as an update - I'll reach out again once this has been completed.

In the meantime the best workaround would be to either add your own submenus, or add commands to the main menu.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Thanks for the feedback - fixed in development build 2042!
