### ISSUE TITLE
Move full screen window from one monitor to another

### ISSUE THREAD

**Issue by tildebox** [sublimehq/sublime_merge#1001]
**Version info**

 - OS: Windows 10
 - Build: 2041

**Description**

If I move **full screen** Sublime Merge window from one monitor to another with following keyboard shortcut:

Windows logo key  + Shift + Left arrow or Right arrow

...the window moves some pixels outside the screen.

**Steps to reproduce**

1. Open Sublime Merge
2. Make Sublime Merge full screen
3. Click on Windows logo key  + Shift + Left arrow or Right arrow to move window from one monitor to another.

**Expected behavior**

The window should not move outside the screen.

**Screenshots**

![Untitled-1](https://user-images.githubusercontent.com/61698441/100539041-ac473200-3233-11eb-8f1b-d2138a7ecd62.png)

**Comment by dpjohnst** [comment]
Hi @tildebox,

Just following up that this has been fixed in both the stable channel and the development channels.

Cheers,
\- Dylan
