### ISSUE TITLE
Warn users when navigating away from the merge tool

### ISSUE THREAD

**Issue by dpjohnst** [sublimehq/sublime_merge#1002]
**Problem description**
When using the merge tool, navigation commands will not warn the user that changes will be lost when navigating away.

**Preferred solution**
Add confirmation dialogs to the navigation commands when using the merge tool.

**Alternatives**
Disable navigation commands in the merge tool.

**Comment by stinos** [comment]
Just an idea, but when things like this would get added, is it possible to make this configurable in the preferences right away, defaulting to showing the dialog? SM does a good job of not getting into your way, and it would be great if it remains like that.

**Comment by dpjohnst** [comment]
Added in development build 2042

**Comment by dpjohnst** [comment]
This was released to the stable channel (Sublime Merge Build 2047)
