### ISSUE TITLE
Hover info on "Parent" commits in commit pane

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/sublime_merge#1009]
### Problem description

I made a multi-parent octopus merge. I'd be interested in tracing the history back along one of the parent graph edges, but I don't know which parent to click.

### Preferred solution

Can I have a hover pane showing at least a truncated first line of the parent commit message? More info would be nicer, but that would be a start.

### Alternatives

What I do right now is click each one, and then click "Back" if it's not the right one. (Sometimes I click the same one several times because I can't remember if I'd already clicked `a508b4f` vs `a8f57ca`.)

**Comment by dpjohnst** [comment]
Hi @michaelblyons,

This was added in Sublime Merge Build 2047!

Cheers,
\- Dylan
