### ISSUE TITLE
add option to hide commits list

### ISSUE THREAD

**Issue by AmjadHD** [sublimehq/sublime_merge#101]
**Problem description**

diffs, can be unclear to spot especially if the lines are long and/or you're in the split diff mode.

**Preferred solution**

add an option (button/keybinding) to hide commits lists, to gain space for diff view.

**Alternatives**

add word wrap option #128

**Comment by Zooce** [comment]
This is a good one - especially when you're working with a small screen (like my 13" Macbook Pro).

**Comment by joelekstrom** [comment]
Bump. Commit list is of almost no interest to me and takes so much space within the app

**Comment by AmjadHD** [comment]
this was fixed in build 2000
