### ISSUE TITLE
Corrupted text when scrolling

### ISSUE THREAD

**Issue by aclysma** [sublimehq/sublime_merge#1018]
**Version info**

 - OS: macOS 11.0, apple silicon, running under rosetta
 - Build: 2039

(While I'm posting, would be helpful to get an update on when an apple silicon build might be available)

I have not seen this before on intel running macOS 10.15. I have not tried 11.0 on intel.

**Description**

Corrupted text when viewing code in windows such as diff/blame

**Steps to reproduce**

1. Open a diff or blame for a file.
2. Scroll through the file. I noticed that part of the text would flicker in and out in different columns of a 3-way diff. It seems to have something to do with the vertical scroll position of the code.

**Expected behavior**

Uncorrupted text

**Screenshots**

![image](https://user-images.githubusercontent.com/316070/103043531-f7eab400-4531-11eb-8c69-a775eaf7719e.png)

**Comment by Ultra-Instinct-05** [comment]
Does this still happen if you disable hardware acceleration ? Go to `Preferences -> Preferences ...` from main menu & go to `Advanced` and disable hardware acceleration.

**Comment by aclysma** [comment]
Disabling hardware acceleration seems to work, thanks for the tip.

**Comment by dpjohnst** [comment]
Hi @aclysma,

Thank you for reporting this issue - this will be resolved in the next build.

As mentioned by @Ultra-Instinct-05, the recommended workaround is to disable hardware acceleration via `Preferences > Advanced > Hardware Acceleration`.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Thanks all for the feedback - fixed in development build 2042!

**Comment by unitof** [comment]
So far so perfectly rendered text!

**Comment by dpjohnst** [comment]
Hi all,

Just following up that the fix for this issue was released to the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan
