### ISSUE TITLE
Selecting "one column" view panel option as first action fails

### ISSUE THREAD

**Issue by pjanck** [sublimehq/sublime_merge#1020]
**Version info**

 - OS: Windows 10
 - Build: 2039

**Description**

Switching the UI element "Locations/Commits/Files" to be "one column" does not work when a repo is freshly cloned, i.e. first action performed.

**Steps to reproduce**

1. Clone some repository
2. On the top left, select "one column" as the view option of the UI elements "Locations/Commits/Files"
3. Nothing happens

**Expected behavior**

Well, an update of the UI, to be "one column". 

It works, when first selecting a different option and then selecting "one column".

**Screenshots**

![grafik](https://user-images.githubusercontent.com/59165496/103201564-70fe5880-48f0-11eb-9581-5604287743ac.png)

**Comment by dpjohnst** [comment]
Hi @pjanck,

Thank you for reporting this issue - I haven't been able to reproduce the issue so far.
Could you confirm what the default layout is when freshly cloning a repository (i.e. does it start with `Two Columns, Files on Right`)?

Thanks,
\- Dylan

**Comment by pjanck** [comment]
Hi @dpjohnst ,

Exactly, default option is two column, Files on Right.

I don't have the issue, if I close an existing repo and open it anew - I assume some sort of settings-saving is happening in the background.

Thisissue occurs when *cloning* new repository and opening it for the first time.

Hopefully this helps.

**Comment by dpjohnst** [comment]
Hi @pjanck,

Thank you for the additional information - I've managed to replicate the issue and will be working to resolve this.
I'll keep you updated.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Thanks for the feedback - fixed in development build 2042

**Comment by dpjohnst** [comment]
Just following up that the fix was released to the stable channel (Sublime Merge Build 2047)
