### ISSUE TITLE
Signature Validation is incompatible with smimesign

### ISSUE THREAD

**Issue by lordwelch** [sublimehq/sublime_merge#1022]
**Version info**

 - OS: Windows 10
 - Build: 2039

**Description**

When Sublime Merge creates the temporary file containing the signature it precedes each line after the first line with space, causing the Go stdlib to provide the error `structure error: tags don't match`.

Changing the temp file to have a preceding space in the first line to make the file consistent also fails with Go stdlib, the only change to the file that is required is to remove the preceding space on the END SIGNED MESSAGE tag.

There are no issues using git to validate the signature, the temporary file it creates does not have the extra beginning space.
Example files showing what is given to smimesign from Sublime Merge is attached

[argv3.txt](https://github.com/sublimehq/sublime_merge/files/5752508/argv3.txt)
[stdin.txt](https://github.com/sublimehq/sublime_merge/files/5752509/stdin.txt)

**Steps to reproduce**

1. Install https://github.com/github/smimesign/releases/tag/v0.1.0
2. Run `git config --global gpg.x509.program smimesign`
3. Open Repository with a commit signed with smimesign
4. Select the signed commit

**Expected behavior**

Signature shows as valid

**Comment by srbs** [comment]
@lordwelch, does it still happen if you change the git binary used to `System`? (Preferences -> Advanced -> Git Binary)

**Comment by lordwelch** [comment]
Yes, it appears that Sublime Merge calls the binary specified by `git config --global gpg.x509.program` directly

**Comment by dpjohnst** [comment]
Hi @lordwelch,

Thanks for reporting this issue - I believe this is a problem with smimesign, as the same issue occurs when displaying the commit signature via: `git show --show-signature COMMIT_HASH`

I'd definitely encourage you to submit a bug report to the folks who maintain `smimesign`.

Kind regards,
\- Dylan
