### ISSUE TITLE
App quits on commit when pre-commit is installed

### ISSUE THREAD

**Issue by samsamoa** [sublimehq/sublime_merge#1023]
**Version info**

 - OS: MacOS 10.11 (on an M1 MacBook)
 - Build: 2039

**Description**

When `pre-commit` is installed in a repository, Sublime Merge will quit whenever I try to make a commit.  If I uninstall the `pre-commit` hook, everything works fine.  There is no crash report - the app just quits, with no error at all.

**Steps to reproduce**

1. `pre-commit install`  (my hooks include `black`)
2. Stage a file, type a commit message, and click "commit"

**Expected behavior**

The commit completes successfully.

**Comment by samsamoa** [comment]
I can resolve the issue by replacing the top line of my `.git/hooks/pre-commit` file:

Triggers crash/quit:
`#!/usr/bin/env python3`

Works fine:
`#!/Users/sam/miniconda3/envs/default/bin/python3`

**Comment by bastianh** [comment]
I also had a problem with a tool crashing in the pre-commit hook which also crashed Sublime Merge instead of reporting the error.
