### ISSUE TITLE
Warn when opening a non git repo dir

### ISSUE THREAD

**Issue by humancopy** [sublimehq/sublime_merge#1026]
**Problem description**

When opening a non repo folder with Sublime Merge it adds all the files under the untracked automatically and doesn't warn that the folder is not a Git repo (and should offer to init it or cancel).

This is huge if yo don't pay attention (like I did today). I asked Sublime Text to open the repo and for some reason it opened the parent folder (where other projects were located), and I thought it was all mistakes of untracked files so I deleted them, losing thousands of valuable work files which I'm now working to restore. This could have been avoided if Sublime Merge would have warned me of opening a non repo folder, instead of just opening it and listing all the files as untracked (when it's not even a git repo)

**Preferred solution**

Add a popup that will warn the user that the folder is not a git repo and would offer to init it as an empty repo or cancel opening it in Sublime Merge

**Comment by srbs** [comment]
Sublime Merge already validates if a folder is a git repo or not.

On the UI:
![Screen Shot 2021-01-04 at 15 02 37](https://user-images.githubusercontent.com/297298/103581398-90255900-4ea1-11eb-890d-47d3b1bc966a.png)



On the command line:
```
$ mkdir repo_validation
$ smerge repo_validation
Unable to find a git repository at repo_validation
```

Are you sure you didn't have a git repo initialized somewhere in the parent hierarchy that made SM think it was a valid repository?

**Comment by humancopy** [comment]
So maybe it's because sub folders have `.git` in them that it assumed the parent is a git repo as well?

I don't have a `.git` folder in the parent folder.

It's basically this structure:

`~/projects/PROJECT_NAME/.git`

And what happened is that I opened `~/projects` by mistake in Sublime Merge and it showed me all those untracked files and didn't say it's not a git repo.

**Comment by humancopy** [comment]
I think all the untracked files were in folders that weren't a git repo, didn't have `.git` under them

**Comment by srbs** [comment]
@humancopy, do you have a `.git` folder in any of `~` or `~/..` or `~/../..`, etc?

If you re-open `~/projects` in Sublime Merge, what does the window title have for the path?

**Comment by humancopy** [comment]
I don't have a `.git` folder in `~/`

In the tab it showed `projects`. I didn't notice in the beginning, I'm sure I opened one of the projects...

I don't want to open it now because I'm restoring and I don't want to wake up any demons while I do the restore 😅

**Comment by dpjohnst** [comment]
Hi @humancopy,

Sorry to hear you've lost files - I'd like to investigate this further so this can be prevented in the future.
We definitely have safeguards in place to detect these situations (as mentioned by @srbs).

When attempting to open a Git repository, Sublime Merge will walk up the directory tree until it finds a `.git` folder or it finds a bare git dir with `core.worktree` enabled. If none of these things can be found, it displays an error like the one mentioned above.

When you get a chance, could you attempt to re-open `~/projects` in Sublime Merge. 
If this is successful, would you mind sharing the `=== Git Config Information ===` from the debug information. 
This can be accessed via `Help > Debug Information`.

Kind regards,
\- Dylan

**Comment by humancopy** [comment]
Hey @dpjohnst 

Thanks, I managed to recover *most* of the files. It was quite a nightmare. I should have paid more attention, that's for sure, but I promise you that I didn't drag or opened `~/projects`, I dragged a subfolder from under `~/projects`. I have noticed this behaviour in the past but didn't think too much of it, just closed the tab and dragged the folder again, it would usually work ok on the second attempt. But this time it was fatal :)

Ok here's the debug log from after dragging `~/projects` onto Sublime Merge. I masked private info with `----`

```
=== Git Config Information ===
branch.master.merge=refs/heads/master
branch.master.remote=origin
branch.new_poker.merge=refs/heads/master
branch.new_poker.remote=dev
branch.v1rc8.merge=refs/heads/master
branch.v1rc8.remote=origin
commit.gpgsign=true
core.bare=false
core.excludesfile=/Users/----/.gitignore
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.quotepath=false
core.repositoryformatversion=0
credential.helper=osxkeychain
diff.tool=Kaleidoscope
difftool.Kaleidoscope.cmd=ksdiff --partial-changeset --relative-path "$MERGED" -- "$LOCAL" "$REMOTE"
difftool.prompt=false
gpg.program=gpg
merge.tool=Kaleidoscope
mergetool.Kaleidoscope.cmd=ksdiff --merge --output "$MERGED" --base "$BASE" -- "$LOCAL" --snapshot "$REMOTE" --snapshot
mergetool.Kaleidoscope.trustexitcode=true
mergetool.prompt=false
remote.dev.fetch=+refs/heads/*:refs/remotes/dev/*
remote.dev.url=----@----:/var/git-repos/----.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=ssh://----@----/var/git-repos/----.git
tag.forcesignannotated=true
user.email=147451+humancopy@users.noreply.github.com
user.name=humancopy
```

**Comment by dpjohnst** [comment]
Hi @humancopy,

Thanks for the additional information - what may have happened is that Sublime Merge didn't detect a Git repository in the subdirectory, so it began traversing up the directory tree until it found one. It seems as if Sublime Merge is detecting what it thinks is a Git repository from within `~/projects`. 

Could you perform the following:
1. Navigate to `~/projects` in the terminal
2. Run `git status` to determine if command-line Git is also picking up a git repository here
3. If so, could you run `git rev-parse --git-dir` and `git rev-parse --show-toplevel` and share the output

Kind regards,
\- Dylan

**Comment by humancopy** [comment]
Hey Dylan,

I don't know what to say. I just checked now again `~/projects` and there is a `.git` folder under it. I'm sure that when I checked before submitting this issue I didn't see one. I moved it and now when I try to drag `~/projects` to Sublime Merge it complains there's no git repo in this folder. 

I guess it was completely my bad. Sorry to take your time, going to close this now :)
