### ISSUE TITLE
Right clicking bottom few pixels of a branch above a folder branch opens context menu for the folder

### ISSUE THREAD

**Issue by markomarkovic** [sublimehq/sublime_merge#1028]
**Version info**

 - OS: Ubuntu 20.04 focal (tested in Gnome and KDE)
 - Build: 2022, 2041

**Description**

Right clicking on bottom few pixels of a branch that's immediately above the folder branch in `Locations` panel opens a context menu for the non-existing branch.

**Steps to reproduce**

1. Create a repository like this

    $ git init
    $ git commit --allow-empty -m "Create repository"
    $ git checkout -b fix/one
    $ git checkout -b fix-two
    $ git checkout master
    $ smerge -n .

3. Right click on the bottom 1-2 pixels of the `fix-two` branch in `Locations` panel.

The context menu for non-existing `fix` branch is shown.

**Expected behavior**

The context menu for the existing `fix-two` branch should be shown.

**Screenshots**

https://user-images.githubusercontent.com/99233/103746530-a99de080-501a-11eb-90b1-e114a6408208.mp4

**Comment by dpjohnst** [comment]
Hi @markomarkovic,

Thank you for reporting this issue!
I've been able to reproduce the issue and will be investigating it further.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Thanks for reporting this - fixed in development build 2042
