### ISSUE TITLE
Sublime merge freeze on a lot of different action, until I click on another window (linux, openGL)

### ISSUE THREAD

**Issue by VincentGuinaudeau** [sublimehq/sublime_merge#1032]
**Version info**

 - OS: Manjaro
 - Build: 2039

**Description**

This only happens when the main window is maximized, and when using openGL rendering (I have a RX 5500 XT, with mesa driver).

Sometime, and on a wide variety of action that involve displaying new information in the main window, the whole application freeze.

To unfreeze it, I have to click on another window, or just move my mouse over some other window (this is consistent, the windows that only need to be moved over are always the same).

Non exhaustive list of action that freeze :
 * clicking on a commit,
 * switching between "Summary" and any specific file.
 * switching branch (because it display another commit probably)
 * displaying the history of a file or a hunk,
 * staging, unstaging, reverting
 * opening or closing the resolve conflict view
 * resolving a hunk in the resolve conflict view

Non exhaustive list of action that don't freeze :
 * scrolling
 * showing / hidding the menu bar (Alt)
 * opening any sub window (preferences, about) 

**Steps to reproduce**

1. Open a repository
2. Do any of the action listed above
3. Click on another window to unfreeze

**Expected behavior**

No freeze

**Comment by dpjohnst** [comment]
Hi @VincentGuinaudeau,

Thank you for reporting this issue.

Just to confirm, does this still occur when disabling OpenGL Rendering (via `Preferences > Advanced > Hardware Acceleration`)?

Kind regards,
\- Dylan

**Comment by VincentGuinaudeau** [comment]
Yes, this doesn't happen when disabling OpenGL Rendering.

**Comment by VincentGuinaudeau** [comment]
Hi, I noticed that this happened too on sublime text, but also on other programs like my terminal.

Eventually, I think a system update fixed the issue, because I haven't seen this problem for at least a month.
