### ISSUE TITLE
Git flow not working

### ISSUE THREAD

**Issue by Bradzer** [sublimehq/sublime_merge#1036]
I faced the following issue after upgrading my system to Linux Mint 20 : `git: 'flow' is not a git command. See 'git --help'.` `git` and `git-flow` are both well installed on my system though.

**Comment by dpjohnst** [comment]
Hi @Bradzer,

Sorry to hear you're having issues using Git Flow with Sublime Merge.

Would you mind sharing your debug information from Sublime Merge (via Help > Debug Information).
Take a moment to strip it of any information you feel is sensitive (emails, names, paths etc).
The most important sections are the `App Version Information` and the `Git Version Information` sections.

Additionally, could you confirm how you installed Git Flow.

Kind regards,
\- Dylan

**Comment by Bradzer** [comment]
The content of the debug :
```
=== App Version Information ===
Build: 2039

=== Git Version Information ===
Using Git: git (system)
git version 2.29.2
PATH: /app/bin:/usr/bin:/app/libexec/git-lfs

=== Our Config Information ===
Git Config Path Information
Using config path: /usr/etc/gitconfig
Using config path: /home/brad/.var/app/com.sublimemerge.App/config/git/config
Using config path: /home/brad/.gitconfig
Using config path: /opt/lampp/htdocs/wordpress/wp-content/plugins/woocommerce-all-discounts-master/.git/config

Our config output is identical to the Git config output

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 
```

I installed sublime merge through the Software Manager of my Linux Mint.

**Comment by dpjohnst** [comment]
Hi @Bradzer,

Thanks for the additional information - could you confirm the following:
- Does running the command `git flow` in the terminal work as expected?
- Could you share your PATH variable from the terminal (`echo $PATH`)?

Kind regards,
\- Dylan

**Comment by Bradzer** [comment]
`git flow` is properly working from terminal and for the moment it's how I've been using it until the problem is solved.

My PATH is as followed : 
`/home/brad/Documents/nodejs/bin:/home/brad/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/brad/Android/Sdk/emulator:/home/brad/Android/Sdk/tools:/home/brad/Android/Sdk/tools/bin:/home/brad/Android/Sdk/platform-tools:/opt/java/jdk1.8.0_191/jre/bin`

**Comment by dpjohnst** [comment]
Hi @Bradzer,

Thank you for sharing the additional information.

It looks as if your terminal is picking up additional PATH variables that are not present when Sublime Merge is launched.
Could you try launching Sublime Merge from the terminal to see if this resolves the issue?

Kind regards,
\- Dylan

**Comment by Bradzer** [comment]
`Command 'smerge' not found`

**Comment by dpjohnst** [comment]
Note that some installation methods require you to manually set up the `smerge` command.
Try run the following in your terminal before running smerge: `ln -s /opt/sublime_merge/sublime_merge ~/bin/smerge`

**Comment by Bradzer** [comment]
Git flow is working when running sublime merge from the terminal.

**Comment by Bradzer** [comment]
I managed to find a solution on my own.

I changed the executable path in the sublime merge `.desktop` file. The commented exec path was the old one.

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Sublime Merge (GitFlow)
GenericName=Git Client
Comment=Sublime Merge is a Git client, from the makers of Sublime Text
#Exec=/opt/sublime_merge/sublime_merge %F
Exec=/var/lib/flatpak/app/com.sublimemerge.App/x86_64/stable/active/files/extra/opt/sublime_merge/sublime_merge
Terminal=false
MimeType=text/plain;
Icon=sublime-merge
Categories=Development;
StartupNotify=true
Actions=new-window;

[Desktop Action new-window]
Name=New Window
#Exec=/opt/sublime_merge/sublime_merge --launch-or-new-window
Exec=/var/lib/flatpak/app/com.sublimemerge.App/x86_64/stable/active/files/extra/opt/sublime_merge/sublime_merge --launch-or-new-window
OnlyShowIn=Unity;
```

**Comment by dpjohnst** [comment]
Hi @Bradzer,

Sorry for the delay in responding - I'm glad you could resolve the issue!
I'm going to go ahead and close this issue now, but feel free to re-open it if you see any further issues.

Kind regards,
\- Dylan
