### ISSUE TITLE
Sublime Merge crashes when open very big dimension image.

### ISSUE THREAD

**Issue by trieulieuf9** [sublimehq/sublime_merge#1037]
**Version info**

 - OS: Windows 10, 16GB RAM, i5
 - Build: 2309

**Description**

When Sublime Merge try to preview or stage an JPG file with very big dimension, it crashes. I have a crafted JPG file with 260x260 pixel in real data, but its width height metadata is 64250x64250.

**Steps to reproduce**

1. Copy this file into a repository file system ![pixels_64250x64250 ](https://user-images.githubusercontent.com/17454792/104538016-aa9fc500-564d-11eb-99d4-de0af1e4b3cc.jpg)
2. Open this repository with Sublime Merge
3. Click on the pixels_64250x64250 image or stage it

**Expected behavior**

Sublime Merge will crash immediately

**By the way**
- Sublime Text will also crash if it try to open this file as image.![pixels_64250x64250 ](https://user-images.githubusercontent.com/17454792/104538016-aa9fc500-564d-11eb-99d4-de0af1e4b3cc.jpg)
- Originally, I got this image from https://hackerone.com/reports/390

**Comment by dpjohnst** [comment]
Hi @trieulieuf9,

Thanks for reporting this issue - this will be resolved in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Fixed in development build 2042
