### ISSUE TITLE
Make holding a ctrl in the project switcher open a new tab

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/sublime_merge#1038]
**Problem description**

Similar to the recent addition in Sublime Text for windows, I'd like to open a new tab from the quick switcher dialog when ctrl is hold (Linux).

The current workaround is to press ctrl+t to create a new tab first.

**Comment by melomac** [comment]
I'd definitely second that feature request, even though option key ⌥ feels more natural on macOS.

**Comment by dpjohnst** [comment]
Thanks for the feedback - added in development build 2042
