### ISSUE TITLE
Fail to clone/pull/push repository on Github

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#1039]
**Version info**

 - OS: Windows 10 
 - Build: 2041
 
**Description**

When cloning a new repository, Github login always fail

**Steps to reproduce**

1. New tab
2. Put a Source URL to clone repo from GitHub, like https://github.com/jasonycw/some-repo.git
3. Click `Clone`
4. GitHub login page pop up 
     ![image](https://user-images.githubusercontent.com/4518597/104810988-61a96580-5833-11eb-91a9-b909b281b9b4.png)
5. Type in the username password and there is the following error on SM and a new pop up, there is no way to press Ctrl+C anywhere
    ![image](https://user-images.githubusercontent.com/4518597/104811023-acc37880-5833-11eb-9fd7-6c1c7c96e210.png)
6. Type in the username and another pop up with absolutely the wrong info
    ![image](https://user-images.githubusercontent.com/4518597/104811048-d54b7280-5833-11eb-8317-a9fc01354954.png)
7. I even tried cancel the GitHub login page and type email in the username popup, and the password popup is again wrong
    ![image](https://user-images.githubusercontent.com/4518597/104811066-03c94d80-5834-11eb-8d57-0ae327a680e7.png)
8. Always showing this
    ![image](https://user-images.githubusercontent.com/4518597/104811103-33785580-5834-11eb-8e13-9229610d916c.png)

**Expected behavior**

Type in the info in GitHub login page, enter 2-step verification code, clone successfully.

**Comment by dpjohnst** [comment]
Hi @jasonycw,

This is likely due to the deprecation of Git Credential Manager for Windows (now replaced with Git Credential Manager Core).
It looks like the old manager is still in use, which can cause issues when authenticating with GitHub.

We've updated the bundled version of Git in the latest development build (which includes Git Credential Manager Core).

When you have a spare moment, could you confirm whether you're using the `system` or `bundled` Git binary?
This can be found via `Preferences > Preferences... > Advanced > Git Binary`

If you find you are using the system Git installation, I'd suggest updating to the latest version of Git (or at least Git 2.29).
If you are using the bundled Git binary, we can investigate further to see what is causing this behavior.

Kind regards,
\- Dylan

**Comment by jasonycw** [comment]
Hi @dpjohnst 

I am using the bundle version

![image](https://user-images.githubusercontent.com/4518597/104916926-acf77b80-59cd-11eb-8b03-7cfd67cb0908.png)

I tried using SourceTree instead and it can pull the same repo without any issue. But they moved to using GitHub authentication instead of login

**Comment by dpjohnst** [comment]
Hi @jasonycw,

Thank you for the additional information. I'll be investigating further.

Could you confirm whether you see a different dialog appear prior to the dialog shown in step 4. You should see a slightly different dialog appear offering to log in via the browser (GitHub oauth dialog). 

Kind regards,
\- Dylan

**Comment by jasonycw** [comment]
It seems like the error is not happening again today even with the same repository.
I deleted the repo that has problem a few days ago and then pulled with SourceTree. Then I try to clone again with Sublime Merge, but it can pull properly.

I do remember the dialog always stay the same but the ending error message (step 8) may have difference message depends on whether I login or cancel the GitHub dialog.

**Comment by jasonycw** [comment]
This happen to me again in the middle of the working day. Where last hour I can still push pull code to my repository and all of a sudden, I cannot pull any code.

This is the same repository that I cannot clone last time.

I tried with command and it seems to fail the same way
![image](https://user-images.githubusercontent.com/4518597/105139544-66bb2d00-5b31-11eb-94b1-0a0ec20ac7ad.png)
![image](https://user-images.githubusercontent.com/4518597/105139565-6ae74a80-5b31-11eb-9cdf-32ac9cbe2108.png)

Maybe a GitHub issue?

**Comment by jasonycw** [comment]
More update,

Without rebooting, I opened SourceTree and use their OAuth login mechanism there, then it seems that I can pull code with Sublime Merge again, I am not quite sure why login with SourceTree can fix Sublime Merge login issue.

**Comment by dpjohnst** [comment]
Hi @jasonycw,

Could you confirm whether you have enabled 2FA on GitHub? 
You can find this via https://github.com/settings/security

If it's enabled, you'll see the following:
![2FA](https://user-images.githubusercontent.com/18252447/105148787-e4ddfa80-5b56-11eb-9f5f-b8b9b5044df1.png)

Kind regards,
\- Dylan

**Comment by jasonycw** [comment]
Yes, I had it enabled for years

**Comment by dpjohnst** [comment]
Hi @jasonycw,

Thanks for the additional info.

Are you using a Personal Access Token (PAT) instead of a password when authenticating in Sublime Merge?

Kind regards,
\- Dylan

**Comment by jasonycw** [comment]
No, I used the GitHub login pop up before and it did asked for my 2-step verification code. I didn't use token for any git operation. 

I have been using Sublime Merge for over a year and have been using GitHub 2-step verification code longer than that and I didn't have this issue before.

**Comment by dpjohnst** [comment]
Hi @jasonycw,

Thanks for sharing - it seems like Git is trying to use the outdated Git Credential Manager for Windows to authenticate (which is no longer maintained, and does not work for basic authentication anymore).

It should be popping up with the newer Git Credential Manager Core (which authenticates via oauth / browser).

Could you try running the following git commands to see if it resolves the issue:
`git config --global credential.helper manager-core`
`git config --global credential.gitHubAuthModes "oauth"`

Thanks,
\- Dylan

**Comment by jasonycw** [comment]
Not sure if it is working since the same issue is not happening right now on both of my PC, I did run both commands and nothing seems change

**Comment by dpjohnst** [comment]
Hi @jasonycw,

Just wanted to reach out to check if you've seen this issue since last time we spoke?

Kind regards,
\- Dylan

**Comment by jasonycw** [comment]
Currently not, since I only have access to two PCs which both experienced the same issue and was fixed the same way using SourceTree

**Comment by dpjohnst** [comment]
Thanks for the response @jasonycw,

I'm going to go ahead and presume this issue is resolved, but please feel free to re-open if it pops up again and I'll gladly investigate.

Kind regards,
\- Dylan
