### ISSUE TITLE
New cloned project are always collapse by default

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#1040]
**Version info**

 - OS: Windows 10
 - Build: 2041

**Description**

New cloned project are not following the "Merge Commit Display" setting

**Steps to reproduce**

1. Set the preference "Merge Commit Display" setting to "Expand by default"
    ![image](https://user-images.githubusercontent.com/4518597/104919829-dc0fec00-59d1-11eb-96c9-4836cde08eaf.png)
2. Clone any project
3. The cloned project's commits are all collapsed
4. Open the preference and switch the "Merge Commit Display" setting back and forth then the commits will be expanded again

**Expected behavior**

Pull new repo and commits are expanded

**Comment by dpjohnst** [comment]
Fixed in development build 2042!
