### ISSUE TITLE
Add `resize_window` command

### ISSUE THREAD

**Issue by dbazile** [sublimehq/sublime_merge#1042]
**Problem description**

I have a laptop with a 4K display but QHD monitors. Whenever I plug it in each morning GNOME resizes things however the heck it likes and I have to manually resize all of my Sublime Merge windows by hand.

I wrote a keymap for Sublime Text to handle this exact problem automatically:

```json
[
    {"keys": ["f7"], "command": "resize_window", "args": {"width":  760, "height": 1000}},
    {"keys": ["f8"], "command": "resize_window", "args": {"width": 1600, "height": 1000}},
    {"keys": ["f9"], "command": "resize_window", "args": {"width": 2000, "height": 1000}},
]
```

Since that command has no effect in Sublime Merge, I assume it isn't implemented.

**Preferred solution**

Add `resize_window` command to Sublime Merge.

**Comment by dpjohnst** [comment]
Thanks for the feedback - added in development build 2042

**Comment by dbazile** [comment]
Nice, works exactly as I'd expect! Loving Sublime Merge more and more by the day. Money well spent. :)
