### ISSUE TITLE
Custom window captions interfere with informational popups

### ISSUE THREAD

**Issue by OdatNurd** [sublimehq/sublime_merge#1047]
**Version info**

 - OS: Slackware Linux (using XFCE 4.12)
 - Build: 2042

**Description**

When using the new custom window caption support, the popup on the Discard button that reminds you that you need to click it a second time displays with a custom caption, obscuring the actual text of the popup.

**Steps to reproduce**

1. Open a repository that has at least one changed file
2. Click the `Discard` button once

**Expected behavior**

The popup/tooltip should provide a message indicating that the operation will not occur unless you click again:

![Expected](https://user-images.githubusercontent.com/13212876/106243078-8c91a300-61bd-11eb-989b-0dd88cc59722.png)

**Screenshots**

Currently, the popup includes a custom caption, though the size remains more or less as expected, and as a result there is no content displayed at all.

![Unexpected](https://user-images.githubusercontent.com/13212876/106243159-b945ba80-61bd-11eb-8cdd-365c45c3e052.png)

**Comment by dpjohnst** [comment]
This has been resolved in Sublime Merge build 2043
