### ISSUE TITLE
Add commit folding preference

### ISSUE THREAD

**Issue by spromicky** [sublimehq/sublime_merge#105]
**Version info**

 - OS: macOS 10.13.6
 - Build: 1070

**Description**

Not everyone have a repository with tons of merges. And i will prefer to see default behaviour with merge commit like it was before. Would be great if you add preference to control this: disable or enable folding.

**Steps to reproduce**

1. Open any repository

**Expected behavior**

Merge commit fot folded.

**Comment by jasonycw** [comment]
Similar issue? https://github.com/sublimehq/sublime_merge/issues/94

**Comment by spromicky** [comment]
Not really. I want fully disable this feature at all. Not just expand more commits.

**Comment by 13xforever** [comment]
This.
I have a bunch of repos with tons on branches, and I need to see how they relate at all times.
Right now I don't see any of this by default, and it's very disorienting and I spend more time figuring this shit out instead of doing my work.
It boggles my mind that it was released without any preferences to disable this behavior change.

**Comment by n8gray** [comment]
I don't *hate* the feature, but I would prefer to turn it off.  I don't want my tools hiding the structure of my repo from me without some positive action on my part.

**Comment by jasonycw** [comment]
If there are some button that will fold and unfold everything and save the setting of that, so no need to expand one by one will be great

**Comment by jskinner** [comment]
A new preferences, `expand_merge_commits_by_default`, has been added in dev build 1071 at https://www.sublimemerge.com/dev. The next stable build with this in it should come out sometime next week.
