### ISSUE TITLE
Wrong style for / type of titlebar

### ISSUE THREAD

**Issue by KoalaBR** [sublimehq/sublime_merge#1051]
**Version info**

 - OS: Manjaro Linux, KDE Plasma 5.20.4
 - Build: 2042

**Description**

The new release has its own titlebar and totally ignores KDE's settings, which looks totally out of place, has less contrast, does not clearly show which window has focus (and too me at least) suggests that the window is disabled.

I didn't find any settings or command line option which would switch back to the correct / old title bar.

**Steps to reproduce**

1. Start Sublime Merge
2. Optional: Open Change Log

**Expected behavior**

Sublime Merge uses the native KDE titlebar.

**Screenshots**

Native KDE titlebar (inactive and active)
![old_titlebar](https://user-images.githubusercontent.com/34948369/106326651-1c4a5680-627d-11eb-9234-b2cf82274cae.png)

New titlebar:
![new_titlebar](https://user-images.githubusercontent.com/34948369/106326643-181e3900-627d-11eb-8d8c-33170a5233cb.png)

**Comment by srbs** [comment]
I doubt the Sublime team will revert this as the entire feature it to support custom title bars on Linux like they exist on Windows & macOS.

However, one of my previous comments has a fix for you: https://github.com/sublimehq/sublime_merge/issues/863#issuecomment-673253334

**Comment by publicarray** [comment]
Well right now it breaks error messages, context menus are grey, and the UI just is weird.
![Screenshot from 2021-01-30 20-33-20](https://user-images.githubusercontent.com/5497998/106352891-77606580-62de-11eb-9a40-c52bddeffea7.png)
![Screenshot from 2021-01-30 20-31-00](https://user-images.githubusercontent.com/5497998/106352893-792a2900-62de-11eb-82d3-725e071a5465.png)

**Comment by publicarray** [comment]
I just reverted with `sudo pacman -U /var/cache/pacman/pkg/sublime-merge-2041-1-x86_64.pkg.tar.xz`

**Comment by srbs** [comment]
that new issue might be #1047

**Comment by publicarray** [comment]
Thanks @srbs yes, that looks like it :) Also switching to the dark theme fixes the context menus.

**Comment by KoalaBR** [comment]
Thanks for the workaround @srbs. At least I now have different colours for active and inactive titlebars. However, I would still prefer my KDE titlebars over GTK ones anytime. But now I can at least install a fitting GTK theme.

Don't get me wrong, I am not asking to revert this feature, only for an option to get the old titlebars back.

**Comment by dpjohnst** [comment]
This has been resolved in Sublime Merge build 2043
