### ISSUE TITLE
Later build has date before previous build date

### ISSUE THREAD

**Issue by mikekokuba** [sublimehq/sublime_merge#1053]
**Version info**

 - OS: macOS 10.15.7
 - Build: 2043

**Description**

Later build has date before previous build date

**Steps to reproduce**

1. Open change log
2. Observe build 2042 date is 29 Jan 2021
3. Observe build 2043 date is 03 Jan 2021

**Expected behavior**

Build dates are later as build number increases

**Screenshots**

![Screen Shot 2021-02-05 at 11 18 31 AM](https://user-images.githubusercontent.com/6855714/107079267-7333bc80-67a4-11eb-8328-c7184a355a64.png)

**Comment by dpjohnst** [comment]
Hi @mikekokuba,

Thanks for letting us know - this was a result of a typographical error.

This will be fixed in the next build :)

Kind regards,
\- Dylan
