### ISSUE TITLE
Build 2043 kernel trap on non-gnome desktop

### ISSUE THREAD

**Issue by step-** [sublimehq/sublime_merge#1054]
**Version info**

 - OS: Gnu/Linux x64 (not a gnome desktop)
 - Build: 2043

**Description**

Builds 2042 and 2043 exit before displaying the UI due to a kernel trap.  From dmesg:
```
[15881.710643] traps: sublime_merge[28387] trap int3 ip:7f620a45dded sp:7fff6f743ed0 error:0 in libglib-2.0.so.0.5800.1[7f620a418000+ef000]
```
(Your server should have already received several corresponding mini dump crash reports from your crash_reporter binary)

Running sublime_merge under strace shows the following relevant log excerpt:
```
(zip zip)
29438 21:52:47.019382 write(2, "\n(sublime_merge:29438): GLib-GIO-ERROR **: 21:52:47.019: Settings schema 'org.gnome.desktop.interface' is not installed\n", 120) = 120
29438 21:52:47.019413 --- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL} ---
29438 21:52:47.019430 rt_sigaction(SIGTRAP, NULL, {sa_handler=0x6b60c2, sa_mask=[ILL TRAP ABRT BUS FPE SEGV], sa_flags=SA_RESTORER|SA_ONSTACK|SA_SIGINFO, sa_restorer=0x7f9eb3f55010}, 8) = 0
29438 21:52:47.019456 prctl(PR_SET_DUMPABLE, SUID_DUMP_USER) = 0
29438 21:52:47.019477 gettid()                = 29438
29438 21:52:47.019499 mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9eb54fc000
(zip zip)
```
The GLibGIO-ERROR isn't printed to the terminal.  I could only catch it by looking at strace's log.

So I installed package  "gsettings-desktop-schemas" on my system and was able to start and use build 2043.  Note that my desktop isn't a gnome desktop therefore that package serves no purpose on my system other than, as of now, as a work-around against sublime-merge not starting. 

**Steps to reproduce**

Just running /opt/sublime_merge/sublime_merge /repo

**Comment by dpjohnst** [comment]
Hi @step-,

This should be resolved in Sublime Merge Build 2044.
Please reach out if it hasn't been resolved on your end.

Kind regards,
\- Dylan

**Comment by step-** [comment]
Hi @dpjohnst,

indeed it is. I tested 2044 and it's a go for me.  Thank you  very much!

- step
