### ISSUE TITLE
Text files with .pgm extension are treated as image files

### ISSUE THREAD

**Issue by kpowick** [sublimehq/sublime_merge#1055]
**Version info**

 - OS: macOS 11.1
 - Build: 2042

**Description**

SM treats text files named with a `.pgm` extension as image files.  Unfortunately, for me anyway, I have a lot of legacy code (text) files that use that extension.  Example: `calc.taxes.pgm`.  As of build 2042, I can no longer use SM with `.pgm` files, and have reverted to build 2041.

**Steps to reproduce**

1. Add a text file named with a `.pgm` extension to your repo.
2. Make some changes to the file.
3. See how SM treats the file as an image diff instead of text.

**Expected behavior**

SM should determine the contents of a file using more than just the file name extension.

**Comment by dpjohnst** [comment]
Hi @kpowick,

Thanks for reporting this issue - this will be resolved in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Comment by kpowick** [comment]
This issue appears to be corrected as of Dev Build 2044.  

Thanks!
