### ISSUE TITLE
Allow undo of operations

### ISSUE THREAD

**Issue by poldi1405** [sublimehq/sublime_merge#1057]
**Problem description**

After operations like reset (basically everything where the HEAD pointer is changed) it would be quite useful to allow undo (maybe Ctrl+Z?) to recover commits otherwise lost.

**Preferred solution**

Should be pretty trivial thanks to git-reflog. Just pick the state before the previous one and return to that.

**Alternatives**

Keeping a history of the pointer somewhere in SM. Though that wouldn't be ideal because a lot of the Beauty of Merge comes from it using pretty much only standard git.

**Comment by dpjohnst** [comment]
Hi @poldi1405,

Thanks for sharing this feedback.

This is currently already possible via the application menu `Repository > Undo`

Kind regards,
\- Dylan

**Comment by poldi1405** [comment]
Never noticed that. Awesome!
