### ISSUE TITLE
Not possible to push to a remote which has a '.' in its name.

### ISSUE THREAD

**Issue by tgaabor** [sublimehq/sublime_merge#106]
**Version info**

OS: Windows 10.0.15063
Build: 1070

**Description**

I have a git remote repository with the name "v1.2". This seems to be a valid name since I can use it from the command line. I can also push to this repository like this: git push v1.2 mybranch.

**Steps to reproduce**

Add a remote via command line like this: git remote add v1.2 ...
Create a new commit
Try to push this using the Repository/Push... menu item
The list of remotes contains v1 instead of v1.2
![push_remote](https://user-images.githubusercontent.com/2537745/46798345-f74f1400-cd51-11e8-8b11-e731e0532725.png)
Selecting v1 will cause that it pushes the branch to a non-existing remote.

**Expected behavior**

The list of remotes contains v1.2

**Comment by jskinner** [comment]
This should be fixed in dev build 1071 at https://www.sublimemerge.com/dev. The changes should migrate into a stable build sometime next week.

Please reopen this if it's still an issue for you after 1071.
