### ISSUE TITLE
Windows UI offset is incorrect

### ISSUE THREAD

**Issue by wibek** [sublimehq/sublime_merge#1068]
**Version info**

 - OS: Windows 10
 - Build: 2047 (Also version 2040 has this problem. Version 2039 is Ok)

**Description**
On Windows there's big black border above all windows. The mouse coordinates offset is wrong with about the height of this black border. E.g. to close a window you have to click in the black border above the "X" button. Same for everything.
The about box doesn't show all data.

This bug makes using the program impossible.

I've also noted that the menu structure is changed to one drop down menu.

**Steps to reproduce**

1. Start SublimeMerge

**Expected behavior**

No black border, all mouse clicks correct.

Menu back to normal (like version 2039).

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/18323823/108992569-c0b39300-7699-11eb-8fd5-fdf413cafb41.png)

![afbeelding](https://user-images.githubusercontent.com/18323823/108993079-5a7b4000-769a-11eb-9985-76341e9c8449.png)

![afbeelding](https://user-images.githubusercontent.com/18323823/108995148-f8700a00-769c-11eb-83ec-04b46959c0cf.png)

**Comment by dns13** [comment]
Same for me. It's due to the hardware acceleration. If I disable OpenGL everything is fine.
The same sometimes happened for the earlier builds of Sublime Merge with OpenGL enabled, but was not present on the latest builds until now.

**Comment by dpjohnst** [comment]
Hi all,

Thank you for reporting this.

For those affected by this bug, could you share your OpenGL context information.
This can be found at the top of the console  (opened via Ctrl + `)

Additionally, could you share:
* whether you have any desktop scaling enabled
*  the resolution of your display

Thanks,
\- Dylan

**Comment by DimsFromDergachy** [comment]
The same.
https://github.com/sublimehq/sublime_merge/issues/1070

**Comment by wibek** [comment]
Scale: 100%
Resolution: 1920x1080

DPI mode: per-monitor v2
startup, version: 2046 windows x64
executable: /C/Program Files/Sublime Merge/sublime_merge.exe
application: /C/Program Files/Sublime Merge
working dir: /C/Program Files/Sublime Merge
packages path: /C/Users/xxx/AppData/Roaming/Sublime Merge/Packages
state path: /C/Users/xxx/AppData/Roaming/Sublime Merge/Local
zip path: /C/Program Files/Sublime Merge/Packages
zip path: /C/Users/xxx/AppData/Roaming/Sublime Merge/Installed Packages
ignored_packages: ["Vintage"]
generating syntax summary
generating meta info summary
pre session restore time: 1.37811
OpenGL Context Information:
  GL API Version: 4.3.0 - Build 20.19.15.4835
  GLSL Version: 4.30 - Build 20.19.15.4835
  Vendor: Intel
  Renderer: Intel(R) HD Graphics 4600
loading repo xxx/.git
loading dictionary Packages/Language - English/en_US.dic
head changed to 7896429b7fdca6d419b1bd559ba871651cb67613
first paint time: 1.66511
font face "Times" could not be used with direct write, using gdi instead

**Comment by wibek** [comment]
I can confirm that disabling OpenGL resolves this offset bug.

(I'm still not fond of the new menu structure, but that's another issue. ;-)

**Comment by aleksandr-bit1** [comment]
Scale: 100%
Resolution: 1920x1080

PI mode: per-monitor v2
startup, version: 2047 windows x64
executable: /C/Program Files/Sublime Merge/sublime_merge.exe
application: /C/Program Files/Sublime Merge
working dir: /C/Program Files/Sublime Merge
packages path: /C/Users/ххх/AppData/Roaming/Sublime Merge/Packages
state path: /C/Users/ххх/AppData/Roaming/Sublime Merge/Local
zip path: /C/Users/хх/AppData/Roaming/Sublime Text 3/Installed Packages
zip path: /C/Program Files/Sublime Merge/Packages
zip path: /C/Users/Alexander.Bityutskov/AppData/Roaming/Sublime Merge/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.278032
OpenGL Context Information:
  GL API Version: 4.4.0 - Build 20.19.15.4531
  GLSL Version: 4.40 - Build 20.19.15.4531
  Vendor: Intel
  Renderer: Intel(R) HD Graphics 5500
loading repo ххх.git
loading dictionary Packages/Language - English/en_US.dic
head changed to 4677c16005bacff62d89ff78c558acc9c00bf852
first paint time: 0.642032

**Comment by dns13** [comment]
Scale: 100%
Resoultion: 2560x1440
(but is also happening on second screen: 100% scale / 1920x1080)

```
DPI mode: per-monitor v2
startup, version: 2047 windows x64
executable: /C/Program Files/Sublime Merge/sublime_merge.exe
application: /C/Program Files/Sublime Merge
working dir: /C/Program Files/Sublime Merge
packages path: /C/Users/xxx/AppData/Roaming/Sublime Merge/Packages
state path: /C/Users/xxx/AppData/Roaming/Sublime Merge/Local
zip path: /C/Users/xxx/AppData/Roaming/Sublime Text 3/Installed Packages
zip path: /C/Program Files/Sublime Merge/Packages
zip path: /C/Users/xxx/AppData/Roaming/Sublime Merge/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.149333
OpenGL Context Information:
  GL API Version: 4.3.0 - Build 20.19.15.5126
  GLSL Version: 4.30 - Build 20.19.15.5126
  Vendor: Intel
  Renderer: Intel(R) HD Graphics 4600
loading repo /C/Users/xxx/git/xxx/.git
loading dictionary Packages/Language - English/en_US.dic
head changed to 32334f01d0d69b01f8a79e8b4050a514bd17c5aa
first paint time: 0.440333
```

**Comment by c17r** [comment]
Windows 10 Pro, Build 18363

Happens on all 3 monitors
1920x1080, 100%
2560x1440, 100%
1440x2560, 100%

```
DPI mode: per-monitor v2
startup, version: 2047 windows x64
executable: /C/Program Files/Sublime Merge/sublime_merge.exe
application: /C/Program Files/Sublime Merge
working dir: ##############################
packages path: /C/Users/cs/AppData/Roaming/Sublime Merge/Packages
state path: /C/Users/cs/AppData/Roaming/Sublime Merge/Local
zip path: /C/Users/cs/AppData/Roaming/Sublime Text 3/Installed Packages
zip path: /C/Program Files/Sublime Merge/Packages
zip path: /C/Users/cs/AppData/Roaming/Sublime Merge/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.498862
OpenGL Context Information:
  GL API Version: 4.3.0 - Build 20.19.15.5126
  GLSL Version: 4.30 - Build 20.19.15.5126
  Vendor: Intel
  Renderer: Intel(R) HD Graphics 4600
loading repo ##############################
loading dictionary Packages/Language - English/en_US.dic
first paint time: 0.913862
head changed to 96e3560b15ab1baa41a1aa23dae6ba81187cd3fc
```

**Comment by wbond** [comment]
If someone experiencing this was willing to try out a build, could you jump on our Discord server and message me there? https://discord.gg/HcmwdVK

**Comment by wbond** [comment]
Unfortunately this appears to be an Intel OpenGL driver bug that affects 4xxx series cards on Windows when custom non-client areas are drawn.

The two possible workarounds are:
 - Turn off Hardware Acceleration in *Preferences > Advanced*
 - Turn off Themed Title Bar in *Preferences > Layout*

We tried a number of workaround in source code, but none of them were fruitful.

**Comment by vincent-blyat** [comment]
Turning off hardware acceleration fixed the issue.
