### ISSUE TITLE
Tags are not foldable like other refs

### ISSUE THREAD

**Issue by n8gray** [sublimehq/sublime_merge#107]
**Problem description**

Tag names are not tree-structured and foldable on `/` like branches are.  Our CI system generates tags that we use for various purposes.  We put them under `t/` so we can easily hide them in most git interfaces.  SM doesn't offer folding for tags, so it's very difficult to use it to manage tags.

**Preferred solution**

Use the same interface idiom for tags that is used for branches.

**Alternatives**

IDK, scroll through thousands of auto-generated CI system tags to find the tag I need?

**Screenshots**

<img width="198" alt="screen shot 2018-10-11 at 11 04 56 am" src="https://user-images.githubusercontent.com/82794/46824376-84d83700-cd45-11e8-853c-d8564b94d0de.png">

**Comment by jskinner** [comment]
Added in Dev Build 1080
