### ISSUE TITLE
Commit Message with URL highlight too greed

### ISSUE THREAD

**Issue by voltechs** [sublimehq/sublime_merge#1073]
**Version info**

 - OS: macOS 10.15.7
 - Build: 2046

**Description**

When putting a URL in the commit message, it highlights (colors blue), but captures the trailing parenthesis

**Steps to reproduce**

1. Make changes
2. Create Commit message with URL in parenthesis

**Expected behavior**

End parenthesis looks like beginning parenthesis

**Screenshots**

<img width="491" alt="Screen Shot 2021-02-25 at 10 10 30" src="https://user-images.githubusercontent.com/1700514/109228333-e797c500-777e-11eb-9f02-e2578c4d551e.png">

**Comment by dpjohnst** [comment]
Hi @voltechs,

Thanks for sharing this feedback - this has been resolved in the latest dev build (2076).

Kind regards,
\- Dylan
