### ISSUE TITLE
Pressing TAB in the command pallet write a \t character

### ISSUE THREAD

**Issue by ineol** [sublimehq/sublime_merge#1075]
**Version info**

 - OS: ubuntu 20.10
 - Build: 2047

**Description**

In the command palet, mistakenly pressing the tab key writes a tab character instead of doing nothing (or acting like Enter)

**Steps to reproduce**

1. Open repository ...
2. Run command `Add remote`
3. For the name of the remote press the keys f, o, o, TAB
4. Realize you were supposed to press enter to validate
5. Press enter
5. Write the url of the remote and press Enter

**Actual behavior**

Git error saying that `"foo\t"` is not a correct name for a remote.

**Expected behavior**

A new remote with name `foo` is added because pressing TAB would have been a noop.

**Comment by dpjohnst** [comment]
Hi @ineol,

Thanks for sharing this feedback - we'll be looking to improve this experience.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @ineol,

A quick update - this has been resolved as of Sublime Merge Build 2054 (stable).

Thanks,
\- Dylan
