### ISSUE TITLE
Previous Commit Message Removes CFLF and Concatenates Two Words Without Spaces

### ISSUE THREAD

**Issue by michaelalandawson** [sublimehq/sublime_merge#1076]
**Version info**

 - OS: Windows 10
 - Build: 2046

**Description**

The previous *multi-line* commit message popup removes the CRLF character(s) but doesn't replace them with a space.  (See screenshot below.)

**Steps to reproduce**

1. Create a commit message that spans multiple lines.
2. Commit.
3. Open the previous commit message popup.
4. Notice that there is no space between the last word of the first line and the first word of the last line.

**Expected behavior**

Add a space, or other delimiting character, between the lines.

**Screenshots**

In the following example, the commit message was:
```
Restrict CFML snippet scopes
Prevent the snippets from triggering within incompatible scopes.
```

![sublime-merge-previous-commit-spacing](https://user-images.githubusercontent.com/39276677/109359158-97863480-784a-11eb-8ee3-4b381de9b4c6.png)

**Comment by dpjohnst** [comment]
Hi @michaelalandawson,

Thank you for reporting this issue - we'll be investigating this further.

Kind regards,
\- Dylan

**Comment by michaelalandawson** [comment]
Hello @dpjohnst 

It appears the display of the commit message history no longer shows subsequent lines of the commit message.  Thank you for fixing that.

It appears the fix may have caused another issue.  When I select a multi-line commit message from the history list, it will only retrieve the first line of the commit message.  Previously, it would retrieve the entire commit message.

Thanks!

**Comment by dpjohnst** [comment]
Hi @michaelalandawson,

This should all be resolved as of Sublime Merge build 2054 (stable).

Thanks,
\- Dylan
