### ISSUE TITLE
ssh: Permission denied (publickey) on Windows

### ISSUE THREAD

**Issue by a-komarov-playrix** [sublimehq/sublime_merge#1082]
**Version info**

 - OS: Windows 7/10
 - Build: 2047

**Description**

ssh was set up, ssh-agent is up and running, but pull and push return the same error:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Steps to reproduce**

1. Create ssh key, store it in non-default place like `~/.ssh/my_key_1/id_rsa`
2. Set up ssh auth on github, clone repo via ssh
2. Run ssh-agent (`ssh-agent -s`)
3. Add private key (`ssh-add ~/.ssh/my_key_1/id_rsa`)
4. Create system env variables `SSH_AUTH_SOCK` and `SSH_AGENT_PID`, set values from ssh-agent
5. Open new instance of cmd and test ssh connection: `ssh -T git@github.com`
`Hi %user%! You've successfully authenticated, but GitHub does not provide shell access.`
6. cd to repo, try to pull: `git pull --rebase` (everything works fine)
7. Open Sublime Merge, click pull button
8. Receive error:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Expected behavior**

8. Pull in Sublime Merge succeeds.

Looks like Sublime Merge doesn't read ssh-related environmental variables and also starts git and ssh in its own sandbox without access to these variables.

**Comment by dpjohnst** [comment]
Hi @a-komarov-playrix,

Thanks for reporting - could you confirm whether you are using the system Git or bundled Git with Sublime Merge?
You can view this information via `Preferences > Preferences... > Advanced` in Sublime Merge

Additionally, would you mind sharing the Sublime Merge debug information. This can be accessed via `Help > Debug Information`. Before sending, take a moment to strip it of any information you feel is sensitive.

Kind regards,
\- Dylan

**Comment by a-komarov-playrix** [comment]
Hi @dpjohnst 

Both bundled git and system git work the same way. I tried "system", "git" and empty field in Preferences. The same goes to ssh field.

<details> 
  <summary>Debug information</summary>

```
=== App Version Information ===
Build: 2047

=== Git Version Information ===
Using Git: M:\bin\SublimeMerge\Git\cmd\git.exe (bundled)
git version 2.29.2.windows.2
PATH: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\UCRT\;C:\Program Files\Intel\UCRT\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;c:\Program files\git\bin;C:\Program Files\TortoiseGit\bin;C:\Windows\system32\wbem

=== Browse Page Information ===
HEAD: 71799f0bb8c56b3835895b51a580c5ce70fce104
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===

=== Git Config Information ===
branch.main.merge=refs/heads/main
branch.main.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager
diff.astextplain.textconv=astextplain
fetch.prune=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
help.format=html
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
include.path=C:/Program Files/Git/etc/gitconfig
pack.packsizelimit=2g
pull.rebase=true
push.recursesubmodules=check
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@github.com:repository.git
submodule.fetchjobs=4
user.email=something@something.com
user.name=user

=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /M/bin/SublimeMerge/Git/etc/gitconfig
Using config path: /C/Users/user/.config/git/config
Using config path: /C/Users/user/.gitconfig
Using config path: /M/Prog/repository/.git/config

Our config output is different to the Git config output
branch.main.merge=refs/heads/main
branch.main.remote=origin
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager
diff.astextplain.textconv=astextplain
fetch.prune=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
pull.rebase=true
push.recursesubmodules=check
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@github.com:repository.git
submodule.fetchjobs=4
user.email=something@something.com
user.name=user

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 1

```
</details>

**Comment by dpjohnst** [comment]
Hi @a-komarov-playrix,

Thank you for the additional information.

How are you setting the system environment variables? Are you setting them in your command prompt / terminal instance, or via Windows Explorer?

Additionally, does the issue resolve if you start Sublime Merge via the terminal (i.e. `smerge`). If the `smerge` command doesn't work, see: https://www.sublimemerge.com/docs/command_line

Thanks,
\- Dylan

**Comment by a-komarov-playrix** [comment]
I set in cmd via setx command.

Whoa! I tried smerge from cmd and it worked! Then I started sublime_merge.exe from Windows Explorer - and it worked too. Seems like this bug is for Wox startup manager.

Thanks for help!
