### ISSUE TITLE
Blame line-by-line history tooltip doesn't update when moving cursor diagonally to the left

### ISSUE THREAD

**Issue by stevenre3d** [sublimehq/sublime_merge#1083]
**Version info**

 - OS: Windows 10, 20H2
 - Build: 2047

**Description**

When scanning your cursor up and down over the line-by-line commit history in the git blame view, the tooltips showing commit info only shows up if your cursor is moving slightly left-to-right. If you are moving with a right-to-left bias, the tooltip for a different line will continue to be rendered.

**Steps to reproduce**

1. Open repository ...
2. Use Ctrl+Shift+P to run "Blame..."
3. Select any file with a lot of different commits
4. Move your cursor up and down the left edge of the file, over the commit hash prefixes.
5. Sometimes move your cursor diagonally up and to the left/down and to the left/up and to the right/down and to the right.
6. Note that the hover tooltip only updates when moving up/down and to the right. When up/down and to the left, the tooltip that is already showing for a previous line continues to be shown.

**Expected behavior**

As your cursor enters a new commit range, a new hover tip should always appear corresponding to the commit you are currently over.

**Screenshots**

Attached short video. Note when moving left-to-right, the tooltips are responsive and quick, but when moving right-to-left the tooltips seem unresponsive and intermittent.

https://user-images.githubusercontent.com/1539059/110190475-535ddb80-7dd8-11eb-9c9a-2cb20acc8d91.mp4

**Comment by dpjohnst** [comment]
Hi @stevenre3d,

Thank you for reporting this issue - this will be resolved in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Just a quick update that this has been resolved as of Sublime Merge Build 2054 (stable).

Thanks,
\- Dylan
