### ISSUE TITLE
Issue with %Path% on Windows

### ISSUE THREAD

**Issue by poldi1405** [sublimehq/sublime_merge#1087]
**Version info**

 - OS: Windows 10
 - Build: 2047

**Description**

It seems SMerge has issues working with the path variable in windows. It cannot find commands that both git-bash and pwsh find.

![photo5352938163754086795](https://user-images.githubusercontent.com/33086936/110638462-82909600-81a6-11eb-9ce8-fcc63abd3af5.jpg)

**Steps to reproduce**

1. Add git-hook
2. try to commit

**Expected behavior**

The Hook works as expected

**The hook**

Just a basic check:
![20210310_14h47m05s_grim](https://user-images.githubusercontent.com/33086936/110639503-b1f3d280-81a7-11eb-8867-05f1500acee0.png)

**Comment by dpjohnst** [comment]
Hi @poldi1405,

Thank you for reaching out to the Sublime Merge team.

Sublime Merge loads the PATH variable defined in the system environment variables.
To begin, could you try opening Sublime Merge and share the debug information here.
This can be accessed via: `Help > Debug Information`

Before sharing, feel free to remove any output you feel is sensitive in nature (i.e. email addresses, paths etc)

Additionally, could you open powershell and share the output of `$env:PATH`

Thanks,
\- Dylan

**Comment by poldi1405** [comment]
<details>
<summary>Debug Information</summary>
<pre>
<code>
=== App Version Information ===
Build: 2047

=== Git Version Information ===
Using Git: C:\Program Files\Sublime Merge\Git\cmd\git.exe (bundled)
git version 2.29.2.windows.2
PATH: C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\WireGuard\;C:\Program Files\FileBot\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Go\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\Jannik Tappert\go\bin;C:\Program Files\Git\usr\bin;C:\Users\Jannik Tappert\.dotnet\tools;C:\Program Files\JetBrains\PhpStorm 2020.2.3\bin;;C:\Users\Jannik Tappert\AppData\Local\Pandoc\;C:\Users\Jannik Tappert\go\bin;D:\Jannik\Desktop\endoclean-api;C:\Program Files (x86)\GnuWin32;C:\Users\Jannik Tappert\AppData\Roaming\npm;C:\Users\Jannik Tappert\AppData\Local\Yarn\bin;C:\winbuilds\bin;D:\Jannik\Desktop\MESO\EndoCleanWorkflow\endoclean-database;C:\Program Files\JetBrains\GoLand 2020.3.1\bin;;D:\Jannik\Desktop\MESO\EndoCleanWorkflow\endoclean-api;

=== Browse Page Information ===
HEAD: 14881d7126309ad355f3a974e215e1619b8ba85d
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===
?? testbinary/test.db-journal

=== Our Status Information ===
?? testbinary/test.db-journal

=== Git Config Information ===
branch.2232.merge=refs/heads/2232
branch.2232.remote=origin
branch.develop.merge=refs/heads/develop
branch.develop.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
commit.gpgsign=true
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=true
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
help.format=html
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslverify=false
include.path=C:/Program Files/Git/etc/gitconfig
init.defaultbranch=master
pack.packsizelimit=2g
pull.rebase=false
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://git.mw.local/EndoClean/endoclean-database.git
user.email=jt@meso.biz
user.name=Jannik Tappert
user.signingkey=166310A62CD7811E39A7CDDA2865F3BEC1C7C656

=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /C/Program Files/Sublime Merge/Git/etc/gitconfig
Using config path: /C/Users/Jannik Tappert/.config/git/config
Using config path: /C/Users/Jannik Tappert/.gitconfig
Using config path: /D/Jannik/Desktop/MESO/EndoCleanWorkflow/endoclean-database/.git/config

Our config output is identical to the Git config output

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 0
</code>
</pre>
</details>

<details>
<summary>Powershell (as User)</summary>
<pre>
<code>
PS C:\Users\Jannik Tappert> $env:PATH
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\WireGuard\;C:\Program Files\FileBot\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Go\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\Jannik Tappert\go\bin;C:\Program Files\Git\usr\bin;C:\Users\Jannik Tappert\.dotnet\tools;C:\Program Files\JetBrains\PhpStorm 2020.2.3\bin;;C:\Users\Jannik Tappert\AppData\Local\Pandoc\;C:\Users\Jannik Tappert\go\bin;D:\Jannik\Desktop\endoclean-api;C:\Program Files (x86)\GnuWin32;C:\Users\Jannik Tappert\AppData\Roaming\npm;C:\Users\Jannik Tappert\AppData\Local\Yarn\bin;C:\winbuilds\bin;D:\Jannik\Desktop\MESO\EndoCleanWorkflow\endoclean-database;C:\Program Files\JetBrains\GoLand 2020.3.1\bin;;D:\Jannik\Desktop\MESO\EndoCleanWorkflow\endoclean-api;
</code>
</pre>
</details>

<details>
<summary>Powershell (as Admin)</summary>
<pre>
<code>
PS C:\WINDOWS\system32> $env:PATH
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\WireGuard\;C:\Program Files\FileBot\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Go\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\Jannik Tappert\go\bin;C:\Program Files\Git\usr\bin;C:\Users\Jannik Tappert\.dotnet\tools;C:\Program Files\JetBrains\PhpStorm 2020.2.3\bin;C:\Users\Jannik Tappert\AppData\Local\Pandoc\;D:\Jannik\Desktop\endoclean-api;C:\Program Files (x86)\GnuWin32;C:\Users\Jannik Tappert\AppData\Roaming\npm;C:\Users\Jannik Tappert\AppData\Local\Yarn\bin;C:\winbuilds\bin;D:\Jannik\Desktop\MESO\EndoCleanWorkflow\endoclean-database;C:\Program Files\JetBrains\GoLand 2020.3.1\bin;D:\Jannik\Desktop\MESO\EndoCleanWorkflow\endoclean-api
</code>
</pre>
</details>

**Comment by dpjohnst** [comment]
Hi @poldi1405,

It looks as if you have `C:\Users\Jannik Tappert\go\bin;` defined as a user environment variable.
If I'm not mistaken, this won't get picked up if you run Sublime Merge as an administrator (or different user).

I would suggest adding `C:\Users\Jannik Tappert\go\bin;` to your system-level PATH and see if this resolves the issue.
If you're unsure how to do this, see: https://www.computerhope.com/issues/ch000549.htm#windows10

Kind regards,
\- Dylan

**Comment by poldi1405** [comment]
It's already in there… at least according to the "Edit environment" (which matches the pwsh-as-admin-output)

**Comment by dpjohnst** [comment]
Hi @poldi1405,

My apologies - you're correct. I'll be investigating this issue further - stay tuned.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @poldi1405,

Could you please confirm where you have go installed? 
i.e. is it installed under `C:\Program Files\Go\bin`

Kind regards,
\- Dylan

**Comment by poldi1405** [comment]
I can confirm that go is installed. However it is under `C:\Go\bin\go.exe` which is also in the PATH

**Comment by dpjohnst** [comment]
Hi @poldi1405,

Could you try switching to `System` Git in Sublime Merge?
This can be done via `Preferences > Preferences.. > Advanced > Git Binary`

Additionally, could you add `echo $PATH` to the top of your pre-commit hook to see what `$PATH` resolves to when executing the pre-commit hook.

Thanks,
\- Dylan

**Comment by poldi1405** [comment]
That circumvented the issue successfully.

Not sure whether to close this issue though. We got it working so I'm fine but the reason has to be something.

**Comment by poldi1405** [comment]
I'll just close it.
