### ISSUE TITLE
Dev Build 2048 does not have a valid developer identity

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#1090]
**Version info**

 - OS: macOS 10.14
 - Build: 2048

**Description**

Build 2048 fails the developer identity check from Gatekeeper.

**Steps to reproduce**

1. Open Sublime Merge on macOS Mojave (possibly others)

**Expected behavior**

Sublime Merge opens.

**Screenshots**

![Screen Shot 2021-03-11 at 21 06 24](https://user-images.githubusercontent.com/297298/110886089-a8ed2900-82ad-11eb-8909-ae631ab820a5.png)

**Comment by dpjohnst** [comment]
Hi @srbs,

Thanks for reporting this issue - this should now be resolved.

Kind regards,
\- Dylan

**Comment by jskinner** [comment]
Well, it should be resolved for 2049 (in the stable channel), but won't be resolved for the dev channel until the next build.

Also, just to reiterate Dylan, thanks for your reports @srbs, you rock!

**Comment by srbs** [comment]
Y'all are very welcome! I love both ST & SM and am happy to help, you guys rock too!
