### ISSUE TITLE
can't select the `Create tag` option while trying to close a hotfix branch

### ISSUE THREAD

**Issue by AhmedKamal20** [sublimehq/sublime_merge#1092]
**Version info**

 - OS: Ubuntu 20.04
 - Build: 2047

**Description**

I can't select the `Create tag` option while trying to close a hotfix branch

**Steps to reproduce**

1. Open repository
2. Run command: `Git Flow: Start Hotfix Branch`
3. Run command: `Git Flow: Finish Hotfix Branch`
4. Try to click `Create tag` Option

**Expected behavior**

`Create tag` Option is added to the command. 

**Screenshots**

![image](https://user-images.githubusercontent.com/14352372/111072973-91988080-84e5-11eb-8532-a29e9dd3ef64.png)

**Comment by dpjohnst** [comment]
Hi @AhmedKamal20,

Thank you for reporting this - this is not actually an entry in a list, but just a preview of what the command is doing.

That being said, this message clearly isn't very useful in this scenario, and isn't very descriptive.
We'll look into improving the language used in this preview.

Thanks,
\- Dylan

**Comment by AhmedKamal20** [comment]
@dpjohnst Thanks for the reply

> this is not actually a clickable entry in a list, but just a preview of what the command is doing.

Ok, but the thing is, it **doesn't** create the tag
here is an example, I selected the release branch and hit enter
![image](https://user-images.githubusercontent.com/14352372/111488204-b4bf6c00-8741-11eb-9c66-59a6d934259f.png)

It say --no-tag

**Comment by cachitas** [comment]
I can confirm that finishing a hotfix does not create a tag
I also noticed that instead of merging from the hotfix branch to dev, it merged from main to dev.
![Screenshot from 2021-04-16 23-53-41](https://user-images.githubusercontent.com/2321514/115091565-bda58800-9f0f-11eb-8aaa-c247ae41e5ff.png)

**Comment by dpjohnst** [comment]
Hi @AhmedKamal20,

Just to confirm, did you provide a message for the tag?
The tag will only be created if a tag message is provided.

If no message is provided, the `--notag` flag will be passed.

Thanks,
\- Dylan

**Comment by AhmedKamal20** [comment]
Oops, my bad,  I tried it now and filled the tag message, the tag is created now

thank you
