### ISSUE TITLE
Sublime Merge version 2049 can't pull or push

### ISSUE THREAD

**Issue by DemonDeLaplace513** [sublimehq/sublime_merge#1093]
**Version info**

 - OS: Windows 10
 - Build: 2049
 
**Description**

When I upgrade from version 2047 to version 2049, I can't even pull or push. When I uninstall version 2049, there is no problem switching back to version 2047.

**Steps to reproduce**

1. upgrade to version 2049
2. pull 

**Tips**

remote: The project you were looking for could not be found.
fatal: repository 'https://xxxx.git/' not found

**Comment by dpjohnst** [comment]
Hi @DemonDeLaplace513,

The error message provided looks as if it's failing to resolve the repository on the remote server.
Sublime Merge Build 2049 upgraded the bundled Git to the latest version, so the remote service may have incompatibilities with this version.

To start, would you mind sharing your debug information from Sublime Merge? This can be accessed via `Help > Debug Information`. Before sharing, take a moment to redact any information you feel is sensitive (file paths, email addresses etc).

Additionally, are you authenticating via GitLab?
There seems to be an existing issue with GitLab authentication: https://forum.gitlab.com/t/how-to-fix-the-project-you-were-looking-for-could-not-be-found-when-using-git-clone/47113

Kind regards,
\- Dylan

**Comment by DemonDeLaplace513** [comment]
Hi @dpjohnst ,

Yes, I am using gitLab.
I tried the solution for this connection. Although I entered the correct password, it still prompted an error.

**Tips:**
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.xxxxx.git/'


**The following is debugInfo**

=== App Version Information ===
Build: 2049

=== Git Version Information ===
Using Git: D:\xxx\Sublime Merge\Git\cmd\git.exe (bundled)
git version 2.30.2.windows.1
PATH: D:\software\Python38\Scripts\;D:\software\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Lua\5.1\clibs;C:\Program Files (x86)\Lua\5.1;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;D:\software\Git\cmd;C:\Program Files (x86)\Corona Labs\Corona\Native\Corona\win\bin;D:\software\minGW\bin;D:\software\Corona\Native\Corona\win\bin;D:\software\Java\jdk-12.0.1\bin;D:\software\Java\jdk-12.0.1\jre\bin;D:\software\TortoiseGit\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\software\Android-sdk\platform-tools;D:\GOS_SERVER\bin;D:\software\nodejs\;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;;D:\software\IntelliJ IDEA 2019.1.2\bin;D:\software\Fiddler;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;%GOPATH%\bin;C:\Users\admin\AppData\Roaming\npm

=== Browse Page Information ===
HEAD: xxx
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===


=== Our Status Information ===


=== Git Config Information ===
alias.lg=log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
branch.master.merge=refs/heads/master
branch.master.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
color.ui=true
core.autocrlf=true
core.bare=false
core.filemode=false
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager-core
diff.astextplain.textconv=astextplain
diff.tool=bc
difftool.bc.path=D:/xxxx/Beyond Compare 4/bcomp.exe
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
gui.geometry=841x483+234+234 189 218
gui.wmstate=normal
help.format=html
include.path=C:/Program Files/Git/etc/gitconfig
merge.tool=bc
mergetool.bc.path=D:/software/Beyond Compare 4/bcomp.exe
mergetool.bc4.cmd="D:\software\Beyond Compare 4/BCompare.exe" "" "" "" ""
mergetool.bc4.path=D:\software\Beyond Compare 4\BCompare.exe
mergetool.bc4.trustexitcode=true
mergetool.keepbackup=false
pack.packsizelimit=2g
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=xxxxxxx
submodule.debugUtils.active=true
submodule.debugUtils.url=xxxxxxxx
user.email=xxxxx@xxxx.com
user.name=xxxxx

=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /D/xxxx/Sublime Merge/Git/etc/gitconfig
Using config path: /C/Users/admin/.config/git/config
Using config path: /C/Users/admin/.gitconfig
Using config path: /D/xxxx/xxx/.git/config

Our config output is different to the Git config output
alias.lg=log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
branch.master.merge=refs/heads/master
branch.master.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
color.ui=true
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager-core
diff.astextplain.textconv=astextplain
diff.tool=bc
difftool.bc.path=D:/xxxxx/Beyond Compare 4/bcomp.exe
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
gui.geometry=841x483+234+234 189 218
gui.wmstate=normal
help.format=html
include.path=C:/Program Files/Git/etc/gitconfig
merge.tool=bc
mergetool.bc.path=D:/xxxx/Beyond Compare 4/bcomp.exe
mergetool.bc4.cmd="D:\xxxx\Beyond Compare 4/BCompare.exe" "" "" "" ""
mergetool.bc4.path=D:\xxxxx\Beyond Compare 4\BCompare.exe
mergetool.bc4.trustexitcode=true
mergetool.keepbackup=false
pack.packsizelimit=2g
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=xxxxx.git
submodule.debugUtils.active=true
submodule.debugUtils.url=xxxxx
user.email=xxxxx@xxxx.com
user.name=xxxxx

=== Git Attributes Information ===
git check_attr --all output


=== Our Modified Files Newline Normalisation and EOL Information ===


=== Our Modified Files Flag Information ===


thank you for your reply.

**Comment by dpjohnst** [comment]
Hi @DemonDeLaplace513,

Thanks for the additional information.

Could you try switching to System Git via `Preferences > Preferences... > Advanced > Git Binary` and see if this resolves the issue?

Kind regards,
\- Dylan

**Comment by DemonDeLaplace513** [comment]
Hi @dpjohnst ,

Thank you for your help,I set the git path to the one I installed, and it works.
Select system will prompt：CreateProcess failed.
It may be that I haven't set it up

thx.

**Comment by dpjohnst** [comment]
Hi @DemonDeLaplace513,

Thank you for the additional information and glad its working on your end. Would you mind sharing your debug information once more now that the new binary is enabled?

I'd like to investigate why this isn't working with the bundled Git binary.

Thanks,
\- Dylan

**Comment by DemonDeLaplace513** [comment]
Hi @dpjohnst ,

Happy to provide you with information.

**The following is the new debugInfo**

=== App Version Information ===
Build: 2049

=== Git Version Information ===
Using Git: D:\software\Git\bin\git.exe (custom)
git version 2.21.0.windows.1
PATH: D:\software\Python38\Scripts\;D:\software\Python38\;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Lua\5.1\clibs;C:\Program Files (x86)\Lua\5.1;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;D:\software\Git\cmd;C:\Program Files (x86)\Corona Labs\Corona\Native\Corona\win\bin;D:\software\minGW\bin;D:\software\Corona\Native\Corona\win\bin;D:\software\Java\jdk-12.0.1\bin;D:\software\Java\jdk-12.0.1\jre\bin;D:\software\TortoiseGit\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\software\Android-sdk\platform-tools;D:\GOS_SERVER\bin;D:\software\nodejs\;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;;D:\software\IntelliJ IDEA 2019.1.2\bin;D:\software\Fiddler;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;%GOPATH%\bin;C:\Users\admin\AppData\Roaming\npm

=== Browse Page Information ===
HEAD: xxxx
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===


=== Our Status Information ===


=== Git Config Information ===
alias.lg=log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
branch.master.merge=refs/heads/master
branch.master.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
color.ui=true
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager
diff.tool=bc
difftool.bc.path=D:/software/Beyond Compare 4/bcomp.exe
gui.geometry=841x483+234+234 189 218
gui.wmstate=normal
help.format=html
http.sslbackend=openssl
http.sslcainfo=D:/software/Git/mingw64/ssl/certs/ca-bundle.crt
merge.tool=bc
mergetool.bc.path=D:/software/Beyond Compare 4/bcomp.exe
mergetool.bc4.cmd="D:\software\Beyond Compare 4/BCompare.exe" "" "" "" ""
mergetool.bc4.path=D:\software\Beyond Compare 4\BCompare.exe
mergetool.bc4.trustexitcode=true
mergetool.keepbackup=false
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=xxxx
submodule.debugUtils.active=true
submodule.debugUtils.url=xxxxx
user.email=xxxxx@xxxx.com
user.name=xxxx

=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /D/software/Git/mingw64/etc/gitconfig
Using config path: /C/Users/admin/.config/git/config
Using config path: /C/Users/admin/.gitconfig
Using config path: /D/GOS_Client/gos/.git/config

Our config output is different to the Git config output
alias.lg=log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
branch.master.merge=refs/heads/master
branch.master.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
color.ui=true
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager-core
diff.astextplain.textconv=astextplain
diff.tool=bc
difftool.bc.path=D:/software/Beyond Compare 4/bcomp.exe
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
gui.geometry=841x483+234+234 189 218
gui.wmstate=normal
help.format=html
include.path=C:/Program Files/Git/etc/gitconfig
merge.tool=bc
mergetool.bc.path=D:/software/Beyond Compare 4/bcomp.exe
mergetool.bc4.cmd="D:\software\Beyond Compare 4/BCompare.exe" "" "" "" ""
mergetool.bc4.path=D:\software\Beyond Compare 4\BCompare.exe
mergetool.bc4.trustexitcode=true
mergetool.keepbackup=false
pack.packsizelimit=2g
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=xxxx
submodule.debugUtils.active=true
submodule.debugUtils.url=xxxxx
user.email=xxxxx@xxxx.com
user.name=xxxxx

=== Git Attributes Information ===
git check_attr --all output


=== Our Modified Files Newline Normalisation and EOL Information ===


=== Our Modified Files Flag Information ===
Ignoring symlinks: 1
