### ISSUE TITLE
Diff option to ignore space

### ISSUE THREAD

**Issue by TheClams** [sublimehq/sublime_merge#11]
**Problem description**

A common option in most diff tools is the ability to hide/ignore space related difference.

**Preferred solution**

It would be good to have this in the preference option, but also the ability to toggle it on a file by file basis.
Also it would be great in the list of file modified in a commit if we could have an indicator that changes are space only (similar to the one for renaming).

**Alternatives**

An extra option that would clearly put sublime merge on top of any other diff tool is the same concept but apply to comments, since SublimeMerge support syntax highlighting: 
 - ability to hide any change inside a comment
 - quick toggle mode
 - indicator in the list of modified files.

And other diff display option would include:
 - control how many "context" line are displayed for each diff (unomidifed line before and after a change)
 - Option to show whole file
 - Hide only trailing space/empty
 - Quick navigation between changes

**Screenshots**

Here is an ugly mockup using icons bar from GitExtension diff:
![diff_option](https://user-images.githubusercontent.com/5270125/46188171-ce596880-c2e7-11e8-8880-60f433bfffba.png)

**Comment by jskinner** [comment]
Whitespace can now be ignored in 1080

**Comment by AliAskari** [comment]
@jskinner, I am running build 1085 and this is what I get when I try to ignore whitespaces:

![image](https://user-images.githubusercontent.com/4864412/48012723-a59b6e80-e0f0-11e8-94c2-8ab5475adb6b.png)

How can I know if the whitespaces are ignored or not? The toggle doesn't show the current state.

Moreover, it would much much easier/useful if it was added to the diff window, something like the mockup that @TheClams has created. It's not really user friendly to go to settings and change this for different commits.

**Comment by jskinner** [comment]
You can also toggle ignore whitespace from the diff context menu
