### ISSUE TITLE
Merge slows down entire computer

### ISSUE THREAD

**Issue by tfiers** [sublimehq/sublime_merge#1110]
**Version info**

 - OS: Windows 10
 - Build: 2049

**Description**

Having Merge open slows down the entire laptop after a while (mouse becomes janky, typing in other apps becomes slow, ..).
Closing Merge immediately solves the issue.
Laptop is modern (i7, 16GB RAM, SSD).
There doesn't seem to be excessive memory or CPU usage by Merge during such slowdowns.

**Steps to reproduce**

1. Open Merge
2. Use app a bit
(Make some commits, edit commit messages, amend, view diffs & blames, view old trees, ..)
Repo contains nothing out of the ordinary and is in fact quite small and young (https://github.com/tfiers/copylot).
3. Wait (about 15'?)

**Expected behavior**

No slow down of OS.

(another bug, maybe related: shortcuts like Ctrl-Enter to edit old commit message don't work).

**Comment by stinos** [comment]
> 2. Use app a bit
> 3. Wait (about 15'?)

Do you mean there's only a slowdown after 15' ? Not before that? And does it not happen if you skip step 2?

> like Ctrl-Enter to edit old commit message don't work

With *like* do you mean there are others which do not work? Which ones?

Note that there is a difference between 'enter' and 'return' keys unfortunately SM only accepts one of them for Ctrl-Enter, you might be using the other one?

**Comment by dpjohnst** [comment]
Hi @tfiers ,

Thanks for reporting this issue.

We've recently fixed a memory issue in Sublime Merge on Windows.
When you have a spare moment, could you install the latest build of Sublime Merge and confirm if the issue is resolved on your end?

Thanks,
\- Dylan

**Comment by tfiers** [comment]
Hi @stinos, thanks for the prompt reply, and @dpjohnst, for following up.
I'll check when I run it again and let you know here if it still happens.
