### ISSUE TITLE
Spellchecker for non-american EN functions poorly

### ISSUE THREAD

**Issue by Amparose** [sublimehq/sublime_merge#1114]
**Version info**

 - OS: macOS 11.2.3 
 - Build: 2049

**Description**

Added `English (Australian).dic` to packages hoping to make the commit message spellchecker not suck and instead it made it suck more. Also, can this not be a feature the app handles instead of messing around with package files and config scripts?

**Steps to reproduce**

Follow [these instructions](https://forum.sublimetext.com/t/solved-spell-check-for-other-language-possible/39538/3).

**Expected behavior**

A better commit message spell checker for Australian English.

**Screenshots**

<img width="359" alt="image" src="https://user-images.githubusercontent.com/949192/114325087-84939f00-9b2e-11eb-9edd-c1d2c696b085.png">

**Comment by dpjohnst** [comment]
Hi @Amparose,

Thanks for sharing this feedback with the Sublime Merge team.
Sublime Merge ships with a US English and UK English dictionary by default.

I'd suggest switching to the UK English dictionary (very close to Australian English), which can be done with the following steps:
1. Open Sublime Merge
2. Navigate to `Preferences > Edit Settings...`
3. Add the following line to the settings file (ensuring it's between the opening and closing braces):
```
"dictionary": "Packages/Language - English/en_GB.dic",
```

After this, the spell checker should match UK English.

Thanks,
\- Dylan

**Comment by Amparose** [comment]
Ta @dpjohnst that works.
