### ISSUE TITLE
Default Global Git Ignore File ~/.config/git/ignore Not Used

### ISSUE THREAD

**Issue by jwillikers** [sublimehq/sublime_merge#1115]
**Version info**

 - OS:  Ubuntu 20.04
 - Build: 2049

**Description**

The default global Git ignore file, `~/.config/git/ignore` is not used by Sublime Merge.

**Steps to reproduce**

1. Create the default Git ignore file `~/.config/git/ignore`.
1. Add a pattern to ignore.
1. Open / create a Git repository containing files that match that pattern with Sublime Merge.
1. Notice that Sublime Merge doesn't ignore those files.

**Expected behavior**

Sublime Merge should recognize the default global Git ignore file as documented [here](https://git-scm.com/docs/gitignore#_synopsis).

**Comment by dpjohnst** [comment]
Hi @jwillikers,

Thanks for reaching out to the Sublime Merge team!
Sorry to hear you're experiencing issues with Sublime Merge - I'll be investigating this further.

When you have a spare moment, could you share the following:
1. The Sublime Merge debug information (Accessible via `Help > Debug Information`)
    * Before sharing, take a moment to remove any information you feel is sensitive (email address, file paths, names etc)
2. Whether running the following via the terminal returns a value or not (don't require the value, just whether there is one): `echo $XDG_CONFIG_HOME`

Thanks,
\- Dylan

**Comment by jwillikers** [comment]
1. Debug Info

```
=== App Version Information ===
Build: 2049

=== Git Version Information ===
Using Git: git (system)
git version 2.31.0
PATH: /app/bin:/usr/bin:/app/libexec/git-lfs

=== Browse Page Information ===
HEAD: 9745620ef8625000239a738df969d21ac8b219f2
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===

=== Git Config Information ===
branch.main.merge=refs/heads/main
branch.main.remote=origin
commit.gpgsign=true
core.bare=false
core.editor=flatpak run com.vscodium.codium --wait
core.filemode=true
core.logallrefupdates=true
core.repositoryformatversion=0
gpg.program=/usr/bin/gpg
init.defaultbranch=main
merge.tool=smerge
mergetool.smerge.cmd=smerge mergetool "$BASE" "$LOCAL" "$REMOTE" -o "$MERGED"
mergetool.smerge.trustexitcode=true
push.gpgsign=if-asked
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@gitlab.agleader.local:components/embedded-modules/eeprom.git
tag.gpgsign=true
user.email=jordan@jwillikers.com
user.name=Jordan Williams
user.signingkey=A6AB406AF5F1DE02CEA3B6F09FB42B0E7F657D8C

=== Our Config Information ===
Git Config Path Information
Using config path: /usr/etc/gitconfig
Using config path: /home/jwilliams/.var/app/com.sublimemerge.App/config/git/config
Using config path: /home/jwilliams/.gitconfig
Using config path: /home/jwilliams/Projects/Ag Leader/eeprom/.git/config

Our config output is identical to the Git config output

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 0
```

2. There's no value when I run `echo $XDG_CONFIG_HOME`

**Comment by dpjohnst** [comment]
Hi @jwillikers,

Thanks for the additional information!

It's worth noting that currently Sublime Merge will not reload the global Git ignore file until the application is restarted.

Just to rule things out, could you confirm that the files matching the pattern are untracked files (as opposed to modified files).

Additionally, could you try the following to confirm whether the ignore file is being loaded at all:
1. Add `*` to the ignore file
2. Create a new file `abc.txt` in the repository root
3. Confirm whether the new file is correctly ignored

Also, if your ignore rules don't contain any sensitive information, would you mind sharing them? No worries if you can't.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @jwillikers,

Just reaching out again to see if you've had a chance to run through the above?

Cheers,
\- Dylan

**Comment by jwillikers** [comment]
@dpjohnst Thanks for the help! I just completed the steps you provided and noticed the same issue. I use the *unofficial* Flatpak, and decided to test with the official tarball. The file is ignored when using the tarball, so this isn't an issue with Sublime Merge, but the unofficial Flatpak, so I'm closing this issue here. Thanks again!
