### ISSUE TITLE
Indicate that progress is being made when staging a lot of files

### ISSUE THREAD

**Issue by Baegus** [sublimehq/sublime_merge#1116]
**Problem description**

At least for me on Windows, it sometimes takes a while to stage a lot of changes at once (like 50 untracked files for example). When I click on "Stage all", the changes disappear and there are "No changes" in the Commits list. It may look like nothing is happening even though the changes appear correctly after a couple of seconds.

**Preferred solution**

I think there should be some indication that progress is being made so that the user doesn't think all his changes are gone (it looks the same as if I accidentaly clicked "Discard all" instead).

**Comment by dpjohnst** [comment]
Hi @Baegus,

Thanks for reaching out to the Sublime Merge team!

When operations are being performed (such as `git add/stage`), a circular indicator will appear in the header bar of Sublime Merge:
![operation in progress](https://user-images.githubusercontent.com/18252447/114955023-16890800-9e9f-11eb-8be8-430858ad7aaa.png)

This should make up a large part of the delay, as the Git command is still executing.
When the command completes, the indicator should turn into a tick icon (and you can expect the staged file to appear shortly).

By this point, there may be a small delay before the staged files appear (as Sublime Merge is reloading the snapshot of the repository). We could display a loading indicator for snapshots, but I suspect this would be less than ideal (as Sublime Merge reloads snapshots whenever any repository-related file is created / updated). You would likely be left with an almost continuous loading bar.

Kind regards,
\- Dylan

**Comment by Baegus** [comment]
The delay is probably caused by a slower hard drive. Repos on my SSD don't seem to have this issue. Closing for now. :) Thanks
