### ISSUE TITLE
Sublime Merge 2049 fails to load repo

### ISSUE THREAD

**Issue by bitmagewb** [sublimehq/sublime_merge#1117]
**Version info**

 - OS: Fedora 32
 - Build: 2049

**Description**

Sublime Merge is failing to load one of my repos.  The console reports:
loading repo /u/brdani/work/systems.extweb/.git
unable to open index: Unable to map index at open_index: sgit/index.cc:17

No items are shown in the main window.  The repo works with command line and QGit, and passes a fsck:
[xyzzy systems.extweb]$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
[xyzzy systems.extweb]$ git fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (41269/41269), done.

The repo is in a NFS mounted filesytem, but other repos in the same filesystem work in Merge as expected (and this repo did as well until recently.)

**Comment by srbs** [comment]
Is the repo publicly available for reproduction?

Did a previous version of Sublime Merge successfully load the repo?

**Comment by bitmagewb** [comment]
Figured it out.  Somehow it had lost the 'bookmarked' path for that repo in the quick_switch_repository dialog.  A path element was missing and it was trying to open a dir that did not exist.  Manually reopened the repo and it is working correctly again.
