### ISSUE TITLE
Maximization state forgot between launches

### ISSUE THREAD

**Issue by nanoant** [sublimehq/sublime_merge#112]
This is related to #26.

**Version info**

 - OS: Windows 10 (1703)
 - Build: 1070

**Description**

While since v1070 SM remembers its non-maximized window position, it does not remember it was previously running maximized, so when re-run it starts in normal state even it was closed as maximized before. (At least this is on Windows).

**Steps to reproduce**

1. Run Sublime Merge
2. Maximize its window
3. Close it
4. Start it again

**Expected behavior**

SM should start maximized.

**Actual behavior**

SM starts with normal (non-maximized) window.

**Comment by jskinner** [comment]
This should be fixed in dev build 1071 at https://www.sublimemerge.com/dev. The changes should migrate into a stable build sometime next week.

Please reopen this if it's still an issue for you after 1071.

**Comment by nanoant** [comment]
@jskinner Many thanks Jon!
