### ISSUE TITLE
Crash when pressing "Resolve"

### ISSUE THREAD

**Issue by themilkman** [sublimehq/sublime_merge#1123]
**Version info**

 - OS: Kubuntu 20.10
 - Build: 2051

**Description**

When clicking the "Resolve" button on a file with merge conflicts SM completely crashes in the latest version.

Also reproduced by @TheSecEng on MacOS.

**Comment by jaraco** [comment]
Similarly when running `git mergetool` on macOS after updating to the 2051 build, the screen flashes as if the application is starting, then git reports:

```
Failed to receive exit code from application
```

**Comment by dpjohnst** [comment]
Hi all,

Thank you for reporting this issue - we have identified the issue and are producing a fix for this.

Kind regards,
\- Dylan

**Comment by jaraco** [comment]
Confirmed fixed in 2052.
