### ISSUE TITLE
Search Location Bar by Branch/Tag Name - Feature Request

### ISSUE THREAD

**Issue by mwhite05** [sublimehq/sublime_merge#113]
We have many repositories and some of them are iterated often. For example repository has 296 tags and another has 199. It would be very helpful to have a filter field at the top of the location bar to narrow down the list quickly.

**Comment by dpjohnst** [comment]
Hi all,

This was added in Sublime Merge Build 2041 (development build), and will be available in the next stable build.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

Just following up that this was released to the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan
