### ISSUE TITLE
Sublime Merge APT Repository broken, won't install on Ubuntu 21.04

### ISSUE THREAD

**Issue by fnkr** [sublimehq/sublime_merge#1131]
**Version info**

 - OS: Ubuntu 21.04
 - Build: latest (trying to install from repository)

**Description**

APT aborts installation and returns the following error:

```
E: Failed to fetch https://download.sublimetext.com/files/sublime-merge_build-2049_amd64.deb  File has unexpected size (4542548 != 4548032). Mirror sync in progress? [IP: 104.236.0.104 443]
```

I have been trying this for >12h so unless mirror sync is taking really long it's not mirror sync in progress.

**Steps to reproduce**

You could use Docker to reproduce this (or any Ubuntu 21.04 machine). Instructions are these from https://www.sublimemerge.com/docs/linux_repositories.

```
$ docker run --rm -it ubuntu:21.04 bash
# apt-get update && apt-get -y install wget curl apt-transport-https gnupg2
# wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
# echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list
# apt-get update
# apt-get -y install sublime-merge
```

**Expected behavior**

APT should install Sublime Merge without error.

**Logs**

```
# apt-get install sublime-merge
[...]
E: Failed to fetch https://download.sublimetext.com/files/sublime-merge_build-2049_amd64.deb  File has unexpected size (4542548 != 4548032). Mirror sync in progress? [IP: 104.236.0.104 443]
   Hashes of expected file:
    - SHA512:f65ce3ca80ff0877da48826a0151036cd8e0bdf28b03d225a03f202262ca1278accdac8e7eb46a22904203750ccf06e3abe496a44f7a4b0c3363076501f72369
    - SHA256:e71fcf37e9d934a60b5112a7b79c819f03f55d331371ec0e9b02378c6234478c
    - SHA1:7fe54a9f7ea5383dbdfc0aae39310e2902c6d7f5 [weak]
    - MD5Sum:fd78a3b986bd7da8b2ebd1f659f5938c [weak]
    - Filesize:4548032 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by sajanp** [comment]
Can confirm.

`sudo apt install sublime-merge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  sublime-merge
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,548 kB of archives.
After this operation, 19.6 MB of additional disk space will be used.
Get:1 https://download.sublimetext.com apt/stable/ sublime-merge 2049 [4,548 kB]
Err:1 https://download.sublimetext.com apt/stable/ sublime-merge 2049
  File has unexpected size (4542548 != 4548032). Mirror sync in progress? [IP: 104.236.0.104 443]
  Hashes of expected file:
   - SHA512:f65ce3ca80ff0877da48826a0151036cd8e0bdf28b03d225a03f202262ca1278accdac8e7eb46a22904203750ccf06e3abe496a44f7a4b0c3363076501f72369
   - SHA256:e71fcf37e9d934a60b5112a7b79c819f03f55d331371ec0e9b02378c6234478c
   - SHA1:7fe54a9f7ea5383dbdfc0aae39310e2902c6d7f5 [weak]
   - MD5Sum:fd78a3b986bd7da8b2ebd1f659f5938c [weak]
   - Filesize:4548032 [weak]
E: Failed to fetch https://download.sublimetext.com/files/sublime-merge_build-2049_amd64.deb  File has unexpected size (4542548 != 4548032). Mirror sync in progress? [IP: 104.236.0.104 443]
   Hashes of expected file:
    - SHA512:f65ce3ca80ff0877da48826a0151036cd8e0bdf28b03d225a03f202262ca1278accdac8e7eb46a22904203750ccf06e3abe496a44f7a4b0c3363076501f72369
    - SHA256:e71fcf37e9d934a60b5112a7b79c819f03f55d331371ec0e9b02378c6234478c
    - SHA1:7fe54a9f7ea5383dbdfc0aae39310e2902c6d7f5 [weak]
    - MD5Sum:fd78a3b986bd7da8b2ebd1f659f5938c [weak]
    - Filesize:4548032 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by srbs** [comment]
@fnkr, this should be fixed in the latest stable build (2054), please verify and close.

**Comment by fnkr** [comment]
Works for me.
