### ISSUE TITLE
Failed to push refs when `git-lfs` is required

### ISSUE THREAD

**Issue by aeisenberg** [sublimehq/sublime_merge#1138]
**Version info**

 - OS: macos 10.15.7
 - Build: 2054

**Description**

When I try to push, I am getting the error:

```
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'git@github.com:github/xxx.git'
```

I have just upgraded to 2054 and I have been able to push with no problem until then. I can still push from the command line. `git-lfs` is on my path.

**Steps to reproduce**

1. Open repository that requires the use of `git-lfs`
2. Push a commit to your remote
3. Error as described above

**Expected behavior**

Should be able to push without an error.

**Comment by dpjohnst** [comment]
Hi @aeisenberg,

Thanks for reaching out to us, and apologies for the inconvenience!

Recently we upgraded Git to version 2.30.2. As of this update, we no longer bundle Git LFS by default. This is to reduce the overall size of the Sublime Merge binary.

You can install Git LFS on MacOS using the following instructions: https://docs.github.com/en/github/managing-large-files/installing-git-large-file-storage

Thanks,
\- Dylan

**Comment by aeisenberg** [comment]
Thanks for your response, but that doesn't work. I already have git-lfs installed. As you can see, I have it working on the command line:

```
$ brew upgrade git-lfs
Warning: git-lfs 2.13.3 already installed
$ git lfs install
Updated git hooks.
Git LFS initialized.
```

Is there something I need to do to install git-lfs from inside sublime merge?

**Comment by aeisenberg** [comment]
Is there a way to download the previous stable build (looks like build 2050)? I'm finding this bug is impacting my work.

**Comment by aeisenberg** [comment]
OK...did a little bit of digging. The debug information for sublime merge has the following section:

```
=== Git Version Information ===
Using Git: git (system)
git version 2.24.3 (Apple Git-128)
PATH: /usr/bin:/bin:/usr/sbin:/sbin
environment variables loaded using: /usr/local/bin/bash -l
```

However, my git-lfs is installed elsewhere:

```
$ which git-lfs
/usr/local/bin/git-lfs
```

I'm guessing this is the problem. The git executable is not looking in the right location for git-lfs.

Due to macos's System Integrity Protection, I can't just create a soft link in a path directory. (I _could_ turn it off briefly and do it, but I'd rather not).

How can I change the path that sublime merge uses?

**Comment by aeisenberg** [comment]
Ah...I changed the git executable that sublime merges to `system` and restarted. Now it is working.

**Comment by dpjohnst** [comment]
Hi @aeisenberg,

Thanks for the additional information!

As you've mentioned, it looks as if the path to Git-LFS is missing from the `PATH` environment variable.
One way to fix this is to switch to System Git, which will have the path hard-coded.

Additionally, you could continue to use the bundled Git, add a `.bash_profile` file in your home directory, and add the following line to it:
```
PATH=$PATH:/path/to/git/lfs
```
replacing `/path/to/git/lfs` with the actual path.

Note that adding this line to `.bashrc` won't work, as the environment variables are loaded using `/usr/local/bin/bash -l` (i.e. a non-interactive terminal).

Hope this helps!

Thanks,
\- Dylan

**Comment by RoyiAvital** [comment]
Have you removed Git LFS from the latest portable version for Windows?

Suddenly today, after an update, I got this:

![image](https://user-images.githubusercontent.com/7347975/118796250-19af5380-b8a4-11eb-85f9-7fad9bb077ae.png)

Having Git LFS is crucial for the Windows Portable version.

**Comment by aeisenberg** [comment]
My guess is "yes". I would think a similar approach that I took on mac would work here. Just change the executable to _system_ (assuming you system git executable includes git-lfs) and restart.

**Comment by RoyiAvital** [comment]
Actually the solution is that `GIT LFS` is not bundled with Sublime Merge Portable (Windows).
I hope they will start doing so.

For now:

https://forum.sublimetext.com/t/git-lfs-error-in-sublime-merge-portable-build-2056/57608
