### ISSUE TITLE
Open console pop up for custom commands

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#114]
**Problem description**

I know there are Default.sublime-commands for Sublime Merge, but would like to have a few feature being added

**Preferred solution**

~~Add "custom command" to the right click menu when there is $commit in the command~~
```
[
    {
        "caption": "Contains branch",
        "command": "git",
        "args": { "argv": ["branch", "-a", "--contains", "$commit"], }
    },
]
```
![image](https://user-images.githubusercontent.com/4518597/46873421-1e4c3980-ce69-11e8-8e13-1db58c5998ba.png)
![image](https://user-images.githubusercontent.com/4518597/47625478-6012fa80-db60-11e8-87c7-5f87fece9cee.png)
Seems add the command to `Commit.sublime-menu` under `\Data\Packages\User` do the trick

Add option for command to show the result after running instead of needing to click the icon on the branch bar
![image](https://user-images.githubusercontent.com/4518597/46873505-55bae600-ce69-11e8-8289-d81eddcf3899.png)

**Comment by wbond** [comment]
Where do you think you would ideally see the output of the command?

**Comment by jasonycw** [comment]
@wbond I think the output position is ok right now, but hope it will show up automatically (no need to click the button left of the branch bar)

If the custom command can be shown in the right click menu will be great too

**Comment by jasonycw** [comment]
Just found out there are all kinds of `.sublime-menu` that I can utilize for all the right click menus.
(Found them inside `\Sublime Merge Dev\Packages\Default.sublime-package\`)

So one of the problem is kind of solved as long as there is a right click menu. 👍 

Still waiting to know if there is an args / command / option to trigger the command to pop up.
