### ISSUE TITLE
win10 non-paged pool useage too much

### ISSUE THREAD

**Issue by kopes18** [sublimehq/sublime_merge#1143]
**Version info**

 - OS: win10
 - Build:  build 2054
 
**Description**

non-paged pool useage too much. non-paged pool usage slowly increase until RAM is full. For example: sublime merge use 10g after 2 day.

**Comment by jfcherng** [comment]
should be the same issue with https://github.com/sublimehq/sublime_text/issues/4122

**Comment by dpjohnst** [comment]
Hi @kopes18,

Thanks for reporting this issue - we've released new builds (2055 dev and 2056 stable) which should address this issue.
Could you confirm it's resolved on your end?

Kind regards,
\- Dylan
