### ISSUE TITLE
Natural Sort (or add a preference to natural sort) the location bar branches/tags.

### ISSUE THREAD

**Issue by mwhite05** [sublimehq/sublime_merge#115]
We have a lot of tags (296 in one repo, 199 in another) for version numbers that currently get sorted alphabetically/numerically which causes them to sort like this:

1.0.0
1.1.1
...
1.1.10
1.1.11
1.1.2
1.1.20
1.1.21
1.1.3
1.1.4
1.4.5

**Preferred solution**

Sort for natural language. It might be best to make this option a preference in the program.

1.0.0
1.1.1
...
1.1.10
1.1.11
1.1.2
1.1.3
1.1.4
1.4.5
...
1.1.20
1.1.21

A description of what changes should be made to Sublime Merge to solve the problem.

**Alternatives**

Have not thought of any.

**Screenshots**

N/A

**Comment by jasonycw** [comment]
Same? #87

**Comment by mwhite05** [comment]
Oops; I Didn't see that one. Yes, this ticket is basically the same as 87 though I would suggest applying the natural sort to all the location bar sections, not just tags. @jasonycw

**Comment by wbond** [comment]
Closing as a duplicate
