### ISSUE TITLE
"Squash with Parent" dialog reporting incorrect hashes

### ISSUE THREAD

**Issue by nk9** [sublimehq/sublime_merge#1151]
**Version info**

 - OS: 10.15.7
 - Build: 2056

**Description**

When using the "Squash with Parent" context menu item to squash a commit with its parent, the commit and parent hashes are both incorrect. It looks like when you actually do the squash, the correct hashes are used. But the dialog is always reporting incorrect hashes.

**Steps to reproduce**

1. Open repository
2. Pick a commit and Ctrl-click on it
3. Choose Edit Commit > Squash with Parent
4. Notice the dialog quotes incorrect hashes

**Expected behavior**

I'd expect the correct hashes to be used. I am not able to ever get this dialog to show the correct hashes. When I use a test repo, clicking the Squash button DOES actually squash the correct commits. But it's very disconcerting that the hashes are wrong!

**Screenshots**

<img width="946" alt="Screenshot 2021-05-19 at 20 17 06" src="https://user-images.githubusercontent.com/3646730/118871758-c8bd5080-b8df-11eb-9a47-9f8142cb1fba.png">

**Comment by dpjohnst** [comment]
Hi @nk9,

Thanks for sharing this feedback!

The short commit hash actually refers to the first 8 characters of the full commit hash, as opposed to the last 8 characters.
I hope this clears things up.

Thanks,
\- Dylan

**Comment by nk9** [comment]
LOL! Wow, I can't believe I didn't notice that. 😊  Thanks for the kind explainer!
