### ISSUE TITLE
Cherry Pick File successfully does nothing if file's parent directory does not exist

### ISSUE THREAD

**Issue by ratijas** [sublimehq/sublime_merge#1154]
**Version info**

 - OS: Arch Linux 5.12.6-arch1-1
 - Build: 2056

**Description**

Cherry-picking file from some branch to the current silently does nothing and reports success (green tick in the top status bar) without any explanations whatsoever. Nothing happens probably because parent directory (directories) of cherry-picked file in question does (do-) not exist — of course, it was (or they were) created in that branch along with the file itself.

**Steps to reproduce**

1. Open/Create repository ...
2. Setup things for the next step if necessary (create branch, dirs & files; add & commit; checkout previous branch/commit)
2. Cherry Pick File whose parent directory does not exist in current working dir state

Minimal reproducible repository and screenshots of it are attached.
[sublime_merge_issue_1154.zip](https://github.com/sublimehq/sublime_merge/files/6532795/sublime_merge_issue_1154.zip)

**Expected behavior**

Create directory and cherry pick file.

**Screenshots**

![initial commit](https://user-images.githubusercontent.com/6737986/119356476-228e9380-bcaf-11eb-97ac-a822db200df3.png)
![new nested file](https://user-images.githubusercontent.com/6737986/119356490-28847480-bcaf-11eb-80e0-d95827b91619.png)
![status](https://user-images.githubusercontent.com/6737986/119356532-376b2700-bcaf-11eb-8743-568346a8c98c.png)

**Comment by srbs** [comment]
good find! (related: #948)

**Comment by dpjohnst** [comment]
Hi @ratijas,

Thanks a bunch for reporting this! We'll have this fixed in the next build of Sublime Merge.

Cheers,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @ratijas,

This was fixed in Sublime Merge Build 2057 (Dev) / 2059 (Stable)!

Cheers,
\- Dylan from Sublime HQ
