### ISSUE TITLE
Up and down buttons move cursor in command palette

### ISSUE THREAD

**Issue by lastsecondsave** [sublimehq/sublime_merge#1158]
**Version info**

 - OS: Ubuntu 20.10
 - Build: 2055 linux x64

**Description**

Pressing up and down in the command palette first moves the text cursor to the beginning/ending of the text and only on second press it moves the selection.

**Steps to reproduce**

1. Open command palette and enter any text.
2. Press series of ups and downs.
3. Notice that first press moves text cursor, not the selection.

**Expected behavior**

Only selection is moved, cursor stays in place.

**Comment by srbs** [comment]
This was reported in Sublime Text (sublimehq/sublime_text#4163) and should be available in the next build of Sublime Merge.

**Comment by dpjohnst** [comment]
Hi @lastsecondsave - this was fixed in Sublime Merge Build 2057 (development build) and will be fixed in the next stable build :)

Cheers,
\- Dylan

**Comment by lastsecondsave** [comment]
I confirm it now works correctly. Thank you!
