### ISSUE TITLE
Please support merge --ff-only

### ISSUE THREAD

**Issue by afridley** [sublimehq/sublime_merge#1159]
**Problem description**

This would allow only merging if ff is possible

**Preferred solution**

implement --ff-only

**Alternatives**

do nothing

**Screenshots**

![ff](https://user-images.githubusercontent.com/34749972/119893122-9ecbe580-bf00-11eb-8f35-d72455775735.png)

**Comment by dpjohnst** [comment]
Hi @afridley,

Thanks for sharing this feedback with the Sublime Merge team!

We don't offer a `--ff-only` option in our merge dialog, as it directly indicates if a fast-forward merge is possible within the merge dialog.

See below:
![Fast Forward](https://user-images.githubusercontent.com/18252447/120143898-583dfa00-c224-11eb-9e69-b3d667c447a9.png)

I have noticed that the contrast on the explanatory text seems a little low, so I'm going to investigate increasing the contrast to improve visibility.

Hope this helps!

Thanks,
\- Dylan
