### ISSUE TITLE
Install not posible on OpenSuse

### ISSUE THREAD

**Issue by enfoqueNativo** [sublimehq/sublime_merge#116]
**Version info**

 - OS: OpenSuse 15.0

**Description**

The procedure to install sublime-merge depicted via zypper doesn't work.
It ask for libpng >= 1.6 even when version 1.6.34 is installed.

**Steps to reproduce**

1. Follow https://www.sublimemerge.com/docs/linux_repositories#zypper steps

**Expected behavior**

Sucessful install

**Screenshots**
![sublime](https://user-images.githubusercontent.com/12297079/46877133-832a7400-ce16-11e8-9b75-e028c5917ce4.png)

**Comment by wbond** [comment]
This should be solved on the dev channel with build 1076. Can you confirm @enfoqueNativo?

**Comment by enfoqueNativo** [comment]
@wbond Confirmed as solved. Thanks!
