### ISSUE TITLE
Known Host Dialog Cropped Out 

### ISSUE THREAD

**Issue by mbarkhau** [sublimehq/sublime_merge#117]
**Version info**

 - OS: Windows 10
 - Build: 1055

I only just found this issue tracker. This error happened with the first version that was released and may have been fixed in the meantime.

**Description**

I was pulling from a repo for the first time and didn't know what to input into the dialog. The top portion of the screenshots from just after I clicked "OK".

Pressing Alt+Tab reveals that the thin white sliver at the bottom is actually a cropped modal dialog.

I could not close the dialog with the mouse, but pressing escape did the trick.

**Screenshots**

![image](https://forum.sublimetext.com/uploads/default/original/3X/5/d/5d3c7d9d7048ba3924125e1add700f9dcafd0a0c.png)

**Comment by jskinner** [comment]
This should be fixed in dev build 1071 at https://www.sublimemerge.com/dev. The changes should migrate into a stable build sometime next week.

Please reopen this if you see it again in a build >= 1071.
