### ISSUE TITLE
Remote URL copyable (and editable?)

### ISSUE THREAD

**Issue by hvisage** [sublimehq/sublime_merge#1179]
**Problem description**

I'd have the needs to copy and edit the remote  repository URLs

**Preferred solution**

Provide (typically on right clicking?) the ability to copy (and paste) Remote URLs3333333333333333333

**Alternatives**

The .git directory to be made visible (easier than currently) in Sublime Text

**Comment by srbs** [comment]
related: #699, #862

**Comment by dpjohnst** [comment]
Hi @hvisage - this was added in Sublime Merge Build 2057 (development build) and will be available in the next stable build :)

Cheers,
\- Dylan

**Comment by Ultra-Instinct-05** [comment]
I have added the following entry to my `Default.sublime-commands`
```json
[
    {
        "caption": "Open Remote URL",
        "command": "open_url",
        "args": {
            "url": "$remote_url"
        },
    },
]
```
but it doesn't seem to work. Does it mean that the `$remote_url` variable works only off of the context menu  of the `Location` tab ?

**Comment by dpjohnst** [comment]
Hi @Ultra-Instinct-05,

That's correct - as a user can have multiple remotes, it's not possible to have a single `$remote_url` variable in the global context (only in the context of a specific remote).

That being said, I can look into adding a command to the command palette that allows you to select the target remote in the case of multiple remotes. If this is something you'd like, please feel free to create a new enhancement request for this and we can definitely look into this :) 

Cheers,
\- Dylan

**Comment by Ultra-Instinct-05** [comment]
@dpjohnst Thanks for the explanation. There's already an issue for adding it to the command palette https://github.com/sublimehq/sublime_merge/issues/862 
My general use case for this is a quick way to open the remote in the browser as I work with only a single remote url.

**Comment by dpjohnst** [comment]
Hi all,

This was added in Sublime Merge Build 2058 (Dev) /2059 (Stable)!

Cheers,
\- Dylan from Sublime HQ
