### ISSUE TITLE
Keybinding popups don't always disappear

### ISSUE THREAD

**Issue by oconnor0** [sublimehq/sublime_merge#1180]
**Version info**

 - OS: Windows 10
 - Build: 2055

**Description**

Sometimes the little keybinding popups that hover below the buttons (usually Discard or Stage) don't disappear. And they get "stuck" so I can't get them to disappear without relaunching the app. I don't know exactly when or why this happens, but I get it maybe once a week.

**Screenshots**

![image](https://user-images.githubusercontent.com/64384/122991613-76e66b00-d362-11eb-88b3-7a01ca45221b.png)

**Comment by srbs** [comment]
possibly related: sublime_text#4389

possibly similar: #1111

**Comment by retifrav** [comment]
To keep this updated, I've just got it happening in **2059** build on Windows (*`Ctrl+2` popup*):

![popup](https://user-images.githubusercontent.com/6904927/129015007-2e8be30a-fe1a-4bcb-a6fe-613ea544ee6c.png)

**Comment by dpjohnst** [comment]
Hi all,

Sublime Merge 2086 (development build) has been released which fixes this.
This fix will also be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ
