### ISSUE TITLE
Revert range of commits

### ISSUE THREAD

**Issue by buzzlawless** [sublimehq/sublime_merge#1185]
**Problem description**

To revert a range of commits, I believe you need to right click each one and select "Revert Commit"

**Preferred solution**

Just as you can select a range of commits (by holding down shift) and then right-click to select "Edit Commit" > "Drop Selected Commits" or > "Squash Selected Commits", there should also be an option to "Revert Selected Commits"

**Comment by srbs** [comment]
related (to multiple-commits actions): #480

**Comment by srbs** [comment]
@buzzlawless, looks like this was added in dev build 2058

**Comment by dpjohnst** [comment]
Hi @buzzlawless,

This was added in Sublime Merge Build 2058 (Dev) /2059 (Stable)!

Cheers,
\- Dylan from Sublime HQ
