### ISSUE TITLE
Validate remote name immediatelly after input and prevent transition to next input handler

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#1192]
**Problem description**

I wanted to add a new remote, but as a dump user doing so rarely, I entered an invalid name. SM didn't prevent me doing so but failed calling the git command. The annyoing thing is, I needed to edit pasted repo URL. Those modifications are lost and need to be done again.

**Preferred solution**

Repo name input handler (screenshot 1) should validate repository name and prevent transition to next one as long as entered name is not valid. Maybe the `description` field could be used to print a little message like `Repo name is invalid` below the input field?.

**Alternatives**

No idea

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/123843589-5eea8a80-d912-11eb-894d-a5e363426e1d.png)

![grafik](https://user-images.githubusercontent.com/16542113/123842873-8b51d700-d911-11eb-8402-87f2e04a4cc8.png)

**Comment by dpjohnst** [comment]
G'day @deathaxe,

Thanks for sharing this and apologies you lost those changes - we can definitely improve here!

CC'ing @DavidW1024 in here :) 

Cheers,
\- Dylan

**Comment by deathaxe** [comment]
Implemented by SM 2058

Thanks!
