### ISSUE TITLE
Split hunk button

### ISSUE THREAD

**Issue by spaskalev** [sublimehq/sublime_merge#1193]
**Problem description**

When adding/discarding lines selectively using 'git add -p' git presents several options, one of which is to split the hunk if it is too big. Having the same split hunk button in sublime merge can be great.

**Preferred solution**

Have a split hunk button on the hunk level.

**Alternatives**

Right now I have to revert back to git when the hunk is too big in sublime merge.

**Comment by srbs** [comment]
see also #233

**Comment by dpjohnst** [comment]
Hi @spaskalev,

Thanks for sharing this feedback!

When you have a spare moment, could you clarify how the individual line staging functionality in Sublime Merge is insufficient for your use case?

Thanks,
\- Dylan

**Comment by spaskalev** [comment]
@dpjohnst Thanks Dylan, I simply did not know about it :) This will work just fine!

Regards,
Stan
