### ISSUE TITLE
Allow commit template path to be relative paths as well.

### ISSUE THREAD

**Issue by Ultra-Instinct-05** [sublimehq/sublime_merge#1196]
**Problem description**

SM Build 2057 introduced a feature where it reads the contents of a file that is marked as a commit template in the git config file. Currently it seems that the path has to be an absolute path on disk for it to work. It would be nice if it could also support relative paths (relative from the repository root).

**Preferred solution**

Allow commit templates paths to be relative paths as well.

**Alternatives**

Continue to use absolute paths for commit templates.

**Version info**

SM Version: SM Build 2057 (dev)
OS: Windows 10 Build 10.0.19041 
Architecture: 64bit
Processor: Intel64 Family 6 Model 126 Stepping 5, GenuineIntel

**Comment by srbs** [comment]
@Ultra-Instinct-05, looks like this was fixed in dev build 2058
