### ISSUE TITLE
`Copy Repository Path` giving unix like repository paths on Windows

### ISSUE THREAD

**Issue by Ultra-Instinct-05** [sublimehq/sublime_merge#1197]
**Version info**

SM Version: SM Build 2057 (dev)
OS: Windows 10 Build 10.0.19041 
Architecture: 64bit
Processor: Intel64 Family 6 Model 126 Stepping 5, GenuineIntel

**Description**

When using `Copy Repository Path` from the action menu on Windows, the menu item copies the path as a unix path.

**Steps to reproduce**

1. Open SM in safe mode.
2. Use the `Copy Repository Path` from the action menu.
3. Paste it somewhere

**Expected behavior**

The copied repository path should be Windows like on Windows.

**Actual behavior**

The copied repository path is unix like in nature.

**Screenshots**

![8](https://user-images.githubusercontent.com/34304644/124227318-17d5e280-db28-11eb-8492-8cc1c927fe6e.gif)

**Comment by srbs** [comment]
@Ultra-Instinct-05, looks like this was fixed in dev build 2058

**Comment by Ultra-Instinct-05** [comment]
@dpjohnst Thanks for the fixes !
