### ISSUE TITLE
Submodule info is partially hidden by horizontal scrollbar

### ISSUE THREAD

**Issue by TheClams** [sublimehq/sublime_merge#12]
**Version info**

 - OS: Windows 10
 - Build: 1062

**Description**

When the window size is not wide enough to display the submodule changes the horizontal scrollbar is always visible and with no transparency effect contrary to a standard file where it is only appears on mouse hover and even in this case there is some transaparency effect to let the text readable

**Steps to reproduce**

 - Open a repository with sub-modules
 - Click on a commit where submodule version is changed
 - resize window to make the horizontal scrollbar appears.

**Expected behavior**

The scroollbar should behave the same as for a standard file: auto-hide and transparency effect

**Screenshots**

![cropped_submodule](https://user-images.githubusercontent.com/5270125/46187805-ba146c00-c2e5-11e8-9526-161bc1209564.png)

**Comment by mikepyne** [comment]
I see this in build 1070 as well.

**Comment by jskinner** [comment]
Fixed in Dev Build 1074
