### ISSUE TITLE
Commit graph line next to stashed files

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#120]
**Version info**

 - OS: Windows 10
 - Build: 1069

**Description**

If the commit of a stash is expanded a commit graph line is rendered next to each file, which has no link to anything.

**Steps to reproduce**

1. Open repository
2. Stash some changes
3. Expand a stash commit

**Expected behavior**

The yellow line left next to the file shouldn't be there.

**Screenshots**

![image](https://user-images.githubusercontent.com/16542113/46903500-3312e680-ced6-11e8-9b74-a1633fc111b4.png)

**Comment by jskinner** [comment]
Fixed in 1086 with the file list being moved to the side bar
