### ISSUE TITLE
Allow amend commit on commit message even without staged files

### ISSUE THREAD

**Issue by cwbaker** [sublimehq/sublime_merge#1200]
**Problem description**

I often would like to amend the most recent commit message without changing any files.  Sublime Merge 2056 displays "Nothing to commit" and won't try to commit in this case.

**Preferred solution**

I'd like to be able to click on "Amend Previous Commit" either from the "Commit" button drop-down or even just have the commit button change to "Amend Previous Commit" when the commit message is not empty even when there are no files staged.

Thanks,
Charles

P.S. I love using both Sublime Merge and Sublime Text, they are amazing tools, thank you for creating them!

**Comment by srbs** [comment]
I would advise the drop-down option to avoid accidental amending.

Workarounds:

1. right click the HEAD commit and choose `Edit Commit > Edit Commit Message`
2. add the below to `Default.sublime-keymap` & replace with whatever keystroke you want (note: the commit message will not clear like normal)
```
[
    {
        "keys": ["super+ctrl+shift+enter"],
        "command": "commit",
        "args": {"mode": "commit --amend"}
    }
]
```

**Comment by dpjohnst** [comment]
Hi @cwbaker,

Thanks for reaching out to the team!

The best way to achieve this would be editing the commit message directly. I've attached a video below to show how to do this - let me know if you have any questions.

It's worth noting you can also use `Ctrl + Enter` (`Cmd + Enter` on MacOS) while the commit message is focused to enter/exit edit mode.

![Change Commit Message](https://user-images.githubusercontent.com/18252447/124404665-3bdf3100-dd7f-11eb-99c7-a6820fcce883.gif)

Thanks,
\- Dylan

**Comment by cwbaker** [comment]
Ah.  I didn't know I could edit the commit messages that way.  There's are also rebase style commands like squash and move commits.  Might as well close this.
