### ISSUE TITLE
New window without repo is opened when clicking onto branch indicator in ST

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#1202]
**Version info**

 - OS: Windows 10
 - Build: 2057

**Description**

If Sublime Merge is already running with a repository (e.g.: MarkdownEditing) open, clicking onto Sublime Text's branch indicator in statusbar (same repo), sometimes opens a new empty Sublime Merge window with "clone or open repo" overlay displayed instead of jumping to the already open repository.

I haven't been able to narrow down exact circumstances which trigger this issue. It seems to be related with branch changing or committing or opening several ST instances - not sure.

Switching to another file in Sublime Text often fixes the issue for the original file, too.

I am not sure whether it is a SM or ST issue. May also be ST passing invalid arguments, I don't know.

That's an issue I started to see occationally, recently.

**Steps to reproduce**

none yet.

**Expected behavior**

Clicking branch indicator of ST's status bar should always bring an already open repo to front.

**Screenshots**

If applicable, add screenshots to help explain your problem. This section may be omitted/removed.

**Comment by deathaxe** [comment]
It's actually quite easy to reproduce.

1. Open a Repository in Sublime Text
2. click on git status badge in status bar -> Sublime Merge openes with correct repository
3. return back to ST
4. click on git status badge again -> Sublime Merge opens new window with clone overlay
5. close that empty window
6. repeat steps 3 to 4 (same behavior)
7. now leave empty SM window open
8. repeat steps 3 to 4 (now Sublime Merge brings the correct repository to front)


It means, I need to keep an empty dummy SM window open in background to work normally. :-/

**Comment by MrOwen** [comment]
Also experiencing this and I want to say it started around maybe 4108 or 4109

**Comment by dpjohnst** [comment]
Hi all,

Thanks for taking the time to report this issue!

I've so far been unable to reproduce the issue, but I'll continue to investigate until I can.

Could you confirm if you see any error messages in the console of Sublime Merge (in the new window that appears when this issue occurs)?

Additionally, could you confirm whether you have multiple repositories open in the window where the target repository is already present?

Thanks,
\- Dylan

**Comment by princemaple** [comment]
https://user-images.githubusercontent.com/1329716/124719758-d0e25580-df4a-11eb-96ac-e6b9d327f868.mp4

**Comment by husanjun** [comment]
The same problem, and I also found that 
1. Switching projects and clicking the Git badge opened a new window
2. Right-clicking SM in ST also pops up

**Comment by stinos** [comment]
> Right-clicking SM in ST also pops up

Yup. What happens for me:
- repository A is open in SM
- in ST (or similar*) use 'Open Git repository' on repository A => SM starts new window with the dialog to open a repository. Can't get error information ('Help->Debug Information' doesn't do anything, nor does ```Ctrl-` ```). Should bring the window/tab with A in it to front, as it used to be.
- in ST (or similar*) use 'Open Git repository' on repository B => SM starts new window where B is opened. Used to be a new tab in the existing window.

(*) using `sublime_merge.exe /path/to/repo`

Using `smerge.exe` instead, I get the original behaviour back (open new tab, or bring existing tab to fron) and have none of these problems. Does ST not use smerge.exe perhaps? Or did arguments for sublime_merge.exe change?

**Comment by husanjun** [comment]
Thanks, @stinos 
Added `"sublime_merge_path": "..../path/sublime_merge/smerge.exe",` to settings solved the problem

**Comment by dpjohnst** [comment]
Hi all,

Thanks for the additional information!

I've been able to reproduce the issue and I am in the process of fixing the issue. In the meantime, the work-around suggested above is best.

Kind regards,
\- Dylan

**Comment by deathaxe** [comment]
Fixed by SM 2058
