### ISSUE TITLE
Shortcuts: Switch Repository (SM) is inconsistent with Quick Switch Project (ST)

### ISSUE THREAD

**Issue by ratijas** [sublimehq/sublime_merge#1204]
**Problem description**

When jumping between Sublime Merge and Sublime Text, I'm always having such a hard times recalling which combination of Ctrl, Shift, Alt, O and P to press to bring this quick switch dialog.

Current shortcuts on Linux are:
- `Ctrl+Shift+O` in Sublime Merge
- `Ctrl+Alt+P` in Sublime Text

**Preferred solution**

Change shortcuts to be the same.

Personally I prefer `Ctrl+Alt+P` for two reasons:
- Nice spacing between fingers, especially if your Ctrl is swapped with CapsLock like mine,
- `P` is a mnemonic for "Project"s which this command deals with.

**Alternatives**

Write down shortcuts on a sticker, and put it on a monitor's corner alongside you bank account's password and wife birthday date.

**Screenshots**

![Sublime Merge](https://user-images.githubusercontent.com/6737986/124436019-3c2afc80-dd7e-11eb-80ef-bb15effc0d46.png)
![Sublime Text](https://user-images.githubusercontent.com/6737986/124436022-3cc39300-dd7e-11eb-985b-7a184c9b6cb9.png)

**Comment by FichteFoll** [comment]
I actually prefer the reverse (and have configured my ST for that). ctrl+alt+p was removed from the Windows default bindings because of a comflict with a locale-specific character input binding a long tim ago and I like the relation to ctrl+o with ctrl+shift+o.

**Comment by srbs** [comment]
I also prefer `cmd`/`ctrl+shift+o` as well, but instead, due to its similarity to the other most common shortcut: `cmd`/`ctrl+shift+p` (command palette).

**Comment by srbs** [comment]
@ratijas, looks like both shortcuts are now supported in dev build 2058

**Comment by ratijas** [comment]
The shortcuts are still inconsistent by default, at least on Windows which I'm currently using.

Sublime Merge: Stable Channel, Build 2121
Sublime Text: Stable Channel, Build 4200
