### ISSUE TITLE
Allow staging multi-selection

### ISSUE THREAD

**Issue by Wouterdek** [sublimehq/sublime_merge#1206]
**Problem description**

When a repo has a lot of changes, staging many files, but not all, is tedious.

**Preferred solution**

Allow selecting files in the change list. E.g:
 - Select first file
 - Shift-select 50th file
 - The first 50 files are now selected and I can press "Stage 50 files"

**Alternatives**

More commands to selectively stage files. E.g. "Stage files in folder1/**/folder2/*.txt"

**Comment by srbs** [comment]
duplicates: #381
related: #418, #143, #461
see also: #382, #689

**Comment by srbs** [comment]
As an alternative, you can add files within folders by doing something similar to: https://forum.sublimetext.com/t/ignore-file-directory-menu-items/57604

**Comment by dpjohnst** [comment]
Hi @Wouterdek,

Thanks for sharing this feedback with the team!

As mentioned by @srbs, this feedback has been shared before so I'll go ahead and close this issue.
Please feel free to give #381 a thumbs up, or subscribe to the issue to ensure you receive any updates related to this issue.

Cheers,
\- Dylan
