### ISSUE TITLE
incorrect submodule status after subtree merge

### ISSUE THREAD

**Issue by braver** [sublimehq/sublime_merge#121]
**Version info**

 - OS: macOS 10.14
 - Build: 1072

**Description**

When [subtree-merging](https://stackoverflow.com/questions/1683531/how-to-import-existing-git-repository-into-another/8396318#8396318) a repo (B) with submodules into a subdirectory of another repo (A) that already has submodules, Merge reports the submodule paths for repo B as removed. Git itself reports the repo as clean. 

**Steps to reproduce**

- take a repo that has .gitmodules
- `git remote add XXX_remote <path-or-url-to-XXX-repo>` another repo that has .gitmodules
- `git fetch XXX_remote`
- `git merge -s ours --no-commit XXX_remote/master`
- `git read-tree --prefix=ZZZ/ -u XXX_remote/master`
- `git commit -m "Imported XXX as a subtree."`

`git status` should report clean right now, while Merge will show something like this:

<img width="1397" alt="screen shot 2018-10-13 at 14 54 58" src="https://user-images.githubusercontent.com/2543659/46905747-374ffb80-cef8-11e8-8ce8-ca0730dedb75.png">

In the cli on the left I printed out the submodules that are registered in the subdirectory.

**debug info**

```
=== App Version Information ===
Build: 1072

=== Git Version Information ===
Using Git: git (system)
git version 2.17.1 (Apple Git-112)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

=== Browse Page Information ===
HEAD: 0502b3274d182a17f7f50b5a9334b2d9f43fb3e7
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===
 D alan/src/lib/alan-core
 D alan/src/lib/c-toolbox
 D alan/src/lib/cxx-toolbox
 D alan/src/lib/package-api

=== Git Config Information ===
branch.master.merge=refs/heads/master
branch.master.remote=origin
core.bare=false
core.editor=nano
core.excludesfile=~/.gitignore
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
credential.helper=osxkeychain
remote.alan.fetch=+refs/heads/*:refs/remotes/alan/*
remote.alan.url=git@gitlab.m-industries.com:alan/alan.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@gitlab.m-industries.com:fabric/webclient.git
submodule.src/lib/cxx-toolbox.active=true
submodule.src/lib/cxx-toolbox.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_toolbox.git
submodule.src/webserver/src/lib/cxx-toolbox.active=true
submodule.src/webserver/src/lib/cxx-toolbox.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_toolbox.git
submodule.src/webserver/src/lib/package_api.active=true
submodule.src/webserver/src/lib/package_api.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_api_package.git
user.email=koen.lageveen@me.com
user.name=Koen Lageveen

=== Our Config Information ===
Git Config Path Information
Using config path: /etc/gitconfig
Using config path: /Users/koenlageveen/.config/git/config
Using config path: /Users/koenlageveen/.gitconfig
Using config path: /Users/koenlageveen/Dev/test/.git/config

Our config output is different to the Git config output
branch.master.merge=refs/heads/master
branch.master.remote=origin
core.bare=false
core.editor=nano
core.excludesfile=~/.gitignore
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
remote.alan.fetch=+refs/heads/*:refs/remotes/alan/*
remote.alan.url=git@gitlab.m-industries.com:alan/alan.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git@gitlab.m-industries.com:fabric/webclient.git
submodule.src/lib/cxx-toolbox.active=true
submodule.src/lib/cxx-toolbox.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_toolbox.git
submodule.src/webserver/src/lib/cxx-toolbox.active=true
submodule.src/webserver/src/lib/cxx-toolbox.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_toolbox.git
submodule.src/webserver/src/lib/package_api.active=true
submodule.src/webserver/src/lib/package_api.url=git@gitlab.m-industries.com:cxx-toolbox/cxx_api_package.git
user.email=koen.lageveen@me.com
user.name=Koen Lageveen

=== Git Attributes Information ===
git check_attr --all output
alan/src/lib/alan-core
alan/src/lib/c-toolbox
alan/src/lib/cxx-toolbox
alan/src/lib/package-api

=== Our Modified Files Newline Normalisation and EOL Information ===
alan/src/lib/alan-core: unspecified - native
alan/src/lib/c-toolbox: unspecified - native
alan/src/lib/cxx-toolbox: unspecified - native
alan/src/lib/package-api: unspecified - native
```

**Comment by braver** [comment]
That’s correct, gitmodules [should be at the top](
https://www.git-scm.com/docs/gitmodules). I’m not sure it works in a subdir, but I suspect it does. I’ve seen them in subdirectories before, mostly because of sloppiness. However, my working dir isn’t dirty and I didn’t actively remove those submodules, I still have to do that. There is right now nothing for me to commit, so Merge definitely reports an incorrect and misleading status.

**Comment by jskinner** [comment]
.gitmodules is only meaningful at the top level, such that doing a subtree merge on a repository is not something you want to do - the submodules will be destroyed, e.g., doing a `git clone --recurse-submodules` won't work as you hope, as the repository has no submodules.

I'll change Sublime Merge's logic to match git here, but do keep in mind that you probably don't want to be doing this.

**Comment by braver** [comment]
Oh sure, I definitely don’t want to keep the repo in its current state and would continue to move the modules to the top level dir. So perhaps Merge’s state is “more correct”, but my expectation is more that it would follow and agree with `git` at all times. That said, `git` sometimes lacks in feedback, and feedback might be valuable in this situation.

**Comment by jskinner** [comment]
This should be resolved in 1074, with Sublime Merge giving the same output as git - thanks for all the data you've provided on this.

**Comment by braver** [comment]
Cool, glad I could help!
