### ISSUE TITLE
Command palette loses focus when working directory content changes 

### ISSUE THREAD

**Issue by codedbypm** [sublimehq/sublime_merge#1217]
**Version info**

 - OS: macOS 11.4
 - Build: 2056

**Description**
While developing I find myself often stashing the changes of my current branch, switching to main and then create a new branch for some other work. 
I perform those operation using keyboard sequences, so I do:
1. cmd+s
2. cmd+p and start typing `checkout`
3. use arrow and select `main`
4. cmd+p and start typing `create branch`
5. and then type the branch name

For the last 2-3 months, while typing the branch name for bullet nr 4, sometimes the command palette was losing the focus and instead the commit message textfield was being selected. So part of the branch name was ending up in the commit message field since the palette was not active anymore (though visible).

I only found today the issue. Well, ... I think
I am an iOS developer so I use Xcode 90% of the time  when writing code for the repo handled by SM. 
In my current project I use 3rd party Swift Packages and right after step 3 is done, Xcode deletes the `Package.resolved` file and then resolve the new packages in relation to the `main` branch. So at the end of step 3, the working directory is not dirty anymore since `Package.resolved` is automatically back.

And I think is right this delete-recreate process that causes the command palette to lose focus. 
It is terribly annoying, so you would have a happier developer and SM user if you would fix it :) 

**Steps to reproduce**

The description contains more or less the steps to reproduce. 

**Expected behavior**
While typing content in the command palette, this one should not lose focus and become inactive. 

**Screenshots**
Not available

**Comment by dpjohnst** [comment]
Hi @codedbypm,

Thanks for sharing this feedback - much appreciated!
I've been able to reproduce the issue, and I am working on a fix.

I'll keep you updated as I progress.

Cheers,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @codedbypm,

This was fixed in Sublime Merge Build 2058 (Dev) /2059 (Stable)!

Cheers,
\- Dylan from Sublime HQ
