### ISSUE TITLE
GitFlow - 'flow' is not a git command

### ISSUE THREAD

**Issue by MaCo117** [sublimehq/sublime_merge#122]
**Version info**

 - OS: [Windows 10 - 64 bit]
 - Build: [1072 (both installed and portable)]

**Description**

Thank you for introducing this feature so quickly 👍 

However, maybe I am just thick, but anything beyond initializing the repo for GitFlow does not work for me.
Initialization command passed fine, but any command beyond that does not get recognized.
`git: 'flow' is not a git command. See 'git --help'`
This sounds like the git installation the SublimeMerge uses does not contain GitFlow. Does the tool use system git installation, or its own one?

**Steps to reproduce**

1. Initialize the GitFlow on repository
2. Attempt to execute some GitFlow command

**Expected behavior**

Command gets recognized and executed.

**Screenshots**
![sublimemerge_gitflow_command](https://user-images.githubusercontent.com/9208666/46905769-7d0cc400-cef8-11e8-8afc-debe391c6e02.png)

![sublimemmerge_gitflow_fail](https://user-images.githubusercontent.com/9208666/46905663-42eef280-cef7-11e8-96db-397fc1f481df.png)

**Comment by jskinner** [comment]
We are not currently bundling Git Flow, but we really should be.

Sublime Merge will use its bundled version of git by default on Windows. You can use the system git by changing the `"git_binary"` preference to `"system"`, it should then find `git flow` if you have it installed.

**Comment by jskinner** [comment]
1073 has git flow included in the bundled version of git
