### ISSUE TITLE
Whitespace not restored properly when choosing Discard Hunk

### ISSUE THREAD

**Issue by bradhoward-dfs** [sublimehq/sublime_merge#1227]
- OS: Mac 10.15.7 Catalina
 - Build: 2059

Choosing Discard Hunk on one hunk of changes. There are more hunks than just the hunk I am discarding.
Once clicked, I return focus to ST4 4113 and the view into the file updates and returns the code as expected,
but the whitespace is not correct and the left margin of the view displays the change colors associated with
changed code on that line.

To reiterate, SublimeMerge shows no changes for the lines I just discarded the hunk for. ST4 DOES show
remaining changes even though I expect there to be none. Those changes that remain are whitespace only.
Obviously this is a big deal in Python since the indentation is now wrong on those lines.

1. Use ST4 to make changes in source file, save file so changes show up in SM
2. Choose to discard one specific hunk, do not discard all.
3. Return to ST4 so the view reloads the file
4. Notice the whitespace differences (along with the change indicators on the left margin)

ST4 should show no changed lines for the area that was just impacted by choosing Discard Hunk in SM.

**Comment by srbs** [comment]
Were you showing or hiding whitespace changes at the time of discarding the hunk?

**Comment by bradhoward-dfs** [comment]
I have my Preferences set to hide whitespace changes in SM.

**Comment by srbs** [comment]
I'm not so sure this is a bug. How is Sublime Merge supposed to know that the following or preceding lines with only whitespace changes are supposed to be a part of the discard action? If it did, it's possible that multiple hunks would then be combined in an even more confusing user experience. (why did two hunks get discarded when I only wanted one).

I would highly recommend showing whitespace prior to any discarding of hunk or lines.

**Comment by bradhoward-dfs** [comment]
I appreciate the advice and will follow it.

I wonder if the act of  hiding whitespace removes it from management by git/SM?

Perhaps the proper use of hiding whitespace (in my case only) would be to NOT hide it while actively modifying any changes via SM.

Thank you for spending time on this issue.
