### ISSUE TITLE
Preserve Tabs from previous session

### ISSUE THREAD

**Issue by Capable-Disk4147** [sublimehq/sublime_merge#1229]
**Problem description**

Every single day I sit down at my Mac work machine and open the same 4 to 6 tabs in Sublime Merge. It's frustrating to have to add the tabs every day before I can start work.

**Preferred solution**

I'd like SM to reopen the same tabs that were already open during the last session.

**Alternatives**

A config option to turn this on and off would be acceptable.

**Comment by srbs** [comment]
@Capable-Disk4147, it should; how are you closing & opening the application? And did you change the preferences in anyway (`Preferences` > `Edit Settings...`)?

**Comment by Capable-Disk4147** [comment]
Thanks for the response @srbs! That's good to know because it means perhaps I have a weird setting or it's a temporary error that can perhaps be patched. :)

I am typically closing SM via shutting down my machine or by right clicking the dock to quit an application. However, this occurs even if I open some tabs and click the little red x in the app's window chrome. I just retested that last case to be certain.

I don't see any settings that I recall setting there, but I do see one set:
```json
{
	"side_bar_layout": "locations_as_column"
}
```

**Comment by srbs** [comment]
@Capable-Disk4147, those settings aren't any issue. How do you open SM? Do you open the application itself or are you using `smerge`? If `smerge`, are there any arguments?

> This occurs even if I open some tabs and click the little red x in the app's window chrome. I just retested that last case to be certain.

Keep in mind how applications work on macOS: closing the window (top left red x) only closes that window, not quit the application (even if it is the last). To get the session preservation behavior you want, you will need to always quit the application via top left app menu -> `Quit Sublime Merge`, right click dock icon -> `Quit`, or `Cmd+Q`.

**Comment by Capable-Disk4147** [comment]
@srbs I've literally never closed an application on a Mac without first closing the Window. I just thought of it as a very bad UX where you need to exit twice (red circle, then right click dock and close). I'm very much not a fan of Mac and have only been developing here for 3 months. I will play my irritation back on Apple.

Thank you for your patience and training even though it wasn't related to the product!

**Comment by srbs** [comment]
@Capable-Disk4147, not a problem!

**Comment by bravechamp** [comment]
Is there a way to prevent accidental window closes? A confirmation when multiple tabs open for example?
