### ISSUE TITLE
path query operator doesn't behave as expected

### ISSUE THREAD

**Issue by drguildo** [sublimehq/sublime_merge#1231]
**Version info**

 - OS: Windows 10.0.19041.1023
 - Build: 2059

**Description**

When searching using the `path` query operator, wildcard patterns don't seem to match directory names, only filenames. This might be just that the wording of the help text and the operator name is (IMHO) poor, but not being able to use pattern matching on directory names is a pain.

**Steps to reproduce**

1. Create a repository
2. Create a subdirectory "FOO" containing a file called "bar.txt" with some data in
3. Commit FOO/bar.txt
4. Hit CTRL+F
5. Type `path:*FOO*`

**Expected behavior**

The list of matching commits includes FOO/bar.txt.

**Comment by srbs** [comment]
The path query operator uses standard glob patterns.

Rules: (adapted from https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob)

1. `*`: matches any number of characters, without crossing directory boundaries (`/`)
2. `**`: matches any number of characters, but can cross directory boundaries (`/`)
3. `?`: matches a single character
4. `[aex-z]`: matches a single character of specified, in this case: a, e, x, y, or z (similar to character classes in regex)
5. all other characters match themselves
6. to match `*`, `?`, `[`, `]`, you can escape them by using the backslash character (e.g. `\*`)

Search terms that work within your example:

* `path:**/FOO/**` (any file that has `FOO` as an ancestor directory)
* `path:**/*FOO*/**` (any file that has `FOO` in the name of an ancestor directory)
* `path:FOO/**` (any file `FOO` as the first directory)
* `path:FOO/*` (all files within FOO dir)

**Comment by drguildo** [comment]
@srbs Thanks for the info. My understanding of how globbing works was overly simplistic and incorrect. Sorry about the noise.
