### ISSUE TITLE
Failed to initialize OpenGL rendering

### ISSUE THREAD

**Issue by Toby222** [sublimehq/sublime_merge#1254]
**Version info**

 - OS: Windows 10 Pro, 21H1
 - Build: all

**Description**

I recently started getting these messages on the work userprofile of my PC, though it worked fine in my private one until then.
As of today, it's stopped working on both profiles, despite nothing changing as far as I'm aware. 

I checked, and apparently my device doesn't support 4.1, which makes me question why it worked (for several years) until now and suddenly stopped working, and if it's perhaps possible to circumvent with some options that I changed unwittingly?

Reinstalled, and also tested it with older builds to see if it was some update.

**Steps to reproduce**

None beyond starting the app.

**Screenshots**
OS Version:
![OS Version](https://user-images.githubusercontent.com/14962962/132092327-24d577f7-112c-454d-8a0f-68771028cd4f.png)

The error message:
![Error message](https://user-images.githubusercontent.com/14962962/132092204-7e6d4db5-30cf-4585-97b6-1bf20a6c4216.png)

Supported OpenGL of my device as per OpenGL Extensions Viewer:
![OpenGL version](https://user-images.githubusercontent.com/14962962/132092276-38cc5a96-7d7f-4946-8607-43c51b35ddff.png)

**Comment by srbs** [comment]
To get SM to run again, you'll need to disable hardware acceleration by hand:

1. edit your preferences file: `%APPDATA%\Sublime Merge\Packages\User\Preferences.sublime-settings` (adapted from [src](https://www.sublimemerge.com/docs/packages) for Windows)
2. change the `hardware_acceleration` value to `none`
3. or add it to the JSON object if missing:
 ```
{
    "hardware_acceleration": "none"
}
```

**Comment by Toby222** [comment]
Yup, that worked, thanks.

**Comment by srbs** [comment]
@Toby222, I feel like this is a legitimate bug & probably should stay open.

@dpjohnst, I'm thinking it would be ideal for SM/ST to disable hardware acceleration anytime the driver doesn't support the required OpenGL version, preferably notifying the user when done. Similarly for SM, disable the preference option.
