### ISSUE TITLE
Open a terminal where git commands may be pasted and executed

### ISSUE THREAD

**Issue by PetrKryslUCSD** [sublimehq/sublime_merge#1257]
**Problem description**

When I find a solution to some complex git problem it often comes in the form of a bunch of git
commands.

**Preferred solution**

 It would be nice to open a command window on the current repository 
from within SM and execute those commands there. Something like "Open containing folder",
except that the folder would be opened in terminal.

**Comment by srbs** [comment]
duplicates #186

A workaround can be found here: https://github.com/sublimehq/sublime_merge/issues/186#issuecomment-618228195

**Comment by PetrKryslUCSD** [comment]
Well, what I meant here was simple a way to execute git commands not implemented/included in SM. I know SM echoes the git commands it executes, so why not allow the user to submit their own commands?

**Comment by srbs** [comment]
@PetrKryslUCSD, more like #201 then?

**Comment by PetrKryslUCSD** [comment]
Yes!
