### ISSUE TITLE
Changing theme of free version leads to chaos

### ISSUE THREAD

**Issue by philosopherdog** [sublimehq/sublime_merge#1259]
**Version info**

 - OS: [e.g. macOS 10.14, Windows 10, Ubuntu 18.04]
macOS 11.5.2
 - Build: [e.g. 1062 - type "About" in the command palette]
 2059

**Description**
A description of what the bug is.
Try to change the theme to dark in unreg version.
On restarting the app the window cannot be located in multi display setup. 
Eventually I got it onscreen although there was only a black screen and change the setting by toggling it to light and quitting.

**Steps to reproduce**

1. using unreg version set the theme to dark
2. restart using multi display setup

**Expected behavior**

A description of what you expected to happen.
The app.

**Screenshots**
Nothing to see except a black screen

**Comment by dpjohnst** [comment]
Hi @philosopherdog,

Thanks for reaching out - currently theme customization is only available with a valid license.
Could you confirm how you're changing the theme?

Thanks,
\- Dylan from Sublime HQ
