### ISSUE TITLE
add or allow the use of the "--allow-unrelated-histories" flag

### ISSUE THREAD

**Issue by ghylander** [sublimehq/sublime_merge#1260]
**Problem description**

When merging from remote branches, trying to merge changes will results in "Refusing to merge unrelated histories". Can't add flags to the merge commands other than "--no-commit" and "--squash" from sublime merge 

**Preferred solution**

Allow the use of the "--allow-unrelated-histories" flag to force merges

**Alternatives**

Can't think of any

**Screenshots**
Here's the result of running the merge with and without the unrelated histories flag

if there are any merge conflicts, you will be able to solve them through the sublime merge gui (just like any other merge with conflicts)

![image](https://user-images.githubusercontent.com/74593034/133059155-57e3cdc7-06d6-4013-b3cf-f16fb0c0f147.png)

**Comment by ghylander** [comment]
as clarification, github does not allow creating private forks of public repositories. To circumvent this, the solution is to add the public repository as a remote branch to a private repo.  To avoid issues, i found it's best to create an empty repo and merge the upstream branch there. This raises the "Refusing to merge unrelated histories" error, and using the above flag is the only way to force the merge/rebase, etc

**Comment by srbs** [comment]
As a workaround for now, you can add your own `Merge Unrelated Histories` command.

**Comment by ghylander** [comment]
what do you mean?
i see no setting to create/add your own commands

**Comment by srbs** [comment]
Docs for adding custom commands: https://www.sublimemerge.com/docs/custom_commands

**Comment by ghylander** [comment]
I saw this has been addressed in build 2068, so i'll close it
