### ISSUE TITLE
macOS 11 Maximising Doesn't Work

### ISSUE THREAD

**Issue by thoran** [sublimehq/sublime_merge#1264]
**Version info**

 - OS: macOS 11.5.2

**Description**

Double-clicking on the title bar does not maximise.
Double-clicking on window corners does not maximise.

**Steps to reproduce**

Pick any SM window and double click on the title bar or a window corner.

**Expected behaviour**

Double-clicking on the title bar does maximise.
Double-clicking on window corners does maximise.

**Comment by rukano** [comment]
Wanted to report this as well. Is quite annoying when changing screens... :)

**Comment by dpjohnst** [comment]
Hi all,

Thanks for reporting this!
This has been resolved in Sublime Merge build 2077.

Kind regards,
\- Dylan
