### ISSUE TITLE
Option to always show tab bar

### ISSUE THREAD

**Issue by samholmes** [sublimehq/sublime_merge#1268]
**Problem description**

If you have two windows and only one repo open in each window, there is no way to drag the tab in one window into the other window to combine the two windows into one window with two tabs. This is because the tab bar is not visible when there is only one tab opened in a window.

**Preferred solution**

An option in the settings that enables a mode to always show tab bar rather than hide it when there is only one tab in a window.

**Comment by srbs** [comment]
duplicates: #848 
see also: #760

**Comment by dpjohnst** [comment]
Hi @samholmes,

Thanks for sharing this feedback!
As this is a duplicate, I'll be closing this issue. Feel free to subscribe to the duplicate issue @srbs has linked above to continue to receive updates on it.

Cheers,
- Dylan
