### ISSUE TITLE
If the cloning is interrupted, do not remove directory.

### ISSUE THREAD

**Issue by jiucenglou** [sublimehq/sublime_merge#127]
In my working place, I need to log onto a gateway before I can access internet. Unfortunately, from time to time the gateway disconnects me, and then I need to log to regain the internet access.

When I am disconnected by the gateway, the cloning is interrupted. With SourceTree or GitHub Desktop, the local directory (including the .git directory) is kept. It seems to me that git can resume the download when I log onto the gateway and run git clone again. On the contrary, Sublime Merge removes the local directory, which means I have to download from the very beginning after being disconnected. 

**Preferred solution**

I would prefer Sublime Merge to keep the local directory if the git clone is not completed.

**Comment by dpjohnst** [comment]
Hi @jiucenglou,

Thanks for sharing your feedback.

Sublime Merge doesn't actually make any writes itself, and relies on Git to perform all write operations.
Unfortunately we cannot control what Git does when cloning (and is interrupted).

As such, I'll be closing this issue.

Kind regards,
\- Dylan
