### ISSUE TITLE
Hover text/tooltip doesn't disappear

### ISSUE THREAD

**Issue by JohannesEH** [sublimehq/sublime_merge#1271]
**Version info**

 - OS: Windows 10
 - Build: 2059

**Description**

Sometimes when you hover your mouse cursor over a list element or button and a tooltip appears it doesn't disappear again and sticks around till you restart the app. Tooltips for other elements continue to function. You can't fix it by hovering the same element and exiting the element again though.

**Steps to reproduce**

Haven't found a reliable repro. I guess, just use the app. Hover various buttons, commits etc.

**Expected behavior**

The tooltip disappears after mouse leaves button/element etc.

**Screenshots**

The green circle is a properly functioning tooltip. The red one is a lingering branch name tooltip from another repo.

![image](https://user-images.githubusercontent.com/118692/134644745-52d69c34-27d8-442c-8941-bd4774925382.png)

**Comment by srbs** [comment]
possible duplicate: #1180, #982

**Comment by dpjohnst** [comment]
Hi @JohannesEH,

Sublime Merge 2086 (development build) has been released which fixes this.
This fix will also be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ
