### ISSUE TITLE
[UX] Copy path/filename of staged/conflicting files 

### ISSUE THREAD

**Issue by sovcharenko** [sublimehq/sublime_merge#1272]
**Problem description**

I'd like to be able to easily share file names/paths of changed/conflicting file names with my team

**Preferred solution**

Please allow copying file name/path of files in Working directory/Staged files into clipboard.

**Alternatives**
None

**Screenshots**

If applicable, add screenshots to help demonstrate the problem or proposed solution. This section may be omitted/removed.

**Comment by srbs** [comment]
related: #178

workaround: https://github.com/sublimehq/sublime_merge/issues/178#issuecomment-433111449

**Comment by sovcharenko** [comment]
Thank you! That solves the issue
