### ISSUE TITLE
Include GUI action for "git rebase --skip" while resolving conflicts

### ISSUE THREAD

**Issue by ZaLiTHkA** [sublimehq/sublime_merge#1276]
**Problem description**

While resolving merge conflicts during a "rebase" operation, there are action buttons in the top-right corner for "Abort Rebase" and "Continue Rebase", whereas the logging output for the command itself shows the following message:

```
error: could not apply d11ecb57... Subtitle fix
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

**Preferred solution**

Add a third button to the UI labelled "Skip This Commit", which would execute the `git rebase --skip` command.

**Alternatives**

This isn't really applicable here; as the only "alternative" here is to drop into a terminal and skip the commit _there_ before returning to SM to continue the rebase process.

**Comment by srbs** [comment]
Sublime Merge already supports this. When conflicts arise the action buttons are `Abort rebase` & `Continue rebase (skip)`. Once the conflicts are resolved, the second becomes `Continue rebase`.

**Comment by ZaLiTHkA** [comment]
Hmm... I've just spent the past 5 days doing nothing but rebasing branches and fixing merge conflicts in multiple repositories, and yet somehow I completely missed that.. 🤦🏼 Thanks @srbs. 👍🏼
