### ISSUE TITLE
`[K` prefixed at start of Rebase success message

### ISSUE THREAD

**Issue by tycrek** [sublimehq/sublime_merge#1277]
**Version info**

 - OS: Windows 10 64-bit
 - Build: Stable 2059

**Description**

I rebased a local branch to keep a clean commit tree and noticed the rebase confirmation message had a `[K` at the start, which I don't think is intentional.

**Steps to reproduce**

1. Have a local commit that is not on remote while also having remote commits that are not local
2. Rebase local on remote
3. Look at the success message after the rebase completes

**Expected behavior**

A normal success message.

**Screenshots**

![Screenshot of the bug](https://ass.rip/t9VMN9knh27Y/direct)

**Additional info**

If it helps, my Git version is `git version 2.28.0.windows.1`

**Comment by jfcherng** [comment]
https://github.com/sublimehq/sublime_merge/issues/827
