### ISSUE TITLE
Allow word wrap for long lines.

### ISSUE THREAD

**Issue by jiucenglou** [sublimehq/sublime_merge#128]
It would be more straightforward to see the differences for long lines with word wrap.

**Comment by jskinner** [comment]
Word wrap has been added in dev build 1088, at https://www.sublimemerge.com/dev

**Comment by k44me** [comment]
Nice! I would suggest that you add a view menu to the menu bar, which contains the word wrap option. I needed to find this issue, to realize this was implemented as a context menu entry... 

I like sublime merge, but I tend to have the feeling often, that what I want to do is probably implemented somehow and I just don't find where. But then again I would also consider myself a novice in terms of git itself, so maybe that's real issue. 

Anyways, should I open a feature request for this?
