### ISSUE TITLE
Spelling error in theme

### ISSUE THREAD

**Issue by michaelalandawson** [sublimehq/sublime_merge#1289]
**Version info**

 - OS: Windows 10
 - Build: 2060

**Description**

The word "sliding" is spelled "eliding" in the theme.

Enable inspection of the theme.

Open the console.

Ctrl + Alt + Click on a file name in the right-hand panel.

![sm-2](https://user-images.githubusercontent.com/39276677/137059674-e46504a1-65f0-4ee6-83ae-eefda2850526.png)

You should see the spelling error.

![sm-1](https://user-images.githubusercontent.com/39276677/137059774-296463e0-7a9d-4e47-9fa4-fb29beedcb80.png)

**Comment by michaelalandawson** [comment]
That's very interesting. I never heard of that word.  Thanks for the knowledge.

To view the control information in Merge's console, place this in Merge's settings file:
````
// log_control_tree=true allows inspecting of Merge's UI
// This is useful for modifying the theme.
// Ctrl + Alt + Click anywhere in the window and associated code will be displayed in the console.
"log_control_tree": true,
````

**Comment by srbs** [comment]
Awesome, my shot in the dark panned out!
