### ISSUE TITLE
Executable name in Linux help text (-h) is wrong

### ISSUE THREAD

**Issue by sergei-dyshel** [sublimehq/sublime_merge#129]
**Version info**

 - OS: Linux
 - Build: 1070

**Description**
Running `smerge -h` on Linux produces help text which mentions `sublime_merge` as executable:
```
Sublime Merge build 1070

Usage: sublime_merge path               Open the given repository
   or: sublime_merge search query       Search for commits in the current repository
   or: sublime_merge blame file [line]  Blame the given file in the current repository
   or: sublime_merge log file           Show the file history in the current repository

  -n or --new-window:      Open a new window
  -b or --background:      Don't activate the application
  -h or --help:            Show help (this message) and exit
  -v or --version:         Show version and exit
```

**Comment by jskinner** [comment]
The executable name is actually correct, it's just that smerge is a shell script that simply calls sublime_merge. This isn't ideal, but it makes our lives a fraction simpler.

If you symlink sublime_merge instead, you'll notice that argv[0] is reflected as expected.
