### ISSUE TITLE
History of previous commit messages crashes when containing a specific message

### ISSUE THREAD

**Issue by sylbru** [sublimehq/sublime_merge#1290]
**Version info**

 - OS: Linux Mint 20.1
 - Build: 2059

**Description**

When creating a commit with the following message:

    fix[form-spectaclec]: analyse métier résiste aux différences de longueur dues à des ligatures (chef de chœur vs chef de choeur)
    
    Closes #91

It appears to be corrupted in the history of previous commit messages (arrow next to the commit message editor), the first `é` being replaced by a U+FFFD �, displayed as FFFD in a square (there might be more, that’s all I can see in the dropdown). More importantly, when opening the history, it crashes after less than a second.

I tried really hard to reduce that message to a simpler one, but I couldn’t identify what was causing the issue. My many attempts showed a clear link between the crash and the corrupted character.

N.B.: When opening the history right after creating the commit (as will probably be the case when trying to reproduce the bug), the crash occurs and seems to prevent the message from staying in the history after restart. However, in my case, the commit message stayed (more time passed before I tried to use this function I guess), so the history of previous commits always crashes if I try to use it.

**Steps to reproduce**

1. Create a new empty repository and open it in Sublime Merge
2. Create a commit with the exact same message as mentioned above
3. Click the arrow next to the commit message editor.
4. In the dropdown, the message appears with a corrupted character; the app crashes right after that.

**Expected behavior**

It shouldn’t crash :) And the accented character should not be corrupted. I write commit messages in French and they usually contain lots of them, without any issue usually.

**Screenshots**
This screenshot was taken in the short interval before the app crashes:
![image](https://user-images.githubusercontent.com/3757523/137311461-cc4d7cf1-845a-4779-a6d9-aecfb93f62c6.png)

**Comment by dpjohnst** [comment]
Hi @sylbru,

Thanks for sharing this feedback!

This should now be resolved as of Sublime Merge Build 2064 (dev).
I'll reach out again when the new stable build is available.

Thanks,
\- Dylan from Sublime HQ
