### ISSUE TITLE
Dedicated shortcut key bindings for Fetch / Push / Pull

### ISSUE THREAD

**Issue by zvuc** [sublimehq/sublime_merge#13]
**Problem description**

Many Git GUI clients offer dedicated shortcut key bindings for most often used Push/Pull operations, but currently in Sublime Merge the fastest way you can do this now is to press Cmd+P, type `push`, hit Enter then press Enter again.

**Preferred solution**

It'd be great if there was an option to bind dedicated key combination to trigger Fetch/Push/Pull immediately. Personally I think `Cmd+Shift+F` (*F*etch), `Cmd+Shift+P` (*P*ush), `Cmd+Shift+L` (Pul*l*) are keys that are easy to remember. (I'm coming from Sourcetree)

**Alternatives**

I noticed others in the forums have suggested keys like `Cmd+ArrowUp`, `Cmd+ArrowDown` for Push/Pull respectively. 

Additionally, it would be great if there was some sort of way to easily access User Key binding preferences through app itself. Sublime Text provides an option like that but currently the configurable items in user preferences is very very limited in Sublime Merge.

**Comment by wbond** [comment]
It is possible to create your own keybindings using the same format at Sublime Text.  If you click on *Preferences > Browse Packages* you will be brought to the packages folder. Inside the `User` package folder you can create `Default.sublime-keymap` and create your own key bindings using the format described at http://docs.sublimetext.info/en/latest/customization/key_bindings.html.

**Comment by zvuc** [comment]
I did try manually opening up the default keymap json and adding items there to bind to `Cmd+Shift+P` and `Cmd+Shift+L`, but they didn't trigger the Push/Pull actions like you would expect. I know the replacement worked because I had to remove the default `Cmd+Shift+P` action that brings up the command input (which just doubles for `Cmd+P` in Merge's case) and it properly stopped triggering the command input after I saved + copied the altered keymap file.

That being said, you mentioned the 'Preferences' menu; My 'Preferences' menu in macOS menubar is grayed out, I thought that wasn't provided by this app in the first place. Is it not supposed to be grayed out? 

<img width="260" alt="image" src="https://user-images.githubusercontent.com/2870726/46267423-d4fa1100-c56f-11e8-987d-50c749b454ee.png">

I can still get the list of Preferences options through the command console, but it only has a few options (which is why I said there are very very limited options in the first post)

<img width="891" alt="image" src="https://user-images.githubusercontent.com/2870726/46267447-01ae2880-c570-11e8-8372-3a4c31e1dff4.png">

Regarding the preferences menu being disabled, I found this old intermittent bug after searching (https://forum.sublimetext.com/t/preferences-greyed-out-in-os-x/2706), perhaps it's somehow related?

**Comment by zvuc** [comment]
```
[
	{ "keys": ["super+shift+f"], "command": "fetch" },
	{ "keys": ["super+shift+l"], "command": "pull" },
	{ "keys": ["super+shift+p"], "command": "push" }
]
```

After the latest update (1070, Stable channel) my preferences button has come back again so I found my user preferences folder where I successfully created a `Default.sublime-keymap` file for Merge and confirmed the key bindings were registered properly to appropriate commands:

<img width="1012" alt="pasted_image_11_10_2018__15_24" src="https://user-images.githubusercontent.com/2870726/46784709-1e194480-cd6a-11e8-94af-2d75749e0f30.png">

(I could see the keys were added as labels in command palette)

However, when I actually press the key combinations, only Push out of the 3 above actually worked. Pull and Fetch did not trigger when I pressed the keys, and only worked when I manually clicked the button on the toolbar or triggered through the command palette. Perhaps this is another bug?

**Comment by jskinner** [comment]
Default key bindings have been added for Push and Pull in Dev Build 1071, at https://www.sublimemerge.com/dev.

Default key bindings for fetch are unlikely (we do a `pull --ff-only` by default, which IMO supersedes fetch for the common usage scenarios), but that ultimately depends on community feedback.

These changes should be migrating to the stable channel sometime next week.
