### ISSUE TITLE
Sublime Text 4 Windows 11 packages broken

### ISSUE THREAD

**Issue by ShePastAway0** [sublimehq/sublime_merge#1301]
**Version info**

 - OS: Windows 11 21H2 (build 22000.258)
 - Build: Sublime Text 4 (4113)

**Description**

Packages don't work properly. i.e. Jedi Autocomplete & Anaconda. Packages installed succesfully but:
1) Jedi - autocomplete don't work. Manual configuration doesn't help. Just shows nothing.
2) Anaconda - connection error at startup, something with sockets about handler on localhost.

Also on Sublime Text 3 shift+key broken after package installation. i.e. shift+9 don't print ) but do nothing. But shortcuts work i.e. shift+ctrl+p works.

OS clean install from official ISO. No tweaks or possible conflicting software installed. On Windows 10 all works perfectly with same steps performed without any additional configuration. Other packages not tested. Sublime restart didn't help. Clean portable Sublime shows same behaviour. Sublime 3 also don't work. On Windows 10 both versions work perfectly. Can that be caused different indexing policy in Windows 11?

**Steps to reproduce**

1. Install packages above
2. Create empty .py file and try to write some python code
3. No autocomplete or hints from packages shown

**Expected behavior**

Autocomplete works out-of-box.

**Screenshots**

![image](https://user-images.githubusercontent.com/11247149/138010221-823fa934-b285-4044-a771-9f4d14277cda.png)
![image](https://user-images.githubusercontent.com/11247149/138010311-ff48930c-7c14-45b4-98aa-de447e389d9c.png)

**Comment by srbs** [comment]
@ShePastAway0, this is the Sublime Merge issue tracker, you'll want to close this one & re-open it on the [Sublime Text issue tracker](https://github.com/sublimehq/sublime_text/issues). Or one of the devs will move it once they see it.
