### ISSUE TITLE
Add key binding to "View More..." recent repositories

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#1304]
**Problem description**

To open a recent repository in a new tab I am used to hit <kbd>ctrl+t</kbd> and select the repo from recent list or "Select Overlay" dialog which is opened via "View More..." button.

The overlay however does often not show the desired repo to open. So it is very likely to hit the "View More..." button via mouse click to open the "Select Overlay" dialog.

**Preferred solution**

A more straight forward way of opening a repository in a new tab - maybe via key binding - would be appriciated.

The commands `quick_open_repository` and `quick_switch_repository` already exist (in Command Palette) to bring up the required "Select Overlay" dialog, but they are not bound to a key. _(Learned about them at the time of writing this issue)_.

I'd suggest to bind them as follows to improve a keyboard based navigation workflow:

```
    // Open repository in new tab (like ctrl+t to create new empty tab, but with a repo opened)
    {
        "keys": ["ctrl+shift+t"],
        "command": "quick_open_repository",
    },

    // Open repository in same tab
    {
        "keys": ["ctrl+shift+o"],
        "command": "quick_switch_repository",
    },
```

The first binding could easily replace the current worflow of createing a new empty tab first before opening a new repository.

A key binding such as <kbd>ctrl+1</kbd> ... <kbd>ctrl+3</kbd> to open one of the 3 displayed recent repositories in the empty tab overlay would probably be useful as well.

**Alternatives**

??

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/138547899-58915e25-bd2f-4730-946c-c372c1d694ad.png)

**Comment by dpjohnst** [comment]
Hi @deathaxe,

Thanks for sharing this feedback!

Currently `quick_switch_repository` is bound to the keybinding `ctrl+shift+o`
I'd suggest the following approaches to opening recent repositories in new tabs in a relatively quick fashion:

**a)** Open a new tab (`ctrl + t`), then switch to a recent repository (`ctrl+shift+o`)

**b)** Open the switch repository dialog (`ctrl+shift+o`) from anywhere, and `ctrl + left click` to open the repository in a new tab.

Hope this helps!

Cheers,
\- Dylan
