### ISSUE TITLE
Editing a commit message in a detached head doesn't work

### ISSUE THREAD

**Issue by miquella** [sublimehq/sublime_merge#131]
**Version info**

 - OS: macOS 10.13.6
 - Build: 1070

**Description**

After editing a commit message while in a detached head, the UI returns to a read-only state, appearing to show that the commit message has been modified. However, the commit list on the left doesn't show the updated commit message. Additionally, when clicking on the commit in the left panel, the commit message reverts to the un-edited version.

**Steps to reproduce**

1. Open repository.
2. Right-click on the HEAD commit in the commits list.
    * Select "Checkout Commit"
3. Click on the commit message.
4. Press `Cmd+Enter`.
5. Edit the commit message.
6. Press `Cmd+Enter` (or click "Save").
7. Click on a different commit in the commits list.
8. Click on the edited commit in the commits list.
    * Observe that the commit message has reverted.

**Expected behavior**

The commit message should be saved when clicking "Save", even when in a detached head.

**Comment by jskinner** [comment]
Thanks for the report, this is now fixed in Dev Build 1085 at https://www.sublimemerge.com/dev
