### ISSUE TITLE
Add console to execute git commands from command line

### ISSUE THREAD

**Issue by RaduW** [sublimehq/sublime_merge#1318]
**Problem description**

Sometimes it is easier to just type the git command with the desired parameters at command line.

I am evaluating sublime merge as an alternative to the Jetbrains IDEs git package,  and although I quite like Sublime Merge I constantly miss the ability to just go into a console window and do a quick git command from the command line and specify whatever parameters I need/want. While I currently issue 90% of the git commands from the IDE (jetbrains) I still rely on the IDE embedded terminal for 10% of the remaining cases. 

**Preferred solution**

It would be great if a console would be available where the user could type in the desired shell command,
or the existing git console would support writing dedicated git commands

**Alternatives**

* either embed a console that would initially start with the working directory set to the git repo root 
* (less than ideal) support some limited input of git commands in the existing git console

**Screenshots**

**Comment by willrowe** [comment]
This sounds similar to #201

**Comment by RaduW** [comment]
Yes, thanks @willrowe  for pointing it out. I'll close this one and +1 #201.
