### ISSUE TITLE
Commit list uncommit and base commit indicator

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#132]
**Problem description**

As the latest version now have "expand all by default" option, I thought it is good time to point out again there should be a good UI indication to differentiate commited commits from uncommited one.
https://github.com/sublimehq/sublime_merge/issues/81#issuecomment-428789292

At least put it as an UI enhancement for the future but not just remove the possibility.

**Preferred solution**

Make base commit bold OR
Add a marker for the base commit OR
Change the color for base commit to uncommit line to a difference one. Like SourceTree
![image](https://user-images.githubusercontent.com/4518597/46994792-783e4f00-d148-11e8-9cdb-1f36f3a3cefb.png)

**Screenshots**

There is no good indication whether this commit is the base commit or still commit above
![image](https://user-images.githubusercontent.com/4518597/46994715-2bf30f00-d148-11e8-809a-1b8d81b54991.png)

**Comment by wbond** [comment]
When you refer to the "base commit", are you referring to HEAD? If so, the HEAD ref annotation (rounded box with ref name) will be highlighted a different color from local and remote branches.

From your screenshot, it appears you haven't actually highlighted the HEAD commit, or some other bug is going on. In the screenshots you added to #81, I can see the teal annotation for HEAD in both.

**Comment by jasonycw** [comment]
Not necessarily the HEAD, but the last commit that is before the "Commit Changes" of current branch
![image](https://user-images.githubusercontent.com/4518597/47096018-ed9d4300-d260-11e8-890c-e1d7927f86e2.png)

If it is behind too much, I need to scroll up and down a few time to find the base commit. 
Like in the screenshot in the above post the left column show there are still commit on top, but is it another commit? or just the "Commit Changes" one?

**Comment by wbond** [comment]
> Make base commit bold OR
> Add a marker for the base commit OR
> Change the color for base commit to uncommit line to a difference one. Like SourceTree

You requested this in your original post. I've shown that we already perform option B "Add a marker for the base commit". The annotation for the "base" commit will be teal using the Merge theme. It will be the name of the branch you are working off of, or "HEAD" if you are in a detached head state.

**Comment by jasonycw** [comment]
Just updated to 1080, the new dot line is great finding base commit. Thanks!
![image](https://user-images.githubusercontent.com/4518597/47401468-19925a00-d774-11e8-8078-8d1992f9d158.png)
