### ISSUE TITLE
sublime_merge removes lines starting with whitespace before git's core.commentChar character

### ISSUE THREAD

**Issue by CheyenneWills** [sublimehq/sublime_merge#1324]
**Version info**

 - OS: Gentoo current maintenance
 - Build: 2062

**Description**

Lines that start with whitespace followed by git's commentChar ('#' default) are removed by sublime_merge when saving the commit message.  
e.g.

```
# comment and should be removed
      # not a comment and should be left alone
```

According to the git documentation for commentChar

> core.commentChar
> Commands such as commit and tag that let you edit messages consider a line that begins with this character commented, and removes them after the editor returns (default #).

Changing the core.commentChar to something else does not alter the behavior, for example changing core.commentChar to ';' will delete lines starting whitespace ;

To restate the problem using a "regular expression":

Only lines that are:  '^<core.commentChar>' should be treated as comment lines and not '^\s+<core.commentChar>'

**Steps to reproduce**

1. Edit a commit message
2. add a line that starts with whitespace followed by the current core.commentChar (e.g.  '      # something')
3. save or commit the change

**Expected behavior**

Lines that do not specifically start with the core.commentChar should not be treated as comments.

**Comment by srbs** [comment]
related: #1307

**Comment by dpjohnst** [comment]
Hi @CheyenneWills,

Thanks for sharing this feedback!

This should now be resolved as of Sublime Merge Build 2064 (dev).
I'll reach out again when the new stable build is available.

Thanks,
\- Dylan from Sublime HQ

**Comment by CheyenneWills** [comment]
> Hi @CheyenneWills,
> 
> Thanks for sharing this feedback!
> 
> This should now be resolved as of Sublime Merge Build 2064 (dev). I'll reach out again when the new stable build is available.
> 
> Thanks, - Dylan from Sublime HQ

Thanks.. I've grabbed the development version of SM and an initial test shows that it does correct the problem.

Thanks :)
