### ISSUE TITLE
How do I rebase in the Sublime Merge?

### ISSUE THREAD

**Issue by nooni85** [sublimehq/sublime_merge#1325]
How do I same effects in Sublime Merge following command?

git rebase -i HEAD~10

**Comment by srbs** [comment]
@nooni85, Sublime Merge does not currently have interactive rebase support.

**Comment by dpjohnst** [comment]
Hi @nooni85,

Thanks for reaching out!

As @srbs mentioned, Sublime Merge doesn't provide an interactive rebase UI.
That being said, we do have a selection of commit editing tools which use interactive rebase under the hood.

Sublime Merge supports:
- Editing commit messages
- Editing commit contents (changes)
- Moving commits up and down
- Squashing commits together
- Dropping commits

For more information, see the following relevant articles:
https://www.sublimemerge.com/docs/getting_started#editing_commits
https://www.sublimemerge.com/blog/sublime-merge-tips-editing-git-commits

Feel free to also give this issue a thumbs up if you'd like to see interactive rebase support added: https://github.com/sublimehq/sublime_merge/issues/1194

Kind regards,
\- Dylan
