### ISSUE TITLE
Copy multiple file path in a commit

### ISSUE THREAD

**Issue by beijingjazzpanda** [sublimehq/sublime_merge#1328]
**Problem description**

Select a commit, go to **Files** tab, If I want to copy the file path, I can only copy one file path at a time by right-clicking each file.

**Preferred solution**

The Sublime Merge should provide a similar function that when right click on "MODIFIED FILES", a "copy all file path" can be used.

**Alternatives**

Or can multiple select some files, and when right-clicked, a "copy selected file path" function is provided.

**Screenshots**

![2021-11-17_161509](https://user-images.githubusercontent.com/10892928/142161514-6bb966a2-8e41-4e95-ad28-5a48152d0780.png)

![2021-11-17_161924](https://user-images.githubusercontent.com/10892928/142162135-38256427-4a2c-4f8d-8ee4-73371e303043.png)

**Comment by srbs** [comment]
alternative related: #381

**Comment by beijingjazzpanda** [comment]
Thanks, I will close the issue, redirect to #381
