### ISSUE TITLE
Commit author is not preserved when editing a commit

### ISSUE THREAD

**Issue by kakra** [sublimehq/sublime_merge#1332]
**Version info**

 - OS: Gentoo Linux 17.1
 - Build: Stable 2020

**Description**

Sometimes I need to amend single commits in the history of a merge or rebase after finding issues with such an operation. Doing so will overwrite the author of the commit with my own identity.

**Steps to reproduce**

1. Right click on a older commit, select "Edit commit contents"
2. Make your changes
3. Commit your changes
4. Discover that the commit author has changed
5. This also applies to cherry picking when I split cherry picks to multiple commits

**Expected behavior**

When running a cherry pick and amending the commit, the author should not change: The commit changes are still authored by the original author. If anything, I'd like to select whether I keep the original author or insert my own identity but the latter is usually done by adding a "Co-authored-by" tagline.

**Comment by stinos** [comment]
Both 'edit commit contents' and 'split cherry picks' as far as I'm aware both mean (in git terms) creating a completely new commit (unlike amending commits or changing commit message), so it is expected that you are the new author and as such SM shouldn't assign another author to them. You could change the author afterwards with e.g. https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by kakra** [comment]
That's not helpful because it requires going to a different environment and amending the commits manually. Sublime Merge should have an option to do that from within the application. It may not even default to that behavior, but the commit button should have an option to use a different author.

**Comment by stinos** [comment]
Only having it on the commit button i.e. for commits you make yourself is a bit limited so if anything, I'd rather have a `change commit author` and `change comitter` then because those are more generic. That being said, I'm pretty sure these can be done as custom actions, perhaps someone can chime in on that.

**Comment by kakra** [comment]
Ah yes, custom actions... I didn't think of that. I'll try.

BTW: Sometimes during rebase it happens that some lines go to the wrong commit, so committing during rebase or cherry-picking with keeping the original author is a valid option - it would be more convenient to have it integrated within that work-flow. Most other Git tools allow overwriting the author during commit, having an additional field above the commit message which has the author identity would be helpful (also as a reminder for committing with the correct author should you use multiple identities yourself).

**Comment by srbs** [comment]
duplicates: #728
see also: #744

**Comment by kakra** [comment]
Okay thanks, closing as duplicate of #728 but #744 sounds useful indeed (tho, I can manually just add the co-authored lines to the commit message, that's much less of a hassle as changing the actual author).
