### ISSUE TITLE
Variable menu item Is there a translation interface?

### ISSUE THREAD

**Issue by maboloshi** [sublimehq/sublime_merge#1341]
<img width="346" alt="屏幕截图 2021-11-30 140700" src="https://user-images.githubusercontent.com/7850715/143994623-63623f29-c894-4f42-b31b-eb86c4967585.png">
<img width="248" alt="屏幕截图 2021-11-30 140915" src="https://user-images.githubusercontent.com/7850715/143994808-be1c58e8-c80f-4f33-91ad-0e04d6d83b67.png">
Corresponding menu file("Commit.sublime-menu"):

```json
	{
		"command": "revert_commit"
	},
	{
		"command": "show_command_palette",
		"args":
		{
			"command": "cherry_pick",
		}
	},
	{
		"command": "hide_all_commit_refs",
		"args": {"commit": "$commit"}
	},
	{
		"command": "hide_all_refs_except_refs_at_commit",
		"args": {"commit": "$commit"}
	},
```
There are also `Undo`, `Redo` etc.

**Comment by dpjohnst** [comment]
Hi @maboloshi,

Thanks for sharing this feedback.

We currently don't have a translation interface, however, you can provide your own custom captions to these commands.
For example, you can override the menu text with:
```
{
	"command": "revert_commit",
	"caption": "My Caption",
},
```

Hope this helps!

Kind regards,
\- Dylan from Sublime HQ
