### ISSUE TITLE
Does not escape path to Sublime Text as default Editor Path

### ISSUE THREAD

**Issue by elliotchance** [sublimehq/sublime_merge#1343]
**Version info**

 - OS: macOS 11.6
 - Build: 2063

**Description**

Without specifying an Editor Path it does not correct escape the path to Sublime Text.

**Steps to reproduce**

I have created the following command:

```json
    {
        "caption": "Interactive Rebase…",
        "command": "git",
        "args": {"argv": ["rebase", "-i", "$select_branch"]}
    },
```

When I run it, Sublime Text fails to open because the path is not correctly escaped (for the space):

```
/Users/elliotc/.aw/pex_resources/scripts/binaries/editor_wrapper.sh: line 6: "/Users/elliotc/Downloads/Sublime: No such file or directory
error: There was a problem with the editor 'DURATION_FILE="/var/folders/4r/221cnlpd7qld297_60lj7vzw0000gn/T/git-XXXX.441kmnGI" ORIG_EDITOR="\"/Users/elliotc/Downloads/Sublime Text.app/Contents/SharedSupport/bin/subl\" --wait" "/Users/elliotc/.aw/pex_resources/scripts/binaries/editor_wrapper.sh"'.
```

`cat /Users/elliotc/.aw/pex_resources/scripts/binaries/editor_wrapper.sh`:

```sh
#!/usr/bin/env bash

# DATE_CMD env is set and exported from wrapper_common.sh

START_TIME=$("$DATE_CMD" +%s%3N 2>/dev/null)
($ORIG_EDITOR "$@")
EXIT_CODE=$?
END_TIME=$("$DATE_CMD" +%s%3N 2>/dev/null)

# write interactive time spent with the editor to a temporary file
# this file will be used in the post step of the command wrapper
echo -n $((END_TIME - START_TIME)) > "$DURATION_FILE"
exit $EXIT_CODE
```

**Expected behavior**

Sublime Text should open with the git rebase todo list.

**Comment by elliotchance** [comment]
I've tried several ways to get around this without success:

1. Creating a symlink to avoid the spaces in the path:

```
ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
```

And set the Editor Path to `/usr/local/bin/subl`:

```
/Users/elliotc/.aw/pex_resources/scripts/binaries/editor_wrapper.sh: line 6: "/usr/local/bin/subl": No such file or directory
error: There was a problem with the editor 'DURATION_FILE="/var/folders/4r/221cnlpd7qld297_60lj7vzw0000gn/T/git-XXXX.Og74p4Ef" ORIG_EDITOR="\"/usr/local/bin/subl\" --wait" "/Users/elliotc/.aw/pex_resources/scripts/binaries/editor_wrapper.sh"'.
```

2. The same thing does not work if i just try to use `subl` as the Editor Path.

3. I thought SM might not like the symlink, so I even copied the binary:

```
cp "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
```

Still no luck (same error). I've made sure in both cases `subl` has execute permissions.

**Comment by srbs** [comment]
What configuration do you have set to cause SM to call `editor_wrapper .sh`?

**Comment by elliotchance** [comment]
@srbs I tried a combination of no configuration (default) or specifying different editors as explained, is there something I'm missing?

**Comment by srbs** [comment]
@elliotchance, my question is _how_ is SM calling `editor_wrapper.sh`?

**Comment by elliotchance** [comment]
Oh, I have no idea. `editor_wrapper.sh` is part of the SM internals.

**Comment by srbs** [comment]
No it isn't. It's located at `/Users/elliotc/.aw/pex_resources/scripts/binaries/editor_wrapper.sh`, which is not within the `Sublime Merge.app` bundle.

**Comment by elliotchance** [comment]
I'm sorry, I take that back. Just before your reply I noticed that must be part of my environment. Indeed this is not a bug with SM.

**Comment by srbs** [comment]
Not a problem!
