### ISSUE TITLE
Add the capability to fetch tags from the remote repositories

### ISSUE THREAD

**Issue by muellerkyle** [sublimehq/sublime_merge#1353]
**Problem description**

Sublime Merge appears to lack the capability to update tags from the upstream repo. For us, this is important as we add tags to the commit that is currently installed on our development and qa servers. Which, requires us to delete and then re-create tags and push them to the upstream repo.

**Preferred solution**

Add a --tags options to the fetch command so that `git fetch upstream --tags` or `git fetch --all --tags` works.

**Alternatives**

The alternative is to run the command in a terminal manually.

**Screenshots**

If applicable, add screenshots to help demonstrate the problem or proposed solution. This section may be omitted/removed.

**Comment by srbs** [comment]
You can create a custom command to fetch with tags: https://www.sublimemerge.com/docs/custom_commands

**Comment by dpjohnst** [comment]
Hi @muellerkyle,

This was added in Sublime Merge build 2066 (development build).
This will be pushed to the stable channel in the next stable update.

Thanks,
\- Dylan from Sublime HQ

**Comment by muellerkyle** [comment]
Fantastic! 

Thanks

**Comment by muellerkyle** [comment]
Thanks for getting this in. I'll close it out to get this off of the list!
