### ISSUE TITLE
UX regression: Escape key does not close the search anymore

### ISSUE THREAD

**Issue by ratijas** [sublimehq/sublime_merge#1356]
**Version info**

 - OS: Arch Linux
 - Build: 2065

**Description**

When the search is active, Escape key closes it when the focus is in the search field. It used to work when the focus is not on a text field too, e.g. when browsing history, clicking on commits etc.

**Steps to reproduce**

1. Open any repository ...
2. Press Ctrl+F to enter search mode
3. Type something
4. Click on commits in the list
5. Press Escape

**Expected behavior**

Sublime Merge should exit from the search mode.

**Screenshots**

Focus is on the item under the cursor on the left. Escape key does nothing there. Only pressing Ctrl+F or pressing the search field and then typing Escape can close the search mode from this state.

![Screenshot_20211210_213953](https://user-images.githubusercontent.com/6737986/145624992-feb73934-dcdb-4d73-bef3-9de572aba17d.png)

**Comment by ratijas** [comment]
Besides, there is no shortcut to give the search field focus back either! Ctrl+F just exits the search mode completely, Escape does nothing, and Ctrl+L (my last resort which usually means to select everything in URL bar) does nothing too.

**Comment by stinos** [comment]
Can confirm, I've been hitting Esc the last couple of days, always wondering why nothing happened :)

**Comment by dpjohnst** [comment]
This should be resolved in Sublime Merge Build 2066

**Comment by ratijas** [comment]
It is fixed, indeed. Thanks!
