### ISSUE TITLE
Cherry pick no commit message only retains the first line

### ISSUE THREAD

**Issue by adamkerz** [sublimehq/sublime_merge#1359]
**Version info**

 - OS: Windows 10
 - Build: 2059

**Description**

When cherry picking with --no-commit and then committing, only the first line of the commit message is stored in the commit. I was just copying, committing, clicking edit commit message and pasting the full message in but that has now broken in 2063 (#1358)

**Steps to reproduce**

1. Open repository <any>
2. Run command cherry pick --no-commit
3. Add a multiline commit message
3. Click on Commit

**Expected behavior**

The commit message in full should be stored.

**Comment by dforrest-es** [comment]
@adamkerz, what did the 2nd line of the commit messages look like? (cherry picked and edited if different)

**Comment by srbs** [comment]
@adamkerz, what did the 2nd line of the commit messages look like? (cherry picked and edited if different)

**Comment by adamkerz** [comment]
Cherry picked and edited were typically different - I added a `Co-authored-by` tag. The git command looks like this and I suspect it's some escaping issue with the `\n`.

```
git commit -q -m $'Replace hash with browser history and fix nav urls (#225)\nCo-authored-by: Sergey xxxx <xxxx@gmail.com>\n'
```

I tried a simple message with only alphanumerics:
```
git commit -q -m $'Change title to ES\nsecond'
```

Same problem, only "Change title to ES" is left, with no trailing EOL char.

It just occurred to me that I'm using a git.bat file to set some env vars first:
```
@echo off
set PATH=%~dp0..\..\PortableGit\bin;%PATH%
set GIT_SSH=C:\Program Files\TortoiseGit\bin\TortoiseGitPlink.exe
set GIT_SSH_VARIANT=ssh
git %*
```

I'll remove it from the sequence and use the git.exe directly and try again without - that could be the cause of the escaping issues...

**Comment by adamkerz** [comment]
Yeah, looks like that batch file was the problem. Not the older version of git (still using git version 2.28.0.windows.1).

Apologies for the distraction. Now to figure out why I needed those environment variables set and how to do it for all the git clients I'm using.

**Comment by srbs** [comment]
> Apologies for the distraction.

Not a problem, glad you found the root cause!
