### ISSUE TITLE
Commit message can't start with  '#'

### ISSUE THREAD

**Issue by pagdot** [sublimehq/sublime_merge#1360]
**Version info**

 - OS: Windows 10
 - Build: 2063

**Description**

Commit message can't contain or at least start with  '#'.

When creating a commit with a message starting with '#', I get the error `error; switch `-m' requires a value`.

it seems like '#' isn't escaped properly and treated as a comment.

(Editing a commit message on created commit to start with '#' doesn't work either)

**Steps to reproduce**

1. Open repository
2. make a change and stage the file
3. Set commit message to `#Test`
4. press "Commit 1 file"

**Expected behavior**

Commit happens with correct message

**Screenshots**

![grafik](https://user-images.githubusercontent.com/2229858/145986911-da748f55-f4a8-429a-8d50-85e8c6374608.png)

(redacted file names)

**Comment by srbs** [comment]
duplicate of #1307

**Comment by pagdot** [comment]
Ok, sorry
