### ISSUE TITLE
Regression: Editing non-HEAD commit message resets the Author information of all later commits

### ISSUE THREAD

**Issue by howeaj** [sublimehq/sublime_merge#1365]
**Version info**

 - OS: Windows 10
 - Build: 2063
 - git version 2.33.1.windows.1

**Description**

Starting from build 2063, modifying a commit message resets the Author of all subsequent commits to have the author of the edited one.

The issue is not present in build 2059 (which I have reverted back to in able to do what I need to do, and won't be able to update to later versions until this is fixed)

**Steps to reproduce**

CTRL-Enter edit commit message of a non-HEAD commit, when the HEAD commit (or any others in-between) have a different Author.

**Expected behavior**

CTRL-Enter to edit commit message should never modify any Author information anywhere.

**Screenshots**

n/a

**Comment by dpjohnst** [comment]
Hi @howeaj,

Thanks for reporting this issue - we've identified the cause of the issue, and are working to resolve it.
I'll keep you updated as things progress further.

Thanks,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Hi @howeaj,

This should now be resolved as of Sublime Merge Build 2067 (development build) and will be fixed in the next stable build.

Thanks,
\- Dylan

**Comment by howeaj** [comment]
Great, thanks :)
