### ISSUE TITLE
Regression: Select and press Enter to [un]stage lines is broken

### ISSUE THREAD

**Issue by ratijas** [sublimehq/sublime_merge#1366]
**Version info**

 - OS: Arch Linux
 - Build: 2066-1

**Description**

Stage lines feature is broken when using keyboard. It used to work by selecting text and pressing Enter, but now it stages/unstages the whole file.

**Steps to reproduce**

1. Open repository ...
2. Modify files & save
3. In either Working Directory or Staged Files view, select some lines in one chunk of many
4. Press Enter

**Expected behavior**

Only selected lines should become staged/unstaged.

**Comment by dpjohnst** [comment]
Hi @ratijas,

Thanks for sharing this feedback - I've been unable to reproduce this issue so far.

To diagnose this further, could you share you Sublime Merge debug information on the repository you're seeing this issue on?
This is available in the application menu under `Help > Debug Information`

Could you ensure that before you collect the debug information, the file/s you're seeing the issue on are in the modified/unstaged section. Additionally, feel free to remove any information you feel is sensitive such as file names, remote URLS, and author information. The most important section of the debug information is the `=== Our Modified Files Flag Information ===` section.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @ratijas,

Just a follow-up - I've identified the cause of the issue, and am in the process of fixing it.
I'll keep you updated as things progress.

Thanks,
\- Dylan

**Comment by ratijas** [comment]
Hi @dpjohnst,

It's good to know, 'cause it's still not consistent on my side either. I can't provide reliable steps to reproduce.

**Comment by dpjohnst** [comment]
Hi @ratijas,

This should be resolved as of Sublime Merge Build 2067. Let me know if you continue to see this issue on the latest build and I can investigate further.

Kind regards,
\- Dylan
