### ISSUE TITLE
Optional tag creation in Git Flow

### ISSUE THREAD

**Issue by davidmartos96** [sublimehq/sublime_merge#137]
**Problem description**

At the moment, when finishing a git flow hotfix a tag needs to be created, otherwise Sublime Merge shows an error.

**Preferred solution**

The ability to choose to create a tag or not. Could be at the moment of finishing the tag or a setting in the Configure Git Flow menu.

**Comment by BenjaminSchaaf** [comment]
Does Merge show an error because the tag Git Flow is trying to create already exists, or is it something else?

**Comment by davidmartos96** [comment]
It is not because it already exists. When running the finish hotfix command the palette asks you to select the hotfix branch. Once selected it asks for a tag. If you press enter leaving that empty the internal git command shows an error in the git output because it is trying to create an empty tag. The git commands looks like is passing the optional parameter to create a tag always, even if it was left empty intentionally.

**Comment by jskinner** [comment]
This is now fixed in 1079; pressing enter with no message will not create a tag now
