### ISSUE TITLE
Empty line in previous message listbox

### ISSUE THREAD

**Issue by verside2** [sublimehq/sublime_merge#1373]
**Version info**

 - OS: Windows 10 Pro 21H2
 - Build: 2067

**Description**

After insert commit with long message on Russian previous message listbox has empty entries. If click on it entry message will be inserted correctly.
File Session.sublime-session contains all entries (see below).

**Steps to reproduce**

1. Insert commit with message "**Fix: это очень длинный текст, который сломает отображение предыдущего комита**"
2. Open previous messages listbox.

**Expected behavior**

Empty entries should display correct text.

**Screenshots**

![image](https://user-images.githubusercontent.com/12224435/146958141-7fc436db-c05e-4235-aad5-293269168605.png)

**Comment by verside2** [comment]
It looks like it depends on the length of the string and language (in my case Russian).

Commit with message "**Fix: это очень длинный текст, который сломает отображение предыдущего комита**" and open previous messages.

**Comment by dpjohnst** [comment]
Hi @verside2,

Thanks for reporting this issue - we'll be investigating this further and will keep you updated.

Kind regards,
\- Dylan from Sublime HQ
