### ISSUE TITLE
Slow performance and freeze on large commit

### ISSUE THREAD

**Issue by ratcashdev** [sublimehq/sublime_merge#138]
**Version info**

 - OS: Win7, 64bit, SSD, 500Mb/sec performance
 - Build: 1075

**Description**

I had a particularly nasty repo (Oracle's 2nd donation pack of Netbeans to Apache). The first commit is basically over 114 thousand files. When clicking on the initial commit, sublime-merge freezes for approx 10-15 sec until the changes are loaded and UI elements populated.

Setup:
The ".git" folder is 1GB. The working folder more-less the same. Sublime-merge RAM consumption ~1GB. CPU utilization (while loading changes) 100% on a single core. The rest of the cores were idle.

Maybe paralellizing this task (if possible) could help.

Anyway, quite an achievement for sublime, given that SourceTree (my current daily helper) does it in 50 secs, same RAM, same CPU. And same UI freeze.

**Comment by jskinner** [comment]
Dev Build 1086 at https://www.sublimemerge.com/dev now handles very large commits efficiently

**Comment by ratcashdev** [comment]
Lovely! Two suggestions though.
1. I could not find the "Content View" in the sidebar, only a "View Tree" in the menu
2. In addition to the notification text (use the Content View) I would appreciate if it showed the button to open the tree directly
3. Changelog is missing this (very important) improvement.
