### ISSUE TITLE
git-lfs: command not found

### ISSUE THREAD

**Issue by howff** [sublimehq/sublime_merge#1384]
**Version info**

 - OS: Windows 10
 - Build: 2068 (the latest)
 - Git: bundled

**Description**

Cloning a repo gives the error:
```
Receiving objects: 100%
Resolving deltas: 100%
git-lfs filter process: git-lfs: command not found
fatal: the remote end hung up unexpectedly.
warning: clone succeeded but checkout failed.
git failed with exit code 128
```

**Comment by dpjohnst** [comment]
Hi @howff,

Thanks for reaching out to us.

It looks like the repository is set up to use Git LFS but it is unable to find Git LFS.
We do not bundle Git LFS with Sublime Merge by default.

Could you confirm whether or not you have Git LFS installed already?
If you're not sure how to do this, you can check by opening the command prompt and running `git lfs --version`.

If you don't have it already installed, you can install it here:
https://git-lfs.github.com/

Thanks,
\- Dylan from Sublime HQ

**Comment by howff** [comment]
Since you already bundle git, why can't you bundle git-lfs as well?

**Comment by dpjohnst** [comment]
Hi @howff,

As Git LFS is only used by a small portion of our community, we do not bundle it by default as it significantly increases the application size.

That being said, an improvement would be providing a way for users to download Git add-ons from within Sublime Merge as requested here: https://github.com/sublimehq/sublime_merge/issues/930

Please feel free to head over to that issue to up-vote it or share your thoughts.

Many thanks,
\- Dylan from Sublime HQ
