### ISSUE TITLE
Need to start three times

### ISSUE THREAD

**Issue by RSeidelsohn** [sublimehq/sublime_merge#139]
**Version info**

 - OS: Ubuntu 18.04.1 LTS
 - Build: 1074
- Two screens - one built in, one external (might be relevant)

**Description**

I use several different repositories at work I switch between. That might play a role here: Since a few days, when I want to start Sublime Merge, I have to start it three times in order to get a running process: I click the dock icon once, a small window appears and disappears immediately - no running sublime merge process (I use `ps ax | grep subl` for checking this). I do this a second time - same result. I do this a third time, and I end up with two Sublime Merge windows running. After that, I can close and restart Sublime Merge just normally. After a reboot I get the same result from above.

**Steps to reproduce**

Hard to tell. I have two repositories listed in my "Switch repository" dialog, although I use three different repositories (one regularly, one less regularly and one rarely). I once had three windows of Sublime Merge open at the same time, with three different repositories.

1. Click on the dock icon
2. Click on dock icon a second time
3. Click on dock icon a third time
4. Finally get two instances of Sublime Merge running

**Expected behavior**

Sublime Merge should start after the first click and not die immediately

**Screenshots**

n/a

I am happy to provide more details, e.g. logs, if someone can tell me how to get them.

Possibly related to  #142

**Comment by jskinner** [comment]
I believe this should be fixed in Dev Build 1076, please let me know if it's still happening for you

**Comment by RSeidelsohn** [comment]
Looks good so far - at home it's fine now, will check also at work tomorrow (though both systems are on Ubuntu, so it's probably fixed now). Thank you for the fast and many updates! This tool gets better and better every day.

**Comment by RSeidelsohn** [comment]
I can now definitely confirm that this bug is fixed. Thx!
