### ISSUE TITLE
Make possible to copy CommitHash in Summary

### ISSUE THREAD

**Issue by Artein** [sublimehq/sublime_merge#1391]
**Problem description**

As a user, I want to be able to copy Commit Hash from Summary tab.

**Preferred solution**

Either to be able to select commit hash, or to copy by double-click/context menu

**Alternatives**

None.

**Screenshots**

Not needed.

**Comment by Ultra-Instinct-05** [comment]
You can already do that by just right clicking on the commit hash in the `Summary` tab & picking the `Copy 'aabbcc...'`.

![image](https://user-images.githubusercontent.com/34304644/149750243-80d2600c-92ee-4d42-8b0b-d3607ce303ba.png)

**Comment by Artein** [comment]
True. Thank you @Ultra-Instinct-05!
