### ISSUE TITLE
Ability to start a merge resolution process on any named files

### ISSUE THREAD

**Issue by dlamblin** [sublimehq/sublime_merge#14]
# Problem description

I really like the Merge Resolution view and behavior (with it's 3/4 solution of swapping merged with base) and would like to use it even with files that aren't in the git repo and/or being merged. As the product has Merge in the name and can do diffs and merge resolution, I would have expected the option to take 3 arbitrary files and open a 3(+) way merge on them. EG I have a file in a current repo; I want to specify another file that is the common base and a third file that will be the staged changes and these are all separate.

In some cases I have a repo that has some files where a base version is not in the history at all and I have another change I'd like to merge in, from the other repo that does have the base in the history and some changes not reflected in this repo. I would like to select the three related files that I have on the file system (probably not all checked into the same repo) and view their diverged differences for manual merging.

# Preferred solution

This may not be simple because you're likely relying on git's diff based storage, but like: Merge[Tool] `filename.ext` `filename.base.ext` `filename.remote.ext` `filename.ext`
Where those are the backup, base, remote and local. I'd be using the same backup and local as in this case I want to make the result saved as a staged change to the local file in the repo. The base is something not tracked that was a specific older version perhaps older than the history of my repo, and the remote is some updates I want to bring in from an outside change to this base file, but I'm expecting, even without conflicts, that I have to manually review everything.

I would normally think the simplest way for me to do it is to check out from somewhere the base version and copy the file to `filename.base.ext`, check out the changes from elsewhere I want to bring in and copy them to `filename.new.ext` then open a 3-way merge with `filename.ext` `filename.base.ext` and `filename.new.ext`, or as shown in the prior paragraph. Because, to be honest, the alternative – committing the base in a branch, updating that with a commit of the existing version and then changing that to the new version to view it – provides me only one 2 way diff at a time. Without a forced merge conflict, I'm not going to see how both versions differ from the base and how to merge their intents together as clearly.

# Alternatives

The current work around is to do:

- git checkout -b base
- cp file.base.ext file.ext
- git commit
- git checkout -b orig
- git checkout -b new
- cp file.new.ext file.ext
- git commit
- git checkout orig
- git revert HEAD
- git commit
- sublime-merge merge new

Now you can finally open a merge resolutions view for each conflicted file, assuming there are conflicts. If there aren't you're out of luck, which may not have been the result you actually wanted to review.

This process could be automated with generated temporary files if need be…

# Screenshots

None available.

**Comment by dlamblin** [comment]
> If possible, can you reformat this using the Enhancement request template?

I hope that's satisfactory.

**Comment by dpjohnst** [comment]
Hi @dlamblin,

Thanks for using Sublime Merge!

Just a quick update - the latest dev build of Sublime Merge has added a mergetool mode to the ```smerge``` command line helper utility. You can run ```smerge --help``` for more details.

Kind regards,
\- Dylan Johnston
Software Engineer, Sublime HQ
