### ISSUE TITLE
Open tabs lost when using command line

### ISSUE THREAD

**Issue by Zwyx** [sublimehq/sublime_merge#1408]
**Version info**

 - OS: MX Linux 21 (`Linux mx 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux`)
 - Build: 2068

**Description**

I usually keep about ten tabs open. To open a new repository, I use the command `sbm .` (`sbm` being aliased to `/opt/sublime_merge/sublime_merge`; I can also use `smerge`).

If I run `sbm .` when Sublime Merge is already open, then it opens a new tab with my directory; perfect. However, if Sublime Merge isn't already open when I run `sbm .`, then Sublime Marge will open _with only the new directory_, all my other tabs will be gone, and I will have to manually open them again one by one.

**Steps to reproduce**

When Sublime Merge isn't running, open it with the command line, with the path of a repository.

**Expected behavior**

Sublime Merge opens, and a new tab with the new repository is added to the right of the existing tabs.

**Actually behavior**

All previously existing tabs are lost, only the one for the new repository is present.

**Comment by verside2** [comment]
I have same problem on Windows 10 Pro 21H2.
Open SM (when it closed) via ST's status bar and lost all opened tabs :(

**Comment by srbs** [comment]
See my summary comment on the forums for more details:

https://forum.sublimetext.com/t/saving-open-repo-tabs/54036/9

**Comment by Zwyx** [comment]
Hi `srbs`, sorry for my late reply and for having created this duplicate :man_facepalming:  I'll close this one in order to not bloat Sublime's issues.
