### ISSUE TITLE
`Stage All` doesn't honor `Filter`

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/sublime_merge#1412]
**Version info**

 - OS: Win10 21H2 19044.1503
 - Build: 2068

**Description**

I guess this is more of a design problem. The original question is "How can I stage a folder in SM like `git  add folder/` in git CLI" and I think I can do it with the `Filter`. However, the number of files are correctly updated but `Stage All` doesn't honor the `Filter` making it quite confusing.

https://user-images.githubusercontent.com/6594915/152651632-37e3d167-8724-400a-a35e-45c37873a34c.mp4

**Steps to reproduce**

1. Open repository
2. Do `Stage All` with `Filter`

**Expected behavior**

`Stage All` honors the `Filter`.

**Comment by srbs** [comment]
This was fixed in build 2069:

    * Files List: Stage filtered files using the file section context menus

**Comment by jfcherng** [comment]
Confirm fixed. Thanks!
