### ISSUE TITLE
No longer starts after upgrade to latest stable build (1075)

### ISSUE THREAD

**Issue by ransagy** [sublimehq/sublime_merge#142]
**Version info**

 - OS: Windows 10 x64 1803
 - Build: 1075 (as per the update dialog message and changelog file, can't verify in about dialog)

**Description**

Application no longer starts after last stable channel update. Process starts and quits, Generating a crash dump. After reinstalling from the site installer (marked as 1075) it no longer generates a dump, just quits on the spot.

**Steps to reproduce**

1. Run the app from start menu shortcut or directly from Explorer.
2. App quits without even showing a window.

**Expected behavior**

The app starts normally and is available to be used.

I don't see any other details right now; I don't have the old dumps either, probably accidentally deleted the old folder when reinstalling.

**Comment by ransagy** [comment]
@RSeidelsohn I was wondering if #139  was indeed related; let's assume it is, for now.

Downloading the 1070 installer from the site and uninstalling/reinstalling it makes it work again. I'll cancel upgrade messages for now.

**Comment by gabeio** [comment]
Just wanted to add some info here, this _seems_ to be specifically a Mojave issue, I had the issue on the one laptop which I run Mojave on but when I upgraded in High Sierra this wasn't an issue, but I also haven't customized my High Sierra one as much so it could be a setting too.

**Comment by jskinner** [comment]
Try Dev Build 1076 if you're seeing this - https://www.sublimemerge.com/dev

**Comment by ransagy** [comment]
Fixed for me as well in the latest stables, closing.
