### ISSUE TITLE
Font rendering issues - Check Updates dialog

### ISSUE THREAD

**Issue by zholobov** [sublimehq/sublime_merge#1429]
**Version info**

 - OS: macOS 12.2.1
 - Build: 2068

**Description**

Text rendered on Check Updates dialog button(s) sometimes has dark grey letters overlayed on white letters. See "p" letter in text "Open Changelog" on button on screenshot.

**Steps to reproduce**

1. Open Check Updates dialog

**Expected behavior**

Expected clean rendering.

**Screenshots**
<img width="498" alt="image" src="https://user-images.githubusercontent.com/907136/156213265-f49c3567-e9fc-4d6f-9ea1-a96e348e03de.png">

**Comment by dpjohnst** [comment]
Hi @zholobov,

Thanks for reporting this issue!

This looks like it's the same issue as https://github.com/sublimehq/sublime_merge/issues/1363, so I'm going to close this issue.
Feel free to head over to the linked issue above and subscribe to it to keep up to date.

Thanks,
\- Dylan from Sublime HQ
