### ISSUE TITLE
Opening a new repo with command palette open causes it to stick

### ISSUE THREAD

**Issue by todsleeman** [sublimehq/sublime_merge#145]
**Version info**

 - OS: MacOS v10.14
 - Build: 1075

**Description**

Opening a new repo with command palette open causes it to stick. You are ten unable to perform actions in the new repo that has been opened because the previous command palette is still there.

**Steps to reproduce**

1. Open a sublime merge window
2. Open the command palette
3. Open a different repo using Command + Shift + O

**Expected behavior**

The sublime merge window will switch to the new repo and all functionality will remain.

**Comment by jskinner** [comment]
Thanks for your report, this is now fixed in Dev Build 1076 at https://www.sublimemerge.com/dev
