### ISSUE TITLE
Search: `file:` path doesn't resolve absolute paths

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#1456]
**Version info**

 - OS: Windows 11
 - Build: 2069

**Description**

When calling "Line History" from within ST, SM is opened with the search field being displayed.

It however doesn't show the file's content/history, even after removing the line part of the search pattern.

It appears SM doesn't resolve the absolute file path correctly.

**Steps to reproduce**

1. Search for a file by absolute path

**Expected behavior**

1. Correctly resolve absolute path.
2. I'd appriciate to be able to enter path in OS specific style (`C:\Data\Sublime\Packages_CPP\C++\Symbol Index.tmPreferences`)

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/161386489-d6118da7-c2a3-4af8-995d-6181e756ecbe.png)

after converting absolute path to relative path manually desired file content is displayed

![grafik](https://user-images.githubusercontent.com/16542113/161386674-ccc7fd1b-975b-40f1-b63f-cb1b32cdb205.png)

**Comment by DavidW1024** [comment]
This issue is fixed in build 2073.
