### ISSUE TITLE
Text truncation fails

### ISSUE THREAD

**Issue by genericptr** [sublimehq/sublime_merge#1457]
**Version info**

 - OS: macOS 12.3 (Apple Sillicon)
 - Build: 2068
 
**Description**

Text is not truncated and overlaps some controls. This is the merge conflict resolution view.

<img width="972" alt="Screen Shot 2022-04-04 at 9 52 53 AM" src="https://user-images.githubusercontent.com/10937186/161466346-0e07b243-7da0-49f0-98bf-cf92f4391398.png">

**Comment by dpjohnst** [comment]
Hi @genericptr,

Thanks for reporting this issue - we'll be investigating this further.

Kind regards,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Hi @genericptr,

Thanks for your patience while this was investigated - this has been resolved in Sublime Merge build 2073.

Kind regards,
\- Dylan
