### ISSUE TITLE
Commit is folded after merge

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#146]
**Version info**

 - OS: Windows 10
 - Build: 1074

**Description**

With #105, setting `expand_merge_commits_by_default` to true, sometime commits are still folded after merge branch. It seems to not consistence as after I unfold the merge, the next merge is not merged.

**Steps to reproduce**

1. Open repository
2. Set `expand_merge_commits_by_default` to true
3. Merge branch
4. Merged and branch is folded

**Expected behavior**

All branches are not folded
Or an option to completely turn off fold commit behavior

**Comment by BenjaminSchaaf** [comment]
I can't seem to replicate the issue: Merging any branch results in either a fast forward or an expanded merge commit.

Could you provide more details as to how you were able to produce this?

**Comment by jasonycw** [comment]
Maybe due to some old branch saved the old version folded behavior?
I am not sure the cause as this only happen once a while especially when I merge branch which is a bit lag behind (like haven't merge for a few days)
After I expand the commit and merge the 2nd time, it usually doesn't fold

**Comment by jasonycw** [comment]
More info after facing the issue a few more days

My colleague use the stable version of Sublime Merge with folding commit enable, I use the latest dev version
Seems when the commit is push by him, my merge will always become folded again even I set it to unfold by default
![image](https://user-images.githubusercontent.com/4518597/47331677-78da6680-d6af-11e8-87eb-6fdebd04dd7f.png)

And the folding status is not saved between startup too, after I expand the commit, close SM, reopen it, they fold again

**Comment by jskinner** [comment]
This should now be fixed in Dev Build 1081
