### ISSUE TITLE
Ubuntu: Can't update to the latest version (2068) using apt repository 

### ISSUE THREAD

**Issue by KindDragon** [sublimehq/sublime_merge#1462]
**Version info**

 - OS: Ubuntu 20.04.4 LTS
 - Build: 2059

**Description**

Can't update to the latest version (2068) using apt repository 

**Steps to reproduce**

1. Configure stable apt repository https://www.sublimemerge.com/docs/linux_repositories
2. Install sublime-merge version from apt
3. Check sublime-merge version in About window (2059 for me)

```
❯ sudo apt-get update
❯ sudo apt-get install sublime-merge
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sublime-merge is already the newest version (2059).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
```

**Comment by dpjohnst** [comment]
Hi @KindDragon,

Thanks for reporting this issue - are you still seeing it?

Kind regards,
\- Dylan

**Comment by KindDragon** [comment]
Hi, it seems to be working now.

**Comment by srbs** [comment]
@KindDragon feel free to close the issue
