### ISSUE TITLE
git-lfs command not found

### ISSUE THREAD

**Issue by Zooce** [sublimehq/sublime_merge#147]
**Version info**

 - OS: macOS 10.14
 - Build: 1074
 - `$ which git` -> `/usr/local/bin/git`
 - `$ git --version` -> `git version 2.19.1`
 - `$ which git-lfs` -> `/usr/local/bin/git-lfs`
 - `$ git-lfs --version` -> `git-lfs/2.5.2 (GitHub; darwin amd64; go 1.11)`

**Description**

When staging several new files tracked by git-lfs, the following error is reported:
```
git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
```
I don't have an issue staging these files from the command line with `$ git add .`

**Steps to reproduce**

1. Setup git-lfs for a repo
  a. `$ git lfs install` // only have to do this once for the repo
  b. `$ git lfs track "*.pdf"` // just as an example
  c. `$ git add .gitattributes` 
  d. `$ git commit -m "LFS track PDF files"`
2. Add any file to the repository that you might want git-lfs to track (like a PDF)
3. Open that repository in Sublime Merge
4. Click "Stage All" twice to stage the new file
5. You should see the error mentioned in the Description section above

**Expected behavior**

The `git-lfs` command should be found, and LFS tracked files should be staged, when clicking "Stage All" twice.

**Screenshots**

<img width="747" alt="smerge_git_lfs_error" src="https://user-images.githubusercontent.com/5490155/47136081-6dc6a700-d267-11e8-90e2-4603ba26936f.png">

**Comment by jskinner** [comment]
What output do you get in the "Git Version Information" section, from the "Help > Debug Information" menu?

**Comment by Zooce** [comment]
@jskinner, here's the git version info from the Debug Information:
```
=== Git Version Information ===
Using Git: git (system)
git version 2.17.1 (Apple Git-112)
PATH: /usr/bin:/bin:/usr/sbin:/sbin
```
I set the version myself:
```
=== Git Version Information ===
Using Git: /usr/local/bin/git (custom)
git version 2.19.1
PATH: /usr/bin:/bin:/usr/sbin:/sbin
```
Still get the same error.

**Comment by jskinner** [comment]
git-lfs isn't in the path that git is being launched with, hence the error.

On Mac, we determine the path to launch git with by launching the default login shell, and asking it what the path is. Assuming you are using the default shell (bash), then you can add an entry to your path by making a `.bash_profile` file in your home directory with the line:

```
export PATH="/usr/local/bin:$PATH"
```

**Comment by Zooce** [comment]
I actually do have that exact line in `~/.bash_profile`, but one other thing I didn't mention is that I use Homebrew to manage my git installation, so both `git` and `git-lfs` are symlinked to `/usr/local/bin` from their corresponding Celler directories. Would this be an issue?

**Comment by jskinner** [comment]
Dev Build 1076 will report a bit more information in its Debug Information output now - can I get you to paste the "Git Version Information" section output again with 1076?

**Comment by Zooce** [comment]
Debug Information from 1076
```
=== Git Version Information ===
Using Git: /usr/local/bin/git (custom)
git version 2.19.1
PATH: /usr/bin:/bin:/usr/sbin:/sbin
environment variables loaded using: /bin/bash -l
```

**Comment by jskinner** [comment]
It looks like we're getting the login shell ok, but the PATH value we get from that is surprising. You can run `PATH='' /bin/bash -lc 'env | grep PATH='` in the terminal and paste in the output? That's similar to what Sublime Merge is doing to extract the path.

**Comment by Zooce** [comment]
```
$ PATH='' /bin/bash -lc 'env | grep PATH='
PATH=/usr/local/var/rbenv/shims:/usr/local/opt/jenv/shims:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Applications/Sublime Text Dev.app/Contents/SharedSupport/bin:/usr/local/opt/go/libexec/bin
```

**Comment by jskinner** [comment]
Build 1077 has a bit more information in the "Git Version Information" section that would be helpful to see.

1077 also has a new preference, "git_env", so you can explicitly set the path, and not rely of Sublime Merge getting it out of bash. You'll want to put something like this in your `Preferences.sublime-settings` file:

```
{
    "git_env":
    {
        "PATH": "/usr/local/bin:/usr/bin:/usr/sbin:/sbin",
    }
}
```

**Comment by Zooce** [comment]
@jskinner the new "git_env" preference worked. I used the same PATH you posted (and also cleaned up two old paths from `~/.bash_profile`. What's odd is that my PATH variable has all of those paths in it (in that order as well).
```
$ tr ":" "\n" <<< $PATH
/usr/local/var/rbenv/shims
/usr/local/opt/jenv/shims
/usr/local/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/TeX/texbin
/opt/X11/bin
```
I did a quick check and neither of the first two paths have anything related to git or git-lfs in them.

**Comment by Zooce** [comment]
Interestingly, I removed `/usr/local/var/rbenv/shims` and `/usr/local/opt/jenv/shims` from my path (since they're left over from previous work), also gave my user account write permission on `/usr/local/sbin`, and removed "git_env" from the Sublime Merge preferences, and staging the git-lfs tracked files worked. Not sure how useful this information is, but I figured it could help.

**Comment by git-commit** [comment]
This is also an issue on windows.
It looks like the bundled git already supports `git-lfs` when calling it through the git binary.
Why doesn't Sublime Merge use it this way?

**Comment by stiv-yakovenko** [comment]
I also have this problem on Windows 10. Will this be ever fixed?

**Comment by atteneder** [comment]
I had the same annoying error on macOS

Turned out I have both `.profile` and `.bash_profile` file, with the latter creating the correct `$PATH`. The Terminal app prefers the `.bash_profile`, if present. For GUI apps, apparently only `.profile` is relevant.

Thanks for the hints in this issue thread!

**Comment by dpjohnst** [comment]
Hi all,

This issue has been fixed in the latest build of Sublime Merge. It would be great if you could confirm this works on your end.

Thanks,
\- Dylan

**Comment by Zooce** [comment]
Just tried this out on Windows 10, and everything looks good. I can try on macOS later today.

**Comment by Zooce** [comment]
Works on macOS  10.15.5 as well!

I was going to try on Pop!_OS (the Linux VM I use) but I wasn't able to install `git lfs` (there's certainly a way, I just didn't try).

Thank you!!
