### ISSUE TITLE
Dev build 2070 starts with "Failed to initialize OpenGL rendering: Unable to create a GL context"

### ISSUE THREAD

**Issue by kortschak** [sublimehq/sublime_merge#1470]
**Version info**

 - OS: Ubuntu 18.04
 - Build: 2070

**Description**

Dialog with "Failed to initialize OpenGL rendering: Unable to create a GL context" appears on start up if OpenGL is enabled in advanced preferences.

Execution continues and appears to be normal after this. Disabling OpenGL prevents the complaint.

**Steps to reproduce**

1. Ensure that OpenGL is enabled in advanced preferences.
2. Restart `smerge`

**Expected behavior**

Quietly successful start up.

**Screenshots**

![Screenshot from 2022-04-24 14-24-21](https://user-images.githubusercontent.com/275221/164957317-f927cee7-0604-441a-9d04-b71bfec4d1b8.png)

**Comment by dpjohnst** [comment]
Hi @kortschak,

Thank you for reporting this issue!

 When you have a spare moment could you confirm the following:
* Whether this is a regression for you (i.e. did this work for you in a previous Sublime Merge version)
* your GPU specs (by running `glxinfo | grep "Device"`)

From our end, I don't believe there have been any changes to the OpenGL initialization, so this could be driver-related if this is a regression.

Kind regards,
\- Dylan

**Comment by kortschak** [comment]
I previously thought this was a regression as I did not see it with 2068. However, looking into getting `glxinfo` output, I suspect this is a regression in the driver due to the distro since `glxinfo` fails.

```
$ glxinfo        
name of display: :0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  85
  Current serial number in output stream:  86
```

I have now reinstalled 2068 and it too is failing now. So I am pretty certain that this is likely to be a kernel issue in the distro.

**Comment by kortschak** [comment]
OK. I've just power cycled in the optimistic belief that things should be working and both `glxinfo` and `smerge` are now working as expected. So the system must have got itself into a bad state.

Thanks for your time and the products.

**Comment by dpjohnst** [comment]
Glad it could be resolved - thanks for using Sublime Merge!
