### ISSUE TITLE
Sublime Merge Freeze in Windows

### ISSUE THREAD

**Issue by KrisAbildgaard** [sublimehq/sublime_merge#1477]
**Version info**

 - Build: Not sure since the program freezes. But this is from the top of the Buildlog.txt: "Build 2068"
 - OS: Windows 10 (see attached screendump)![PCAndWindowsVersion](https://user-images.githubusercontent.com/76517143/165501924-91215c82-31c6-4563-a52d-72e83027baa4.png)

**Description**

When I open Sublime Merge (from Sublime Text 3 or from shortcut) the program opens, but I can't do anything. It is totally freezed and I need to "end it" in the Windows Task Manager.

**Steps to reproduce**
Open Sublime Merge

**Comment by KrisAbildgaard** [comment]
And now (for some unknown reason) it works again?

**Comment by dpjohnst** [comment]
Hi @KrisAbildgaard,

Thanks for reaching out - I'm glad it's working again.
Please reach out again if the issue persists and I can investigate this further.

Kind regards,
\- Dylan from Sublime HQ

**Comment by MoonLighTingPY** [comment]
got the same exact issue. need to reinstall it every time this happens. build 2112, 

<img width="854" height="648" alt="Image" src="https://github.com/user-attachments/assets/e6142710-cc71-4530-b850-69b5f7b48534" />
