### ISSUE TITLE
'unsafe repository' after the update

### ISSUE THREAD

**Issue by TaroEld** [sublimehq/sublime_merge#1482]
**Version info**

 - OS: Windows 10 x64
 - Build: 2071

**Description**
After updating Sublime Merge to 2071, any action with an existing, local repository, such as staging files, will be rejected with the message: 'fatal: unsafe repostitory ('PATH' is owned by someone else)'

**Steps to reproduce**

1. Update to 2071
2. Do any repository action (checking out branches, staging files)
3. Get error message

**Expected behavior**
Well, no error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/34767248/165891733-2706d033-f4ff-4cb4-b424-140ad0274b60.png)

**Comment by jfcherng** [comment]
To disable that feature which is introduced in git 2.35.3
```bash
$ git config --global --replace-all safe.directory '*'
```

**Comment by codecat** [comment]
I feel like disabling the new security feature (how annoying it may be) really shouldn't be necessary, especially on Windows. Why does the error even appear? Does Merge run git from a different user than my command prompt? What's happening?
