### ISSUE TITLE
OpenGL error on Pop!_OS (Ubuntu) 22.04

### ISSUE THREAD

**Issue by Zooce** [sublimehq/sublime_merge#1484]
**Version info**

 - OS: Pop!_OS 22.04
 - Build: Dev 2070

**Description**

I see the the following error when opening Sublime Merge on Pop!_OS 22.04:

```
OpenGL: Error on context creation: Unable to create a GL context
```

![smerge_opengl_error](https://user-images.githubusercontent.com/5490155/166116230-975a9802-7d44-4dda-ae1f-6563a67e211f.png)

**Comment by Ultra-Instinct-05** [comment]
A similar issue was opened a few days ago https://github.com/sublimehq/sublime_merge/issues/1470

Try what Dylan has said here https://github.com/sublimehq/sublime_merge/issues/1470#issuecomment-1107961643

**Comment by Zooce** [comment]
So `glxinfo | grep "Device"` gives no output and returns 1, but `glxinfo` does have a bunch of output like:

```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 2070 Super/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 510.68.02
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```

Perhaps it is a driver issue then. I'll do some more searching.

**Comment by Zooce** [comment]
Looks like updating packages has fixed it. Sorry about this! Thanks.
