### ISSUE TITLE
Console receives input focus (using Tab key) even when not open/shown

### ISSUE THREAD

**Issue by frou** [sublimehq/sublime_merge#1485]
**Version info**

 - OS: macOS 11.6.5
 - Build: 2071

**Description**

When using the Tab key to move input focus to the next UI element, the Console receives input focus even when it is not open/shown.

Because it is not open, the visual feedback to show that it has received input focus (flashing border) is also invisible, and to the user it seems like nothing has input focus.

**Steps to reproduce**

1. Open repository
2. Click on an entry in the Commits column
3. Press the Tab key

**Expected behavior**

Input focus moves to the next visible UI element (i.e. the commit summary on the right, in this case)

**Comment by Ultra-Instinct-05** [comment]
This is fixed as of Build 2072.

![image](https://user-images.githubusercontent.com/34304644/168529837-0d0a7aaa-56a2-4942-ade6-b8bca2993825.png)
