### ISSUE TITLE
SSH Fails

### ISSUE THREAD

**Issue by KrisAbildgaard** [sublimehq/sublime_merge#1488]
Please help! My workflow without Sublime Merge sucks!

**Version info**
 - OS: 
![Windows_Version](https://user-images.githubusercontent.com/76517143/166918637-a70ae6c2-05ea-4d74-a44b-05a9fed3a42b.png)
 - Problem came when updated from Build 2068 to 2071

**Description**
When I do pretty much anything. The following happens:
![Bug Sublime Merge](https://user-images.githubusercontent.com/76517143/166918892-acc9655f-d943-40d8-8852-438556ea9b04.png)

When I do the same from my Git Bash it works fine.
It all also worked fine from S.Merge before I updated from Build 2068 to 2071

If I do what it suggests (add safe directory) the failure still exists.

I tried to add :
"PubkeyAcceptedKeyTypes +ssh-rsa
HostKeyAlgorithms +ssh-rsa"
to my ssh config (since this helped my colleague with a similar problem, when he updated Sublime Merge). But this changes nothing.

**Comment by jfcherng** [comment]
see https://github.com/sublimehq/sublime_merge/issues/1482#issuecomment-1112911815

**Comment by KrisAbildgaard** [comment]
Sorry I missed that one.

It works perfectly!

Thank you sooo much :-)
