### ISSUE TITLE
Add merge no fast forward option

### ISSUE THREAD

**Issue by damianogiusti** [sublimehq/sublime_merge#149]
**Problem description**

Will be useful to force a merge to use the `--no-ff` option, creating always the merge commit with the default message.

**Preferred solution**

When choosing the "Merge Branch..." action in the quick action popup, after selecting the branch a list of merge options should be showed. The list should include at least the `--no-ff` option.
The expected behavior is similar to what happens for the "Push" command, where a list of options will be presented (i.e. `--force`, `--force-with-lease` or without option) after selecting the branch and the origin.
As default value, my suggestion is to keep the default `git merge` behavior.

**Comment by jskinner** [comment]
This has been added recently in dev build 1076 - https://www.sublimemerge.com/dev
