### ISSUE TITLE
Can support Windows directory separator in path search phrases?

### ISSUE THREAD

**Issue by richex-cn** [sublimehq/sublime_merge#1492]
**Problem description**

Windows and VS Code is my development environment now. I usually right-click to copy the relative path then paste to Sublime Merge search input if I want to view file histories.

![image](https://user-images.githubusercontent.com/25103518/168811384-054819ef-328b-4f93-a4e0-68c4b61b9f1f.png)

But the path is like `path\to\file.txt`, and Sublime Merge cannot match any result. I need to manually replace `\` with `/` then get some result. It's inconvenient.

![image](https://user-images.githubusercontent.com/25103518/168812764-b15c916c-80ad-4b26-bc96-09ce67d09e56.png)

**Preferred solution**

Compatible the Windows directory separator.

**Comment by srbs** [comment]
This was fixed in dev build 2073 / stable build 20474:

> * Search: `file` and `path` queries now support absolute paths and Windows-style paths

**Comment by richex-cn** [comment]
Yes, it was repaired less than a month after I open this issue, It's great.
