### ISSUE TITLE
Removal of scrollbars has made Merge unusable in certain cases

### ISSUE THREAD

**Issue by resynth** [sublimehq/sublime_merge#1501]
It seems the scrollbars have been removed/hidden? (Unless something weird is happening on my specific Lenovo T530 running Ubuntu 20.04)

I guess this is fine for most people as they can scroll using the scroll wheel on their mouse or 2 fingers on the touchpad.  I have neither of those luxuries and it has suddenly made Merge absolutely useless to me!  Unfortunately scrolling through the diffs using the keyboard does not work either as it only scrolls to the end of the hunk.

I'd appreciate it if you'd consider re-adding the scrollbars, otherwise I (and presumably some others) simply cannot use the software anymore.

**Comment by DavidW1024** [comment]
Can you try go to "Preferences->Edit Settings...". Check if there's any line that says `"overlay_scroll_bars"`, if not, try add this line to the file: `"overlay_scroll_bars": "system",`. Then experiment between "system", "enabled" and "disabled" value, see if any of the settings make scroll bar visible again.

If that doesn't work, it's likely a bug that needs to be fixed. Merge never removed scroll bars outright.

**Comment by resynth** [comment]
```"overlay_scroll_bars": "disabled",``` worked for me.  Thanks
