### ISSUE TITLE
Staging or Unstaging hunks makes the function name context display become blank

### ISSUE THREAD

**Issue by Zorro666** [sublimehq/sublime_merge#1506]
**Version info**

 - OS: macOS 12.4
 - Build: 2071

**Description**

When doing partial staging of changes ie. using `Stage Hunk` or `Unstage Hunk` the function name context becomes blank after doing partial stage/unstage. This applies to files in both the "Working Directory" (using `Stage Hunk`) and "Staged Files" (using `Unstage Hunk`) sections.

The function name context can be recovered by clicking `Show entire file` and then `Show only modified hunks`.

**Steps to reproduce**

1. Have a source code file ie. C++ file with changes in multiple functions.
2. In the "Working Directory" display, the differences in each function have the function name context displayed.
3. Click on `Stage Hunk` on a change in one function.
4. The function name context is now blank for other functions in that file. 
5. The function name context for other modified files are not affected.
6. Follow similar steps on "Staged Files" display clicking `Unstage Hunk` instead of `Stage Hunk` 

**Expected behavior**

Staging or Unstaging hunks should not change the function name context display.

**Screenshots**

Before clicking `Stage Hunk` : function name contexts displayed `setFragmentTexture`, `Serialise_setViewport` and `endEncoding`.
<img width="935" alt="image" src="https://user-images.githubusercontent.com/39392/171331201-cb965e16-8a9b-48b0-9ee5-e43063ef0fff.png">

After clicking `Stage Hunk` : function name contexts are blank.
<img width="924" alt="image" src="https://user-images.githubusercontent.com/39392/171331277-95a0503f-eab1-41ea-bd49-f020d62d51e0.png">

After pressing `Show entire file` and then `Show only modified hunks`. The function name contexts are restored : `setFragmentTexture` and `endEncoding`.
<img width="927" alt="image" src="https://user-images.githubusercontent.com/39392/171331614-5983c655-3815-4b12-8c9a-f00ec9a801ab.png">

**Comment by srbs** [comment]
duplicates: #1411
