### ISSUE TITLE
License lost when upgrading from 2071 to 2074

### ISSUE THREAD

**Issue by danielsamuels** [sublimehq/sublime_merge#1514]
**Version info**

 - OS: Windows 11
 - Build: 2074

**Description**

For quite a while now, I've been using Sublime Merge with a purchased license. After upgrading from 2071 to 2074 this morning, it has forgotten all about it.

**Steps to reproduce**

1. Have a licensed version of 2071
2. Upgrade to 2074
3. See that it is unlicensed

**Expected behavior**

The license should continue to be valid

**Comment by jfcherng** [comment]
Does your "See that it is unlicensed" mean "LICENSE UPGRADE REQUIRED"?

**Comment by danielsamuels** [comment]
`UNREGISTERED` is what I see

**Comment by jfcherng** [comment]
> I find it hard to believe that three years have past since I purchased my license. I could be wrong about that though.

https://www.sublimehq.com/store/retrieve_key should sends you the original invoice, which contains the purchase date.

**Comment by bradhoward-dfs** [comment]
@jfcherng
Thanks for the link. That returned my Sublime Text key, not the Sublime Merge key.
The date on the invoice from May of last year jives with what I remember in regards to purchasing Sublime Merge.
Perhaps I used different email addresses for the purchase of Merge and Text.
I'll keep an eye on this thread and see what happens.

**Comment by dpjohnst** [comment]
Hi @danielsamuels,

Thanks for reaching out, and sorry to hear you're experiencing this issue. I'll be investigating this further.

* Are you able to re-enter the license key? If so, what happens and do you see any notices appear?
* Additionally, are you using any networked directories on your computer (including your home directory)?

Thanks,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Hi @bradhoward-dfs,

Sorry that you've experienced this - we'd like to get this resolved as soon as possible.

If you could reach out to [sales@sublimetext.com](mailto:sales@sublimetext.com) and include the description of the issue you're experiencing and your license key, we can investigate this promptly.

Thanks,
\- Dylan from Sublime HQ

**Comment by eug-r** [comment]
I have exactly the same issue - UNREGISTERED for key which was purchased last year.

> By the way, 2073 is the first release that SM shows "LICENSE UPGRADE REQUIRED".

Nice, so the 2073 and 2074 builds were affected by this bug.
Old builds 2071 and 2072 still work fine with my key.

**Comment by eug-r** [comment]
I have updated from 2072 to 2076 - and my license was lost again.
Are you going to fix that?

**Comment by dpjohnst** [comment]
Hi @eug-r,

Thanks for reaching out.

Sublime Merge build 2075 includes a fix to the updater, ensuring users are presented with license validity information when updating. This will ensure that users updating from build 2075 will be notified of their license validity for any future builds.

If you are losing your license entirely (rather than seeing `license upgrade required`) there may be something else going on.
If you could please reach out to sales@sublimetext.com with your license details, they can verify the status of the license and investigate further.

Thank you for your patience while this is investigated.
Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

Today we've released a fix for the bug that caused the updater to not display license validity information.
This means that from build 2077, license validity information will be displayed in the update dialog.

I'm going to go ahead and close this issue now, but please feel free to re-open / comment if you're still experiencing any issues.

Thank you for your support and patience while this has been addressed.

Kind regards,
\- Dylan

**Comment by eug-r** [comment]
> If you are losing your license entirely (rather than seeing `license upgrade required`) there may be something else going on.

It was really very confusing - I have "Single User License" - so I supposed it will be valid for 3-years. But sales@sublimetext.com replied me that my license was annual and ended in April 2022. But it works fine with build 2072 which was released in May. And I never saw any `license upgrade required` messages. Something does not hang together...
