### ISSUE TITLE
Add git stash –staged option

### ISSUE THREAD

**Issue by fabien-michel** [sublimehq/sublime_merge#1515]
**Problem description**

Since git 2.35 there is a new `git stash` option to stash only staged files/lines. Would be nice to have it from sublime merge.

`git stash --staged`

Git doc: [https://git-scm.com/docs/git-stash/#Documentation/git-stash.txt---staged](https://git-scm.com/docs/git-stash/#Documentation/git-stash.txt---staged)

Changelog: [https://github.blog/2022-01-24-highlights-from-git-2-35/](https://github.blog/2022-01-24-highlights-from-git-2-35/)

**Comment by dpjohnst** [comment]
Hi,

This has been added in Sublime Merge 2075 (development build), and will be added to the next stable build.

Cheers,
\- Dylan
