### ISSUE TITLE
Please add 'Repository > Open Containing Folder' to the the Command Palette 

### ISSUE THREAD

**Issue by steve-mather** [sublimehq/sublime_merge#1517]
**Problem description**

I frequently work with many repos open during the day and in almost all cases will need to open the repo's containing folder (to drag in new media etc). As Sublime Merge is becoming more and more my base tool to manage these multiple projects, going up to the hamburger > repository > Open Containing folder a lot seems slow especially when doing so multiple times a day. In fact I find opening in Sublime Text then right clicking Open Folder quicker sometimes!

**Preferred solution**

Adding 'Repository > Open Containing Folder' to the the Command Palette 

**Alternatives**

And/or adding the  'Open Containing Folder' command to the '...' ellipsis menu at the top to the right of the search icon.  Like how 'Open in Sublime Text' is there already

**Comment by steve-mather** [comment]
Many thanks Ashwin that was really helpful thank you

Best regards

Steve

**Comment by Dimava** [comment]
This feature got implemented, please check it and close the issue
