### ISSUE TITLE
[2074] Latest build breaks "Open in Editor" functionality

### ISSUE THREAD

**Issue by ashut0shk** [sublimehq/sublime_merge#1519]
**Version info**

 - OS: Windows 10
 - Build: 2074

**Description**

After upgrading from 2071 to 2074, "Open in Editor" option works inconsistently, mostly fails to open/switch to the editor of choice.

Tried with latest Sublime Text, as well as VS Code and the issue remains unchanged. However, reverting to 2071, with the same preference file, solves the issue. This is apparent to be an issue in 2074 itself.

**Steps to reproduce**

1. Open repository ...
2. Go to any commit
3. Select any file with changes in the diff panel
4. Right click and select "Open in Editor"
5. Nothing happens :(

**Expected behavior**

Whenever "Open in Editor" command is triggered, an editor should be prompted with the file with cursor on that location

**Screenshots**

N/A

**Comment by jfcherng** [comment]
Someone has a similar report on the forum too.
https://forum.sublimetext.com/t/open-in-editor-command-stopped-working/64310

**Comment by srbs** [comment]
@ashut0shk, dev build 2075 may have fixed this issue with this note:

> **BUILD 2075**
> * Fixed open_in_editor command waiting

**Comment by ashut0shk** [comment]
The latest version fixes the issue, Thanks. 

Proceeding to close and mark this issue as resolved.
