### ISSUE TITLE
Unable to navigate repo tabs with keyboard

### ISSUE THREAD

**Issue by skoonin** [sublimehq/sublime_merge#1521]
**Version info**

 - OS: MacOS 12.4
 - Build: 2074

**Description**

Unable to use keys to navigate btwn repo tabs

**Steps to reproduce**

Tried standard keys to navigate tabs and they did not work.  Re-mapped keys via System Preferences -> Keyboard -> Shortcuts and they still won't work.  Also remapped Next File Tab and it won't respond either. 

**Expected behavior**

Able to move btwn repo tabs with keys.  Tested with default keys and remapped keys.

**Screenshots**

![Remapped keys settings](https://user-images.githubusercontent.com/12276904/174867267-770c25a5-e570-4d29-b5cc-caeea9e355fa.jpg)
Remapped keys setup

**Comment by dpjohnst** [comment]
Hi @skoonin,

Thanks for reaching out - I'll be investigating this further.

So far I've been unable to reproduce this issue. To narrow this down further, could you confirm:
* Which shortcut you were using to switch repository tabs (before setting up the app shortcuts)
* If the shortcuts work while the "Navigate" app menu is open

Kind regards,
\- Dylan from Sublime HQ

**Comment by srbs** [comment]
@skoonin, I wouldn't recommend using the macOS global shortcuts when you can use Sublime Merge's built-in [keybinding support](https://www.sublimemerge.com/docs/key_bindings). Here are my overrides (I'm not a fan of the existing defaults either) to get you started on customizing them to your preferences:

`Default.sublime-keymap`:
```
[
	{ "keys": ["ctrl+pageup"      ], "command": "prev_tab" },
	{ "keys": ["ctrl+pagedown"    ], "command": "next_tab" },
	{ "keys": ["ctrl+shift+tab"   ], "command": "prev_tab" },
	{ "keys": ["ctrl+tab"         ], "command": "next_tab" },
	{ "keys": ["super+shift+["    ], "command": "prev_tab" },
	{ "keys": ["super+shift+]"    ], "command": "next_tab" },
	
	{ "keys": ["ctrl+alt+pageup"  ], "command": "prev_file_tab" },
	{ "keys": ["ctrl+alt+pagedown"], "command": "next_file_tab" },
	{ "keys": ["super+pageup"     ], "command": "prev_file_tab" },
	{ "keys": ["super+pagedown"   ], "command": "next_file_tab" },
	{ "keys": ["super+alt+["      ], "command": "prev_file_tab" },
	{ "keys": ["super+alt+]"      ], "command": "next_file_tab" },
]
```
