### ISSUE TITLE
Sublime Merge auto-updates after license has expired, resulting in LICENSE UPGRADE REQUIRED

### ISSUE THREAD

**Issue by kpitt** [sublimehq/sublime_merge#1524]
**Version info**

 - OS: macOS 12.3.1
 - Build: 2074

**Description**

The auto-update dialog for Sublime Merge recently popped up indicating that a new build 2074 was available, so I downloaded and installed it. After SM restarted, I now have a LICENSE UPGRADE REQUIRED message in the title bar. I checked my purchase records and discovered that my license reached 3 years back in April, so the license upgrade message is valid, but Sublime Merge should not have auto-updated with no warning if the new version is not covered by my license.

I was able to recover the app bundle for build 2071 from the Trash on this machine, but I couldn't find any way to download an older version of the installer in case I need to install the licensed version on a new machine. The only links on https://www.sublimemerge.com/download are for the most recent build and for the page containing the Dev Builds, and even the Dev Builds page only has a link to the most recent development version. I even tried copying and pasting the download link, hoping that I could just change the build number in the link, but the URL doesn't contain any version number.

**Steps to reproduce**

1. Run Sublime Merge build 2071 with a valid license that expires before 9 June 2022 (release date of build 2074).
2. Receive automatic update dialog indicating that build 2074 is available, with no indication that license is expired.
3. Accept the upgrade.

**Expected behavior**

Sublime Merge should disable automatic update checks if the current license is expired. At the very least, the upgrade dialog should clearly indicate that the upgrade is _not_ covered by the current license and allow me to easily disable further update checks. Note that I tried to uncheck the "Check for updates periodically" option and cancel the download when this update popped up on a second machine, but Sublime Merge still kept prompting me to update. After about a week of daily update prompts, I finally gave in and let it install the update because the LICENSE UPGRADE REQUIRED message is less annoying than having to constantly cancel the Update dialogs.

**Screenshots**

![Screen Shot 2022-06-22 at 4 28 39 PM](https://user-images.githubusercontent.com/16420/175130338-ce23b38e-1856-40ad-93fa-36ab812b10a2.png)

**Comment by erazor-de** [comment]
One can't even see up until when the actual license is still valid. Why not put this information in the about window where the licensee is already mentioned? This also applies to Sublime Text.

**Comment by kpitt** [comment]
Here's an updated screenshot from today. I downgraded to build 2071 and unchecked the "Check for updates periodically" option. The screenshot includes a snippet of my `Preferences.sublime-settings` file showing that the `"update_check": false` was added to my settings when I unchecked the option, but yet I'm still getting the update popup.

![Screen Shot 2022-06-29 at 12 29 16 PM](https://user-images.githubusercontent.com/16420/176488953-95204078-08c7-4952-acb3-ad714eb61e2c.png)

**Comment by kpitt** [comment]
> Assuming your SM is registered since that's a registered feature

Yeah, that's the whole point of the bug. I purchased my license in April 2019, and my 3 years expired before 2074 was released. However, no matter what I do, I can't seem to get 2071 to stop prompting me to upgrade to a version that isn't covered by my license.

Comparing my purchase records (since Sublime Merge doesn't provide any way to see what your license expiration date is) with the release dates on the download page, it would appear that my 3 years actually expired a few weeks _before_ build 2071 was released, but I had no way to know that since there was no message _before_ updating and no "LICENSE UPGRADE REQUIRED" message _after_ updating.

Would the fact that 2071 is technically outside of my license period cause disabling updates to not work? If so, then this bug is even worse than I thought. That would mean that Sublime Merge auto-updated me, without warning, to an unlicensed version that prevents me from disabling any further update checks. Furthermore, the download page doesn't seem to provide any way to recover an older versions that _is_ within my license period, even though I supposedly have a perpetual license to use those versions, which makes it effectively impossible for me to continue to use Sublime Merge the way I always have without constantly dismissing update dialogs.

**Comment by kpitt** [comment]
Someone on the forums helped me find the way to get a link to an older version, so I downloaded build 2068 (last build prior to the end of my license period) and I am testing that to see if I still get the update prompts.

In case anyone stumbles across this issue and is having the same problem finding the downloads, here is the (rather convoluted) process:

1. Go to the Sublime Merge download page: https://www.sublimemerge.com/download
2. ***Click*** on the link for the latest build. You _must_ actually click on the link. Do not try to use right-click and "Download Linked File" or "Copy Link".
3. The new page will attempt to automatically download the latest build of Sublime Merge. Just cancel or discard this download.
4. Under the "Thanks for Downloading..." banner, ***click*** on the "direct link" link in the "Download not working? Try a direct link" message. Again, do _not_ try to copy this link, you must click it.
5. The "link" is actually a JavaScript action that opens a hidden panel that contains the _actual_ direct links.
6. Now you can right-click and "Copy Link" on the link for the OS that you need.
7. Paste this URL into the address bar of your browser, and then edit the URL to replace the latest build number with the build number you want to download. Submit the updated address to download the desired build.

**Comment by dpjohnst** [comment]
Hi @kpitt,

Firstly, apologies for your update experience and thank you for sharing your feedback - there's lots of room for us to improve here.

Based on feedback, we've been prioritising a new update dialog that provides licensing and validity information. This has now been enabled in Sublime Text, and will be enabled in the next Sublime Merge update to prevent this situation from occurring again.

I will also investigate improving the download page to allow simple access to prior versions. Thank you for your support!

Kind regards,
\- Dylan from Sublime HQ

**Comment by stinos** [comment]
@dpjohnst thanks for looking into this. Question: I'm also having this issue since a couple of weeks but am just ignoring it for now, with seemingly no adverse effects so far. So can I just wait until you guys get these fixes in and it will resolve automatically?

**Comment by kpitt** [comment]
@dpjohnst Since my license is expired, I can't install any new updates, so I'm currently stuck on an earlier version that has the update issue. If you do release an update that fixes the update issue, will there be any way to get the fix without first renewing the license?

**Comment by dpjohnst** [comment]
Hi all,

@stinos - to clarify, is the issue that you're being prompted for an update when you've disabled updates, or that you were affected by the lack of notice for license validity.

If it's the lack of notice - as long as the `Upgrade Required` title-bar isn't bothering you, then certainly feel free to keep using that version. Otherwise, you can downgrade to a prior version using the links below (replacing `VERSION` with the version number you're after):
https://download.sublimetext.com/sublime_merge_build_VERSION_x64_setup.exe
https://download.sublimetext.com/sublime_merge_build_VERSION_mac.zip
https://download.sublimetext.com/sublime-merge_build-VERSION_amd64.deb

@kpitt - I'm currently investigating the `disable_update` issue you're experiencing and will get back to you as soon as possible. Thank you for your patience!

Thanks,
- Dylan

**Comment by dpjohnst** [comment]
Hi @kpitt,

Could you confirm if the following steps do or do not disable the update check on your end:

1. Open Sublime Merge
2. Select `Preferences > Edit Settings...` from the application menu
3. Add the following to the settings:
![image](https://user-images.githubusercontent.com/18252447/177930106-ec8549ec-c5ed-4d57-92fd-07be616f8506.png)
4. Save the file
5. Restart Sublime Merge

Additionally, could you confirm that you're still seeing the `License Upgrade Required` message in the title bar?

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

A quick update from our end - we've just pushed an update to the development channel which fixes the issue causing the license validity to not show in the updater.

Thanks for your patience and feedback,
\- Dylan

**Comment by centur** [comment]
@dpjohnst I suspect this bug was re-introduced somehow. My license is recently expired (I learned it from the update prompt, so this part is working), I'm ok with current features set and has no plans to renew the license, I've un-ticked "Check for updates periodically"
My config indeed reflects this:
<img width="421" alt="image" src="https://github.com/sublimehq/sublime_merge/assets/720822/6f39e1b2-eb82-481f-8ec1-cd41a3425af0">

But I'm still getting periodic update prompts. Could it be a regression of this bug ?
SM Build: Stable channel, Build 2091

**Comment by dpjohnst** [comment]
G'day @centur,

Thanks for reaching out and sorry to hear you're running into this issue. I'll be investigating this further!

Could you confirm whether the expired license is still registered in Sublime Merge?

You can confirm this by checking the `Help` menu in Sublime Merge.
If you see `Enter License`, the license is no longer registered with Sublime Merge. 

Could you also confirm whether you are using a personal license, or a business subscription?
This can help me reproduce the bug on my end.

Cheers,
\- Dylan

**Comment by centur** [comment]
G'day mate,
License is personal and it's still registered with Sublime Merge.
I can see Buy and Remove license options in SM Help menu

**Comment by dpjohnst** [comment]
Hi @centur,

Thanks for the information - could you also confirm what operating system you're using?

Additionally, could you try restarting Sublime Merge and confirming if this resolves the issue.
Note that it may take up to 24 hours to verify this, as the update check is only triggered once every 24 hours.

Kind regards,
\- Dylan from Sublime HQ

**Comment by centur** [comment]
MacOS Sonoma: 14.4.1 (23E224)
Restarted SM, will write here in about 24+ hours whether it appeared again or not.


Side note, may be irrelevant here, but just in case - I run SM as a full-screen dedicated app with MacOS Stage Manager on, it's not on any desktop but rather a desktop on it's own:
<img width="826" alt="image" src="https://github.com/sublimehq/sublime_merge/assets/720822/d47f7acc-d930-4d47-8ff2-2b4113c635c4">

**Comment by centur** [comment]
UPD: I can confirm, that after I restarted SM with known unchecked "Check for updates periodically" box that update prompt does not show up anymore.
Sorry for some red herring here. It seems that the missing piece was a restart (and I'm guilty here - I don't restart SM usually, it just always on).
