### ISSUE TITLE
Git Pull and Git Push shortcuts not working 

### ISSUE THREAD

**Issue by rodrigomlpOz** [sublimehq/sublime_merge#1525]
**Version info**

 - OS: Windows 11
 - Build: 2074

**Description**
Ctrl + Alt + Down
Ctrl + Alt + Up

For git push and pull are not working as shortcuts, slowing down workflow

**Steps to reproduce**

1. Open repository ...
2. Run command ...
3. Click on ...

**Expected behavior**

A description of what you expected to happen.

**Screenshots**

If applicable, add screenshots to help explain your problem. This section may be omitted/removed.

**Comment by srbs** [comment]
Only saying 'this or that does not work' isn't useful, help us help you by providing as much details and information as you can.

1. Are you getting any errors?
2. Does running the command instead of the keybinding work?
3. Does push/pull work on the command line?

**Comment by rodrigomlpOz** [comment]
1) No errors
2) The command works if I click, not if I type.
3) It does work in the command line

**Comment by dpjohnst** [comment]
Hi @rodrigomlpOz,

Thanks for sharing this feedback - this has been resolved in the latest dev build (2076).

Kind regards,
\- Dylan
