### ISSUE TITLE
Editing the content of the 2nd commit is not possible

### ISSUE THREAD

**Issue by SicroAtGit** [sublimehq/sublime_merge#1532]
**Version info**

 - OS: Manjaro Linux
 - Build: 2074

**Description**

The content of the 2nd commit cannot be edited.

When I click on `Edit Commit – Edit Commit Contents` in the context menu of the 2nd commit, the error message `Error: cannot edit the contents of the commit with no parents` appears. But Sublime Merge shows me a parent commit hash when I click on the second commit in the commit history.

**Steps to reproduce**

1. Create a repository with at least two commits.
2. Try to edit the commit content of the second commit.

**Expected behavior**

Editing the 2nd commit should be possible because Git can do that.

**Comment by dpjohnst** [comment]
Hi @SicroAtGit,

Thanks for reporting this issue!
The cause of this issue has been identified and a fix will be provided in the next release.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @SicroAtGit,

Thanks for reporting this!
This has been resolved in Sublime Merge build 2077.

Kind regards,
\- Dylan

**Comment by SicroAtGit** [comment]
Thanks!
