### ISSUE TITLE
File history does not show merge commits

### ISSUE THREAD

**Issue by rattuscz** [sublimehq/sublime_merge#1537]
**Version info**

 - OS: Fedora 36 - 5.18.9-200.fc36.x86_64
 - Build: 2074
 - Git: Using Git: git (system) git version 2.36.1

**Description**

File history does not show changes in the file made by branch merge commits, even though the commit diff itself shows the change on the file and allows clicking file history.

**Steps to reproduce**

1. Have 2 branches
2. Merge changes on file from one branch to the other
3. File history of the file that was changed by the merge
4. No merge commit visible

**Expected behavior**

I expect any commit changing the file should be visible, so including merge commits

**Screenshots**

![image](https://user-images.githubusercontent.com/688332/177997695-9d3cbbcc-a9e6-4836-b4ca-bbae8b16234a.png)

**Comment by srbs** [comment]
This is expected behavior, see https://github.com/sublimehq/sublime_merge/issues/478#issuecomment-487529415

**Comment by rattuscz** [comment]
closing as duplicate
