### ISSUE TITLE
SM ignores some .gitignore entrys

### ISSUE THREAD

**Issue by HappyWarbird** [sublimehq/sublime_merge#1539]
**Version info**
=== App Version Information ===
Build: 2074

=== Git Version Information ===
Using Git: C:\Program Files\Sublime Merge\Git\cmd\git.exe (bundled)
git version 2.35.3.windows.1
PATH: C:\Python310\Scripts\;C:\Python310\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Oracle\VirtualBox;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\PuTTY\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Bitvise SSH Client;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\PowerShell\7\;C:\Users\PoP\AppData\Local\Microsoft\WindowsApps;C:\Users\PoP\AppData\Roaming\npm;C:\Users\PoP\AppData\Local\Programs\Fiddler

=== Browse Page Information ===
HEAD: 08822c422f25fcd8466338926891a5a720f3b4be
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===
 M axie-collandschol.sublime-workspace

=== Our Status Information ===
 M axie-collandschol.sublime-workspace

=== Git Config Information ===
branch.master.merge=refs/heads/master
branch.master.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
core.autocrlf=true
core.bare=false
core.filemode=false
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager-core
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
help.format=html
include.path=C:/Program Files/Git/etc/gitconfig
pack.packsizelimit=2g
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/*****************
user.email=******************
user.name=**************

=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /C/Program Files/Sublime Merge/Git/etc/gitconfig
Using config path: /C/Users/PoP/.config/git/config
Using config path: /C/Users/PoP/.gitconfig
Using config path: /E/Projects/axie-collandschol/.git/config

Our config output is different to the Git config output
branch.master.merge=refs/heads/master
branch.master.remote=origin
color.branch=auto
color.diff=auto
color.interactive=true
color.status=auto
core.autocrlf=true
core.bare=false
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
credential.helper=manager-core
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
help.format=html
include.path=C:/Program Files/Git/etc/gitconfig
pack.packsizelimit=2g
rebase.autosquash=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com**************
user.email=************
user.name=***************

=== Git Attributes Information ===
git check_attr --all output
axie-collandschol.sublime-workspace

=== Our Modified Files Newline Normalisation and EOL Information ===
axie-collandschol.sublime-workspace: autocrlf - crlf

=== Our Modified Files Flag Information ===
Ignoring symlinks: 1
axie-collandschol.sublime-workspace: Working - Normal File : Index - Normal File

 - OS: Windows 11
 - Build: 22000.739

**Description**

Sublime and Sublime Merge don't ignore all files in .gitignore

**Steps to reproduce**

Problem occurs since last SM Update, can't reproduce

**Expected behavior**

SM and Sublime should ignore files on .gitignore correctly
**Screenshots**

![2022-07-12_14h54_18](https://user-images.githubusercontent.com/13272054/178495167-97339d86-ba24-4506-84ac-73279cae0309.png)
![2022-07-12_14h54_30](https://user-images.githubusercontent.com/13272054/178495187-6301c5f3-e2a2-42d9-836e-13755a797799.png)
![2022-07-12_14h54_48](https://user-images.githubusercontent.com/13272054/178495197-e694d291-f324-45f3-b509-3bee8e999467.png)

As shown in Screenshots, the db.sqlite in app folder and the sublime-workspace file aren't ignored by SM

**Comment by dpjohnst** [comment]
Hi @HappyWarbird,

Thanks for reaching out!

It looks as if the `sublime-workspace` file has been committed (as it appears to be modified rather than untracked).
`.gitignore` rules will [apply to untracked files only](https://git-scm.com/docs/gitignore#_description).

Could you also confirm whether `db.sqlite` has been committed?

Thanks,
\- Dylan

**Comment by HappyWarbird** [comment]
Hi Dylan
both files were comitted, as on creating and adding to gitignore, they aren't ignored.
I try to reproduce with new repository

Thanks for help

Pascal

Closed
