### ISSUE TITLE
Add option to hide whitespace changes

### ISSUE THREAD

**Issue by iamntz** [sublimehq/sublime_merge#154]
Sometimes I do some code formatting, which is basically only whitespace changes (e.g. a `tab` there, some spaces there and so on).

While this may be useful sometimes, most of the time is just clutter, because you see a red screen on the left and a green screen on the right, without any _real_ value or information.

Now, my favorite Git client is/was Gitextension, which have this nice feature to hide all whitespace changes. 

Here is how it looks on Sublime:

![](https://img.iamntz.com/2018-10-20_17h18_36.jpg)

This is the functionality in Gitextension:

https://img.iamntz.com/2018-10-20_17h19_50.mp4

Can we have this kind of awesomeness here too? :)

**Comment by TheClams** [comment]
Duplicate with #11

**Comment by iamntz** [comment]
And #119 too!

Actually i was looking _only_ for `white space` and... obviously, I got no results :/
