### ISSUE TITLE
Use "full" diff instead of side-by-side on new added files

### ISSUE THREAD

**Issue by themilkman** [sublimehq/sublime_merge#1547]
**Problem description**

When a new file is added (staged, commited, .. diffed) and the diff style is set to side-by-side, in the diff the left part is (obviously) always blank and wasted.

**Preferred solution**

In that case the diff could fill the whole section. Maybe at least on diffstyle "Auto".

**Alternatives**

Leave it as it is because this would not be side-by-side anymore and could disrupt users (not sure about this)

**Comment by dpjohnst** [comment]
This has been added in Sublime Merge 2075 (development build), and will be added to the next stable build.

**Comment by themilkman** [comment]
Thanks, works like a charm.

**Comment by themilkman** [comment]
Nice addition to apply this to removed files, too! (Build 2076)
