### ISSUE TITLE
Opening a repo making use of `core.worktree` leads to many issues

### ISSUE THREAD

**Issue by Zwyx** [sublimehq/sublime_merge#1548]
**Version info**

- OS: Ubuntu 22.04
- Build: 2074

**Description**

Opening a repository which has its work tree placed somewhere else than next to the repository itself, leads to many issues. See [this comment](https://github.com/sublimehq/sublime_merge/issues/960#issuecomment-1185561236) for a full description of the setup.

Issues I noticed:
- Trying to edit a commit message leads to an error, as well as trying to do a rebase.
- Signatures are shown as invalid:
![Signatures are shown as invalid](https://user-images.githubusercontent.com/29386932/179187973-41730573-5e2b-489d-b575-f032d34f90b6.png)
- When closing Sublime Merge and reopening it, the list of commits is empty. We have to close the repository and reopen it to have the commit list again.

It looks like this is because Sublime Merge opens the directory of the _work tree_, and loses track of where the _repository_ is, if it's not next to the work tree in the usual `.git` folder.

**Comment by dpjohnst** [comment]
Thanks for reporting this issue - this will be resolved in the next Sublime Merge build

**Comment by Zwyx** [comment]
Great to hear! Thanks!

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge 2075 (development build)

**Comment by Zwyx** [comment]
Hi @dpjohnst, I just updated Sublime Merge to build 2077. The first two issues I mentioned above are indeed fixed, that's great, thanks for that! However, the third one is not: when closing Sublime Merge and reopening it, the list of commits is empty. We have to close the repository and reopen it to have the commit list again.

If you'd like to reopen this issue, I can cross out the two first points. Or if you prefer, I can open a new issue?
