### ISSUE TITLE
Working Directory 

### ISSUE THREAD

**Issue by TarekSalama** [sublimehq/sublime_merge#155]
I’ve been getting my tracked edits split into Working Directory and Binary. Is there a way to group them together so I can stage them at once?

Also when I tried undoing a commit that hasn’t been pushed, the undo action itself was treated as a new commit. Is there a way to make it work like other Git GUI clients?

![f3df5ae9-0d30-483d-b6f6-d30cd61e61c2](https://user-images.githubusercontent.com/11663696/47258806-1b70ca80-d4a1-11e8-9f03-7001338bc49d.jpeg)

**Comment by wbond** [comment]
Can you utilize one of the template for this issue?

**Comment by deathaxe** [comment]
> split into Working Directory and Binary

The screenshot shows 2 changed binary files in the working directory, which could be staged together by pressing the "Stage All" button.

So what exactly is the issue? Text files, which are detected as binary?

If yes, please check the file encoding. In case it is `utf-16` (unicode), the behavior is quite normal as git handles such files as binary.
