### ISSUE TITLE
Create branch from remote branch command is no longer in available in Ctrl+P dialog

### ISSUE THREAD

**Issue by thiemeljiri** [sublimehq/sublime_merge#1551]
**Problem description**

This command was previously there. It's a pretty common thing to do. Few versions ago it disappeared and it wasn't added back since then. using the small app menu that isn't that quickly and easily reachable via keyboard for this is quite frustrating.

**Preferred solution**

Add this command back to Ctrl+P dialog

**Comment by srbs** [comment]
It was folded into the checkout branch command:

> **BUILD 2071**
> * Branches: Combined all checkout commands into a single command

---

You can resurrect the command by adding this to `Default.sublime-commands`:
```
[
    {
        "caption": "Create Branch From Remote Branch…",
        "command": "create_branch_from_remote_branch",
    }
]
```

**Comment by thiemeljiri** [comment]
Thank you! I can see it now, I missed that somehow. Thanks!

**Comment by srbs** [comment]
@thiemeljiri, also of note from yesterday's release:

> **BUILD 2076** 
> * Added `Create Branch from Remote Branch` back to command palette
