### ISSUE TITLE
Dark theme hunk header should have darker background (in between the file header and the diff content)

### ISSUE THREAD

**Issue by vladeck** [sublimehq/sublime_merge#1552]
**Problem description**

I believe dark theme hunk header should have darker background (in between the file header and the diff content). Now its brighter - because it is brighter when using light theme. For light theme it makes sense to have it brighter, but I believe that it does not make sense for dark theme; I feel like it should be a shade in-between the file header and the diff content. Right now it steals attention from other parts of the UI.

**Preferred solution**

Make hunk header darker than the file header for dark theme.

**Screenshots**

![Screenshot 2022-07-25 170724](https://user-images.githubusercontent.com/16443718/180812779-d2af977e-aca6-485a-b60e-73f3e65d573e.png)

**Comment by srbs** [comment]
As opposed to changing this for everyone, you can customize the theme to your preferences: https://www.sublimemerge.com/docs/themes

---

The element/class in question is `file_diff_hunk_header` as seen in the [file diffs section](https://www.sublimemerge.com/docs/themes#elements-file_diffs). The (extracted) rule that defines this element/class is:
###### from `Merge.sublime-theme`:
```json
{
	"class": "file_diff_hunk_header",
	"layer0.tint": "var(hunk_header_bg)",
	"layer0.opacity": 1.0,
	"content_margin": 4
}
```

As seen in the `layer0.tint` value, the variable `hunk_header_bg` is used. You're free to set that variable to any value you'd like according to the [color guidelines](https://www.sublimemerge.com/docs/themes#color_values). Here are the current light & dark themed values:
###### from `Merge.sublime-theme`:
```
"hunk_header_bg": "color(var(light_blue) s(- 10%) l(+ 10%))"
```
###### from `Merge Dark.sublime-theme`:
```
"hunk_header_bg": "color(var(--background) l(+ 11%))"
```

---

Based off the above, you can change the dark theme coloring to whatever you'd like, for example (changing the `+` to `-`):

###### `Merge Dark.sublime-theme`:
```
{
    "variables": {
        "hunk_header_bg": "color(var(--background) l(- 11%))",
    },
}
```

**Comment by dpjohnst** [comment]
Hi @vladeck,

Thanks for sharing this feedback! We've updated the dark theme in the latest dev build (2076).

Kind regards,
- Dylan

**Comment by vladeck** [comment]
Thank you @dpjohnst, really liking the result! 😁
