### ISSUE TITLE
Feature request: add a view mode to display all souce content in Text Diff viewport

### ISSUE THREAD

**Issue by dawnarc** [sublimehq/sublime_merge#1556]
Most of the time I need to watch the context of modification, so if just show the difference of source code, I have to open source file in Sublime Text, if there's an option to show the full souce code and difference in the same viewport, it will be more efficient, thanks.

**Comment by srbs** [comment]
Is this what you're asking about? https://www.sublimemerge.com/docs/diff_context#full_file_toggling

**Comment by dawnarc** [comment]
@srbs Exactly! thanks man :)
