### ISSUE TITLE
Frequent crashes with large repository on Linux

### ISSUE THREAD

**Issue by laffer1** [sublimehq/sublime_merge#1560]
**Version info**

 - OS: Ubuntu 22.04
 - Build: 2059

**Description**

Seeing frequent crashes when modifying a large repository. 

**Steps to reproduce**

1. Open large repository with ~10k files modified and unstaged. 
2. Start staging files. 
3. When ~150 to 200 files are staged, app will just crash randomly.

**Expected behavior**

App shouldn't crash.

**Comment by dpjohnst** [comment]
Hi @laffer1,

Thanks for reaching out. Does this issue occur on the latest version of Sublime Merge ( 2074)?

Kind regards,
\- Dylan

**Comment by laffer1** [comment]
Just installed build 2074.  I'll do some testing and get back to you.

**Comment by laffer1** [comment]
Finally got time to test with the newer 2077 build. It seems to be working a lot better now. Thanks.
