### ISSUE TITLE
"git revert" command not available from command palette

### ISSUE THREAD

**Issue by NTMan** [sublimehq/sublime_merge#1568]
**Problem description**

"git revert" command not available from command palette. It very useful when I know commit hash, but I don't want search this commit in commit history.

Of course would be usefull option "--no-commit" by analogy with the "git merge" command.

![Screenshot from 2022-08-08 03-13-32](https://user-images.githubusercontent.com/200750/183313021-679594fe-e88a-45d3-9829-c3a5b9d2a21a.png)

**Preferred solution**

Add "git revert" command to command palette

**Alternatives**

At present by alternatives I use terminal for enter "git revert" command.

**Screenshots**

![Screenshot from 2022-08-08 03-06-51](https://user-images.githubusercontent.com/200750/183312911-ef963370-d0c8-4ea1-bf32-be61b86f4e30.png)

**Comment by srbs** [comment]
Custom commands can be added, see the docs: https://www.sublimemerge.com/docs/custom_commands

Command for this request:

###### `Default.sublime-commands`:
```
[
	{
		"caption": "Revert Commit…",
		"command": "git",
		"args": { "argv": ["revert", "--no-commit", "$select_commit"] }
	}
]
```

**Comment by NTMan** [comment]
> Custom commands can be added, see the docs: https://www.sublimemerge.com/docs/custom_commands
> 
> Command for this request:
> 
> ###### `Default.sublime-commands`:
> ```
> [
> 	{
> 		"caption": "Revert Commit…",
> 		"command": "git",
> 		"args": { "argv": ["revert", "--no-commit", "$select_commit"] }
> 	}
> ]
> ```

Thanks, exactly that I was needed.
