### ISSUE TITLE
Commit Message Syntax regression

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#1573]
**Version info**

 - OS: Windows 11
 - Build: SM 2076

**Description**

SM used _Packages/Git Formats/Git Commit.sublime-syntax_ to highlight commit messages which scopes commit subjects (1st line) `meta.subject markup.heading`.

A color scheme can therefore highlight it or render it bold via:

```json
{
	"scope": "markup.heading",
	"font_style": "bold",
},
```

Furthermore the second line is highlihgted illegal if none-empty, which is required for subject and message body to be separated.

A new simplified _Packages/Default/Commit Message.sublime-syntax_ ships with ST 2076, which regresses both behaviors.

**Steps to reproduce**

1. Open any repository
2. Customize Mariana.sublime-color-schme to add bold headings
3. View a commit message

**Actual behavior**

![grafik](https://user-images.githubusercontent.com/16542113/184476723-7a579a62-3b0c-4c9c-950d-2f14d7ef0548.png)

**Expected behavior**

![grafik](https://user-images.githubusercontent.com/16542113/184476660-c106c7b4-1d94-4fa9-9b4f-76fc2986bce2.png)

> _Note: Screenshot uses customized Brackets Dark color scheme_

#### Proposal

Use _Packages/Git Formats/Git Commit Message.sublime-syntax_ from https://github.com/sublimehq/Packages/pull/3472 once it is merged.

**Comment by deathaxe** [comment]
Unfortunately Mariana.sublime-color-scheme doesn't make use of it by default.

![grafik](https://user-images.githubusercontent.com/16542113/184476916-aa40162f-9648-4152-83e4-c84a1003cddd.png)

**Comment by dpjohnst** [comment]
Hi @deathaxe,

Thanks for reaching out.

From my understanding, I don't think we've ever used `Git Commit.sublime-syntax` by default - perhaps you replaced the default syntax file with it?

The 2076 update fixed a bug in the default Commit Message syntax file which caused certain URLs to be highlighted incorrectly. It may have been the case that your custom `Commit Message` syntax file was replaced when the updated occurred.

Kind regards,
\- Dylan

**Comment by deathaxe** [comment]
> ... I don't think we've ever used Git Commit.sublime-syntax by default ...

I have indeed been under the impression that ST 2060 assigned exectly this syntax to commit messages.

![grafik](https://user-images.githubusercontent.com/16542113/185317294-ee309ef9-d758-4251-8b82-d2d61d38430d.png)

_Therefore just reset my custom sttings after reading changelog of 2076, out of curiosity._

Now, I wonder why another syntax was created, which even depends on parts of _Git Formats_ package as _Git Commit.sublime-syntax_ is made for exactly this purpose. It contains some contexts/patterns which are required for `COMMIT_EDITMSG` or `MERGE_MSG` only, but all of them apply within comments only, thus don't impact performance in normal commit messages at all - especially with the limited size of commit messages.

Advantage of _Git Commit.sublime-syntax_ is not obvious in a vanilla SM setup due to absense of required color scheme rules in Breakers and Mariana, but rendering _subjet_ different (color, font-style) improves UX as there is only a lot of text on a blank background. It's just easier to spot.

Fortunatelly all custom themes assign _Git Commit.sublime-syntax_ and my custom prefs do so, too.
