### ISSUE TITLE
Copy tag name

### ISSUE THREAD

**Issue by pallzoltan** [sublimehq/sublime_merge#1576]
**Problem description**

When making builds, our CI creates tags and we report to our testers which build (based on tag) to test. We currently have to type out the tag name such as `7.8.0b1001192`, which is prone to mistakes and slightly tedious.

**Preferred solution**

Ideally a right-click menu on a tagged commit would offer a "Copy tag build/beta/7.8.0b1001192" option.

**Alternatives**

A slightly less intrusive change would be right-clicking the yellow tag, which would offer a "Copy tag build/beta/7.8.0b1001192" option.

**Screenshots**

Unnecessary.

**Comment by srbs** [comment]
I have similar needs, my solution was to add my own menu item for tags:

Add this menu item to `Tag.sublime-menu`:
```
[
    {
        "caption": "Copy '$tag_name'",
        "command": "copy_to_clipboard",
        "args": { "text": "$tag_name" }
    },
]
```

**Comment by pallzoltan** [comment]
Thank you so much @srbs, this is a great solution.
