### ISSUE TITLE
Location bar is reset when switching repositories

### ISSUE THREAD

**Issue by RSeidelsohn** [sublimehq/sublime_merge#158]
**Version info**

 - OS: Ubuntu 18.04.1 LTS
 - Build: 1078

**Description**

The state of the location bar is now saved in between sessions, which is good. But when I _switch_ repositories, the new view always opens with the location bar in a reset state (closed and width is the initial one).

**Steps to reproduce**

Open location bar, switch repository, location bar is closed. Switch back to the first repository, and the location bar is still closed.

Steps to reproduce the behaviour:
1. Open repository
2. Open location bar
3. Switch repository
4. The location bar is reset
5. Open location bar
6. Switch back to the previous repository
7. The location bar is reset again

**Expected behaviour**

The state (open/closed, width) of the location bar should be maintained when switching repositories.

**Comment by jskinner** [comment]
Thanks for the report, this is now fixed in Dev Build 1081 at https://www.sublimemerge.com/dev
