### ISSUE TITLE
When a branch has diverged, the amount of commits ahead in the tooltip is wrong

### ISSUE THREAD

**Issue by paulcacheux** [sublimehq/sublime_merge#1584]
**Version info**

 - OS: macOS 12.5.1
 - Build: 2077

**Description**

When a branch has diverged with origin, the amount of commits ahead in the tooltip is wrong, out of sync with the button content

**Steps to reproduce**

1. Create a diverting branch with origin
2. Check that you have both an down-arrow(pull) and a up-arrow(push) button
3. Hover the mouse over those buttons and check the tooltips

**Expected behavior**

The tooltips should be in sync with the button content and the state of the repo

**Screenshots**

<img width="297" alt="image" src="https://user-images.githubusercontent.com/2822037/186102099-24233f03-0e1f-403d-a6ec-2283b0f03c90.png">

**Comment by paulcacheux** [comment]
@dpjohnst any update on this ? It's been nearly 2 months now

**Comment by paulcacheux** [comment]
This issue is still present in Build 2078 from today

**Comment by paulcacheux** [comment]
@dpjohnst It's been nearly 3 months now, and the BUILD 2079 that was released today still has this issue. It's getting a bit frustrating that you are not able to respond on such a small issue

**Comment by dpjohnst** [comment]
Hi @paulcacheux,

Thank you for reporting this, and apologies for the delay in getting back to you.

I can assure you though that this issue has been fixed internally and we are just waiting to release it in the next development build along with some exciting new features!

Thank you for your patience.

Kind regards,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Hi @paulcacheux,

This has been resolved in Sublime Merge 2080 (development build).

Kind regards,
\- Dylan from Sublime HQ

**Comment by paulcacheux** [comment]
I can confirm that the bug is fixed on my end. Thanks
