### ISSUE TITLE
Bug: Modified commit message discarded when Continuing a cherry-pick

### ISSUE THREAD

**Issue by howeaj** [sublimehq/sublime_merge#1588]
**Version info**

 - OS: Windows 10
 - Build: 2074, 2077 (not noticed in earlier builds. My guess would be this was introduced when the "cherry pick multiple commits at once" functionality was added in 2059)

**Description**

When a cherry-pick fails due to conflict (i.e. this message in the log):
```
Auto-merging <stuff>
CONFLICT (content): Merge conflict in <stuff>
error: could not apply 48a95617ff... <commit message>
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
```
You are put into a "resolve conflicts" state, with the changes to be made and the commit message displayed in edit mode

_The commit message is automatically put into edit mode, but clicking "Continue cherry pick" discards any changes that were made to it._

Workaround: Pressing CTRL-ENTER instead has the behaviour that I would expect "Continue cherry pick" to have in this situation for a single commit; the resulting commit has the correct edited message. I don't know if this behaves differently when cherry picking multiple commits at once, though.

**Steps to reproduce**

Steps to reproduce the behaviour:
1. Cherry-pick a commit with a merge conflict
2. Resolve the conflict and edit the commit message with a note about what the conflict was (or uncomment the automated conflicts comment)
3. Click "Continue cherry pick" and read the resulting commit message.

**Expected behaviour**

If the commit message is editable, the edits should be preserved when you click the "Continue" button.
If it can't be preserved, it shouldn't be editable.

**Screenshots**

![image](https://user-images.githubusercontent.com/3149230/186186666-9c66cfbb-3230-4b17-a034-e44cee71d63f.png)

**Comment by howeaj** [comment]
Version 2079 mentions some other fixes to commit message loss, but this one is still present.

**Comment by dpjohnst** [comment]
Hi @howeaj,

Thanks for reporting this issue - this has now been resolved in Sublime Merge build 2080 (development build).

Kind regards,
\- Dylan from Sublime HQ
