### ISSUE TITLE
Option to Disable Location Bar Tree

### ISSUE THREAD

**Issue by tyler8691** [sublimehq/sublime_merge#159]
**Problem description**

In build 1070 the Location Bar was converted to be a tree, with all branches an sections collapsed by default.

For repositories with minimal branches, this just gets in the way. An option to disable this would be fantastic.

**Preferred solution**

Add a preference to disable the "tree" behavior in the Location Bar.

**Alternatives**

None, there is really no middle ground between enabling and disabling the feature.

**Comment by deathaxe** [comment]
Just to understand your proposal: What exactly gets in the way? Branches are expanded by default and hence display nearly the same way as with the old location bar. The only difference is `/` in the branch name to be resolved and displayed as tree.

IMHO the current solution to display remotes and their remote branches is even more consistent than before, when we had two sections for them.

Is it the tree structure itself, which feels not so good or the circumstance of scrolling all branches in one tree?

**Comment by jasonycw** [comment]
Maybe an option to not fold by default like commit list?
As right now, location bar is always folded on startup.
Saving the folding status for location bar should do the trick?

**Comment by jskinner** [comment]
Dev Build 1081 now stores the expanded state of items in the location bar, as well as applies the location bar visibility to new windows

**Comment by jasonycw** [comment]
@jskinner Expand state of location bar is not save when open the repo from the open recent menu
![image](https://user-images.githubusercontent.com/4518597/47539411-e6320580-d902-11e8-89e2-d0246f8a469a.png)

The new windows still collapse the file tree
