### ISSUE TITLE
Git Credential Manager Core can't authenticate Azure repository users

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#1595]
**Version info**

 - OS: Windows
 - Build: 2076 (all)

**Description**

Bundled git's credential manager fails to authenticate a user to dev.azure.com as a relevant configuration is missing.

see: https://forum.sublimetext.com/t/sublime-merge-how-to-save-git-credentials-win-11/64785/10

**Steps to reproduce**

1. Try to authenticate to azure code repository

**Expected behavior**

Single sign on using git-credential-manager-core should work.

**Fix**

Add the following lines to bundled .gitconfig

```
[credential "https://dev.azure.com"]
	useHttpPath = true
```

**Comment by dpjohnst** [comment]
Hi @deathaxe,

Thanks for reporting this - we've added a fix for this and it will be available in the next build.

Cheers,
\- Dylan from Sublime HQ
