### ISSUE TITLE
Parent branch not visible in commit log after merge

### ISSUE THREAD

**Issue by RobertPaauw** [sublimehq/sublime_merge#1596]
**Version info**

 - OS: Windows 10 Pro (64 bit, 21H2 OS build: 19044.1889)
 - Build: 2077

**Description**
After merging the `master` branch into another branch the `master` branch is not visible in the commit log any more. When the `mater` branch is checked out, both branches are visible (as expected). When checking out the feature branch, the `master` disappears.

**Steps to reproduce**

1) Merge `master` into feature branch
2) Checkout `master`, both branches are visible
3) Checkout the feature branch and the `master` disappears.

Unfortunately I cannot share the repository where this occurred.

**Expected behavior**

I would have expected the `master` branch to stay visible when the feature branch is checked out.

**Screenshots**
View from feature branch:
![From feature branch_edited](https://user-images.githubusercontent.com/58423245/187673165-0249bf4b-4147-41dc-a2ea-c5194fd65148.PNG)

View from master branch
![From master branch_edited](https://user-images.githubusercontent.com/58423245/187673179-a88f3ef3-1f48-428c-80d2-4f69c4142fa3.PNG)

**Comment by themilkman** [comment]
Does changing `Preferences -> Commits -> Merge Commit Display` match your expectation?

**Comment by RobertPaauw** [comment]
That solves it nicely. Thank you for the quick reply.
