### ISSUE TITLE
Excessive Memory Usage

### ISSUE THREAD

**Issue by Algo-ryth-mix** [sublimehq/sublime_merge#1601]
**Version info**

 - OS: Windows 11 64bit
 - Build: 2077

**Description**

A description of what the bug is.
Excessive Memory Usage, almost 36 Gigabytes and rising

**Steps to reproduce**

1. Open Sublime Merge 
2. Wait?

**Expected behavior**
Less memory usage

**Screenshots**
![20220907-101710](https://user-images.githubusercontent.com/12379720/188827526-7f2be5a0-63fb-4bab-b9cf-ff89a19f02e8.png)

**Comment by dpjohnst** [comment]
Hi @Algo-ryth-mix,

Thanks for reaching out and sorry that you're experiencing this issue.
When you have a spare moment, could you share the following:
* The output from running the command: `git count-objects -vH`
* The Sublime Merge debug information (accessible via the application menu under `Help > Debug Information`)
    * Before sharing this, please take a moment to redact any information that may be sensitive such as file paths, remote URLs, user information, and PATH data that is sensitive.
* Could you confirm whether this happens on all repositories, or just a specific repository?
* Does the memory usage grow over time when opening, or is it this high from the beginning?

Thanks,
\- Dylan from Sublime HQ

**Comment by Algo-ryth-mix** [comment]
Hey @dpjohnst,
I will run these commands a little later, but here is some additional info
- it is indeed only when opening a specific repository
- it will stay at around 50Mb for a while and all of a sudden it rapidly increases to almost 36 gigs

**Comment by Algo-ryth-mix** [comment]
Sorry it seems like I cannot reproduce it anymore, something in one of my repositories must have changed that initially caused the behaviour. To be fair the repositories I work with are rather large so it is entirely possible that a lot of stuff changed all at once which somehow triggered this.
