### ISSUE TITLE
Allow $text selector for custom commands as substring

### ISSUE THREAD

**Issue by VulumeCode** [sublimehq/sublime_merge#1603]
**Problem description**

The text selector can only be used as a whole string `"$text"`. It cannot be used as a substring.

    [
        {
            "caption": "Create bookmark at commit",
            "command": "git",
            "args": {
                "argv": [
                    "branch", "bookmarks/$text", "$select_commit"
                ]
            }
        }
    ]

Nevertheless, it is parsed and replaced by an empty string.

**Preferred solution**

Do show a prompt for the $text selector.

**Alternatives**

Write "bookmarks/..." every time.

**Screenshots**

![image](https://user-images.githubusercontent.com/2590984/189883252-8144bf90-d070-4e50-ba1e-f206e41ca28d.png)

**Comment by dpjohnst** [comment]
Hi @VulumeCode,

Thanks for sharing this feedback!

This has been addressed in Sublime Merge build 2080 (development).

Kind regards,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Added in Sublime Merge 2083 (stable) :tada:
