### ISSUE TITLE
Untracked files "delete" and "delete all" do nothing. 

### ISSUE THREAD

**Issue by VlodShvetsov** [sublimehq/sublime_merge#1605]
**Version info**

 - OS: Windows 10
 - Build: 2077

**Description**

A description of what the bug is.

**Steps to reproduce**

1. Checkout old commit (or revert a big commit)
2. Showes up a lot of unstaged files (454 in my case)
3. Click on "delete all" or "delete" certain unstaged file.
4. Nothing happens

**Expected behavior**

Delete all unstaged files or delete certain unstaged file

**Screenshots**

![image](https://user-images.githubusercontent.com/58740274/190141636-a1aeb184-f49d-4d91-885b-46fb4f998e41.png)

**Comment by dpjohnst** [comment]
Hi @VlodShvetsov,

Thanks for reaching out and sorry to hear you're experiencing this issue.
When you have a spare moment, could you share the Sublime Merge Debug Information:
1. Open Sublime Merge
2. Open the repository in question
3. Open the application hamburger menu
4. Copy the debug information via `Help > Debug Information`
5. Before sharing this, please redact any information that may be sensitive such as Git user information, remote URLs, path names etc.

Kind regards,
\- Dylan from Sublime HQ

**Comment by srbs** [comment]
see also: #1535

**Comment by VlodShvetsov** [comment]
Hello, I resolve my issue.
It appeared when I select old commit or branch without submidule that preseted in current version of code.

`git clean -fd` doesn't delete these files.
So I use the `git clean -ffd` and it helps me.

Thanks for feedback!
