### ISSUE TITLE
please provide option to disable font glyph ligatures

### ISSUE THREAD

**Issue by dentad** [sublimehq/sublime_merge#1615]
**Problem description**

First, I am sorry I don't know the right word for this, but I know font people do have a word for it. (Ligatures...?)

In my code editor (VS Code) I have a Python expression "leftside != rightside". In my code editor the symbol in the middle is a "not equal to" operator which I see as a "!" immediately followed by a "="... "!=".

In Sublime Merge, set to the same font as my code editor, instead I see a large equal sign with a slash superimposed on it.

Please add an option to revert this super annoying behavior.

**Preferred solution**

Add an option to allow user to choose to use this font feature or not.

**Alternatives**

-

**Comment by jfcherng** [comment]
You can manually set the following in preferences.

```js
    "font_options": [
        "no_liga",
        "no_clig",
        "no_calt",
    ],
```

**Comment by dentad** [comment]
Oic. Awesome. Thanks!
Maybe a future gui  preference enhancement.

Problem solved for me, so im closing.
