### ISSUE TITLE
Please add "blame parent commit"

### ISSUE THREAD

**Issue by sxenos** [sublimehq/sublime_merge#1619]
**Problem description**

When in blame view, git gui has a "blame parent commit" action that lets you run blame on the version of the file that the selected line came from. This is very useful for viewing changes in the context in which they were originally written. I miss it dearly when using sublime merge.

**Preferred solution**

A new context menu action that opens when right-clicking on a line of code or the commit info sidebar while in blame view.

**Comment by srbs** [comment]
> the commit info sidebar while in blame view

The gutter of each line when in blame mode has the commit hash & author initials. If you hover over that area, a pop up will appear with a clickable commit hash which will navigate to that commit's blame. If you then wanted the parent, just pick the previous commit in the commit list panel.

**Comment by sxenos** [comment]
Ah! I never discovered that because I never use hovers. My hand isn't steady enough to reliably keep them open, and I find waiting for them to be frustrating.

I'll close this and open a feature requests for the addition of a "blame parent" gesture that doesn't require waiting for a hover.

**Comment by ptere** [comment]
Follow-up is in #1625
