### ISSUE TITLE
Respect LC_TIME

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/sublime_merge#162]
**Problem description**

All timestamps are displayed in a US locale, despite having `LC_TIME=en_DK.UTF-8` set, which specifies ISO dates and times.
`Wed, 19 Sep 2018 4:30 AM` in timestamps for commits in the commit view, and `Wed 4:30 AM` in the commit history. I don't fancy the 12-hour format.

**Preferred solution**

Respect `LC_TIME=en_DK.UTF-8` (and similar).

**Alternatives**

Add an option.

---

Related: #65

**Comment by deathaxe** [comment]
SM 1081 addresses this issue.

**Comment by FichteFoll** [comment]
Not for Linux.

**Comment by Kolobamanacas** [comment]
> A preference was added for this is 1083

Sorry for probably inappropriate place to ask, but where can one find this preference? I can't see anything like this in "Preferences" in 2079.

**Comment by FichteFoll** [comment]
![2022-12-01_13-20-49](https://user-images.githubusercontent.com/931051/205051613-698a3d27-2bde-480d-b092-4de10e2516c4.png)

**Comment by Kolobamanacas** [comment]
Maybe I've read the thread not good enough as I wish not only to have the ability to choose time format, but also a date format. To set it to something like yyyy-mm-dd hh::mm

**Comment by FichteFoll** [comment]
That's probably not so trivial because currently SM uses 4 different formats depending on how long ago the commit was. My initial problem was solved here, though, so I suggest to open a new issue with your precise demands.
