### ISSUE TITLE
Show tags in a branch when only a single branch is shown

### ISSUE THREAD

**Issue by nikhilm** [sublimehq/sublime_merge#1621]
**Problem description**

For my project, I have a release branch, and every few commits there are version number tags. Sometimes I want to quickly see what changes happened between two versions. To do this, I would like to declutter the Commits view first by hiding all other branches, and then I would like to multi-select the two tagged commits to see the differences/list of commits between them.

However, as soon as I hide all other branches (by right clicking on the branch I want to see, or by using the sidebar "eye" icons), Sublime Merge also hides the tags, so I'm lost.

**Preferred solution**

Treat tags as separate from branches and always show them.

**Alternatives**

- Make it easy to "mark" a commit in some way. Because sublime merge loses focus on a commit whenever I do "Navigate to <branch/tag/commit>", I can't do the following workflow:
1. Navigate to tag -> v4.4.6 (example version)
2. Somehow keep this commit selected in the Commits list (**Currently not supported**)
3. Navigate to tag -> v4.4.5 (the previous version)
4. Use multi-select between these.

**Screenshots**

When all branches are visible, the tag is being displayed.
![image](https://user-images.githubusercontent.com/78682/195392823-cf488ebf-4ebb-462f-98be-e2a5361ab9d5.png)

When only one branch is visible, the tag is hidden (the lower arrow points to the same commit where the tag should've been before.

![image](https://user-images.githubusercontent.com/78682/195393330-64e92d1c-1b29-470f-8ead-46e52c646ebf.png)

**Comment by themilkman** [comment]
Not sure if this helps, but does Alt/Super and click on the Eye icon next to "TAGS (..)" help you? Tbh I didn't know about this before.

**Comment by nikhilm** [comment]
> Not sure if this helps, but does Alt/Super and click on the Eye icon next to "TAGS (..)" help you? Tbh I didn't know about this before.

This works, but is not a realistic approach with hundreds of tags.

**Comment by themilkman** [comment]
I guess I misunderstand you, but I to be sure: I meant the heading "TAGS", not the actual tags.

**Comment by nikhilm** [comment]
Ah! Thanks for clarifying. Yes, clicking on the TAGS group does show the tags. This is a reasonable workaround.
