### ISSUE TITLE
"opening here" from PowerShell

### ISSUE THREAD

**Issue by aropele** [sublimehq/sublime_merge#1634]
**Problem description**

When you work a lot from terminal and you are inside a project, it is such a huge pain to move away the hands from the keyaboard and reaching the mouse in order to open Sublime Merge.
Then you have to do a ton of clicks in order to open the project inside Merge.

**Preferred solution**

It would be wonderful to enable the same feature of VSCode that allows you to open inside VSC the current folder by typing `code .`, as in the screenshot:
![immagine](https://user-images.githubusercontent.com/30937097/198963676-9ea2a5e6-c1ba-4bda-9aea-011f0b10dd27.png)

For Sublime Merge it would be very usefull to obtain the same behaviour, maybe writing **`merge .`** inside the terminal.

**Comment by jfcherng** [comment]
`subl` for sublime text and `smerge` for sublime merge. but the key part is that you have to manually add the installation directories into the `PATH` env variable.

**Comment by aropele** [comment]
It works perfectly, many thanks!

**Comment by stinos** [comment]
> the key part is that you have to manually add the installation directories into the PATH env variable.

I'd suggest using an alias to the full path instead: they can be even shorter (I use `st` and `sm`) and PATH stays shorter which is always good. For PS that would be:

```
Set-Alias st 'C:\Program Files\Sublime Text 3\sublime_text.exe'
Set-Alias sm 'C:\Program Files\Sublime Merge\sublime_merge.exe'
```

**Comment by aropele** [comment]
Yes, optimization never ends...
