### ISSUE TITLE
Deleting a branch always scrolls commit list to the top

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#1635]
**Version info**

 - OS: Windows 11
 - Build: 2076

**Description**

Each time, I skim through the history of repos to remove no longer WIP branches (or giving up incomplete ideas), I get interrupted by SM always scrolling to HEAD after a branch is deleted. This is annoying and takes a lot of time to get back to the point I was before.

I thought it was enough in older builds to just select a nearby commit and than just right-click the branch to delete it. But in SM 2076 right-clicking the branch selects its commit, too. As a result SM resets scroll position after deletion, because the previously selected commit doesn't exist anymore.

**Steps to reproduce**

1. Delete a branch which is way back in history

**Expected behavior**

Don't change scroll position. Maybe select the nearest commit (newer or older, don't care)

**Comment by srbs** [comment]
I 100% agree and am now in the habit of clicking a few surrounding commits prior to branch deletion & then `Navigate > Go Back`-ing to get back where I was.

**Comment by dpjohnst** [comment]
Hi @deathaxe,

Thank you for your reporting this issue!
This was resolved in Sublime Merge 2084 (and will be fixed in the next stable build too).

Kind regards,
\- Dylan from Sublime HQ
