### ISSUE TITLE
Can not push to gerrit

### ISSUE THREAD

**Issue by zhaonianzhu** [sublimehq/sublime_merge#1640]
- OS:  Ubuntu 16.04

gerrit: git push origin branch_a:refs/for/branch_b 
sublime: git push origin branch

I add Default.sublime-commands.
`
{
    "caption": "push test",
    "command": "git",
    "args": {"argv": ["push", "origin", "HEAD:refs/for/$select_remote_branch"]}//The wrong way
}
{
    "caption": "push test2",
    "command": "git",
    "args": {"argv": ["push", "origin", "$text"]}// git push origin "branch"
}
`

what can i do to use "git push origin branch_a:refs/for/branch_b"
I want branches to be optional.

**Comment by srbs** [comment]
I don't understand what you are trying to accomplish here. Can you explain the behavior you see & the behavior you want?

---

> I want branches to be optional.

This reminds me of #341

**Comment by zhaonianzhu** [comment]
i changed to push `git push origin HEAD:refs/for/branch_a`
checkout other push`git push origin HEAD:refs/for/branch_b`
branch is different,
Default.sublime-commands.Customization is not support `git push origin HEAD:refs/for/$select_remote_branch`
I have implemented it in the Packages/User/Branch.sublime-menu
`[
    {
        "caption": "推送HEAD到远程分支...",
        "command": "git",
        "args": {
            "argv": ["push", "--progress", "origin", "HEAD:refs/for/$branch"]
        }
    },

    {
        "caption": "推送HEAD到Gerrit分支",
        "children":
        [
            {
                "caption": "origin",
                "command": "git",
                "args": {
                    "argv": ["push", "--progress", "origin", "HEAD:refs/for/$branch"]
                }
            },
            {
                "caption": "origin2",
                "command": "git",
                "args": {
                    "argv": ["push", "--progress", "origin2", "HEAD:refs/for/$branch"]
                }
            }
        ]
    },
]`
