### ISSUE TITLE
View combined changes from multiple commits 

### ISSUE THREAD

**Issue by xims** [sublimehq/sublime_merge#1643]
**Problem description**

Often work is done in multiple commits, including changes to the same code blocks. 
But it's hard to see the combined changes when spread over multiple commits. 
It would be very useful to be able to see combined changes from multiple commits.

**Preferred solution**

Being able to select multiple commits in the commits section and see the combined changes from multiple files in the summary section would be amazing!

**Alternatives**

Any other possibility to somehow select multiple commits and view combined changes would be great.

Thank you!

**Comment by srbs** [comment]
See the 'Can I diff between two commits?' section of the FAQ docs: https://www.sublimemerge.com/docs/faq#diffing_between_commits

**Comment by xims** [comment]
You're right, that's what I was after!
I kept selecting 2 commits next to each other and it didn't show both, should've selected one before that...

Thank you!

**Comment by srbs** [comment]
@xims, ah yes that is a common source of confusion. Take a look at my explanation of that behavior here: https://github.com/sublimehq/sublime_merge/issues/255#issuecomment-596668053
