### ISSUE TITLE
Select previous query text in Search field

### ISSUE THREAD

**Issue by stinos** [sublimehq/sublime_merge#1646]
**Problem description**

Hitting Ctrl-F then starting to type only works once, because the previous search query text is still (which is good) but the cursor is after the text, so the previous text first needs to be deleted manually (not good, requires one multi-key keystroke like Ctrl-Backspace).

**Preferred solution**

Like in Sublime Text, VSCode, Visual Studio, ...: retain the previous text in the search field but select it. Result:
- just starting to type erases previous text and new query just works
- the other case where one wants to modify the previous query still just works without change

(note that the Filter text box actually works like this already)

**Comment by dpjohnst** [comment]
Hi @stinos,

Thanks for sharing this feedback!

This has been addressed in Sublime Merge build 2080 (development).

Kind regards,
\- Dylan from Sublime HQ

**Comment by stinos** [comment]
> This has been addressed in Sublime Merge build 2080 (development)

@dpjohnst it has indeed, thanks!
