### ISSUE TITLE
Copy path to uncommitted file

### ISSUE THREAD

**Issue by KrilYura** [sublimehq/sublime_merge#1648]
**Problem description**
Lets say I made changes to some files in sublime
I saved and closed one of them
Now that I'm looking at changed files in sublime merge I want to make some additional changes to the closed file
I can find the file and reopen it but would be great if I could just copy file path from sublime merge so that I can open it with sublime using command+P

**Preferred solution**

Whenever there is path to a file there should be easy way to copy it

**Alternatives**

Since sublime merge is related app, it would be super great if I could click a button in sublime merge and the file is opened in sublime

**Screenshots**
There is a way to copy file path or open the file when it is committed 
![image](https://user-images.githubusercontent.com/1006331/202572127-3507511e-dc46-410c-a41b-a52c4ac466b4.png)
But there is no way to copy file path or open the file when it new or changed committed
![image](https://user-images.githubusercontent.com/1006331/202572298-76f8de58-930a-4c8d-b09f-aa32bd9adde1.png)

**Comment by srbs** [comment]
partial duplicate: #178
see https://github.com/sublimehq/sublime_merge/issues/178#issuecomment-433111449 for a work around

**Comment by dpjohnst** [comment]
Hi @KrilYura,

Thanks for reaching out!

You can currently copy the file path via file context menu in the `Files` tab.
Additionally you can open the file in your favourite editor using the "Open in Editor" context menu item.

I'll close this issue as we currently support this functionality, but we'll be looking at adding this functionality in additional areas such as the diff title bar.

Kind regards,
\- Dylan
