### ISSUE TITLE
Sort commit graph by author date instead of commit date

### ISSUE THREAD

**Issue by themilkman** [sublimehq/sublime_merge#1657]
**Problem description**

E.g. when rebasing a big branch it'd be very useful to have the "original" commit and the rebased one near to each other.

**Preferred solution**

Add a possibility to switch the order of the commits/commit graph to the author date.

**Alternatives**

None that I could think of for this.

**Comment by srbs** [comment]
related: #1169
see also: #1100

**Comment by themilkman** [comment]
While I still struggle with the understanding and impact of the topological order which mixes in, this has been added in dev build 2081 and seems to work fine, thanks! :partying_face:

**Comment by themilkman** [comment]
When the topological order is equal (which is mostly the case on rebases) this works like a charm. Thanks again!
