### ISSUE TITLE
Bug: can't adjust the size of Sublime Merge

### ISSUE THREAD

**Issue by innicoder** [sublimehq/sublime_merge#1664]
# Issue

I can't find any settings to scale the size of the sublime merge, the font only applies to the actual code and doesn't affect sublime tabs and other things. (Like in sublime UIscale)

It doesn't work currently and I couldn't find any resource on how to do it in preferences either..

**Comment by dpjohnst** [comment]
Hi @innicoder,

Thanks for reaching out!

To scale up the UI, you can set the `ui_scale` setting via `Preferences > Edit Settings...`

Once the settings file is open, you can add the following:
```
// Settings in here override those in "Default/Preferences.sublime-settings",
// and are overridden in turn by syntax-specific settings.
{
    "ui_scale": 2.0,
}
```

Once saved, you'll need to restart Sublime Merge for the scaling to take effect. Hope this helps!
Note that this isn't currently exposed in the preferences dialog, but we'll look into adding this in the future.

Kind regards,
\- Dylan from Sublime HQ
