### ISSUE TITLE
No files in Tree view

### ISSUE THREAD

**Issue by naringas** [sublimehq/sublime_merge#1667]
**Version info**

 - OS: Manjaro, X11, KDE Plasma 5.26.3
 - Build: 2079

**Description**

Tree view in files is always empty, I tried a few different repos

**Steps to reproduce**

1. Open repository
2. Choose some commit
3. Look at the Tree, next to the Changes tab-button
4. The tree is empty, see the screenshot

**Expected behavior**

There should be files there, I tested this on a 2069 build in another computer and it's fine.

**Screenshots**

![image](https://user-images.githubusercontent.com/566811/205365211-6913aa78-6c0d-4317-9e30-41f946a17e46.png)

**Comment by dpjohnst** [comment]
Hi @naringas,

Thanks for reporting this - we're actively investigating this and will let you know when we have an update.
As a temporary workaround, you can toggle between the `Tree` and `Changes` at the bottom of the files view, and the tree will load correctly.

Kind regards,
\- Dylan from Sublime HQ

**Comment by naringas** [comment]
hello, toggling doesn't do anything, the Tree view stays empty.

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge 2083 :tada:
