### ISSUE TITLE
[dev] Custom command stopped working in latest build

### ISSUE THREAD

**Issue by Zwyx** [sublimehq/sublime_merge#1669]
**Version info**

 - OS: Ubuntu 22.04.1
 - Build: Dev 2080

**Description**

I have a custom context menu command **Open containing folder…** in my `~/.config/sublime-merge/Packages/User/Diff Context.sublime-menu`:

```js
{
	"caption": "Open containing folder…",
	"command": "git",
	"args": { "argv": ["sublime-merge-open-containing-folder", "$working_dir/$path"] }
}
```

(It works with a git alias.)

It has been working well for months, but in the last release, it is now greyed out in the menu:

![image](https://user-images.githubusercontent.com/29386932/205806731-1323079c-cc3e-49e3-b3d2-5d3335dafe22.png)

I noticed that changing `"$working_dir/$path"` to only `"$working_dir"` or `"$path"` makes the entry available in the menu (but doesn't provide the intended behaviour):

![image](https://user-images.githubusercontent.com/29386932/205806713-52bc1604-edac-4585-b2b9-06a3ef4291a4.png)

**Comment by Zwyx** [comment]
I was able to make it working again by replacing `"$working_dir/$path"` with two arguments: `"$working_dir", "$path"`.

Looks like we can't have more than one variable per argument.

It seems like a regression, but if this new behaviour is wanted, feel free to close this issue.

**Comment by dpjohnst** [comment]
Hi @Zwyx,

Thanks for reporting this issue - I'll be investigating this further.

Cheers,
\- Dylan from Sublime HQ

**Comment by joelekstrom** [comment]
Possibly related to #1671

**Comment by dpjohnst** [comment]
Hi @Zwyx,

Just a quick update - this will be resolved in the next build.

Kind regards,
\- Dylan from Sublime HQ

**Comment by Zwyx** [comment]
Hi Dylan, that's awesome, thanks for letting us know!

**Comment by themilkman** [comment]
For me this is fixed with dev build 2081 :+1:

**Comment by Zwyx** [comment]
Thanks Erik!
