### ISSUE TITLE
Resize hunk diff window grabber thing takes priority over clicking on stage hunk button

### ISSUE THREAD

**Issue by superlopuh** [sublimehq/sublime_merge#167]
**Version info**

 - OS: macOS
 - Build: 1079

**Description**

When I try to click stage hunk after scrolling for half a line in the window, the button doesn't work. The resizing of the window is done instead

**Steps to reproduce**

1. change line in file
2. look at diff in sublime merge
3. scroll down by half a line in the diff view
4. attempt to stage hunk
5. hunk is not staged

**Expected behavior**

Hunk is staged

**Comment by jskinner** [comment]
Thanks for the report, this is fixed in Dev Build 1081 at https://www.sublimemerge.com/dev
