### ISSUE TITLE
Add ability to cherry-pick merge commits

### ISSUE THREAD

**Issue by n8gray** [sublimehq/sublime_merge#168]
**Problem description**

In a typical pull-request based workflow involving multiple branches you sometimes need to cherry-pick a merge commit.  If you try to cherry-pick a merge commit in SM today you currently get an error: 
```
error: commit 92a65646e946dc350d948165d603baf1fb850f72 is a merge but no -m option was given.
fatal: cherry-pick failed
```

**Preferred solution**

To cherry-pick a merge commit you need to specify which parent should be diffed against (to pass to `-m`).  It would be nice if SM displayed a dialog allowing the user to choose from the two (or more!) parent commits.  Ideally this would include lots of rich information about each commit, including author, date, committer, message, etc.  Bonus points if you can drill in to see the actual diff of each commit.

**Alternatives**

At the very least, a dialog letting you type a number (1 for first parent, 2 for second, etc) would suffice.

**Comment by willrowe** [comment]
This would be very helpful since it just displays an error message, meaning there is no way to cherry pick merge commits at all currently.

**Comment by dpjohnst** [comment]
This was fixed as of Sublime Merge build 1117.

Thanks,
\- Dylan
