### ISSUE TITLE
Crash when the signature of a commit is checked

### ISSUE THREAD

**Issue by niquenen** [sublimehq/sublime_merge#1693]
**Version info**

 - OS: macOS 13.1 (22C65)
 - Build: 2079

**Description**

A crash occurred in Sublime Merge when the signatures were checked. The problem occurs when using [GPG Suite](https://gpgtools.org/) and loading the key of a teammate on one of his commits. His key was not shared on a [keyserver](http://keyserver.ubuntu.com/).

One solution is to not click on the commit that is crashing to avoid the issue.

Another solution is to update the dirmngr configuration to add a missing server.

1. Open the directory `~/.gnupg`.
2. Open the file `dirmngr.conf`.
3. Add a missing server (example: `keyserver hkps://keyserver.ubuntu.com`).

A key can be checked with the following command:

```sh
gpg --keyserver keyserver.ubuntu.com --search-keys '<EMAIL>'
```

If a key is not shared, you can import it manually. You can list your keys with the command `gpg --list-keys --keyid-format LONG`. The command `gpg --import public.key` can be used to import a key and `gpg --list-public-keys` to list the previous import.

**Steps to reproduce**

1. Have [GPG Suite](https://gpgtools.org) suite installed.
5. Clone a repository.
6. Open Sublime Merge.
7. Click on the commit, where the key does not seem to be checked.

**Expected behavior**

The crash occurs after the dirmngr binary crash. Sublime Merge should display an invalid signature in case of a bad verification and crash of the binary.

You can find the version of this binary with the following command.

```console
foo:~$ dirmngr --version

dirmngr (GnuPG/MacGPG2) 2.2.40
Copyright (C) 2022 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Screenshots**

You can find attached two images of one of my commits that is verified and one that loads before the crash. A crash report ([crash-report.zip](https://github.com/sublimehq/sublime_merge/files/10339976/crash-report.zip)) is also available.

<div align="center">
  <img
    width="440"
    alt="Screenshot 2023-01-03 at 22 28 23"
    src="https://user-images.githubusercontent.com/7528452/210445959-f1596d16-4c1d-47e0-80f5-686a5af52404.png"
  />
</div>

<div align="center">
  <img
    width="440"
    alt="Screenshot 2023-01-03 at 22 28 35"
    src="https://user-images.githubusercontent.com/7528452/210445962-9d6681f4-ada8-43e9-8443-edfe75cc8aa6.png"
  />
</div>

<div align="center">
  <img
    width="674"
    alt="Screenshot 2023-01-03 at 22 35 39"
    src="https://user-images.githubusercontent.com/7528452/210445970-9f6d04ab-ac10-4291-8e4f-d48772ba82b3.png"
  />
</div>

**Comment by tdkt** [comment]
I can confirm this on macos 13.1 one. It's pretty crippling. After having downloaded certain keys manually it doesn't seem to crash anymore on that repository, but for some commits I see `valid`, and for some commits `No public key` even made by the same person, so it's not 100% clear what exactly happens but manually downloading the keys alleviated some crashes for sure.

**Comment by cwfitzgerald** [comment]
This is a real blocker - it's making some projects completely unnavigable on mac

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge 2083 (stable)

**Comment by cwfitzgerald** [comment]
Works like a charm, thanks to everyone!

**Comment by tdkt** [comment]
And auto fetch! Thanks a lot.
