### ISSUE TITLE
Improve tab navigation

### ISSUE THREAD

**Issue by y10s** [sublimehq/sublime_merge#1696]
My ST window holds a bunch of tabs (about 30). In order to improve tab handling, I'd love

* the repo tab list (accessible via the triangle on the right side of the tab bar) being alphabetically sorted or having the option to be sorted
* a command to access a tab by its name (the repository name), so that I can use the command palette to switch to a repo tab and add a keybinding for searching a repo tab

Cheers!

**Comment by srbs** [comment]
@y10s, please follow the templates & it would be best to create separate tickets per feature request.

> alphabetically sorted or having the option to be sorted

I don't think I've ever seen any application do this before. Sounds more like you want your tabs in alphabetical order to begin with.

> a command to access a tab by its name

`File` -> `Switch Repository...`

**Comment by y10s** [comment]
My bad, I did not find the `File` -> `Switch Repository...` which was exactly what I was looking for.

Will use the template in the future, sorry for that.
