### ISSUE TITLE
Add setting for custom rulers

### ISSUE THREAD

**Issue by Zooce** [sublimehq/sublime_merge#170]
**Problem description**

Sublime Text has a great setting called "rulers" where any number of column guides can be specified. This can even be done for specific types of files, which is perfect for commit messages which many organizations have defined standards for. Sublime Merge doesn't seem to have this setting yet.

**Preferred solution**

I'd like to request that a "rulers" setting and a "commit_message_rultes" setting be made available in Sublime Merge.

**Comment by jskinner** [comment]
Sublime Merge does support the `rulers` setting, you just need to put it in `Commit Message.sublime-settings`. You can access this file from the `Preferences/Edit Commit Message Settings` menu.
