### ISSUE TITLE
Staging deleted file does nothing

### ISSUE THREAD

**Issue by nrusch** [sublimehq/sublime_merge#171]
**Version info**

 - OS: CentOS 7.3.1611
 - Build: 1079

**Description**

Deleted files show up in the "Working Directory" list, highlighted red. Clicking their `Stage` buttons removes them from the list, but does not actually stage them as delete operations; after a refresh, they are back in the "Working Directory" list again.

**Steps to reproduce**

1. Manually delete a tracked file
2. Refresh Sublime Merge
3. Click the "Stage" button next to the file.
4. Refresh Sublime Merge

**Expected behavior**

The deleted file should be staged as "deleted". It might be desirable to make staging a deleted file a "two-click" operation, the way discarding file/hunk diffs is.

**Comment by nrusch** [comment]
OK, it has to do with SM on Linux not shipping with git, and the system having a pre-2.0 version installed. Overriding the git binary preference with a 2.x version "fixes" the issue.

With that possibility in mind, I think it would be worth it for SM to either A) put a hard floor on the required git version, or B) handle the version differences in command specification.

**Comment by jskinner** [comment]
Thanks for the update - I'm closing this issue, as supporting Git 1.x is currently a non-goal for Sublime Merge, but feel free to open an issue specifically about that
