### ISSUE TITLE
When nothing in stage, notify the user when they want to commit

### ISSUE THREAD

**Issue by kud** [sublimehq/sublime_merge#1717]
**Problem description**

Imagine you have nothing in stage and you try to commit via the keyboard after having written a sentence in this commit.

**Preferred solution**

Display a notification/toast saying "Nothing in stage yet".

**Comment by dpjohnst** [comment]
Hi @kud,

Thanks for reaching out and sharing this feedback!

We currently display a "Nothing to commit" label in the commit button if there is nothing in the staged files section.
Could you confirm if this is not the case for you, and we can investigate further (likely a bug).

Many thanks,
\- Dylan from Sublime HQ
