### ISSUE TITLE
Cannot pop/drop stash when using custom git binary path

### ISSUE THREAD

**Issue by nicholas-ochoa** [sublimehq/sublime_merge#1719]
**Version info**

 - OS: Windows 10
 - Build: Build 2082 Dev Channel

**Description**

When I try and drop / pop stash I'm getting an error message:

![image](https://user-images.githubusercontent.com/126299/218553972-2396510b-5a30-43a0-8117-cc45aefb1f83.png)
![image](https://user-images.githubusercontent.com/126299/218553991-86f331c1-d611-4655-abf9-fe07048d503c.png)

If I open a terminal and run the same command it runs successfully:

![image](https://user-images.githubusercontent.com/126299/218554088-ffd81824-18fe-4089-93f6-465ce9d9575e.png)

I have a custom Git binary configured in Sublime Merge:
<img width="441" alt="image" src="https://user-images.githubusercontent.com/126299/218555102-3d1d1640-0fa7-4cdf-a0f1-b7bdfa2b4df1.png">
I confirmed that the binary I'm calling in the Terminal is the same that I'm calling in Sublime Merge.

When I change this back to `bundled` it seems to work just fine from Sublime Merge.

I can't remember what issue I had that prompted me to change the Git path, so leaving it at `bundled` is fine for now but I figured this was still worth reporting.

The version of git I was using is `2.39.1` installed via MSYS2 UCRT64.

**Steps to reproduce**

1. Open repository
2. Make some changes to a file and then stash those changes
3. Right click on the stash in the Locations tab and select Drop Stash

**Expected behavior**

The stash should drop without issue.

**Comment by nicholas-ochoa** [comment]
Well, I quickly remembered why I use a custom git binary when I tried to push out some commits. I cannot get the `bundled` git to pick up my SSH keys correctly (probably because I'm using ssh-agent instead of using pagent even though I'm on windows). I've reverted back to the custom git binary for now, hopefully this issue can be fixed.

**Comment by dpjohnst** [comment]
Hi @nicholas-ochoa,

Thanks for reaching out - it looks like your shell is escaping the `{`/`}` characters when they're passed in. Could you confirm what shell you're using?

Kind regards,
\- Dylan from Sublime HQ

**Comment by nicholas-ochoa** [comment]
I'm using Bash via MSYS2

**Comment by dpjohnst** [comment]
Hi @nicholas-ochoa,

Sublime Merge 2086 (development build) has been released which fixes this.
This fix will also be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ
