### ISSUE TITLE
Active branch is not bold when inside a folder

### ISSUE THREAD

**Issue by cunninghamd** [sublimehq/sublime_merge#172]
**Version info**

 - OS: Windows 10
 - Build: 1079

**Description**

A description of what the bug is.

When I expand a "folder" under Branches, the active branch is not bold until I click on it.

INTERESTING: When I was trying to take a screenshot, GreenShot must have called some sort of window refresh statement, because it made SMerge bold the branch. So there's some weirdness there.

1. Check out a branch prefixed with a folder name, i.e.: feature/
2. collapse the folder, then re-expand it.

**Expected behavior**

The active branch should be emboldened (i.e.: bold) when the folder is expanded.

**Screenshots**

![image](https://user-images.githubusercontent.com/6536735/47432742-ea2c1f00-d76c-11e8-976d-a0c7ae92402b.png)

![image](https://user-images.githubusercontent.com/6536735/47432778-03cd6680-d76d-11e8-98f7-b80a36be156e.png)

**Comment by jskinner** [comment]
Thanks for the report - this is now fixed in Dev Build 1081, at https://www.sublimemerge.com/dev
