### ISSUE TITLE
Drag commits to rebase

### ISSUE THREAD

**Issue by samholmes** [sublimehq/sublime_merge#1728]
**Problem description**

To re-order a single commit on a branch, one must run `git rebase -i <merge-base>` and then edit a text file.

**Preferred solution**

Add a feature that allows you to drag a commit up and down to re-order the commit using rebase.

**Alternatives**

Holding down a key modifier to avoid accidentally rebasing branches.

**Comment by dpjohnst** [comment]
Hi @samholmes,

Thank you for reaching out and sharing this feedback - this is definitely something we're wanting to support!

I'm going to put this under the same umbrella as https://github.com/sublimehq/sublime_merge/issues/1194
Feel free to head over to that issue and give it a thumbs up to show your interest in this feature.

Thanks,
\- Dylan from Sublime HQ
