### ISSUE TITLE
Add ability to commit with `--no-verify` to disable hooks

### ISSUE THREAD

**Issue by jkrehm** [sublimehq/sublime_merge#173]
**Problem description**

I would like to have the option to skip pre-commit hooks, e.g. to skip tests when committing changes to a README.

Currently, if I want to commit like that, I have to open up a terminal and perform the commit via CLI (or use SourceTree).

**Preferred solution**

Add an option to the "Commit" button dropdown to skip hooks.

**Alternatives**

Any other means to disable hooks for the commit.

**Comment by schnoddelbotz** [comment]
It would also be nice to have `--no-verify` in the drop-down list for *push* options (to circumvent `pre-push` hook).

**Comment by blaggacao** [comment]
@wbond Is there plans to milestone this?

**Comment by wbond** [comment]
We use milestones to indicated what build contained a new feature or bug fix. I do not have any info on when/if this will be added.

**Comment by jkrehm** [comment]
This is the sort of functionality that I would love to have.

![skip_hooks](https://user-images.githubusercontent.com/999845/55297061-d26d5c80-53d6-11e9-8369-7e1370466bd0.png)

**Comment by srbs** [comment]
This has been added in dev build 1113.

**Comment by MatthewKelly** [comment]
Can we also have this for push? e.g. git push --no-verify

**Comment by srbs** [comment]
@MatthewKelly, please create a new enhancement request for that request.

**Comment by jkrehm** [comment]
Thank you for adding this functionality!
