### ISSUE TITLE
Sublime Merge after start consume 100% CPU all time. It beginning after update from version 2082-1 to version 2084-1.

### ISSUE THREAD

**Issue by NTMan** [sublimehq/sublime_merge#1736]
**Version info**

 - OS: Fedora Rawhide
 - Build: 2084

**Description**

Sublime Merge after start consume 100% CPU all time. It beginning after update from version 2082-1 to version 2084-1.
Also Sublime Merge stop respond when I try quit application by pressing [x] at right upper window corner.

**Steps to reproduce**

1. Start Sublime Merge
2. Open Linux repository `git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`
3. Check CPU load
4. Try close Sublime Merge after several minutes continuous 100% CPU loading.

**Expected behavior**

- Sublime Merge does not consume 100% CPU all time 
- And closes immediately at the request of the user

**Debug Information**

```
=== App Version Information ===
Build: 2084

=== Git Version Information ===
Using Git: git (system)
git version 2.40.0
PATH: /usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/mikhail/.dotnet/tools

=== Browse Page Information ===
HEAD: f3a2439f20d918930cc4ae8f76fe1c1afd26958f
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===
?? fix-wifi.diff
?? grab-extra-fence-reference-for-drm_sched_job_add_dependency.diff
?? kunit-patch.diff
?? leak-fix-patch.diff
?? patch-a.diff
?? patch-b.diff
?? revert-rework-entity-flush-kill.diff
?? tools/bpf/resolve_btfids/libsubcmd/

=== Our Status Information ===
?? fix-wifi.diff
?? grab-extra-fence-reference-for-drm_sched_job_add_dependency.diff
?? kunit-patch.diff
?? leak-fix-patch.diff
?? patch-a.diff
?? patch-b.diff
?? revert-rework-entity-flush-kill.diff
?? tools/bpf/resolve_btfids/libsubcmd/include/subcmd/exec-cmd.h
?? tools/bpf/resolve_btfids/libsubcmd/include/subcmd/help.h
?? tools/bpf/resolve_btfids/libsubcmd/include/subcmd/pager.h
?? tools/bpf/resolve_btfids/libsubcmd/include/subcmd/parse-options.h
?? tools/bpf/resolve_btfids/libsubcmd/include/subcmd/run-command.h

=== Git Config Information ===
branch.master.merge=refs/heads/master
branch.master.remote=origin
core.bare=false
core.filemode=true
core.logallrefupdates=true
core.repositoryformatversion=0
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

=== Our Config Information ===
Git Config Path Information
Using config path: /usr/etc/gitconfig
Using config path: /home/mikhail/.config/git/config
Using config path: /home/mikhail/.gitconfig
Using config path: /home/mikhail/packaging-work/git/linux/.git/config

Our config output is identical to the Git config output

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 0
```

**Screenshots**

![Screenshot from 2023-03-17 03-11-55](https://user-images.githubusercontent.com/200750/225767228-0e325eda-0d65-4f98-974b-46562435118f.png)

![Screenshot from 2023-03-17 03-20-46](https://user-images.githubusercontent.com/200750/225767258-e15de45c-5889-497a-a31b-73005c6dbc3c.png)

**Comment by dpjohnst** [comment]
Hi @NTMan,

Thanks for reporting this issue - we've identified the cause of the issue and are actively working on a fix - stay tuned.

In the meantime, you can download an earlier version of Sublime Merge either:
* using apt: `sudo apt install sublime-merge=2082`
* directly at https://www.sublimemerge.com/dev, replacing the version number in the download link with the version you'd like to revert to.

We'll keep you updated.

Kind regards,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Hi @NTMan,

Thank you for your patience while we investigated this issue.

We've release Sublime Merge 2085 which should resolve the issue. When you get a chance, could you please confirm the issue has been resolved on your end?

Kind regards,
\- Dylan from Sublime HQ

**Comment by NTMan** [comment]
> When you get a chance, could you please confirm the issue has been resolved on your end?

Yes, I confirm issue fixed.
Actual behavior: Sublime Merge load CPU at start at 100% but after 50 seconds load normalizes.

**Comment by NTMan** [comment]
The problem was reintroduced in version 2086-1
Please reopen issue.

![image](https://github.com/sublimehq/sublime_merge/assets/200750/29559c79-e2f8-4314-a7f0-44611b2fed58)

Last good version is 2085-1
https://download.sublimetext.com/sublime-merge-2085-1.x86_64.rpm

**Comment by dpjohnst** [comment]
Hi @NTMan,

Could you confirm if you're still seeing this issue in Sublime Merge 2087?

If so, could you also confirm if this repository contains images, and if the hanging causes a particular tab or the entire application to hang.

Thanks,
\- Dylan from Sublime HQ

**Comment by NTMan** [comment]
> Could you confirm if you're still seeing this issue in Sublime Merge 2087?

yes, and 2088 also broken

> If so, could you also confirm if this repository contains images, and if the hanging causes a particular tab or the entire application to hang.

not sure about images
it is Linux kernel repository `git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git`
And it not technically the hang and mostly looks like looping.

**Comment by dpjohnst** [comment]
Hi @NTMan,

Thanks for the additional information - we've now been able to identify the cause of the issue and have released build 2089 to address this. Can you confirm that this build resolves the issue for you?

Kind regards,
\- Dylan from Sublime HQ

**Comment by NTMan** [comment]
> Hi @NTMan,
> 
> Thanks for the additional information - we've now been able to identify the cause of the issue and have released build 2089 to address this. Can you confirm that this build resolves the issue for you?
> 
> Kind regards, - Dylan from Sublime HQ

Thanks, I confirm the issue fixed again in 2089 build
