### ISSUE TITLE
Option to limit a search to just visible branches

### ISSUE THREAD

**Issue by CheyenneWills** [sublimehq/sublime_merge#1744]
**Problem description**

When performing a search it would be helpful to be able to limit the search results to just the branches that are currently visible.  This would be helpful in the case of having to maintain several feature or release branches where there a specific commit may be located (either directly, or because it was cherry-picked into another branch).

**Preferred solution**

An configurable option, or an option in the search prompt that limits to the search to just those branches that are visible.  There are probably various ways this could be presented to the user.  The filtering could be done either while the search itself is being preformed or as a post-search filter.

**Alternatives**

N/A

**Screenshots**

N/A

**Comment by dpjohnst** [comment]
Hi @CheyenneWills,

Sublime Merge 2086 (development build) has been released which adds this feature.
This will also be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ

**Comment by CheyenneWills** [comment]
Just picked it up.  Works like a charm :) thanks
