### ISSUE TITLE
Stage and Unstage hunk for beginning of multi-hunks files does nothing

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#175]
**Version info**

 - OS: Windows 10
 - Build: 1080

**Description**

`Stage hunk` and `Unstage hunk`  does nothing when the hunk is in the beginning of the file and there are other hunks in the same file

**Steps to reproduce**

1. Open repository ...
2. Change the file so there are 2 hunks<br>![image](https://user-images.githubusercontent.com/4518597/47473151-018a0b80-d844-11e8-9ac4-ab281f7dcd81.png)
3. Click on `Stage hunk`<br>![image](https://user-images.githubusercontent.com/4518597/47473170-1b2b5300-d844-11e8-85de-efaec208e4c7.png)
4. The hunk flashed and still unstage

If I use other git client to stage those lines
Situation and reproduce steps are same for `Unstage hunk`
![image](https://user-images.githubusercontent.com/4518597/47473261-8e34c980-d844-11e8-9bdb-825f500e8ea6.png)

Console message:
![image](https://user-images.githubusercontent.com/4518597/47473304-b6bcc380-d844-11e8-8b8e-f0139bdfa1da.png)

**Expected behavior**

That hunk is staged

**Comment by jasonycw** [comment]
Just found out discard hunk also not working in this situation
![image](https://user-images.githubusercontent.com/4518597/47473582-cee11280-d845-11e8-9682-41de609ce950.png)

Console also says failed
![image](https://user-images.githubusercontent.com/4518597/47473608-df918880-d845-11e8-8c62-857275f7e94c.png)

**Comment by jskinner** [comment]
Build 1081 should provide more information about the actual error that's happening here

**Comment by jskinner** [comment]
This should be fixed in 1083 btw

Stage and Discard Hunk weren't working correctly when the underlying file started with a UTF8-BOM
