### ISSUE TITLE
Support to search for more than one `branch:`

### ISSUE THREAD

**Issue by themilkman** [sublimehq/sublime_merge#1753]
**Problem description**

It is currently not possible to search for more branches via the `branch:` keyword. But this would be helpful to show changes for a issue/topics/.. references or specific `file:` changes  spread across multiple branches.
This currently results in an  "Error: branch: may only be used once in a query at position X" message.

(This limitation also applies for `file:` searches, but I don't want to mix too much into this issue/feature request)

**Preferred solution**

Support filters like `(branch:"develop" or branch:"feature/foobar")`

**Comment by dpjohnst** [comment]
Hi @themilkman,

Sublime Merge 2086 (development build) has been released which adds this feature.
This will also be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ

**Comment by themilkman** [comment]
Great, thank you! Based on my quick tests it works exactly as I expected it.
