### ISSUE TITLE
Create missing directory instead of failing when cloning repo

### ISSUE THREAD

**Issue by NutchapolSal** [sublimehq/sublime_merge#1754]
**Version info**

 - OS: Windows 10
 - Build: 2083

**Description**

When cloning a repository into a non-existant folder, it should create any missing folders along the destination path

Currently, it errors out with `CreateProcess failed: The directory name is invalid.`

**Steps to reproduce**

1. Open Clone Repository dialog
2. Put a link in Source URL
3. Include a non-existant folder in the destination path (not including the faded out new folder name)
4. Click Clone

**Expected behavior**

Sublime Merge should create the non-existant folders along the path instead of erroring out. Maybe have a popup show up to let the user confirm the folders being created.

**Comment by dpjohnst** [comment]
Hi @NutchapolSal,

Sublime Merge 2086 (development build) has been released which fixes this.
This fix will also be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ
