### ISSUE TITLE
Ctrl+F4 keybinding to close tab missing

### ISSUE THREAD

**Issue by keith-hall** [sublimehq/sublime_merge#1755]
**Version info**

 - OS: Windows 11
 - Build: 2083

**Description**

It is standard behaviour to be able to close a tab by pressing <kbd>Ctrl+F4</kbd>. This currently does nothing.

**Steps to reproduce**

1. Have more than one repository open
2. Press  <kbd>Ctrl+F4</kbd>

**Expected behavior**

The current tab should close.

Currently the workaround is to use 
 <kbd>Ctrl+W</kbd> but <kbd>Ctrl+F4</kbd> should also work - just like it does in Sublime Text.

**Proposed solution**
Add this binding to the default keymap (at least for Windows and Linux):
```json
{ "keys": ["ctrl+f4"], "command": "close_tab" },
```

**Comment by pasmai** [comment]
You can already use :
<kbd>Ctrl</kbd> + <kbd>W</kbd> to close the tab
<kbd>Ctrl</kbd> + <kbd>Shift</kbd>  + <kbd>T</kbd> to re-open the tab

**Comment by dpjohnst** [comment]
Hi @keith-hall,

Thanks for reporting this - this has been fixed in Sublime Merge 2086 (development build) and will be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ

**Comment by keith-hall** [comment]
Thanks Dylan, let's close this issue then to keep the open issues list relevant 🙂
