### ISSUE TITLE
Commits only reachable via tags cannot be navigated to

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#176]
**Version info**

 - OS: macOS 10.14
 - Build: 1079

**Description**

Tags that are not reachable via a branch shows in the location bar, but cannot be navigated to by clicking in the location bar or using the `Navigate to Commit...` command.

**Steps to reproduce**

1. open a repository
2. modify a file & commit
3. tag newly created commit
4. reset to previous commit (i.e. `git reset HEAD~`)
5. attempt to view created tag in Sublime Merge

Commands to create an example test repo I used to reproduce:

    mkdir __test; cd __test
    git init
    touch README.md
    git add README.md
    git commit -m initial-commit
    echo hi > README.md 
    git commit -am hi
    
    git tag 1.0
    git reset HEAD~
    
    smerge .

**Expected behavior**

Tags & commits only reachable via tags are visible and navigable.

**Comment by thomas6g** [comment]
`gitk --all` shows the commits which are reachable by tags only.

**Comment by bcomnes** [comment]
First thing I ran into.

**Comment by willrowe** [comment]
I can confirm this as well. In the console it says `Unable to find commit xxxxxxxxxxxxxx`.
I was able to use the commit hash to manually checkout the commit from the command line. SM then updated to show the tag and detached head in the interface.

**Comment by dpjohnst** [comment]
Hi all,

Just a quick update - this has been resolved in the latest development build (2034) and will be available in the next stable build.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

This was fixed in the latest stable build (2038)!

Kind regards,
\- Dylan
