### ISSUE TITLE
Consider renaming the default branch from `master` to `main`

### ISSUE THREAD

**Issue by RobertPaauw** [sublimehq/sublime_merge#1762]
**Problem description**

When making a first commit in a fresh repository (local or remote), this creates a branch named `master`.

Apparently Git in general (e.g. Git, Github, Atlasian, Gitlab) is moving toward (re)naming the `master` branch to `main`. For consistency, it would be nice if the initial branch in Sublime Merge would also be named `main`.

Not really a big deal, but I have multiple repositories, and the ones where I let the Git provider create the initial commit are now named differently (namely `main`) than the ones I created with Sublime Merge (which are called `master`).

**Preferred solution**

Name the default branch `main` instead of `master`.

**Screenshots**

![sublime merge initial branch](https://github.com/sublimehq/sublime_merge/assets/58423245/b446bf0d-9583-43f6-8d54-75b865dd9e5b)

**Comment by jfcherng** [comment]
Not sure whether SM respects `git config --global init.defaultBranch main`.

**Comment by RobertPaauw** [comment]
@jfcherng That solved it, thanks 😄 .
