### ISSUE TITLE
There is no easy way to open the console

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/sublime_merge#1767]
**Problem description**

As I was debugging https://github.com/sublimehq/sublime_text/issues/6022 and wanted to take a look at the recorded "startup time", I found out that I was unable to open the console without first creating a key binding for it. I normally have that in my configuration, but not inside Safe Mode.

**Preferred solution**

Have a menu item to toggle the console like in ST.

**Alternatives**

Have a command palette entry to toggle the console.

**Comment by FichteFoll** [comment]
I should mention that the default keybinding as ``ctrl+` `` doesn't help me because my keyboard has and uses a German layout.

**Comment by dpjohnst** [comment]
Hi @FichteFoll,

Thanks for reporting this.

You can show the console via the application menu under `Tools > Show Console`.

Kind regards,
\- Dylan from Sublime HQ
