### ISSUE TITLE
Navigation issues with natural ordering of branch names

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#177]
**Version info**

 - OS: macOS 10.14
 - Build: 1079

**Description**

Sublime Merge seems to be getting lost when two branches are ordered differently between natural ordering & ascii ordering. Here are two behaviors I am noticing:

1. clicking on a local or remote branch doesn't always navigate or navigate to the correct commit
    * tags seem to work correctly, but I didn't do excessive testing
2. ahead / behind counters are not always correct (see screenshot below)
    * this was found in a private repository & I have not been able to reproduce this locally yet

**Steps to reproduce**

Commands to create an example test repos I used to reproduce:

    mkdir __test; cd __test
    git init
    touch README.md
    git add README.md
    git commit -m initial-commit
    
    git checkout -b prefix-8
    echo first >> README.md
    git commit -am first
    git tag release-8
    
    git checkout -b prefix-11
    echo second >> README.md
    git commit -am second
    git tag release-11
    
    mkdir ../__test-clone; cd ../__test-clone
    git clone ../__test .
    git checkout prefix-8
    git checkout prefix-11
    git checkout master
    
    smerge .

Steps to reproduce the behavior of behavior 1 above:
1. open repository created from commands above
2. in location bar, click on `master`, then on `prefix-8`
    - notice correct behavior
3. in location bar, click on `master`, then on `prefix-11`
    - notice navigation to `prefix-8` commit
4. repeat steps 2 & 3 with double clicking to checkout each branch
    - notice similar behavior
5. repeat steps 2 & 3 for remote branches `origin/prefix-8` & `origin/prefix-11`
    - notice similar behavior
6. repeat steps 2 & 3 for `release-8` & `release-11`
    - notice correct behavior

**Expected behavior**

Navigation & checkout via location bar works correctly. Ahead/Behind numbers are accurate for all branches.

Note: all of these cases work correctly in build 1075

**Screenshots**

<img width="550" alt="out-of-sync" src="https://user-images.githubusercontent.com/297298/47475565-9576bb80-d7e1-11e8-8d48-468a0c77b7d5.png">

If the second issue seen in this screenshot should be a separate bug/issue, let me know & I will create it, but it seemed related or at least along the same vein

**Comment by jskinner** [comment]
Thanks for the detailed report - I believe this is fixed in Build 1080, at https://www.sublimemerge.com/dev

**Comment by srbs** [comment]
Ah, yes it is! I'll be sure to start testing with dev builds before submitting. Thanks for an awesome git tool!
