### ISSUE TITLE
Some TypeScript files cause Sublime Merge to hang

### ISSUE THREAD

**Issue by gywn** [sublimehq/sublime_merge#1771]
**Version info**

 - OS: Debian GNU/Linux 11 (bullseye)
 - Build: 2083

**Description**

Some TypeScript files with enough lexical complexity will cause the GUI to wait indefinitely for the diff to appear. The worker thread cannot be terminated normally, but is forcibly terminated. 

**Steps to reproduce**

1. Install build 2083 (build 2079 is OK);
2. Create empty new repository;
3. Add a `index.ts` file with the following content;
4. Open Sublime Merge and try to show `index.ts`'s content in untracked files.

```
_ = () => {
  _(() => {
    if (_ && _._) {
      _ = _._(_._) as _ 
      _()
      _(_ => {
        for (_ of _._) { }
      })
    } 
  }, [_])

  _ = () => {
    if () {
      try { } catch (_: _) { }
    }
  }
}
```

**Expected behavior**

The content of `index.ts` to be shown

**Screenshots**
![Screenshot from 2023-06-24 14-46-40](https://github.com/sublimehq/sublime_merge/assets/1876200/394e4d83-4180-4e06-ab5c-3608e1c64e06)

**Comment by dpjohnst** [comment]
Hi @gywn,

I'm closing this issue as I believe it's been resolved in the latest build. Please feel free to reopen the issue if you're still experiencing it.

Kind regards,
\- Dylan from Sublime HQ
