### ISSUE TITLE
Add Kotlin Language Syntax Highlighting

### ISSUE THREAD

**Issue by DaveM7788** [sublimehq/sublime_merge#1778]
**Problem description**

Sublime Merge does not have syntax highlighting for the Kotlin programming language in the main diff window

**Preferred solution**

Please add syntax highlighting for Kotlin. I understand that it's not feasible to add highlighting for all languages. However, Kotlin has pretty much replaced Java as the default language for Android development. It's also featured as a starter template for the highly popular Spring Boot web framework (https://start.spring.io/). Given these two facts, I suggest that Kotlin deserves a spot among the default languages supported by Sublime merge

**Alternatives**

Apparently, it's possible to add the highlighting through a 3rd party download. See here (https://hugo.md/post/adding-kotlin-syntax-highlighting-to-sublime-merge/). Perhaps, this package could be added to the default install of Sublime Merge?

**Screenshots**

Screen shot of Kotlin file in Sublime Merge default install with no highlighting

![KotlinNoHighlights](https://github.com/sublimehq/sublime_merge/assets/19933553/a9e18071-5849-4c95-a5bc-f55a2684e52f)

**Comment by DaveM7788** [comment]
"Write better Android apps faster with Kotlin. Kotlin is a modern statically typed programming language used by over 60% of professional Android developers that helps boost productivity, developer satisfaction, and code safety."

from https://developer.android.com/kotlin#:~:text=Kotlin%20is%20a%20modern%20statically,developer%20satisfaction%2C%20and%20code%20safety.

**Comment by mobile-ar** [comment]
> **Problem description**
> 
> Sublime Merge does not have syntax highlighting for the Kotlin programming language in the main diff window
> 
> **Preferred solution**
> 
> Please add syntax highlighting for Kotlin. I understand that it's not feasible to add highlighting for all languages. However, Kotlin has pretty much replaced Java as the default language for Android development. It's also featured as a starter template for the highly popular Spring Boot web framework (https://start.spring.io/). Given these two facts, I suggest that Kotlin deserves a spot among the default languages supported by Sublime merge
> 
> **Alternatives**
> 
> Apparently, it's possible to add the highlighting through a 3rd party download. See here (https://hugo.md/post/adding-kotlin-syntax-highlighting-to-sublime-merge/). Perhaps, this package could be added to the default install of Sublime Merge?
> 
> **Screenshots**
> 
> Screen shot of Kotlin file in Sublime Merge default install with no highlighting
> 
> ![KotlinNoHighlights](https://user-images.githubusercontent.com/19933553/252828340-a9e18071-5849-4c95-a5bc-f55a2684e52f.png)

You can install language support from Sublime Text -> cmd + shift + p -> Package Control: Install Package -> Kotlin and install Kotlin support there, the it should work in Sublime Merge (maybe quit and reopen the app)

**Comment by DaveM7788** [comment]
Yes that works. Installing Kotlin in Sublime Text causes the syntax highlighting to also work in merge. Thank you
