### ISSUE TITLE
Commit message lose annotation message

### ISSUE THREAD

**Issue by GentlemanHao** [sublimehq/sublime_merge#1784]
**Version info**

 - OS: [e.g. macOS 10.14]
 - Build: [2083]

**Description**

Commit message lose annotation message

**Steps to reproduce**

1. git merge ... contains conflicts
2. Commit message like
```
Merge branch 'featureA' into featureB

# Conflicts:
#	local.properties
```
3. Commit this message
4. Gitlab commit message show "Merge branch 'featureA' into featureB"，Does not contain information that starts with #

**Expected behavior**

All information should be displayed

**Screenshots**

![image](https://github.com/sublimehq/sublime_merge/assets/23253887/4a9b09a9-e46b-4b34-885a-442f85411c29)

**Comment by dpjohnst** [comment]
Hi @GentlemanHao,

Thanks for reaching out!

By default, lines starting with `#` are treated as comments by Git, and are stripped when committing. 
You can disable this behavior by setting the Git configuration variable `commit.cleanup` to `whitespace`.
i.e. run `git config commit.cleanup whitespace`

Kind regards,
\- Dylan from Sublime HQ
