### ISSUE TITLE
Please support Apple Silicon

### ISSUE THREAD

**Issue by nref** [sublimehq/sublime_merge#1785]
**Problem description**

The app is sluggish and hangs when running under x64 emulation on Apple Silicon (Apple M2 Ventura 13.4.1).

Simply changing open file tab takes 0.5-1.5s.

**Preferred solution**

The app needs to be lightning fast.

**Alternatives**

Don't use Sublime Merge on macOS.

**Screenshots**

I tried to take a screen recording using the macOS screen recorder, but the problem goes away when recording!

**Comment by themilkman** [comment]
I guess there is another problem involved on your Mac, SM (as well as ST) binaries are native Apple Silicon builds, see Changelog:

https://www.sublimemerge.com/dev

```
Build 2051 - 22 April 2021

    Mac releases now include native Apple Silicon binaries
```

**Comment by nref** [comment]
Thanks for the quick feedback. 

That was pretty quick to pass the buck. Nothing else is sluggish on my mac.

I installed the dev version (2085). Still slow.

**Comment by nref** [comment]
Closing since as you showed, at least nominally Apple Silicon is supported.
