### ISSUE TITLE
Hangs shortly after launch

### ISSUE THREAD

**Issue by ayush-j** [sublimehq/sublime_merge#1788]
**Version info**

 - OS: Windows 10
 - Build: 22H2

**Description**

After launching Sublime Merge, it restores my sessions and works for 10-15 seconds then hangs forever and I have to kill the process.

The started happening immediately after update and is always happening now.

**Steps to reproduce**

1. Open repository ...
2. Run command ...
3. Click on ...

**Expected behavior**

A description of what you expected to happen.

**Debug Information**

```
=== App Version Information ===
Build: 2087

=== Git Version Information ===
Using Git: C:\git\bin\git.exe (custom)
git version 2.37.0.windows.1

=== Browse Page Information ===
HEAD: 69a0aa1a59b978ba3e24e61fbb1c25b4d0091f78
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===

=== Our Config Information ===


Our config output is identical to the Git config output

=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 1
```

**Screenshots**

If applicable, add screenshots to help explain your problem. This section may be omitted/removed.

**Comment by ayush-j** [comment]
After removing a particular repo from my session, I no longer get the hang. I tried a clean profile and if I load that repo, Sublime Merge works for a few seconds (I can click on commits etc) but then hangs again indefinitely.

I can't share the repo details (it is a large repo) but this is the state when it is stuck:
![image](https://github.com/sublimehq/sublime_merge/assets/4624541/33fa2494-7b35-40af-be7a-63be624d7d8c)

**Comment by dpjohnst** [comment]
Hi @ayush-j,

Thanks for reporting this issue.

Could you confirm:
* If it's the entire application hanging, or just that specific repository tab
* If this is a public repository
* If Git Scalar is enabled for this repository
* How many modified files (if any) are in the working directory

Kind regards,
\- Dylan from Sublime HQ

**Comment by ayush-j** [comment]
- It's the whole application.
- No, sorry.
- AFAIK, no,
- none, I'm on clean main branch

**Comment by dpjohnst** [comment]
Hi @ayush-j,

Thanks for the additional information.

Could you confirm if reverting to build 2085 resolves the issue for the given repository: https://download.sublimetext.com/sublime_merge_build_2085_x64_setup.exe

Kind regards,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Hi @ayush-j,

We've just released Sublime Merge 2088 - could you confirm if this version resolves this issue for you?

Thanks,
\- Dylan from Sublime HQ

**Comment by ayush-j** [comment]
@dpjohnst No, after updating, I re-opened the repo and it hung again after 15-20 seconds

**Comment by dpjohnst** [comment]
Could you confirm if reverting to build 2085 resolves the issue for the given repository: https://download.sublimetext.com/sublime_merge_build_2085_x64_setup.exe

Kind regards,
\- Dylan from Sublime HQ

**Comment by ayush-j** [comment]
@dpjohnst Yes, that works fine. No issues.

**Comment by dpjohnst** [comment]
Hi @ayush-j,

Thanks for the additional information - we've identified the cause of the issue and have just released build 2089 to address this. Could you confirm that build 2089 resolves this issue on your end?

Kind regards,
\- Dylan from Sublime HQ

**Comment by ayush-j** [comment]
Thanks @dpjohnst! Build 2089 is working fine.
