### ISSUE TITLE
Large repo not working (UI doesn't show updates, checkout/create branch commands do nothing)

### ISSUE THREAD

**Issue by ayush-j** [sublimehq/sublime_merge#1789]
This, similar to #1788 started happening after 2087 update. I have large repos, one of which was hanging the application (bug #1788) and the other one seemed to be working but I noticed that the UI doesn't update if I do git commands from command prompt (e.g. checking out a different branch doesn't reflect in Sublime Merge until I restart SM) and trying to create a branch or checkout a different branch from within Sublime Merge does nothing. I don't even see the command logged in git output popup.

**Version info**

 - OS: Windows 10
 - Build: 22H2

**Debug Information**
The Sublime Merge debug information can be used to narrow down the cause of an issue.
It can be collected with the following steps:
1. Open Sublime Merge
2. Open the repository where the bug occurs
3. Navigate to `Help > Debug Information` via the application menu
4. Before sharing, please redact any information that's sensitive such as file paths, git user information, remote URLs etc.

This section may be omitted/removed.

**Screenshots**

If applicable, add screenshots to help explain your problem. This section may be omitted/removed.

**Comment by ayush-j** [comment]
After switching to "bundled" git, it solved the issue about not being able to create/checkout branch. Although I still get random hangs when working with the repo

**Comment by ayush-j** [comment]
With the bundled git, I do face another issue: whenever I checkout a branch, I get an error:

```
Your branch is up to date with 'origin/main'.
Switched to branch 'main'
/bin/bash: .git/hooks/post-checkout: No such file or directory
```

The post-checkout is a hook that is a symlink to a file in the repo. This works with my system git but not with Sublime Merge's bundled git.

Although this issue is probably unrelated to new version update.

**Comment by dpjohnst** [comment]
Hi @ayush-j,

As mentioned on the other issue posted, we've identified the cause of the issue and have just released build 2089 to address this. Could you confirm that build 2089 resolves this issue on your end?

Kind regards,
\- Dylan from Sublime HQ

**Comment by ayush-j** [comment]
Yes, 2089 resolves the hang and checkout issues. I've tried using my system git with the new build and haven't faced any issues with checkout/branch creation.

The issue with symlinked hook file when using bundled git remains though.

**Comment by ayush-j** [comment]
@dpjohnst should I create separate issue for the git hook issue?
