### ISSUE TITLE
Commit folding preference is not applied on program restart

### ISSUE THREAD

**Issue by 13xforever** [sublimehq/sublime_merge#179]
**Version info**
 - OS: Windows 10 1809
 - Build: 1079

**Description**
In #105 there was a new pref `expand_merge_commits_by_default` that should enforce the desired commit merging behavior, and it works when you toggle it in the UI. However, when you restart Sublime Merge (Exit, then launch again), it will stick to the default behavior, and not to the override set by the pref. You have to change the preference to something else, and then set it back to what you want to re-apply the behavior every time.

**Steps to reproduce**
1. Have a repo open with multiple merged branches
2. Set `expand_merge_commits_by_default` pref to `true`
3. Restart by selecting File → Exit, then start Sublime Merge again
4. Observe the state of the commit graph

**Expected behavior**
If you set the preference to always expand the graph, it should always expand the graph, even after restart.

**Screenshots**
State of the UI before restarting
![image](https://user-images.githubusercontent.com/36445/47496702-129d4180-d871-11e8-983f-12a0c756d462.png)

State of the UI after restart, as you can see the pref is forced to `true`
![image](https://user-images.githubusercontent.com/36445/47496651-f39eaf80-d870-11e8-9459-353162f5d2fa.png)

**Comment by jskinner** [comment]
Thanks for the report - this should now be fixed in Dev Build 1081, at https://www.sublimemerge.com/dev.
