### ISSUE TITLE
mouse couldn't raise hidden Windows taskbar

### ISSUE THREAD

**Issue by awesomeTW** [sublimehq/sublime_merge#1795]
**Version info**

 - OS: Windows 10 22H2 19045.3324
 - Build: 19045.3324

**Description**

while the application is maximized, my hidden taskbar, which was places on my left edge of the desktop, could not be raised by mouse touching on the left edge of the screen.

**Steps to reproduce**

1. place the taskbar on the left
2. hide the taskbar
3. open sublime merge
4. maximized the window
5. move the mouse to the left edge of window

**Expected behavior**

the mouse supposes raise the taskbar to switch between applications

========
I also test the sublime text, and it didn't block the taskbar
![image](https://github.com/sublimehq/sublime_merge/assets/59501079/ce6ab0c4-bef7-4e9c-942a-8ed41bad88fa)
![image](https://github.com/sublimehq/sublime_merge/assets/59501079/9ce86b0f-a00b-4f67-9039-589935c74fe3)

**Comment by might42** [comment]
This is likely a duplicate of [this](https://github.com/sublimehq/sublime_merge/issues/1794).

**Comment by awesomeTW** [comment]
cool we almost post the same issue at the same time.

**Comment by awesomeTW** [comment]
cool we almost post the same issue at the same time.
