### ISSUE TITLE
missing autocoplete for search

### ISSUE THREAD

**Issue by frank-bg** [sublimehq/sublime_merge#1798]
**Version info**

 - OS: Linux Mint 21.2 Cinnamon
 - Build: 2091

**Description**

autocomplete is missing for search (`ctrl` + `f`)

**Steps to reproduce**

1. Open repository ...
2. `ctrl` + `f` or search ...
3. type `cont`

**Expected behavior**

must autocomplete template for `contents:""`

**Comment by themilkman** [comment]
Cannot reproduce with Build 2090 on Kubuntu 23.04.

**Comment by frank-bg** [comment]
I have to do a downgrade to 2083 yesterday, upgrade again, the issue is not there :upside_down_face:
