### ISSUE TITLE
Request: remember layout when switching repos/closing the app

### ISSUE THREAD

**Issue by Herteby** [sublimehq/sublime_merge#180]
**Problem description**

Whenever you switch to another repo or close/reopen the app, the "Location bar" is closed, and the width of the history view is reset to a pretty small size. This is pretty annoying.

**Preferred solution**

Sublime Merge should remember the width of panels and the state of the location bar.

**Alternatives**

Add preferences like "show_location_bar_by_default" and "default_history_view_width".

**Comment by deathaxe** [comment]
The location bar visibility and width are stored in the session with SM1081 now.

But but if there are several Windows open with different states of the location bar visibility/width or state of the location bar tree, only the state of the last open Window is restored.

**Comment by jskinner** [comment]
This is implemented in Dev Build 1081, at https://www.sublimemerge.com/dev

@deathaxe That shouldn't be happening, and in a quick test, exiting with multiple windows will restore their state as expected. You do have to use File/Exit to get this though, if you just close the windows one by one then there will only be one window stored in the session. Probably best to make a new issue if session restoration isn't working as expected.
