### ISSUE TITLE
Please add "Switch Repository" to the Command Palette

### ISSUE THREAD

**Issue by oscar-b** [sublimehq/sublime_merge#1808]
**Problem description**

"Switch Repository" can't be triggered from the Command Palette

**Preferred solution**

Being able to trigger Switch Repository from the Command Palette

**Alternatives**

Remembering the shortcut for Switch Repository, which is outrageously hard.

**Comment by themilkman** [comment]
You may add this to your Command Palette  manually by adding

```json
    {
        "caption": "Switch Repository",
        "command": "quick_switch_repository",
    }
```
in the `Default.sublime-commands` file (if the file does not exist yet, put the json above inside an Array []) in your Sublime Merge User Dir (e.g. on my machine ~/.config/sublime-merge/Packages/User )

**Comment by oscar-b** [comment]
@themilkman Oh wow, very nice, thanks! :D

Not sure if this is the preferred solution so this should be closed?

**Comment by themilkman** [comment]
Glad that it helped you :) 
If I did not oversee it Sublime Text also does not offer this by default in the CP, so I'd assume there are no plans to add it per default (and it's easy to customize). I'd personally suggest closing this, but that's your decision - it may be re-opend by the devs or you in the future anyway.
Cheers!

**Comment by themilkman** [comment]
FTR, SM Build 2092 (dev) added it. Changelog entry:
`* Added Switch Repository to command palette`
