### ISSUE TITLE
Navigating to a commit sometimes fails when commit is currently hidden

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#182]
**Version info**

 - OS: macOS 10.14
 - Build: 1081

**Description**

Navigating to a currently hidden commit fails in at least two cases:
 1. Clicking on a parent commit from a Search
 2. `Navigate to Commit...` in the command palette _from_ the find view
    * note: must choose a commit hash not currently found in the search results
    * it might be worth adding a way to back to the standard view from a commit in the search results

**Steps to reproduce**

Commands to create an example test repos I used to reproduce:

    mkdir __test; cd __test
    git init
    touch README.md
    git add README.md
    git commit -m initial-commit
    
    git checkout -b changes
    echo first >> README.md
    git commit -am first
    echo second >> README.md
    git commit -am second
    
    git checkout master
    git merge changes --no-ff
    
    smerge .

1. create the repository above
2. copy the commit hash for the `changes` branch (`git rev-parse changes`)
3. (1) hide the `changes` branch from view
4. open find view and search for `commit:<paste>`
5. click on parent commit hash
    * notice find view is closed, but the commit is not shown
6. (2) hide the `changes` branch from view
7. open find view
8. run command `Navigate to Commit...` with the commit hash copied from before
    * notice find view is closed, but the commit is not shown
    * rerun the same command to see expected behavior
   

**Expected behavior**

Navigation to the commit succeeds & the branch/history appears in the tree.

**Comment by jskinner** [comment]
Thanks for the report - this is fixed in 1082
