### ISSUE TITLE
Searching for merge commit by commit hash requires min-/max-parents

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#183]
**Version info**

 - OS: macOS 10.14
 - Build: 1081

**Description**

I'm not sure if this should be a bug or not, but searching for a merge commit by hash requires `min-parents:` or `max-parents:`.

**Steps to reproduce**

1. oen repository
2. find a merge commit (`min-parents:2`) & copy it's commit hash
3. search for commit `commit:<paste>`

**Expected behavior**

Commit to show in the search results.

**Comment by jskinner** [comment]
Thanks for the report - automatic exclusion of merge commits from the search results has been tweaked for 1082, and generally makes more sense now
