### ISSUE TITLE
Lost changes and deleted files

### ISSUE THREAD

**Issue by Stuk** [sublimehq/sublime_merge#184]
**Version info**

 - OS: 10.13.6
 - Build: 1079

**Description**

* I had staged a number of new and changed files and started writing a commit message
* I then made a number of changes to one of the new files I had staged, and staged those changes as well
* I added another new file
* I finished writing the commit message and hit Cmd+Enter to commit
* I received an error from Sublime Merge saying something about being unable to commit
* **All the changes were reverted and the changed files were deleted**.
* The first line of `git reflog` is `HEAD@{0}: reset: moving to HEAD`, so looks like something reset hard back to HEAD

(Fortunately I was able to recover most, but not all, of my work through the buffers of my text editor...)

**Steps to reproduce**

Unsure. 

**Expected behavior**

I don't lose any data, even if something goes wrong

**Screenshots**

This is what was left in the status bar afterwards (commit message masked)

<img width="895" alt="screen shot 2018-10-25 at 10 05 59 am" src="https://user-images.githubusercontent.com/48019/47517920-73f7ed00-d83e-11e8-932d-1d93503ad674.png">

**Comment by Stuk** [comment]
I have been using Sublime Merge almost every day recently, and (so far) have not run into this issue again.

**Comment by dpjohnst** [comment]
Hi @Stuk,

I'm going to go ahead and close this issue, as I don't think there's a reliable way we can replicate this issue (and no other users have reported it in the last year). As Sublime Merge doesn't perform any write operations (only shells out to Git), I'd put this down to a bug in Git or similar.

Please feel free to re-open if it ever happens again.

Thanks,
\- Dylan
