### ISSUE TITLE
Update Button

### ISSUE THREAD

**Issue by sheepism** [sublimehq/sublime_merge#1840]
**Problem description**

When a commit happens via web editor Sublime does not update the files

**Preferred solution**
"Get New Version" Button

**Comment by dpjohnst** [comment]
Hi there!

When you refer to the web editor, are you referring to editing the files directly on the remote? (e.g. via GitHub)
If that's the case, you'll need to run `git pull` (via the pull button in Sublime Merge) to pull down the changes from the remote to your local machine.

If you've got a different setup such as a remote file system, let me know and I can investigate further.

Kind regards,
\- Dylan from Sublime HQ

**Comment by sheepism** [comment]
Sorry for ghosting you. Yeah that was really not my proudest moment.
