### ISSUE TITLE
Add option to always show tab bar - even with only one single tab

### ISSUE THREAD

**Issue by themilkman** [sublimehq/sublime_merge#1854]
**Problem description**

Sometimes I accidentally drag&drop one of my SM tabs and thus it opens in a new window. I cannot simply put it back as the new window has no tab bar - and so no tab to drag. If the original window had only two tabs it makes the thing even more "complicated" to resolve without closing & reopening the repo - which is not desired.

**Preferred solution**

Add an option to always show the tab bar.

**Alternatives**

Maybe add an option to disable drag&drop into new window.

**Comment by srbs** [comment]
duplicates: #848

**Comment by themilkman** [comment]
> duplicates: #848
> 

Thanks, did not find it.
