### ISSUE TITLE
custom `create_branch` command doesn't read `$branch` prefix

### ISSUE THREAD

**Issue by ivribalko** [sublimehq/sublime_merge#1855]
**Problem description**

this opens 'create branch' menu without any prefix:

```
    {
        "keys": ["super+alt+b"],
        "command": "show_command_palette",
        "args":
        {
            "command": "create_branch",
            "args": { "prefix": "$branch" },
        }
    },
```

but this works and adds current commit as prefix:

```
    {
        "keys": ["super+alt+b"],
        "command": "show_command_palette",
        "args":
        {
            "command": "create_branch",
            "args": { "prefix": "$commit" },
        }
    },
```

**Preferred solution**

`$branch` should give current branch name to the command

**Alternatives**

more involved custom command? I know there's 'right click -> create branch...' from branch folder but it doesn't do it for me and 'right click -> copy $branch' on a branch is almost good but also not quite

**Screenshots**

<img width="406" alt="image" src="https://github.com/sublimehq/sublime_merge/assets/20713003/9e081469-669e-44eb-982a-33bec1512ef2">

**Comment by dpjohnst** [comment]
Hi @ivribalko,

Thanks for reaching out!

You might be looking for the `head` variable.

This variable will resolve to the current branch name if a branch is checked out.
If a commit is checked out instead, this variable will resolve to the commit hash.

Kind regards,
\- Dylan from Sublime HQ

**Comment by ivribalko** [comment]
yup, that works! thank you!
