### ISSUE TITLE
Improve colorized text readability in the command output viewer

### ISSUE THREAD

**Issue by dreikanter** [sublimehq/sublime_merge#1863]
**Problem description**

Git hooks can print ANSI color codes to stdout. As a result, the output dropdown shows these codes as-is, reducing text readability.

**Preferred solution**

Support colorized text rendering in the command output dropdown.

**Alternatives**

A setting to filter out the color codes.

**Screenshots**

![CleanShot 2024-01-16 at 18 14 51@2x](https://github.com/sublimehq/sublime_merge/assets/126636/66215930-b7af-4971-b9d8-7561727e2a5c)

**Comment by srbs** [comment]
duplicates: #1445, #827

**Comment by dreikanter** [comment]
@srbs True, I didn't notice the existing ticket. I'm closing this one.
