### ISSUE TITLE
Viewing a Stash with Untracked Files

### ISSUE THREAD

**Issue by justinmcbride** [sublimehq/sublime_merge#1866]
**Version info**

 - OS: macOS 14.3
 - Build: 2091

**Description**

When attempting to view a stash that only includes untracked files, nothing appears.

**Steps to reproduce**

Have a clean working directory
Create a new file
Stash it without tracking it (`git stash -u -- your_file.txt`)
View the stash in Sublime Merge

**Expected behavior**

The untracked files should be visible in Sublime Merge as newly-created files.

**Screenshots**

![stash_untracked](https://github.com/sublimehq/sublime_merge/assets/7710325/76ecc4d8-f41d-4ad7-9ea2-a8bd59a43964)

**Comment by dpjohnst** [comment]
Hi @justinmcbride,

Thanks for reaching out and sharing this feedback!

Sublime Merge represents the stash as two components - an object for the modified/staged files, and then a separate object for the untracked files. This is how Git represents these stashes internally.

You can view the untracked stash object by expanding the stash (click the purple square next to the stash name in the commit graph).

I understand that this behaviour is quite unintuitive. This is something we're looking to improve - stay tuned.

Kind regards,
\- Dylan from Sublime HQ

**Comment by justinmcbride** [comment]
Hey Dylan,

Thanks for the reply! I just tried it, and I see what you mean. Clicking on the purple square does expand the stash into its two additional parents.

While this is helpful, I'd probably still contest a bit that the experience isn't correct. It seems as though the default visible stash object should present the changes from both of its constituting components. It makes sense that after expanding the object and clicking into either of those two components (modified/staged and untracked) that you would see those items individually, but shouldn't the result of those two components (the highlighted object in the original screenshot) display the full resulting combination?

Thanks again!
Justin

**Comment by srbs** [comment]
see also: #859

**Comment by justinmcbride** [comment]
Duplicates #859 

Thanks
