### ISSUE TITLE
Remember layout of windows

### ISSUE THREAD

**Issue by chere005** [sublimehq/sublime_merge#187]
It would be convenient if sublime merge would remember how wide the commit history vs diff windows were, and whether the side bar was shown. It would be extra convenient if this could be a global setting, but the settings are also remembered per repo.

**Comment by jskinner** [comment]
This is implemented in Dev Build 1081, at https://www.sublimemerge.com/dev

The commit graph width isn't currently being serialised, but will be in a future build

**Comment by chere005** [comment]
@jskinner thanks for the prompt reply!

**Comment by chere005** [comment]
Looks like this works in the most recent dev build. Yay! If we got tabs I could probably switch over and purchase a license.
