### ISSUE TITLE
Active branches displays greyed

### ISSUE THREAD

**Issue by qubiq1337** [sublimehq/sublime_merge#1876]
**Version info**
 - OS: [macOS 14.2.1]
 - Build: [2091]

**Description**
Sometimes the local branches show grayed out when I actually checked out on them.

**Steps to reproduce**
Checkout to branch

**Expected behavior**
Checked out branch should be black

**Screenshots**
![Something wrong](https://github.com/sublimehq/sublime_merge/assets/25990090/fe244e2b-7513-4f15-9bbe-5aa5352fc19a)
![All good](https://github.com/sublimehq/sublime_merge/assets/25990090/b50b1e48-de80-475a-a782-1436e0f45d2b)

**Comment by srbs** [comment]
FYI, this is due to the upstream branch having been deleted:

> ### BUILD 2083
> * Locations tab: Branches with invalid tracking information are now faded

via https://www.sublimemerge.com/download


---

That being said, it's impossible to tell which branch is checked out & should at least be bolded & maybe darker.

**Comment by themilkman** [comment]
@qubiq1337: Why did you close this? For me, on the latest build, it still behaves as you wrote, which is suboptimal.
