### ISSUE TITLE
Expanded state of items in the location bar not save for recent repo

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#188]
**Version info**

 - OS: Windows 10
 - Build: 1081

**Description**

Expand state in location bar only save for 1 window, not by repository
Open recent repo will not open with the saved expand state

**Steps to reproduce**

1. Open repository, change the expand state in location bar
2. Click on File, open another repo/recent repo <br>![image](https://user-images.githubusercontent.com/4518597/47539609-c18a5d80-d903-11e8-8fca-02fdf82f911f.png)
3. Change that new repo location bar state
4. Close that new repo
5. Click on File and open that repo again
6. The new repo's location bar still collapsed

**Expected behavior**

Expanded state of items in the location bar save

**Screenshots**
![image](https://user-images.githubusercontent.com/4518597/47539682-1a59f600-d904-11e8-83ab-ce901690fd35.png)

**Comment by jskinner** [comment]
Added in 1082
