### ISSUE TITLE
Hide remote merge makes current tree disappear

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#189]
**Version info**

 - OS: Windows 10
 - Build: 1081

**Description**

When collapse the merge commit for local current branch to remote branch, the local current branch will be hidden completely

**Steps to reproduce**

1. Open repository ...
2. Click a remote branch merge commit that merge current local branch<br>![image](https://user-images.githubusercontent.com/4518597/47539906-3ad68000-d905-11e8-8799-b34700a31df7.png)
3. Current local branch completely gone<br>![image](https://user-images.githubusercontent.com/4518597/47539984-8be67400-d905-11e8-86d8-dd8854b70254.png)
4. Even till the very end<br>![image](https://user-images.githubusercontent.com/4518597/47540099-07e0bc00-d906-11e8-874d-612426edd0ae.png)

**Expected behavior**

Just hide that merge line, if that is a local branch, only hide the whole branch tree if it is not the local current one
![image](https://user-images.githubusercontent.com/4518597/47539944-648fa700-d905-11e8-8125-79ae7ee9c8ef.png)

**Comment by jskinner** [comment]
HEAD is now implicitly unfolded in 1082
