### ISSUE TITLE
Force Delete Any Branch

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#191]
**Problem description**

There is no way to force delete a branch.

**Preferred solution**

A pop up that will allow you to force delete
This is from SourceTree
![image](https://user-images.githubusercontent.com/4518597/47560382-a4c54880-d94a-11e8-817f-3f622c3f9fa9.png)

**Alternatives**

An extra option to force delete branch

**Screenshots**

![image](https://user-images.githubusercontent.com/4518597/47692377-59ec4f00-dc30-11e8-8180-2dffeaaa27fc.png)

**Comment by deathaxe** [comment]
This works on my Windows box. Deleting an unmerged branch automatically displays such an confirmation dialog.

**Comment by jasonycw** [comment]
OK, I am not sure why I am facing it again, I think it is because I got unpush change.

1. Commit, and don't push
2. Create a new branch and push
3. Try to delete old branch<br>![image](https://user-images.githubusercontent.com/4518597/47692019-4b516800-dc2f-11e8-85b7-127ca70399a3.png)
4. This pop up<br>![image](https://user-images.githubusercontent.com/4518597/47692022-4db3c200-dc2f-11e8-926b-e42930dadc8d.png)
5. I cannot force delete that branch<br>![image](https://user-images.githubusercontent.com/4518597/47692028-50161c00-dc2f-11e8-9163-f45e2e623b96.png)
6. I need to go back to SourceTree to force delete it<br>![image](https://user-images.githubusercontent.com/4518597/47692223-e21e2480-dc2f-11e8-9bbe-7cbb98b5879e.png)

**Comment by deathaxe** [comment]
Should not be related with unpushed changes. It rather looks like SM doesn't detect `develop` as an unmerged branch and therefore does not call `git -D` or `git -d -f`.

**Comment by jskinner** [comment]
Sublime Merge wasn't using the same criteria as Git to determine if a force delete was required, leading to sometimes being unable to delete a branch.

This is now fixed in 1085
