### ISSUE TITLE
Per repository preferences and session file to store states

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#193]
**Problem description**

As partly discussed in #180 the location bar size and the expand/collapse state of the items there are stored in the session since SM1081. This is ok when working with only one repository at a time.

But as soon as there are several repos in use either by having multiple windows open or by switching repos via _File/Switch Repository_, the session becomes an insufficient place to store those states.

If there are multiple windows open, calling _File/Exit_ closes all windows with their states stored in a session, but this is a very uncommon workflow at least on Windows. At least I always close a Window either by <kbd>alt+f4</kbd> or by closing a window via the title bar's close button, which results in the state of the last window being stored only.

Same issue exists when working with only one SM window but switching repositories often. Everytime you do so, the state of the old repository is lost.

**Preferred solution**

GitExtension solves this issue by adding a custom settings file to the repositorie's _.git_ folder called _GitExtensions.settings_ to store per repository settings and states.

SM could do so as well to have all repository settings/states stored in a repository, so "copying" the repo to usb stick would restore the same state for all instances of SM on several PCs.

**Alternatives**

Store the settings/states for all repositories, which are listed in the "Open Recent" list or the "Switch Repository" dialog in the session file.

**Comment by jskinner** [comment]
1082 now remembers window state per-repository

**Comment by deathaxe** [comment]
Thanks for that change.

The issue includes "expand/collapse state of the items", but SM1082 does not yet include save them per repository. They are still stored per `"windows": []`.

```
	"windows":
	[
		{
			"excluded_refs":
			{
			},
			"expanded_commits":
			{
			},
			"expanded_refs":
			{
				"refs/remotes/": true,
				"refs/remotes/origin": true
			}
		}
	]
```

Hence this issue is actually not (completely) closed.

**Comment by jskinner** [comment]
Should be resolved in 1083 now
