### ISSUE TITLE
Sublime Merge fails to start/open with ntdll.dll fault

### ISSUE THREAD

**Issue by mikebowering** [sublimehq/sublime_merge#1947]
Hi folks,

I'm a licenced user of Sublime Merge through my employer, unfortunately build 2096 has recently failed to start (no window, no process in task manager etc) - event viewer shows:

Faulting application name: sublime_merge.exe, version: 2.0.9.6, time stamp: 0x6626051e
Faulting module name: ntdll.dll, version: 10.0.19041.4522, time stamp: 0x8a1bb6f3
Exception code: 0xc0000005
Fault offset: 0x00000000000649f6
Faulting process ID: 0x1618
Faulting application start time: 0x01dae8c2ef45539d
Faulting application path: C:\Program Files\Sublime Merge\sublime_merge.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 75f346ae-e4a2-4511-af9e-022d0fa4492b
Faulting package full name:
Faulting package-relative application ID: 

Windows 10 Version 10.0.19045 Build 19045

This build had been working fine since April. Tried the usual reboot, uninstall, deletion of Sublime Merge's data folder etc. and reinstalled to no luck. GPU drivers are up to date. I have downgraded to build 2083 which works fine, but can't seemingly upgrade back to 2096. Any help would be welcome 👍

Kind regards,
Mike.

**Comment by dpjohnst** [comment]
Hi @mikebowering,

Thank you for reaching out and for your patience while we've investigated this issue.

Can you confirm if you have OpenGL Hardware Acceleration enabled (using build 2083)?

This can be found via the Sublime Merge Application Menu under `Preferences > Preferences... > Advanced > Hardware Acceleration`

Kind regards,
\- Dylan from Sublime HQ

**Comment by mikebowering** [comment]
Hey @dpjohnst - thanks for the reply! I've just read from various forum posts that suggested to add an antivirus exception for sublime merge which has thankfully worked 🎉
