### ISSUE TITLE
Switch Repository 1082 regression: always opens default view

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#195]
**Version info**

 - OS: macOS 10.14
 - Build: 1082

**Description**

Switch Repository no longer loads the requested repository and instead loads the default/home view. (see screenshot below)

**Steps to reproduce**

1. open a repository
2. switch to another repository

**Expected behavior**

Load requested repository

**Screenshots**

<img width="1207" alt="default view" src="https://user-images.githubusercontent.com/297298/47600590-394e9b80-d989-11e8-95e0-8043b96ee076.png">

**Comment by deathaxe** [comment]
Applies to Windows 10 as well.

**Comment by jskinner** [comment]
Thanks for the heads up; fixed in 1083

**Comment by srbs** [comment]
You're welcome & thanks for a quick fix!
