### ISSUE TITLE
Files appeared as modified in Sublime Merge but not in git status

### ISSUE THREAD

**Issue by schmiidt** [sublimehq/sublime_merge#1962]
**Version info**

 - OS: Windows 10 (19045.4780)
 - Sublime Merge Build 2100

**Description**

I upgraded Sublime Merge this morning from build 2099 to 2100. After the upgrade, several files appeared as modified in Sublime Merge, but when I run git status (version 2.42.0) from the command line, they do not show as modified. Sublime Merge lists these files as deleted, even though they are still present in the file system with all their content intact. The affected files are plain text files, as far as I can tell, and they are all located in the same directories within a large monorepo.

Curiously, Sublime Text does not show these files as modified either, so there seems to be a discrepancy between the modified files shown by Sublime Merge and Sublime Text.

**Steps to reproduce**

I guess you need access to my git repository to reproduce this since I did nothing else other than upgrading Sublime Merge from build 2099 to 2100.

**Expected behavior**

The expected behavior is to show the files as not modified.

**Debug Information**

Here is a list of some of the files that show up as modified in Sublime Merge but not in git or Sublime Text.

- C:\repos\tsw\application\Powertrain\Lubrication\Include\Signals.h
- C:\repos\tsw\application\Powertrain\NoiseControl\Variant0\Source\Control\NoiseControlVariant0.cpp
- C:\repos\tsw\application\Powertrain\NoiseControl\Variant0\Source\Control\NoiseControlVariant0.h

The above files are shown as modified in Sublime Merge but not in git and Sublime Text.

Please do not hesitate to contact me if you need more information. I will be available for a joint debug session as well if you need to guide me through some further debugging of the issue.

**Comment by dpjohnst** [comment]
Hi @schmiidt,

Thanks for reaching out and sorry to hear you've run into this issue.

To investigate this further, would you mind sharing your Sublime Merge Debug Information when you have a spare moment?
It can be collected with the following steps:
1. Open Sublime Merge
2. Open the repository where the bug occurs
3. Navigate to `Help > Debug Information` via the application menu
4. Before sharing, please redact any information that's sensitive such as file paths, git user information, remote URLs etc.

In particular, I'd be interested in seeing the git config portion of the debug information if you'd mind sharing this.

Many thanks,
\- Dylan from Sublime HQ

**Comment by schmiidt** [comment]
Hi, thank you for the quick feedback on this issue. Below is the output from running the Help > Debug Information:

=== App Version Information ===
Build: 2100

=== Git Version Information ===
Using Git: C:\Program Files\Sublime Merge\Git\cmd\git.exe (bundled)
git version 2.39.1.windows.1

=== Browse Page Information ===
HEAD: cc51714b6542e1bcb49c4303b0aa2f1c40ab7ead
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===

=== Our Status Information ===
 D application/Powertrain/Gearbox/Common/Models/PowerTrainGearboxCommon.workspace
 D application/Powertrain/Gearbox/Common/Models/SubSys/PowertrainGearboxCommon/PowertrainGearboxCommon.pmx
 D application/Powertrain/Gearbox/Common/PowerTrainGearboxCommonIntegration.yml
 D application/Powertrain/Generator/Variant3/Include/Commands.h
 D application/Powertrain/Generator/Variant3/Include/Signals.h
 D application/Powertrain/Lubrication/Include/Signals.h
 D application/Powertrain/Lubrication/Variant3/Include/Commands.h
 D application/Powertrain/Lubrication/Variant3/Include/Signals.h
 D application/Powertrain/NoiseControl/Variant0/ContacT/NoiseControlVariant0Test.test
 D application/Powertrain/NoiseControl/Variant0/ContacT/PC_NoiseControlVariant0.sui
 D application/Powertrain/NoiseControl/Variant0/Models/Control/NoiseControlVariant0.pmx
 D application/Powertrain/NoiseControl/Variant0/Models/IntTest/NoiseControlVariant0Int.assignments
 D application/Powertrain/NoiseControl/Variant0/Models/IntTest/NoiseControlVariant0Int.pmx
 D application/Powertrain/NoiseControl/Variant0/Models/NoiseControlVariant0.workspace
 D application/Powertrain/NoiseControl/Variant0/Models/Sim/NoiseControlVariant0Sim.pmx
 D application/Powertrain/NoiseControl/Variant0/Models/Sim/NoiseControlVariant0Stub.pmx
 D application/Powertrain/NoiseControl/Variant0/Models/UnitTest/NoiseControlVariant0UnitTest.pmx
 D application/Powertrain/NoiseControl/Variant0/NoiseControlVariant0.yml
 D application/Powertrain/NoiseControl/Variant0/NoiseControlVariant0Integration.yml
 D application/Powertrain/NoiseControl/Variant0/Source/Control/NoiseControlVariant0.cpp
 D application/Powertrain/NoiseControl/Variant0/Source/Control/NoiseControlVariant0.h
 D application/Powertrain/NoiseControl/Variant0/Source/Control/SystemError.cpp
 D application/Powertrain/NoiseControl/Variant0/Source/Control/SystemError.h
 D application/Powertrain/NoiseControl/Variant0/Source/Control/public.h
 D application/Powertrain/NoiseControl/Variant0/Source/NoiseControlVariant0IT.cpp
 D application/Powertrain/NoiseControl/Variant0/Source/NoiseControlVariant0PicturesIT.cpp
 D application/Powertrain/NoiseControl/Variant0/Source/Sim/NoiseControlVariant0Sim.cpp
 D application/Powertrain/NoiseControl/Variant0/Source/Sim/NoiseControlVariant0Sim.h
 D application/Powertrain/NoiseControl/Variant0/Source/Sim/Stub/NoiseControlVariant0GeneratorTachoSpeedSimStub.cpp
 D application/Powertrain/NoiseControl/Variant0/Source/Sim/Stub/NoiseControlVariant0IOSystemSim.cpp
 D application/Powertrain/NoiseControl/Variant0/Source/Sim/simpublic.h
 D application/Powertrain/NoiseControl/Variant0/Source/Test/NoiseControlVariant0Test.cpp
 D application/Powertrain/NoiseControl/Variant0/VAX/PowertrainNoiseControlVariant0Enums.txt
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/CommandInterface.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/ExternalOutputs.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/ManualCommands.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/NoiseControlVariant0IO.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/SetManualMode.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/config.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/config.xml
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/NoiseControlVariant0SimIO.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/SignalStatusCmds.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/SimulatorCmds.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/config.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/config.xml
 D application/Powertrain/NoiseControl/Variant0/VAX/config.ini
 D application/Powertrain/NoiseControl/Variant0/VAX/vax.bat
 D application/Powertrain/NoiseControl/Variant0/workspace.yml
 D application/Powertrain/PowerTrainIntegrationFiles.yml
 D application/Powertrain/PowerTrainPictures.json
 D application/Powertrain/pirate.yml
 D application/Powertrain/subsystems.yml

=== Git Config Information ===
color.interactive=true
color.ui=auto
core.autocrlf=false
core.bare=false
core.editor="C:\\Program Files\\Sublime Text\\subl.exe" -w
core.filemode=false
core.fscache=true
core.ignorecase=true
core.logallrefupdates=true
core.repositoryformatversion=0
core.symlinks=false
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
help.format=html
http.sslbackend=schannel
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
include.path=C:/Program Files/Git/etc/gitconfig
init.defaultbranch=master
lfs.repositoryformatversion=0
pack.packsizelimit=2g
pull.rebase=false
rebase.autosquash=true

=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /C/Program Files/Sublime Merge/Git/etc/gitconfig

Our config output is identical to the Git config output

=== Git Attributes Information ===
git check_attr --all output
application/Powertrain/Gearbox/Common/Models/PowerTrainGearboxCommon.workspace
application/Powertrain/Gearbox/Common/Models/SubSys/PowertrainGearboxCommon/PowertrainGearboxCommon.pmx
application/Powertrain/Gearbox/Common/PowerTrainGearboxCommonIntegration.yml
application/Powertrain/Generator/Variant3/Include/Commands.h
application/Powertrain/Generator/Variant3/Include/Signals.h
application/Powertrain/Lubrication/Include/Signals.h
application/Powertrain/Lubrication/Variant3/Include/Commands.h
application/Powertrain/Lubrication/Variant3/Include/Signals.h
application/Powertrain/NoiseControl/Variant0/ContacT/NoiseControlVariant0Test.test
application/Powertrain/NoiseControl/Variant0/ContacT/PC_NoiseControlVariant0.sui
application/Powertrain/NoiseControl/Variant0/Models/Control/NoiseControlVariant0.pmx
application/Powertrain/NoiseControl/Variant0/Models/IntTest/NoiseControlVariant0Int.assignments
application/Powertrain/NoiseControl/Variant0/Models/IntTest/NoiseControlVariant0Int.pmx
application/Powertrain/NoiseControl/Variant0/Models/NoiseControlVariant0.workspace
application/Powertrain/NoiseControl/Variant0/Models/Sim/NoiseControlVariant0Sim.pmx
application/Powertrain/NoiseControl/Variant0/Models/Sim/NoiseControlVariant0Stub.pmx
application/Powertrain/NoiseControl/Variant0/Models/UnitTest/NoiseControlVariant0UnitTest.pmx
application/Powertrain/NoiseControl/Variant0/NoiseControlVariant0.yml
application/Powertrain/NoiseControl/Variant0/NoiseControlVariant0Integration.yml
application/Powertrain/NoiseControl/Variant0/Source/Control/NoiseControlVariant0.cpp
application/Powertrain/NoiseControl/Variant0/Source/Control/NoiseControlVariant0.h
application/Powertrain/NoiseControl/Variant0/Source/Control/SystemError.cpp
application/Powertrain/NoiseControl/Variant0/Source/Control/SystemError.h
application/Powertrain/NoiseControl/Variant0/Source/Control/public.h
application/Powertrain/NoiseControl/Variant0/Source/NoiseControlVariant0IT.cpp
application/Powertrain/NoiseControl/Variant0/Source/NoiseControlVariant0PicturesIT.cpp
application/Powertrain/NoiseControl/Variant0/Source/Sim/NoiseControlVariant0Sim.cpp
application/Powertrain/NoiseControl/Variant0/Source/Sim/NoiseControlVariant0Sim.h
application/Powertrain/NoiseControl/Variant0/Source/Sim/Stub/NoiseControlVariant0GeneratorTachoSpeedSimStub.cpp
application/Powertrain/NoiseControl/Variant0/Source/Sim/Stub/NoiseControlVariant0IOSystemSim.cpp
application/Powertrain/NoiseControl/Variant0/Source/Sim/simpublic.h
application/Powertrain/NoiseControl/Variant0/Source/Test/NoiseControlVariant0Test.cpp
application/Powertrain/NoiseControl/Variant0/VAX/PowertrainNoiseControlVariant0Enums.txt
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/CommandInterface.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/ExternalOutputs.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/ManualCommands.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/NoiseControlVariant0IO.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/SetManualMode.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/config.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/config.xml
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/NoiseControlVariant0SimIO.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/SignalStatusCmds.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/SimulatorCmds.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/config.ini
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/config.xml
application/Powertrain/NoiseControl/Variant0/VAX/config.ini
application/Powertrain/NoiseControl/Variant0/VAX/vax.bat
application/Powertrain/NoiseControl/Variant0/workspace.yml
application/Powertrain/PowerTrainIntegrationFiles.yml
application/Powertrain/PowerTrainPictures.json
application/Powertrain/pirate.yml
application/Powertrain/subsystems.yml

=== Our Modified Files Newline Normalisation and EOL Information ===
application/Powertrain/Gearbox/Common/Models/PowerTrainGearboxCommon.workspace: unspecified - native
application/Powertrain/Gearbox/Common/Models/SubSys/PowertrainGearboxCommon/PowertrainGearboxCommon.pmx: unspecified - native
application/Powertrain/Gearbox/Common/PowerTrainGearboxCommonIntegration.yml: unspecified - native
application/Powertrain/Generator/Variant3/Include/Commands.h: unspecified - native
application/Powertrain/Generator/Variant3/Include/Signals.h: unspecified - native
application/Powertrain/Lubrication/Include/Signals.h: unspecified - native
application/Powertrain/Lubrication/Variant3/Include/Commands.h: unspecified - native
application/Powertrain/Lubrication/Variant3/Include/Signals.h: unspecified - native
application/Powertrain/NoiseControl/Variant0/ContacT/NoiseControlVariant0Test.test: unspecified - native
application/Powertrain/NoiseControl/Variant0/ContacT/PC_NoiseControlVariant0.sui: unspecified - native
application/Powertrain/NoiseControl/Variant0/Models/Control/NoiseControlVariant0.pmx: unspecified - native
application/Powertrain/NoiseControl/Variant0/Models/IntTest/NoiseControlVariant0Int.assignments: unspecified - native
application/Powertrain/NoiseControl/Variant0/Models/IntTest/NoiseControlVariant0Int.pmx: unspecified - native
application/Powertrain/NoiseControl/Variant0/Models/NoiseControlVariant0.workspace: unspecified - native
application/Powertrain/NoiseControl/Variant0/Models/Sim/NoiseControlVariant0Sim.pmx: unspecified - native
application/Powertrain/NoiseControl/Variant0/Models/Sim/NoiseControlVariant0Stub.pmx: unspecified - native
application/Powertrain/NoiseControl/Variant0/Models/UnitTest/NoiseControlVariant0UnitTest.pmx: unspecified - native
application/Powertrain/NoiseControl/Variant0/NoiseControlVariant0.yml: unspecified - native
application/Powertrain/NoiseControl/Variant0/NoiseControlVariant0Integration.yml: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Control/NoiseControlVariant0.cpp: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Control/NoiseControlVariant0.h: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Control/SystemError.cpp: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Control/SystemError.h: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Control/public.h: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/NoiseControlVariant0IT.cpp: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/NoiseControlVariant0PicturesIT.cpp: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Sim/NoiseControlVariant0Sim.cpp: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Sim/NoiseControlVariant0Sim.h: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Sim/Stub/NoiseControlVariant0GeneratorTachoSpeedSimStub.cpp: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Sim/Stub/NoiseControlVariant0IOSystemSim.cpp: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Sim/simpublic.h: unspecified - native
application/Powertrain/NoiseControl/Variant0/Source/Test/NoiseControlVariant0Test.cpp: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/PowertrainNoiseControlVariant0Enums.txt: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/CommandInterface.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/ExternalOutputs.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/ManualCommands.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/NoiseControlVariant0IO.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/SetManualMode.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/config.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/config.xml: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/NoiseControlVariant0SimIO.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/SignalStatusCmds.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/SimulatorCmds.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/config.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/config.xml: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/config.ini: unspecified - native
application/Powertrain/NoiseControl/Variant0/VAX/vax.bat: unspecified - native
application/Powertrain/NoiseControl/Variant0/workspace.yml: unspecified - native
application/Powertrain/PowerTrainIntegrationFiles.yml: unspecified - native
application/Powertrain/PowerTrainPictures.json: unspecified - native
application/Powertrain/pirate.yml: unspecified - native
application/Powertrain/subsystems.yml: unspecified - native

=== Our Modified Files Flag Information ===
Ignoring symlinks: 1
application/Powertrain/Gearbox/Common/Models/PowerTrainGearboxCommon.workspace: Working - Normal File : Index - Normal File
application/Powertrain/Gearbox/Common/Models/SubSys/PowertrainGearboxCommon/PowertrainGearboxCommon.pmx: Working - Normal File : Index - Normal File
application/Powertrain/Gearbox/Common/PowerTrainGearboxCommonIntegration.yml: Working - Normal File : Index - Normal File
application/Powertrain/Generator/Variant3/Include/Commands.h: Working - Normal File : Index - Normal File
application/Powertrain/Generator/Variant3/Include/Signals.h: Working - Normal File : Index - Normal File
application/Powertrain/Lubrication/Include/Signals.h: Working - Normal File : Index - Normal File
application/Powertrain/Lubrication/Variant3/Include/Commands.h: Working - Normal File : Index - Normal File
application/Powertrain/Lubrication/Variant3/Include/Signals.h: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/ContacT/NoiseControlVariant0Test.test: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/ContacT/PC_NoiseControlVariant0.sui: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Models/Control/NoiseControlVariant0.pmx: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Models/IntTest/NoiseControlVariant0Int.assignments: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Models/IntTest/NoiseControlVariant0Int.pmx: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Models/NoiseControlVariant0.workspace: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Models/Sim/NoiseControlVariant0Sim.pmx: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Models/Sim/NoiseControlVariant0Stub.pmx: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Models/UnitTest/NoiseControlVariant0UnitTest.pmx: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/NoiseControlVariant0.yml: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/NoiseControlVariant0Integration.yml: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Control/NoiseControlVariant0.cpp: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Control/NoiseControlVariant0.h: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Control/SystemError.cpp: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Control/SystemError.h: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Control/public.h: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/NoiseControlVariant0IT.cpp: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/NoiseControlVariant0PicturesIT.cpp: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Sim/NoiseControlVariant0Sim.cpp: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Sim/NoiseControlVariant0Sim.h: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Sim/Stub/NoiseControlVariant0GeneratorTachoSpeedSimStub.cpp: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Sim/Stub/NoiseControlVariant0IOSystemSim.cpp: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Sim/simpublic.h: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/Source/Test/NoiseControlVariant0Test.cpp: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/PowertrainNoiseControlVariant0Enums.txt: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/CommandInterface.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/ExternalOutputs.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/ManualCommands.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/NoiseControlVariant0IO.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/SetManualMode.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/config.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0/config.xml: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/NoiseControlVariant0SimIO.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/SignalStatusCmds.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/SimulatorCmds.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/config.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/Projects/PowertrainNoiseControlVariant0Sim/config.xml: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/config.ini: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/VAX/vax.bat: Working - Normal File : Index - Normal File
application/Powertrain/NoiseControl/Variant0/workspace.yml: Working - Normal File : Index - Normal File
application/Powertrain/PowerTrainIntegrationFiles.yml: Working - Normal File : Index - Normal File
application/Powertrain/PowerTrainPictures.json: Working - Normal File : Index - Normal File
application/Powertrain/pirate.yml: Working - Normal File : Index - Normal File
application/Powertrain/subsystems.yml: Working - Normal File : Index - Normal File

=== Staged Files Information ===

=== Repository Statistics ===
Commit Count: 82060
Untracked Files Count: 0
Modified Files Count: 52
Staged Files Count: 0
Submodule Count: 0
Loose Objects Count: 628
Packfile Count: 10

**Comment by dpjohnst** [comment]
Hi @schmiidt,

Thanks for the additional information. I've managed to track down the cause of the issue and will be working on addressing this for the next version of Sublime Merge.

In the meantime you can downgrade to version 2096 (stable) to workaround this issue.

Many thanks,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
G'day @schmiidt,

Thank you for your patience while we've addressed this issue.

Just a quick update - we've released Sublime Merge build 2101 today on the development channel which should resolve this issue.

Please reach out if you're still seeing the issue and we can investigate further.

Cheers,
\- Dylan from Sublime HQ

**Comment by schmiidt** [comment]
Hi Dylan,

I can confirm that build 2101 resolves this issue for me. Thank you for addressing it and releasing an updated build so promptly.

Cheers,
Jesper
