### ISSUE TITLE
No Commit option when merging often commits anyway

### ISSUE THREAD

**Issue by decarbonise** [sublimehq/sublime_merge#1967]
**Version info**

 - OS: macOS 12.6 and 13.4
 - Build: 2096

**Description**

Often (but not always) when I or my friend click 'No commit' in the merge options, it still does a commit. I am now super careful to make sure I am definitely clicking that checkbox, and it shows checked, but about a quarter to a third of the time it commits anyway, which is very bothersome. This has been the case for at least 4 months.

**Steps to reproduce**

I can't consistently reproduce this yet, but it does not occur if there are already merge conflicts (because necessarily it can't commit then).

I am happy to provide other debugging info or help to get to the bottom of this, because in the meantime we have had to stop using SM.

**Comment by dpjohnst** [comment]
Hi @decarbonise,

Thank you for reaching out and sorry to hear you've experienced this issue. I will be investigating this further.

The next time this happens, can you copy the git command found in the git output console and share it here. This can be found by clicking the `Show Git Output` button in the repository header next to the branch name. You can see it in the below screenshot as a green tick inside a button:
![Screenshot from 2024-10-02 15-11-15](https://github.com/user-attachments/assets/af0b7767-10a9-4d64-953c-fcbf5bb1abbb)

To copy the command text, you can left-click the command text in the UI shown below:
![image](https://github.com/user-attachments/assets/1c4deacc-59ce-4417-b8e5-9feef201f941)

Many thanks,
\- Dylan from Sublime HQ

**Comment by decarbonise** [comment]
Thank you for the clear instructions. Here are the commands and their outputs:

git merge origin/feature/branch-name-in-kebab-case

```
Auto-merging src/folder_name/modules/fileNameInCamelCase.ts
Merge made by the 'ort' strategy.
 src/folder_name/modules/fileNameInCamelCase.ts | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```
 
git merge --no-commit origin/bugfix/branch-name-in-kebab-case
```
Auto-merging src/file_name_in_snake_case.ts
Auto-merging tests/file_name_in_snake_case.test.ts
Automatic merge went well; stopped before committing as requested
```

In both cases, it committed rather than stopping. The first didn't try to use no-commit (but I definitely checked the checkbox). The second says it stopped before committing but didn't.

**Comment by dpjohnst** [comment]
Hi @decarbonise,

Thanks for confirming this and apologies for the delay in getting back to you.

It seems there may be two issues at play here:
1. A commit being made when the `--no-commit` has been selected
2. Git not respecting the `--no-commit` flag

To give some more context, Sublime Merge doesn't actually perform any Git operations directly (and delegates to Git itself to run operations such as `git merge`. If it was the case that Git reported `Automatic merge went well; stopped before committing as requested` but a commit was still made, this is likely a bug with git.

However, in the first example you provided the `--no-commit` flag wasn't sent to Git despite the `--no-commit` box being checked. I'll be investigating this further to see if I can reproduce the issue.

In the meantime, would you mind sharing your Sublime Merge debug information for the repository you've encountered this issue on.

> **Debug Information**
> The Sublime Merge debug information can be used to narrow down the cause of an issue.
> It can be collected with the following steps:
> 1. Open Sublime Merge
> 2. Open the repository where the bug occurs
> 3. Navigate to `Help > Debug Information` via the application menu
> 4. Before sharing, please redact any information that's sensitive such as file paths, git user information, remote URLs etc.

Kind regards,
\- Dylan from Sublime HQ

**Comment by decarbonise** [comment]
Thanks @dpjohnst. It just happened again and I've managed to capture better logs:

Sequence of actions:
1). Checked out branch /dev/primary
Command in Sublime Git output: git checkout dev/primary

```
Switched to branch 'dev/primary'
Your branch is up to date with 'origin/dev/primary'.
```

2) Merged with --no-commit. A fast forward appears to have happened with no pause for approval
Command in Sublime Git output: git merge --no-commit origin/feature/redacted

```
Updating 25c13b6..9d34b07
Fast-forward
 main.py                                 |  20 +-
 static/js/redacted_file1.js             | 685 ++++++++++++++++++++++++++++++++
 static/js/redacted_file2.js             |  20 +-
 static/js/redacted_file3.js             |   6 +-
 templates/redacted_file4.html           | 192 +++++++++
 5 files changed, 911 insertions(+), 12 deletions(-)
 create mode 100755 static/js/redacted_file3.js
 create mode 100755 templates/redacted_file4.html

Debug Information:
```
=== App Version Information ===
Build: 2102

=== Git Version Information ===
Using Git: git (system)
git version 2.37.1 (Apple Git-137.1)
PATH: /opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Users/user/.cargo/bin:/Users/user/Library/Application Support/JetBrains/Toolbox/scripts (from shell)
environment variables loaded using: /bin/zsh -l

=== Browse Page Information ===
HEAD: 9d34b07a210051230e2d7ece62369ad8f07f1afa
Is in merge: 0
Is in cherry_pick: 0
Is in rebase: 0
Is in revert: 0

=== Git Status Information ===
AA migrations/redacted.sql

=== Our Status Information ===
A A migrations/redacted.sql

=== Git Config Information ===
branch.dev/primary.merge=refs/heads/dev/primary
branch.dev/primary.remote=origin
branch.feature/redacted1.merge=refs/heads/feature/redacted1
branch.feature/redacted1.remote=origin
branch.feature/redacted2.merge=refs/heads/feature/redacted2
branch.feature/redacted2.remote=origin
branch.feature/redacted3.merge=refs/heads/feature/redacted3
branch.feature/redacted3.remote=origin
branch.main.merge=refs/heads/main
branch.main.remote=origin
branch.migration/initial.merge=refs/heads/migration/initial
branch.migration/initial.remote=origin
branch.stable.merge=refs/heads/stable
branch.stable.remote=origin
core.bare=false
core.editor=nano
core.excludesfile=/Users/user/.gitignore_global
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
credential.helper=osxkeychain
diff.jupyternotebook.command=git-nbdiffdriver diff
difftool.nbdime.cmd=git-nbdifftool diff "$LOCAL" "$REMOTE" "$BASE"
difftool.prompt=false
difftool.sourcetree.cmd=opendiff "$LOCAL" "$REMOTE"
difftool.sourcetree.path=
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
init.defaultbranch=main
merge.jupyternotebook.driver=git-nbmergedriver merge %O %A %B %L %P
merge.jupyternotebook.name=jupyter notebook merge driver
mergetool.nbdime.cmd=git-nbmergetool merge "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
mergetool.prompt=false
mergetool.sourcetree.cmd=/Applications/Sourcetree.app/Contents/Resources/opendiff-w.sh "$LOCAL" "$REMOTE" -ancestor "$BASE" -merge "$MERGED"
mergetool.sourcetree.trustexitcode=true
push.autosetupremote=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://redacted.git
safe.directory=/Users/user/Desktop/Redacted
user.email=redacted@domain.tld
user.name=Redacted Redacted

=== Our Config Information ===
Git Config Path Information
Using config path: /etc/gitconfig
Using config path: /Users/user/.config/git/config
Using config path: /Users/user/.gitconfig
Using config path: /Users/user/redacted.git/config

Our config output is different to the Git config output
branch.dev/primary.merge=refs/heads/dev/primary
branch.dev/primary.remote=origin
branch.feature/redacted1.merge=refs/heads/feature/redacted1
branch.feature/redacted1.remote=origin
branch.feature/redacted2.merge=refs/heads/feature/redacted2
branch.feature/redacted2.remote=origin
branch.feature/redacted3.merge=refs/heads/feature/redacted3
branch.feature/redacted3.remote=origin
branch.main.merge=refs/heads/main
branch.main.remote=origin
branch.migration/initial.merge=refs/heads/migration/initial
branch.migration/initial.remote=origin
branch.stable.merge=refs/heads/stable
branch.stable.remote=origin
core.bare=false
core.editor=nano
core.excludesfile=/Users/user/.gitignore_global
core.filemode=true
core.ignorecase=true
core.logallrefupdates=true
core.precomposeunicode=true
core.repositoryformatversion=0
diff.jupyternotebook.command=git-nbdiffdriver diff
difftool.nbdime.cmd=git-nbdifftool diff "$LOCAL" "$REMOTE" "$BASE"
difftool.prompt=false
difftool.sourcetree.cmd=opendiff "$LOCAL" "$REMOTE"
difftool.sourcetree.path=
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.smudge=git-lfs smudge -- %f
merge.jupyternotebook.driver=git-nbmergedriver merge %O %A %B %L %P
merge.jupyternotebook.name=jupyter notebook merge driver
mergetool.nbdime.cmd=git-nbmergetool merge "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
mergetool.prompt=false
mergetool.sourcetree.cmd=/Applications/Sourcetree.app/Contents/Resources/opendiff-w.sh "$LOCAL" "$REMOTE" -ancestor "$BASE" -merge "$MERGED"
mergetool.sourcetree.trustexitcode=true
push.autosetupremote=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://redacted.git
safe.directory=/Users/user/Desktop/Redacted
user.email=redacted@domain.tld
user.name=Redacted Redacted
=== Git Attributes Information ===
git check_attr --all output

=== Our Modified Files Newline Normalisation and EOL Information ===

=== Our Modified Files Flag Information ===
Ignoring symlinks: 0

=== Staged Files Information ===

=== Repository Statistics ===
Commit Count: 246
Untracked Files Count: 0
Modified Files Count: 0
Staged Files Count: 0
Submodule Count: 0
Loose Objects Count: 2719
Packfile Count: 2
```

**Comment by decarbonise** [comment]
I've managed to track this down and the fault was mine. I was selecting --no-commit, but wasn't also selecting --no-ff. Thank you for your help
