### ISSUE TITLE
Focus lost on filtering Files

### ISSUE THREAD

**Issue by rchl** [sublimehq/sublime_merge#1968]
**Version info**

 - OS: macOS
 - Build: 2101

**Description**

Focus is lost from the input field for filtering files if selected file doesn't match filtering

**Steps to reproduce**

1. Click on any commit
2. In the sidebar focus the `Files` tab
3. Click on any of the files
4. Enter some query that will make the selected file get filtered out

**Expected behavior**

Focus is not lost from the input on typing

**Screenshots**

https://github.com/user-attachments/assets/294c068c-c96c-48c4-99e8-161b662d666d

**Comment by dpjohnst** [comment]
G'day @rchl,

Thanks for reporting this issue! I've been able to reproduce this issue on my end and will be working on a fix.

Cheers,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Hi @rchl,

Just a quick update that I've resolved this issue internally, and the fix will be available in the next release of Sublime Merge.
I'll keep you updated on when this is released.

Kind regards,
\- Dylan from Sublime HQ

**Comment by rchl** [comment]
This is not fixed in 2102.

**Comment by dpjohnst** [comment]
Hi @rchl,

Apologies for the error in my previous message.

This will be fixed in the next _development_ build of Sublime Merge.

Cheers,
\- Dylan from Sublime HQ
