### ISSUE TITLE
Improper high-line the unrelative line in diff UI.

### ISSUE THREAD

**Issue by Eric-Guo** [sublimehq/sublime_merge#1974]
**Version info**

 - OS: macOS 14.7.1
 - Build: 2102 (stable version)

**Description**

Improper high-line the unrelative line in diff UI. (no matter what diff algorithms choose, same, so I guess it's a UI issue)

<img width="601" alt="image" src="https://github.com/user-attachments/assets/36d51f13-19e2-426f-a9f5-f9752d920925">

**Steps to reproduce**

Any repo commit having similar issue, if you try to see the screen shot one, [click link](https://github.com/thape-cn/web/commit/e6a38275ccb8ac1cb54e402e26f39ae3002a7808#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deL1237)

**Expected behavior**

Not change line should not highlight.

**Comment by dpjohnst** [comment]
Hi @Eric-Guo,

Thanks for reaching out - this looks to be a syntax definition issue.
I'll follow this up and get back to you when I have an update.

Cheers,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Hi @Eric-Guo,

Just following up on this - by default we don't have a syntax definition for these lock files.
It's likely that either the incorrect syntax is being used, or a third-party syntax is being used (but has a bug).

You may have set a default syntax definition for an extension (`.lock` in this case) in Sublime Text at some point.
When a default syntax definition is set in Sublime Text, it's also set in Sublime Merge.

You can check this by:
1. Opening the file in Sublime Text
2. Navigating to `View > Syntax > Open all with current extension as...` in the application menu and checking which syntax is selected (ticked)

Kind regards,
\- Dylan from Sublime HQ

**Comment by Eric-Guo** [comment]
Yeah, reproduce it in Sublime Text as well.

<img width="838" alt="image" src="https://github.com/user-attachments/assets/d29bf0e1-4ab6-4ec2-992a-6e865bc2136a">

It's YAML (Yarn)

**Comment by Eric-Guo** [comment]
I can reproduce in Sublime Text, but when I disable 'YAML' (build-in), it resolved in Sublime Text, because yarn.lock will got plain text, but in Sublime Merge, same (no effect), I guess there is no way to disable yarn.lock display as YAML or YAML need to fix.

**Comment by Eric-Guo** [comment]
Upgrade Sublime Text from stable version to build 4183 no help.

**Comment by dpjohnst** [comment]
Hi @Eric-Guo,

Sorry to hear it’s not working as expected. I’ll be investigating this further.

Just wanted to also double check if you restarted Sublime Merge after changing the syntax in Sublime Text?

Kind regards,
\- Dylan from Sublime HQ

**Comment by Eric-Guo** [comment]
Yes restarted Merge, I guess the persistence of disable YAML syntax is not saved.

**Comment by jwortmann** [comment]
The syntax name `YAML (Yarn)` indicates that the syntax is either provided by an icon package like "A File Icon" or a theme in Sublime Text. This just uses the regular YAML syntax under the hood for files with name `yarn.lock`, which is perhaps a wrong assumption if these files are not fully YAML compliant.

I think Sublime Merge uses its own YAML syntax and that is why disabling it in ST has no effect.

I'd recommend to not disable the YAML package in Sublime Text. Instead use `View > Syntax > Open all with current extension as...` with such a file open and select "Plain Text". I think that should disable syntax highlighting for all `.lock` files.

**Comment by Eric-Guo** [comment]
@jwortmann are right, after disable "A File Icon", it resolved.
