### ISSUE TITLE
Add remote should trim URL

### ISSUE THREAD

**Issue by mbartlett21** [sublimehq/sublime_merge#1986]
**Version info**

 - OS: Windows 11
 - Build: 2102

**Description**

Adding a https remote with a space before it stops Git with an invalid protocol error.

**Steps to reproduce**

1. Have a repo open
2. Use add remote, giving a https URL with a space before it that you didn't realise.
   For example `" https://github.com/Keychron/ChibiOS.git"`.
3. Run `fetch --all`
4. ```
   Fetching origin
   Fetching keychron
   fatal: protocol ' https' is not supported
   error: could not fetch keychron
   ```

**Expected behavior**

The add remote command would have trimmed the extra space from the start when adding the remote.

**Comment by dpjohnst** [comment]
G'day @mbartlett21,

Thanks for sharing this feedback - I've just fixed this internally and the fix will be available in the next build.

Cheers,
\- Dylan from Sublime HQ
