### ISSUE TITLE
Docs: download instructions need adjustment for dnf5

### ISSUE THREAD

**Issue by ammkrn** [sublimehq/sublime_merge#1988]
**Version info**
Stable channel, build 2102

 - OS: Fedora 41
 - Build: Stable channel, build 2102

**Description**

The download instructions for fedora's dnf version 5 do not work as written. It seems there were quite a few syntax changes made between dnf4 and dnf5. The syntax (for stable) should be:

```
sudo dnf config-manager addrepo --from-repofile=https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
```

With the URL switched for dev.

**Comment by themilkman** [comment]
Related on the ST tracker: https://github.com/sublimehq/sublime_text/issues/6529

**Comment by dpjohnst** [comment]
G'day @ammkrn,

Thanks for sharing this feedback - I've just fixed this internally and we'll push an update to the website soon.

Cheers,
\- Dylan from Sublime HQ
