### ISSUE TITLE
[BUG] Blame does not work on Linux.

### ISSUE THREAD

**Issue by wilfredwee** [sublimehq/sublime_merge#199]
**Version info**

 - OS: Ubuntu 18.04
 - Build: 1079

**Description**
Blame functionality does not work on Linux

**Steps to reproduce**

1. Open any repository.
1. Ctrl + P to bring up command palette.
1. type 'Blame'
1. Choose any file.
1. Notice that nothing happens. Blame is not shown.

**Expected behavior**

Blame for the selected file is shown.

**Additional Notes**
This looks similar to the bug that was fixed in OSX in Build 1079, but it looks like the fix was not done for Linux.

**Comment by dylanjohnston** [comment]
Hi @wilfredwee,

Thanks for the report. This has been fixed as of build 1080.

Kind regards,
- Dylan

**Comment by jskinner** [comment]
FWIW, the current stable build is 1084, which as a fix for this issue
