### ISSUE TITLE
Git Flow does not start a feature properly

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#200]
**Version info**

 - OS: Windows 10
 - Build: 1083

**Description**

Git flow will fail directly and not asking user for entering feature's name

**Steps to reproduce**

1. Open repository ...
2. Open git flow feature for the repository
3. Start feature branch <br> ![image](https://user-images.githubusercontent.com/4518597/47700745-8022e680-dc52-11e8-86b7-a0d188b23f80.png)
3. It just failed<br>![image](https://user-images.githubusercontent.com/4518597/47700764-8f099900-dc52-11e8-9b5a-4e9673b7f95d.png)

**Expected behavior**

It should ask for the feature's name and pop up the input console with the command in it

**Screenshots**
![image](https://user-images.githubusercontent.com/4518597/47700806-b3657580-dc52-11e8-8881-f49495511b3c.png)

**Comment by jskinner** [comment]
Thanks for the report, fixed in 1085
