### ISSUE TITLE
Make commit screen less confusing: add color and/or fixed layout 

### ISSUE THREAD

**Issue by marcellarius** [sublimehq/sublime_merge#203]
**Problem description**

I've been using SublimeMerge full-time for over a month, and yet I still find myself confused about which files have been staged. I don't think the staged files are visually distinct enough, and the disappearing empty sections when empty adds to the confusion -- the UI seems to 'jump' and I have to reparse it to understand what's going on.

I previously used the Git command line interface, and found its red/green colouring of staged/unstaged files was really helpful to reinforce the status of files.

**Preferred solution**

The staged files on the commit screen would have a distinctive green colour. The unstaged files would have a distinctive red colour.

Further, the commit screen layout is 'fixed' using a split pane to allow them to resized. (i.e. unstaged on top, staged on bottom -- although ideally I'd prefer those the other way around, consistent with Sourcetree and the Git CLI).

This is the way SourceTree's commit layout works, and makes it much clearer that files are "moving" into the staged section, rather than just scrambling around.

**Alternatives**

One of the above suggestions... maybe bolder headings for "Working Directory" and "Staged Files"

**Comment by jasonycw** [comment]
Especially with refactoring, there are so many file changes it is an headache to know where am I looking at.

**Comment by jskinner** [comment]
Dev Build 1086 (at https://www.sublimemerge.com/dev) now has an alternate commit interface, via the Contents tab, that makes things clearer

**Comment by braver** [comment]
@jskinner This doesn't really fix that the default commit view is confusing. More thoughts over at #47. Also:

- with the sidebar collapsed (which is the default state) it's not clear that there is a contents tab. 
- and if you do find the contents tab it's not clear that that's going to improve the commit UI.
- if you open the contents view by hitting space bar, clicking the "locations" tab both doesn't make sense and doesn't work (it just closes the sidebar that's overplayed on top of the graph).

That's all to say that the confusing-ness is not exactly resolved here.
