### ISSUE TITLE
Ability to split hunks

### ISSUE THREAD

**Issue by themilkman** [sublimehq/sublime_merge#206]
**Problem description**

git allows to split some hunks can been staged/committed. Adding this option to SM would be very useful.

**Preferred solution**

Add another button to next to the current in diff view.

**Alternatives**

An option in the context menu (right click)

**Comment by jskinner** [comment]
When committing, you can select one or more lines, and the 'Stage Hunk' button will transform into 'Stage Lines', allowing you to stage only part of a hunk

**Comment by themilkman** [comment]
@jskinner This is... awesome! Didn't recognize it since the first day. Thanks for pointing that out!

@dylanjohnston Thanks for your answer, too. Not quite what I was looking for, but I already played with this feature earlier this day :)

Btw: I love Sublimemerge so thanks for this!

**Comment by jonnytest1** [comment]
> When committing, you can select one or more lines, and the 'Stage Hunk' button will transform into 'Stage Lines', allowing you to stage only part of a hunk

maybe we should add a right click menu option as well - (thats where i searched for it)
