### ISSUE TITLE
Some commit changes hidden until mouse hover

### ISSUE THREAD

**Issue by tommcc** [sublimehq/sublime_merge#208]
**Version info**

 - OS: macOS 10.13.6 (2015-era MacBook Pro)
 - Build: 1085 (Dev)

**Description**

When I click on any commit or the current working state, only the first or first few changes appear in the right column. In order to see subsequent changes, I need to hover my mouse over the first hunk's body.

**Steps to reproduce**

1. Click any commit that includes more than one hunk of changes (including single- and multi-file commits).
2. Only a subset of changes will appear in the right column.
3. Move mouse over to the right column, anywhere on or below the first hunk.
4. The remaining hunks now appear.

**Expected behavior**

All changes/hunks appear right when clicking a commit or working state.

**Screenshots**

![smerge hide](https://user-images.githubusercontent.com/881466/47812716-80d57e80-dd1f-11e8-8f8a-bb02c1090e9c.gif)

**Comment by jasonycw** [comment]
Yes, same thing happen to me after update to 1086,
not just some hunk but even some file is missing. Need to scroll one time on the commit detail section and the render will back to normal.

- OS: Windows 10
- Build: 1086 (Dev)

**Comment by tommcc** [comment]
Update: 1088 seems to fix this bug for me.
