### ISSUE TITLE
Cmdline git tag breaks contents: search

### ISSUE THREAD

**Issue by qgates** [sublimehq/sublime_merge#211]
**Version info**

 - OS: Windows 7
 - Build: 1085

**Description**

While showing the results of a contents: search, performing a git tag outside Merge blanks the main Merge screen (history and contents panels)

**Steps to reproduce**

1. Open local repository
2. Search for `contents:xyz` (search is performed correctly)
3. Outside Merge, from cmdline issue `git tag -a v1234 <hash>`
4. Merge's history and contents panels disappear and `...` is shown at the top of the history panel

nb. bug discovered when retrospectively tagging with a commit hash, may occur when tagging at HEAD and also with commits.

**Expected behavior**

(preferable) The search should update to reflect changes to the repo
(sufficient) Search results remain as before the external tag command, and will only update with Ctrl+R

**Comment by jskinner** [comment]
Thanks for the report, this was fixed in dev build 1087
