### ISSUE TITLE
Shortcuts and improvements to search

### ISSUE THREAD

**Issue by qgates** [sublimehq/sublime_merge#212]
**Problem description**

Typing `contents:` etc. all the time in search is cumbersome, there's no history etc.

**Preferred solution**

1. Autocomplete everywhere with tab. So typing c `tab` expands to `contents:` and f `tab` to `file:` etc.
2. Up and down arrows traverse through search history.
3. When typing paths to autocomplete them with `tab` similar to bash.
4. Allow regex on `contents:` search

**Alternatives**

Just 1 and 2 above, the biggest priority for me ;-)

**Comment by themilkman** [comment]
A ST like "history for the search history" (up/down arrows) would really be a very useful addition.
The other points of course would nice, too.

**Comment by dpjohnst** [comment]
Hi all,

Thanks for sharing this feedback - we've added autocomplete to the search bar in Sublime Merge Build 2064 (dev).

Cheers,
\- Dylan from Sublime HQ
