### ISSUE TITLE
Context of diffs needed

### ISSUE THREAD

**Issue by zsynacl** [sublimehq/sublime_merge#217]
**Problem**

**Can not get context of diffs when checking all changes**

Sometime changes was not handmade, they were generated by some tools. At these moments, some check were requested to make sure everything was right.

But when using Sublime Merge, I couldn't know the context of each change, it was necessary to locate some problems.

**Preferred solution**

Give some way to show the context of particular diff, like the merge review page of gitlab.

for example:
show a button like '...' on the top and bottom of each diff hunks.

**Alternatives**

**Screenshots**

Like the screenshot below. it's hard to know which function we are looking at
![default](https://user-images.githubusercontent.com/4392800/47982173-bb695d80-e109-11e8-90a6-b2fe26cae21a.png)

**Comment by jskinner** [comment]
You can show more context by grabbing the splitter bar at the top and bottom of each hunk. You can either drag the splitter bar, or double click it for 10 additional lines of context
