### ISSUE TITLE
Window with Sublime Merge launches with 1px width and 1px height

### ISSUE THREAD

**Issue by tomasz-nolberczak** [sublimehq/sublime_merge#218]
**Version info**

 - OS: Ubuntu 16.04
 - Build: 1084

**Description**

Window with Sublime Merge launches with 1px width and 1px height. It is very hard to resize it. It is located in left top corner of main screen. 

**Steps to reproduce**

1. Open Sublime Merge.

**Expected behavior**

Window with Sublime Merge opens on full screen.

**Comment by jskinner** [comment]
Thanks for the report, this should be fixed in the next build

**Comment by jskinner** [comment]
This should now be fixed in dev build 1086 at https://www.sublimemerge.com/dev
