### ISSUE TITLE
Gitflow --showcommands

### ISSUE THREAD

**Issue by jeffreydelooff** [sublimehq/sublime_merge#219]
**Version info**

 - OS: macOS 10.14
 - Build: Stable 1084

**Description**

--showcommands is appended to git flow commands which is an unsupported option.

**Steps to reproduce**

1. Open repository.
2. Checkout develop
3. Start a new feature branch through gitflow

**Expected behavior**

A new branch with the given feature name is created and checked out locally.

**Screenshots**

<img width="514" alt="screenshot 2018-11-05 at 10 42 46" src="https://user-images.githubusercontent.com/263346/47990487-ed69c800-e0e7-11e8-9197-bc517269d880.png">

**Comment by jskinner** [comment]
We're currently assuming the AVH variant of Git Flow, which supports `--showcommands` as well as some of the other Git Flow options we expose.

**Comment by jeffreydelooff** [comment]
Alright, thank you for the reply. I will install the AVH variant and try again. Is it documented somewhere that you rely on this variant?

**Comment by iodic** [comment]
I had the same issue and I can confirm that `brew install git-flow-avh` fixed the issue. :)

**Comment by nikoskip** [comment]
@iodic I tried installing `git-flow-avh` but I'm getting this error:

![image](https://user-images.githubusercontent.com/1230033/48954058-b50b1c00-ef26-11e8-8324-b4f8de7c4da5.png)

@jskinner any idea? I'm running build 1084

**Comment by jeffreydelooff** [comment]
Looks like you haven't specified the version or branch name in the input field.

**Comment by nikoskip** [comment]
@jeffreydelooff I was using the "new hotfix" option from the `Tools` menu, but it didn't ask me the branch name:

![image](https://user-images.githubusercontent.com/1230033/48954627-1f24c080-ef29-11e8-8e79-5966a65bf8e9.png)

But from the command pallet works fine!

![image](https://user-images.githubusercontent.com/1230033/48955930-04554a80-ef2f-11e8-8369-e9944652fd25.png)

Thank you!
