### ISSUE TITLE
Discard all as hazard button?

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#22]
**Problem description**

The hazard buttons are a very good alternative for modal dialogs asking for dangerous actions to be really performed. While "Abort merge", "Stage All" and others follow this functionality the "Discard All" button shows a modal dialog asking for the files to be deleted or not. 

Is there any certain reason to not make it a normal hazard button?

**Preferred solution**

The "Discard All" button in the commit dialog should work like the other hazard buttons. Clicking once turns it into red while clicking a second time performs the action.

**Comment by TheSecEng** [comment]
As an update from devs

<img width="839" alt="image" src="https://user-images.githubusercontent.com/32599364/82164726-00825a00-9880-11ea-9d96-3882aaef7cc1.png">

**Comment by TheSecEng** [comment]
I'd like to add, that I too would like the Discard All to work as Stage All. But purely preference

**Comment by stinos** [comment]
@deathaxe why did you close this? I think it is still a valid concern.
