### ISSUE TITLE
Shows timestamps in wrong time zone -- daylight saving time related?

### ISSUE THREAD

**Issue by marcellarius** [sublimehq/sublime_merge#223]
**Version info**

 - OS: Windows 10
 - Build: 1084

**Description**

I noticed that the timestamps shown in SublimeMerge are an hour behind localtime -- perhaps they are being converted to NZST rather than NZDT (the current timezone).

If I look at `git log` the commits are being made with the correct local timestamp in NZDT, but I assume SublimeMerge is showing them in NZST.

**Steps to reproduce**

1. Be on daylight savings time?
2. Create a new repo
3. Commit something
4. Compare timestamp between Sublime Merge and local time

**Expected behavior**

SublimeMerge should show all timestamps in the local timezone.

**Screenshots**

![image](https://user-images.githubusercontent.com/1151819/48088663-6f342f80-e267-11e8-9a6d-00d3bc0216cf.png)

**Comment by srbs** [comment]
Out of curiosity, did you start Sublime Merge before the time change? If so, does restarting SM fix the issue? I'm wondering if SM just thought it was still a different timezone or something like that.

**Comment by marcellarius** [comment]
I wondered that too and tried restarting SublimeMerge before submitting the bug.

NZ has been on NZDT for over a month and my computer has been restarted since then. I'm surprised I didn't notice the issue sooner!

**Comment by jskinner** [comment]
Thanks for the report, we weren't using the `GetTimeZoneInformation` API correctly on Windows.

This should be fixed in the next build.

**Comment by jskinner** [comment]
This in now fixed in 1086
