### ISSUE TITLE
Show number of lines changed in the commit section

### ISSUE THREAD

**Issue by ericclone** [sublimehq/sublime_merge#224]
Is it possible to show something equivalent to the output of "git log --oneline --stat"
```
Makefile          |  3 ++-
main.h            | 11 ++++++++---
main.cpp          | 54 
3 files changed, 60 insertions(+), 8 deletions(-)
```
It is quite handy to help decide when it is a good time to create a new patch so that it is not too large.

**Comment by srbs** [comment]
I like this idea, it could be a hidden (by default) block above or next to the `Collapse all` button that shows a similar summary in a given commit or diff.

Better yet, add the added & removed line counts on each file's title row and the full summary.. uhh somewhere

**Comment by deenison** [comment]
Any updates on this?

**Comment by yohanmishkin** [comment]
I'd love this feature and find myself looking for commit stats in the application pretty often.

**Comment by dpjohnst** [comment]
Hi all,

Just providing a quick update- this has been added in Sublime Merge Build 2003 (Development Build)!

Let us know how you find it :)

Thanks,
\- Dylan
