### ISSUE TITLE
View Tree doesn't work from commit search result

### ISSUE THREAD

**Issue by braver** [sublimehq/sublime_merge#225]
**Version info**

 - OS: macOS 10.14
 - Build: 1085

**Description**

Instead of jumping to the tree view for a commit, it jumps back out to the default view.

**Steps to reproduce**

1. Open repository ...
2. Search for a commit 
3. Click on the disclosure button
4. Click on "View Tree"
<img width="1031" alt="screen shot 2018-11-07 at 11 59 59" src="https://user-images.githubusercontent.com/2543659/48127703-b2e96200-e284-11e8-860a-34ba26686a6c.png">

**Expected behavior**

The tree view for that commit should open.

**Screenshots**

![tree](https://user-images.githubusercontent.com/2543659/48127800-e7f5b480-e284-11e8-997d-3a0f99a499dd.gif)

**Comment by deathaxe** [comment]
Works in 1087.

**Comment by braver** [comment]
🎉
