### ISSUE TITLE
Blame on specific line not working

### ISSUE THREAD

**Issue by sergei-dyshel** [sublimehq/sublime_merge#237]
**Version info**

 - OS: Linux
 - Build: 1084
**Description**

When running Sublime Merge in blame mode with `smerge blame <file> <line>`, specifying line number does not reveal this line.

**Steps to reproduce**

Specify line number as argument.

**Expected behavior**

The specified line is revealed in blame view after startup.

**Screenshots**

If applicable, add screenshots to help explain your problem. This section may be omitted/removed.

**Comment by jskinner** [comment]
Thanks for the report, this has been fixed in dev build 1088, at https://www.sublimemerge.com/dev
