### ISSUE TITLE
Impossible to clone into folder with different name

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/sublime_merge#238]
**Problem description**

When cloning a repo, SM will automatically add the repo's name to the specified folder. This can be useful, but is very annoying when you want to clone into a differently-named folder as SM will *always* append the repo's name.

**Preferred solution**

Only add the repo's name if the path ends with `/` (or `\` on Windows). The visibility of the placeholder text should make this obvious enough to not need any explanation.

Related: #197

**Comment by jskinner** [comment]
Thanks for the suggestion, the folder name can now be customized in 1088
