### ISSUE TITLE
Infinity login retry

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#239]
**Version info**

 - OS: Windows 10 
 - Build: 1087

**Description**

Sublime Merge seems will retry GitHub connection in the background even the login failed. And I am not sure why the token expire so quickly, SM seems to require me to login every few hours. Not sure if it is related to #214 or GitHub's 2-steps verification

Recently, I saw multiple time SM crashing my PC overnight (locked, but not turned off) with GitHub login prompts. it created like over 100 GitHub login prompts in the background and completely overwhelm all 16GB of RAM.

I think SM should stop retry if login fail too much so it will not crash the computer every time GitHub fail to login.

**Steps to reproduce**

1. Turn on GitHub 2 step verification
2. Clone a GitHub project on SM
3. Put it there
4. Wait until GitHub login failed
5. 5 GitHub login windows pop up
6. Wait more, 5 more GitHub login windows pop up
7. Repeat 6 until PC out of memory

**Expected behavior**

1 GitHub login failed pop up and will not show anymore GitHub login windows.
I am not sure if SM have log for connection issue, or I hope to see some.

**Screenshots**

![image](https://user-images.githubusercontent.com/4518597/48524408-214ca680-e8bb-11e8-9a89-dc0d45e03a32.png)
This is what every time it pops up when SM fail to login and 5 GitHub login windows will pop up.
5 more will pop up later if you left it there. If you don't login, they will keep coming until your PC completely freeze

**Comment by dpjohnst** [comment]
Hi @jasonycw,

Could you confirm if you're still seeing this issue?

Kind regards,
\- Dylan from Sublime HQ

**Comment by jasonycw** [comment]
Not recently, but my working PC switches to a Mac, so I haven't touch the Windows version for quite some time.

**Comment by dpjohnst** [comment]
Thanks for the quick reply!

I'll go ahead and close this issue, but feel free to re-open it if you experience this issue again.

Cheers,
\- Dylan from Sublime HQ
