### ISSUE TITLE
Stash keep index not working

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#241]
**Version info**

 - OS: Windows 10 
 - Build: 1087

**Description**

Stash keep index is not working, the working directory is cleared

**Steps to reproduce**

1. Open repository
2. Click <br>![image](https://user-images.githubusercontent.com/4518597/48597538-43b4f180-e999-11e8-9022-4262d00fdda3.png)
3. Click <br>![image](https://user-images.githubusercontent.com/4518597/48597574-6e06af00-e999-11e8-9e13-4b10ac8220ad.png)
4. Click (I don't know why this need to click again) <br>![image](https://user-images.githubusercontent.com/4518597/48597582-81197f00-e999-11e8-852e-068f6c6d9b9f.png)
5. Type something or nothing <br>![image](https://user-images.githubusercontent.com/4518597/48597598-97273f80-e999-11e8-9be0-4a89cab17049.png)
6. Type `Enter`
7. Stashed with nothing left in working directory<br>![image](https://user-images.githubusercontent.com/4518597/48597616-adcd9680-e999-11e8-8b48-dc86e7d7e9cd.png)

**Expected behavior**

The working directory keep the change and there is still a stash

**Screenshots**

![image](https://user-images.githubusercontent.com/4518597/48597624-b58d3b00-e999-11e8-9bdf-d43f688b0f9e.png)

**Comment by dylanjohnston** [comment]
Hi @jasonycw,

Thank you for reporting this. 
I've been unable to reproduce this issue using the steps you provided. 

To double check: do you have staged files when you run this command?

Kind regards,
\- Dylan

**Comment by jasonycw** [comment]
No, but I don't have staged files, just uncommit changes
![image](https://user-images.githubusercontent.com/4518597/48684852-976c4880-ebee-11e8-80f7-6c001170d36e.png)

After running it stash push keep index, it shows success
![image](https://user-images.githubusercontent.com/4518597/48685047-5de80d00-ebef-11e8-92d1-c77fdae0fafd.png)

But the result is not saving the stash in working directory
![image](https://user-images.githubusercontent.com/4518597/48685060-6dffec80-ebef-11e8-879d-174e42ac4626.png)

I expect I still have 1 file change in my working directory

**Comment by jskinner** [comment]
This is working as intended: the command `git stash --keep-index` is run as it should be.

`--keep-index` means stash, but keep the index (aka staged files) as it is. If you don't have any staged files, passing `--keep-index` does not change the behavior of git stash.
