### ISSUE TITLE
Make the "x commits behind" indicator clickable, to pull that branch.

### ISSUE THREAD

**Issue by Herteby** [sublimehq/sublime_merge#242]
**Problem description**
You should be able to click the "x commits behind" indicator to pull that branch.
I think it's more intutitive when you see the indicator to just click it, rather than having to click the pull button on the opposite side of the window. This would also solve the annoyance of having to switch to a branch before pulling it (especially when you have uncomitted changes that you first have to stash before switching).

And it already looks like a button!

Likewise, I suppose the "x commits ahead" indicator should push the branch when clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/6474685/48612253-c1bccc80-e988-11e8-8e61-480684ab86d1.png)

**Comment by dpjohnst** [comment]
Thanks for the feedback - added in development build 2042!

**Comment by dpjohnst** [comment]
Hi @Herteby,

Just following up that this was released to the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan
