### ISSUE TITLE
Commit "View on Web" URL format string

### ISSUE THREAD

**Issue by benmosher** [sublimehq/sublime_merge#243]
**Problem description**

Our remote repo is in Bitbucket and therefore a URL can be constructed from the commit hash to get to the Bitbucket commit page. This is presumably true for most hosted Git sites (e.g. Github, GitLab).

It would be nice to be able to click in the UI to warp directly to the page. Right now I just do it by hand by opening a commit and pasting over the hash with one copied out of the UI.

**Preferred solution**

A config option to provide a template string (such as `https://github.com/sublimehq/sublime_merge/commit/${commit_hash}`) which, if configured, adds a link in the commit metadata to that commit.

I can imagine eventually some presets for common hosting providers but just the template string to start would be great!

**Comment by srbs** [comment]
This would likely be best provided as a plugin when the plugin API gets released.

**Comment by benmosher** [comment]
Makes sense to me.

**Comment by srbs** [comment]
@benmosher, I finally got around to writing a workaround for this: https://forum.sublimetext.com/t/github-integration-commands-menu-items/53893

**Comment by reslear** [comment]
@benmosher @srbs resource https://github.com/reslear/sublime-merge-github
