### ISSUE TITLE
A Repository List Window showing repos previously added

### ISSUE THREAD

**Issue by greggman** [sublimehq/sublime_merge#246]
**Problem description**

Opening a specific repo if you have many repos is a pain

**Preferred solution**

Add a repo list window that shows all the repos ever opened in sublime merge, ideally with icons as icons make it easier to spot a repo quicker than without

**Alternatives**

The "Open Recent" list is a kind of alternative but recent lists usually only handle the last 4 to 10 repos which means visiting a repo that was registered a while ago is more tedious

**Screenshots**

Here's how another app does it. For icons it looks for icon.png/gif/jpg in the root of each repo

<img width="592" alt="screen shot 2018-11-18 at 22 36 46" src="https://user-images.githubusercontent.com/234804/48673286-46733a80-eb83-11e8-90e4-b6280aa8170a.png">

**Comment by Herteby** [comment]
Isn't this what "switch repo" already does?

**Comment by greggman** [comment]
well hmmm,

* Wish "switch repo" showed icons as they are much easier to see. OSes have icons for apps for the same reason. It's easier at a glance to find what I'm looking for.

* Wish I could open more than one repo at a time from the "switch repos" window. In other words wish it was named something else like "list repos" or "browse repos" or "show repos" and clicking a repo just opened a new window and the "list repos" window stayed open.

**Comment by jasonycw** [comment]
Maybe addint Ctrl + Click to the switch repo windows so we can open multiple repo at once

**Comment by wbond** [comment]
I'm curious, where do those icons come from?

**Comment by dpjohnst** [comment]
This has been added to the latest build of Sublime Merge. You can find it on the welcome page of a new tab.
