### ISSUE TITLE
Window sometimes gets minimal size

### ISSUE THREAD

**Issue by Herteby** [sublimehq/sublime_merge#249]
**Version info**

 - OS: CentOS Linux 7.5 with Cinnamon 3.6.7
 - Build: 1084

**Description**

Sometimes, the window opens as the smallest size possible.
I suspect this has something to do with the feature "Window state is now restored when re-opening a repository". Perhaps it defaults to zero when it can't find the previous session or something.

**Steps to reproduce**
Not sure yet, I will post an update if I find a repeatable sequence.

**Expected behavior**

The window should open with a reasonable size.

**Screenshots**

![image](https://user-images.githubusercontent.com/6474685/48782753-2e183280-ecdf-11e8-815b-cf05eed7ff08.png)

**Comment by jskinner** [comment]
Thanks for the report, this has been fixed in the current series of dev builds, at https://www.sublimemerge.com/dev

**Comment by arcturus140** [comment]
I am also having this issue. 

**Version Info**

- OS: Linux Ubuntu 16.04
- Build: 1084

**Steps to reproduce**
1. start ST Merge
2. resize image of the window to size 30x1 pixel
3. try to find it on a dual monitor setup :rofl: 

**Screenshots**
![st_m](https://user-images.githubusercontent.com/44707562/49155179-304b4400-f312-11e8-84d0-4daa52a39558.png)
*minimum size of ST Merge*

**Comment by Herteby** [comment]
@arcturus140 Now that's small! :open_mouth: 
I guess I was saved by Cinnamon which puts the application menu inside the window, and doesn't let the window be smaller than that.
