### ISSUE TITLE
Commit Graph + Space 1086 regression: cannot enter space in search filter

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#250]
**Version info**

 - OS: macOS 10.14
 - Build: 1087

**Description**

When searching for a commit message, `content:`, a `file:` / `path:` with a space in it, or any advanced search (`and`/`or`) the space is not inserted and instead switches to the `Contents` view.

Note: sometimes everything seems to work fine until a commit is clicked & then this behavior occurs. I'm not sure how to reproduce that behavior.

For those curious, this is the build 1086 feature:
> Double-clicking or pressing space in the commit graph will focus on the first file of the selected commit

**Steps to reproduce**

1. open a repository
2. start a search
3. type by hand `contents:"some text"`
    * note: there have to be results, feel free to replace `some text` with any multi-word phrase
4. notice the view changes to `Contents` when typing the space

**Expected behavior**

Space inserted in the search input box.

**Comment by jskinner** [comment]
Thanks for the report, this has been fixed in 1088
