### ISSUE TITLE
Hunk history does not show diff in the commit the file was added in

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#251]
**Version info**

 - OS: macOS 10.14
 - Build: 1087

**Description**

Hunk history doesn't show diff of when the file was added and includes extra commits prior to when the hunk was added.

**Steps to reproduce**

Commands to create an example test repos I used to reproduce: 

    mkdir __test; cd __test
    git init
    
    printf "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15" > file.txt
    git add file.txt
    git commit -m initial-original
    
    printf "1\na\nb\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\ny\nz\n15" > file.txt
    git commit -am letters-original
    
    printf "1\na\n+\nb\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\ny\n-\nz\n15" > file.txt
    git commit -am symbols-original
    
    # reset & repeat
    printf "" > file.txt
    git commit -am empty-file
    
    printf "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15" > file.txt
    cp -f file.txt another-file.txt
    git add another-file.txt
    git commit -am initial-again
    
    printf "1\na\nb\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\ny\nz\n15" > file.txt
    cp -f file.txt another-file.txt
    git commit -am letters-again
    
    printf "1\na\n+\nb\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\ny\n-\nz\n15" > file.txt
    cp -f file.txt another-file.txt
    git commit -am symbols-again
    
    smerge .

1. create the repository above
2. navigate to current `master`
3. view Hunk History for one of the hunks in `another-file.txt`
4. notice correct diffs in commits `symbols-again` and `letters-again`, but no diff is shown for `initial-again`
5. go back to current `master`
6. view Hunk History for one of the hunks in `file.txt`
7. notice the same correct behavior for `symbols-again` and `letters-again`, and now `initial-again`
    * the file existed, but was emptied in the previous commit, `empty-file`
8. but now, `initial-original` shows up with a blank diff even though it shouldn't

**Expected behavior**

Diff of added/new files shown for hunk history & previous history for hunks prior to being added not shown.

**Comment by jskinner** [comment]
Thanks for the detailed report, this is now fixed in 1089
