### ISSUE TITLE
Build 1088 on Ubuntu 16.04 - Unable to start

### ISSUE THREAD

**Issue by clci** [sublimehq/sublime_merge#254]
Hi.

Just updated to build 1088. Running Sublime Merge from terminal I got these errors:
`$ smerge .`
`Unable to load gdk_display_get_monitor_at_point from libgdk-3.0.so`
`Unable to load gdk_display_get_monitor_at_window from libgdk-3.0.so`
`Unable to load gdk_monitor_get_scale_factor from libgdk-3.0.so`
`Unable to load gdk_monitor_get_workarea from libgdk-3.0.so`

And the Sublime Merge window doesn't show up.
I'm on Ubuntu 16.04.

Bye

Edit: previous build 1087 worked fine.

**Comment by deathaxe** [comment]
It was reported _gtk 3.24.1_ is working well. Did you consider updating your gtk?

**Comment by jskinner** [comment]
Upgrading to a newer version of GTK will fix the issue, but it'll also be addressed on our end in the next build, where we'll be compatible with older versions too.

**Comment by clci** [comment]
If Sublime's authors say they intentionally do not support Ubuntu 16.04 anymore, thus this isn't a bug, I'll shrug and adapt myself. Otherwise I'd rather not to tinker with base system libraries on my daily work laptop.

I'll stick with build 1087 until the next version. Thanks jskinner.

**Comment by srbs** [comment]
Based on those 4 error message, the minimum would be GTK 3.22.

**Comment by jskinner** [comment]
This should now be fixed in 1089
