### ISSUE TITLE
Ignore Whitespace: Multi-column diff issues when blank lines are hidden/ignored

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#257]
**Version info**

 - OS: macOS 10.14
 - Build: 1089 (verified on 1080 when whitespace ignoring was added)

**Description**

When whitespace is ignored, the side-by-side diff can be incorrect when a hunk is ignored. Similarly, inline diff's line numbers are incorrect.

Note: 'Ignore whitespace' is no longer available in the context menu as of 1088, contradicting the changelog

**Steps to reproduce**

Commands to create an example test repos I used to reproduce:

    mkdir __test; cd __test
    git init
    
    printf "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n" > file.txt
    git add file.txt
    git commit -m initial
    
    printf "1 2\n3 4\n5\n6\n7\n8\n9\n10\n\n\n11\n12\n13\n14\n15\n16\n17 18\n19 20\n" > file.txt
    git commit -am broken-hunk-diff
    
    smerge .

1. create the repository above
2. navigate to current master
    * turn off ignore whitespace
    * expand the diff viewport to allow for side-by-side diff
3. you should see screenshot (a) below, take note of the added blank lines around line 9
4. turn on ignore whitespace
5. you should see screenshot (b) below, note:
    * the blank line hunk/diff is how hidden
    * repeated 17 & 18 on the left
    * duplicate line numbers 17 & 18 on the left 
6. condense the diff viewport to switch to inline diff
7. you should see screenshot (x) below, note:
    * the blank line hunk/diff is still hidden
    * the diff is correct now
    * duplicate line numbers 17 & 18 are still present

Notes:

1. this behavior exists as well when the blank lines are in their own hunk when ignore whitespace is off
2. staging hunks when ignore whitespace is on is _very_ weird, see video (d) below

**Expected behavior**

Correct differences & line numbers displayed when whitespace is ignored.

**Screenshots**

a. show-all-whitespace
<img width="1260" alt="show-all-whitespace" src="https://user-images.githubusercontent.com/297298/48974425-cafc0800-f01e-11e8-87a5-e5dcc7334f3f.png">
b. ignore-whitespace-two-columns
<img width="1260" alt="ignore-whitespace-two-column" src="https://user-images.githubusercontent.com/297298/48974433-01398780-f01f-11e8-876e-079bf3d166ed.png">
c. ignore-whitespace-one-column
<img width="1088" alt="ignore-whitespace-one-column" src="https://user-images.githubusercontent.com/297298/48974429-e2d38c00-f01e-11e8-83c0-0a297ea74109.png">
d. staging-hunks-with-ignore-whitespace
![staging-hunks-with-ignore-whitespace](https://user-images.githubusercontent.com/297298/48975196-deb06a00-f030-11e8-871c-c4103eecc78f.gif)

**Comment by dylanjohnston** [comment]
Hi @srbs,

Thank you for reporting this!

I have investigated this issue, and submitted a fix for it. I will update you when this fix arrives in a new build.

Kind regards,
- Dylan

**Comment by srbs** [comment]
@dylanjohnston, everything looks good to me! Thanks a ton!
