### ISSUE TITLE
A File List?

### ISSUE THREAD

**Issue by greggman** [sublimehq/sublime_merge#259]
**Problem description**

I wish there was an easier way to see just the names of the files and not all the diffs themselves

**Preferred solution**

Either another pane that could replace the history pane (on the left) or be stacked with the history pane. OR, maybe just a button that cycles the diff pane through 3 states

1. whatever the default currently is (seems to be show diffs, hide new files)
2. show everything
3. collapse everything.

Note that collapsed each line is still rather large. Compare

<img width="398" alt="screen shot 2018-11-26 at 15 32 52" src="https://user-images.githubusercontent.com/234804/48996944-61e8d180-f191-11e8-839d-accc2bc22278.png">

vs

<img width="721" alt="screen shot 2018-11-26 at 15 39 34" src="https://user-images.githubusercontent.com/234804/48996979-804ecd00-f191-11e8-9bb2-fe9f178365e4.png">

Further, there seems to be no easy way to stage multiple files quickly. If you're just working on code then maybe that's fine but if you're working on projects like webpages with lots of assets I often have 50-150 files (images) I need to stage and if they are intermixed with things I don't want to stage then AFAIK in SublimeMerge I have to click 50-150 stage buttons where as from the command line I could just `git add path/to/new/images` and in some other tools I could shift select

**Comment by wbond** [comment]
The Contents view shows the filenames to the left of the diff pane.

**Comment by greggman** [comment]
Thanks! 

BTW doesn't this seem seems like a very strange workflow? There's 2 labels at the top, "location" and "contents" but clicking "location" makes the two labels disappear. Should those 2 labels should always just be there to make it easy to switch between them?

![screenflow](https://user-images.githubusercontent.com/234804/50621790-9c414d80-0f4b-11e9-8c59-264cdf81e7ad.gif)

**Comment by safield** [comment]
I agree, this is a weird workflow. I am finding the Sublime Merge UI to a nest of anti patterns and confusing design. It needs to be rethought from the ground up!

**Comment by jskinner** [comment]
When you have the sidebar hidden, and you select the Show Contents menu item, we show the table of contents in a temporary state: as soon as you close the selected file, the sidebar is hidden again.

If we didn't do this, then showing the table of contents would require also showing the sidebar, which would then have to be manually toggled off afterwards. This isn't desirable, especially on small screens where there isn't enough space to show the side bar at all times.

If you leave the sidebar visible (i.e., by pressing the leftmost button on the tool bar), then showing the contents will work as you expect.

**Comment by greggman** [comment]
Why was this closed? Being able to stage multiple files quickly is still an issue. I check in 500 assets from some artist and in sublime merge that requires 500 clicks.

Also your comment makes no sense. See the gif again

First there's a panel on the left, picking a menu item changes that panel to a different panel, that different panel shows 2 options "Locations" and "Contents". Clicking one removes the option to see the contents. Why not just always show the toggle at the top to show one or the other?

**Comment by greggman** [comment]
Why was this closed? The issue of dealing with lots of files is still there. I have 500 new assets from an artist I have to click stage 500 times!??!?!

**Comment by jskinner** [comment]
There is a Stage All button next to the Untracked Files heading when it's expanded that will stage all 500 new assets

**Comment by greggman** [comment]
WOW! I can't believe that response came from someone making a **GIT** front end

The entire point of having a GIT front end is to be able to **selectively** stage things. If I wanted to stage all all the time I'd use SVN.

Some artist gives me

     +-assets
        +-ui-feature-1
           +-file1
           +-file2
           +-file3
           +-file...
           +-file100
        +-ui-feature-2
           +-file1
           +-file2
           +-file3
           +-file...
           +-file100
        +-ui-feature-3
           +-file1
           +-file2
           +-file3
           +-file...
           +-file100

Etc. I need to be able to select `ui-feature-2` and stage all under that. Why is that a controversial feature? 

![screenflow](https://user-images.githubusercontent.com/234804/53074242-97e9e780-352d-11e9-9aa9-d33beda18e73.gif)

**Comment by stinos** [comment]
> The entire point of having a GIT front end is to be able to **selectively** stage things

Staging multiple files is handy yes, but please don't turn it into 'what I need is what the rest of the world must need as well' with phrases like this. There's more to a git UI than this :)

**Comment by greggman** [comment]
you turned it into a nobody needs this feature by closing the request.

In my field, games, almost everyone needs this feature. There are more
asset files than text files and the get modified in bulk
