### ISSUE TITLE
Builds 1088, 1089 - Command palette does not update after keypresses

### ISSUE THREAD

**Issue by weelillad** [sublimehq/sublime_merge#262]
**Version info**

 - OS: elementary OS 5.0 Juno, built on Ubuntu 18.04 LTS
 - libgtk-3-0: 3.22.30-1ubuntu1 amd64
 - Build: 1088, 1089

**Description**

The command palette sometimes does not redraw after a keypress. Alt-Tabbing out and back will force a redraw, but further keypresses after that will also not be drawn. The keypresses are captured, just not drawn - pressing Enter will cause the branch to be created with whatever was typed.

**Steps to reproduce**

1. Call up the Command Palette with Ctrl-Shift-P
2. Type "create branch", or select the "Create Branch" option
3. Start typing a desired branch name (problem becomes visible by the 5th letter)

**Expected behavior**

The branch name is displayed in the command palette as I type it.

**Comment by jskinner** [comment]
Thanks for the report - this should now be fixed in 1091, please let me know if it's still happening for you
