### ISSUE TITLE
Open Repository in ST should be disabled when a repo is not in focus

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#265]
**Version info**

 - OS: macOS 10.14
 - Build: 1090

**Description**

In various window states or dialogs, 'Open in Sublime Text' will open a `/tmp/subl stdin *.txt` file.

Known broken states/dialogs: (non-exhaustive check)
* New repository
* Clone repository...
* Check for Updates...
* Changelog...

**Steps to reproduce**

1. open SM
2. `File -> New repository`
3. `Repository -> Open in Sublime Text`

**Expected behavior**

Nothing opened in ST or a disabled menu item when a repository isn't open. ('Reveal in Finder' should probably be disabled as well)

**Comment by jskinner** [comment]
Thanks for the report - fixed in 1091
