### ISSUE TITLE
Package depends on libgtk-3.0 which is not installable

### ISSUE THREAD

**Issue by dbeckwith** [sublimehq/sublime_merge#268]
**Version info**

 - OS: Ubuntu 18.04
 - Build: 1084, trying to upgrade to 1092

**Description**

Trying to upgrade to 1092 via `apt`, I get the following message:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 sublime-merge : Depends: libgtk-3.0 but it is not installable
E: Broken packages
```
There is no debian package named `libgtk-3.0`, maybe it's supposed to be `libgtk-3-0`?

**Steps to reproduce**

1. Run `apt install sublime-merge=1092` on Ubuntu 18.04

**Expected behavior**

The package should install its dependencies correctly then install itself.

**Comment by srbs** [comment]
Could you check again, this might have been fixed for SM as [it has for ST](https://forum.sublimetext.com/t/cant-install-sublime-merge-because-of-unmet-dependency/40676/2).

**Comment by dbeckwith** [comment]
:+1:
