### ISSUE TITLE
Can't read .gitconfig if [include] file does not exist

### ISSUE THREAD

**Issue by alanbriolat** [sublimehq/sublime_merge#271]
**Version info**

 - OS: Ubuntu 18.04
 - Build: 1084

**Description**

Sublime Merge won't show my user details as configured in `.gitconfig`, even when `git config` does. Instead it shows "Click here to set user details". If I use the user details dialog to set new values, those are reflected in `git config` but still not displayed in Sublime Merge.

I narrowed it down to the fact my `.gitconfig` has an `[include]` that refers to a file that exists on some machines but not others. Removing the `[include]` or creating the file both resolve the problem in Sublime Merge. This diverges from `git` CLI behaviour, which silently ignores the missing include.

This may be related to #30, but this particular case feels like a bug rather than an unimplemented feature, since the `[include]` works correctly (included config values are used) when the file is present.

**Steps to reproduce**

1. Create a `~/.gitconfig` with the following contents:
```
[user]
    name = User Name
    email = user@example.com
[include]
    path = ~/.this-file-does-not-exist
```
2. Open a repository in Sublime Merge that doesn't have a `[user]` section in `.git/config`
3. Look for the user info below the commit message box

**Expected behavior**

Commit interface should show my user details as configured in `.gitconfig`.

**Comment by jskinner** [comment]
Thanks for the report - this was fixed in 1103
