### ISSUE TITLE
Theme breaks – possibly license related

### ISSUE THREAD

**Issue by lvarado** [sublimehq/sublime_merge#272]
**Version info**

 - OS: macOS 10.14
 - Build: 1092

**Description**

I downloaded Sublime Merge and ran it for the first time today. Tried changing the theme to dark and was asked for a license key. I didn't know this was a separate license from Sublime Text so I put that one in and got the message telling me it's a different license. Closed out of that and changed the font face and size, but they didn't apply immediately so I restarted the app, only to see a broken theme. I suspect this is license-related since the font settings are stored in a preferences file which I later deleted to no avail.

**Steps to reproduce**

Apologies if this is inaccurate. It's all I can recall doing but I haven't been able to restore the original state to see if this is how to reproduce exactly. I deleted `~/Library/Application Support/Sublime Merge` and deleted the app file then reinstalled but the issue persists. Nothing happens when I select **Help > Debug Information**. Please let me know if there are additional steps to take to clear out cache/settings files or to debug.

1. Open preferences, change theme to Dark
2. Fill license key with Sublime Text key
3. Click to dismiss message about this being a license for a different product
4. Update font face and size
5. Quit and relaunch app

**Expected behavior**

Default theme is displayed

**Screenshots**

![screen shot 2018-11-29 at 11 27 52 am](https://user-images.githubusercontent.com/32886847/49240511-f1c59000-f3ca-11e8-82a2-006660f1e5c4.png)

**Comment by lvarado** [comment]
I deleted build 1092 again and installed build 1091. The default theme shows fine now, so I deleted 1091 and reinstalled 1092... still good, and I tried to reproduce the issue but wasn't able to. Maybe there's something I don't remember doing.

**Comment by wbond** [comment]
Yes, it would appear you corrupted your theme, or tried to edit the theme on the evaluation version.
