### ISSUE TITLE
Display ahead/behind info in Location Bar sidebar

### ISSUE THREAD

**Issue by onecrayon** [sublimehq/sublime_merge#28]
**Problem description**

Currently you can only see how many commits a branch is ahead/behind of its tracking branch if you check it out and look at the branch name box in the middle of the toolbar.

**Preferred solution**

Display the number of commits each local branch is ahead/behind of its tracking branch in the Location Bar sidebar.

**Alternatives**

Several ways this could be displayed; see attached screenshot for how Fork does it as an example of prior art (mac OS app).

**Screenshots**

![screen shot 2018-09-28 at 3 27 46 pm](https://user-images.githubusercontent.com/33501/46236392-62045680-c333-11e8-963e-4393f0df7e5d.png)

**Comment by jskinner** [comment]
This is now implemented in build 1070
