### ISSUE TITLE
Make switch project as in Sublime Text

### ISSUE THREAD

**Issue by insolution4** [sublimehq/sublime_merge#281]
**Problem description**
I'd like to see a switching project feature at Merge(Ctrl + Alt + P). It would be grate! I miss it very much )

**Comment by srbs** [comment]
Does `Ctrl`+`Shift`+`o` / `File`->`Switch Repository` satisfy what you're looking for?

**Comment by insolution4** [comment]
Yes, it is. Thanks.
But the querstion now is... why it differs from sublimes shortkey? I thought it uses the same shortkeys as Sublime Text.

**Comment by deathaxe** [comment]
Because you don't open projects, but repositories, I guess. I think it's derived from the default shortcut to open files - `ctrl+o`.

**Comment by insolution4** [comment]
ok. i see. Its ok then.
Thank you very much )
