### ISSUE TITLE
Favorite repositories support

### ISSUE THREAD

**Issue by renattou** [sublimehq/sublime_merge#285]
**Problem description**

Every time I open Sublime Merge, I have to locate my repositories manually. As this is something I have to do quite frequently, it's a little troublesome.

**Preferred solution**

On the initial screen where we open our repository, I think there should be a list of favorite repositories. After opening any repository, there would be a favorite button or menu item that allows the user to favorite it.

**Alternatives**

Showing the recent opened repositories could also help with this problem. I know we can see them on the top menu, but I think these would be used more than the new/open/clone buttons in the long run.

**Screenshots**

This is the screen which I'm referring to:
![screen shot 2018-12-01 at 19 15 31](https://user-images.githubusercontent.com/2185726/49333038-e460ff00-f59e-11e8-9cfa-b273aefae281.png)

**Comment by srbs** [comment]
Sublime Merge does remember all of the previously opened repositories, you can find them at `File`->`Open Recent`.

Other ways to open known repos:
* `File`->`Open Recent`->`Select` for fuzzy search abilities
* `File` -> `Switch Repository...`
* `Cmd`/`Ctrl`+`Shift`+`o` is the shortcut for Switch Repository

**Comment by renattou** [comment]
@srbs Yeah, I know. That's what I meant by "I know we can see them on the top menu". Sorry for being unclear about that. I was suggesting for this list to be shown in the popup from the attached screenshot, as I think people want to access the same repositories more than new ones.

**Comment by blag** [comment]
I think there should be two lists - a "Recent repositories" (just a copy of `File` -> `Open Recent`) list and a "Favorite repositories" (eg: user managed) list.

Perhaps repos that are in the favorites list should not be displayed in the recent repos list. I don't really see the value in displaying the same repo in both lists, but it could get confusing why the recent list doesn't contain repos in the favorites list.
