### ISSUE TITLE
Support nested folder display mode for ref lists

### ISSUE THREAD

**Issue by n8gray** [sublimehq/sublime_merge#29]
**Problem description**

Sublime Merge should display ref lists using a nested folder representation.  This is a common feature in most git clients and lots of users leverage it to keep large lists of refs organized.

Git itself has semi-formal support for "path-like" ref names using `/` as a path separator.  If you have a "foo/bar" branch git will prevent you from creating a "foo" branch, since "foo" can't be both a ref and a "directory" of other refs.

**Preferred solution**

* Lists of ref names should be displayed using a nested folder representation.
* This would include at least the sidebar lists:
    * Branches
    * Remote Branches
    * Tags
* For example, if there are four ref names: `foo/bar/alpha`, `foo/bar/beta`, `foo/gamma`, and `buzz/lightyear` they should be displayed like:
    * foo
        * bar
            * alpha
            * beta
        * gamma
    * buzz
        * lightyear
* In this example the `foo`, `bar`, and `buzz` rows should have disclosure triangles that can be expanded or collapsed.

**Alternatives**

Using search to filter the list of branches might be considered an alternative to hierarchical organization of refs.  I feel that both are highly valuable for different use cases and neither approach is 100% sufficient.

**Screenshots**

Branch list in SourceTree:
<img width="265" alt="screen shot 2018-09-28 at 6 18 54 pm" src="https://user-images.githubusercontent.com/82794/46239258-2f665800-c34b-11e8-9e6f-3a5a6bb3adcd.png">

Branch list in Git Tower:
<img width="199" alt="screen shot 2018-09-28 at 6 19 34 pm" src="https://user-images.githubusercontent.com/82794/46239255-21b0d280-c34b-11e8-8a5e-d8c1b81bcfdf.png">

**Comment by jskinner** [comment]
This is implemented in dev build 1067 - https://www.sublimemerge.com/dev
