### ISSUE TITLE
Pressing Backspace does not discard hunk anymore

### ISSUE THREAD

**Issue by peret** [sublimehq/sublime_merge#290]
**Version info**

 - OS: macOS 10.14.1
 - Build: 1092

**Description**

Pressing the shortcut for discarding a hunk (Backspace) does nothing since the latest update. It used to work fine. Also, discarding all file changes with Shift + Backspace still works as expected.

**Comment by jskinner** [comment]
Thanks for the report, this is now fixed in 1097
