### ISSUE TITLE
Crashes on first keypress

### ISSUE THREAD

**Issue by indrelf** [sublimehq/sublime_merge#291]
**Version info**

 - OS: Linux Mint 18.3, (Ubuntu 16.04)
 - Build: 1092

**Description**

Crashes always on first keypress (except arrow keys).
kern.log:
kernel: [*] sublime_merge[*]: segfault at e8 ip 00007f60934116a2 sp 00007ffc55da24a8 error 4 in libgdk-3.so.0.1800.9[7f60933d4000+d4000]
Works just fine when executing as root user.

**Steps to reproduce**

1. run sublime_merge
2. press Spacebar

**Expected behavior**

I expected to be able to write commit message.

**Temporary solution**

Downgraded to 1084

**Comment by jskinner** [comment]
Thanks for the report, this should be fixed in 1097
