### ISSUE TITLE
Allow clicking links in "Last Command" drop down

### ISSUE THREAD

**Issue by kortschak** [sublimehq/sublime_merge#295]
**Problem description**

Ability to send a PR to GitHub or Bitbucket.

**Preferred solution**

Currently, both GitHub and Bitbucket send back a link to open a PR on push to a repository or branch that is forked from another. This text can be see by clicking on the last command status. It would be good to be able to click that link.

**Alternatives**

Full PR integration (the solution above seems simpler).

**Comment by srbs** [comment]
See also #42

**Comment by kortschak** [comment]
@srbs Thanks. Closing as dup.
