### ISSUE TITLE
Support for .gitconfig conditional includes

### ISSUE THREAD

**Issue by markashleybell** [sublimehq/sublime_merge#30]
**Problem description**

I use [conditional includes](https://git-scm.com/docs/git-config#_includes) to separate my personal projects from work for my employer. Because of this, my `.gitconfig` doesn't directly contain a `[user]` section; it's included dynamically based on the folder I'm working in:

### In `.gitconfig`

    [includeIf "gitdir:Work/"]
        path = .gitconfig-work
    [includeIf "gitdir:Personal/"]
        path = .gitconfig-personal

### `.gitconfig-work`

    [user]
        name = Mark Bell
        email = [MY WORK EMAIL]

### `.gitconfig-personal`

    [user]
        name = Mark Bell
        email = [MY PERSONAL EMAIL]

However, this results in Sublime Merge asking me to enter my name and email address when I commit to any repository, presumably because it can't find them in `.gitconfig` and isn't parsing the conditionals. 

As a result, I can't currently use SM at all, unless I re-specify my credentials for every repository I work on and persist them to the settings for the individual working copy.

**Preferred solution**

Sublime Merge should be able to figure out that the current repository is using conditionally included user info. I realise mine is a fairly niche use case, but it would be great to get support for this, as it is an established Git feature.

**Comment by IlikePepsi** [comment]
I'm also using several git configs and would appreciate if sublime merge could evaluate conditional includes to show the right git identity based on the working directory.

At the moment when you put a `[user]` section and some include directives into your `.gitconfig` sublime merge will use that identity in the UI but when issuing a commit the identity configured for the specific directory will be used.

**Comment by voltechs** [comment]
Please support this! (I came to file a ticket, but searched first like a responsible developer 😉)

Today I set up conditional includes to manage different identities under me `~/Workspace/..`. It's beautiful and works great! I was about to finally ditch `Sourcetree` (they don't support it either, FTR) but sadly `Sublime Merge` doesn't either.

This should be relatively straight-forward. I'm not sure how `SM` is currently getting settings, but it probably shouldn't be much more than `git config user.email` and `git config user.name` on repo load. :)

**Comment by pasnox** [comment]
> Please support this! (I came to file a ticket, but searched first like a responsible developer )

No more words needed.

**Comment by jskinner** [comment]
Support for conditional includes was added in build 1103

**Comment by pasnox** [comment]
Hu ? I'm using Sublime Merge on Linux (Stable Channel, Build 1107) and it's clearly not there, or not working at all :)
Is there something to enable / configure ?

**Comment by jskinner** [comment]
If it's not working for you, please file a new issue, and include the output of the Help/Debug Information menu item (removing any confidential parts first).

**Comment by pasnox** [comment]
Done @ #502
