### ISSUE TITLE
Crash when viewing specific file on Windows 10

### ISSUE THREAD

**Issue by mayfieldiv** [sublimehq/sublime_merge#303]
**Version info**

 - OS: Windows 10
 - Build: 1096, 1097, 1098

**Description**

Application crashes on viewing changes to a specific file. When using "View Tree" or navigating to any (at least recent) commit containing changes to that file, Sublime Merge crashes within 1 second.

The file doesn't seem to be anything special: 1800 lines of Java UTF-8 w/ CRLF.

This is happening in the current stable and dev channel builds and happened in the last couple dev channel builds.

**Steps to reproduce**

1. Clone this repo: https://github.com/mayfieldiv/sublime-merge-crash-demo
2. Click on commit
3. Sublime Merge crashes

**Comment by srbs** [comment]
Are you able to share the repo?

**Comment by mayfieldiv** [comment]
No I can't, sorry. Is there any kind of log file I can provide?

**Comment by mayfieldiv** [comment]
I extracted the file at the earliest point where it causes the crash and updated the steps to reproduce in the original post.

**Comment by mayfieldiv** [comment]
Alright, looked around and see that others have reported the same issue.
https://forum.sublimetext.com/t/crash-when-opening-java-source-file/40815/2

**Comment by srbs** [comment]
@mayfieldiv, yeah there are a few issues that have been created in both Text & Merge for that core issue, feel free to downgrade to build 1092 (stable) / 1091 (dev) or before.

**Comment by mayfieldiv** [comment]
It looks like this is fixed in 1100
