### ISSUE TITLE
Missing commits in history

### ISSUE THREAD

**Issue by AndreasOM** [sublimehq/sublime_merge#305]
**Version info**

 - OS: Windows 10
 - Build: 1097
 - Trial version (while we are waiting for internal procurement to get us some licenses)

**Description**

Some times commits are missing from the history.
I had the "hunch" before, but this commit is the first where I can actually see it.

**Steps to reproduce**

Not clear.
Opening the affected repository in Sublime Merge always reproduces it.

**Expected behavior**

All commits show up.

**Screenshots**
This is how it looks on the console. Commit 6bd2806 is the one of interest.

![git](https://user-images.githubusercontent.com/192244/49646857-c2dd9880-fa20-11e8-9084-fb3ebd8de045.png)

This is how it looks in the default Sublime Merge view. Commit should be second from bottom on Thursday at 3:56pm.
![sublime_merge_1097-history](https://user-images.githubusercontent.com/192244/49646905-e99bcf00-fa20-11e8-8a2b-7a378f175175.png)

If I check the file history of the file that was changed I see the commit on Thursday at 3:56pm.
![sublime_merge_1097-file_history](https://user-images.githubusercontent.com/192244/49647273-3502ad00-fa22-11e8-80c4-c8734e1b7059.png)

**Other**

I tested various other tools (e.g. gitk), and they all show the correct history.
And sorry for the need to censor.

**Comment by srbs** [comment]
If you look to the left of the commit message `Merge remote-tracking branch [...]`, you'll see an empty orange box. When you click on it, it'll open/expand the merge commit's children and you should see your missing commits.

The setting that powers this behavior is `expand_merge_commits_by_default`.

See also https://forum.sublimetext.com/t/sublime-merge-tree-view/40808

**Comment by AndreasOM** [comment]
Thank you.
That solved it.

I was searching the whole documentation, but didn't find any info about that.
And it wasn't clear at all that I could click those empty boxes.

ps:
merge-commits shouldn't happen in the first place, so I didn't have them on my radar.
