### ISSUE TITLE
Commit hooks not found

### ISSUE THREAD

**Issue by Zooce** [sublimehq/sublime_merge#307]
**Version info**

 - OS: Windows 10
 - Build: 1096

**Description**

When trying to make a commit - it fails with an error like this:
```
error: cannot spawn C:/Users/<my user name>/.git/hooks//commit-msg: No such file or directory
```
There's `//` in the path, so maybe that's the problem?

**Steps to reproduce**

1. Open repository on a Windows 10 machine
2. Stage some changes and write a commit message
3. Click "Commit <#> files"

**Expected behavior**

The commit is successful.

**Screenshots**

![commit-error-blur](https://user-images.githubusercontent.com/5490155/49665247-86ef0700-fa11-11e8-8d68-40d3a4eb3f00.png)

![commit-error-2-blur](https://user-images.githubusercontent.com/5490155/49674189-49e53d80-fa2e-11e8-9127-d7eaa3486da3.png)

**Comment by Zooce** [comment]
*Update*
This seems to happen for amending commits as well.

Still happening with Build 1098.

**Comment by jskinner** [comment]
FWIW, Sublime Merge doesn't know anything about commit hooks, it's git itself that's doing that.

It'd be handy if you could include the output from `Help/Debug Information`, at least the "Git Version Information" section

**Comment by Zooce** [comment]
```
=== Git Version Information ===
Using Git: C:\Program Files\Git\mingw64\bin\git.exe (custom)
git version 2.19.1.windows.1
PATH: C:\ProgramData\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\BullseyeCoverage\bin;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\CCM ;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\CMake\bin;C:\Program Files (x86)\quex;C:\Program Files (x86)\Xoreax\IncrediBuild;C:\Program Files\doxygen\bin;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;E:\devtools\Microsoft_VS_Code_Insiders\bin;C:\Program Files\Citrix\System32\;C:\Program Files\Citrix\ICAService\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GitExtensions\;C:\Program Files\Git\cmd;C:\Python27;C:\Qt\5.4\msvc2012_opengl\bin;C:\Program Files (x86)\D-Bus\bin;C:\android\sdk\platform-tools;C:\ant\bin;C:\Program Files (x86)\GnuWin32\bin\;E:\devtools\Microsoft_VS_Code\bin;C:\Users\<username>\AppData\Local\GitHubDesktop\bin;C:\Users\<username>\AppData\Roaming\npm;C:\Users\<username>\AppData\Local\Microsoft\WindowsApps;E:\devtools\Microsoft VS Code Insiders\bin
```

**Comment by Zooce** [comment]
> FWIW, Sublime Merge doesn't know anything about commit hooks, it's git itself that's doing that.

Okay, interesting. I'm able to commit on the command line without issue. Maybe a configuration issue on my end...

**Comment by Zooce** [comment]
So I fixed the double-slash issue (there was an ending slash in my global git config for core.hookspath). The issue still remains, however.

I tried to do an amend commit and I get the same error (the `pre-commit` file is definitely there):

```
error: cannot spawn C:/Users/<username>/.git/hooks/pre-commit: No such file or directory
```

**Comment by Zooce** [comment]
I changed the "Git Binary" setting from `C:\Program Files\Git\mingw64\bin\git.exe` to `system` and the issue has been resolved. The `system` path is `C:\Program Files\Git\cmd\git.exe`.

**Comment by Kolobamanacas** [comment]
> I changed the "Git Binary" setting from `C:\Program Files\Git\mingw64\bin\git.exe` to `system` and the issue has been resolved. The `system` path is `C:\Program Files\Git\cmd\git.exe`.

Thanks a lot for your solution. It was so not obvious that Sublime Merge has at least two option of using Git: one is to use Git client built in Sublime Merge itself and the second is to use Git separately installed on Operation System. Choosing second option resolved all git hooks issues I've been struggling with for months. You are a savior. It's so strange that no SM expert mentioned that in any thread I've encountered about the issue and I would personally highly recommend SM team to update error message when dealing with Git Hooks.
