### ISSUE TITLE
Please implement expansion of the context in the diff viewer.

### ISSUE THREAD

**Issue by vruyr** [sublimehq/sublime_merge#313]
**Problem description**

Sometimes to understand the context of the change one might want to read a larger context in the code. If the code is on the right and Sublime Merge is showing the working tree status, opening an editor is a solution (⌘⏎). In other cases (e.g. viewing a historical diff) opening an editor is opening the currently checked out file which is not what was expected. That leaves the only solution to get the text from git history `git cat-file -p <commit-sha>:<file-path> | $EDITOR -` and manually navigating to the desired line.

**Preferred solution**

Please implement buttons and keyboard shortcuts at the beginning and end of diff chunks that will expand the currently loaded context. It should be possible to load the entire file using this.

**Alternatives**

GitHub diff viewer provides such functionality.

**Comment by srbs** [comment]
You can double click or drag the edge of each diff hunk to show more context. Alternatively, you can click the `...` button on the file header and choose Blame to see the entire file contents at that location.

**Comment by vruyr** [comment]
The drag and double-click is exactly what I needed. Thank you so much!
