### ISSUE TITLE
Resolve by “taking theirs” or “taking mine”

### ISSUE THREAD

**Issue by mstum** [sublimehq/sublime_merge#316]
**Problem description**

When I have a merge conflict, it would be nice if the Resolve screen has an option to just "take theirs" or "take mine".

(This was also brought up in [this comment](https://github.com/sublimehq/sublime_merge/issues/24#issuecomment-431375698), making it a top level issue)

**Preferred solution**

In the side-by-side Resolve view, add a button/menu to either "Take theirs" or "Take mine" to resolve all conflicts. Ideally also show the branch names, because I always have to guess which one is my branch and which one is theirs.

**Alternatives**

I can manually `git checkout theirbranch filename`, or resolve and click the arrow on one side at every conflict.

**Comment by keith-hall** [comment]
This is sometimes also referred to as "keep source contributor" and "keep destination contributor", which IMO is better terminology than "take theirs" and "take mine" :)

**Comment by mstum** [comment]
Maybe, but Sublime sticks to git terminology, which seems to use `ours` and `theirs`, e.g., in https://git-scm.com/docs/git-merge strategies. I'm mostly indifferent, as long as it works ;)

**Comment by GrotzkyD** [comment]
Strange that this is so hard to find as a requested feature. It is the main reason I cannot use Sublime Merge for our company's main workflow.

**Comment by srbs** [comment]
This as been added to the `...` menu in dev build 1114.

**Comment by renatoliveira** [comment]
@srbs but is there a shortcut for it? I had a merge request conflict and I didn't see a "take theirs"-like command from the command palette. Is this only available in the file's menu?

**Comment by jskinner** [comment]
It's available within the Merge Tool (i.e., after pressing the "Resolve" button), and then from the "..." button in the tool bar. 

There's no key binding for it by default, but the respective commands are `take_ours` and `take_theirs` for `Take Left` and `Take Right` respectively

**Comment by coldice** [comment]
Maybe a bit hidden under the "..." menu, but works fine.

**Comment by denis-beurive** [comment]
> Maybe a bit hidden under the "..." menu, but works fine.

Yes, it is hidden. But it works.
