### ISSUE TITLE
Reset context menu item seems to do nothing

### ISSUE THREAD

**Issue by facelessuser** [sublimehq/sublime_merge#317]
**Version info**

 - OS: Windows 10 and Mac (seems to not be OS dependent)
 - Build: 1097

**Description**

Right clicking the last commit and selecting the reset option (any of them: soft, hard, etc.) appears to do nothing.

It will show a green checkmark, and when you look at the last command, it shows `git reset --soft <hash>`, but nothing actually seems to occur. Currently, I must go to command line and instead run `git reset HEAD~1`.

**Steps to reproduce**

1. Commit some changes
2. Right click the committed change and select a reset command from the context, nothing will be done.

**Expected behavior**

Right clicking a commit, and selecting a reset should perform the desired reset.

**Comment by facelessuser** [comment]
Turns out, I was clicking the commit I wanted to reset, not the commit I was resetting to, so this is clearly a user error.

**Comment by bitmagewb** [comment]
I did the same, so a warning of "You are resetting to the current commit, no changes were made" or similar would be helpful.  Or disable those options for the most recent commit.
