### ISSUE TITLE
Bind double-click on remote branch to create local branch + checkout

### ISSUE THREAD

**Issue by zvuc** [sublimehq/sublime_merge#32]
**Problem description**
I don't know about others but in my case very often I have to quickly pull from a remote branch from the list and switch to it. Other clients often ask me if I want to create a local branch of the same name when I double-click on the branch from the remote branches list. Sublime Merge also has double-click for switching between local branches, but no action is specified for when you double-click on a remote branch.

**Preferred solution**

Display a confirmation modal asking if I want to create a local branch of the same name when I double-click on a branch from remote list

<img width="391" alt="image" src="https://user-images.githubusercontent.com/2870726/46267614-e68fe880-c570-11e8-9fc2-c17311002467.png">

Here's an example of what Sourcetree shows when I double-click on a remote branch from list: 

<img width="530" alt="image" src="https://user-images.githubusercontent.com/2870726/46267655-22c34900-c571-11e8-85f7-98e6779d5237.png">

**Comment by AliAskari** [comment]
+1 This. It's such a common task in my workflow I was actually surprised this was not available with the first release.

**Comment by dpjohnst** [comment]
Hi all - this was added in Sublime Merge Build 2057 (development build) and will be available in the next stable build :)

Cheers,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

Just a quick note that this is now available in the latest stable build.

Cheers,
\- Dylan from Sublime HQ
