### ISSUE TITLE
Do you plan a web or ssh version of Sublime Merge?

### ISSUE THREAD

**Issue by in4s** [sublimehq/sublime_merge#325]
I like this tool very much. Do you plan a web or ssh version of it?

**Comment by srbs** [comment]
You should be using the [forum](https://forum.sublimetext.com/c/sublime-merge) for any non-bug or non-enhancement requests.

**Comment by wbond** [comment]
I would think that an "ssh version" would probably be the original command line git client.

In terms of a web version, it sounds as if you are asking if we'd be building it into some sort of online IDE?

We don't currently have any plans to build a version that isn't desktop GUI software.

**Comment by RanceZero** [comment]
As for ssh I actually use it like this: Connect your nautilus (gnome file browser) through ssh, and you should see ssh files like they are local, so you use it like that.

**Comment by kinton** [comment]
@wbond Hello! There is a need to develop projects on a remote server without downloading them to my computer. Sublime merge is an incredible assistant that allows me to solve many problems. Although @RanceZero proposed a solution, constantly mounting a remote directory is problematic and costly. Therefore, it is unfortunate to hear your answer.
