### ISSUE TITLE
Pre-commit hook failure log disappears when losing focus to another application

### ISSUE THREAD

**Issue by foobuzz** [sublimehq/sublime_merge#327]
**Problem description**

When a pre-commit hook fails and the failure log pops in over the yellow-ish background, I want to go to the text editor in another monitor to fix the problems, which are listed in the error logs (e.g. a linter listing specific lines of codes as problematic). But as soon as Sublime Merge loses focus, the pop-up disappears and I need to run the hook in a terminal to be able to consult the message while coding.

**Preferred solution**

Do not make the pre-commit hook log disappear when losing to focus to another window.

**Alternatives**

Add a button or any UI device to sticky the pre-commit hook log.

**Comment by dylanjohnston** [comment]
Hi @foobuzz,

Thank you for using Sublime Merge, and thanks for the feedback.

Currently you can view the output of the last-run Git command at any time by clicking the 'Show Git Output' button. 
![git output](https://user-images.githubusercontent.com/43527364/50189664-5052ae00-037a-11e9-86c3-a587659e6119.png)

In the case of the failed commit hook, this will contain all the output from Git regarding the commit hook status.

Thanks,

\- Dylan Johnston
Software Engineer, Sublime HQ

**Comment by foobuzz** [comment]
That is perfect, thanks for your time.
