### ISSUE TITLE
On pre-commit hook failure, commit message is discarded.

### ISSUE THREAD

**Issue by oddsund** [sublimehq/sublime_merge#33]
**Version info**

 - OS: Windows 10
 - Build: 1062

**Description**

When pre-commit hook fails, the commit message is discarded and the commit message box is empty.

**Steps to reproduce**

1. Open any repository
2. Ensure that pre-commit hook fails(e.g. by returning 1)
3. Stage files and write a commit message
4. Click on commit

**Expected behavior**

Commit message remains in the commit message box.

**Comment by jskinner** [comment]
This is fixed dev build 1067 - https://www.sublimemerge.com/dev
