### ISSUE TITLE
Add "Go to Parent" in "Navigate" menu

### ISSUE THREAD

**Issue by Zooce** [sublimehq/sublime_merge#331]
**Problem description**

When selecting a commit from the commit tree, it would be helpful to have an option to jump to that commit's parent (like in the case where the parent commit is relatively old).

**Preferred solution**

Add a "Go to Parent" option in the "Navigate" menu. We could then also add a keybinding to it, for quick access.

**Alternatives**

An option to do this in the Command Pallet would also work. Another alternative would be to add this option to the context menu when right-clicking on the commit.

**Comment by srbs** [comment]
Mouse-based workaround: you can click on the parent commit hash to goto that commit.

**Comment by renattou** [comment]
It's important to say that the shortcut would be ambiguous when the commit has multiple parents (in a merge, for example). The mouse-based solution gives this option, but I don't know how it would work on the keyboard. Maybe it could always default for first parent.

**Comment by srbs** [comment]
@Zooce This should be added in build 1104

**Comment by Zooce** [comment]
@wbond I'm just curious - should I be the one to close this, or should the Sublime Text team do so? I'm not clear on the process?

**Comment by jskinner** [comment]
This was added in 1104.

NB., the navigate_to_parent command accepts a parent index via the "parent" arg, so you can bind key bindings to go to parents other than the 1st.
