### ISSUE TITLE
Visual indicator of currently checked-out branch

### ISSUE THREAD

**Issue by wickedchicken** [sublimehq/sublime_merge#333]
First off, thanks so much for Sublime Merge!

**Problem description**

Currently checked-out branch/commit isn't visually highlighted in the commit list. This makes it a bit annoying to figure out where exactly you are and what options might be available to you.

<img width="1155" alt="screen shot 2018-12-29 at 2 46 27 pm" src="https://user-images.githubusercontent.com/33220/50541708-320a6080-0b79-11e9-8373-beebbb436c35.png">

**Preferred solution**

Excuse my poor hacky photoshop:

<img width="1155" alt="screen shot 2018-12-29 at 2 46 27 pm copy" src="https://user-images.githubusercontent.com/33220/50541775-b90c0880-0b7a-11e9-9b7d-29b43df3544f.png">

Obviously you'd need to pick a different color than the 'currently selected' background used when clicking on commits ("Add day 12 solution" in this case).

**Alternatives**

An outline, or some other visual indicator! I'm not a UX person so there might be tons of alternatives out there.

**Comment by srbs** [comment]
There are a few visual indicators that aren't the most obvious:
1. the dashed line in the tree _always_ points to the currently checked out commit (be it branch, tag, detached HEAD, etc); see also #132
2. if the current commit is a branch, that branch's label is _always_ purple for dark mode & green in light mode
3. the current commit & direct-descendent (first parent) commits are _always_ blue in dark mode & pink in light mode

Note: It is a little weird that in dark mode the current branch & local branch colors are opposite the current & first tree colors, but I think that is goal of #221.

Label Colors:

  label type   | light mode | dark mode
-------------- | ---------- | ---------
current branch |   green    |  purple  
local branch   |   blue     |  blue    
remote branch  |   purple   |  green   
tag            |   yellow   |  yellow  
stash          |   orange   |  orange

**Comment by wickedchicken** [comment]
@srbs thanks for the quick response! I still feel like a stronger indicator is needed because nearly all operations depend on the currently-checked-out branch. Feel free to close this issue if you think the current indicators are enough though.

**Comment by jasonycw** [comment]
I had suggested maybe bold the current commit together with the uncommit dashed line, so when scrolling through the commit list, it is very easy to spot it.

But I think it is not the "Sublime style" so now we get the dashed line only. Maybe changing the dashed line help too?

**Comment by srbs** [comment]
> Feel free to close this issue if you think the current indicators are enough though.

I don't have permission (not a Sublime HQ dev) and I agree that there should be something a little more obvious.

**Comment by FichteFoll** [comment]
I think this has been improved significantly in the latest build, so the issue can probably be closed. @dpjohnst @wickedchicken 

![2020-10-08_13-53-26](https://user-images.githubusercontent.com/931051/95455234-d7b54b00-096d-11eb-8940-f9f8d27455a7.png)
