### ISSUE TITLE
Lost all staged changes when trying to commit

### ISSUE THREAD

**Issue by bdorfman** [sublimehq/sublime_merge#338]
**Version info**

 - OS: macOS 10.14.2
 - Build: 1097

**Description**

Twice in the last two day Sublime Merge has irrevocably destroyed all my staged changes. Luckily they weren't huge commits but this appears to be quite the serious bug. AFAICT I was simply using it as normal. I staged some changes, typed in a commit message, and hit commit. A small error popped up in the top bar that said "git failed" and then all my staged changes were completely gone with no commit being made (and thus no way to get them back through the reflog or some other method).

**Steps to reproduce**

I am not sure how to reproduce. After the first time it happened I thought maybe I had just hit discard instead of stage/commit somehow and re-wrote my code and continued using Sublime Merge. I had some changes commit successfully. Then just now it failed again in the destructive way described. I don't appear to have done anything different or unusual in the failed commits and there was no helpful error information. I usually wouldn't even bother reporting something without repro steps but this seemed serious enough that I wanted to surface it.

**Expected behavior**

Sublime Merge shouldn't delete all my changes :\

**Comment by srbs** [comment]
See also #184. I wonder if your reflog also has a `reset: moving to HEAD`.

**Comment by bdorfman** [comment]
I do also have a `reset: moving to HEAD` in my reflog! It looks like my issue is the same as the one you linked.

**Comment by wbond** [comment]
@bdorfman Would you mind adding your details to #184?
