### ISSUE TITLE
Extended attributes lost on Sublime Merge.app non-executable files when upgraded

### ISSUE THREAD

**Issue by wbond** [sublimehq/sublime_merge#34]
**Version info**

 - OS: Mac
 - Build: 1064

**Description**

When the built-in upgrader is used to update Sublime Merge, the `Sublime Merge.app` that results does not have a valid signature. This appears to be because the non-executable files in the app do not have the proper extended attributes set on them to utilize the `_CodeSignature/` folder.

This doesn't have the effect of making the application unusable since the quarantine extended attribute is no longer present.

This is likely a result of the copy that happens before the diff is applied by the `up` executable.

Originally reported at https://forum.sublimetext.com/t/invalid-code-signature-after-self-update-on-macos/39387.

**Steps to reproduce**

1. Update Sublime Merge to a newer version

**Expected behavior**

The .app should continue to have a valid signature after the upgrade.

**Comment by melomac** [comment]
According to WWDC 2019 session 701, this would become a real issue in a near future:
https://developer.apple.com/wwdc19/701

**Comment by melomac** [comment]
It looks like Sublime Merge build 1118 solves the issue:
- `com.apple.cs` extended attributes are preserved
- code signature is valid
And Sublime Merge is even notarized! Great update!

**Comment by BenjaminSchaaf** [comment]
@wbond Is this good to close?

**Comment by melomac** [comment]
Both Sublime HQ apps are now keeping their extended attributes and notarized 👏
Thanks 🙏 Good to close 👋

**Comment by wbond** [comment]
Yes, I believe this was fixed with build 1201
