### ISSUE TITLE
Change the missing commit message workflow?

### ISSUE THREAD

**Issue by greggman** [sublimehq/sublime_merge#344]
**Problem description**

If you don't enter a commit message and click the "commit" button an annoying message appears

<img width="487" alt="screen shot 2019-01-14 at 17 52 25" src="https://user-images.githubusercontent.com/234804/51103196-35fadb80-1825-11e9-90a4-1cf7a7707547.png">

It is covering the very place the user needs to see to enter a message.

**Preferred solution**

It seems like a better workflow would be, if there is no commit message then just move the cursor the commit message input area and flash the area red for a moment. Maybe that area should just say "enter commit message" when no message is there.

This would be far less annoying than having to use the mouse to dismiss the notification that's covering the commit message input area and then having to click again to make that area have the focus.

**Alternatives**

N/A

**Comment by srbs** [comment]
Also: disable the standard commit button when no message exists.

**Comment by greggman** [comment]
> Also: disable the standard commit button when no message exists.

I think I'd prefer the commit button take me to the commit message if it's empty rather than be disabled. The flat design makes the commit message area not stick out so leading the user there doesn't seem bad IMO.

I'd also argue the one line input box (yes I know it expands) encourages the bad practice of terse uninformative commit messages.

Look at most big team projects (Chrome/WebKit/LLVM/Linux/Firefox/...) and single line messages are not the norm

**Comment by dpjohnst** [comment]
Closing as this has been fixed as of Sublime Merge build 1112.
