### ISSUE TITLE
Scroll diff view to top of collapsed file

### ISSUE THREAD

**Issue by dbeckwith** [sublimehq/sublime_merge#348]
**Problem description**

When I have a bunch of long files open in the diff view, and I collapse the one currently in the center of my view, it can cause me to get disoriented because the files below it get moved way up above my current view.

**Preferred solution**

When you collapse a file, the view should scroll up so that the collapsed file is at the top of your view. I think the confusion mainly comes from the fact that the header for the file in view "floats" at the top of the screen, which I like, but it gets very confusing when I collapse it and it disappears completely because it jumped back to its proper position.

**Alternatives**

The alternative is to keep the current behavior, but my solution is much more intuitive to me, and how I've seen many other applications handle this problem.

**Screenshots**

Starting state. Lots of files, `b` has a lot of content in it.
![screenshot_2019-01-17_10-24-09](https://user-images.githubusercontent.com/1279939/51328851-43d97800-1a42-11e9-8375-312999f04f50.png)
Clicked `b` to expand it, `b`'s header is still in the normal place.
![screenshot_2019-01-17_10-24-34](https://user-images.githubusercontent.com/1279939/51328858-45a33b80-1a42-11e9-9e1b-89b4aa863d6e.png)
Started scrolling over the content of `b`. Header stays at the top of the screen, which is great!
![screenshot_2019-01-17_10-24-53](https://user-images.githubusercontent.com/1279939/51328861-46d46880-1a42-11e9-879d-65628751bc26.png)
All I did between this and the previous image is collapse `b`. Where did everything go?? The issue is that my absolute scroll position is still the same, but the whole file list has moved up.
![screenshot_2019-01-17_10-25-09](https://user-images.githubusercontent.com/1279939/51328863-489e2c00-1a42-11e9-8889-a83ebf1987c2.png)
After scrolling up, I find my files again. This is what I would expect to see as soon as I collapsed `b`. The view should automatically scroll so that `b`'s header is at the top of my screen when I collapse it (if it was floating when I collapsed it).
![screenshot_2019-01-17_10-25-32](https://user-images.githubusercontent.com/1279939/51328873-4c31b300-1a42-11e9-8c56-f37ec9af728b.png)

Let me know if any of that is confusing, I did my best to describe it!

**Comment by dpjohnst** [comment]
Hi @dbeckwith,

Thank you for using Sublime Merge!

I've been able to reproduce the issue you mentioned, and I am currently investigating it.
I will post an update here when a fix has been released.

Thanks,
\- Dylan Johnston
Software Engineer, Sublime HQ

**Comment by srbs** [comment]
Note: this was fixed quite a while back

**Comment by dbeckwith** [comment]
Confirmed this is fixed, thanks!
