### ISSUE TITLE
Does not handle worktree "gitdir: " syntax in .git file

### ISSUE THREAD

**Issue by javaJake** [sublimehq/sublime_merge#35]
**Version info**

 - OS: Windows 7 64-bit
 - Build: 1062

**Description**

When attempting to open a worktree (which has a .git file with "gitdir: " syntax), Sublime Merge complains that it "doesn't look like a git repository."

**Steps to reproduce**

1. Create a bare repository, and then create a worktree based on that bare repository.
2. Open Sublime Merge and attempt to open the worktree.
The error will appear.

**Expected behavior**

I expect Sublime Merge to open the repository and operate on it as if the directory referenced by "gitdir:" is the real .git directory and the worktree directory is the working copy location.

**Comment by wbond** [comment]
Worktree support was added in dev build 1063: https://www.sublimemerge.com/dev.

**Comment by gibwar** [comment]
**Version Info**
  - OS: Windows 7 64-bit
  - Build: 1070

**Description**
Wanted to point out that this issue isn't resolved. I've had both stable builds of 1065 and 1070 and the issue above is still the case.

**Steps to reproduce**
Full set of repro steps for Windows (Git Bash):

```sh
$ pwd
/c
$ git init repo
Initialized empty Git repository in C:/repo/.git/
$ cd repo
$ touch file.txt
$ git add file.txt
$ git commit -m "Initial Commit"
[master (root-commit) d29f0df] Initial Commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 file.txt
$ git branch other
$ git worktree add ../other other
Preparing ../other (identifier other)
HEAD is now at d29f0df Initial Commit
$ git worktree list
C:/repo   d29f0df [master]
C:/other  d29f0df [other]
$
```
Opening the repo at `C:\repo` works just fine, but opening `C:\other` nets me

> ```text
> ---------------------------
> Sublime Merge
> ---------------------------
> C:\other doesn't look like a git repository
> ---------------------------
> OK   
> ---------------------------
> ```

**Comment by wbond** [comment]
@gibwar you should open a new issue about the trouble you are running into.

**Comment by jskinner** [comment]
@gibwar I believe that issue has been fixed in builds 1075 and later
