### ISSUE TITLE
search by branch 

### ISSUE THREAD

**Issue by yalelo** [sublimehq/sublime_merge#352]
**Problem description**

When having many branches (dev, prod,etc), the search will often show too many confusing results (same commit cherry-picked to multiple branches + all stashed commits, for instance). 
It would be great if we were able to filter search results to only show commits within a specific branch.

**Preferred solution**

1/ Allow a `branch:"XXXXX"` keyword in the search bar.
2/ By default (when hitting Ctrl+F), the search bar should be pre-filled with the current branch.
3/ By default, do not show stashed commits (add an option to enable it)

**Comment by polocco** [comment]
vote for this topic

**Comment by dominik-skorka** [comment]
Yes, definitely I'd appreciate filtering by a branch. It's so much quicker to type rather to click. Especially in big projects.

**Comment by psimek12** [comment]
Věry well! 👍

Dne út 28. 9. 2021 6:58 uživatel Dylan Johnston ***@***.***>
napsal:
