### ISSUE TITLE
Kotlin syntax highlighting

### ISSUE THREAD

**Issue by toXel** [sublimehq/sublime_merge#356]
**Problem description**

Kotlin syntax is not highlighted.

**Preferred solution**

Add support for Kotlin syntax highlighting.

**Comment by srbs** [comment]
This report should be moved to the default packages repo: https://github.com/sublimehq/Packages

**Comment by keith-hall** [comment]
see https://www.sublimemerge.com/docs/packages#installing_packages

**Comment by wbond** [comment]
I don't think we are planning on adding support for Kotlin out-of-the-box. Looks like you'll want to install https://packagecontrol.io/packages/Kotlin. If you don't use Sublime Text, you can use the directions that @keith-hall linked to.
