### ISSUE TITLE
Custom commands do not launch external editor

### ISSUE THREAD

**Issue by stinos** [sublimehq/sublime_merge#357]
**Version info**

 - OS: Windows 10
 - Build: 1102 and earlier

**Description**

Cutsom git commands which should launch a text editor, like rebase --interactive, don't show the text editor but do execute somehow.

**Steps to reproduce**

1. In Default.sublime-commands add
```
  {
    "caption": "rebase -i",
    "command": "git",
    "args": {"argv": ["rebase", "--interactive", "$commit"]}
  },
```
2. Edit .gitconfig to setup an editor, any of the following reproduces the problem for me:
```
[core]
	editor = \"c:/program files/GitExtensions/GitExtensions.exe\" fileeditor
	editor = 'c:/program files/sublime text 3/subl.exe' -w
```
3. Verify this config is available in Sublime Merge: click Help->Debug Information, paste the clipboard text and check it contains the configured editor from step 2 e.g. somethigg like
```
=== Git Config Information ===
...
core.editor='c:/program files/sublime text 3/subl.exe' -w
...
Our config output is identical to the Git config output
....
```
3. Open a repository, select a commit, Ctrl-P, choose 'rebase -i'

**Expected behavior**

This should start the selected editor to allow editing the rebase steps. Instead the command is executed and succeeds without having shown the text editor (not even sure how that is possible, I thought when a win32 process is launched with SW_HIDE it still allows launching other processes with a window), and hence without having changed commits; unless there happened to be fixup commits or even squash commits, the latter also executed silently. Command output is like this:

```
Last Command  git rebase --interactive 8a548281b9de36dd1384781accd6dbf0492eb8ca
Status  Success
Successfully rebased and updated refs/heads/master.
```

**Comment by wbond** [comment]
The reason for this, I believe, is that various commands we run for built-in functionality need to not get stuck waiting for user input, since there obviously isn't a terminal to accept it via.

For custom git commands that require user interaction, a terminal is going to be your best bet.

**Comment by stinos** [comment]
Fair enough, but imo then interactive rebasing (the real thing, not 'squash commit with parent') should really be possible with Sublime Merge in some way. Or at least a way to open a terminal so that we don't have to open it manually in the correct diorectory. Actually I find it hard to grasp that Sublime Merge basically does git right on every single front, has good customization etc but does not have single a way (unless I missed something) to do interactive rebase which is a major git feature. I think. Don't know, maybe I'm biased beacuse I use that multiple times everyday..

**Comment by jskinner** [comment]
What interactive rebase functionality do you feel is missing?

Under the Edit Commit menu we have Edit Commit Message, Edit Commit Contents, Squash with Parent, Squash Selected Commits, Move Commit Up, Move Commit Down, and Drop Selected Commits.

**Comment by stinos** [comment]
Sorry should have been more clear. Yes the functionality itself is there, but it's an insane amount of point/click/type to use those for anything but a couple of localized commits. For example for a fairly typical rebase of a couple of hours of work I start with
```
pick 1c9ff1c
pick 841cccd
pick 8276df5
pick eecc09b
pick 6614142
pick ea0fb5b
pick 4e3435b
pick 19e8988
pick 4385224
```

which with a text editor is turned into this in no time:

```
r 1c9ff1c
f 4e3435b
f 19e8988
f 4385224
pick 841cccd
e 8276df5
f ea0fb5b
pick eecc09b
r 6614142
```

whereas with Sublime Merge just moving those fixup commits would need repeating the 'Move Commit Up' 5 times, in the meantime losing oversight of what goes where.

**Comment by FichteFoll** [comment]
I'm quite sure you can squash and fix up commits that aren't adjacent, but I can't confirm this right now.

Regardless, I like the interactive rebase because of autosquashing "fixup!" commits and that workflow isn't currently available.

**Comment by marcinsmialek** [comment]
While I can select 2 commits and pick squash (fixup) from menu, it would be good if it was possible to auto fixup, or at least make it enough to right-click only the fixing or fixed commit

**Comment by dpjohnst** [comment]
Hi all,

Just a quick update - this has been added in the latest development build (2034) and will be available in the next stable build.

Kind regards,
\- Dylan

**Comment by stinos** [comment]
@dpjohnst I'm on Windows and the path to the editor is configured or launched incorrectly, without quotes; could be that it is a configuration problem on my system though.

Here's the command I have in Commit.sublime-menu:
```
  {
    "caption": "rebase -i",
    "command": "git",
    "args": {"argv": ["rebase", "-i", "$commit"]}
  }
```

resultin error:

```
/C/Program Files/Sublime Text 3/sublime_text.exe --wait: /C/Program: No such file or directory
error: There was a problem with the editor '/C/Program Files/Sublime Text 3/sublime_text.exe --wait'.
```

I'm using system git, note in the debug information I have this (which is from my git config):

```
core.editor='C:/Program Files/Sublime Text 3/subl.exe' -n -w
```

so I assume the failing command comes from SM? Ideally it should respect the core.editor value?

**Comment by FichteFoll** [comment]
I assume it always opens ST for editing interactive sessions, but can I configure SM to open a new ST window with the file to be edited (`-n`)?

**Comment by dpjohnst** [comment]
Hi all,

This is now fully supported on all platforms in the latest Sublime Merge builds (2037 dev/2038 stable).

I'll close the issue now as it has been resolved. For all feedback relating to this feature, please feel free to open a new issue/enhancement request on the issue tracker.

Cheers,
\- Dylan

**Comment by dpjohnst** [comment]
PS @FichteFoll in case you haven't resolved this, you can customize the `editor_wait_args` (available under Preferences > Editor) to include any custom flags.

**Comment by FichteFoll** [comment]
Thanks for the note, I added `--new-window` to that.
