### ISSUE TITLE
No obvious way to checkout remote branch

### ISSUE THREAD

**Issue by Digital-Monk** [sublimehq/sublime_merge#360]
I had a freshly cloned repo that only had one local tracking branch in it.  I wanted to checkout a different branch that I knew was on the origin repo, but the checkout tool didn't provide this option.

Once I dropped to a command shell and issued 'git checkout nameOfRemoteBranch', git created a local tracking branch and everything was fine.  It would be nice if the checkout tool also listed origin branches that were not yet locally tracked.

I see there are other issues to simplify working with remote branches, but (and maybe I'm just blind) I'm not seeing the tool/menu for listing remote branches at all.

**Comment by omertuc** [comment]
I've discussed something similar [here](https://forum.sublimetext.com/t/quick-way-to-checkout-remote-branch-after-fetch/41569)

**Comment by jskinner** [comment]
You can view remote branches either via the sidebar (the leftmost icon on the toolbar), or via the Command Palette (Ctrl+P on Linux and Windows, Cmd+P on Mac). From the Command Palette, you can use either "Checkout Remote Branch" or "Create Branch From Remote Branch"
