### ISSUE TITLE
Extending custom theme from build in themes

### ISSUE THREAD

**Issue by Helfull** [sublimehq/sublime_merge#365]
**Version info**

 - OS: Windows 10
 - Build: 1103

**Description**

Having the custom theme `test.sublime-theme`.
```json
{
    "extends": "Merge Dark.sublime-theme"
}
```
I would like to have the Dark theme and the ability to modify the theme.
Right now it does get a bugged out version of the Dark theme.
![image](https://user-images.githubusercontent.com/720645/52084292-07f5f500-25a2-11e9-87e7-85ffffc3ea1d.png)

`Preferences.sublime-settings`
```json
{
	"font_face": "Fira Code medium",
	"font_size": 11,
	"line_padding_bottom": 5,
	"line_padding_top": 5,
	"theme": "test.sublime-theme",
        "hide_menu": true
}
```

**Steps to reproduce**

1. Create a new theme
2. Paste the code snippet into the theme
3. Set the theme within the Preferences.sublime-settings to the fresh created theme

**Expected behavior**

Have the extended theme.

**Comment by jskinner** [comment]
There are other things that need to be done for this approach to work, most notably making a "Diff - test.sublime-settings" to assign the color scheme used for diffs (Mariana to match Merge Dark). Currently test.sublime-theme is pulling some colors from the color scheme used in the diffs, which is unassigned, and thus has a white background.

However, a better approach is to just make an override file for Merge Dark that has just the changes you want. Put this file in your Packages/User directory as `Merge Dark.sublime-theme`:

```
{
    "variables":
    {
        "file_header_bg": "#999900",
        "file_header_bg-hover": "#aaaa00",
    },
    "rules":
    [
    ]
}
```
