### ISSUE TITLE
Font size for diffs is too big

### ISSUE THREAD

**Issue by olablt** [sublimehq/sublime_merge#366]
**Version info**

 - OS: Fedora 27
 - Build: 1102

**Description**

When I change the font size in the settings, the Diff font size is still big

**Steps to reproduce**

1. Open repository ...
2. View the Diff

**Expected behavior**

Expect the font size to bee like in the settings

**Screenshots**

![image](https://user-images.githubusercontent.com/674574/52126018-d8dd9300-2636-11e9-8bf9-54e07c536ad4.png)

**Comment by jskinner** [comment]
You can choose a smaller font size via the preferences dialog.

**Comment by olablt** [comment]
what do you mean? I wrote in the description that the preferences dialog had no effect on diff font size.
