### ISSUE TITLE
Clone Repository fails with WinError 128

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#368]
**Version info**

 - OS: Windows 10 x64 1803
 - Build: 1102

**Description**

SM fails cloning a repository with error 128 (again). It seems to have trouble setting the destination path.

I can't clone the `folder-aliaser` as is into Packages nor can I change the destination folder to ask SM to clone it into _Folder Aliaser_ folder as I did via console.

Related: #277, #355

**Steps to reproduce**

1. Open SM
2. Run _Clone Repository_ command
3. Enter an URL and a destination path
4. Press Clone

**Expected behavior**

The requested repository should be cloned.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/52164483-574b3b00-26f2-11e9-8314-c714ded63d8a.png)

Cloning via console works.

![grafik](https://user-images.githubusercontent.com/16542113/52164495-882b7000-26f2-11e9-803d-b92ebc63f958.png)

**Comment by jskinner** [comment]
This is working as intended - when a full path is given in the destination field, we clone into that path exactly.

However, if you put a trailing slash in the destination path, it will automatically append the repo name (you can see this in action via the ghosted text that gets added after the trailing slash). If you use the "..." button to browse for a directory, the trailing slash will be automatically added
