### ISSUE TITLE
support two column view for reviewing files

### ISSUE THREAD

**Issue by cppforlife** [sublimehq/sublime_merge#37]
**Problem description**

When committing it's hard to glance which files have been staged. This is true especially when you have a decent number of changes and you are trying to split it off into smaller commits.

**Preferred solution**

I would love if Sublime Merge provided a view similar to the following found in products such as Sourcetree:

![SourceTree screenshot](https://www.sourcetreeapp.com/dam/jcr:b6ec8a39-5a98-4e28-842b-f9198824fe74/commit_with_confidence.png)

Benefits:

- easy to view which files are staged or not
- view is compact
- allows to stage particular lines hence file shows up in two places: staged and unstaged
- allows intuitive keyboard navigation to move between files, and familiar select all files via cmd+a feature as well

**Comment by Ujinjinjin** [comment]
Yeah, would be really usefull feature

**Comment by risperdal** [comment]
that would be usefull

**Comment by dpjohnst** [comment]
Closing this request, as we have had a files tab for quite some time now.
