### ISSUE TITLE
Add ellipsis for long file names in unstaged files panel

### ISSUE THREAD

**Issue by cixtor** [sublimehq/sublime_merge#372]
**Problem description**

The “unstaged files” panel shows a list of files that have been added, modified or deleted. When the file path is very long, and the window frame is small, the buttons “Discard” and “Stage” obstruct the visibility of the last portion of the filename, making some operations unintuitive because we cannot see what file is actually being referenced.

**Preferred solution**

Replace a portion of the filename with the ellipsis.

**Alternatives**

Allow the panel containing the file path to scroll horizontally.

**Screenshots**

| Current UI | Proposed UI |
|------------|-------------|
| ![long-lines-old](https://user-images.githubusercontent.com/1933999/52381119-27b76e00-2a25-11e9-98e1-2fbcf2b67075.png) | ![long-lines-new](https://user-images.githubusercontent.com/1933999/52381129-2f771280-2a25-11e9-8ed1-b668e066f271.png) |

Notice how this list of files:

```
.aliases
.bashrc
Library/Application Support/Sublime Text 3/Installed [discard] [stage]
Library/Application Support/Sublime Text 3/Installed [discard] [stage]
Library/Application Support/Sublime Text 3/Installed [discard] [stage]
Library/Application Support/Sublime Text 3/Installed [discard] [stage]
```

… becomes this:

```
.aliases
.bashrc
Library/.../0_package_control_loader.sublime-package [discard] [stage]
Library/...talled Packages/FileIcons.sublime-package [discard] [stage]
Library/...3/Installed Packages/LESS.sublime-package [discard] [stage]
Library/... 3/Installed Packages/LSP.sublime-package [discard] [stage]
```

**Comment by greggman** [comment]
I'd prefer horizontal scrolling. Cutting out data means I can't actually use sublime merge to select files since the part of the file name I need to know may be hidden by the ellipsis
