### ISSUE TITLE
Manual typing of destination path doesn't take effect when cloning repository.

### ISSUE THREAD

**Issue by devsedo** [sublimehq/sublime_merge#376]
**Version info**

 - OS: macOS 10.13.6
 - Build: 1103

**Description**

Manual typing of destination path doesn't take effect when cloning repository.
Changing path by pressing three dots and choosing a folder works OK.

**Steps to reproduce**

1. File -> Clone Repository.
2. Type in / paste repository url.
3. Change destination path by typing any combination of letters / slashes (nesting into a folder, etc.).
4. Press Clone.

**Expected behavior**

Cloning goes into chosen folder.

**Screenshots**

- Default state.
![before-path](https://user-images.githubusercontent.com/20434221/52458514-6c144c80-2b92-11e9-899f-b49c46699534.png)

- Destination path is changed by typing in manually (it can be either different folder or even different name).
![correct-path](https://user-images.githubusercontent.com/20434221/52458537-8d753880-2b92-11e9-987a-1e34081e836b.png)

- Cloning goes into wrong path.
![wrong-path](https://user-images.githubusercontent.com/20434221/52458563-b4336f00-2b92-11e9-9e56-7d10a383c660.png)

**Comment by 13xforever** [comment]
Also an issue on Windows

**Comment by srbs** [comment]
@devsedo / @13xforever Is this still an issue with dev build 1104?

**Comment by jskinner** [comment]
This was fixed as part of the clone dialog refresh in 1104
