### ISSUE TITLE
Sublime crash after closing the program with unsaved changes

### ISSUE THREAD

**Issue by shaylempert** [sublimehq/sublime_merge#378]
**Version info**

* OS: Ubuntu 18.04.1 LTS x86_64
* Build: 3176

**Description**

Sublime started crashing on startup after I closed the program with unsaved changes. I don't know how it happened, but deleting sublime-text-3/Local/Session.sublime_session solved the problem.
**Steps to reproduce**

IDK

**Expected behavior**

Sublime opens but doesn't allow you to do anything and quickly crashes.

**Comment by srbs** [comment]
@shaylempert, this issue tracker is for Sublime Merge not Sublime Text. Please close this and create it in the Sublime Text [issue tracker](https://github.com/SublimeTextIssues/Core/issues).
