### ISSUE TITLE
Tag, Commit & Merge Sign Verification in UI

### ISSUE THREAD

**Issue by pshelly** [sublimehq/sublime_merge#38]
**Problem description**
Sublime Merge doesn't show when tags commits or merges are signed. This is particularly useful to check for unwanted/unauthorized commits.

**Preferred solution**
Something like github's approach of a verified icon:
![image](https://user-images.githubusercontent.com/43761801/46310507-92dfc800-c58d-11e8-8c9a-1eac9c2239d0.png)
[https://blog.github.com/2016-04-05-gpg-signature-verification/](url)

Also maybe a filter for verified and unverified tags commits or merges?

**Comment by jskinner** [comment]
Build 2020 implements GPG signature verification
