### ISSUE TITLE
Add ability to stage multiple files at once.

### ISSUE THREAD

**Issue by safield** [sublimehq/sublime_merge#381]
Other git gui I have used, offer the ability to shift+click or ctrl+click to highlight multiple files, and then stage them all at once.

In addition, batch selecting could be applied to different operation. I could select a batch of files and discard, etc.

Sublime Merge lacks this ability currently, and I think it is huge hindrance to usability.

**Comment by wbond** [comment]
Wouldn't that involve one more click than just clicking stage for each file?

**Comment by safield** [comment]
No, think a normal file list in OS file explorer.

If I wanted to stage twenty contiguous files, the action would be as follows...

hold shift
left click top file
left click bottom file
click stage

That is 4 actions, whereas in sublime that would be N actions, where N is the file count.

It would be the same amount of actions when ctrl adding files, then staging. But ctrl clicking still has benefit.

The most substantial benefit is that shift and ctrl clicking to add files to selection is an ubiquitous action in every file manager I have ever used (on Windows and Linux), so I feel like it is an expected feature, even outside the context of a file manager.

PS. Shift clicking because exponentially more powerful when you can parse the changed files list by regex. eg supply *.xml to show only xml files, then shift click to stage all of the xml files.

**Comment by wbond** [comment]
Thanks for adding addition context and ideas to your request!

**Comment by safield** [comment]
I updated the title and initial post to reflect the fact that this feature is not specific to just staging.
I had to do a bunch of discards today, and I had to open up GitExtensions to get it done.

**Comment by safield** [comment]
I just had to stage some spine assets with thousands of sprites. My mouse broke. Had to drop down to command line just to stage files.

**Comment by genericptr** [comment]
Here's an example of the problem I faced. I would be so easy to enable a multiple selection in the list. It's no-brainer in my opinion.

![Screen_Shot_2020-10-24_at_11 20 49_AM](https://user-images.githubusercontent.com/10937186/97186649-2f71f580-1767-11eb-9b1c-fc78b7d8c822.png)

**Comment by dabinat** [comment]
+1 for this. I just deleted a folder with quite a lot of files in it and had to go through and stage the deletion of each file individually. What could have been two clicks ended up being about 50.

**Comment by spaskalev** [comment]
I'd like to see multi-select of files with a context menu of open in sublime. My workflow involves a review repo (e.g. gitlab, gerrit) and some changes have been reviewed the files might need further changes. Instead of doing `git show --name-only --pretty="" | xargs subl'` I'd like to be able to this in smerge.

**Comment by dawilson9** [comment]
+1 on this feature for me. The fact that I can only stage individual files or all files is a real annoyance to me when I frequently need to generate multiple commits containing groups of files all generated by a single build. Staging each file individually isn't workable for me. As things stand, I'm having to move back to GitHub Desktop to do this but it would be fantastic if I could finally do all my git work in a single tool!

**Comment by CaptainCrowbar** [comment]
I'll add my +1 to this.

**Comment by MathieuLorber** [comment]
The app is really great but this missing feature really stops me to migrate from my current git client. We generate lots of files (& commit them on purpose), being unable to select them with "classic" expected native cmd+click / shift+click selection is disappointing.

**Comment by kg-currenxie** [comment]
Same. Hard to fully switch.. Would pay for a license if this was implemented <3

**Comment by dpjohnst** [comment]
Hi all,

Thanks for sharing your feedback!

We've added multi-select to the files tab in Sublime Merge Build 2080 (development). This allows you to stage / unstage / discard multiple files at once.

Kind regards,
\- Dylan from Sublime HQ

**Comment by dpjohnst** [comment]
Hi again,

This has now been added to Sublime Merge Build 2083 (stable).

Cheers,
\- Dylan from Sublime HQ
