### ISSUE TITLE
Show entire file diff setting.

### ISSUE THREAD

**Issue by safield** [sublimehq/sublime_merge#383]
It would be nice to have a setting that would enable diff views to show the entire contents of the file in diff view, instead of just isolated chunks.

This would work for both side by side and inline view.

I prefer this way, as it gives me the ultimate birds eye view of changes, and the context of them.

Alternatively, it would also be nice to have a popout window to fullscreen diff files.

**Comment by Zooce** [comment]
It would be cool to have a quick toggle button to do this on-the-fly as well, like if I wanted to just quickly see a lot of context around whatever chunk I was looking at.

**Comment by Novack** [comment]
Hey, a personal note, this is sorta must-have for me, I dont feel confortable at all with the hunks. Other than that... what a great git client!

**Comment by tajmone** [comment]
I may add, it would be also nice to be able to control which diff elements are important or not (e.g. being able to mark comments differences as non-important). This is a cool feature in BeyondCompare 4, called "Text Compare Importance Settings":

https://www.scootersoftware.com/v4help/

I find it very useful when working on large source code projects, for it allows me to selectively ignore some elements (comments, strings, etc.). Possibly, because SM relies on ST syntaxes, it should be possible to customize which semantically scoped elements should be excluded from diffing (again, usually being able to exclude comments is the most important use of this feature, but also strings and other elements, depending on the syntax at hand).

**Comment by gshultz21** [comment]
I would also find full-file side-by-side diffs to be very useful.  Hunks don't provide full context.  Thanks.

**Comment by urzq** [comment]
Same here !

**Comment by joaoe** [comment]
Could e at least change the number of lines of context ? 3 lines just does not cut it.

**Comment by srbs** [comment]
@joaoe, if you didn't know, you can drag the context borders to show more or double click the bottom or top borders to get 10 extra lines. It's not ideal as you probably want it globally, but it can help for now.

**Comment by joaoe** [comment]
@srbs Thank I know that. With a big diff with many small changes, that feature is unusable. And the hitboxes are small.

**Comment by coob** [comment]
This feature is must have if you at least sometimes do peer code review. Sometimes it's hard to understand the context seeing only a hunk.

**Comment by GertVanKruiningen** [comment]
Yes please, a full file review/comparison would be very usefull thanks !!!

**Comment by lionah** [comment]
Now that we have separate tabs for each file, I think it makes even more sense to have this feature. It would be great if we could have a pref option to always show the full file in the file tab. If you wanted to be real fancy, it would already be scrolled to the first change and perhaps add prev/next buttons for egregiously large files.

**Screenshots**

What we see now:
<img width="1360" alt="Screen Shot 2020-06-19 at 9 52 05 AM" src="https://user-images.githubusercontent.com/862303/85159919-f94dc380-b212-11ea-9e15-67a233ff2b29.png">


What I like to see:
<img width="1469" alt="Screen Shot 2020-06-19 at 9 53 24 AM" src="https://user-images.githubusercontent.com/862303/85159934-fe127780-b212-11ea-868d-db269f3da057.png">

**Comment by Phaiax** [comment]
I want to see this feature, too

A second thing which I would like to amend here:
Seeing through submodules when doing the diff.
(Like `git config diff.submodule diff` then `git diff ...`)

My forum comment https://forum.sublimetext.com/t/feature-request-option-to-show-whole-file-contents-in-diff-view/52808/2

**Comment by srbs** [comment]
@Phaiax, I would recommend creating another enhancement request for that.

**Comment by dpjohnst** [comment]
Hi all,

This has been added in Sublime Merge development build 2028 :tada: 

Kind regards,
\- Dylan

**Comment by tajmone** [comment]
> This has been added in Sublime Merge development build 2028

`2028`? My current dev build is `3210`, aren't ST3 build supposed to start with a `3`?

**Comment by jfcherng** [comment]
here's sublime merge issue tracker. not sublime text's.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/89701691-de264700-d96b-11ea-9d44-31296608d907.png)

It took me a while to find this in 2028.

**Comment by dpjohnst** [comment]
Added in Sublime Merge Build 2032 (stable build) 🎉
