### ISSUE TITLE
Commit file view should be collapsed by default.

### ISSUE THREAD

**Issue by safield** [sublimehq/sublime_merge#386]
Currently when browsing through commits (or current working directory), the changed file diff views on the right will be expanded by default.

I think it would be much more desirable to have these collapsed by default. This way the user could get a birds eye view, and then expand the specific files to inspect the diff if he chooses.

I don't see any logical benefit to having these changed file diff views expanded by default.

**Comment by jskinner** [comment]
It depends on the sort of commit you're looking at: sometimes commits are small, and the entire set of changes can comfortably fit on one screen, in which case it's desirable to show the files expanded by default.

If you're only interested in the file names on the first pass, then you can show the Contents tab in the sidebar.

**Comment by safield** [comment]
That is the underlying flaw of SM ui design. There is this awkward duality between the contents view and the commit view on the right side. Each do half of the jobs of one view. If I want to have a nice easy view to stage files with one click....the commit view is best. If I want to see a birds eye view of the files, contents view is best. If I want more advanced operations like navigate to file, I have to use contents view. I never feel comfortable in either view  and overall I am clicking my mouse much more than other git gui clients. This needs to be rethought.

What if I want to select and stage multiple files at once? Which view will be chosen at random to take on that behaviour. This problem will only become more and more prominent as more behaviours are added in.

**Comment by chrisjbillington** [comment]
The contents view is completely redundant, its removal would simplify the UI considerably, and prevent a lot of the confusion I've been hitting. Integrate it into the commit view, and collapse diffs by default if the diff is too large to fit on the screen (i.e most of the time). Display summary of number of lines changed on each file in the view. Then no more contents view - the user can then hide the side pane most of the time until they want to list tags or remotes or whatnot.
