### ISSUE TITLE
Undo pull

### ISSUE THREAD

**Issue by communistkiro** [sublimehq/sublime_merge#392]
**Problem description**

I got an idea on how to fix some issues on project I'm working on, fixed them as usually do- several files- working, testing versions, no external version control. After everything worked, deleted old versions and decided to force push to git to have a copy of a working thing. Opening Merge, it **automatically** downloaded everything, overwriting everything. Having the 2 important files open, a CTRL+Z reverted their states, but 1 file with 1 month's worth of data was lost. And since the output file was overwritten, I can't even manually reenter the data. 

**Preferred solution**

An undo button, where the action of pulling actually have be reverted.
Preferences to not pull from the repo on startup- some people like to work offline and without Merge turned on.
A message box asking you if you want you current working dir destoryed.

**Comment by jskinner** [comment]
Sublime Merge does not pull automatically, neither on startup nor periodically, FWIW
