### ISSUE TITLE
dpi_scale settings is ignored

### ISSUE THREAD

**Issue by naringas** [sublimehq/sublime_merge#399]
**Version info**

 - OS: Linux 4.19.23-1-MANJARO #1 SMP PREEMPT Fri Feb 15 21:27:33 UTC 2019 x86_64 GNU/Linux
 
 - Build: Sublime Merge Build 1103

**Description**

on a HiDPI display with KDE Plasma Sublime Merge ignores it's dpi setting from its own configuration file:

```
{
	"dpi_scale": 1.5
}
```

**Steps to reproduce**

1. open sublime merge
1. click "Preferences -> edit settings"
1. add `"dpi_scale": 1.5`, save and restart sublime mege
1. sublime merge looks the same size.

**Expected behavior**

sublime merge looks slightly bigger

**Screenshots**

<img width="671" alt="smerge bug" src="https://user-images.githubusercontent.com/566811/53265617-4d3eab80-36a4-11e9-8c18-4ecf13e4e7ca.png">

**Comment by jskinner** [comment]
`ui_scale` is the name of the setting you're after. `dpi_scale` no longer exists since the port to GTK3.
