### ISSUE TITLE
clean_working_dir does not remove untracked files in sub directories.

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#4]
**Version info**

 - OS: Windows 10
 - Build: 1062

**Description**

As the title already says, the `clean_working_dir` alias `git clean -f` removes all untracked files located in the top-level of the working directory. If a file is located in any sub directory it remains there.

**Steps to reproduce**

1. Open a repository
2. Add a dummy file in a new sub directory `newsub/subsub/foo.json`
3. Run "Delete All Untracked Files..." from command palette

**Expected behavior**

No more unchanged files should remain in the working directory.

Looks like `git clean -d -f` is required to do that.

**Comment by wbond** [comment]
This should be resolved in the next build

**Comment by deathaxe** [comment]
Confirmed
