### ISSUE TITLE
Cherry pick with --no-commit option

### ISSUE THREAD

**Issue by vdimir** [sublimehq/sublime_merge#406]
**Problem description**

In some cases changes from particular commit is needed, but commit not required. Current solution is cherry pick and reset branch to previous commit. It is require additional step.

**Preferred solution**

Add `--no-commit` to cherry pick options as other command options (e.g. for pull we can choose `--rebase`, `--no-ff` etc)

**Alternatives**

Add cherry-pich-no-commit to context menu (as reset can be soft, mixed, hard).

**Comment by deathaxe** [comment]
SM 2xxx implements this feature. The issue can be closed.
