### ISSUE TITLE
Long log message (first line) breaks rebase log message/display.

### ISSUE THREAD

**Issue by svendhhh** [sublimehq/sublime_merge#407]
**Version info**

 - OS: Windows 10
 - Build: 1103

**Description**
When a long log message first-section/title has been entered and a rebase is then performed, the log window is broken.

**Steps to reproduce**

1. Be in a branch where the remote is ahead.
2. Make a commit with a very long first section. This can be on several lines, but with no blank lines inbetween.
3. Perform a rebase.
4. Open the log to see the output from the rebase.
5. Notice that the log is broken and the beginning and end cannot be seen.

**Expected behavior**

The entire log should be visible, or at the least it should be possible to scroll.
Breaking/wrapping long lines would be ideal.

**Screenshots**

![image](https://user-images.githubusercontent.com/5302311/53795557-85f74400-3f32-11e9-9c0b-b01b2b3bf68d.png)

**Comment by willrowe** [comment]
This is related to #538, #343, and #658.

**Comment by dpjohnst** [comment]
Hi @svendhhh,

This has been fixed as of Sublime Merge Build 2002 (Dev)

Cheers,
\- Dylan

**Comment by willrowe** [comment]
I can confirm that this is now working in build 2002.
