### ISSUE TITLE
Unable to revert merge commit

### ISSUE THREAD

**Issue by erazor-de** [sublimehq/sublime_merge#409]
**Version info**

 - Fedora 27
 - Sublime Merge Build 1106

**Description**

If I press "Revert Commit" on a merge commit the command "git revert --no-commit ..." is issued which fails on merge commits because of missing -m option.

You might add a possibility to specify the parent and additionally add a ["reverting a merge is no undo"](https://github.com/git/git/blob/master/Documentation/howto/revert-a-faulty-merge.txt) warning.

**Comment by jskinner** [comment]
Revert Commit now passes -m for merge commits (always with -m 1, to match the display within Sublime Merge) in 1116
