### ISSUE TITLE
Ubuntu installation for 64 bit systems only?

### ISSUE THREAD

**Issue by ace280** [sublimehq/sublime_merge#410]
It seems to me that sublime-merge can not be installed on a Linux 32 bit system. 

Even though I set up apt correctly I am getting a package not found error.

![image](https://user-images.githubusercontent.com/25365744/54283233-e07d4980-459d-11e9-94c6-d89bf4a92bb5.png)

I suspect that there is no package for a 32 bit system. This is not entirely bad, but, imho it should be noted somewhere.

**Comment by TeamSpen210** [comment]
It's mentioned on the [download page](https://www.sublimemerge.com/download):
*Sublime Merge is available for 64 bit platforms only.*

**Comment by ace280** [comment]
True. Sorry, I must have overlooked this.
