### ISSUE TITLE
cannot edit commit message inside a worktree

### ISSUE THREAD

**Issue by paul2t** [sublimehq/sublime_merge#412]
**Version info**

 - OS: Windows 10
 - Build: 1107

**Description**

Cannot edit commit message inside a worktree.

**Steps to reproduce**

1. Open worktree folder of a repository (not the main worktree with the .git directory inside)
2. Right click on a commit
3. Edit commit message
4. Click on Save
=> The message is changed in the window, but not in the history. If you click on a commit and come back on this same commit. The commit message is restored back to its original value.

**Expected behavior**

The commit message should be changed.

**Comment by jskinner** [comment]
Thanks for the report, this is fixed in 1116
