### ISSUE TITLE
staging removed objects don't work

### ISSUE THREAD

**Issue by ehahnks** [sublimehq/sublime_merge#413]
---
name: Bug report
about: staging removed objects

---

**Version info**

 - OS: [e.g. CentOS]
 - Build: [e.g. 3.10.0-957.5.1.el7.x86_64, git version 1.8.3.1]

**Description**

Deleted items can not be staged about "Stage" Button on its line.

**Steps to reproduce**

1. Open repository
2. commit file to repo
3. remove file from harddisk
4. try to stage removing of the file
5.E xecuting "git rm filename" in terminal adds the file to Staged Files list.

**Expected behavior**

click on "Stage" should add the removed file to Staged Files list.

**Comment by jskinner** [comment]
This is working correctly.

When deleting a file in Git, the deletion must be staged, and then committed for the deletion to be part of the repository history.

**Comment by jskinner** [comment]
Note that you are using a very old version of git, and I believe the command line interface to staging deleted files has changed between 1.8 and the current versions.

Sublime Merge does not support git 1.x
