### ISSUE TITLE
Sublime_merge.exe crashes when BitDefender feature is enabled

### ISSUE THREAD

**Issue by jdgregson** [sublimehq/sublime_merge#414]
**Sublime Merge, Stable Channel, Build 1107**

 - OS: Windows 10 Pro x64 version 1809
 - Build: 1107

Sublime_merge.exe fails to start when "Advanced Threat Protection" is enabled in BitDefender Total Security 2019. Disabling the feature or adding an exception for sublime_merge.exe allows it to start. An application error is logged in the Event Viewer when this issue occurs:

```
Faulting application name: sublime_merge.exe, version: 1.0.0.1, time stamp: 0x5c883b25
Faulting module name: ntdll.dll, version: 10.0.17763.348, time stamp: 0xca65c822
Exception code: 0xc0000409
Fault offset: 0x000000000008fb3f
Faulting process id: 0x420
Faulting application start time: 0x01d4d9dd7afe66d3
Faulting application path: C:\Program Files\Sublime Merge\sublime_merge.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 03f30178-9457-4469-bf8a-b5336dfd57d3
Faulting package full name: 
Faulting package-relative application ID: 
```
**Important:** This also affects the newest build of Sublime Text 3 (sublime_text.exe), since it implements some of Sublime Merge's features.

**Steps to reproduce**
1. Install BitDefender Total Security 2019.
2. Confirm that "Advanced Threat Protection" is enabled in BitDefender.
3. Attempt to start Sublime Merge.

**Expected behavior**
The expected behavior is that Sublime Merge starts whether or not it is being monitored by BitDefender.

**Comment by stinos** [comment]
Isn't this rather a problem with BitDefender? Depends on what exactly BitDefender does here: is it really merely 'monitoring' (and what does that entail?) or is it injecting/hijacking some dlls? In the latter case it's tempting to say it's a BitDefender problem, not a Sublime one.

**Comment by jdgregson** [comment]
While I agree that there is a good chance this is a Bitdefender issue, I also think it's important to point out that I've found no other software that is incompatible like this. There is something unique to Sublime Merge which renders it incompatible, specifically. 

As for what Advanced Threat Defense actually does, I can't say for certain. I would suspect that it does inject a DLL, but then again, so does the main "Bitdefender Shield" realtime anti-virus component of Bitdefender without causing any issues. Their [published documentation](https://www.bitdefender.com/consumer/support/answer/2024/) is naturally geared more towards marketing than technical details.

Is there a debugging tool I can use to get a better idea of what Bitdefender is doing to the process? I could load up the previous build of Sublime Text and get a snapshot of the memory layout with Advanced Threat Defense on and with it off, which should give you a picture of what's different and might be tripping up Sublime Merge.

Clarification: what I've been calling "Advanced Threat Protection" is actually called "Advanced Threat Defense".

**Comment by jskinner** [comment]
I'm sorry, but there's nothing we can do about another product breaking Sublime Merge.
