### ISSUE TITLE
Add a log file with a history of all performed Git Commands

### ISSUE THREAD

**Issue by strawlink** [sublimehq/sublime_merge#415]
**Problem description**

I some times encounter situations where it would be beneficial to see all git commands I've recently run, along with the result of that command. I can currently see only the last command + result when clicking a button in the center, but I can't find any information about commands before that.

**Preferred solution**

Add a log file stored in `%appdata%/Sublime Merge` that is appended to when any git command is performed. I would like for all the output of the git command to be shown in this log.
When the application starts, the existing log file should be renamed with a suffix, eg. "-previous", and a new log file should be created, so you can see the data of the current session and the last session.

**Screenshots**

Existing functionality only shows the latest log.
![image](https://user-images.githubusercontent.com/6575922/54343114-618c1d80-463e-11e9-98f6-5b8a77c894fd.png)

Possibly add a shortcut to the help menu that opens the git command log.
![image](https://user-images.githubusercontent.com/6575922/54342406-a31bc900-463c-11e9-97b9-d8d95f7cfc99.png)
Or add it as a command in the command palette.
![image](https://user-images.githubusercontent.com/6575922/54343770-d1e76e80-463f-11e9-8781-c08d80467514.png)

**Comment by BenjaminSchaaf** [comment]
This has been added for Sublime Merge 2: 
![Screenshot from 2020-06-18 12-46-07](https://user-images.githubusercontent.com/2748981/84972279-d9aa9280-b161-11ea-9acf-98759a47abb8.png)
