### ISSUE TITLE
Is there a way to set a custom `node_path` (for nvm)?

### ISSUE THREAD

**Issue by gka** [sublimehq/sublime_merge#424]
**Problem description**

I use pre-commit hooks that run node commands that lint the code before allowing to commit etc. These node commands depend on my users node version (under `~/.nvm/version/node/.../bin/node`). Instead the hook tries to use the system node which is some outdated version I never use and so the pre-commit hook fails.

**Preferred solution**

I'd like to be able to just set a `node_path` or a `path` in the sublime-merge config so my pre-commit hooks run through.

**Screenshots**

![image](https://user-images.githubusercontent.com/617518/54397500-fd597000-46b6-11e9-9069-511d553c1e26.png)

**Comment by wbond** [comment]
Are you on Linux, or Mac? If on Linux, you could set the env var when you invoke sublime_merge. On Mac, the issue is tricker since the app is always launched with the Dock as the parent process.

**Comment by gka** [comment]
I'm using Linux, but after following the installation instructions via `apt` I don't have a `sublime_merge` command in my $PATH. Instead I am launching Sublime Merge via the status footer in Sublime Text which shows the current branch. Is there maybe a SublimeText config that allows me to set the `env`?

**Comment by jskinner** [comment]
You can use the "git_env" setting for this (via the Preferences/Edit Settings... menu)

```
"git_env": {"MY_ENV_VAR": "foo"},
```

**Comment by jimlawton** [comment]
👍 

This fixed my issue with pre-commit hooks on MacOS. I used `git_env` to specify a custom `PATH` for Sublime Merge.

Thanks!

**Comment by jeandat** [comment]
I don't see any git_env setting in latest version of Sublime merge. Am I missing something?
