### ISSUE TITLE
There is no way to exit file history view with just the mouse

### ISSUE THREAD

**Issue by safield** [sublimehq/sublime_merge#433]
Window 10 1809
Sublime Merge Dev Channel 1106

When I right click on a file in the contents view, or the right side commit changes window, there is not way to exit the subsequent File History view with a mouse click.

The only way I am aware of the return back to the previous view is to press escape.

I don't see how this navigation action is any different that other navigation actions that are supported the mouse.

**Comment by BenjaminSchaaf** [comment]
I can't seem to reproduce this on linux, are you saying that the back button on the top left of the screen does not take you back from the File History view?

**Comment by safield** [comment]
I noticed the back button does work for me. But even better, dev build 1109 introduced an explicit close X on the search box. That alleviates my issue even better.
