### ISSUE TITLE
Typo in theme (transparent icon buttons)

### ISSUE THREAD

**Issue by jrappen** [sublimehq/sublime_merge#437]
**Version info**

 - OS: macOS 10.14.3 (18D109)
 - Build: 1106

**Description**

It seems `min_size` here should be `[0, something]` rather than `0`.

```json
//  Merge.sublime-theme#1272

        {
            "class": "button_control icon_button transparent",
            "min_size": 0,
            "content_margin": [2, 2],
            "layer1.opacity": 0,
        },
```

**Comment by jskinner** [comment]
`0` is equivalent to  `[0, 0]` here, is there a visual artifact that this is causing?

**Comment by jrappen** [comment]
No, Jon. I was looking at the code with PackageDev highlighting it as an error.

/cc @FichteFoll

**Comment by FichteFoll** [comment]
Note that the current docs say this about `min_size`:

> an array of two integers specifying the minimum width and height of a button, in DIPs 

Do `icon_spacing` and `shadow_offset` also behave like this?

Fixed for PackageDev in https://github.com/SublimeText/PackageDev/commit/b60fcd8898287467b49b4a294ce6407709e41686. Thanks for the heads-up.

**Comment by jskinner** [comment]
@FichteFoll Yes, `icon_spacing` and `shadow_offset` also both support being specified by a single number only (internally it's part of the json->vec2 conversion logic)
