### ISSUE TITLE
Keyboard shortcuts don't work when using as mergetool

### ISSUE THREAD

**Issue by rchl** [sublimehq/sublime_merge#438]
**Version info**

 - OS: macOS 10.14.3
 - Build: 1107

**Description**

Configured as git mergtool per https://www.sublimemerge.com/docs/command_line but keyboard shortcuts for going to next conflict (command+n) or saving resolved conflicts (command+s) don't work.

**Steps to reproduce**

1. Have a conflict in git
2. Open SM using `git mergetool`
3. Resolve conflict and press command+S
or
Press command+N to go to next conflict.

**Expected behavior**

Shortcuts work the same as pressing the UI button with a mouse.
Instead SM opens new SM window on command+N and does nothing on command+S.

**Comment by jskinner** [comment]
Thanks for the report - this should be fixed in 1109, at https://www.sublimemerge.com/dev
