### ISSUE TITLE
Unable to authenticate for github.com with GitHub Two-factor authentication

### ISSUE THREAD

**Issue by FrankTheTank9** [sublimehq/sublime_merge#44]
**Version info**

 - OS: macOS 10.13.6
 - Build: 1065

**Description**

Unable to authenticate for github.com in Sublime Merge with GitHub Two-factor authentication.

**Steps to reproduce**

1. Enable GitHub Two-factor authentication (my authenticator application is 1Password)
2. Clone a new repository
3. An "Authentication Required" popup opens asking for authentication for github.com with "Username" and "Password" input boxes
4. Enter GitHub username and password

**Expected behavior**

As GitHub Two-factor authentication is enabled, a second popup should be asking for an authentication code (second authentication factor). As a comparison, I am providing screenshots showing the authentication flow from GitHub Desktop and Sublime Merge.

GitHub Desktop
![github desktop sign-in](https://user-images.githubusercontent.com/15252390/46345722-9ddd3b80-c613-11e8-8726-7bb4c954cd89.png)
![github desktop authentication code](https://user-images.githubusercontent.com/15252390/46345727-a5044980-c613-11e8-9155-5a98333c054d.png)

Sublime Merge
![sublime merge authentication required](https://user-images.githubusercontent.com/15252390/46345736-ad5c8480-c613-11e8-9084-cc45113fe484.png)
![sublime merge invalid credentials](https://user-images.githubusercontent.com/15252390/46345743-b188a200-c613-11e8-9b9c-12741a046a9b.png)

**Comment by FrankTheTank9** [comment]
I ended up creating a personal access token as described here: https://help.github.com/articles/accessing-github-using-two-factor-authentication/#using-two-factor-authentication-with-the-command-line. I have authenticated using it through the command line and Sublime Merge works like a charm now.

**Comment by djibarian** [comment]
I had the same problem recently. I was able to pull from GitHub with no problems and suddenly Merge is asking me for credentials. When I enter the right ones I get an “Invalid username or password” error. Then I disabled 2FA in GitHub and everything worked properly. Afterwards I enabled 2FA again and the problem reappeared in Merge.

**Comment by djibarian** [comment]
Why is this suddenly appearing if I never had any auth problems? Maybe a password cache issue? (I see there is an menu option for that which in my case is disabled).

**Comment by nicknameNothing** [comment]
Yeah, I'll check it out later, but I really don't want to get rid of my 2FA anyway...

________________________________

**Comment by djibarian** [comment]
Just tried to generate an access token as described by @FrankTheTank9, used it as the password when asked in Sublime Merge and that solved the problem.

**Comment by nicknameNothing** [comment]
Really? I didn't know that. Gonna give it a try. Nice one dude!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gregbarbosa** [comment]
Taking @FrankTheTank9's advice, I was able to finally resolve this.

1. Created a [personal token for the command line](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line)
2. [Updated my macOS keychain](https://help.github.com/en/articles/updating-credentials-from-the-osx-keychain) with the new personal token
3. In Terminal, ran a git command, and it re-prompted for my credentials. I typed in my username and used my personal token as the password

Sublime Merge now works beautifully!

**Comment by BenjaminHoegh** [comment]
is there any status on when this would be fixed?

**Comment by frozenpandaman** [comment]
Instructions below worked – thanks!

Hoping to get this fixed as well, i.e. it'd be great if Sublime Merge integrated 2FA support or even linked to a page saying how to perform these steps.

**Comment by iSilverfyre** [comment]
=== App Version Information ===
Build: 1119

=== Git Version Information ===
Using Git: git (system)
git version 2.17.2 (Apple Git-113)
PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin (from shell)
environment variables loaded using: /bin/bash -l

This is an issue in the current version.  I was able to get around this using the instructions for an access token, but ignoring native 2FA is not a great option in your build either.  Especially when GitHub Desktop GUI prompts for the 2FA, which is what this program is designed in part to replace.

Is there any status updates on if or when this might be fixed or implemented?

**Comment by dpjohnst** [comment]
Hi all, 

Thank you for sharing your concerns on this issue.

This is the official advice from GitHub: https://github.blog/2013-09-03-two-factor-authentication/#how-does-it-work-for-command-line-git

As Sublime Merge wraps around command line Git itself, its behavior should match the command line.

I'm going to go ahead and close this issue, but please feel free to re-open it if you feel it has not been addressed adequately.

Thanks,
\- Dylan

**Comment by nk9** [comment]
I ran into this problem on Windows with Sublime Merge and git bash. While I followed the instructions and created a PAT, in the end I never needed to enter it anywhere. After creating the token, I ran `git merge --rebase` from the git bash command line and the tool opened a github.com page in my browser. I confirmed that I wanted the github command line tool to have access to my github account and _voilà_, Sublime Merge now works without further login requests. So If that's your setup, it may not actually be necessary to create a PAT, try just authenticating with the CLI first.

**Comment by hyunbinseo** [comment]
You don't need a personal access token anymore. Above link is a blog post from [2013](https://github.blog/news-insights/company-news/two-factor-authentication/#how-does-it-work-for-command-line-git).

Use the GitHub CLI `gh` instead. Reference [Caching your GitHub credentials in Git](https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git)

```shell
gh auth login
# Where do you use GitHub? GitHub.com
# What is your preferred protocol for Git operations on this host? HTTPS
# Authenticate Git with your GitHub credentials? Yes -- IMPORTANT!
# How would you like to authenticate GitHub CLI? Login with a web browser
```

I've successfully accessed a private repo. using a GitHub account with hardware key 2FA.

It even supports multi-accounts:

```shell
gh auth status
# github.com
#   ✓ Logged in to github.com account username_a (keyring)
#   - Active account: true
#   - Git operations protocol: https
#   - Token: gho_************************************
#   - Token scopes: 'gist', 'read:org', 'repo', 'workflow'
# 
#   ✓ Logged in to github.com account username_b (keyring)
#   - Active account: false
#   - Git operations protocol: https
#   - Token: gho_************************************
#   - Token scopes: 'gist', 'read:org', 'repo', 'workflow'

gh auth switch
# ✓ Switched active account for github.com to username_b
```

To set a default GitHub credential per remote or repository:

```shell
# Always use the alice account for:

# ALL repositories on github.com
git config --global credential.https://github.com.username alice
```

```shell
# SPECIFIC local repository

# Option A: Configure an existing repository
git config credential.https://github.com.username alice

# Option B: Specify username when cloning
git clone https://alice@github.com/mona/test
```

[TL;DR: Tell GCM to remember which account to use](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/multiple-users.md#tldr-tell-gcm-to-remember-which-account-to-use)
