### ISSUE TITLE
Clicking File header in contents view, closes contents view.

### ISSUE THREAD

**Issue by safield** [sublimehq/sublime_merge#441]
Windows 10 1809
Sublime Merge Dev build 1111

To reproduce:
-Browse the contents of a commit by double click on said commit in the commits graph view.
-this should close the graph view and result in only the contents view panel showing.
-in the contents view, click on a file to view its diff on the right hand side pane.
-double click the blue file header in the right hand side pane.

After doing this action:
-you leave the single file diff view of the contents view
-the graph view is opened up, 
-the right hand side pane is populated with the short diffs of all of the files.

See screenshot
![smb1](https://user-images.githubusercontent.com/12876404/54783929-98d76d00-4bf0-11e9-860c-74f63beb6405.jpg)
![smb2](https://user-images.githubusercontent.com/12876404/54783936-9b39c700-4bf0-11e9-8d34-e37750b336f3.jpg)

**This action should be removed.**
-it is unexpected
-a click on a specific file header should not execute a general purpose action like changing the whole UI
-the close operation indicated by the X should be limited to the bounds of the X.

Please make sublime merge navigation more explicit.

**Comment by dpjohnst** [comment]
Closing, as this is no longer applicable.
