### ISSUE TITLE
php if else wrong indentation

### ISSUE THREAD

**Issue by xhpohanka** [sublimehq/sublime_merge#442]
**Version info**
 - OS: Arch Linux
 - Build: 3176

**Description**
Sublime text indentation wrongly indents else branch of php branch.

**Steps to reproduce**
- Create new file and set php syntax
- Fill in
```
<?php if (true): ?>
asdfadf
<?php else if():?>
asdf
<?php endif;?>
```
- select reindent from edit menu

**Expected behavior**
First and third line should start on the same column

**Comment by srbs** [comment]
@xhpohanka, this issue tracker is for Sublime Merge, you'll want to close this & open on in the Sublime Text issue tracker: https://github.com/SublimeTextIssues/Core/issues.
