### ISSUE TITLE
Ability to see a console output on git commands run

### ISSUE THREAD

**Issue by Piterden** [sublimehq/sublime_merge#444]
I have a husky pre-push hook, which runs a lint command on push to remote.
The problem: I don't see any output results of that command.

Maybe it would be good to add an ability to show/hide the terminal tab, which would contain all `stdout` log?

(Whooh, 444, I always was a lucky guy))))

**Comment by jskinner** [comment]
You should be able to see the git output via clicking on the icon on the left hand side of the info box, where the current branch name is displayed

**Comment by Piterden** [comment]
Ya, I see. Thanks.

But there is only the last command. How to see a previous one?

**Comment by jskinner** [comment]
Currently we only show the last one, but we are planning on changing that in the future to show all past commands

**Comment by Piterden** [comment]
Thank you for the response. Will test it with `husky` soon...

*So, what would I do now? To leave this issue or it's better to close it?*

**Comment by Piterden** [comment]
Hello. Yeah it works fine. Thanx one more time)
