### ISSUE TITLE
Cursor line and column position is not displayed when amending a previous commit's commit message

### ISSUE THREAD

**Issue by weelillad** [sublimehq/sublime_merge#453]
**Version info**

 - OS: elementary OS 5.0 Juno, built on Ubuntu 18.04 LTS
 - Build: 1111

**Description**

Cursor line and column position is not displayed when amending a previous commit's commit message (see second screenshot).

**Steps to reproduce**

1. Right click on a commit
2. Select "Edit Commit", "Edit Commit Message"

**Expected behavior**

The cursor line and column position should be displayed beneath the commit message, similar to writing a new commit message (see first screenshot).

**Screenshots**

![Writing a new commit message](https://user-images.githubusercontent.com/3506248/55473523-7fe3a880-5641-11e9-99c0-562083d79de9.png)

![Amending an old commit message](https://user-images.githubusercontent.com/3506248/55473433-5296fa80-5641-11e9-8ccd-9c28461fa299.png)

**Comment by jskinner** [comment]
Thanks for the report, this is now implemented in 1116
