### ISSUE TITLE
git add --intent-to-add is shown in Staged Files

### ISSUE THREAD

**Issue by Tcc100** [sublimehq/sublime_merge#454]
**Version info**

 - OS: Arch Linux
 - Build: 1107

**Description**

Files added with the `--intent-to-add` option are shown in *Staged Files* with `<contents empty>`.
(They are also shown in the *Working Directory* section, as expected.)

**Steps to reproduce**

1. Open repository with files added with the `--intent-to-add` option

**Expected behavior**

Files added with the `--intent-to-add` option are only shown in the *Working Directory* section.

**Comment by jskinner** [comment]
Thanks for the report, `--intent-to-add` is now supported in 1116
