### ISSUE TITLE
Crash when moving window between displays

### ISSUE THREAD

**Issue by David-Nickerson-CashStar** [sublimehq/sublime_merge#456]
macOS Mojave Version 10.14.4, MacBook Pro (15-inch, 2017)
Displays connected via DisplayLink Dock
DisplayLink driver version 5.1
Sublime Merge Build 1107

When 1 or 2 displays are connected there are no problems.
When 3 displays are connected, Sublime Merge will reliably crash when the application window is moved to a specific display.
When 4 displays are connected, Sublime Merge will fail to launch on any monitor.
No other applications are affected.

**Comment by srbs** [comment]
This might work for you (but with Sublime Merge settings):
https://forum.sublimetext.com/t/crash-or-memory-leak-on-macos-mojave-10-14-4/43447

**Comment by jskinner** [comment]
This is a macOS 10.14.4 bug, that should be resolved by a workaround in Sublime Merge 1112 at https://www.sublimemerge.com/dev
