### ISSUE TITLE
A quick way to open a selected file in text editor

### ISSUE THREAD

**Issue by chatchavan** [sublimehq/sublime_merge#458]
**Problem description**

I found myself frequently looking at a specific changes in a file and need to make additional changes in that file before committing. In Build 1107, there's a way to "Open Repository in Sublime Text". Using this command means that I have to search for that file again in Sublime Text before being able to edit it.

**Preferred solution**

Provide an option to open a specific file in Sublime Text. For example when right-click on a file, show a context menu with an option "Open in Sublime Text".

**Alternatives**

Allow basic text editing in Sublime Merge itself.

**Comment by jskinner** [comment]
If you right click within the text of a diff in Sublime Merge, there's a context menu entry for "Open in Editor...", which will open the file in Sublime Text
