### ISSUE TITLE
Submodules in detached HEAD state show up as unstaged changes

### ISSUE THREAD

**Issue by Zooce** [sublimehq/sublime_merge#46]
**Version info**
* OS: Windows 10
* Build: 1065

**Description**

If you have submodules at detached heads they show up as unstaged files. This happens even if there are no changes locally in the submodule (see the screenshots below).

**Steps to reproduce**

1. Have one or more submodules in detached HEAD states in a repo
2. Open Sublime Merge for that repo
3. Notice the submodules are marked as unstaged changes
4. Make a change in one of the submodules
5. Notice (in Sublime Merge) those changes do not show up (<< this could be a separate issue)

**Expected behavior**

If there are no changes to the submodule, and the submodule is in a detached HEAD state, it shouldn't necessarily show up as unstaged changes. I would expect there might be some indication that the submodules are in detached HEAD states, but not as unstaged changes, especially when there were no changes. Also, I'd expect there to be some indication of modified files in a submodule if there were changes.

**Screenshots**

_**No changes in submodules, just detached HEAD states**_

This shows the status of the repo: `$ git status`

![smerge_submod_term_no_changes](https://user-images.githubusercontent.com/5490155/46369501-0c33f500-c638-11e8-9d87-cf18cc6017d0.png)

This shows the corresponding view in Sublime Merge

![smerge_submod_no_changes](https://user-images.githubusercontent.com/5490155/46369509-135b0300-c638-11e8-8dbb-b9f8f6b68dc0.png)

_**With changes in submodules and detached HEAD states**_

This shows the status of the repo: `$ git status`

![smerge_submod_term_changes](https://user-images.githubusercontent.com/5490155/46369527-22da4c00-c638-11e8-89b3-ddd630f43400.png)

This shows the corresponding view in Sublime Merge - note the first submodule is the one with changes

![smerge_submod_changes](https://user-images.githubusercontent.com/5490155/46369533-253ca600-c638-11e8-8273-b0630eeef1df.png)

**Comment by ansonj** [comment]
I am also seeing this "Deleted", `<contents empty>` issue in build 1065 on macOS, even for a submodule with no changes and no detached HEAD involved. There are also several reports [on the forums here](https://forum.sublimetext.com/t/bug-submodule-updated-in-sublime-merge-no-changes-in-git-bash/39161).

**Comment by jskinner** [comment]
Thanks for the report. This should be fixed now in dev build 1066 at https://www.sublimemerge.com/dev - please let me know if it's not

**Comment by Zooce** [comment]
Thanks, @jskinner - the first case I mentioned seems to be fixed - which is awesome, so thank you. The second however seems to still be present. This is where I have submodules in a detached HEAD state, AND there's local changes that have been made to them, which are not showing up in Sublime Merge, but do show up when I run `$ git status`. This could be completely unrelated, but I'm not sure. If necessary I can submit a separate issue for this - just let me know.

![smerge_submod_term_changes_2](https://user-images.githubusercontent.com/5490155/46392031-96aa4200-c694-11e8-9748-5a918cae953c.png)

![smerge_submod_changes_2](https://user-images.githubusercontent.com/5490155/46392036-9c078c80-c694-11e8-9b47-a34326980674.png)

**Comment by jskinner** [comment]
Thanks for the confirmation @Zooce!

Sublime Merge not showing changes within a submodule is indeed a separate issue. We don't currently recurse into the submodule to determine if there are any local changes, we only look at the current HEAD of the submodule and compare it vs the index.

It's more of a UI thing than anything else: showing that the submodule has modified or untracked files in the 'Commit Changes' dialog does have the advantage of doing the same thing that `git status` does, but it also has downsides: there's no way to resolve those items from within the commit changes area, so they'd have to appear as status items without any buttons, which is fine, but does require some planning.

We'll be going over our submodule UI in the near future, and I hope to get this addressed then.
