### ISSUE TITLE
Execute Arbitrary Programs

### ISSUE THREAD

**Issue by dpjohnst** [sublimehq/sublime_merge#462]
**Problem description**

In my current work environment, I need to execute a few other programs in order to move code between different version control systems. Currently I need to switch between Sublime Merge and the command line to do this.

**Preferred solution**

Allow shelling out to arbitrary programs via Sublime Merge, similar to the "git" command, but for any program.

**Comment by stinos** [comment]
Duplicate of https://github.com/sublimehq/sublime_merge/issues/247 ?

**Comment by dpjohnst** [comment]
Indeed! I'll close
