### ISSUE TITLE
Syntax highlight is broken iterating on deconstructed tuples (C# 7.0)

### ISSUE THREAD

**Issue by mihaipopescu** [sublimehq/sublime_merge#463]
**Version info**

 - OS: macOS 10.14.4
 - Build: 1107

**Description**

Sublime merge syntax highlight breaks when it encounters iterations on deconstructed tuples.

**Steps to reproduce**

1. Create a new git repository
2. Create a new C# file, say `bug.cs`
3. Paste the following code https://pastebin.com/VVeQykmg
4. Add and commit the file to git repository
5. Edit the file again and apply this patch https://pastebin.com/FrB85G6V (so that the modified line is within the limit patch context range)
5. Observe that the syntax highlight is broken

N.B. if I add a space between `var` and `(x, y)` the bug doesn't reproduce anymore.

**Expected behavior**

Code is recognized as valid syntax.

**Screenshots**
my own experience https://gyazo.com/ec58ba9656775b8b3459ff494f1dca3a
the proposed reproduction steps https://gyazo.com/d6c8526d21546475dd36b13eea41045d

**Comment by srbs** [comment]
Sublime Merge syntax highlighters are handled in this repo: https://github.com/sublimehq/Packages, you should move this issue over there.

**Comment by mihaipopescu** [comment]
thanks @srbs. Opened https://github.com/sublimehq/Packages/issues/1946 for the reference.
