### ISSUE TITLE
Title bar funky after minimize from full screen with tabs

### ISSUE THREAD

**Issue by voltechs** [sublimehq/sublime_merge#466]
**Version info:**
 - OS: macOS 10.14.4 (18E226)
 - Build: 1107

**Description:**

After exiting fullscreen with tabs, the window has a malformed title bar.

**Steps to reproduce:**
1. Open a few project windows.
2. Merge windows.
3. Enter full screen.
4. Exit full screen.
5. Observe the title bar for the window.

**Expected behavior:**

The title bar is all screwy.
The attached screenshot shows a small window for "brevity", but rest assured it occurs in normally sized windows as well.

**Screenshots:**
<img width="1989" alt="Screen Shot 2019-04-19 at 16 24 25" src="https://user-images.githubusercontent.com/1700514/56446438-e7dff300-62bf-11e9-8f6d-1daa66846b0d.png">

**Comment by srbs** [comment]
Reproduced in SM dev build 1112, does not occur in Sublime Text dev build 3202. It appears to be caused by the SM toolbar & forgetting that multiple macOS-window-tabs exist.

**Comment by voltechs** [comment]
Just updated to build 2028. Still getting a funky title bar when going from full screen to windowed, using tabs.
When hitting command+n (for a new window/native tab), the rendering issue is cleared up. Upon closing the new tab, the issue returns.

There was a note in the changelog that mentioned fixing a mac rendering issue, so I was hopeful :)

<img width="1473" alt="Screen Shot 2020-08-07 at 2 24 02 PM" src="https://user-images.githubusercontent.com/1700514/89686866-5f260580-d8bc-11ea-9325-dcf7434f307f.png">
<img width="1038" alt="Screen Shot 2020-08-07 at 2 26 38 PM" src="https://user-images.githubusercontent.com/1700514/89686873-60efc900-d8bc-11ea-85ee-62e7c92099cc.png">
<img width="912" alt="Screen Shot 2020-08-07 at 2 25 24 PM" src="https://user-images.githubusercontent.com/1700514/89685873-6f3ce580-d8ba-11ea-9b31-2c2ac407c629.png">

**Comment by srbs** [comment]
Note: this only occurs when using macOS-window-tabs. Not when using the Sublime-Merge-native-tabs.

Does that match your experiences @voltechs?

**Comment by voltechs** [comment]
@srbs that is correct.

**Comment by voltechs** [comment]
Just updated to build 2042. This is still happening. What's the issue? Can't the framework from ST be used for SM?

**Comment by voltechs** [comment]
As usual, a new update brings new trust 😀, however as of build 2045, this is still an issue 😞
I can't wait to be able to fullscreen this puppy, like SublimeText!

<img width="664" alt="image" src="https://user-images.githubusercontent.com/1700514/108388072-7c248500-71cb-11eb-8dbe-81b309e5f040.png">

**Comment by voltechs** [comment]
It's been a while. Build 2057 unfortunately did not fix this issue. Was hoping this (screenshot) would fix it. Still a problem.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/1700514/123859740-406c9b00-d8e2-11eb-8cea-df3f509c6017.png">

**Comment by voltechs** [comment]
Seems to be fixed at least 2060
