### ISSUE TITLE
Sublime Merge's installation directory is owned by an unknown user

### ISSUE THREAD

**Issue by timmydog** [sublimehq/sublime_merge#469]
**Version info**

 - OS: Ubuntu 18.04
 - Build: 1107

**Description**

Sublime Merge's installation directory is owned by an unknown user.

**Steps to reproduce**

1. Install sublime merge using the `apt` instructions on https://www.sublimetext.com/docs/3/linux_repositories.html
2. Run commands to view ownership:
```
% ls -Ahl /opt
total 60K
drwxr-xr-x  4        501 staff 4.0K Apr 23 09:16 sublime_merge
drwxr-xr-x  4 root       root  4.0K Apr 23 09:16 sublime_text
% ls -Ahl /opt/sublime_merge
total 11M
-rw-r--r-- 1 501 staff  15K Mar 12 23:22 changelog.txt
-rwxr-xr-x 1 501 staff 1.1M Mar 12 23:22 crash_reporter
-rwxr-xr-x 1 501 staff  15K Mar 12 23:22 git-credential-sublime
drwxr-xr-x 7 501 staff 4.0K Apr 23 09:16 Icon
drwxr-xr-x 2 501 staff 4.0K Apr 23 09:16 Packages
-rwxr-xr-x 1 501 staff  15K Mar 12 23:22 ssh-askpass-sublime
-rwxr-xr-x 1 501 staff 8.9M Mar 12 23:22 sublime_merge
```
**Expected behavior**

The directory and files should probably be owned by the root user.

**Comment by jskinner** [comment]
Thanks for the report, this is fixed in 1116, but you'll have to uninstall Sublime Merge to force the directory to be recreated:

```
sudo apt update
sudo apt remove sublime_merge
sudo apt install sublime_merge
```
