### ISSUE TITLE
git flow finish with options

### ISSUE THREAD

**Issue by neo-cheung** [sublimehq/sublime_merge#477]
**Problem description**

sublime merge call `git flow finish` with `-F` which will cause git delete remote branch before pushing the merge commit
If you are using pull request workflow the delete of remote branch before pushing merges it will change the PR status to **CLOSED** instead of **MERGED**

**Preferred solution**

a setting under preference which globally applies or a per repo setting

**Comment by srbs** [comment]
This sounds like an issue with `git-flow` or maybe your repo hosting provider and not Sublime Merge. The argument `-F` should only fetch remote changes and as far as I know, Sublime Merge just runs that command and nothing else.

Have you tried running that command on the command line and see what the behavior was? Also, can you specify the version of Sublime Merge & platform you're using?

**Comment by neo-cheung** [comment]
seems Sublime Merge has different behaviour on Mac and Windows

Procedures
1. Start git flow new feature
2. commit changes
3. push feature branch to github
4. create new PR
5. git flow finish feature 

## On Mac

when finish feature the output from Sublime Merge it only remove the local branch as expected

Sublime Merge Version: Stable Channel Build 1107
Git Binary: system
git version: 2.20.1

```
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
Updating 8f830e2..a771d85
Fast-forward
 sample.txt | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
Deleted branch feature/mac_pr (was a771d85).

Summary of actions:
- The feature branch 'feature/mac_pr' was merged into 'develop'
- Feature branch 'feature/mac_pr' has been removed
- You are now on branch 'develop'
```

## On Windows

when finish feature the output from Sublime Merge not only remove the local branch, it also remove the remote branch

Sublime Merge Version: Stable Channel Build 1107
Git Binary: system
git version: 2.21.0.windows.1

```
Your branch is up to date with 'origin/develop'.
Switched to branch 'develop'
Updating c046375..8f830e2
Fast-forward
 sample.txt | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
To github.com:neo-cheung/github-playground.git
 - [deleted]         feature/windows_edit
Deleted branch feature/windows_edit (was 8f830e2).

Summary of actions:
- The feature branch 'feature/windows_edit' was merged into 'develop'
- Feature branch 'feature/windows_edit' has been locally deleted; it has been remotely deleted from 'origin'
- You are now on branch 'develop'
```

**Comment by srbs** [comment]
Since you're using the system git binary, what version of git-flow is installed? (`git flow version`) Could you try these steps out with the bundled binary as well? I'm thinking it's just an older bug in the installed version of git-flow.

**Comment by neo-cheung** [comment]
@srbs yes it is a bug from git-flow i use the git-flow ship with git cli for windows
The different behaviours are causing by git-flow on Windows which will also remove remote branch if not specify `-k` with `git flow finish`

**Comment by srbs** [comment]
@neo-cheung, that is good to know. I had forgotten that there were different implementations of git flow (here I was lost poking around [this code](https://github.com/nvie/gitflow/blob/develop/git-flow-feature#L232)); thanks for investigating further!

**Comment by neo-cheung** [comment]
for anyone have the same problem you can follow the config steps from [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-Configuration) to set the default falgs
