### ISSUE TITLE
Cherry pick multiple commits

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#480]
**Problem description**

In some cases a `git rebase` is not possible to move a branch ot a new root, especially if the current branch is based on a totally different "tree" as the desired destination. Rebasing would therefore move the whole tree instead of the branch.

Git Extensions allows to select the number of commits to handle that.

The only solution to do so in Sublime Merge is to create a new branch at the new base commit and cherry pick all the commits of the branch, which is to be moved.

The main issue is only one commit to be able to be cherry picked at a time.

**Preferred solution**

All selected commits in the commit tree should be cherry picked one after another beginning with the oldest one.

**Alternatives**

Add a rebase operation which rebases the current branch 

a) beginning with the first unique commit, which is not part of any other branch.
b) including only the selected commits of a branch.

**Screenshots**

![Animation](https://user-images.githubusercontent.com/16542113/57017429-7e48d880-6c1f-11e9-98ab-b25010db7e91.gif)

**Comment by srbs** [comment]
Similarly, supporting multiple commits in `Edit Commit[s]` > `Move Commit[s] Up` & `Move Commit[s] Down` would be useful.

**Comment by TheGag96** [comment]
Any plans to do this? It seems like a pretty convenient feature and not uncommonly needed... I had to go through the trouble of cherry picking one-by-one for a decently-sized series of commits recently. TortoiseGit, for example, supports this feature.

**Comment by dpjohnst** [comment]
Hi all,

This was added in Sublime Merge build 2057, and will be available in the next stable build!

Cheers,
\- Dylan
