### ISSUE TITLE
Immediate crash on startup

### ISSUE THREAD

**Issue by brianm** [sublimehq/sublime_merge#484]
**Version info**

 - OS: MacOS 10.14.4
 - Build: 1107

**Description**

The app opens, paints window, and crashes. Happens on every repo I have tried. Logs show:

```
May  2 09:49:50 scuffin sublime_merge[16547]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
May  2 09:49:52 scuffin com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x100003c2.sublime_merge[16547]): Service exited with abnormal code: 1
```

**Steps to reproduce**

1. Run SublimeMerge
2. See app open/window paint
3. See app go away

**Expected behavior**

The application should open and work

**Comment by brianm** [comment]
I removed `~/Library/Application Support/Sublime Merge/` and now it will open, show :

![image](https://user-images.githubusercontent.com/1291/57092712-ddaaf500-6cc0-11e9-8a76-85de679b49d8.png)

but crash if I click `Open Repository`, try to open preferences, try top open a new window (File -> New Window).

The same message as reported above is logged in `system.log` when this happens:

```
May  2 09:56:49 scuffin sublime_merge[26174]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
May  2 09:57:01 scuffin com.apple.xpc.launchd[1] (com.sublimemerge.35912[26174]): Service exited with abnormal code: 1
May  2 09:57:04 scuffin sublime_merge[26417]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
May  2 09:57:11 scuffin com.apple.xpc.launchd[1] (com.sublimemerge.35912[26417]): Service exited with abnormal code: 1
May  2 09:58:01 scuffin sublime_merge[27799]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
May  2 09:58:04 scuffin com.apple.xpc.launchd[1] (com.sublimemerge.35912[27799]): Service exited with abnormal code: 1
May  2 09:58:14 scuffin sublime_merge[28340]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
May  2 09:59:12 scuffin com.apple.xpc.launchd[1] (com.sublimemerge.35912[28340]): Service exited with abnormal code: 1
May  2 09:59:25 scuffin sublime_merge[29573]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
May  2 09:59:32 scuffin com.apple.xpc.launchd[1] (com.sublimemerge.35912[29573]): Service exited with abnormal code: 1
```

**Comment by brianm** [comment]
Same behavior occurs if I remove `~/Library/Preferences/com.sublimemerge.plist`

**Comment by brianm** [comment]
Same behavior occurs if I remove `~/Library/Caches/com.sublimemerge`

**Comment by brianm** [comment]
Same behavior occurs if I remove `~/Library/Saved Application State/com.sublimemerge.savedState`

Basically, I tried removing everything I could find which might be bad state (`find ~/Library -iname '*sublime*'`), including the application, unzipped and copied back to `/Applications/`, and behavior occured every time.

**Comment by srbs** [comment]
This should do the trick for you (but with Sublime Merge settings): https://forum.sublimetext.com/t/crash-or-memory-leak-on-macos-mojave-10-14-4/43447

See also #475

**Comment by srbs** [comment]
Also, dev build 1112 should fix this as well.

See also #456

**Comment by brianm** [comment]
Confirmed, this resolves the issue. Thank you!
