### ISSUE TITLE
Easy to lose the commit message when using "Edit commit message"

### ISSUE THREAD

**Issue by nickolay** [sublimehq/sublime_merge#486]
**Version info**

 - OS: macOS 10.9.5
 - Build: 1112

**Description**

I've lost the commit message several times on different OSes and Sublime Merge versions, when rebasing via "Edit commit -> Edit commit message". I can reproduce by manually focussing another commit while editing, but I think sometimes I lose it just by switching from Sublime - perhaps as the focussed commit is changed on its own?

**Steps to reproduce**
(Didn't try to reproduce from scratch, because I assume I'd get the same results.)
1. In a repository right-click the last commit of the currently active branch, select "Edit commit -> Edit commit message"
2. Edit the commit message, but don't amend
3. Click on the second-to-last commit and then back on the commit you've been editing

**Expected behavior**
The edits to the commit message are not lost.

(a related way to lose a commit message is by hitting ESC - #141)

**Comment by srbs** [comment]
This can be fixed similarly to the recent merge tool improvement:
> * Navigation commands: a warning is displayed when exiting the merge tool

**Comment by Zwyx** [comment]
Wouhou :partying_face: This is fixed in the new version of Sublime (2068). I believe we can close this issue, as well as https://github.com/sublimehq/sublime_merge/issues/1069.
