### ISSUE TITLE
Installation on Windows without administrator account

### ISSUE THREAD

**Issue by zladuric** [sublimehq/sublime_merge#488]
**Problem description**

Trying to install Sublime Merge on the Windows 10 Pro (up to date), but I'm running into the dialog "You must be logged in as administrator when installing this program."
The version I've downloaded is _sublime_merge_build_1107_x64_setup.exe_.

I'm trying to install Merge on a corporate laptop, see if I can persuade a boss into getting me a licence there. It's a corporate-maintained laptop. I do have admin privileges (at least I think so, as I can run other programs through "run as administrator" right-click option), but I do not have an admin account.

So I can't even install the program to try it out. At home I use other operating systems and have no issues, but on my work laptop, I have to use Windows, I suspect I'm not the only one.

**Preferred solution**

Ideally, the installer wouldn't need an admin account - maybe only raised privileges, but ideally nothing at all.

**Alternatives**

As an alternative, a portable build would be nice as well.

**Comment by TheClams** [comment]
The portable version exists already : https://www.sublimemerge.com/download

**Comment by zladuric** [comment]
Oh, cool, thanks! Regular download links being prominent on the landing page, I didn't think of looking up a dedicated downloads page so I didn't notice. I can try out the program now. I'm not much of a GUI user normally, but I find sublime text close to what I like about vim, so I home to find a similar match in Merge to what I get from the shell. 
In any case, my original issue - that I can test this on windows - is resolved. I don't know if you want to leave the ticket open to consider the other part - not asking for admin privileges in the installer version as well. So I'll leave the ticket for you to triage further then.

Thanks again for great software.

**Comment by TETRIS122** [comment]
i want to install sublime text with no admin is this possible ?
