### ISSUE TITLE
Automatically switch light/dark-mode

### ISSUE THREAD

**Issue by me-benni** [sublimehq/sublime_merge#490]
**Problem description**

When switching the system between light/dark mode, apps switch automatically except Sublime Merge, which I have to change manually.

**Preferred solution**

It would be awesome if Sublime Merge could change it's appearance automatically based on the global state of light/dark themes. On macOS there seems to be a global state, as other apps have implemented this.

**Comment by Fudoshiki** [comment]
Make an option system theme on macOS

**Comment by rsmything** [comment]
It should be added the Auto option, which will change the theme according to the OS system settings, as it was done in Telegram and other applications

**Comment by jrappen** [comment]
It might make sense to replace:

```js
//  Packages/Default/Preferences.sublime-settings

{
	"theme": "Merge.sublime-theme"
}
```

with:

```js
//  Packages/Default/Preferences.sublime-settings

{
	"theme.light": "Merge.sublime-theme",
	"theme.dark": "Merge Dark.sublime-theme",

    // one of ["auto", "dark", "light"]
	"theme.prefers": "auto"
}
```

going forward with macOS and Windows preferring `"auto"` and Linux preferring `"dark"` based on the current situation with support by the OSes.

As theme switching is **currently the only feature available only to paying users**, the app could ignore the `"theme.prefers"` setting and force it to `"light"` when no license is provided.

**Comment by me-benni** [comment]
This feature just landed in Sublime Merge 2042 and Sublime Text 4096

**Comment by pranoy-k** [comment]
Hey @bfkss  Can you describe how will I use this feature?
