### ISSUE TITLE
Request: On move_commit and squash_commit, update which commit is selected 

### ISSUE THREAD

**Issue by tomngo** [sublimehq/sublime_merge#495]
**Problem description**

Now that I have [bound keys](https://forum.sublimetext.com/t/show-console-in-sublime-merge/44236/2) to `move_commit` in both directions, I find that pressing those keys repeatedly does something quite non-intuitive: it moves a different commit with each keypress. Instead, I expect and want to move the originally selected commit many times.

**Preferred solution**

Suppose you have commits:
A
B
C
D

and suppose you select B then invoke `move_commit` with `down: true`. The postcondition of that operation ought to be that the commits are in the order below, with B selected:
A
C
B
D

**Alternatives**

An alternative is to let a user create macros as described [here](https://forum.sublimetext.com/t/feature-request-on-move-commit-update-which-commit-is-selected/44243/2?u=tomngo). I believe that's cumbersome.

**Comment by tomngo** [comment]
**Further Enhancement**

In addition to the `move_commit` treatment above, there's the analogous treatment of `squash_commit`. If I squash A with B producing C, I proposed to wind up with C selected.

**Comment by tomngo** [comment]
Today, `move_commit` behaves as I expect (it matches the Preferred Solution above). Unless I am losing it, it was not behaving that way when I posted this enhancement request. I was on Build 1107 both times. Perhaps there's some circumstance that accounts for the difference, but I haven't pinpointed it.

**Comment by jskinner** [comment]
This should be fixed in 1116, please reopen the issue if it isn't
