### ISSUE TITLE
Window incorrectly offset with red panel in fullscreen mode

### ISSUE THREAD

**Issue by 13tales** [sublimehq/sublime_merge#496]
**Version info**

 - OS: MacOS 10.14.4
 - Build: 1107

**Description**

When displaying sublime merge in MacOS fullscreen mode on my secondary monitor, on switching back to Sublime Merge, I often see the the window offset down from the top of the screen by a few cm, with a solid red panel where the top of the window _should_ be positioned. See attached screenshot.

The screen doesn't respond correctly to actions like moving the mouse to the top of the screen to display the OS' window title bar and close/toggle fullscreen/minimise buttons, but does seem to revert to normal eventually, or if fullscreen mode is toggled off and on again.

**Steps to reproduce**

1. Make Sublime Merge fullscreen, and move it to a second monitor (in this case, my 15" Macbook Pro's built in display)
2. Lock the screen, and wait until after it goes to sleep.
3. Unlock the computer and switch back to sublime merge.

**Expected behavior**

The Sublime Merge window should display correctly in fullscreen.

**Screenshots**

![Pasted_Image_16_5_19__7_51_am](https://user-images.githubusercontent.com/14958909/57812302-04ccf080-77b0-11e9-9337-3fadc1859a75.jpg)
(Pixelisation added to obscure work stuff, obviously. The solid red panel at the top is the problem.)

**Comment by PVGrad** [comment]
I also affected with similar behaviour:

**Version info**

OS: MacOS 10.14.3 (18D109)
Build: 1107

**Screenshots**
<img width="829" alt="screen" src="https://user-images.githubusercontent.com/5259629/57937651-04774700-78cf-11e9-8c95-18fbbf7f931c.png">

**Comment by dpjohnst** [comment]
Hi all,

Could you confirm if you're still experiencing this issue?

I'm going to tentatively close the issue given the amount of time passed, but please re-open this if you're still affected by it.

Kind regards,
\- Dylan from Sublime HQ
