### ISSUE TITLE
Mergetool adds current working directory to absolute paths

### ISSUE THREAD

**Issue by mikelitvinets** [sublimehq/sublime_merge#497]
**Version info**

 - OS: Windows 10
 - Build: 1107

**Description**

On Windows when using Sublime Merge as a merge tool it adds CWD to provided absolute paths.

**Steps to reproduce**

1. Open cmd.exe
2. Run Sublime Merge as a merge tool with any absolute paths:

    C:\> "C:\Program Files\Sublime Merge\smerge.exe" mergetool F:\test.txt F:\test.txt F:\test.txt

3. Observe the error:

    Error reading file: C:\F:\test.txt

**Expected behavior**

Absolute paths are left intact.

**Screenshots**

![error_absolute_path](https://user-images.githubusercontent.com/9080149/57922578-ba7b6a80-78a8-11e9-93b5-810365065a9d.png)

**Comment by jskinner** [comment]
Thanks for the report, this is fixed in 1116
