### ISSUE TITLE
Viewing a single branch's commit history in the commit view

### ISSUE THREAD

**Issue by chuckiesmals** [sublimehq/sublime_merge#5]
**Problem description**

A common activity I do is exploring what commits are in a particular branch. Be it the currently checked out branch, an arbitrary branch or tag.

I'm on a large team who makes a lot of remote branches including many experimental ones that never get pulled into master. Having everything in the mix makes it extremely difficult to see what commits are in what branch. 

**Preferred solution**

If there was a way to limit the commit branch view. I'm imagining a set of "always on top" options at the top of the commit view. 

Options to convey how the list view will be filtered: 
- Checked out branch 
- Branch 
- Tag

Whatever makes sense really, but at least the currently checked out branch.

**Screenshots**

<img width="1044" alt="screen shot 2018-09-27 at 12 39 33 pm" src="https://user-images.githubusercontent.com/365477/46170431-a53ac880-c252-11e8-8ae8-5105b36660a1.png">

**Comment by chuckiesmals** [comment]
> Would you mind using the template provided please?

Ah sorry, for some reason I thought it was some sort of suggested github template. Updating!

**Comment by jasonycw** [comment]
Alternative is to highlight the current branch's commit, like making the other branches' commit dimmer or gray out

This is what SourceTree provides
![image](https://user-images.githubusercontent.com/4518597/46590647-696ff080-cae7-11e8-8b6e-d000f00395c5.png)

**Comment by jskinner** [comment]
This is now implemented in build 1070.

Individual branches can be hidden by clicking on the eye icon in the location bar, and just a single branch can be shown by alt-clicking on the eye icon.
