### ISSUE TITLE
Collapse options in location bar

### ISSUE THREAD

**Issue by maurovieirareis** [sublimehq/sublime_merge#50]
**Problem description**

Not exist a possibility of collapsing these areas.

![2198445aa992de5cb4b06a5b8a4dc70fd2887016](https://user-images.githubusercontent.com/3084774/46412923-cf3f2f80-c717-11e8-8c87-cc1c7b5da89b.png)

**Preferred solution**

![367232547acd7282842cd979da128aa5d24e37e9](https://user-images.githubusercontent.com/3084774/46412968-e41bc300-c717-11e8-9227-118b2f1c1be9.png)

**Comment by jskinner** [comment]
The sidebar is a tree as of dev build 1067 - https://www.sublimemerge.com/dev
