### ISSUE TITLE
Does not interpret TODO comments

### ISSUE THREAD

**Issue by WHK102** [sublimehq/sublime_merge#501]
In software development the TODO comment indicates tasks to be performed, intelij and other editors interpret this comment by marking them with a special color, Sublime Text should also color the word TODO that matches the syntax of TODO comment for python syntax: `# TODO: Unimplemented.`

**Comment by stinos** [comment]
> Sublime Text should also color the word TODO

It does this by aid of the [Sublime Linter plugin](http://www.sublimelinter.com/en/stable/).

However this is the Sublime Merge issue tracker :]
