### ISSUE TITLE
Sublime Merge hangs if one of the unstaged file is a pretty long minified js (7mb long)

### ISSUE THREAD

**Issue by aleGpereira** [sublimehq/sublime_merge#507]
**Version info**

 - OS: Ubuntu 18.04
 - Build: 1107

**Description**

When working on a web app project which is developed with react, a long min.js is generated when building the project. Git detects this "new file" as unstaged. So after working a while and ready to commit, when i open SM all unstaged files are listed but i cannot see their changes. When i try to close the windows i get a popup alert saying "Sublime merge is not responding".
![sublime_merge_issue](https://user-images.githubusercontent.com/1494870/58829448-30f4c800-861e-11e9-9443-b2f2fef7c0a1.png)

**Steps to reproduce**

1. In a working repository add a 7mb data file and make sure git see it as unstaged. 
2. Do changes in other files so we can have multiple files ready to stage.
3. Open sublime merge from sublime text
4. We can see all files but we cannot see their changes.
5. Force close sublime merge 
6. Remove the 7mb file from the repository.
7. Try again opening sublime merge from sublime text.
8. Now we can see all files changes normally.

**Expected behavior**

Once open sublime merge, we should be able to see all files changes. For long ones, maybe the user shouldn't be able.

**Comment by srbs** [comment]
> Large files are now only diffed when clicked on

I think this might have been remedied in [dev build 1113](https://www.sublimemerge.com/dev) if you'd like to try it out.

**Comment by dpjohnst** [comment]
Closing, as this issue was addressed (diff file size limits, and on-demand diff loading)
