### ISSUE TITLE
Output of pull is in greek

### ISSUE THREAD

**Issue by Levilutz** [sublimehq/sublime_merge#508]
OS: macOS 10.14.5
Build: 1116

Description: 
When pulling from remote, the description of the status is partly or fully greek. 
Interestingly, the same does not occur when pushing. 
Persists through app restarts. 

Steps to reproduce:
1. Have remote repository
2. Pull from remote (with or without external changes to whatever you're pulling)
3. Click the small icon next to the branch name. 
4. Observe Greek

Expected Behaviour:
Output should be in English like the rest of the app / my system language

Screenshots:
![Screen Shot 2019-06-05 at 12 32 54](https://user-images.githubusercontent.com/22489327/58973788-d9299e80-878e-11e9-8d5b-caf54ab66b80.png)
![Screen Shot 2019-06-05 at 12 37 28](https://user-images.githubusercontent.com/22489327/58973796-dcbd2580-878e-11e9-98e8-c2fe95ba4a07.png)

**Comment by Levilutz** [comment]
Greek is the secondary language on my system (I use it when typing math stuff), but English is the primary language. Not sure why Sublime would select the non-default system language.

**Comment by jskinner** [comment]
FWIW, it's Git that's choosing to output Greek here: Sublime Merge doesn't have any sort of language detection in it, but we do shell out to Git for all write operations to the repository, including Pull and Push.

Perhaps switching from the bundled version of Git to the system Git will resolve this for you (via the Preferences dialog)
