### ISSUE TITLE
Rendering Performance Regression

### ISSUE THREAD

**Issue by mbebenita** [sublimehq/sublime_merge#510]
**Version info**

 - OS: 10.14
 - Build: 1116

**Description**

Rendering perf, while scrolling, clicking buttons, etc.. is very poor. ~ 5ps

**Steps to reproduce**

1. Open repository
2. Scroll various views.

This is a regression, I reverted to 1107 and it runs much more smoothly.

**Comment by jskinner** [comment]
1116 disables OpenGL acceleration of macOS 10.14.4 due to a driver mac in macOS. If you update to 10.14.5 the issue should be resolved.
