### ISSUE TITLE
Reuse commit messages from the history

### ISSUE THREAD

**Issue by liborbus** [sublimehq/sublime_merge#514]
**Problem description**
As an User, When I am entering a new commit message, I want to reuse commit messages from the history so that I do not need to manually enter the whole message again or find / copy / paste the message from the Commit History.

**Preferred solution**
When I press Arrow Down in the Commit Message field then display list of N last matching messages from which I can pick one to be reused. For example, when I press Arrow Down with empty Commit Message field list of last 10 messages is displayed, however, when I enter "xyz" and press Arrow Down then only the last 10 messages matching "xyz" text appears.

**Alternatives**
Provide a button next to the Commit Message text field to display list of N last commit messages and pick one to be reused.

**Comment by mr-potato-head** [comment]
+1, essential feature for me too. Awesome software otherwise.

**Comment by totorokun** [comment]
this is useful when the commit message contains a ticket code that helps link commits to features / bugs. an automatic way of extracting that from the branch name would be great too

**Comment by troygNZ** [comment]
Yes please! As per previous comments, we prefix commit messages with the JIRA or DevOps feature #, and don't want to re-type them where possible.

**Comment by srbs** [comment]
This has been added in build 1201+, including stable build 2020.
