### ISSUE TITLE
Add ability to push with --no-verify flag to disable hooks

### ISSUE THREAD

**Issue by MatthewKelly** [sublimehq/sublime_merge#516]
#173 added the ability to commit with the --no-verify flag

It would be handy to have the same option when pushing, so that the push hooks can be skipped.

**Comment by haritonasty** [comment]
Any updates here?

**Comment by dpjohnst** [comment]
Hi all,

Just following up that this available in the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan
