### ISSUE TITLE
Robot nested '${}' syntax highlighting is off

### ISSUE THREAD

**Issue by stdedos** [sublimehq/sublime_merge#522]
**Version info**

 - OS: Ubuntu 16.04.5
 - Build: 1116

**Description**

Robot nested `${${}}` syntax highlighting is off

**Steps to reproduce**

A variable `${named.like.${this}}` will have the last `}` black

**Expected behavior**

Self-explanatory: nesting of `${` should be counted

**Screenshots**

Self-explanatory

**Comment by srbs** [comment]
What syntax language is this for?

If it is a built-in language, you will need to file this bug in the Packages repository (https://github.com/sublimehq/Packages/issues) as Sublime Merge & Sublime Text both use that repo for syntax languages.

If it powered by a plugin that has been added to Sublime Text (SM piggy backs on ST plugins), you would need to report this bug in that plugin's respective bug tracker.

**Comment by stdedos** [comment]
> (SM piggy backs on ST plugins)
That's a suprise! :smiley:

Well, I guess then it has to go to https://github.com/andriyko/sublime-robot-framework-assistant

**Comment by srbs** [comment]
Yeah, it's definitely not always expected. Keep in mind, it's only for syntax definitions: https://www.sublimemerge.com/docs/packages#installing_packages
