### ISSUE TITLE
Open in Visual Studio Code

### ISSUE THREAD

**Issue by ahmetcetin** [sublimehq/sublime_merge#525]
**Problem description**

Open in Editor... opens in Sublime Text

**Preferred solution**

I would like to have an option to select which editor to use. I'm using vsc mostly for development, I have sublime text as well but I'm using it for quick fix, etc.

**Alternatives**

It can also shows available options when clicking on Open in Editor...

**Comment by srbs** [comment]
In the preference, there is a setting for `Editor Path`. You should be able to make it work with that setting.

**Comment by ahmetcetin** [comment]
indeed, just found it, but still there is a problem as SM is passing the filename together with line and column params. it results vsc to open a new file instead of showing the existing file.

there is --goto parameter which results vscode to navigate to the given line:
https://github.com/Microsoft/vscode/issues/11731

i tried entering this line in Editor path option:
/usr/local/bin/code --goto

it just didn't work, it didn't even open vscode at all.

**Comment by YellowAfterlife** [comment]
You would want to use "Editor Argument Format" (immediately below the Editor Path) for that, like so:
```
--goto ${file}:${line}:${col}
```

**Comment by srbs** [comment]
See also https://forum.sublimetext.com/t/sublime-merge/38962/17 and possibly https://forum.sublimetext.com/t/setting-vs-code-as-editor-on-ubuntu/42243.

**Comment by ahmetcetin** [comment]
@YellowAfterlife there is no "Editor Argument Format" field in Advanced tab. I'm using build 1116.
<img width="795" alt="Untitled1" src="https://user-images.githubusercontent.com/5046786/60973153-fa4e5380-a327-11e9-9405-2ddb88233f0b.png">

I tried to use "vscode --goto ${file}:${line}:${col}" in Editor Path, but didn't work either.

**Comment by YellowAfterlife** [comment]
Does for me. Windows<->Mac difference perhaps?
![image](https://user-images.githubusercontent.com/731492/60979224-fc6ddd80-a33a-11e9-80b9-24dd6cf416af.png)

**Comment by srbs** [comment]
Yeah, the Editor Argument Format setting is not there on macOS for some reason. However, @ahmetcetin, you should be able to set the `editor_argument_format` property (as seen in my first link) in the settings file yourself (`Preferences` -> `Edit Settings...`).

**Comment by ahmetcetin** [comment]
Cool, that made the trick thx a lot @srbs, @YellowAfterlife ! Somehow I miss it in the first link.
