### ISSUE TITLE
Add `--no-ff` option when merging a branch

### ISSUE THREAD

**Issue by willrowe** [sublimehq/sublime_merge#53]
**Problem description**
When running the `Merge Branch` command there is no option to always create a merge commit.

**Preferred solution**
Display options similar to the `Push` command:
- `merge`
- `merge --no-ff`

**Alternatives**
- A setting could be added to always do this when merging.
- A separate merge command could be added to the command palette.

**Screenshots**
The current `Push` command options:
![push-command](https://user-images.githubusercontent.com/7152423/46431115-edf1f600-c718-11e8-8058-1e47f1150077.png)

**Comment by jskinner** [comment]
This is now implemented in Dev Build 1076 at https://www.sublimemerge.com/dev
