### ISSUE TITLE
SublimeText: Relative paths in sublime-project get rewritten as absolute paths

### ISSUE THREAD

**Issue by mulle-nat** [sublimehq/sublime_merge#534]
**Version info**

- OS: macOS 10.14, Ubuntu 19.04
- Build: 3207

**Description**

I use sublime-project files in a cross platform manner. The relative project structure is identical. But on Linux it's /home/... and on MacOS its /Users/..
This gets periodically rewritten, probably when somethings is changed and then all relative source paths like `"path": "../srcM/mulle-bashfunctions"` get rewritten as absolute paths and stop working on the other platform.

**Steps to reproduce**

Start with:

```
{
	"folders":
	[
		{
			"path": "../srcS/mulle-compile"
		},
		{
			"path": "../srcM/mulle-bashfunctions"
		}
	]
}
```

Now add another folder and see how paths get absolute:

```
{
	"folders":
	[
		{
			"path": "/Volumes/Source/srcS/mulle-compile"
		},
		{
			"path": "/Volumes/Source/srcM/mulle-bashfunctions"
		},
		{
			"path": "/Volumes/Source/SimFinger"
		}
	]
}
```

**Expected behavior**

Should not rewrite existing relative paths.

**Screenshots**

**Comment by mulle-nat** [comment]
Sorry. I noticed a little late, that this is probably only for sublime merge ?

**Comment by srbs** [comment]
Yes, close this one & create a new one in the Sublime Text issue tracker: https://github.com/SublimeTextIssues/Core/issues
