### ISSUE TITLE
Provide locale.exe on Windows

### ISSUE THREAD

**Issue by ryanpcmcquen** [sublimehq/sublime_merge#536]
**Version info**

 - OS: Windows 10
 - Build: 1116

**Description**

When using Sublime Merge's `git` executable in the command line, it becomes apparent that a necessary binary is missing. Since `env.exe` expects `locale.exe`, would you mind providing it?

**Steps to reproduce**

1. Add `C:\Program Files\Sublime Merge\Git\cmd` to your `PATH`.
2. Open a new cmder window/tab.

**Expected behavior**

No errors would appear.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/772937/60765130-ff6e8280-a049-11e9-95ad-202eb256130c.PNG)

**Comment by dpjohnst** [comment]
Hi @ryanpcmcquen,

Could you confirm if you're still experiencing this issue?

I'm going to tentatively close the issue given the amount of time passed, but please re-open this if you're still affected by it.

Kind regards,
\- Dylan from Sublime HQ

**Comment by ryanpcmcquen** [comment]
I probably found a workaround.
