### ISSUE TITLE
Wrap command line output of git commands

### ISSUE THREAD

**Issue by sakekasi** [sublimehq/sublime_merge#538]
**Problem description**

I have a precommit/prepush hook that has some very long lines in its output. When these lines come out, the command line output looks like it's forcibly scrolled to the right. 

**Preferred solution**

Wrap the command line output of commands so that the output fits in the window width

**Alternatives**

Allow scrolling of the command line output of commands

**Screenshots**

If applicable, add screenshots to help demonstrate the problem or proposed solution. This section may be omitted/removed.

<img width="1440" alt="Screenshot 2019-07-10 12 35 26" src="https://user-images.githubusercontent.com/979969/60999126-37f2b280-a30f-11e9-9633-a80e1b52e930.png">

**Comment by srbs** [comment]
related: 343

**Comment by willrowe** [comment]
As I have commented on the other issue, this really needs to be address. It causes a lot of the output to be inaccessible.

**Comment by davidbonnet** [comment]
Experience is great, until I looked at the console… I won't register until this simple-to-fix bug is gone.

**Comment by markomarkovic** [comment]
This is still an issue with the new command history functionality as shown in the screenshot below. There's already a horizontal scroll in the output section, just the whole dialog needs a hard limit on the width.

![20200204113947-3840x2160](https://user-images.githubusercontent.com/99233/73724775-85b88780-4745-11ea-93a4-fb701517acef.png)

**Comment by willrowe** [comment]
I can confirm that this is still an issue because it becomes wider than the viewable screen with no way to view it.

**Comment by DanielPower** [comment]
This is also a deal breaker for me. I can't consider using a tool that entirely prevents me from reading console output.

**Comment by willrowe** [comment]
I can confirm that this has been fixed in build 2002. It now stays at a smaller width and allows full scrolling.

**Comment by sakekasi** [comment]
when will build 2002 make it out to the release?

**Comment by jskinner** [comment]
Dev builds are available at https://www.sublimemerge.com/dev
