### ISSUE TITLE
Bold-looking text on @1x displays on macOS Mojave

### ISSUE THREAD

**Issue by doersino** [sublimehq/sublime_merge#54]
**Version info**

 - OS: macOS 10.14
 - Build: 1065

**Description**

After upgrading to Mojave today (from Sierra – no idea if this issue affects High Sierra), I noticed that all text in Sublime Merge looks noticeably bolder than in other apps (including Sublime Text Build 3176). This manifests itself only on external monitors (the ones I have access to are all @1x), not on my laptop's built-in @2x screen.

I assume this has to do with Apple's removal of subpixel-smoothed text rendering.

**Steps to reproduce**

Use Sublime Merge on an @1x screen connected to a computer running macOS Mojave.

**Expected behavior**

Nice text rendering.

**Screenshots**

![screenshot 2018-10-03 at 21 02 27](https://user-images.githubusercontent.com/1944410/46432887-a9358180-c74f-11e8-85bd-aa68caa58af8.png)

**Comment by wbond** [comment]
Are you using dark mode?

**Comment by doersino** [comment]
No, light mode – but I just tried switching to dark mode and the problem persists.

**Comment by petert82** [comment]
I'm seeing the same on my MacBook Air's built in (@1x) screen. Text is oddly bold-looking, especially in lines that are being highlighted as an addition/removal in the stage/commit view.

I'm using the same macOS version and Sublime Merge build as reported in the OP.

**Comment by wbond** [comment]
We’ve reproduced this and are working on a fix. Beyond removing subpixel antialiasing from Mojave, Apple seems to have made other changes.

**Comment by jskinner** [comment]
Thanks for the report, this is now fixed in 1070
