### ISSUE TITLE
Add vertical navigation when viewing changes

### ISSUE THREAD

**Issue by pindamonhangaba** [sublimehq/sublime_merge#544]
**Problem description**

Currently we can only navigate committed and changes files with an accordion. It's very hard to navigate and there is no way to easily parse what has been changed or committed at a glance.

**Preferred solution**

A vertical menu to the right, showing a list of changed/committed files.

**Alternatives**

Gitkraken has done this to great success, even having the option of showing filenames vs folder structure.

**Comment by dpjohnst** [comment]
Closing as the Files tab is now present in Sublime Merge.
