### ISSUE TITLE
Resizing the commits pane rounds tag up to nearest integer

### ISSUE THREAD

**Issue by dotherightthing** [sublimehq/sublime_merge#556]
**Version info**

 - OS: macOS 10.12.6
 - Build: 1116

**Description**

When the commits pane is manually resized to become narrower, the content in the yellow commit tag changes. For example, `0.8.4` is rounded up to `1`.

**Steps to reproduce**

1. Open repository https://github.com/dotherightthing/generator-wpdtrt-plugin-boilerplate
2. Locate a yellow commit tag, where merge information is also displayed
3. Resize the commit pane so that it becomes narrower
4. Observe the change in the contents of the yellow commit tag

**Expected behavior**

* a `0.n.n` tag is shortened to `0`
* a `1.n.n` tag is shortened to `1`
* a `2.n.n` tag is shortened to `2`
* etc

**Screenshots**

(1) A wider commits pane. Note that both `0.n.n` tags display in full.

![Two commit tags, within a wider commits pane](https://user-images.githubusercontent.com/638871/63073854-bd0c5f80-bf7e-11e9-8f88-9b5e3003f679.png)

(2) A narrower commits pane. Note that the first `0.n.n` tag has been shortened and rounded up to `1`.

![Two commit tags, within a narrower commits pane](https://user-images.githubusercontent.com/638871/63073876-d1505c80-bf7e-11e9-9009-f57b1a79f787.png)

**Comment by srbs** [comment]
@dotherightthing, Sublime Merge is not rounding but is instead showing quantity. If you continue making the commit pane thinner, you'll notice that the `origin/development` & `origin/master` will collapse into a purple `2`.

**Comment by dpjohnst** [comment]
Thanks for sharing this feedback.

As @srbs mentioned, this is expected behavior as it's showing the count of tags on the commit. You can then hover over this summary to display a tooltip with the individual tag names.
