### ISSUE TITLE
Make combining of combining characters optional

### ISSUE THREAD

**Issue by rimvaliulin** [sublimehq/sublime_merge#558]
Example for arabic language:
![Screen Shot 2019-08-19 at 19 27 53](https://user-images.githubusercontent.com/5262175/63273591-b13ed700-c2b7-11e9-85fb-ec2ac9bcb092.png)

**Comment by srbs** [comment]
This is the repo for Sublime Merge, the Sublime Text repo is [here](https://github.com/SublimeTextIssues/Core/issues).
