### ISSUE TITLE
Feature request: Hide menu bar

### ISSUE THREAD

**Issue by jcassee** [sublimehq/sublime_merge#56]
**Problem description**

Because of shortcuts and ctrl-shift-p, the menu bar is often not needed. Hiding it would add some useful vertical space.

**Preferred solution**

An option to remove the menu bar, similar to Sublime Text.

**Comment by abjugard** [comment]
Would be nice to be able to hide it for those of us who have paid for a license and are using the dark theme, the contrast difference between my dark window border, the white menu bar, and the dark application theme looks hideous, example attached.

![image](https://user-images.githubusercontent.com/287697/48340080-fddeed00-e669-11e8-901d-b36fa5067e75.png)

**Comment by jskinner** [comment]
Dev Build 1089 now has a preference to hide the menu bar on Windows and Linux - https://www.sublimemerge.com/dev

**Comment by jcassee** [comment]
Note that the help text says "Auto hide menu until alt is pressed", but pressing Alt does not show the menu for me. (A similar function in Firefox does.)
