### ISSUE TITLE
Add `date-range` keyword to search query syntax

### ISSUE THREAD

**Issue by Zooce** [sublimehq/sublime_merge#571]
**Problem description**

When searching for changes, the query syntax should also allow a date range to be specified.

**Preferred solution**

_Updated based on comment by @srbs below, with the addition of an `on` keyword._
```
# find all changes between May 20, 2019 and June 20, 2019
after:"2019-05-19" and before:"2019-06-21"

# find all changes on May 20, 2019
on:"2019-05-20"

# find all changes not on May 20, 2019
not on:"2019-05-20"

# find all changes on or after May 20, 2019
after:"2019-05-19"

# find all changes after (not on) May 20, 2019
after:"2019-05-20"

# find all changes on or before May 20, 2019
before:"2019-05-21"

# find all changes before (not on) May 20, 2019
before:"2019-05-20"
```

**Alternative 1**

Add a single `date-range` keyword. This might require a more sophisticated syntax for specifying min/max dates. However, this could also enhance the behavior.
```
# find all changes between May 20, 2019 and June 20, 2019
date-range:"2019-05-20"-"2019-06-20"

# find all changes on May 20, 2019
date-range:"2019-05-20"

# find all changes not on May 20, 2019
not date-range:"2019-05-20"

# find all changes on or after May 20, 2019
date-range:>="2019-05-20"

# find all changes after (not on) May 20, 2019
date-range:>"2019-05-20"

# find all changes on or before May 20, 2019
date-range:<="2019-05-20"

# find all changes before (not on) May 20, 2019
date-range:<"2019-05-20"
```

**Alternative 2**

Add `min-date` and `max-date` keywords to the query syntax. However, this doesn't cover as many cases.
```
# find all changes between May 20, 2019 and June 20, 2019
min-date:"2019-05-20" and max-date:"2019-06-20"

# find all changes on or after May 20, 2019
min-date:"2019-05-20"

# find all changes on or before May 20, 2019
max-date:"2019-05-20"
```

**Comment by srbs** [comment]
I agree on the date filtering idea. However, I think it would be most straightforward for most users to use the terms `before`/`after` instead of `min`/`max` or the complexity of `date-range`.

**Comment by pasnox** [comment]
Was about to report an issue for that as well, so it's clearly a +1 from me !

**Comment by BenjaminSchaaf** [comment]
We've got an implementation of this in the pipeline

**Comment by Zooce** [comment]
Build 2000 has this! Thank you!!

**Comment by srbs** [comment]
@Zooce, feel free to close the issue.
