### ISSUE TITLE
"Open Recent" always empty

### ISSUE THREAD

**Issue by richardeakin** [sublimehq/sublime_merge#574]
**Version info**

 - OS: Windows 10, Version	10.0.18362 Build 18362
 - Build: 1116

**Description**

I use Sublime Merge every day, however when I look at the "Open Recent" menu, it is always empty, with the only item in the submenu being "select...". When I open that pane, it is also empty, like this:

![image](https://user-images.githubusercontent.com/5132127/64545687-2f126300-d2f7-11e9-9018-2e01cafb5d70.png)

**Comment by jkrehm** [comment]
I have had similar issues. Fiddling with `C:\Users\<user>\AppData\Roaming\Sublime Merge\Local\Session.sublime_session` sesms to have fixed the problem, but clearly that's not ideal.

**Comment by dpjohnst** [comment]
Hi all,

Could you confirm if you're still experiencing this issue?

I'm going to tentatively close the issue given the amount of time passed, but please re-open this if you're still affected by it.

Kind regards,
\- Dylan from Sublime HQ
