### ISSUE TITLE
Feature request: Forward/Back through commits

### ISSUE THREAD

**Issue by lannierose** [sublimehq/sublime_merge#581]
I have a branch with sparse commits, so I have to scroll and watch carefully to find the previous commit in the chain. It would be so cool if Control or Shift changed the function of the Forward/Back buttons to Next Commit/Previous Commit. (I actually thought they were already doing that, but it was just because I had manually paged through a bunch of commits.)

**Comment by srbs** [comment]
> a branch with sparse commits

There is another way to visualize & navigate within Sublime Merge if you're looking at a single branch. In the location bar (left most icon on toolbar), there are eye icons on the right hand side of each row that indicates what branches/tags/etc are visible. Alt/Option+clicking the eye will hide all other branches/commits & only show the one you want. This will allow you to use solely the up & down arrows to navigate around the commit history.

Note: the command palette has commands for these as well (`Hide Branch...` & `Hide All Branches Except...`)


> scroll and watch carefully to find the previous commit

The parent commit hash(es) in the commit details section are clickable & will navigate to the respective parent(s). Once clicked, the back button & subsequently forward buttons will start working as expected. Also note that there is the menu item `Navigate`->`Go to Parent` that works as well and can be assigned to a keyboard shortcut if so desired.

**Comment by lannierose** [comment]
Very clever, srbs! I'll use those techniques. Thanks.

**Comment by srbs** [comment]
@lannierose, if you didn't see, Sublime Merge 2 (build 2020+) supports both `Navigate` -> `Go to Parent` & `Navigate` -> `Go to Child` (keyboard shortcuts shown in the menu).

**Comment by dpjohnst** [comment]
Hi all,

As @srbs mentioned, this has been implemented from build 2020 onwards.

Thanks,
\- Dylan
