### ISSUE TITLE
Search by author doesn't return all commits

### ISSUE THREAD

**Issue by safield** [sublimehq/sublime_merge#583]
Windows  version 10.0.18362 Build 18362
Sublime Merge version: Dev Channel Build 1118

I am trying to search for a commit by and author. I have the author and the commit hash.

When I search by commit hash, the commit shows up, when I search by author, the commit doesn't show up (and my other arbitrary commits are missing.

When I search by commit, I then look at the commit details, and take the exact author name that Sublime Merge shows me in the commit, and use it to search, so I don't believe there are any typos in the name.

Nothing has change in my git user settings to have warranted any change is the user doing these commits.

**Comment by srbs** [comment]
Are you correctly quoting the search term? i.e. `author:"my name"`

Can you share the repo & search term, or reproduce it in another repo (or new repo)?
