### ISSUE TITLE
Expand Selection Case Sensitivity Control

### ISSUE THREAD

**Issue by personalnadir** [sublimehq/sublime_merge#585]
I am not sure if this is a bug, as despite using Sublime Text for many years, I never noticed (or forgot) that toggling case sensitivity on the find pane also modifies the behaviour of the expand selection command.

If this is intentional, then I think they should be separated as from a usability perspective I don't think there is anything that ties them together. I would expect a modifier key would instead toggle how the expand selection command functions, or an option in the command palette. 

My instinct when I noticed this changed behaviour was to:
1. Check the selection drop down menu
2. Check sublime preferences
3. Check the change log 
4. Check the sublime forums
5. Check the find palette

That says to me that they should be independent.

**Comment by srbs** [comment]
This is the repo for Sublime Merge, the Sublime Text repo is [here](https://github.com/SublimeTextIssues/Core/issues).

**Comment by personalnadir** [comment]
Ah, my mistake. Thanks have posted it in the correct location.
