### ISSUE TITLE
Improvement in Switch Repository

### ISSUE THREAD

**Issue by djibarian** [sublimehq/sublime_merge#59]
**Problem description**

When using Switch Repository the selection stays in the current one.

**Preferred solution**

It would be better to replicate the functionality in Sublime Text where the selected repository is the previously used.

**Alternatives**

A description of any alternative solutions or enhancements considered.

**Screenshots**

If applicable, add screenshots to help demonstrate the problem or proposed solution. This section may be omitted/removed.

**Comment by dpjohnst** [comment]
Hi @djibarian,

Thanks for sharing this feedback - this has been addressed as of Sublime Merge Build 2054 (stable).

Thanks,
\- Dylan

**Comment by djibarian** [comment]
Good improvement, thanks. I noticed that for SM the current project doesn’t appear in the list, as opposite as in ST, which it does. Although perfectly functional in both cases, that different behaviour between SM and ST is a bit confusing.
