### ISSUE TITLE
Scrollbars are displayed even if there is enough space for the list

### ISSUE THREAD

**Issue by Drovosek01** [sublimehq/sublime_merge#593]
**Version info**

 - OS: Windows 10 v1809
 - Build Sublime Merge: 1119

**Description**

I noticed a strange behavior of the sidebar, which displays a list of modified files and a visual display of changes to them.

I made changes to my repository in just 2 files. They fit in the sidebar, but I can still spin the mouse wheel in that pane, but why would it if everything fits.
The problem is that I often have such cases when I scroll the wheel in this panel and the list of changed files is hidden from view and when I quickly look there, I do not see the list of files that I have changed. It's very frightening.

A description of what the bug is.

**Steps to reproduce**

1. Open any repository in Sublime Merge.
2. Make changes to multiple files.
3. Open Sublime Merge, move the mouse cursor to the right side of the window and rotate the mouse wheel until the list of modified files moves up and disappears from view.

**Expected behavior**

I expected that if there is enough space in the window to display the entire list, then the scroll bar will not appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/29478700/66855767-8d80d000-ef8c-11e9-8227-7c454cf34db6.png)
![image](https://user-images.githubusercontent.com/29478700/66855811-9d98af80-ef8c-11e9-9be1-ba586f6947b0.png)

Video: https://sendvid.com/2e0dqg85

**Comment by srbs** [comment]
Sublime Text has had the `scroll_past_end` setting default to `true` (see snippet below), so it stands to reason that Sublime Merge would default to this behavior as well.
```
// Set to false to disable scrolling past the end of the buffer.
"scroll_past_end": true
```

It would be nice to be able to enable or disable the behavior in each location (diff context, sidebar, merge window/editor, etc).

**Comment by Drovosek01** [comment]
> Sublime Text has had the `scroll_past_end` setting default to `true` (see snippet below), so it stands to reason that Sublime Merge would default to this behavior as well.
> 
> ```
> // Set to false to disable scrolling past the end of the buffer.
> "scroll_past_end": true
> ```
> 
> It would be nice to be able to enable or disable the behavior in each location (diff context, sidebar, merge window/editor, etc).

That's an interesting idea.

I opened the "Preferences" panel and clicked "Edit Settings..." and opened the file in Notepad++, copied and pasted your code, saved the file, and restarted Sublime Merge.
Unfortunately the miracle did not happen and the Sublime Merge behavior when scrolling in the sidebar has not changed.

I opened the file `C:\Program Files\Sublime Merge\Packages\Default.sublime-package\` archiver and looked at the standard settings and there the property you mentioned is already set to true.

So, I believe there is a scrolling bug in Sublime Merge for Windows.

![image](https://user-images.githubusercontent.com/29478700/67264123-cfd96e00-f4b2-11e9-9211-e8b8a3d0f882.png)

**Comment by srbs** [comment]
> Unfortunately the miracle did not happen and the Sublime Merge behavior when scrolling in the sidebar has not changed.

That is correct (the setting doesn't work for me either). Remember that the setting in ST is specifically for the ST editor component and most of SM is editor components _embedded_ in other views & structures thus not allowing the setting to take effect.

**Comment by dpjohnst** [comment]
Hi all,

Could you confirm if you're still experiencing this issue? I believe this was fixed in a much earlier build.

I'm going to tentatively close the issue given the amount of time passed, but please re-open this if you're still affected by it.

Kind regards,
\- Dylan from Sublime HQ
