### ISSUE TITLE
Squashing against the initial commit produces errant 'rebase' state

### ISSUE THREAD

**Issue by mdwhatcott** [sublimehq/sublime_merge#594]
**Version info**

 - OS: macOS 10.14.6
 - Build: 1119

**Description**

When squashing a set of commits that includes the first commit in the repo's history, the operation fails with an error message being displayed (see screenshot). Also, as a result of the failure the repository is now in a very strange state, indicated by the terminal output of `git status` shown below.

**Steps to reproduce**

1. create new directory
2. cd to new directory
3. run `git init`
4. touch a file and commit it
5. touch another file and commit it
6. open sublime merge
7. select both commits, right click, expand "Edit Commit", then select "Squash Selected Commits"
8 . The error will be displayed (and the commits will NOT have been squashed as expected)
9. in the terminal, run `git status` to see the strange terminal output below

_Any attempt to exit the errant 'rebase' state fails._

**Expected behavior**

It should just merge the commits without error.

**Screenshots**

### Before attempting to squash the first two commits:

<img width="1792" alt="Screen Shot 2019-10-16 at 10 42 35 AM" src="https://user-images.githubusercontent.com/202910/66940776-c78cb900-f002-11e9-8e8c-726304296eee.png">

### The error message displayed after squashing the first two commits:

<img width="1792" alt="Screen Shot 2019-10-16 at 10 42 49 AM" src="https://user-images.githubusercontent.com/202910/66940777-c78cb900-f002-11e9-816b-21967d0d9ca4.png">

### Terminal output of `git status` after attempting the squash in sublime merge.

```
$ git status
On branch master
git-rebase-todo is missing.
No commands done.
No commands remaining.
You are currently editing a commit while rebasing branch 'master' on '(null)'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working tree clean
```

### Running git rebase --continue fails:

```
$ git rebase --continue
error: could not read '.git/rebase-merge/onto': No such file or directory
```

### Running git commit --amend doesn't exit the rebase state either.

```
$ git commit --amend
[master beb0569] squash: a & b
 Date: Wed Oct 16 10:42:09 2019 -0600
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 b.txt

$ git status
On branch master
git-rebase-todo is missing.
No commands done.
No commands remaining.
You are currently editing a commit while rebasing branch 'master' on '(null)'.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working tree clean
```

**Comment by srbs** [comment]
A way out of the errant 'rebase' state:
```
echo master > .git/rebase-merge/onto
git rebase --abort
```


It looks like Sublime Merge just needs to identify if the root commit is being used & to pass in the `--root` argument instead of a commit range.

**Comment by mdwhatcott** [comment]
@srbs  - Ah, thanks!. I was unsure what the contents of that file should be. I think for now I'll just make sure NOT to rebase against the room commit--but it's good to know there's a way out.

**Comment by srbs** [comment]
@mdwhatcott, I'm not even 100% sure if the file content is correct either, it just didn't fail when I ran `--abort` (& I'm assuming the abort cleans things up correctly as well).

**Comment by mdwhatcott** [comment]
@srbs Acknowledged.

**Comment by dpjohnst** [comment]
Hi all,

Just following up here - this should be fixed in the latest development build of Sublime Merge.

Thanks,
\- Dylan
