### ISSUE TITLE
merge --no-ff ancestor not shown in history tree

### ISSUE THREAD

**Issue by squiddie** [sublimehq/sublime_merge#603]
OS: Windows 10
Build: 1119

The commit and line down to a branch merged with --no-ff are completely missing.

Reproduce:
- Create two branches on the same commit.
- Make a few commits on branch 1.
- merge --no-ff branch 2 into branch 2.
- There should be two lines in the diagram but the straight line down to the original commit is missing.

Screenshot:
- left: sublime merge without the line
- right: other tool showing the missing line.

![no-ff-bug](https://user-images.githubusercontent.com/23278/67468369-a5bab400-f64a-11e9-817d-93bc73c03c9f.png)

**Comment by srbs** [comment]
If you look to the left of the selected commit (with message `Merge master into [...]`), you'll see an empty blue box. When you click on it, it'll open/expand the merge commit's children and you should see your missing line.

The setting that powers this behavior is `expand_merge_commits_by_default`.

See also https://forum.sublimetext.com/t/sublime-merge-tree-view/40808, #305

**Comment by squiddie** [comment]
Awesome, thank you, that did it.
