### ISSUE TITLE
Add functionality for generating statistics

### ISSUE THREAD

**Issue by erazor-de** [sublimehq/sublime_merge#609]
In extension to issues #346 and #224 which suggest showing a summary of line modifications like git option '--stat' does, I would go a step further and suggest a more extensive statistics solution which not only shows totals per commit but a commit range, branch, per user etc. A reference for this functionality could be the [git-quick-stats](https://github.com/arzzen/git-quick-stats) project which does part of this.

**Comment by Codinablack** [comment]
I have looked everywhere in sublime merge and can't find this feature anywhere... how exactly does one enable sublime merge to show the line change count?
