### ISSUE TITLE
Add functionality to use templates for commit messages

### ISSUE THREAD

**Issue by berkanteber** [sublimehq/sublime_merge#612]
**Problem description**

Using templates for commit mesages may improve the quality of commit messages by enforcing a standard. However, there is currently no way to use templates for commit  messages in Sublime Merge.

**Preferred solution**

Git already provides a way to use templtes for commit messages by setting `commit.template`. I think the best solution would be to directly use this setting. 

**Alternatives**

This can performed be done by setting templates from Sublime Merge independent from git settings. This approach may be more flexible by allowing to select a template from a list, but I think adhering to the git configuration would be better.

**Comment by onmyway133** [comment]
I need this feature too. Found a thread https://forum.sublimetext.com/t/commit-message-template/44643 but it didn't work for me

**Comment by taebox** [comment]
+1

**Comment by ivanglushko** [comment]
Still needed. Or just having prefix/suffix would be great. Like I always start my commit message based on my current brunch name and number

**Comment by stinos** [comment]
> Like I always start my commit message based on my current brunch name and number

Sorry for the off-topicness, but: I'm not sure what you mean, can you elaborate? You include the branch name in each commit messages?

**Comment by ivanglushko** [comment]
> > Like I always start my commit message based on my current brunch name and number
> 
> Sorry for the off-topicness, but: I'm not sure what you mean, can you elaborate? You include the branch name in each commit messages?

Yes basically I have tasks on jira which start like this MYAPP-434 // Where is myApp is the name of the app and number is the issue / feature number on jira.
Full commit message looks like this.

MYAPP-434 // Implemented scrolling

**Comment by stinos** [comment]
Aha, that's the issue number though, which might or might not be the same as the branch name :)

**Comment by ivanglushko** [comment]
> Aha, that's the issue number though, which might or might not be the same as the branch name :)

For me it's always the same unless it's a problem with no ticket. 
Anyways having some prefixes and suffixes would be great 😊 
Thanks!

**Comment by dpjohnst** [comment]
Hi all - support for the Git config variable `commit.template` was added in Sublime Merge Build 2057 (development build) and will be available in the next stable build :)

Cheers,
\- Dylan

**Comment by ivanglushko** [comment]
@dpjohnst 

Dylan you're a hero! 
Thank you so much 🥰 
I'm very excited for this feature to come. Yay!

**Comment by dpjohnst** [comment]
Hi all,

Just a quick note that this is now available in the latest stable build of Sublime Merge (2059).

Cheers,
\- Dylan from Sublime HQ
