### ISSUE TITLE
stash pop hits bug in git 2.24.0

### ISSUE THREAD

**Issue by stevenkaras** [sublimehq/sublime_merge#615]
**Version info**

 - OS: Ubuntu 16.04
 - Build: 1119
 - Git: 2.24.0

**Description**

When editing commit messages, I have a habit of hitting <kbd>ctrl</kbd>+<kbd>s</kbd>. After upgrading git to the latest version, there is [apparently an issue][git-stash-quiet-bug] with `git stash` and the `--quiet` flag. The gist of the bug is that it clears the index, making it appear that all the files in the repository have been removed. This leads to SublimeMerge listing every single file as removed and for large repositories causes a huge spike in memory usage (for reference, this happened in our monorepo and SM jumped from ~160MB resident to around 2.4GB).

[git-stash-quiet-bug]: https://public-inbox.org/git/20191113111539.GA3047@cat/T/

I don't necessarily expect SublimeMerge to do anything with this bug, but hopefully it will be easier to discover than the git bug and show up in search results and save someone else searching for the relevant bug reports for an hour.

**Steps to reproduce**

1. Make some changes in a repository.
2. Stash those changes
3. Pop the stash

**Comment by Bjarno** [comment]
The same issue is happening on my system. Really confusing behavior of Sublime Merge.

**Comment by stdedos** [comment]
> I don't necessarily expect SublimeMerge to do anything with this bug

I would expect that I could "hack" the command not to be quiet, for the time being :-D

**Comment by stevenkaras** [comment]
Looks like there is an actual bug here:

![sublime-merge-stash-pop](https://user-images.githubusercontent.com/322377/69621068-189ebc80-1047-11ea-9454-16c00260f8ae.png)

it should show that it's running `git stash pop -q`

**Comment by mwean** [comment]
This is happening for me also, and it usually crashes the app. I use stashes all the time in Tower, and I've never had this issue, so there must be some way around it.

**Comment by themilkman** [comment]
I also saw this behavior under linux. I'd hope that the git devs will respolve it soon.

**Comment by martijnboers** [comment]
Also affected, subscribing

**Comment by themilkman** [comment]
If I see it correctly (couldn't test it yet) it should be resolved in git 2.25 (see https://github.com/git/git/blob/v2.25.0/Documentation/RelNotes/2.25.0.txt )

**Comment by themilkman** [comment]
Could just test it, works on my Linux machine as expected again with git 2.25 :+1:

**Comment by stdedos** [comment]
It is so lovely that no-one is responding here ❤️ 

Sublime Text repositories are much more responsive/active, which makes this strange.

**Comment by stevenkaras** [comment]
Looks like this was resolved in sublime merge build 2020 with the release note:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/322377/83255326-e36f5480-a1b8-11ea-8a6f-87405e9e089c.png">

Closing this as a result.

**Comment by themilkman** [comment]
Just for the records, respectively fixed on the [dev Build 1201](https://www.sublimemerge.com/dev) in February :)
