### ISSUE TITLE
Missing "Continue rebase" option

### ISSUE THREAD

**Issue by damianogiusti** [sublimehq/sublime_merge#62]
**Version info**

 - OS: macOS 10.13.6 
 - Build: 1065

**Description**

Missing "Continue rebase" option after resolving a rebase conflict.

**Steps to reproduce**

1. Rebase a branch onto another, obtaining a conflict
2. Resolve the conflict and stage the file
3. Appears the "Commit" button, instead of the "Continue rebase"

**Expected behavior**

The "Continue rebase" button should appear

**Comment by wbond** [comment]
This has been identified and fixed and will be part of the next dev build.

**Comment by jskinner** [comment]
The fix is now in the stable channel with build 1070
