### ISSUE TITLE
Shift+enter does not stage

### ISSUE THREAD

**Issue by AmjadHD** [sublimehq/sublime_merge#629]
**Version info**

 - OS: Windows 10
 - Build: dev 1118 (although the issue predates it)

**Description**

when there are unstaged changes hitting <kbd>shift</kbd>+<kbd>enter</kbd> does not stage any file.
if commit message input is focused it inserts a newline, otherwise does nothing.

**Expected behavior**
hitting <kbd>shift</kbd>+<kbd>enter</kbd> should stage the unstaged file

Note: modify this line in the windows keymap:
`{ "keys": ["shift+enter"], "command": "insert", "args": {"characters": "\n"} },`

**Comment by BenjaminSchaaf** [comment]
I can't reproduce this in build 2005

**Comment by AmjadHD** [comment]
were you able to reproduce it before ?

**Comment by BenjaminSchaaf** [comment]
No. Are you able to reproduce this in 2005?
