### ISSUE TITLE
Crash on Open Repo or New Repo 

### ISSUE THREAD

**Issue by fishtopher** [sublimehq/sublime_merge#63]
**Version info**

 - OS: Win 10 Pro (1803)
 - Build: All public versions (installed and portable) (up to 1065)

**Description**

App crashes almost immediately for me when I try to open or create a new repo from the main screen, or via the menus.

**Steps to reproduce**

1. Select Open Repository or New Repository
2. Select folder 
3. Click OK
4. App closes with no error info.

[Download crash dump here](https://www.dropbox.com/s/jkkrzwgqlara7dt/7b966062-28f5-45e7-bdff-6f296d146b07.dmp?dl=0)

**Expected behavior**

App proceeds without crashing :)

**Screenshots**
Open Repo:
![sublimecrash_open](https://user-images.githubusercontent.com/2338561/46480258-c36f6e00-c7e8-11e8-9a93-631ef197bd07.gif)

Create New:
![sublimecrash_new](https://user-images.githubusercontent.com/2338561/46480276-cec29980-c7e8-11e8-94c2-7106cf1a42cf.gif)

**Comment by jskinner** [comment]
There's a good chance this is fixed in 1070

**Comment by fishtopher** [comment]
It is fixed!

Thank you!
