### ISSUE TITLE
Enhancement request - Show current repo

### ISSUE THREAD

**Issue by 13pixlar** [sublimehq/sublime_merge#631]
**Problem description**
When you are in a repo, the main view does not show what repo that is. This can be confusing and sometimes you are not sure what repo you are currently viewing.

**Preferred solution**
Show the name/slug of the repo in the main view, for example next to the current branch in the top center.

**Comment by sindrijo** [comment]
Are you on mac/linux? On Windows the path of the repo is shown in the window titlebar.

![image](https://user-images.githubusercontent.com/1384288/71994879-d2d63600-3239-11ea-8479-f727e66f37e2.png)

**Comment by 13pixlar** [comment]
Yes. This is on Ubuntu Linux 16.04

**Comment by dpjohnst** [comment]
Hi @13pixlar,

The repository path should be displayed in the title bar of the window. Could you kindly confirm whether you can see it here?

Thanks,
\- Dylan

**Comment by 13pixlar** [comment]
I can confirm that the repository path is NOT displayed in the title bar of the window.

![sm](https://user-images.githubusercontent.com/7256412/76769540-f0290280-679c-11ea-846b-d24d96ed3ac0.png)

This is on Ubuntu Linux 16.04. Sublime Merge build 1116

**Comment by BenjaminSchaaf** [comment]
@13pixlar Are you perhaps using the Unity or a custom gnome theme? None of the default themes put the close button on the right or merge the menu into the title bar.

**Comment by 13pixlar** [comment]
This is stock Ubuntu 16.04 Unity. I did however discover why the repo path was not showing. In the Appearance -> Behavior setting I had "Show the menus for a window" set to "In the window's title bar" and "Menus visibility" set to "Always displayed". 

This caused the repo path to be hidden by the menu. See screenshots:

![unity2](https://user-images.githubusercontent.com/7256412/78771930-3b47c700-7991-11ea-9d07-1178133fbb65.png)
![unity1](https://user-images.githubusercontent.com/7256412/78771932-3be05d80-7991-11ea-8bf6-a51e87327e63.png)

**Comment by BenjaminSchaaf** [comment]
Considering other desktop environments don't do this, and ubuntu has since switched to gnome which doesn't hide the title, nor do other platforms, I think it's fair to close this issue.
