### ISSUE TITLE
Integration with Sublime Text

### ISSUE THREAD

**Issue by nanoant** [sublimehq/sublime_merge#64]
**Problem description**

Would be nice if there is some Sublime Text plugin that integrated with Sublime Merge, e.g. I want to see the blame for the file or see its history. Now, honestly I have no idea how to do it without escaping to command line.

**Preferred solution**

A plugin that will expose some common actions redirecting to Sublime Merge via Command Palette.

**Comment by pvanb** [comment]
A plugin by @sublimehq would definitely be preferred, but as an alternative check out [GitGutter](https://jisaacks.github.io/GitGutter/). It even has [line annotations](https://jisaacks.github.io/GitGutter/settings/#line-annotation) now (which still seem a little buggy).

One feature I'd love to see in such a plugin is the ability to easily show the history of the selected text and navigate between and compare revisions. JetBrains (IntelliJ, etc) does a really good job of this with their Git integration, but I haven't found an equivalent for Sublime Text.

**Comment by deathaxe** [comment]
I have the basic idea to show a popup with the commit message and a link calling Sublime Merge's blame function if a user hovers the line annotation, which would immitate the functionality of VS Code's GitLense. 

But as you already found out the underlying phantom text text being used for line annotation is a bit buggy and causes a couple of users not to like the feature or even disable it. 

Hence I didn't start any effort to create such a popup. 

Doing blame and diff for single files within ST itself seems less useful as it simply does not provide the required GUI infrastructure for that. But if we can jump around between SM and ST using command line calls and arguments well, I think SM will do it.

**Comment by Herteby** [comment]
@deathaxe Yeah, I think rather than inserting features from SM into ST, you could just provide quick shortcuts to jump between them. For example, right click a file and select "view history" in ST, and it will be opened in SM.

Also, having a shortcut in ST to "open project in SM", and a shortcut in SM to "open repo in ST".

**Comment by deathaxe** [comment]
I use the _ExternalTools_ package to open a repository in SM.

In the _Packages/User/ExternalTools.sublime-settings_ I added

```
{
    "apps": [
        {
            "id": "SublimeMerge",
            "name": "Sublime Merge",
            "cmd": [
                "C:\\Apps\\Sublime Merge\\sublime_merge.exe",
                "$file_path"
            ]
        }
    ],
}
```

In _Packages/User/ExternalTools.sublime-settings_

```
// ExternalTools Commands - User
[
    {
        "caption": "Run: Sublime Merge",
        "command": "external_tools_run",
        "args": { "id": "SublimeMerge" }
    }
]
```

**Comment by deathaxe** [comment]
I still hope some of the great changes of SM will find their way to ST as well. The side-by-side diff control and the change indicators of the blame view's scrollbar as well as the extra gutter area would add a lot of value. 

Using the normal gutter for diffs has a couple of disadvantages as it interferes too much with other plugins. Would like to see a better alternative as well. An API to provide a file path or content to diff a view's content against using SM's very fast diff engine would be awesome.

**Comment by srbs** [comment]
This has been done in Sublime Text 3.2 ([docs](https://www.sublimetext.com/docs/3/git_integration.html#sublime_merge)) and Sublime Merge stable [build 1092](https://www.sublimemerge.com/download).

Is this ticket worth closing now?
