### ISSUE TITLE
Fail to "Open Repository in Sublime Text" from submodule

### ISSUE THREAD

**Issue by bornovalov** [sublimehq/sublime_merge#642]
**Version info**

 - OS: macOS 10.15.1
 - Build: 1119

**Description**

Call to "Open Repository in Sublime Text" from submodule opens Sublime Text with empty file instead of submodule folder

**Steps to reproduce**

1. Clone repository https://github.com/githubtraining/example-dependency
2. Run command `git submodule update --init` inside repository root
3. Open new Sublime Merge window from location bar for submodule js
4. In command palette of submodule window call the "Open Repository in Sublime Text"
5. Sublime Text will be opened with new empty file 'js'
<img width="762" alt="image" src="https://user-images.githubusercontent.com/2136506/71393566-b930ce00-263f-11ea-9532-e9afb9e349ae.png">

**Expected behavior**

Submodule folder opened in new sublime text window
<img width="762" alt="image" src="https://user-images.githubusercontent.com/2136506/71393736-8fc47200-2640-11ea-8e6b-6ade11e42bb3.png">

**Comment by srbs** [comment]
Also note: individual file operations `Open in Editor...`, `Reveal in Finder`, & `Copy File Path` don't work from within a submodule either.

This is likely due to the non-fully-qualified behaviors of submodule paths in Sublime Merge (as seen from the result of `Copy File Path`).

**Comment by BenjaminSchaaf** [comment]
We've got a fix in the pipeline for this

**Comment by BenjaminSchaaf** [comment]
Should be fixed in build 2002
