### ISSUE TITLE
Extra slash in the destination path when cloning a repository

### ISSUE THREAD

**Issue by AmjadHD** [sublimehq/sublime_merge#647]
**Version info**

 - OS: Windows 10
 - Build: dev 1118

**Description**

when cloning a repository an extra slash (`\`) is added to the destination path, this results in duplicates in the "Switch Repository" panel if one later opens the same repo via the "Open Repository" command
![sublime_merge_bug](https://user-images.githubusercontent.com/33235928/72382475-a169d880-3719-11ea-8fee-02bc1b38ba54.png)

**Steps to reproduce**

1. Clone a repository

**Expected behavior**

No extra slash is added.

**Screenshots**

Notice that the slash character is redundant:
![alt](https://user-images.githubusercontent.com/33235928/72382136-ea6d5d00-3718-11ea-8052-40e4c3037ffd.gif)

**Comment by dpjohnst** [comment]
Hi @AmjadHD,

Thank you for your feedback! This issue should be resolved in the next build of Sublime Merge.
