### ISSUE TITLE
Push not using branch.<branch>.pushRemote and remote.pushDefault

### ISSUE THREAD

**Issue by ChristopherRogers** [sublimehq/sublime_merge#649]
**Version info**

 - OS: macOS 10.15.2
 - Build: 1119

**Description**

The default remote selected when pushing a branch is not what Git would use natively if you didn't specify the remote when pushing. In Sublime Merge, it seems that the default remote selected is the remote configured in `branch.<branch>.remote`.

**Steps to reproduce**

1. Enter the push command via Command-P.
2. The default remote shown is not the customized one as described one.

**Expected behavior**

It should be checking `branch.<branch>.pushRemote` and `remote.pushDefault` first and using that as the default branch instead.

**Comment by dpjohnst** [comment]
Hi @ChristopherRogers,

Thank you for your feedback! We're investigating this.
I'll let you know when we've got a further update for you.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Following up on the previous post - A new build of Sublime Merge has been released, which adds support for pushRemote and pushDefault: https://www.sublimemerge.com/dev
