### ISSUE TITLE
Preference to display author date instead of commit data on the commit list / respecting system time format

### ISSUE THREAD

**Issue by nanoant** [sublimehq/sublime_merge#65]
**Problem description**

Currently on the list I can see the commit dates, and I need to select particular commit in order to see author date. This is usually the same date, unless you rebase, then all rebased commits have rebase date.

Since often I am the author and a commiter :) I would prefer to see clearly when I have made the changes, not when I rebased.

And btw. my system is using European 24h hour format, but Sublime Merge uses 12h PM/AM format. Can we please make it an option or respect current system setting?

**Preferred solution**

A setting to switch between commit and author data (or both?), and 12h/24h or respecting system format settings.

**Comment by doersino** [comment]
+1 re. time format.

**Comment by jskinner** [comment]
Added in 1083

**Comment by FichteFoll** [comment]
@jskinner I think this issue was closed prematurely. #162 was the issue regarding the time format, which has been addressed and closed, but there doesn't appear to be an option for which timestamp to show in the commit list (authored vs committed).

**Comment by Penguin98kStudio** [comment]
I hope someone works on this 🥺

**Comment by dpjohnst** [comment]
Hi all,

This has been added in Sublime Merge 2075 (development build), and will be added to the next stable build.

Cheers,
\- Dylan

**Comment by reednj** [comment]
Anyone know the name of the setting or even where to find a list of settings?
