### ISSUE TITLE
Github (or Gitlab) MFA not supported for Merge

### ISSUE THREAD

**Issue by mdella** [sublimehq/sublime_merge#650]
**Problem description**

MacOS Catalina 10.15.2, Sublime Merge Build 1119
Trying to clone a git entry however when prompted for my username/password, it never prompts me for my MFA token.  Basically it says:

"Cloning into '/Users/mdella/SailInternet'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/SailInternet/network/'

git failed with exit code 128"

**Preferred solution**

It should recognize that Git is requesting an MFA and prompt for that value

**Alternatives**

None

**Comment by dpjohnst** [comment]
Hi @mdella,

Thank you for your feedback. Currently, Git does not distinguish between MFA and username/password.

To work around this, see: https://help.github.com/en/github/authenticating-to-github/accessing-github-using-two-factor-authentication#using-two-factor-authentication-with-the-command-line

Let me know if this helps!

Kind regards,
- Dylan
