### ISSUE TITLE
Crash on bottom of search

### ISSUE THREAD

**Issue by themilkman** [sublimehq/sublime_merge#652]
**Version info**

OS: Ubuntu 18.04
Build 1201

**Description**

When I (plain) search for a string in SM, it shows me the results. 
By going down with the arrow key to/after the last match SM (sometimes for a short time freezes and) hard exits afterwards. I could reproduce it with different repos (and search terms).
I have the feeling that it depends on the length of the search string (>7)

**Comment by dpjohnst** [comment]
Hi @themilkman,

Thank you for reporting this! We have been able to reproduce the bug, and are working on a fix.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Following up on the previous post - A new build of Sublime Merge has been released, which fixes this issue: https://www.sublimemerge.com/dev

**Comment by themilkman** [comment]
Confirmed, thanks! :+1:
