### ISSUE TITLE
Main screen shows correct merge diff but merge tool shows entire file as different

### ISSUE THREAD

**Issue by ShaneCourtrille** [sublimehq/sublime_merge#653]
OS: Windows 10  
Build: 1119

I'm merging a branch into my develop branch and I have merge conflicts to deal with.  When I review the merge details for a .cshtml file prior to clicking the Resolve button what I see makes sense.  I see the <<<< HEAD and ======  ... >>>> branch markers and the coloration makes sense.  

As soon as I click the Resolve button though things go a bit bonkers.  The merge tool thinks there are no commonalities at all and shows both files as being 100% in conflict.  I've verified that the person who checked in this file has autocrlf = true and that my SUblime Merge built in git instance also has that setting (as does my won git install)

Any suggestions?  Thanks

**Comment by ShaneCourtrille** [comment]
Figured out that the file was being considered as added twice!

**Comment by srbs** [comment]
See also: https://forum.sublimetext.com/t/sublime-merge-cant-recognize-the-conflict-correctly/48032
