### ISSUE TITLE
Main menu behaves erratically when "Hidden unless Alt is pressed" is used

### ISSUE THREAD

**Issue by markomarkovic** [sublimehq/sublime_merge#655]
**Version info**

 - OS: Ubuntu 19.10
 - Build: 1201

**Description**

Main menu behaves erratically when "Hidden unless Alt is pressed" is used as illustrated in the gifs below.

**Steps to reproduce**

1. In the preferences enable "Hidden unless Alt is pressed" option
2. Press Alt and go through the menus
3. Observe that the "Repository" menu contains many more entries that usual
4. Clicking on any entry will hide the extraneous items and rearrange the rest making clicking wrong items a real possibility.

**Expected behavior**

No extraneous menu items are shown in the menu when it's visible.

**Screenshots**
![Peek 2020-02-04 12-05](https://user-images.githubusercontent.com/99233/73725782-90741c00-4747-11ea-9547-c3d6cc4b0325.gif)

Here I'm trying to click on "Changelog..." but the "Enter License" disappears at the moment I click so the "About" is clicked.
![Peek 2020-02-04 12-02](https://user-images.githubusercontent.com/99233/73725788-9538d000-4747-11ea-88c7-71824c6c33ea.gif)

**Comment by dpjohnst** [comment]
Hi @markomarkovic,

Thanks for the bug report!
We've just fixed this issue - it will be fixed in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Following up on the previous post - A new build of Sublime Merge has been released, which fixes this issue: https://www.sublimemerge.com/dev
