### ISSUE TITLE
Filter working directory

### ISSUE THREAD

**Issue by mheckel** [sublimehq/sublime_merge#656]
**Problem description**

Sometimes I have a long list of uncommitted changes or untracked files. It would be helpful to easily filter the list.

**Preferred solution**

Some sort of a filtering mechanism (parts of filename, but maybe also date, etc.)

**Alternatives**

The recently changed symbol is helping, but filtering would be much easier on the eyes.

**Comment by srbs** [comment]
Duplicate of #330
See also #417

**Comment by dpjohnst** [comment]
Closing this issue as it's a duplicate of #330 - feel free to head over to that issue and subscribe to it for status updates.
