### ISSUE TITLE
Multiple bugs in search function.

### ISSUE THREAD

**Issue by dolpsdw** [sublimehq/sublime_merge#657]
1. You can not preview the Commit until the search finish iterating all over the history.
(Previusly you could select the commit and the changes appear in the changes view)

2. Right click on the commit while still searching show a 00000 comit reference (probably related to 1)

3. After selecting the commit and pressing Escape the Main branch view does not open on the commit selected. (Previusly this autoNavigate to that)
![image](https://user-images.githubusercontent.com/4348598/73795183-52f4aa80-47aa-11ea-9589-a9864c916a39.png)

**Comment by dpjohnst** [comment]
Hi @dolpsdw,

Thanks for reporting this! We are working to resolve this issue.

Many thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @dolpsdw,

Just a quick update - we have been able to fix these issues, and the fixes will be included in the next build of Sublime Merge.

Thanks,
\- Dylan
