### ISSUE TITLE
Pre-commit hook error message overflows the panel

### ISSUE THREAD

**Issue by sinan** [sublimehq/sublime_merge#658]
**Version info**

 - OS: macOS 10.15.2
 - Build: 1119

**Description**

Commit error screen overflows horizontally if there is a long message in the panel. 

**Steps to reproduce**

1. Have a repository with `jsx-a11y` linter as a precommit hook
2. Have an error due to https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md
3. Try to commit

4. This long line shows up as an error and sublime merge commit error panel doesn't wrap the text. _(not in the initial panel that pops up, but when you click on the commit status icon on the left side of the branch name)_

```
  Line 48:26:  The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
```

**Expected behavior**

Regardless the original error content format, sublime merge should either wrap the content or make it horizontally scrollable to make it readable.

**Screenshots**

![sublime merge](https://user-images.githubusercontent.com/440086/73820686-255a3200-47a7-11ea-970f-120a8616ec07.png)

**Comment by willrowe** [comment]
This is related to #538, #343, and #407.

**Comment by dpjohnst** [comment]
Hi @willrowe,

Thanks for reporting this! We are working to fix this.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @willrowe,

This has been fixed as of Sublime Merge Build 2002 (Dev)

Cheers,
\- Dylan

**Comment by willrowe** [comment]
I can confirm this has been fixed in build 2002.
