### ISSUE TITLE
Arrow keys no longer work in Edit Commit Message & Create Branch

### ISSUE THREAD

**Issue by bgeron-contiamo** [sublimehq/sublime_merge#659]
**Version info**

 - OS: macOS Catalina
 - Build: 1201

**Description**

Since the recent Sublime Merge update, when I try to Edit Commit Message, I can no longer use the arrow keys to move the cursor in the commit message box.

**Steps to reproduce**

1. Open repository.
2. Right-click a commit in the current linear history, click Edit Commit -> Edit Commit Message
3. I can type and use Backspace, but the arrow keys do nothing.

**Expected behavior**

The arrow keys work as in a normal textbox.

This used to work for me.

**Comment by bgeron-contiamo** [comment]
Same when I do Cmd+P, Create Branch: in the little dialog box I can't use arrow keys.

**Comment by willrowe** [comment]
I'm having the same problem.

**Comment by dpjohnst** [comment]
Hi All,

Thanks for reporting this. I've begun investigating, and will provide an update soon!

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi All,

This will be fixed in the next build of Sublime Merge.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Following up on the previous post - A new build of Sublime Merge has been released, which fixes this issue: https://www.sublimemerge.com/dev

**Comment by willrowe** [comment]
I can confirm that this has been fixed in build 1202.
