### ISSUE TITLE
Multiple windows open when starting sublime merge from the command line

### ISSUE THREAD

**Issue by chrisjbillington** [sublimehq/sublime_merge#660]
**Version info**

 - OS: Arch Linux
 - Build: 1201

**Description**

When starting sublime-merge from the command line with `smerge <repository_directory>`, two sublime-merge windows open: one for the repository in question and one for whatever the last repository open was.

I understand sublime merge is probably set to open whatever the last repository open was, but this is a bit of a pain.

In the long run, a tabbed interface like sublime-text would be ideal. You could re-open all repos that were open when sublime merge was closed, with the tab for the repo specified on the command line active. 

But for now I think just disregarding whatever was open last when specifying a repo on the command line would be better.

**Steps to reproduce**

1. Open a repository in sublime merge
2. Close sublime merge
3. Run `smerge <repository_directory>` from the command line on any (possibly the same) repository
4. See that two windows open

**Expected behavior**

Just one window should open - the one for the repository passed on the command line

**Comment by dpjohnst** [comment]
Thanks for reporting this!

A new build of Sublime Merge has been released, which fixes this issue: https://www.sublimemerge.com/dev

**Comment by chrisjbillington** [comment]
Thank you!
