### ISSUE TITLE
Signature verification fails on my own commits

### ISSUE THREAD

**Issue by bgeron-contiamo** [sublimehq/sublime_merge#661]
**Version info**

 - OS: macOS Catalina
 - Build: 1202

**Description**

I upgraded Sublime Merge. Now on all my commits, it says "Signature : Verification Failed" in red in the commit header. Even on commits which show with the green [Verified] tag on GitHub.

Unsigned commits do not seem to have this scary marker.

When I make a new test commit from the latest version of Sublime Merge, it also shows this marker.

There is nothing relevant in the Console, just some "Unknown refs form in packed-refs" that I caused (semi) on purpose.

**Expected behavior**

My own commits are not marked with a tag that looks like a warning sign.

**Comment by dpjohnst** [comment]
Hi @bgeron-contiamo,

Thank you for reporting this issue! We are investigating this.

Kind regards,
\- Dylan

**Comment by BenjaminSchaaf** [comment]
@bgeron-contiamo Do you have GPG installed and in your PATH? If you hover over the "Verification Failed" it should give you the output of gpg.

**Comment by bgeron-contiamo** [comment]
I have GnuPG in `/usr/local/bin/gpg` ; can't tell you if it's in the PATH for Sublime Merge because global environment variables are kind of a mess afaict. 

- When I start Sublime Merge from that bar at the bottom of my screen (Launcher?) I get a red `Verification Failed`; I cannot get a tooltip to show up. In Help -> Debug Information, under `Git Version Information`, `/usr/local/bin` is listed. I copied the full PATH there to a new bash (`export PATH=...<ENTER>`) and verified that `gpg` and `which gpg` seems good, besides some locale warnings. The debug info does say that `Our config output is different to the Git config output`. I do notice that the PATH here strangely includes `~/.dotnet/tools`, which is nonsense of course. I do not have a directory called `~`. I have a home directory, but shell expansions do not run against `$PATH` as far as I'm aware. 

(Maybe the signature verification stuff isn't robust against nonexistent paths in `$PATH`?)

- When I start `smerge` from my terminal (which has a nice custom PATH set), I get a green Signature: `Verified` _with_ a tooltip. The PATH is mostly smaller, one irrelevant path added and lots deleted.

**Comment by bgeron-contiamo** [comment]
I verified that signature checking works with `/usr/bin/open -a Sublime\ Merge .`, but it fails with `env PATH=$PATH:nonexistent /usr/bin/open -a Sublime\ Merge .` . Found it! 🙌

**Comment by bgeron-contiamo** [comment]
I didn't see any error messages anywhere though!

**Comment by bgeron-contiamo** [comment]
Super weird. So there's this PATH that Sublime Merge has when macOS itself starts it. If I go to bash, do `export PATH='...'`, then do `open -a Sublime\ Merge .`, the behavior is different! Verification now _works_ on my own commits. The PATH is still slightly different: new duplicates are added at the start and the front. In both cases, `/usr/local/bin` is before the faulty path `~/.dotnet/tools` and both appear only once. 

I'm starting to wonder if it's something else. Maybe `open -a Sublime\ Merge` isn't so equivalent to the macOS launcher.

**Comment by bgeron-contiamo** [comment]
I also noticed something else. On one of the repos, we have commits created by GitHub itself. In my terminal, they show as

```
> git show --show-signature
commit f9328c98174f05cc5229eed54af2f5dbfaa03c22 (HEAD -> master, origin/master, origin/HEAD)
Warning: Failed to set locale category LC_NUMERIC to en_DE.
Warning: Failed to set locale category LC_TIME to en_DE.
Warning: Failed to set locale category LC_COLLATE to en_DE.
Warning: Failed to set locale category LC_MONETARY to en_DE.
Warning: Failed to set locale category LC_MESSAGES to en_DE.
gpg: Signature made Wed Feb  5 15:59:54 2020 CET
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Good signature from "GitHub (web-flow commit signing) <noreply@github.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 5DE3 E050 9C47 EA3C F04A  42D3 4AEE 18F8 3AFD EB23
```

But the tooltip in Sublime Merge contains `gpg: BAD signature` !

**Comment by BenjaminSchaaf** [comment]
@bgeron-contiamo We've got some fixes in the works for better handling gpg not being installed, but that doesn't seem like it would help here. I know what the environment issue is too, I'll be working on that next.

Do you know of an easy way to reproduce the github signature bug? Perhaps a public repository with a commit from github?

**Comment by bgeron-contiamo** [comment]
Sure! I just created a new repo on GitHub using the web wizard, with the initial commit, and that reproduces it already. I invited you to a private repo of mine that has this (all commits, including ce03a70f237767aa37dc404591b56a1043e64abd ) . For reference I also attached it as a bundle that you should be able to `git clone` from. 

[smerge-661.git.bundle.zip](https://github.com/sublimehq/sublime_merge/files/4213421/smerge-661.git.bundle.zip)

**Comment by BenjaminSchaaf** [comment]
I've found the issue. It will be fixed soon.

**Comment by bgeron-contiamo** [comment]
Fixed in build 1203 🙌
