### ISSUE TITLE
Show submodule's current branch name

### ISSUE THREAD

**Issue by themilkman** [sublimehq/sublime_merge#662]
**Problem description**

By working with multiple submodules in different versions it is easy to not have the correct branch checked out currently.

**Preferred solution**

Show branch name of submodule - maybe in brackets - after the submodule name

**Alternatives**

Hovering the submodule might show the name.

**Comment by dpjohnst** [comment]
Hi @themilkman,

Thanks for the suggestion! We're investigating ways we can add this functionality.

Kind regards,
\- Dylan

**Comment by themilkman** [comment]
The way it was implemented in v2002 is great, thanks!! :pray: 
You're all doing an awesome job :+1:
