### ISSUE TITLE
Crashes on search

### ISSUE THREAD

**Issue by jnns** [sublimehq/sublime_merge#664]
**Version info**

 - OS: Ubuntu 19.10
 - Build: 1202 + 1201 (dev)

**Description**

On some repositories, a search makes Sublime Merge hang unrecoverably after typing 2-3 characters. This is a regression introduced in build 1201. Build 1119 works just fine.

**Steps to reproduce**

1. Open repository ...
2. Press <kbd>CTRL</kbd> <kbd>F</kbd>, enter search string.

**Expected behavior**

I expect the sidebar to only list commits that match the search string.

**Comment by dpjohnst** [comment]
Sorry to hear you're running into this issue, and thank you for the bug report.

Which languages does this repository use?

Many thanks,
\- Dylan

**Comment by jnns** [comment]
The repositories this happens on consist mainly of Python, HTML and SCSS. 

Interestingly, there's one project with staged and unstaged files (`*.py`, `*.md`, `*.mo`, `*.po`, `*.html`) where Sublime Merge crashes a few seconds after startup. I can get a glimpse of the files in the working directory and the loading indicators for the diffs of each file but before any output is shown, Sublime Merge closes already.

**Comment by dpjohnst** [comment]
Thanks for the extra information @jnns!

Could you confirm whether clearing the cache solves this issue? This can be done by navigating to:

OS X: ~/Library/Application Support/Sublime Merge
Windows: %APPDATA%\Sublime Merge
Linux: ~/.config/sublime-merge

and deleting the cache folder.

Once deleted, try restarting the program.

Many thanks,
\- Dylan

**Comment by jnns** [comment]
Hello Dylan,

thanks for the support. I deleted the cache folder but the crashes still happen.

**Comment by dpjohnst** [comment]
Thank you for the information!

Is this a publicly available repository that this occurs on? If so, I would like to see if I can replicate it on a development build.

Thanks,
\- Dylan

**Comment by jnns** [comment]
Hi Dylan,

the respositories I experienced this with are unfortunately all private. But I can reproduce the problem on a public repository:

1. Clone the Django repository
    `git clone https://github.com/django/django.git`
2.  Start Sublime Merge 
   `smerge .`
3. Press <kbd>CTRL</kbd><kbd>f</kbd> and type `foo`
4. Sublime Merge crashes.

This happens on the latest build 1203.

**Comment by dpjohnst** [comment]
Hi @jnns,

Thank you for following up with the new information - we'll be investigating this further, and I'll keep you updated on any progress.

**Comment by jnns** [comment]
In another issue, a user mentioned that their problem with SublimeMerge crashing was resolved in build 1204. I just wanted to note briefly that 1204 crashes too. Same behavior.

**Comment by jnns** [comment]
I just tested the new development build 2000 and love the new layout. Thanks for putting in the effort to all those who were involved!

Unfortunately, SublimeMerge still crashes when performing the steps in https://github.com/sublimehq/sublime_merge/issues/664#issuecomment-589211521.

**Comment by dpjohnst** [comment]
@jnns I am glad you were able to resolve it! 

During my investigation, I was unable to reproduce the issue. It sounds like the culprit may be a broken syntax definition - perhaps third-party. Let me know if you experience it further.

**Comment by jnns** [comment]
I will close this issue to keep the tracker clean. I did not experience this issue anymore since then and I assume you're right that a broken third-party syntax definition was the culprit. Thanks for your help!
