### ISSUE TITLE
Support drag and drop at first run

### ISSUE THREAD

**Issue by jminer** [sublimehq/sublime_merge#666]
**Problem description**

When I opened Sublime Merge the first time (without opening a repository), I tried dragging and dropping a repository folder to the window but nothing happened. After a repository is open, you can drag and drop to open another one, but it isn't possible for the first one. So it won't be a problem for me in the future, but I thought I'd report this issue because it wasn't a great first impression (although I loved Sublime Merge afterward).

**Preferred solution**

I think the window shown on the first launch, currently the Clone Repository window, should support dragging and dropping a repository folder to open it.

**Comment by dpjohnst** [comment]
Hi @jminer,

Thank you for trying Sublime Merge, and for taking the time to report this! We want everyones first time run to be a smooth experience, and this is definitely something we can improve.

We will look into adding this functionality in future builds.

Thanks,
\- Dylan

**Comment by BenjaminSchaaf** [comment]
I can't reproduce this in build 2022 on neither Linux or Windows.

**Comment by dpjohnst** [comment]
Added in Sublime Merge Build 2025 (stable)
