### ISSUE TITLE
Delete Tags from Remote

### ISSUE THREAD

**Issue by voltechs** [sublimehq/sublime_merge#667]
**Problem description**

Deleting tags in the SM client does not remove them from remotes.

**Preferred solution**

When deleting a tag in the SM client, ask (checkbox on verification modal?) if it should be deleted from remote(s).

**Alternatives**

Show a list of tags under each remote, and allow the user to manage remote tags from there (similar to remote branches).

**Screenshots**

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1700514/74764981-f9778b80-523f-11ea-897d-7a27fe25e509.png">

**Comment by dpjohnst** [comment]
Hi @voltechs,

Thank you for your suggestion! We will be investigating ways to improve this experience for future builds.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @voltechs, this was added in Sublime Merge Development Build 2041.
