### ISSUE TITLE
Post-stash highlighted commits are no longer (all?) selected

### ISSUE THREAD

**Issue by michaelblyons** [sublimehq/sublime_merge#668]
**Version info**

 - OS: macOS Catalina
 - Build: 1119

**Description**

After stashing, the commits previously selected in the sidebar _look_ like they are still selected, but they are not.

**Steps to reproduce**

1. Open repository
2. Edit a file
3. {<kbd>Cmd</kbd>/<kbd>Ctrl</kbd>/<kbd>Shift</kbd>}-click two+ past commits in the sidebar
4. Right-click one of the selected commits.
5. Choose _Edit Commit > Squash selected commits_
6. "Oh no! Index is dirty. Have to stash!"
7. Click `stash save` button.
8. Notice the commits are still highlighted.
9. Try Right-click > _Edit Commit > Squash selected commits_ again.
   - It is greyed-out.

**Expected behavior**

- I can still squash with those commits highlighted.
- Or, if not, the commits un-highlight after stash (but this is not as good).

**Comment by dpjohnst** [comment]
Hi @michaelblyons,

Thank you for reporting this issue! I will be investigating this.

Kind regards,
\- Dylan

**Comment by michaelblyons** [comment]
Seems fixed.
