### ISSUE TITLE
Use SM as a diff tool

### ISSUE THREAD

**Issue by AmjadHD** [sublimehq/sublime_merge#669]
**Problem description**

Sometimes i wish i could use Sublime Merge as a diff tool to quickly compare two arbitrary files, much like `git diff file1.txt file2.txt`.

**Preferred solution**

Add a new command to `smerge`:
`smerge diff file1.txt file2.txt`
which, like `git diff`, can compare a tracked to untracked files.
Bindings can be made in ST to SM (e.g when the user selects two files from the sidebar or multi-selects two tabs,...)

**Comment by keith-hall** [comment]
related:
https://github.com/sublimehq/sublime_merge/issues/434
https://github.com/sublimehq/sublime_merge/issues/40

**Comment by michaelblyons** [comment]
I kind of feel like this is an exact dup of #40

**Comment by AmjadHD** [comment]
I did make a quick search but didn't make a thourough check.

**Comment by striatum** [comment]
This can be also achieved with:
```
smerge mergetool <FILE1> <FILE2>
```
