### ISSUE TITLE
Add console message feedback capabilities

### ISSUE THREAD

**Issue by Hammit** [sublimehq/sublime_merge#67]
As part of the Git workflow, we receive important messages and feedback from commit hooks. It would be useful if Merge had some way of displaying these commit messages in an integrated terminal or console.

**Comment by willrowe** [comment]
You can click on the status icon to the left of the current branch name to view the last command run and the output from it.

**Comment by jasonycw** [comment]
Currently the feedback is pretty weak, only the "branch" box on the top tool bar show a thin progress bar and a static in-progress icon with a little wording change.
There is no clear indication that it is working in background.

I suggest adding a thicker and larger progress bar (maybe use the top toolbar background) with a clearer color. Or add a gif in-progress icon instead a static one.

**Comment by Hammit** [comment]
The feedback via the indicated icon works well. User problem. Thank you
