### ISSUE TITLE
Command to Navigate/Go to child

### ISSUE THREAD

**Issue by lukaw3d** [sublimehq/sublime_merge#670]
**Problem description**

Command `navigate_to_parent` exists, but not the reverse.

Right now my keybindings for navigating the tree and its behaviour are awkward
```
    {
        "keys": ["up"],
        "command": "move",
        "args": {"by": "lines", "forward": false},
        "context": [ { "key": "control", "operand": "commit_table" } ]
    },
    {
        "keys": ["down"],
        "command": "navigate_to_parent",
        "context": [ { "key": "control", "operand": "commit_table" } ]
    },
```

**Preferred solution**

`navigate_to_child`

**Alternatives**

https://github.com/sublimehq/sublime_merge/issues/331 gave me a bit of hope that this would work, but nope:
`"command": "navigate_to_parent", args: { "parent": -1 }`

**Comment by dpjohnst** [comment]
Hi @lukaw3d,

The command "navigate_to_child" does actually exist :) You can see it in use within the Navigation menu of Sublime Merge. You can also trigger this command using alt + up (super + up for MacOS).

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @lukaw3d,

Just following up on the previous comment: I didn't mention this behaviour is only in the development build. It will soon be released into the stable builds.

Kind regards,
\- Dylan

**Comment by lukaw3d** [comment]
It works!
