### ISSUE TITLE
Find All Missing a Close Option

### ISSUE THREAD

**Issue by MC2018** [sublimehq/sublime_merge#675]
When finding text with Ctrl+F, I am brought with the menu along with an X in the top right corner of the UI that pops up in order to close that menu (which is expected). However, when trying to find the same X when bringing up the replace menu with Ctrl+Shift+F, it is nowhere to be found. I suggest that this be added for continuity's sake.

**Comment by dpjohnst** [comment]
Hi @MC2018,

Thanks for the feedback! This is actually a bug tracker for Sublime Merge.
To ensure this feedback isn't lost, could you file this bug over at: https://github.com/sublimehq/sublime_text.

Many thanks,
\- Dylan
