### ISSUE TITLE
Repository not added to "open recent" when program not closed normally. 

### ISSUE THREAD

**Issue by VulumeCode** [sublimehq/sublime_merge#676]
**Version info**

 - OS: Windows 10
 - Build: 1119

**Description**

Repositories are only added to "open recent" when the program is closed normally. When the program is killed by shutting down the computer or by closing a command line from it was launched, it's not remembered. 

**Steps to reproduce**

Create new repository. 
Open sublime merge from the command line in that repository with `sublime_merge.exe .`.
Close the command line. 
Open sublime merge from the start menu.
Look at file>open recent. 
The new repository is not in the list. 

**Expected behavior**

The new repository is at the top.

**Comment by BenjaminSchaaf** [comment]
Executables on windows can either be linked as a command line application or as a GUI application. `sublime_merge.exe` is the GUI application and thus doesn't support command line usage. You should be using `smerge.exe` instead, which is linked as a command line application.

**Comment by VulumeCode** [comment]
@BenjaminSchaaf That doesn't solve the actual problem. Rebooting with `smerge` open still doesn't make it remember. 

That happens to me way more often. I was opening with `sublime_merge.exe . &` anyways. I was just giving an easier way to reproduce.

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge Build 2025
