### ISSUE TITLE
Select and delete multiple branches.

### ISSUE THREAD

**Issue by ivanglushko** [sublimehq/sublime_merge#677]
I have lots of branches that I'm working on. It would be. nice to delete local selected branches. For now I have to use Fork. 

**Preferred solution**
Select branches -> delete all local (maybe a checkmark for remotes too)

**Comment by dpjohnst** [comment]
Hi @ivanglushko,

Thank you for this feedback! We're always looking to support more work flows, and we will be investigating ways to support this.

Kind regards,
\- Dylan

**Comment by ivanglushko** [comment]
Thank you I'm in love with your product guys keep on rocking!
