### ISSUE TITLE
Next/Previous tab menu items behave incorrectly

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#682]
**Version info**

 - OS: macOS 10.14
 - Build: 2000

**Description**

Menu items for `Next File Tab`/`Previous File Tab` & `Next File Section`/`Previous File Section` both go next & never previous.

**Steps to reproduce**

1. open a repository
2. choose a commit with multiple files
3. click on `Navigate` > `Tabs` > `Next File Tab`
4. click on `Navigate` > `Tabs` > `Prev File Tab`

**Expected behavior**

Correct previous/next behavior.

Note: I'm fairly certain it because both menu items reference `next_*` commands & the keyboard shortcuts reference `next_*` and `prev_*` commands. I'm hoping that once this is fixed the shortcuts will appear in the menu items.

** Related thoughts **

The difference between file tab & section tab isn't exactly clear or easy to determine. And it is confusing that changing tabs at the 'same level' between commit vs staging views are different keyboard shortcuts.

**Comment by dpjohnst** [comment]
Hi @srbs,

Thanks for reporting this - this will be fixed in the next build :)
Also thanks for the additional thoughts - we will be updating the keybindings for the commit dialog sections in the next build.

Kind regards,
\- Dylan

**Comment by srbs** [comment]
@dpjohnst, something else I noticed about the keyboard shortcuts:

`Cmd+Shift+[` & `Cmd+Shift+]` are the standard top-level tab changing shortcuts on macOS (most apps also support the standard Windows/Linux shortcuts: `ctrl+tab` & `ctrl_shift_tab`)

At the moment, the File Tab next/prev is assigned to those shortcuts & not the main repository tab changing. Could we get that changed as well? (If you'd like I can create a new issue with this in it)

**Comment by srbs** [comment]
Fixed in build 2002.
