### ISSUE TITLE
Keep commit text display panel in a fixed location

### ISSUE THREAD

**Issue by stinos** [sublimehq/sublime_merge#683]
**Problem description**

In build 2000 the panel with the commit text/button jumps from the top (where it always has been) when viewing commits, to the bottom when viewing the staging area (i.e. clicking on the top entry `Commit changes` in the commit tree.) To make it worse this looks like 'oh, I have to enter commit text at the bottom now' but that's not true in all cases: editing commit text still happens at the top.

**Preferred solution**

Please just keep this at the top, always. People are used to that by now.

**Alternatives**

Location could be configurable. But having it change is just bad, sorry.

**Comment by dpjohnst** [comment]
Hi @stinos ,

Thank you for your feedback! I'm happy to announce that we've made some changes to the commit dialog, and the commit message is now at the top by default.

For closure, you can configure this layout through the preferences window.

Thanks,
\- Dylan

**Comment by stinos** [comment]
Hy Dylan, tested the last release and can confirm this works ok now.
Thanks for the quick fix!
