### ISSUE TITLE
There is no way to merge Binary files.

### ISSUE THREAD

**Issue by Win32Troy** [sublimehq/sublime_merge#686]
**Problem description**

Now when I try to merge binary files the sha256 hash of the binary file is written to the result file.

**Preferred solution**

Add buttons: take mine and take their files. The result of their work will be a full copy of the file from the selected branch.

**Comment by srbs** [comment]
Are there not `Take Left` & `Take Right` options in the `...` menu at the top center of the resolve merge view?

**Comment by Win32Troy** [comment]
There are, but it works incorrectly for binary files and writes to the file `sha256 hash`  instead of the binary file

**Comment by dpjohnst** [comment]
Hi @Win32Troy,

I've added keep ours / keep theirs options on the main commit screen - this should aid in merging binary files. This will be available in the next development build of Sublime Merge.

With regard to the merge tool, are you seeing the contents of the file corrupted after saving merge? (e.g. for an image file, can you still view the image in an image viewer correctly).

Thanks,
\- Dylan

**Comment by Win32Troy** [comment]
Hi, @dpjohnst
No, I'm not seeing. Binary files contain only sha256 hash.

**Comment by dpjohnst** [comment]
Hi @Win32Troy,

Do you have an example repository you could share where you are seeing this issue?

Kind regards,
\- Dylan

**Comment by Win32Troy** [comment]
Hi @dpjohnst 
Sorry, everything works fine in the latest build, thanks.
Problem resolved.
