### ISSUE TITLE
Sublime Merge starts in safe mode when ran from other software

### ISSUE THREAD

**Issue by stinos** [sublimehq/sublime_merge#688]
**Version info**

 - OS: Windows 10
 - Build: 2000

**Description**

Since build 2000 starting sublime_merge.exe from within Visual Studio always starts a new instance in safe mode.

**Steps to reproduce**

Add 'external tool' in VS, for me that's command=C:\Program Files\Sublime Merge\sublime_merge.exe and argument=$(ItemPath).

**Expected behavior**

Should either start in normal mode, or when started already should open the repository in a new tab or reuse existing tab if the repository is open already.

**Screenshots**

Dialog text:
```
---------------------------
Sublime Merge
---------------------------
Safe Mode

Sublime Merge has been started in safe mode.

Safe mode causes Sublime Merge to use a separate directory to store packages, settings and state information. Additionally, packages from Sublime Text are not loaded. This provides a pristine environment and leaves the normal mode data directory intact.

Please note that all application settings changes will be erased the next time the application is started in safe mode.
---------------------------
OK   
---------------------------
```

**Comment by BenjaminSchaaf** [comment]
Are you holding down control when Visual Studio launches Sublime Merge?

**Comment by stinos** [comment]
@BenjaminSchaaf apologies, missed your reply. IIRC it happened both when holding down control and accessing from the menu. However in build 2004 I do not have the problem anymore :)
