### ISSUE TITLE
segfault while lexing markdown

### ISSUE THREAD

**Issue by darthoctopus** [sublimehq/sublime_merge#691]
**Version info**

 - OS: Arch Linux
 - Build: 2000

**Description**

Sublime Merge segfaults while attempting to lex markdown files for syntax highlighting that contain YAML headers for use with Pandoc. I attach an example:

[excitation_new.zip](https://github.com/sublimehq/sublime_merge/files/4308221/excitation_new.zip)

This results in the following lines in the system message log:

```
[ 6936.456798] lex_queue[18125]: segfault at 9500000094 ip 00000000009c17bb sp 00007fda237fba00 error 4 in sublime_merge[4ab000+55e000]
[ 6936.456803] Code: af ff 48 89 df e8 95 04 b9 ff cc cc cc cc cc 55 41 57 41 56 41 55 41 54 53 48 83 ec 48 49 89 ce 48 89 54 24 20 48 89 74 24 18 <4c> 8b 27 48 89 7c 24 40 48 8b 77 08 48 89 f1 b0 01 4c 29 e1 0f 84
```

**Steps to reproduce**

1. Put file in repository
2. Preview file (e.g. in "unstaged")
3. Segfault occurs

**Expected behavior**

Segfault should not occur; failed lexing should result in markdown file being treated as plaintext

**Comment by darthoctopus** [comment]
I can also confirm that this issue occurs in 1202 and 1204; the last working build for me appears to be 1118.

**Comment by srbs** [comment]
@darthoctopus, this might be related to the syntax definition, it may be useful to report it there as well:

https://github.com/sublimehq/Packages/issues

**Comment by dpjohnst** [comment]
Hi @darthoctopus,

Thank you for reporting the issue.

Could you try using safe mode and seeing if the issue still persists?
Safe mode can be enabled by running ```subl --safe-mode``` from the command line.

Thanks,
\- Dylan

**Comment by darthoctopus** [comment]
Here's what I found:

- Segfault doesn't happen on safe mode
- Segfault doesn't happen with clean Sublime Text config directory
- Uninstalling package one by one in alphabetical order, I found the segfault stop happening with the CSS3 package uninstalled (i.e. https://packagecontrol.io/packages/CSS3). Disabling it didn't help, I had to uninstall it to stop the segfaults.
- A fresh profile with CSS3 didn't segfault smerge
- From my old profile, uninstalling packages one by one in reverse alphabetical order, I found the segfault to stop happening with the Markdown Extended package uninstalled.
- A fresh profile with both CSS3 and Markdown Extended didn't segfault smerge until I associated the extension .md with Markdown Extended.

**Comment by dpjohnst** [comment]
Hi @darthoctopus,

Just following up - we've added a work-around for the issue in the CSS3 package.
Given that, I'm going to go ahead and close this issue.

If you run into any issues after this, please feel free to re-open this or another issue.

Thanks,
\- Dylan
