### ISSUE TITLE
Support "compact" display of commits within the tree

### ISSUE THREAD

**Issue by brokenbeta** [sublimehq/sublime_merge#692]
**Problem description**

Commits in the tree take up 2-lines vertically, which is good for showing detail on the commit, but means you see less of them than other git clients, and it's harder to interpret the graph since it's very stretched vertically (while being quite tight horizontally).

**Preferred solution**

It would be good to add a "compact" toggle to change the display so each commit is reduced to 1-line each.

**Comment by srbs** [comment]
See also #18

**Comment by brokenbeta** [comment]
ah yeah this is definitely a duplicate of that one. I'll close this.
