### ISSUE TITLE
Old repo tabs are cleaned up if open from command line

### ISSUE THREAD

**Issue by jfcherng** [sublimehq/sublime_merge#694]
**Version info**

 - OS: Win7 x64
 - Build: 2000

---

**Description**

I am not sure whether this is designed or a bug.

When SM process doesn't exist, if SM is opened via `$ smerge REPO_PATH` or by double clicking [ST's branch icon in the status bar](https://user-images.githubusercontent.com/6594915/76520667-4f85ca80-649e-11ea-8fc3-c1facb055b77.png), SM's repo tabs are cleaned up.

---

**Steps to reproduce**

1. Make SM have some repo tabs
      ![image](https://user-images.githubusercontent.com/6594915/76521212-5234ef80-649f-11ea-8e12-e65be24b5842.png)
2. Close SM (this is important)
3. Open SM via `$ smerge REPO_PATH` or by double clicking [ST's branch icon in the status bar](https://user-images.githubusercontent.com/6594915/76520667-4f85ca80-649e-11ea-8fc3-c1facb055b77.png)
4. Old repo tabs are cleaned up.
  ![image](https://user-images.githubusercontent.com/6594915/76521151-33365d80-649f-11ea-9ce8-ca8967413d1e.png)

---

**Expected behavior**

If this is a bug, repos opened last time should not be removed.

**Comment by dpjohnst** [comment]
Hi @jfcherng,

This is an intentional design decision. We've thought about this quite hard, as there are arguments for both behaviors. However, we've decided to keep this behavior. As you know, we're always monitoring everyone's feedback, and will continue to do so.

Thanks,
\- Dylan

**Comment by jfcherng** [comment]
Got it. Thanks.

**Comment by srbs** [comment]
@dpjohnst, I'd love it if this could be an option I can turn on for myself.

**Comment by Zwyx** [comment]
Here's a script that checks if Sublime Merge is running before executing it, in order to prevent any loss of open tabs:
https://github.com/sublimehq/sublime_merge/issues/309#issuecomment-1668019269

I cannot understand how losing 15 tabs can be seen as a feature.

**Comment by themilkman** [comment]
> @dpjohnst, I'd love it if this could be an option I can turn on for myself.

+1 I'd also prefere it to be configurable.
