### ISSUE TITLE
Clicking the "Complete Merge with no changes" does nothing

### ISSUE THREAD

**Issue by eludwig** [sublimehq/sublime_merge#695]
**Version info**

 - OS: macOS 10.14
 - Build: 1119

**Description**

Trying to complete a merge that results in no change doesn't work. Clicking the "Complete Merge with no changes" does nothing. I have to go back to the command line an issue "git commit" for the repo to finish the merge

**Steps to reproduce**

Do a merge with conflicts and "Take Left" or whatever
Merge will by definition not have any changes
Clicking the "Complete Merge with no changes"
Nothing happens, merge never completes

**Expected behavior**

Merge should complete

**Screenshots**

**Comment by dpjohnst** [comment]
Hi @eludwig,

Thank you for reporting this - this has been fixed in the development builds of Sublime Merge. This fix will soon be available in the stable builds.

Kind regards,
\- Dylan
