### ISSUE TITLE
Opening repo through command line on macOS produces 2 tabs

### ISSUE THREAD

**Issue by schrodincat** [sublimehq/sublime_merge#696]
**Version info**

 - OS: macOS 10.15.3 (19D76)
 - Build: 2002

**Description**

Using `open -a "Sublime Merge.app" /path/to/git/repo` opens Sublime Merge with 2 tabs (see screenshot). This is a standard way to open apps through the command line and it's used by many 3rd party tools. The issue presents itself only if the app is already running.

**Steps to reproduce**

1. Launch Sublime Merge.app
2. Close all Sublime Merge windows.
3. `open -a "Sublime Merge.app" /path/to/git/repo` where `/path/to/git/repo` is a Git repo.

**Expected behavior**

A window opens with one tab.

**Screenshots**

<img width="1312" alt="Screenshot 2020-03-21 at 17 33 50" src="https://user-images.githubusercontent.com/13354491/77228712-2e0d9880-6b9a-11ea-9dea-2f2f4a8447a1.png">

**Comment by jfcherng** [comment]
I can reproduce this on Win7 too.

Double clicking the branch name in the status bar in ST results in that too.

**Comment by dpjohnst** [comment]
Hi @schrodincat,

Thank you for reporting this! I will be investigating this further.

Kind regards,
\- Dylan

**Comment by CheyenneWills** [comment]
Happens on Linux as well. 

Steps to reproduce:

Open SM with a repo
Close SM
Open ST and from a file within the above repo, click on "open git repository"

Now as a comment.. I think I actually like having the ability to have two tabs (or two windows) looking at the same repo.  I often need to browse the contents of multiple branches so having separate "read-only" views of a repo and a single "read-write" view would actually be nice to have.  The read-only view wouldn't be able to alter the "state" of the repo (e.g. checkout a different branch, edit a commit, etc.)

**Comment by dpjohnst** [comment]
Hi all,

Thank you for your feedback!
This will be fixed in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

Could you confirm that the issue described here is fixed as of Build 2003?

Thanks,
\- Dylan

**Comment by jfcherng** [comment]
i can confirm fixed
