### ISSUE TITLE
Sidebar gets reset when opening a repo in a new tab

### ISSUE THREAD

**Issue by myzeiri** [sublimehq/sublime_merge#697]
**Version info**

 - OS: macOS 10.13.6
 - Build: 2002

**Description**

When opening a repo in a new tab, the sidebar/location bar gets reset to its default state and width. The sidebar on the new tab should be in the same state and the same size as in the previously selected tab.

**Steps to reproduce**

1. Open a repo
2. Configure the sidebar to have "Two columns, Files on the left"
3. Collapse the Locations and Files bar, leaving only the commit graph visible
4. Resize the commit graph by dragging to your desired width
5. Open a repo (that you've never opened before in SM) in a new tab
6. The Locations and Files bar is reopened and the width of the commit graph is reset to its default.

**Expected behavior**

The new tab should open with Locations/Files collapsed and with the commit graph the same size as it was in the previous tab. In the stable version of Sublime Merge, a repo opened in a new window would have the same sidebar state and commit graph size as the old window. That behavior should also apply to opening a repo in a new tab with the new UI.

**Comment by dpjohnst** [comment]
Hi @myzeiri,

Thanks for reporting this issue - we'll be investigating this further, and I will keep you updated of progress.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @myzeiri,

This will be fixed in the next build of Sublime Merge.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Fixed as of Build 2003
