### ISSUE TITLE
Add ability to revert single files/hunks/lines

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#7]
**Problem description**

If a bug was found being introduced by a commit, it might be useful to be able to revert the causing file, hunk or even just a single line of code. This can be required as a temporary solution until a better fix is available or to remove a regression. It would at least help complete all functions like (stage/stash/revert/...) supporting all kinds of operation in the same way.

**Preferred solution**

The command should work like staging files. Means select single folders, files, hunks or lines to revert.

The hunk header of a committed file currently just shows the "hunk history" button. Maybe the hunk header could be turned into a toolbar containing things like

- Revert Hunk
- etc.

Selecting single lines within the hunk should then change the buttons to 

- Revert Lines
- etc.

The commands should be able to be bound to user defined keys as well.

Such a toolbar could make use of glyphs/icons instead of text to keep the button size as compact as possible. A description of the action can be displayed as tooltip if the button is hovered. The buttons might be hidden in the same way as the current "hunk history" button.

**Comment by Drunkendarknut** [comment]
Here's a way to at least check out files:
```json
[
    { "caption": "-" },
    {
        "caption": "Reset file to this version",
        "command": "git",
        "args": {"argv": ["checkout", "$commit", "$path"]}
    }
]
```
Save in your user folder as File.sublime-menu.

**Comment by shawjef3** [comment]
Reversing/reverting hunks and selected lines are the only features keeping me from switching from SourceTree.

**Comment by srbs** [comment]
Workaround:
https://forum.sublimetext.com/t/reverse-hunk-workaround/44645

**Comment by kakra** [comment]
Isn't this usually a problem of having committed unrelated changes within the same commit previously? If a hunk could work on it's own it should have been committed as a single commit in the first place... While it may come in handy, it may promote not committing atomic changes.

If you need to revert a hunk, you should probably revert the complete commit without yet committing it, then only stage the hunks that need to be reverted, commit, then discard the rest.

So I think it could be useful to have a context menu item "Revert without committing" aka `git revert --no-commit`. That way, you could either squash multiple reverts into one, or stage just one reverting hunk and discard the rest.

**Comment by deathaxe** [comment]
> Isn't this usually a problem of having committed unrelated changes within the same commit previously?

No. What if you made a fix for an issue which containes many code lines. During review another guy finds a regression in maybe one or two lines, which he wants to revert.

This might not be an everyday scenario, but I was sometimes faced to it here and there.

> If you need to revert a hunk, you should probably revert the complete commit without yet committing it, then only stage the hunks that need to be reverted, commit, then discard the rest.

1. Of course, you can always take the long way - or the sublime one.
2. This PR was made with the functionality of GitExtensions in mind and to make all git related functions (stash,stage,revert) work the same way on all pieces of code.

**Comment by srbs** [comment]
This has been added in dev build 2024!

**Comment by deathaxe** [comment]
Nice job.
