### ISSUE TITLE
Diff between commits

### ISSUE THREAD

**Issue by TheClams** [sublimehq/sublime_merge#70]
**Problem description**

It is often usefull to do diff between last commit/current worksapce and another commit.

**Preferred solution**

Add contextual menu to the commit list to do a diff between selected menu and current workspace/last commit

**Alternatives**

Allow selecting two commit and right-click -> diff

**Comment by TheClams** [comment]
Selecting two commit actually already show the diff between two commits, with an indicator "Diffing from ###"

**Comment by dikond** [comment]
I just want to add that this issue helped me found this "feature". Initially I couldn't find how to diff between 2 commits. Sublime Merge has no such command or menu item and it isn't obvious that you can select two commits either, IMHO.
