### ISSUE TITLE
Crash on clicking on a commit right after opening repo in a new tab

### ISSUE THREAD

**Issue by rchl** [sublimehq/sublime_merge#700]
**Version info**

 - OS: macOS 10.15.4
 - Build: 2002

**Description**

A description of what the bug is.

**Steps to reproduce**

1. Open any repository
2. Open the "faulty" repository (only one reproduces the problem but it's private, unfortunately)
3. Click on any commit

**Expected behavior**

No crash

**Screenshots**

Crashes (without crash dialog so basically just closes)

Notes:
I can't quite reproduce this by opening "faulty" repo from the initial empty state screen. Maybe it's timing related...

**Comment by jskinner** [comment]
When you open the problematic repository, you've still got the original one open, I take it?

What sort of files are in the commits that you're clicking on in the problematic repository? Are they the same type of files in the first repository you have open?

In principle you could try running Sublime Merge under a debugger (we ship with debug symbols on macOS), but apple make that really difficult these days.

**Comment by rchl** [comment]
Is there a way to start smerge without the smerge process closing? I can't seem to connect to running process in Catalina so wanted to try to start it through binary but that binary exits after starting SM.

**Comment by jskinner** [comment]
`smerge` is just a helper that starts the real app, which is `/Applications/Sublime Merge.app/Contents/MacOS/sublime_merge` on mac

**Comment by rchl** [comment]
Since I can't provide the reproduction steps (I can't even reproduce this myself anymore), I think there is no point in keeping this issue open.
