### ISSUE TITLE
Clicking the triangle toggle of the Work Directory in the Summary tab crashes Sublime Merge

### ISSUE THREAD

**Issue by rpkoller** [sublimehq/sublime_merge#701]
**Version info**

 - OS: MacOS 10.13.6 (17G12034)
 - Build: 2002

**Description**

When clicking the Working Directory toggle triangle in the Summary tab Sublime Merge crashes each and every time. 

**Steps to reproduce**

1. I've created a new repository locally within a existing directory with a Drupal code base managed by composer in it. 
2. Narrowed the unstaged files down to 2654 with `.gitignore`
3. Then clicked within the Summary tab onto the toggle triangle for the Working Directory (see screenshot)

**Expected behavior**
I would expect Sublime Merge not to crash consistently each time I click that toggle. ;) ...and I would expect that Sublime Merge would write a crash report but I am unable to find any in `~/library/logs/diagnosticreports/`

**Screenshots**
![Bildschirmfoto 2020-03-28 um 02 26 07](https://user-images.githubusercontent.com/1665422/77811701-6cc0b880-709c-11ea-8ced-b1ff130ff383.png)

**Comment by dpjohnst** [comment]
Hi @rpkoller,

Thanks for reporting this issue! 

I suspect this is a performance issue with displaying 2654 untracked files at once. Could you confirm for me whether the application crashes (closes entirely) or hangs (stays unresponsive)? 

Additionally, do you still see the issue when starting Sublime Merge in safe mode (accessed by running the command ```smerge --safe-mode``` 

Thanks,
\- Dylan

**Comment by rpkoller** [comment]
Hi Dylan... The application crashes instantly and closes entirely... no hangs and not staying unresponsive for a millisecond. tried starting in the safe mode now . Exact the same effect and "behavior". The odd thing is that still no crash report is created. :/

**Comment by rpkoller** [comment]
Yep probably due to the initial high number of untracked files.... 
![Bildschirmfoto 2020-03-30 um 01 30 19](https://user-images.githubusercontent.com/1665422/77863932-462e8900-7226-11ea-86e0-4239a77735a5.png)
And tried the same creating a new repo for a directory with a single file in it. There clicking the toggle works: 
![Bildschirmfoto 2020-03-30 um 01 33 07](https://user-images.githubusercontent.com/1665422/77863981-783feb00-7226-11ea-8ea9-781e6ad19479.png)

**Comment by dpjohnst** [comment]
Thanks @rpkoller,

I've been able to reproduce the issue, and will be investigating a fix for the issue!

You can expect this to be fixed in the next build of Sublime Merge :)

Many thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @rpkoller,

Could you confirm that build 2003 fixes this issue for you?

Many thanks,
\- Dylan

**Comment by rpkoller** [comment]
I've tried with build 2004 now... I've tried with a new Drupal repo without a `.gitignore` file which lead to 19808 untracked files initially. The crash doesn't take place anymore and i was able to collapse the toggle. 
![Bildschirmfoto 2020-03-31 um 12 19 13](https://user-images.githubusercontent.com/1665422/78015616-ed581100-7349-11ea-9f40-a934a4a55738.png)
so i would consider the issues fixed. I only have an ux related follow up nitpick with the way things are currently handled. consider someone new to the app or someone savvy. both have no idea what is happening. at least the latter could expect that there are too many files to process. the former has no idea at all and thinks either there is a bug and the app is behaving odd or even more wonky. ;) 

i would suggest to add some microcopy feedback if a certain number of unstaged files is reached making it unviable to display and would take a too high toll performance wise.  in the summary tab for the collapsed working directory. something like `The number of untracked files is too high. Either stage and commit them or narrow down the scope with a .gitignore file upfront`. similar to the untracked files tab. there the fans also start to spin up immediately in build 2004 even there is the remark `too many files to display` and nothing to parse and display. There i wonder why the fans are keep spinning when the untracked files tab is still open even there is the condition with too many files to display?

**Comment by dpjohnst** [comment]
Hi @rpkoller,

Thanks for your feedback - I've noted it down on my end. As the original issue is fixed, I'm going to go ahead and close this, but please feel free to file any more feedback on the issue tracker :)

To address your second comment: we've actually got a second performance improvement in the works. Once this is out, there should be a drastic improvement in the performance of the untracked files dialog when there are too many files to display (your fans should stay very quiet).
