### ISSUE TITLE
Diffs of long single-line files are unreviewable

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/sublime_merge#702]
**Version info**

 - OS: Arch Linux
 - Build: 2002

**Description**

When viewing a diff for a single-line file with a long line, the scroll bar overlaps with the line's text and becomes practically invisible and impossible to handle. This is mostly the case for generated minified files, e.g. JavaScript or CSS, which you rarely need to review if at all, but it's an issue nonetheless.

**Steps to reproduce**

1. Open repository https://github.com/SublimeText/sublime_lib on branch `gh-pages`
2. View the diff for `searchindex.js` in `01de6f481cd36d201a325e045487e5dc262738ca` in two-column mode (makes the issue more prominent)

**Screenshots**

![2020-03-28_16-03-22](https://user-images.githubusercontent.com/931051/77826100-ba293e00-710d-11ea-975e-2fc4e73b7d10.png)

**Comment by srbs** [comment]
probably a duplicate of #85

**Comment by dpjohnst** [comment]
Thanks for reporting this @FichteFoll!

We'll be investigating ways we can improve this experience in the future.

Cheers,
\- Dylan

**Comment by FichteFoll** [comment]
I don't quite remember which build it was, but this issue has been fixed by scroll bars now appearing below a hunk and always being visible.
