### ISSUE TITLE
Command palette entry for switching between light/dark theme

### ISSUE THREAD

**Issue by jnns** [sublimehq/sublime_merge#703]
**Problem description**

A description of a problem, workflow or integration that your suggestion would solve. If the problem is OS-specific, include that information here.

Depending on the time of day (or rather lighting conditions) I cycle between the light and the dark theme of Sublime Merge. Right now this involves the following steps:

1. <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>p</kbd>
2. Type `pref`
3. <kbd>ENTER</kbd>
4. Switch to mouse and select desired theme. (The radio buttons cannot be toggled via keyboard).
5. Click "Close"

**Preferred solution**

If switching themes were available through the command palette it wouldn't be necessary anymore to reach for the mouse.

1. <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>p</kbd>
2. Type `theme`. ("UI: Toggle theme" appears as selected entry).
3. <kbd>ENTER</kbd>

**Alternatives**

There's the [request](https://github.com/sublimehq/sublime_merge/issues/490) to have Sublime Merge automatically toggle themes depending on system UI status. In my opinion the command palette entry would be so simple to use that I personally wouldn't need automatic switching.

Thanks for the ongoing work and for considering this change.

**Comment by Zwyx** [comment]
I am also keen to see this feature implemented.

In the meantime, here's a convoluted solution that I found to do this:

Create the file `~/.config/sublime-merge/Packages/User/switch-theme.sh`, containing:

```sh
prefsFile=$(dirname $0)/Preferences.sublime-settings

if grep -q "Merge.sublime-theme" $prefsFile; then
	sed -i \
		-e 's/^\t"theme":.*$/\t"theme": "Merge Dark.sublime-theme"/g' \
		$prefsFile
else
	sed -i \
		-e 's/^\t"theme":.*$/\t"theme": "Merge.sublime-theme"/g' \
		$prefsFile
fi
```

In `~/.gitconfig`:

```ini
[alias]
	switch-sublime-theme = !~/.config/sublime-merge/Packages/User/switch-theme.sh
```

Now we can create a command, in `~/.config/sublime-merge/Packages/User/Default.sublime-commands`:

```json
[
	{
		"caption": "Switch theme",
		"command": "git",
		"args": { "argv": ["switch-sublime-theme"] }
	}
]
```

And/or create a shortcut, in `~/.config/sublime-merge/Packages/User/Default (Linux).sublime-keymap`:

```json
[
	{
		"keys": ["alt+shift+t"],
		"command": "git",
		"args": { "argv": ["switch-sublime-theme"] }
	}
]
```

**Comment by jnns** [comment]
Hello @Zwyx . Thanks for sharing your solution. 

My own workaround currently is to alias two commands to switch between light and dark themes in Gnome Shell. Every relevant application (Sublime Text, Sublime Merge, Firefox, Gnome-Terminal) adapts accordingly nowadays.

```
alias dark 'gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark'
alias light 'gsettings set org.gnome.desktop.interface gtk-theme Adwaita'
``` 

Sublime Merge: 

 - Preferences → General → Theme → Auto (switches to match the OS appearance)

Sublime Text: 

 - Command Palette → UI: Select Color Scheme → Auto 
 - Command Palette → UI: Select Theme → Adaptive
 
Firefox:

 - `about:addons` → Themes → System-Theme

**Comment by dpjohnst** [comment]
Hi all,

Thank you for your sharing this feedback!
This was added in Sublime Merge 2084 (and will be in the next stable build too).

Kind regards,
\- Dylan from Sublime HQ
