### ISSUE TITLE
Can't Hide Divergent Branches

### ISSUE THREAD

**Issue by tajmone** [sublimehq/sublime_merge#704]
In SM (`Dev Build 2004`, under Win 10 x64) attempting to hide a divergent branch doesn't work.

To reproduce the error, clone the following repository:

https://github.com/tajmone/Tonton-Pixel-Photoshop-Scripts

The `master-old` branch is a copy of the original `master` branch before rewriting its history (i.e. squashing the first 36 commits into one — see #687).

Try to uncheck the eye icon for `master-old` branch (both local and remote), you'll notice that the UI isn't affected, and the divergent commits are still there. The problem occured also when the `master-old` branch was only present locally.

Probably the same applies to orphan branches in general (e.g. GitHub Pages orphan branches), which SM seems to have problems handling in various respects.

**Comment by DavidWang1024** [comment]
Hi tajmone,

I haven't been able to replicate the issue, the master-old branch is correctly hidden when I hide it in graph.

Are you able to give more details as to what causes this issue? Can this problem be reproduced on another repository? Perhaps a screenshot?

Thanks

**Comment by tajmone** [comment]
> Can this problem be reproduced on another repository? 

Yes:

- https://github.com/won21kr/Tonton-Pixel-Photoshop-Scripts

For the full details, please look at #687 — this bug is related to the same repository that caused the other bug reported there.

**Comment by DavidW1024** [comment]
Thanks for the details tajmone, I'll investigate further to see if I can replicate this issue on my end and narrow down the cause.

I would like to know, if possible, whether this issue can be replicate on another machine and on a unrelated repo?

**Comment by tajmone** [comment]
> I would like to know, if possible, whether this issue can be replicate on another machine and on a unrelated repo?

I currently have installed SM only on one machine. But I'll let you know if I encounter this problem in other repositories too — I should have a couple of repositories with an orphan branch for GitHub Pages, which probably replicate this problem.

I just need to find some time to experiment with it, but I'll let you know.

**Comment by DavidW1024** [comment]
Thank you!

**Comment by tajmone** [comment]
@DavidW1024, while I was about to take a screenshot of the problem I realized that the issue was due to the presence of an extra dev branch based on the original. So basically, I wasn't hiding all the branches in the first place.

I apologize for the inconvenience. 😢  I simple missed out that extra branch (_mea culpa_).
