### ISSUE TITLE
Unable to open a new instance of Sublime Merge with -n

### ISSUE THREAD

**Issue by TheClams** [sublimehq/sublime_merge#707]
**Version info**

 - OS: CentOS 7, Windows 10, XUbuntu 19.10
 - Build: 2004

**Description**

Unable to open a new instance of Sublime Merge when there is already one opened

**Steps to reproduce**

1. run `smerge`
2. run `smerge -n`

**Expected behavior**

There should be two instance of sublime merge, but there is only one

**Comment by dpjohnst** [comment]
Hi @TheClams,

I've been able to reproduce this issue, and have made a fix. This should be fixed in the next build of Sublime Merge.

Thanks,
\- Dylan

**Comment by TheClams** [comment]
Thanks, I tested it and it works.
