### ISSUE TITLE
Improve logging for commands run (with from the palette)

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/sublime_merge#711]
**Problem description**

The same applies to Sublime Text, but is more prominent for Merge. Related: https://github.com/sublimehq/sublime_text/issues/1834.

As I was trying to add key bindings for some commands, notably pre-selecting the remote for creating a tag, I wanted to figure out what command Merge runs after my input, but the `log_commands` setting does not expose this. 

Commands spawned by key bindings or menus are logged properly, until the command palette is involved, which swallows all further logging and hides arguments inserted by input handlers. As an example, following are console logs for pushing a tag from various sources:

Context menu:
```
command: show_command_palette {"args": {"ref": "refs/tags/test"}, "command": "push_tag", "description": "Push test"}
Executing: git -c credential.helper=/opt/sublime_merge/git-credential-sublime push --progress origin test
```

Command palette:
```
command: show_command_palette
Executing: git -c credential.helper=/opt/sublime_merge/git-credential-sublime push --progress origin test
```

Key binding (custom, direct):
```
command: push_tag
Executing: git -c credential.helper=/opt/sublime_merge/git-credential-sublime push --progress
```

Key binding (custom, indirect):
```
command: show_command_palette {"command": "push_tag"}
Executing: git -c credential.helper=/opt/sublime_merge/git-credential-sublime push --progress origin test
```

**Preferred solution**

Either log nested command executions or at least log those run via the command palette, which acts as a command hub.

**Alternatives**

Documentation for all available commands and their arguments would be nice.

**Comment by BenjaminSchaaf** [comment]
We've got a fix for this in the pipeline

**Comment by FichteFoll** [comment]
The logging has been fixed, thanks.

Unfortunately, my initial motivation for this issue in trying to provide a default remote argument for the push_tag command can not be solved through key bindings, so I'll create a separate issue for that.
