### ISSUE TITLE
Worktrees with submodules will consistently show the unchanged submodules as unstaged changes in Sublime Merge

### ISSUE THREAD

**Issue by colekurk** [sublimehq/sublime_merge#712]
**Version info**

 - OS: macOS 10.14.6
 - Build: 1119

**Description**

When using worktrees in a repo with submodules, Sublime Merge always reports the submodules as unstaged changes as long as the main repo has initialized the submodules and the worktree submodule commits do not match the main repo's submodules' commits.

**Steps to reproduce**

1. Create a repo
2. Add a submodule
3. Add a worktree to the created repo
4. Initalize the submodules in the worktree
5. Checkout a different submodule commit (this may not always be necessary to reproduce)

Sublime merge will now always display the submodule as an unstaged change when in the commit changes view. Pressing "Stage" or "Discard" does nothing in this state if `git status` does not show anything for the submodule, though they work correctly if there is actually an unstaged submodule change.

Note: The commit changes view shows the submodule change as the current submodule commit in the worktree being updated to the current submodule commit in the main repo
 e.g. `<submodule updated SUBMODULE_REF_IN_WORKTREE -> SUBMODULE_REF_IN_MAIN_REPO>`

**Workaround**
Delete or rename the `.git/modules` directory in the main repo. This will fix the issue until the main repo has its submodules intialized again.

**Expected behavior**
Submodules should only appear changed when they have actually been changed in the current worktree. `git status` behaves correctly in this scenario.

**Comment by BenjaminSchaaf** [comment]
We've got a fix for this in the pipeline

**Comment by BenjaminSchaaf** [comment]
This should be fixed in build 2006
