### ISSUE TITLE
Creation of a tag (local) with name <TagName> will create a tag with name <Commit Hash> instead

### ISSUE THREAD

**Issue by sonhuytran** [sublimehq/sublime_merge#713]
**Version info**

 - OS: Windows 10
 - Build: 2005

**Description**

Creation of a tag (local) with name &lt;TagName&gt; will create a tag with name &lt;Commit Hash&gt;

**Steps to reproduce**

1. Open repository
2. Run command "Create Tag..."
3. Type your name &lt;TagName&gt;
4. A tag created with name &lt;Commit Hash&gt;

**Expected behavior**

4. A tag created with name &lt;TagName&gt;

**Screenshots**

![2020-04-07_07h04_07](https://user-images.githubusercontent.com/3252584/78632326-00656680-789f-11ea-8f78-5726e29066ee.png)
![2020-04-07_07h04_41](https://user-images.githubusercontent.com/3252584/78632331-02c7c080-789f-11ea-9a49-94135badabf1.png)

**Comment by dpjohnst** [comment]
Hi @sonhuytran,

Thank you for reporting this! I've been able to fix this issue, and it should be fixed on your end in the next build of Sublime Merge :)

**Comment by sonhuytran** [comment]
Hi @dpjohnst,

I confirmed that it's fixed with the build 2009 on 17 april 2020.
Thank you so much for your works, very pleased to use Sublime's products.
