### ISSUE TITLE
Git flow does not work

### ISSUE THREAD

**Issue by steveooo1** [sublimehq/sublime_merge#714]
**Version info**
 - OS: macOS Mojave
 - Build: 2005

**Description**
When trying to add a feature via git flow in Sublime Merge command palette, I get following error:
```
/Applications/Sublime Merge.app/Contents/Resources/Git/git/libexec/git-core/gitflow-shFlags: line 138: 21784 Abort trap: 6           ${FLAGS_GETOPT_CMD} > /dev/null 2>&1
/Applications/Sublime Merge.app/Contents/Resources/Git/git/libexec/git-core/gitflow-shFlags: line 158: _flags_fatal: command not found
/Applications/Sublime Merge.app/Contents/Resources/Git/git/libexec/git-core/gitflow-shFlags: line 273: [: too many arguments
/Applications/Sublime Merge.app/Contents/Resources/Git/git/libexec/git-core/gitflow-shFlags: line 273: [: too many arguments
/Applications/Sublime Merge.app/Contents/Resources/Git/git/libexec/git-core/gitflow-shFlags: line 273: [: too many arguments
/Applications/Sublime Merge.app/Contents/Resources/Git/git/libexec/git-core/gitflow-shFlags: line 1024: [: -ne: unary operator expected
flags:WARN dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Applications/Sublime Merge.app/Contents/Resources/Git/git/libexec/git-core/getopt
  Reason: image not found
flags:FATAL unable to parse provided options with getopt.
```

**Comment by dpjohnst** [comment]
Hi @steveooo1,

Could you confirm this works on the command line for you?
Alternatively, could you change your Git binary version to System (via Preferences > Advanced > Git Binary > ...), and confirm whether this fixes the issue?

Thanks,
\- Dylan

**Comment by steveooo1** [comment]
@dpjohnst What do you mean with "confirm THIS works..."? Do you have any code for me to run?

**Comment by dpjohnst** [comment]
Hi @steveooo1,

could you change your Git binary version to System (via Preferences > Advanced > Git Binary > ...), and confirm whether this fixes the issue?

Kind regards,
\- Dylan

**Comment by steveooo1** [comment]
@dpjohnst It says: "Git flow is not installed":

```
git: 'flow' is not a git command. See 'git --help'.

The most similar commands are
	reflog
	show
```

I am on macOS Mojave with git version 2.21.1 (Apple Git-122.3)

**Comment by steveooo1** [comment]
I assumed that the bundled git version has everything it needs?

**Comment by dpjohnst** [comment]
Hi @steveooo1,

Thanks for getting back to me with this information.

To clarify, the bundled version of Git should be sufficient to run Sublime Merge. From the logs you originally sent, it seems as if the gettext installation is not working on your machine. I am unsure what could have caused this, but could you try run ```brew reinstall gettext``` from the terminal?

Thanks,
\- Dylan

**Comment by steveooo1** [comment]
@dpjohnst I don't have Brew. Since when is this a dependency? I checked the docs and didn't find any mention on having to install brew for Merge to run?

I am no fan of brew, because it screwed my complete OS in the earlier days, so I still avoid it.

Or easier asked: When I simply install Sublime Merge and I want to use the integrated Git Flow features. What exactly do I have to do?

**Comment by dpjohnst** [comment]
Hi @steveooo1,

Thank you for your patience while we investigate this.

Brew should definitely not be a dependency when working with Sublime Merge, however it seems from the original log you sent that the bundled Git Flow was having troubles finding gettext libraries.
For the moment, it seems as if the bundled Git Flow is not working correctly (this may be an issue with the version of Git we bundle), and will need further investigation. 

In the meantime, what I'd suggest is manually installing git flow on your machine. For example, see: https://github.com/nvie/gitflow/wiki/Mac-OS-X

If the issue still persists at this point, then I suggest switching to the system Git (as described earlier).

Please don't hesitate to reach out again, and I'll be more than happy to assist you further.

Thanks,
\- Dylan

**Comment by steveooo1** [comment]
Ok thanks. But would be great to have this fixed by using the bundled version. In Tower.app I always used the bundled Git version and it was great! It was an up-to-date Git version and gitflow worked great.

**Comment by steveooo1** [comment]
Any update on this?

**Comment by dpjohnst** [comment]
Hi @steveooo1,

We've managed to reproduce the issue on our end, and we are actively working to produce a fix.
I'll send further updates here when the fix has been released.

Thank you for reporting this, and for your patience while we investigate it further.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @steveooo1,

Just keeping you updated - we're in the process of releasing a new bundled Git version for the MacOS client. This should fix the issues with git flow you've been seeing. I'll send you a further follow-up when the update has been released.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @steveooo1,

Good news - we've just released a new development build of Sublime Merge which should resolve this issue.

Could you confirm this fixes the issue on your end?

Thanks,
\- Dylan

**Comment by steveooo1** [comment]
@dpjohnst It seems to work! Thank you!! <3
