### ISSUE TITLE
Creating a tag without a message, creates a tag with strange name.

### ISSUE THREAD

**Issue by meboev** [sublimehq/sublime_merge#717]
**Version info**

 - OS: Windows 10 x64
 - Sublime Merge, Build: 2006

**Description**

Creating a tag without a message, creates a tag with a hash-like name.

**Steps to reproduce**

1. Right click on a commit, and select "Create Tag at Commit"
2. Specify a random Tag Name, for example: asdf
3. Do NOT specify a "Tag Message" (with Tag Message it works correctly)
4. Witness a new tag is created with a hash-like name, for example: 5fffd3a20cabec3c0ff6a4ed111bdecf85ea25ff

**Expected behavior**

A tag with the specified name to be created.

**Screenshots**

![image](https://user-images.githubusercontent.com/2070752/78788936-23823a00-79b5-11ea-85e9-9e2e8e0f23be.png)

**Git Console output**
Tag name: qq; Tag message: <empy>; Error
Executing: "C:\Program Files\Sublime Merge\Git\cmd\git.exe" tag -a -m  qq 601cdf17ac029b3e2597f2081d868685d5a881be

Tag name: qq; Tag message: aa; Correct
Executing: "C:\Program Files\Sublime Merge\Git\cmd\git.exe" tag -a -m aa qq 601cdf17ac029b3e2597f2081d868685d5a881be

**Possible solution**
You should probably not add the -m flag if a message is empy.

**Comment by srbs** [comment]
Probably a duplicate of #713

**Comment by BenjaminSchaaf** [comment]
@meboev Could you confirm that this is fixed in build 2009.

**Comment by meboev** [comment]
> @meboev Could you confirm that this is fixed in build 2009.

Yes, this is now fixed in build 2009.
Thanks.
