### ISSUE TITLE
Sublime Merge Tabs Showing Full Path on Windows 10 instead of Folder Name

### ISSUE THREAD

**Issue by tkuraku** [sublimehq/sublime_merge#718]
**Version info**

 - OS: Windows 10
 - Build: 2006

**Description**

On Linux Sublime Merge tabs only show the folder name, but on windows 10 the full path to the repository is shown and makes the tabs bigger and harder to navigate.

**Steps to reproduce**

Open multiple tabs with sublime merge on windows 10.

**Expected behavior**

Tabs should only show the folder name, unless there are two repositories open with the same folder name in different directories.

**Comment by dpjohnst** [comment]
Hi @tkuraku,

Thank you for taking the time to report this! This will be fixed in the next build of Sublime Merge.

Thanks,
\- Dylan

**Comment by tkuraku** [comment]
Great. Thank you.
