### ISSUE TITLE
Tag message is required when creating a new tag

### ISSUE THREAD

**Issue by onecrayon** [sublimehq/sublime_merge#72]
**Version info**

 - OS: macOS 10.13.6
 - Build: 1065

**Description**

When creating a new tag (via right click "Create Tag at Commit"), Sublime Merge will not create the tag unless you enter a message for the tag.

**Steps to reproduce**

1. Right click a commit and choose "Create Tag at Commit"
2. Type a tag name and hit enter
3. Hit enter to attempt to create the tag without a message

Nothing happens.

**Expected behavior**

A tag should be created without a description.

**Comment by deathaxe** [comment]
In some situations you might want to add a message. But you are right, an empty message should be accepted as well and result in a simple tag.

**Comment by onecrayon** [comment]
Yeah, I've got nothing against being *prompted* for a message. It's just that I can't immediately hit enter a second time to commit a message-less tag that's the problem for me.

**Comment by jskinner** [comment]
This in fixed in 1070
