### ISSUE TITLE
Long lines are not wrapped in the "Show Git Output" pop-over window

### ISSUE THREAD

**Issue by doersino** [sublimehq/sublime_merge#721]
**Version info**

 - OS: macOS 10.14.6
 - Build: 1119

**Description**

When pushing a commit to a remote that has a `post-receive` hook (or similar) which produces long lines in its output, the output in the "Show Git Output" pop-over window neither wraps nor is horizontally scrollable. This makes it impossible to see most of the output.

**Steps to reproduce**

Set up a remote and a repository as outlined above:

```
mkdir test.git
cd test.git
git init --bare
echo "echo 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'" > hooks/post-receive
chmod +x hooks/post-receive
cd ..
git clone test.git
cd test
touch test.txt
git add test.txt
git commit -m "test"
```

1. Open the repository "test" in Sublime Merge.
2. Push.
3. Click the "Show Git Output" button.

**Expected behavior**

Long lines are automatically wrapped (preferred) *or* horizontal scrolling is enabled.

**Screenshots**

<img width="1072" alt="Screenshot 2020-04-10 at 15 22 13" src="https://user-images.githubusercontent.com/1944410/78993894-18f3ac00-7b3f-11ea-9c2c-d4fedacbb7ce.png">

**Comment by willrowe** [comment]
This is a duplicate and has already been fixed for the next release.
