### ISSUE TITLE
Opon Repo Drop Down List

### ISSUE THREAD

**Issue by tkuraku** [sublimehq/sublime_merge#723]
**Problem description**

Right now if I have many git repo tabs open in sublime merge it is difficult to navigate them or see how many are open as some are pushed off the screen near the "+" icon to open a new repository.  There should be a quick drop down menu to see all open tabs and navigate to a selected one. Maybe on the far left of the tab bar.

**Comment by tkuraku** [comment]
![smerge](https://user-images.githubusercontent.com/11217294/79161340-2f447680-7d90-11ea-98c9-7c2eb6884205.png)

**Comment by tkuraku** [comment]
![smerge](https://user-images.githubusercontent.com/11217294/79161566-8cd8c300-7d90-11ea-83ab-924e235b4211.png)

**Comment by PatWie** [comment]
Something like the GoTo/Switch Project Dialog to navigate between projects like in SublimeText would be indeed super useful!

**Comment by srbs** [comment]
@PatWie, `cmd`/`ctrl`+`shift`+`o` or `File` -> `Switch Repository...` already supports this & switches tabs/windows if it is already open, otherwise replaces the current repository.

**Comment by tkuraku** [comment]
fixed in build 2030 with tab selector.
