### ISSUE TITLE
No swift syntax highlighting support in Sublime Merge

### ISSUE THREAD

**Issue by hk0i** [sublimehq/sublime_merge#724]
**Problem description**

It seems like Sublime Merge doesn't come with any swift syntax highlighting support. Being able to do language highlighting on top of diff highlighting is a huge selling point for many.

**Preferred solution**

Expand sublime merge to support a subset of Sublime Text plugins, allowing free access to the existing Sublime Text ecosystem of plugins. This way any new language that requires support can easily be handled by the community organically instead of requiring a full software update to support it.

**Alternatives**

Hard code that sh!t

**Screenshots**

(I'll update later with screenshots when I have access to some non-proprietary code later)

**Comment by dpjohnst** [comment]
Hi @hk0i,

Thank you for taking the time to share you feedback! Adding plugin support to Sublime Merge is definitely on the roadmap :)

In the meantime, I can confirm we load third-party packages from Sublime Text (for use in Sublime Merge). This means you can install a swift syntax definition in Sublime Text, and it should appear in Sublime Merge! Let me know if you have any trouble setting this up, and I can give you a hand.

Thanks,
\- Dylan

**Comment by deathaxe** [comment]
If you have ST and SM installed normally (no portable builts), Sublime Merge should pick up all syntax definitions from Sublime Text automatically.

SM looks into _%APPDATA%\Sublime Text 3_ on Windows or _~/.config/sublime-text-3_ on Linux/MacOS.

Not sure whether it also works with the new ST4xxx folders, though.

**Comment by hk0i** [comment]
That worked 👍 I did not have sublime text installed on this machine so I had no packages for it to load.
Thanks!

Closing this issues.
