### ISSUE TITLE
The first line of a commit message jumps in and out of view when entering new lines

### ISSUE THREAD

**Issue by myzeiri** [sublimehq/sublime_merge#727]
**Version info**

 - OS: Windows 10
 - Build: 2009

**Description**

When writing a commit message, the first line seems to jump in and out of the view as you enter new lines.

**Steps to reproduce**

1. Type one line of a commit message
2. Hit enter twice to add a new line. The first line now leaves the view.
3. Start typing a second line. The first line is visible again.

**Expected behavior**

The first message line should stay put at the top of the view.

**Screenshots**

![screen-capture](https://user-images.githubusercontent.com/7775058/79579067-16d8a280-8095-11ea-8687-14b6f6d6dde6.gif)

**Comment by dpjohnst** [comment]
Hi @myzeiri,

Thank you for reporting this - we'll be investigating this further.

Kind regards,
\- Dylan

**Comment by myzeiri** [comment]
Looks like this was fixed in build 2011. 👍
Closing the issue.
