### ISSUE TITLE
Ignore empty commit messages in history

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#729]
**Problem description**

The dropdown menu next to the commit message editor sometimes contains empty items.

They are most likely added by `git commit --amend` being executed without entering a new commit message.

**Preferred solution**

Don't store (empty) commit messages in the history.

**Alternatives**

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/79589684-1b717b00-80d6-11ea-91d8-f3e407f81bd7.png)

**Comment by BenjaminSchaaf** [comment]
We've got a fix for this in the pipeline

**Comment by hartsublime** [comment]
@deathaxe - Looks like it could be a newline at the start of the commit message beginning with "RunMyScreens: ..." that gives impression there is a bank entry. Could you verify by hovering over the entry. The entry highlighting should indicate if this is the case.

**Comment by deathaxe** [comment]
I don't think any commit message ever started with a new line in one of my repos.

Anyway, the following screen cast illustrates the saved messages are actually empty and `git commit --amend` creates new ones. The last 4 valid entries are reduced by one.

Yes , I know - maybe do commits too quickly and amend too often ;-)

![Animation](https://user-images.githubusercontent.com/16542113/79880206-fb9cc880-83ef-11ea-98c5-55bf0b797b4b.png)

**Comment by hartsublime** [comment]
@deathaxe Thanks for verifying! In any case both issues have been resolved in the forthcoming build.

**Comment by deathaxe** [comment]
Nice, thank's very much!

**Comment by dpjohnst** [comment]
Hi all,

Just following up - this issue has been fixed in the latest build.

I'm going to go ahead and close this issue, but please feel free to reopen it if you experience any issues going forward.

Thanks,
\- Dylan
