### ISSUE TITLE
Branch visibility not stored in the session

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#73]
**Version info**

 - OS: Windows 10
 - Build: 1067

**Description**

Built 1067 introduces the awesome function to hide branches via location bar. The visibility state seems not to be stored in the session file, which results in all hidden branches to reappear after closing and reopening SM.

**Steps to reproduce**

1. Open repository ...
2. Hide some branches
3. Close SM
4. Open SM

**Expected behavior**

A hidden branch should still be hidden after closing SM.

**Comment by jskinner** [comment]
Implemented in 1068
