### ISSUE TITLE
Git status dropdown panel pane split moves in the opposite direction to a mouse drag

### ISSUE THREAD

**Issue by kortschak** [sublimehq/sublime_merge#730]
**Version info**

 - OS: Ubuntu 18.04
 - Build: 2006

**Description**

Status drop down pane split handle moves the opposite direction of the drag.

**Steps to reproduce**

1. Open a repository.
2. Perform a git operation that results in a git status update.
3. Click on the "Show git output" button in the status dropdown.
3. Drag the pane divider (boxed in red in the image below) to the left or right.

**Expected behavior**

Pane split moves with the mouse drag.

**Actual behavior**

Pane split moves in the opposite direction.

**Screenshots**

![Screenshot from 2020-04-23 11-55-54](https://user-images.githubusercontent.com/275221/80069672-e4411500-8580-11ea-9d99-78fd6e660f89.png)

**Comment by hartsublime** [comment]
Thanks for the report! We'll have a fix in the next build.

**Comment by dpjohnst** [comment]
Hi @kortschak,

Thanks again for reporting this!

Just a quick follow-up: a new build of Sublime Merge (v2011) has been released which addresses this issue. Please feel free to re-open this issue if you are still experiencing it.

Kind regards,
\- Dylan

**Comment by kortschak** [comment]
@dpjohnst Thanks. Fix confirmed. Shall, I post a feature request to have the position state persist between drop downs? At the moment it makes odd choices (read "choices that don't agree with mine, though I can see why they're made").

**Comment by dpjohnst** [comment]
Hi @kortschak,

If you could post a feature request that would be much appreciated.

Thanks,
\- Dylan
