### ISSUE TITLE
Client stalls for several minutes after committing to the Linux kernel source tree

### ISSUE THREAD

**Issue by kakra** [sublimehq/sublime_merge#732]
**Version info**

 - OS: Gentoo Linux
 - Build: 1119

**Description**

When committing to the Linux kernel source (or doing similar operations like rebase, edit commit message etc), Sublime Merge stalls for several minutes. I can still somewhat use the GUI but the commit list itself is stale and out-of-date. Trying to quit the client states a message box that the application does not respond and asks if I'd like to kill the window.

**Steps to reproduce**

1. Clone the Linux kernel source with git
2. Commit a change to some source file using Sublime Merge or Git CLI while Sublime Merge is opened
3. Try to do another action in Sublime Merge or try to quit Sublime Merge, and you'll discover it's no longer responding properly for several minutes and the view state is out of sync with the repo

**Expected behavior**

Sublime Merge should recover faster from such operations. It looks like it's still doing some background work on the old commit state while I'm interested in the new. Other clients like `tig` just restart scanning commits from scratch in such situations. If I force-quit Sublime Merge and restart it, it immediately shows the current status of the source tree, so viewing the current state itself seems not to be the performance problem. As a good start on improving this, a progress indicator would be nice and it should not block on trying to quit the application. If whatever background worker is blocking becomes fixed by this, it should be easy to emit a "stop background worker and start over signal" when Sublime Merge detects a new HEAD.

**Comment by jskinner** [comment]
This should be fixed in the current dev build at https://www.sublimemerge.com/dev - let me know if its not.

Alternatively, the next stable build with these changes isn't too far away

**Comment by kakra** [comment]
Yes, seems to work fine now by a quick test. Thanks.

But now it shows a different behavior: Whenever I try to ctrl+click multiple commits to select for a squash it will just deselect these commits again the next second. Trying like 10 times finalle leaves the commits selected. Now sure if this is already known. Maybe also a problem just with big source trees like the kernel.

**Comment by dpjohnst** [comment]
Hi @kakra,

Just following up on this - the issue you referred to above will be fixed in the next development build of Sublime Merge. I'll follow up again on this thread when it's been released!

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @kakra,

This issue should be fixed in the latest development build (v2011) of Sublime Merge.
Could you please confirm for me whether it's fixed on your end?

Thanks,
\- Dylan

**Comment by kakra** [comment]
I could no longer observe the problems.
