### ISSUE TITLE
Sublime Merge Build 2010: Unable to start due to Xorg dependency

### ISSUE THREAD

**Issue by trobjo** [sublimehq/sublime_merge#739]
**Version info**
Sublime Merge Build 2010
Sway on Arch Linux. That is, I run Wayland only, no Xorg.

**Description**

I cannot launch Sublime Merge any longer.

Somehow this very upgrade introduced a runtime dependency of Xorg. It gives me this warning:

`(sublime_merge:34521): Gtk-WARNING **: 10:01:17.575: cannot open display:`

This is the warning an application that tries to run as an Xorg application gives when it -- understandably -- fails to launch due to not finding an X server.

Before this build and after the migration to GTK3 Sublime Merge (and, Sublime Text as well for that matter) had no problems running in a Wayland-only environment.

Why has this dependency been introduced now? It seems completely backwards to integrate a dependency that is slowly being phased out in the Linux world.

**Steps to reproduce**

Open Sublime Merge in a terminal with `smerge` in a Wayland session without XWayland (and therefore no DISPLAY env var set).

**Expected behavior**

The application should launch normally, as it has done before.

**Comment by dpjohnst** [comment]
Hi @trobjo,

Thank you for reporting this! 

We're actively investigating this issue, and we will keep you updated as we progress.

Kind regards,
\- Dylan

**Comment by BenjaminSchaaf** [comment]
Do note that while we try to avoid/fix crashes and incompatibilities when we can, running under Wayland is not something we fully support due to missing features that prevent functionality like tab dragging from working as expected.

**Comment by trobjo** [comment]
That is perfectly understandable. 

But how shall I interpret your answer? 

I do not use the more advanced GUI features found at the intersection of Sublime, the GTK toolkit, and my compositor, so I care less about "full Wayland support", but I hope I am correct in assuming that you will treat this as a bug with a reasonably high priority, so I can continue to enjoy using Sublime Merge in the future. I mean, I do not feel like I have been missing out on anything in the past, before this dependency was introduced.

**Comment by BenjaminSchaaf** [comment]
The next build (2011) is already out and should fix this.

**Comment by trobjo** [comment]
That has indeed fixed it!
