### ISSUE TITLE
Make git status drop-down panel pane split either persist state or pick better defaults

### ISSUE THREAD

**Issue by kortschak** [sublimehq/sublime_merge#740]
**Problem description**

The drop-down status panel shows two sets of information, the session git operation status history on the left and the current git output on the right. Arguably the right panel is more informative for most situations, and potentially includes links for PR etc. Currently the default split for this pair of panes give more space to the left panel and less to the right panel (I suspect the split is actually equal for the information-containing parts of each pane). This balance is probably wrong for many situations, although there is likely no correct default for all cases.

Every time the drop-down is selected, it goes back to this default.

**Preferred solution**

Given that there is likely to be no correct default for all cases and users, it would be nice for the position of the division to persist at least within a session (and probably across sessions) so that it does not need to be corrected each time the drop-down is looked at.

**Alternatives**

There is no alternative other than to ignore the problem.

**Screenshots**

![Screenshot from 2020-05-19 12-53-11](https://user-images.githubusercontent.com/275221/82281223-f53e4400-99cf-11ea-8561-5ae48acd3fe5.png)

Note that the right pane needs a scroll bar and the left pane wastes a lot of real estate.

**Comment by dpjohnst** [comment]
Hi @kortschak,

This has been added in Sublime Merge build 2077.

Kind regards,
\- Dylan

**Comment by kortschak** [comment]
Just checked. That's great thank you.
