### ISSUE TITLE
Fuzzy Search for Merge Branch doesn't work as expected

### ISSUE THREAD

**Issue by TheSecEng** [sublimehq/sublime_merge#745]
**Version info**

 - OS: 10.15.5 Beta (19F94a)
 - Build: 2011

**Description**

When working with many branches of a repo, if merging a branch, typing master exactly, still selects a different branch.

**Steps to reproduce**

1. Open repository ...
2. Check out branch
3. Merge Branch
4. Search exact branch name (Master, but a different one is selected)

**Expected behavior**

When typing master, or specific branch names, they should be the first match selected.

**Screenshots**

![2020-05-22_06-52-57 (1)](https://user-images.githubusercontent.com/32599364/82660885-0918be80-9bf9-11ea-8e58-b78a236507a0.gif)

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/32599364/82660479-737d2f00-9bf8-11ea-968d-d53ed8445aba.png">

**Comment by willrowe** [comment]
I believe this may be a duplicate of #663.

**Comment by TheSecEng** [comment]
Thanks! I believe so. Will defer to that issue
