### ISSUE TITLE
Stash With Message does not work

### ISSUE THREAD

**Issue by onecrayon** [sublimehq/sublime_merge#75]
**Version info**

 - OS: macOS 10.13.6
 - Build: 1065

**Description**

The Stash With Message command never executes.

**Steps to reproduce**

1. Modify a file in the repo
2. Stage the changes (or not; makes no difference either way)
3. Command-P to open the command palette, type `stash`, then select "Stash With Message" and hit enter
4. Enter a short message; e.g. `My nifty stash`
5. Hit enter; nothing happens

**Expected behavior**

The stash should be committed with the custom message specified.

**Comment by jskinner** [comment]
What version of git is Sublime Merge using? (The Help|Debug Information menu will show this). From memory, `git stash push`, which is used to implement stash with message, requires a relatively recent version of git.

**Comment by onecrayon** [comment]
SM is currently using the default Apple-installed git:

```
=== App Version Information ===
Build: 1065

=== Git Version Information ===
Using Git: git
git version 2.17.1 (Apple Git-112)
PATH: /usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by onecrayon** [comment]
If it matters, `git stash save "My nifty stash"` on the commandline using the same git version works just fine (as does popping and pushing stashes without a message via the Sublime Merge toolbar buttons).

**Comment by jskinner** [comment]
That version of git supports `git stash push` just fine, and it's working with Stash With Message for me locally, too.

What does the git output overlay say about the stash command that was run? It's accessible via the icon on the left of the infobox, where the branch name is displayed. It should show the command that was executed, and if it was successful or not.

**Comment by onecrayon** [comment]
According to the git output overlay, the stash command is never even executed (it just shows whatever I did immediately prior to trying to run Stash With Message).

**Comment by jskinner** [comment]
I'm not sure what would cause the command to never be run, however it's worth giving this a shot on build 1069 or later, using the bundled version of git. You'll need to set the git_binary preference to "bundled" to use the bundled version of git over the system version.

**Comment by onecrayon** [comment]
I've tested this with build 1070, both using the standard System git and bundled git, and the result is the same (hitting enter does nothing). I also tried using quotation marks vs. not using quotation marks (no difference; tested both double and single quotes).

```
=== App Version Information ===
Build: 1070

=== Git Version Information ===
Using Git: /Applications/Coding/Sublime Merge.app/Contents/Resources/Git/bin/git (bundled)
git version 2.18.0
PATH: /usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by jskinner** [comment]
I think this may just be an unclear UI on our part.

After you choose "Stash With Message", it'll prompt you to select which flags, if any, you want to use. If you don't want any flags, you need to press enter, and then type in the stash message, when the hint text is showing "Optional Message".

i.e., Ctrl+P to show command palette, then select "Stash With Message", then press enter, then type a message and press enter again. From your initial description, I think there needs to be a step 3.5 "press enter again".

The current dev build (1076) has somewhat improved messaging here, but it's still not super clear.

**Comment by onecrayon** [comment]
Aha! That was indeed the problem. If you enter a message when it says "Stash options" and hit enter nothing happens (no feedback of any kind). If I hit enter when it's empty and then enter a message, it works perfectly.

**Comment by jskinner** [comment]
Glad to hear we got this one sorted :)
