### ISSUE TITLE
"Blame File" from Sublime Text is not working

### ISSUE THREAD

**Issue by OlyAney** [sublimehq/sublime_merge#751]
**Version info**
 - OS: macOS Catalina 10.15.4
 - Build: 3211

**Description**
 fter upgrading to newest version shortcut for "blame file" from sublime text stopped working. 
Before it was opening sublime merge and showing the history of the file. Now it does nothing. Attached a screenshot

**Steps to reproduce**
1. Open repository in sublime text
2. Open a file
3. Right click -> "Blame file"
4. Nothing happens

**Expected behavior**
Sublime merge is opened with the history of the file

**Screenshots**
![Screen Shot 2020-05-27 at 2 58 04 PM](https://user-images.githubusercontent.com/43271182/83016386-880f5c00-a02a-11ea-83c8-2af993b7dd3e.png)

**Comment by srbs** [comment]
What version of Sublime Merge are you using? Also, does the command line blame work? (`smerge blame`)

**Comment by OlyAney** [comment]
@srbs sublime merge build is 2020
But now both the command line & right-click + "Blame File" work
Weird 🤔 I think this can be closed

**Comment by dpjohnst** [comment]
Hi @OlyAney,

I'm going to go ahead and close this issue, but please re-open it if you experience the issue again :)

Thanks,
\- Dylan
