### ISSUE TITLE
Sublime Merge Starts & Stops Immediately

### ISSUE THREAD

**Issue by famagusta** [sublimehq/sublime_merge#756]
**Version info**

 - OS: macOS 10.10.5 Yosemite
 - Build: 2020

**Description**

After the most recent update, Sublime Merge will not open. when you click on it, it attempts to open and then immediately closes. 

**Steps to reproduce**

1. Open Sublime Merge

**Expected behavior**

Sublime opens

**Screenshots**

Attached is the console output
![Screen Shot 2020-05-28 at 9 15 56 pm](https://user-images.githubusercontent.com/1617696/83163247-744a1f80-a128-11ea-9978-eae06c670624.png)
.

**Comment by dpjohnst** [comment]
Hi @famagusta,

Thanks for reporting this issue! We've got a fix for this coming soon.

In the meantime, you can work around this by disabling hardware_acceleration through preferences.

This can be done by opening the preferences file in the Packages/User directory (or creating if it doesn't exist). You can most likely find this in:
~/Library/Application Support/Sublime Merge/Packages/User/Preferences.sublime-settings

Once open, you can disable hardware acceleration. Ensure the file contains the following:
```
{
    "hardware_acceleration": "none",
    // Any other settings you previously had
}
```

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @famagusta,

Just wanted to follow up to check whether you've been able to start Sublime Merge successfully since my last message?

Thanks,
\- Dylan

**Comment by famagusta** [comment]
Yes this worked
