### ISSUE TITLE
Top status git indicator issues

### ISSUE THREAD

**Issue by Resike** [sublimehq/sublime_merge#758]
**Version info**

Operating system and version:
Windows 7 x64 6.1 build 7601
Sublime Merge:
Build 2011
64 bit

**Description**

Git action text indicator will get "stuck" on various interactions.

**Steps to reproduce**

1. Start fetching from a remote
2. Right click on any of the commit to bring up the context menu
3. The top status inditor text will show "Fetcing..." untill the context menu is closed

**Expected behavior**

The action indicator text should also get updated while context menus are shown, or force close the menu when the action is done.

**Comment by BenjaminSchaaf** [comment]
We've got a fix for this in the pipeline.
