### ISSUE TITLE
Click with control key unselects commit in commit list when multiple commit selected

### ISSUE THREAD

**Issue by joona0825** [sublimehq/sublime_merge#766]
**Version info**

 - OS: macOS 10.15.5
 - Build: 2020

**Description**

In macOS, click with control key pressed is used for secondary click. In other panes it looks working without problem in Sublime Merge. But in Commits pane, if I click with control key when multiple commits selected, it unselects selected commit items and then performs secondary click. It is super inconvenient when I need to squash commits. 

**Steps to reproduce**

1. Open repo which has two or more commits
2. In 'Commits' pane, select two or more commits using command key or shift key
3. Click commit while control key is pressed.

**Expected behavior**

Shows menu for selected commits without unselecting others

**Screenshots**

[Screen Recording 2020-06-01 at 12.00.46.mov.zip](https://github.com/sublimehq/sublime_merge/files/4709153/Screen.Recording.2020-06-01.at.12.00.46.mov.zip)

**Comment by jskinner** [comment]
Thanks for the report, this will be fixed in the next build

**Comment by dpjohnst** [comment]
Closing as this has been fixed in the latest build.
