### ISSUE TITLE
Commit list does not show stashed untracked files

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#77]
**Version info**

 - OS: Windows 10
 - Build: [e.g. 1067

**Description**

Git creates a pseudo commit which represents untracked files in a stash if  `git stash --include-untracked` is performed. This commit is not displayed in the commit list of SM, which makes it impossible to find or access untracked files in the stash.

**Steps to reproduce**

1. Open repository ...
2. Modify some files and add some untracked ones to the worktree ...
3. Call stash --include-untracked
4. Try to find untracked files in the stash

**Expected behavior**

The commit list should display a dedicated "commit" which represents the untracked files

**Screenshots**

See how GitExtensions displays untracked files in the commit list

![unbenannt](https://user-images.githubusercontent.com/16542113/46574790-0411e780-c9a1-11e8-94c8-b3bf9a9470d6.PNG)

**Comment by jskinner** [comment]
All parents of a stash are now shown in 1067 btw. Stash commits are folded by default, so you'll need to either click on the commit box in the graph, or click on one of the parents in the commit details to see them.

**Comment by deathaxe** [comment]
Sorry, didn't realize them to be folded.

**Comment by deathaxe** [comment]
But the yellow graph line next to the expanded file seems not to be meant to be there?

![grafik](https://user-images.githubusercontent.com/16542113/46580605-f8193a80-ca1f-11e8-9dad-362c9455fef9.png)
