### ISSUE TITLE
Mergetool conflict resolving messes up the merged file

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#776]
**Version info**

 - OS: Windows 10 x64 2004
 - Build: 2021

**Description**

I am using the key bindings below since day one to quickly pick changes from the left and the right pane in order to conflict resolving with a keyboard.

Since built 2021 those mess up the file in the middle. I can't follow what is tried to pick from the right or left pane as it doesn't match the content marked as conflicting and makes absolutely no sence to me.

It happens while cherry picking a commit which contains conflicting changes.

I can't even undo the changes as it messes the file even more.

**Steps to reproduce**

1. Cherry pick a commit with several merge conflicts
2. Try to solve them one by one.

**Expected behavior**

`use_left_hunk` and `use_right_hunk` should do what their name says, again - apply the hunk.

**Screenshots**

```
    //
    // Merge Tool
    //

    {
        "keys": ["ctrl+alt+right"],
        "command": "use_left_hunk" },
    {
        "keys": ["ctrl+alt+left"],
        "command": "use_right_hunk" },
    {
        "keys": ["ctrl+alt+up"],
        "command": "prev_conflict",
        "context": [{"key": "merge_mode"}]
    },
    {
        "keys": ["ctrl+alt+down"],
        "command": "next_conflict",
        "context": [{"key": "merge_mode"}]
    }
```

![Animation](https://user-images.githubusercontent.com/16542113/83564358-dd60d700-a51c-11ea-8481-311db66506a8.png)

**Comment by deathaxe** [comment]
I'd say there's some offset issue.

![grafik](https://user-images.githubusercontent.com/16542113/83565709-231e9f00-a51f-11ea-8ae7-22466de49654.png)

**Comment by dpjohnst** [comment]
Hi @deathaxe,

Thank you for reporting this issue.
I'll be investigating this further.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @deathaxe,

This will be fixed in the next build of Sublime Merge.

Thanks again for reporting this.

\- Dylan

**Comment by deathaxe** [comment]
Thanks for fixing so quickly.
