### ISSUE TITLE
Mergetool scrolling of left and right pane stops after conflicts

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#777]
**Version info**

 - OS: Windows 10 x64 2004
 - Build: 2021

**Description**

As the title says. Same circumstances as in #776 .

Scrolling of the left and right pane stops after some conflicts.

**Steps to reproduce**

1.  Try scrolling in a file with conflicts.

**Expected behavior**

Left and right pane should scroll as in the builds before.

**Screenshots**

![Animation](https://user-images.githubusercontent.com/16542113/83565093-12215e00-a51e-11ea-9fe4-678b922fa9fb.png)

**Comment by dpjohnst** [comment]
Hi @deathaxe,

Thanks for reporting this!

I'll be investigating this issue too, and will keep you updated.

Thanks\- Dylan

**Comment by dpjohnst** [comment]
Hi @deathaxe,

This will also be fixed in the next build of Sublime Merge.

Thanks,
\- Dylan

**Comment by deathaxe** [comment]
Works perfectly in 2021
