### ISSUE TITLE
"Noise" and non-existing menu option in files review

### ISSUE THREAD

**Issue by alexander-potemkin** [sublimehq/sublime_merge#779]
**Version info**

 - OS: MacOS 10.15.5
 - Build: 2020

**Description**

Parasite noise at the top of the app

**Steps to reproduce**

1. Open repository
2. Stage & commit files OR just browse the repo
3. Watch at the top right corner

**Expected behavior**

No such noise. It's also moving sometimes with my mouse moves.

**Screenshots**

![Screenshot 2020-06-04 at 12 57 08](https://user-images.githubusercontent.com/2323840/83743178-09867000-a663-11ea-9c15-27637365f86f.png)

**Comment by srbs** [comment]
duplicate of #747 

The non-existing menu is the commit message history menu, you likely haven't committed anything yet & thus the menu is empty.

**Comment by alexander-potemkin** [comment]
Right, it is, indeed
