### ISSUE TITLE
Some letters are not rendered when hardware acceleration is enabled

### ISSUE THREAD

**Issue by Devenec** [sublimehq/sublime_merge#782]
**Version info**

 - OS: Windows 10 1909 18363.836
 - Build: 2022
 - AMD Driver: 20.4.2 (19.50.29.27-200515a-355311C-RadeonSoftwareAdrenalin2020)

**Description**

Please see the screenshot:
![bug](https://user-images.githubusercontent.com/2027262/83842529-da780900-a70b-11ea-9464-66ba71e6bd4e.png)

The issue occurs on some tooltips as well. E.g. when the cursor is placed on top of "Stage All" button, the appearing tooltip behaves as in the screenshot.

OpenGL Context Information:

    GL API Version: 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27017
    GLSL Version: 4.60
    Vendor: ATI Technologies Inc.
    Renderer: AMD Radeon RX 5700 XT

**Steps to reproduce**

1. Enable hardware acceleration.
2. Restart the application.
3. Open Preferences.
4. The bug does not always appear: restart the application or toggle hardware acceleration, with restart after changing the setting.

**Expected behavior**

All letters are rendered correctly.

**Comment by dpjohnst** [comment]
Hi @Devenec ,

Thank you for reporting this issue.

We've identified the driver bug involved, and have created a work-around.
This will be released soon - thank you for your patience while this is resolved.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @Devenec,

This has been addressed in development build 2024. Could you confirm whether issue is fixed on your end?

Kind regards,
\- Dylan
