### ISSUE TITLE
Selecting a range of commits should show full diff

### ISSUE THREAD

**Issue by rjchatfield** [sublimehq/sublime_merge#787]
**Problem description**

When I'm working on a branch and have many commits, I would like to see everything that changed. This also applies for checking someone else's branch, or perhaps all commits since the last release.

**Preferred solution**

Selecting a range of commits should present a diff of all the commits.

This may be tricky if the range is not contiguous. 

**Alternatives**

-

**Screenshots**

-

**Comment by stinos** [comment]
I'm not 100% sure what you mean with this. I.e. current functionality allows to show the diff between any 2 selected commits. But you seem to be wanting something else, but it's not unambiguous I think.

>  a diff of all the commits

Can you explain exactly what this should look like? Do you really mean all the diffs between all consecutive commits? And how is that useful? I.e. if commit A adds a character and child commit B removes it, so the net result of the diff between the parent of A and B is empty, do you want to see that, or do you really want to see the character being added and then removed again? And how should all of this be ordered in a way it still makes sense?

**Comment by rjchatfield** [comment]
My apologies. It acts as you describe. When I selected multiple commits I thought the diff was only of the last I tapped, but in fact it was doing a diff of the range. 

Thanks for taking the time to clarify.
