### ISSUE TITLE
Mouse button 4, 5 (Back and Forward) support

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#79]
**Problem description**

By default, clicking mouse 4 and 5 does nothing

**Preferred solution**

Add ability to bind mouse 4, 5 for back and forward

**Alternatives**

Maybe hotkey config like sublime keymap

**Comment by jasonycw** [comment]
Found that I can create custom mouse map
![image](https://user-images.githubusercontent.com/4518597/47625909-1bd52980-db63-11e8-82cc-c134ae64aef8.png)

But still don't know where is the command for `Back` and `Forward`
![image](https://user-images.githubusercontent.com/4518597/47625921-3c9d7f00-db63-11e8-9e45-f85453bc5d24.png)

**Comment by BenjaminSchaaf** [comment]
The commands for the back and forward button are `"navigate_back"` and `"navigate_forward"` respectively.

**Comment by dpjohnst** [comment]
Added in Sublime Merge Build 2025 (stable)
