### ISSUE TITLE
Showing more context of a diff sometimes doesn't work

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#793]
**Version info**

 - OS: macOS 10.14.6
 - Build: 2022 & 2020

**Description**

Inability to drag or double click bottom border of a hunk in a modified file to show additional lines. Occurs randomly and wasn't straightforward to reproduce as I had to match line count, line content, and changed lines to reproduce it.

**Steps to reproduce**

Commands to create an example test repos I used to reproduce:

    mkdir __test; cd __test
    git init

    printf "1\n2\n3\n4\n\n6\n" > file1.txt
    printf "1\n2\n3\n4\n5\n\n7\n" > file2.txt
    git add file1.txt file2.txt
    git commit -m initial-commit
    
    printf "1\n2-\n3\n4\n\n6\n" > file1.txt
    printf "1\n2-\n3\n4\n5\n\n7\n" > file2.txt
    
    smerge .

1. create the repository above
2. drag down to show the last two lines on `file2.txt`
3. notice you cannot do the same on `file1.txt` despite how there are 2 more lines in the file

Notes:
* same issue occurs if the changes are staged or committed

**Expected behavior**

The ability to drag on files with more content at all times.

**Comment by dpjohnst** [comment]
Hi @srbs,

Thank you for reporting this issue - I've reproduced the issue, and will be investigating a fix for this.

Kind regards,
\- Dylan

**Comment by srbs** [comment]
This has been fixed in dev build 2028, thank you @dpjohnst!
