### ISSUE TITLE
Action to `Copy path of repo`

### ISSUE THREAD

**Issue by nikitavoloboev** [sublimehq/sublime_merge#795]
**Problem description**

I am not sure if it's already possible but I want an action that would put the path of the .git repo in my clipboard from the currently open tab.

Sublime Text has a way to get a file path for a currently open file. I want to do the same but for the currently open tab.

**Comment by rchl** [comment]
Copy path:
```js
    {
        "caption": "Copy Repository Path",
        "command": "copy_to_clipboard",
        "args": {"text": "$working_dir"}
    },
```

Open repository folder:

```js
    {
        "caption": "Open Repository in Finder",
        "command": "open_dir",
        "args": {"dir": "$working_dir"}
    },
```

**Comment by dpjohnst** [comment]
Hi all,

This was added as a default in Sublime Merge Build 2057 (Dev) / 2059 (Stable)!

Cheers,
\- Dylan from Sublime HQ
