### ISSUE TITLE
Lag when editing "find" field while a large file is open

### ISSUE THREAD

**Issue by alex-shapiro** [sublimehq/sublime_merge#798]
**Version info**

 - OS: macOS 10.15.5
 - Build: 3211

**Description**

Sublime lags noticeably when editing the "find" field while a large file is open.

**Steps to reproduce**

1. Open a large text file (e.g. 30MB or so)
2. Open the find field (Cmd-F)
3. start typing in the find field

**Expected behavior**

Editing text in the find field should never lag.

**Comment by BenjaminSchaaf** [comment]
> Build: 3211
Is this a Sublime Text issue @alex-shapiro ?

**Comment by alex-shapiro** [comment]
@BenjaminSchaaf Ah, my mistake. Closing and reopening on Sublime Text: https://github.com/sublimehq/sublime_text/issues/3421.
