### ISSUE TITLE
Custom command with commit hash

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#80]
**Problem description**

Creating custom command with selected commit hash
I know there is Default.sublime-commands support, but seems no syntax for adding the selected commit hash?
Custom commands like `git branch -a --contains $SHA` is possible in SourceTree

**Preferred solution**

Add ability to add toolbar button with custom commands with commit hash

**Alternatives**

Just add custom commands in the `...` button

**Comment by jskinner** [comment]
You can use "$commit" with the `git` command in `Default.sublime-commands` and key bindings. Also available are $working_dir, $git_dir, $head, $head_ref .

**Comment by jasonycw** [comment]
@jskinner Thanks, "$commit" works great

```
[
    {
        "caption": "Contains branch",
        "command": "git",
        "args": { "argv": ["branch", "-a", "--contains", "$commit"], }
    },
]
```

 Is there option to show the console after the command is ran?
Right now, I need to click the "console" icon on the top tool bar to check the result
