### ISSUE TITLE
Dark theme: active repo tab not standing out

### ISSUE THREAD

**Issue by trebitzki** [sublimehq/sublime_merge#801]
**Version info**

 - OS: macOS 10.11
 - Build: 2020

**Description**

The active repo tab is not standing out.

**Steps to reproduce**

1. Open some repositories.
2. Click on one of the repo tabs.
3. The active tab looks just like the others.

**Expected behavior**

The active tab should be more easily recognizable.

![Screen Shot 2020-06-14 at 18 07 34](https://user-images.githubusercontent.com/940634/84641486-5be54d80-aefb-11ea-8e43-5d4af013b8bb.png)

I'm using an older Macbook Pro (there's nothing wrong with the display) and I've never had problems with dark pages. By tilting the display toward me, the tab gets a little more contrast, but then the diffs section is almost unreadable, and vice versa. The name of the tab is just a bit lighter, but not really noticable for quick orientation. I suspect that the designer was a bit too enthusiastic with the coolness of the theme.

I'm surprised nobody has mentioned this accessibility issue. The difference of the active tab is really subliminal.

Would you consider highlighting the active tab just a nudge?

**Screenshots**

If applicable, add screenshots to help explain your problem. This section may be omitted/removed.

**Comment by trebitzki** [comment]
Hi @dpjohnst ! What does S:minor mean in terms of when the issue will be adressed? Do you schedule it, or do major bugs get priority? I really find it hard to get around the dark theme as it is...

**Comment by dpjohnst** [comment]
Hi @trebitzki,

The severity label doesn't necessarily reflect the priority of issues. Rest assured we take these kind of issues seriously and will be investigating a solution.

I'll keep you updated as things progress.
Many thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @trebitzki,

We've made some adjustments to address this issue, and this should improve the contrast between the selected tab and other tabs. This will be available in the next build of Sublime Merge.

Thanks for sharing this feedback with us.

Kind regards,
\- Dylan
