### ISSUE TITLE
Show git output on success

### ISSUE THREAD

**Issue by BenjaminSchaaf** [sublimehq/sublime_merge#805]
**Problem description**

Taken from https://forum.sublimetext.com/t/show-git-output-on-success/52084
Show git output on success

**Preferred solution**

Add a setting for always showing the git output popup when the git command succeeds.

**Alternatives**

A description of any alternative solutions or enhancements considered.

**Screenshots**

If applicable, add screenshots to help demonstrate the problem or proposed solution. This section may be omitted/removed.

**Comment by srbs** [comment]
I like this idea, but I had a thought for future API support: it would be nice if certain commands/repository actions could indicate that their output should always be shown on success.
For example, I have a menu item to show what [branches a commit is part](https://forum.sublimetext.com/t/display-branch-name-in-history-view/39134/2) of that I would want to always show but (personally) I really don't need to see the success output for checkout, push, create branch, etc.

**Comment by ricab** [comment]
I see this got implemented :smiley: thanks a lot!
