### ISSUE TITLE
UI stops responding when switching tabs while the command palette is open 

### ISSUE THREAD

**Issue by srbs** [sublimehq/sublime_merge#806]
**Version info**

 - OS: macOS 10.14.6
 - Build: 2022 & 2020

**Description**

When changing tabs while the command palette is open, switch back, & choose a command to execute, the UI starts not responding/lagging only on that tab and the shaded regions around the command palette modal stay shaded despite the palette hiding.

**Steps to reproduce**

1. open multiple repositories in tabs
2. open command palette
3. change tabs (mouse or keyboard)
4. change back to the original tab with opened command palette
5. pick a command to run, I usually use `Checkout Branch`
6. notice how various aspects of the UI break

Behaviors:
* sometimes the UI will fix itself in 5-10 seconds
* sometimes clicking anywhere on the UI (below tab bar) will help move things along (click + 5-10 seconds fixes)
* sometimes changing tabs fixes the UI
* if you typed & switched tabs back and forth, those keystrokes are executed on the original frozen tab, sometimes causing more freezes
* sometimes both clicking & changing tabs fixes the UI
* switching applications doesn't seem to help

**Expected behavior**

No UI freezes/lag.

**Screenshots**

Reproduction, which you can also see near the end that the mouse clicks I performed while the UI was frozen still occurred given that my cursor & focus was in the commit message field.
![ui-freeze-tab-change](https://user-images.githubusercontent.com/297298/85095582-6d5a7e00-b1b7-11ea-8d9c-18a1c42a28e0.gif)

Raw video without GIF compression: [ui-freeze-tab-change.mov.zip](https://github.com/sublimehq/sublime_merge/files/4802381/ui-freeze-tab-change.mov.zip)

**Comment by srbs** [comment]
Note: turning on/off hardware acceleration does not help.

**Comment by dpjohnst** [comment]
Hi @srbs,

Thank you for reporting this issue. I'll be investigating this further and will keep you updated.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @srbs,

The bug has been identified, and will be resolved in the next build of Sublime Merge.
Thanks again for reporting this issue.

Kind regards,
\- Dylan

**Comment by srbs** [comment]
Fixed in dev build 2024!
