### ISSUE TITLE
Option to show full file in the file tab

### ISSUE THREAD

**Issue by lionah** [sublimehq/sublime_merge#808]
**Problem description**

Currently we can scan hunks in the summary tab to get a gist of all the overall changes. If we click the a file tab to work more in depth with the changes in a file, it presents no benefit. If I want to gain full context, I have to tediously drag the hunk separators up and down so that I can see the changes in the full context of the file.

**Preferred solution**

It would be great if while reviewing code to see the file in its entirety with a click from the "..." menu and/or pref option to always show the full file in the file tab. If you wanted to be real fancy, it would already be scrolled to the first change and perhaps add prev/next buttons for egregiously large files.

**Alternatives**

The current work around is to drag and expand the hunk separators until the full file is visible.

**Screenshots**

What we see now:
<img width="1360" alt="Screen Shot 2020-06-19 at 9 52 05 AM" src="https://user-images.githubusercontent.com/862303/85159919-f94dc380-b212-11ea-9e15-67a233ff2b29.png">

What I like to see:
<img width="1469" alt="Screen Shot 2020-06-19 at 9 53 24 AM" src="https://user-images.githubusercontent.com/862303/85159934-fe127780-b212-11ea-868d-db269f3da057.png">

**Comment by srbs** [comment]
related: #383

**Comment by lionah** [comment]
I suppose this can be closed.

**Comment by srbs** [comment]
@lionah I wasn't sure if it should. Your report was more geared to the relatively new file tab feature vs the list-of-all-diffs view. Maybe add a comment in the other with your thoughts. Maybe showing the full file in the file tabs would be a good solution for the other issue.
