### ISSUE TITLE
Highlight base commit

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#81]
**Problem description**

After doing some changes, the branch list is a bit messy to trace back the base commit if it is too behind.

**Preferred solution**

Add highlight to trace back original commit

**Screenshots**

![image](https://user-images.githubusercontent.com/4518597/46590464-0f226000-cae6-11e8-81a4-2f5d760e8b1f.png)

This is what SourceTree offer, using difference color for uncommited change also allow tracing back base commit more easily
![image](https://user-images.githubusercontent.com/4518597/46590511-67f1f880-cae6-11e8-97a5-b210ee24e8c6.png)

**Comment by jskinner** [comment]
Thanks for your report. If I'm interpreting this correctly, the request is to draw the line between "Commit Changes" and the first commit in a different color?

This isn't something I imagine we'll be implementing, so I'm going to close this issue. However, a couple of points:

- The line from Commit Changes is always in the first column, so tracing it down is fairly straight forward
- The current dev builds (https://www.sublimemerge.com/dev) have Commit Folding, which significantly cleans up the commit graph, leading to less need for this in the first place

**Comment by jasonycw** [comment]
@jskinner For example, you cannot tell whether the left column shows the latest commit easily or if there are still commit on the top
![image](https://user-images.githubusercontent.com/4518597/46775395-a3383580-cd39-11e8-90e7-ced77a2c151f.png)

While in SourceTree, you can be sure this commit is the base commit just by glancing at the line as it clearly indicate what is actually committed and what is not.
![image](https://user-images.githubusercontent.com/4518597/46775419-c2cf5e00-cd39-11e8-85ad-536df1247c2e.png)
