### ISSUE TITLE
Support --set-upstream for pushes

### ISSUE THREAD

**Issue by dpjohnst** [sublimehq/sublime_merge#811]
Moved from: https://forum.sublimetext.com/t/feature-request-set-upstream-as-push-option/52236

**Problem description**
Currently setting an upstream and pushing is a two-step process.

**Preferred solution**

Please could `--set-upstream`/`-u` be added as an option for push? It’s very useful when working with multiple remotes to be able to do this alongside push.default = upstream

**Comment by bendilley** [comment]
The changelog for build 2032 says “Improved `--set-upstream` behaviour” but now I can no longer switch my upstream branch once it has been set. I work with multiple remotes and my workflow often requires that I switch my local branch to push to a different remote, setting it as the new upstream.

Perhaps the logic should be to present the `--set-upstream` option unless the proposed remote branch is already the upstream? At the moment it looks like the option is simply removed once it’s set, i.e. it cannot be _changed_.

**Comment by bendilley** [comment]
Sorry, I've reported this properly now: #897
