### ISSUE TITLE
Tabs Glitch upon showing hidden Application Menu

### ISSUE THREAD

**Issue by cardin** [sublimehq/sublime_merge#812]
**Version info**

 - OS: Windows 10x64 1909
 - Build: 2020 (Paid edition)

**Description**

I've set the Application Menu to be hidden. But when I press Alt to reveal the Application Menu, the tabs' display glitched.

**Steps to reproduce**

1. In Sublime Merge, File Menu > Preferences > Advanced
2. Set Application Menu Visibilty to "Hidden unless Alt is pressed"
3. Press Close button
4. Ensure you have at least 1 repository tab
5. Observe the application menu is hidden, as expected.
6. Press Alt to show the application menu
7. Tabs' display glitched (see screenshot below)

**Expected behavior**
I expect no glitching.

**Screenshots**
![image](https://user-images.githubusercontent.com/553816/85832469-ba93ac80-b7c2-11ea-8936-93acc7c6f54d.png)

**Comment by srbs** [comment]
see also #768

**Comment by dpjohnst** [comment]
Hi @cardin,

Thanks for taking the time to report this.

To investigate this further, could you please share the following:

* OpenGL context information: open Sublime Merge, open the console with ctrl + `, and copy the OpenGL Context Information

The driver version you are using for your GPU: open Control Panel > Hardware and Sound > Device Manager > Display Adapters > Right Click the display adapter > Driver.
Thanks,
- Dylan

**Comment by cardin** [comment]
The OpenGL Context Information is:
```
OpenGL Context Information:
  GL API Version: 4.6.0 - Build 27.20.100.8336
  GLSL Version: 4.60 - Build 27.20.100.8336
  Vendor: Intel
  Renderer: Intel(R) HD Graphics 630
```

The GPU driver is:
![image](https://user-images.githubusercontent.com/553816/86007428-f42a1900-ba49-11ea-9c08-3af1447cc831.png)

**Comment by dpjohnst** [comment]
Hi @cardin,

Thanks for the additional information.

This seems to be the same issue as:
https://github.com/sublimehq/sublime_merge/issues/768

Likely it's a bug with the Intel HD Graphics 630 driver - we'll be investigating a work-around for the meantime.

I'm going to close this issue, and move over to the one linked above. 
Please go ahead and subscribe / comment on the above issue to ensure you receive further updates as the investigation progresses.

Thanks,
\- Dylan
