### ISSUE TITLE
Change theme according to OS theme setting

### ISSUE THREAD

**Issue by nikitavoloboev** [sublimehq/sublime_merge#815]
**Problem description**

Currently you have to manually switch between dark/light themes. It would be great if you could instead have a new option `system theme` as most apps on macOS already provide that will change the theme automatically for you.
**Preferred solution**

New option in system prefs that says `System`.

Not sure if this can apply to windows/linux too. 

**Alternatives**

Above is preferred solution. Perhaps you can hack another solution already? But an official setting for this would be great.

**Comment by srbs** [comment]
duplicates: #490

as for whether or not this can apply to windows, see https://forum.sublimetext.com/t/support-dark-theme-on-windows/48255

**Comment by nikitavoloboev** [comment]
Even a simple hotkey to change themes would be good to have. Although ideally it should indeed work via `System` theme setting.

**Comment by nikitavoloboev** [comment]
A way to do it via applescript or something would work well too. I have a macro that changes a theme for me from light to dark and I'd love to run an update to the theme in sublime merge as part of the script. 

But it seems there is no commands or anything you can send to change how sublime merge looks without manually going to preferences and changing the the theme there? 😞

**Comment by srbs** [comment]
@nikitavoloboev, you could modify the preference file within the applescript. Sublime Merge will auto-reload the preferences when the file changes.

**Comment by nikitavoloboev** [comment]
> you could modify the preference file within the applescript

How can I do it?

**Comment by dpjohnst** [comment]
Closing, as automatic theming was added in Sublime Merge build 2047
