### ISSUE TITLE
Application Menu can show up in the Preferences window

### ISSUE THREAD

**Issue by balcsida** [sublimehq/sublime_merge#819]
**Version info**

 - OS: Windows 10 Version 2004
 - Build: 2020

**Description**

If Application Menu Visibility is set to "Hidden unless Alt is pressed", the menu can show up if `Alt` key is pressed the setting is switched to "Always visible"

**Steps to reproduce**

1. Open _Preferences_
2. Go to _Advanced_ tab
3. Select "Hidden unless Alt is pressed"
4. Press `Alt` key or select "Always visible"

Result: Application Menu is displayed on the top of Preferences window

**Expected behavior**

Application menu doesn't show up

**Screenshots**

![sm_preferences_menu_bug](https://user-images.githubusercontent.com/1768446/87052949-ab205480-c201-11ea-8e7c-e1712d442530.gif)

**Comment by dpjohnst** [comment]
Hi @balcsida,

Thank you for reporting this issue - I've identified the issue, and a fix will be coming in the next build of Sublime Merge.

Thanks,
\- Dylan
