### ISSUE TITLE
Collapse All function

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#82]
**Problem description**

On the commit list, after using arrow key to expand the file list for multiple commits, there is no 1 click way to collapse all?

**Preferred solution**

Tapping left arrow twice to collapse all / once on not expanded commit

**Alternatives**

Or a hot key for that?

**Screenshots**

![image](https://user-images.githubusercontent.com/4518597/46593698-ac8a8d80-cb00-11e8-9aa4-c0e432e3b95a.png)

**Comment by dpjohnst** [comment]
Closing, as this is now redundant.
