### ISSUE TITLE
Signature: Invalid: gpg: can't open '<Path to %temp%>\subXXXX.tmp': System error w/o errno

### ISSUE THREAD

**Issue by Whissi** [sublimehq/sublime_merge#821]
**Version info**

 - OS: Microsoft Windows 10 Build 2004
 - Build: 2020

**Description**

All signatures are shown with status "Invalid":

![sublime-merge-gpg-error](https://user-images.githubusercontent.com/729436/87476400-9d663700-c626-11ea-87fd-c52f431e1d43.png)

**Steps to reproduce**

1. Open repository with signed commits
2. View commit

**Expected behavior**

Valid signature status should be shown.

At the moment I don't know if Sublime Merge uses its own GnuPG or is using system's GnuPG because I have a **working** GPG4Win installation on this system:
```
D:\>gpg --version
gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: D:/Users/<Username>/AppData/Roaming/gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by dpjohnst** [comment]
Hi @Whissi,

Thanks for reporting this. This has been fixed in the latest development builds, and will be fixed in the next stable build. 

Thanks,
\- Dylan

**Comment by Whissi** [comment]
Can I get this development build somewhere? At least it is not fixed in build 2022.

**Comment by dpjohnst** [comment]
My apologies @Whissi,

The fix has not been released as of yet - this will actually be fixed in the upcoming development build.

Kind regards,
\- Dylan

**Comment by srbs** [comment]
This should have been fixed in dev build 2024.

**Comment by dpjohnst** [comment]
Hi @Whissi,

When you have a chance, could you confirm whether this bug has been fixed on your end in development build 2024?

Thanks,
\- Dylan

**Comment by Whissi** [comment]
Issue is resolved in build 2024, thank you!
