### ISSUE TITLE
Certain commits cause all diff views to only show loading animation

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#823]
**Version info**

 - OS: Windows 10 x64 2004
 - Build: 2022
 - git version 2.27.0.windows.1

**Description**

As soon as I click onto commit https://github.com/sublimehq/Packages/commit/5c0af64e3911bcf0a87832c70ac621cf5347fc40 in the commit list the file loading animation shows for syntax_test file forever.

From that point on all diff views and the merge tool only show that loader.

The same issue rises if I try to merge the main branch into another one. If a merge conflict is to be resolved SM shows the loader animation only.

If SM is closed the application remains running in the background. Looks like an infinit loop still running.

**Steps to reproduce**

1. Open Sublime Merge (in Safe Mode)
2. Clone https://github.com/sublimehq/Packages
3. Click on the `[Scala] Fix infinit loop` commit

**Expected behavior**

A description of what you expected to happen.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/87578651-04dac000-c6d5-11ea-8afc-61a21092db74.png)

After:

![grafik](https://user-images.githubusercontent.com/16542113/87579036-9cd8a980-c6d5-11ea-9073-d0ad30d2450d.png)

**Comment by dpjohnst** [comment]
Hi @deathaxe,

Thanks for reporting this!

The commit that fixes the bug is also causing the bug in Sublime Merge, as that version of Sublime Merge hasn't integrated in the changes from the Packages repo yet.

This will be fixed in the next development build.

Kind regards,
\- Dylan

**Comment by deathaxe** [comment]
This came to my mind as well last night when thinking about it once more. Thanks, anyway.

Just copied the package from ST to SM in the meanwhile.

**Comment by deathaxe** [comment]
Fixed in SM 2028.
