### ISSUE TITLE
GPG Invalid : No such file or directory

### ISSUE THREAD

**Issue by djtb2924** [sublimehq/sublime_merge#825]
**Version info**

 - OS: Windows 10
 - Build: 2020

**Description**

gpg is not found (I'm using GnuPG for windows, and git from system)

**Steps to reproduce**

I don't really know, just sign a commit I think ?

**Expected behavior**

Tell if Valid or not, but not "no such file or directory)

**Screenshots**

![image](https://user-images.githubusercontent.com/26027040/87727343-1bf6dc00-c7c1-11ea-8d64-f4010363c0da.png)

**Comment by srbs** [comment]
possible duplicate of #821 

also, [dev build 2024](https://www.sublimemerge.com/dev) might have fixed this with this change:
> Commit Signatures: Added GPG4Win support

**Comment by djtb2924** [comment]
> also, dev build 2024 might have fixed this with this change:

Yup, thanks a lot ! I was searching for the build !
