### ISSUE TITLE
"clean" filters not taking effect until changes are staged

### ISSUE THREAD

**Issue by lkrms** [sublimehq/sublime_merge#826]
**Version info**

 - OS: Arch Linux
 - Build: 2020

**Description**

As reported on the Sublime HQ forums [here](https://forum.sublimetext.com/t/where-is-the-smudge-clean-filter-support/52630), Sublime Merge 2's support for Git's `clean` and `smudge` appears not to be working when files have unstaged changes.

For example, in a private repo I use to sync app settings, I have a filter configured to `clean` Typora's hex-encoded JSON settings file into formatted JSON using `xxd` and `jq`, and vice-versa for `smudge`, but the diff in SM2's unchanged files view looks like this:

![Screen Shot 2020-07-13 at 11 46 02 am](https://user-images.githubusercontent.com/2563783/87727001-7749be00-c803-11ea-801d-64bf9c9e8a1a.png)

Meanwhile, the same unstaged changes appear correctly in git-cola:

![Screen Shot 2020-07-13 at 12 01 50 pm](https://user-images.githubusercontent.com/2563783/87727061-95afb980-c803-11ea-9d51-abff37bbbd7a.png)

**After** staging (which I can do successfully in SM2 -- IIRC it didn't work in SM1, so that's been improved :+1:), the diff appears as expected:

![Screen Shot 2020-07-13 at 12 06 19 pm](https://user-images.githubusercontent.com/2563783/87727275-fd660480-c803-11ea-91b7-15efbe4fb5fd.png)

Here's my .gitconfig:

```
[core]
	excludesFile = ~/.gitignore
[include]
	path = /opt/lk-settings/.gitconfig
[user]
	name = Luke Arms
[push]
	default = current
	followTags = true
[merge]
	ff = only
	tool = meld
[pull]
	ff = only
[cola]
	spellcheck = false
	tabwidth = 4
	safemode = true
[gui]
	editor = code
[diff]
	tool = meld
```

And here's the filter in question (the same happens for other filters, including more straightforward ones that simply remove confidential lines). The following appears in `/opt/lk-settings/.gitconfig` on my system, but the results are the same with `include.path` removed and the file included directly in my main `~/.gitconfig`. Ditto for indenting the lines under `[filter...]`.

```
[filter "typora"]
clean = xxd -r -p | echo "$(cat)" | tac | sed -E '2s/,$//' | tac | jq -S --indent 4 'del(.\"sidebar-width\", .initialize_ver, .lastClosedBounds, .lastSavePath, .pinFolder, .sidebar_tab, .uuid)'
smudge = sh -c 'echo \"$(cat)\" | tac | sed -E \"2s/,\\$//\" | tac | jq -c | xxd -p | tr -d \"\\\\n\"'
```

Finally, the .gitattributes line at the top of the relevant repo:

```
typora/*.data filter=typora
```

**Steps to reproduce**

1. Use `.gitconfig` and `.gitattributes` to assign `clean` and `smudge` filters to particular files in a repo
2. Check the filter behaves as expected when using `git diff` on the commandline to inspect unstaged changes
3. Open SM2 to inspect the same changes

**Expected behavior**

A properly filtered view of unstaged changes should appear.

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge build 2032 (stable)
