### ISSUE TITLE
Is this diff correct?

### ISSUE THREAD

**Issue by greggman** [sublimehq/sublime_merge#829]
**Version info**

 - OS: MacOS 10.15.6
 - Build: 2020

**Description**

The highlighting of this diff appears to be off?

<img width="1434" alt="Screen Shot 2020-07-22 at 13 47 24" src="https://user-images.githubusercontent.com/234804/88135560-49f57980-cc22-11ea-8c42-731a3835a560.png">

**Expected behavior**

It's not clear to my why `webglUniformLocation` is not highlighted in the diff on line 1131

**Comment by TheSecEng** [comment]
@greggman the diff is in fact correct. The red highlight line shows that the deleted items included a new line, and then the insertion included a new line. `webglUniformLocation` isn’t highlight because technically, it wasn’t edited, only the items around it such as the new line, etc was modified.
