### ISSUE TITLE
Stage several files at once

### ISSUE THREAD

**Issue by jeffrson** [sublimehq/sublime_merge#833]
**Problem description**

Currently it's possible to stage files only single files or all files (modified or untracked).

**Preferred solution**

In the files list it could be possible to select more than one file (a range by shift, or several distinct files by ctrl).

Also there could be a way to add complete (new or changed) folders.

**Comment by srbs** [comment]
duplicates: #381 
related: #418, #143, #461
see also: #382, #689

**Comment by jeffrson** [comment]
Sorry, must have overlooked this. Came via this https://github.com/sublimehq/sublime_merge/issues/330 which is different though.

**Comment by dpjohnst** [comment]
Hi @jeffrson,

Thanks for sharing this feedback - as @srbs has pointed out there is an existing feature request for this, so I'm going to go ahead and close this issue.

Please don't hesitate to subscribe to the issue linked above, so you can continue to receive issue updates.

Thanks,
\- Dylan
