### ISSUE TITLE
Image diffs not working with LFS tracked objects

### ISSUE THREAD

**Issue by OnlyFreeUsername** [sublimehq/sublime_merge#834]
---
name: Bug report
about: Create a report to help us fix a problem with Sublime Merge

---

**Version info**

 - OS: Windows 10 Version 1909 (OS Build 18363.959)
 - Build: 2025

**Description**

When updating an image file that is tracked by git lfs the image comparison shows 0x0 size images (probably the pointer files interpreted as images).

The bug appears every time an image file is modified if it is tracked with git lfs.

**Steps to reproduce**

1. Create or open any repository
2. Execute `git lfs track logo.png`
3. Stage `.gitattributes` file
4. Add image file as logo.png
5. Stage logo.png

**Expected behavior**

I excpect Sublime Merge to show the added image even if it is tracked by git lfs (Sublime Merge may show an [LFS] tag).
Alternatively do not show the image, but the text content of the lfs pointer file just as before.

**Screenshots**

After adding an image file (Step 4) without staging it (before git lfs staging hook):
![image](https://user-images.githubusercontent.com/18463421/88281680-665be980-cce8-11ea-8c85-18e6c2cf39a7.png)

After staging the image (Step 5) (after conversion to lfs pointer):
![image](https://user-images.githubusercontent.com/18463421/88281746-7bd11380-cce8-11ea-95ee-62295c60aeac.png)

**Comment by dpjohnst** [comment]
Hi @OnlyFreeUsername,

Thanks for reporting this issue - I'll be investigating this further.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @OnlyFreeUsername,

This will be fixed in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge Build 2032 (stable) 🎉

**Comment by OnlyFreeUsername** [comment]
It's working like a charm, thank you!
