### ISSUE TITLE
Large RAM consumption when idling

### ISSUE THREAD

**Issue by ggirelli** [sublimehq/sublime_merge#836]
**Version info**

 - OS: Ubuntu 20.04
 - Build: 2025

**Description**

SublimeMerge starts consuming vast amounts of RAM, and it ends up making my machine swap quite brutally. Yesterday it happened while I was checking some file diffs, especially "large" images (~5 MB), so I initially thought it could be related to the new image diff feature. But today the same happened while idling (I was AFK for 20 min and when I came back the computer was swapping again, always due to SublimeMerge).

**Steps to reproduce**

1. Open repository
2. Go drink a coffee
3. Come back to a swapping computer

**Expected behavior**

Not to require such large amounts of RAM :)

**Comment by dpjohnst** [comment]
Hi @ggirelli,

Thanks for reporting this issue - I'll be investigating this further. For the moment, could I ask what tool you're using to measure the memory usage?

Additionally, could I ask if you're experiencing this on a public repository?

Thanks,
\- Dylan

**Comment by ggirelli** [comment]
Hi @dpjohnst,

thanks for the quick reply! I am checking the RAM consumption very coarsely using `htop`. All other processes had `%Mem` typically below 7% while SublimeMerge suddenly spiked up. Sadly I am experiencing this on a private repository that I cannot share... if this happens with a public one I'll gladly direct you to it!

Best,
\- Gabriele

**Comment by dpjohnst** [comment]
Hi @ggirelli,

I've found the source of the issue - this will be fixed in the next build.

Thanks again for reporting this.

Kind regards,
\- Dylan

**Comment by ggirelli** [comment]
Awesome! Thank you so much for looking into this!

**Comment by dpjohnst** [comment]
Hi @ggirelli (and all),

A quick update: Sublime Merge 2026 has been released on the development channel, fixing this issue.

Thanks,
\- Dylan

**Comment by ggirelli** [comment]
Running to get it now, thanks again!
