### ISSUE TITLE
Sublime Merge won't open at all

### ISSUE THREAD

**Issue by tywunon** [sublimehq/sublime_merge#838]
**Version info**

 - OS: Windows 10
 - Build: 2025 stable / 2026 Dev

**Description**

I was using the dev channel and 2024 today I got an Update to 2026 since then Sublime Merge does not open anymore. It just stays in the taskbar as a empty preview and no window is opening. I switched to stable 2025. Same here.

**Steps to reproduce**

1. Start Sublime Merge

**Expected behavior**

Sublime Merge to open.

**Comment by dpjohnst** [comment]
Hi @tywunon,

Sorry to hear you're having issues launching Sublime Merge. Rest assured I will be investigating this until it's resolved.

Could you try the following:
* Open your terminal / console and navigate to the folder where your repository is.
* Run `smerge .`

Let me know if Sublime Merge opens correctly. If so, try closing it, and re-opening again as you normally would.

Thanks,
\- Dylan

**Comment by tywunon** [comment]
Hi @dpjohnst 
It's Windows, so smerge on it's own did not work, but opening the repro on the commandline fixed that. 
All my Tabs are closed now, but that's an sacrifice I am willing to take.

Thanks
