### ISSUE TITLE
Command line launcher broken in 2025

### ISSUE THREAD

**Issue by ulope** [sublimehq/sublime_merge#839]
**Version info**

 - OS: macOS 10.15.5
 - Build: 2025

**Description**

The `smerge` cli launcher doesn't behave correctly anymore in build 2025.

**Steps to reproduce**

1. Run `/Applications/Sublime Merge.app/Contents/SharedSupport/bin/smerge .` inside a git repository

**Expected behavior**

Sublime Merge to open the repository in the given path.

**What happens instead**

Sublime Merge opens as if launched from the app icon (i.e. no repo opened).
Additionally the cli launcher is hanging. Pressing Cmd-Q quits and immediately reopens SM until the cli launcher is killed with Ctrl-C.

**Comment by dpjohnst** [comment]
Hi @ulope,

Thanks for reporting this - we'll be investigating this further.

Kind regards,
\- Dylan

**Comment by BenjaminSchaaf** [comment]
I can't reproduce this behaviour on macOS 10.15.5. Can you check your "Security & Privacy > Privacy" settings to see if Sublime Merge has been restricted off anything? Is Sublime Merge running when you're trying this? If so can you check whether there are any related files in `/tmp`?

**Comment by ulope** [comment]
Apparently it was a problem on my machine. Something seemed to have been mucked up with IPC.
A reboot fixed it.

Sorry for the noise.
