### ISSUE TITLE
Tab Support (Multiple Repositories per Window)

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#84]
**Problem description**

Currently, the title of Sublime Merge is begin with the full folder path just like Sublime Text, but there is no tab support, so opening multiple repositories means multiple Merge windows.
If the repo is put deep inside multiple folders, there is no way to identify which windows for which repo

**Preferred solution**

Custom title config that can be edit by user, full path/folder name/repo name/no name, etc

**Alternatives**

1) Display the repo name / folder name only
2) Tab functionality like Sublime text and only display "SublimeMerge" in task bar

**Screenshots**

![image](https://user-images.githubusercontent.com/4518597/46594464-d0040700-cb05-11e8-9bfb-8f4ab0bb8fe6.png)

**Comment by nrusch** [comment]
I'd like to add my vote to the request for tabbed UI support.

**Comment by renattou** [comment]
I'm really looking forward to tab support.

**Comment by chere005** [comment]
One other note on tabs, it would be great if we could save groups of tabs, similar to projects in sublime text.

**Comment by chere005** [comment]
Sorry but one other detail on my previous suggestion. It would be really cool is if my project in Sublime Text were directly linked to projects in Sublime Merge. Sublime Merge projects could maybe simply point to the existing .sublime-project file as a simple way to link the two together.

**Comment by whins** [comment]
It will be very useful. (like in SourceTree)

**Comment by renattou** [comment]
This was added on build [1107](https://www.sublimemerge.com/blog/sublime-merge-build-1107), but it appears that it's only for Mac.
> Mac: Add full support for macOS native tabs

**Comment by wbond** [comment]
@renattou Yes, to be clear, macOS provides a "tab" interface for multiple windows. We added some supporting menu entries and a setting to disable this functionality, but the tabs themselves are all implemented/provided by the OS. I do not believe Windows nor GTK provide such a feature.

I do believe that Sublime Merge tabs are still on the roadmap, and likely when those are implemented they will replace the macOS native tabs.

**Comment by dpjohnst** [comment]
We’re very excited to announce that the latest development build of Sublime Merge has been released. This release is packed with upgrades, including tab support.

Please note the nature of development builds (these upgrades will move to the stable channel soon), and feel free to post any bug reports or feature requests to this issue tracker.

Thanks,
\- Dylan

**Comment by jasonycw** [comment]
@dpjohnst thanks very much!
Just had a look at the latest dev build and it looks pretty neat. 
![image](https://user-images.githubusercontent.com/4518597/75964258-dcaaab80-5f01-11ea-9201-6f19d4a22ef5.png)

It will be nice if there is a preference setting to not show the repo path in the title and just show the `Sublime Merge` instead

**Comment by ahmetcetin** [comment]
looks really good!

**Comment by dpjohnst** [comment]
Hi all,

A new stable build of Sublime Merge has been released.
Tabs have been added, along with a huge amount of upgrades.

Thanks to everyone for the feedback you've given throughout the development process!

With that said, I'll close this issue :)
