### ISSUE TITLE
Sublime Merge crashes when closing

### ISSUE THREAD

**Issue by christianrickert** [sublimehq/sublime_merge#842]
**Version info**

 - OS: Microsoft Windows [Version 10.0.18363.959]
 - Build: Stable Channel, Build 2027

**Description**

Sublime Merge crashes when closing the application window.
This happened after an update to the latest version,
from the previous version, via auto-updater.

The Windows Event Viewer lists this event reproducibly:
```
Faulting application name: sublime_merge.exe, version: 1.1.1.6, time stamp: 0x5f1f66b6
Faulting module name: KERNELBASE.dll, version: 10.0.18362.959, time stamp: 0x7b90c1b5
Exception code: 0x80000003
Fault offset: 0x00000000000c0aa2
Faulting process id: 0x2adc
Faulting application start time: 0x01d66490f08b717c
Faulting application path: C:\Program Files\Sublime Merge\sublime_merge.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 717831fb-8d98-43f9-bf75-6e06da66fbf9
Faulting package full name: 
Faulting package-relative application ID: 
```

**Steps to reproduce**

1. Open Sublime Merge
2. Close Sublime Merge
3. Sublime Merge has crashed.

**Expected behavior**

No crash.

**Screenshots**

![SublimeMergeCrash](https://user-images.githubusercontent.com/19319377/88618004-3a789500-d055-11ea-991e-1da085a6271e.PNG)

**Comment by dpjohnst** [comment]
Hi @christianrickert,

Thanks for reporting this. We have an incoming fix for this - stay tuned.

Kind regards,
\- Dylan

**Comment by stinos** [comment]
Note the same crash occures when opening SM from within ST using `Open Git Respoitory...` when SM is open already, I assume because it launches a separate SM instance which tels the other instance to open the repository, then quits.

**Comment by christianrickert** [comment]
> 
> 
> Hi @christianrickert,
> 
> Thanks for reporting this. We have an incoming fix for this - stay tuned.
> 
> Kind regards,
> - Dylan

Great news, thanks!

**Comment by jeffrson** [comment]
FYI - not fixed in 2028

**Comment by christianrickert** [comment]
it's an inconvenience, not the end of 2020

**Comment by dpjohnst** [comment]
Hi @jeffrson,

Thanks for the heads up - we'll be investigating this further.

Kind regards,
\- Dylan

**Comment by jeffrson** [comment]
Maybe this message from WinDBG helps:

```
An interface [000001D7140B7778] was created but not released. Use 'dps 000001D7140B7718' to view its allocation stack.
Object type: ID2D1Factory
	Factory type: D2D1_FACTORY_TYPE_SINGLE_THREADED
	Outstanding reference count: 1

D2D DEBUG ERROR - Memory leaks detected.
```

**Comment by christianrickert** [comment]
Fixed for me:

    OS: Microsoft Windows [Version 10.0.18363.959]
    Build: Stable Channel, Build 2032

Thank you very much! 💯

**Comment by jeffrson** [comment]
Yeah, looks good!

**Comment by dpjohnst** [comment]
I'll go ahead and close this issue - thanks for all the information everyone.
