### ISSUE TITLE
Wrong branch gets deleted if you open the context menu before deletion of another branch finishes

### ISSUE THREAD

**Issue by sijmn** [sublimehq/sublime_merge#844]
**Version info**

 - OS: Arch Linux
 - Build: 2025

**Description**

When deleting two branches, and you open the context menu of a second branch before deletion of the first branch finishes, it will delete a third branch.

**Steps to reproduce**

Say, you have three remote branches: `foo`, `bar` and `develop`.

1. Delete branch `origin/foo`
2. Before deleting is finished (and `origin/foo` still shows), right click branch `origin/bar`
3. Meanwhile, the deletion completes and `origin/develop` is now under the cursor (but you still think the context menu is open for `origin/bar`)
4. Select delete in the context menu - the alert prompts you if you want to delete `origin/develop` (which you might miss)
5. Hit delete, and `origin/develop` gets deleted (or not, because you should really protect your develop branch)

**Expected behavior**

Either:
- `origin/bar` is deleted
- The context menu is closed when the deletion finished (bit flimsy, but better)
- Not being able to right click before deletion finishes (less flimsy, but could still be annoying)

**Screenshots**

Note that I hit return on the dialog box of the first deletion. Also note that the context menu says `origin/foo`, but the alert says `origin/main`.

<img src="https://i.sijman.nl/5ZvW" width="500">

**Comment by dpjohnst** [comment]
This has been fixed as of build 2032
