### ISSUE TITLE
Poor performance since build 2025

### ISSUE THREAD

**Issue by semecan** [sublimehq/sublime_merge#847]
**Version info**

 - OS: Windows 7
 - Build: 2025 and 2027

**Description**

Since build 2025 sublime merge seems to hang at all sorts of occasions, most noticable when switching repository tabs or expanding a merge commit. I have rolled back to build 2020 and the issue is completely gone, so it may be connected to the new image diff feature.

**Steps to reproduce**

1. Open repository
2. Expand a merge commit or switch to a different repository tab

**Expected behavior**

The commits of the merge should be fluently displayed, but the expansion hangs and is very stuttery.
Changing tabs should be (almost) instant but instead hangs for at least 2-3 seconds.

**Comment by deathaxe** [comment]
Can't reproduce that on Windows 7 x64 with latest available patches nor on Windows 10.

**Comment by semecan** [comment]
Is there something I can do to provide more information?
I downloaded the portable Windows version of build 2027 again to have a completely clean installation.
I sadly still have the issue mentioned above. I have tested with this repo: [https://github.com/semecan/Farmer](https://github.com/semecan/Farmer), maybe it has to do something with the files of the repo.

**Comment by dpjohnst** [comment]
Hi @semecan,

Thank you for reporting this issue - I have not had any luck reproducing the issue with the repo mentioned above.
There's definitely more we can do to investigate this. When you have a chance, could you share the following:

* Whether you have OpenGL rendering enabled under `Preferences > Advanced`
* If you are running OpenGL, could you share the OpenGL context information, found at the top of Sublime Merge's console (`` ctrl + ` ``)
* What system specs you have, specifically Windows version information and processor information
    * You can get the specific windows version by opening the start menu, typing `winver` and pressing `enter`

Kind regards,
\- Dylan

**Comment by semecan** [comment]
I have OpenGL rendering disabled. I have tried enabling OpenGL to check if that fixes the issue.
Some of the issues improved: I no longer had delay when switching tabs or clicking a menu in the top bar. The displaying of the eye icon when hovering over a branch and expanding a merge request still was delayed and stuttery though.
After about 20 seconds got an error, but could keep using the application:
> Failed to initialize OpenGL rendering:
> GL_INVALID_OPERATION

Here is the OpenGL context information: 

> OpenGL Context Information:
>   GL API Version: 4.5.13399 Compatibility Profile Context 15.200.1062.1004
>   GLSL Version: 4.40
>   Vendor: ATI Technologies Inc.
>   Renderer: AMD Radeon HD 5800 Series

My Windows version is: Windows 7 Professional Version 6.1 (Build 7601: Service Pack 1) which should be the very latest version.

**Comment by dpjohnst** [comment]
Hi all,

For those still affected by the issue, we have a placeholder fix available in development build 2028.

* Add the following line to your settings file: `"win32_vsync_enabled": false,`
* You can access the settings file via `Preferences > Edit Settings...`
* Once added, restart Sublime Merge.

A full fix will be available in upcoming stable builds.

Kind regards,
\- Dylan

**Comment by semecan** [comment]
That setting reminded me of the fact that disabling Windows Aero also disables vsync.
I had Aero turned off and turning it back on fixed the issue for me without using the developer build.

**Comment by deathaxe** [comment]
Found one situation which causes SM 2028 to suffer from poor performance today, which I can't rembember to have seen before.

- a commit with 10 modified files
- 3407 lines of code changed with (1 to 2 changes per hunk). => 1700 ... 3000 hunks to display

Any interaction with SM takes about 1...3 seconds for the GUI to respond.

Rendering of context menus is delayed. Show blank rectangles for 1..3secs before items are rendered.
Scrolling is heavily delayed and slow.
Hover effects are heavily delayed sometimes, but not always.
Even saw tooltips remaining visible forever.

As the repo contains internal data I can't share it, unfortunatelly.

**Comment by BenjaminSchaaf** [comment]
@deathaxe If you're seeing this outside of Windows 7 with a non-Aero theme then that's a separate issue.

**Comment by semecan** [comment]
With the latest stable build 2030 the issue is completely gone for me.
