### ISSUE TITLE
Horizontal scroll bar is overlapping the code

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#85]
**Version info**

 - OS: Windows 10
 - Build: Dev Build 1067

**Description**

Horizontal scroll bar is overlapping the code

**Steps to reproduce**

1. Open repository ...
2. Click on commit
3. Resize windows so the diff section has horizontal scroll bar

**Expected behavior**

The scroll bar is not overlapping the code / keep persistence under the code block

**Screenshots**
![image](https://user-images.githubusercontent.com/4518597/46598673-83c1c280-cb17-11e8-94e1-1ae8482f3ce4.png)

**Comment by jasonycw** [comment]
Maybe related with #12

**Comment by wbond** [comment]
Does the scroll bar disappear when you stop scrolling, or is it always visible?

**Comment by jasonycw** [comment]
On 1069 build, the horizontal scroll bar only show on hover
![image](https://user-images.githubusercontent.com/4518597/46774661-32dbe500-cd36-11e8-8b75-aca5331f9a52.png)

**Comment by keith-hall** [comment]
One thing I don't like is that the horizontal scrollbar only appears when moving the mouse over it, it isn't always clear that there is extra content out of view. I would really like it to honor the system setting or be configurable in SM to always be visible.
(the system setting looks like this in Windows 10:)
![image](https://user-images.githubusercontent.com/11882719/52482750-bd383680-2bba-11e9-9930-0f019cd14cd4.png)

I guess a possible alternative would be for it to appear when the mouse moves anywhere in the scrollable area, but it's still not ideal IMO.

![ezgif-3-7ae36218a383](https://user-images.githubusercontent.com/11882719/52483185-f624db00-2bbb-11e9-9376-538cc092a875.gif)

**Comment by wbond** [comment]
Just a comment for future reference, the scroll bar setting "Automatically hide scroll bars in Windows" is written to `HKEY_CURRENT_USER\Control Panel\Accessibility\DynamicScrollbars`. Also, not many programs do anything with that. It seems to affect mostly the start menu and UWP apps like Settings? It doesn't have any effect on Edge or Notepad or Explorer.
