### ISSUE TITLE
Build 2025: merge tool algorithm not ideal for my specific use case

### ISSUE THREAD

**Issue by jjackson-pixel** [sublimehq/sublime_merge#854]
**Version info**

 - OS: macOS 10.14.5
 - Build: 2027

**Description**

Merge Conflict tool selection is smaller than it used to be, and for my particular use case, kills the usefulness that Sublimemerge used to offer. This change, presumably, was made in build 2025 and was working as intended in build 2020.

While this does increase the effort for myself, I'm not positive what use cases this algorithm change affected. The net gain may still be positive. If we can have both, that would be awesome. If this change could be made into a preference, allowing the user to toggle which method they used, that might be the best solution.

**Steps to reproduce**

1. Consider the following file snippet. This is an XML tree that tracks migrations.

```xml
  <migration id="20200805T0800_add_widget_A">
    <description>Adding widget A</description>
    <location>20200805T0800_add_widget_A</location>
    <parent>_root</parent>
  </migration>
```

2. Two changes are made in separate branches:

```xml
  <migration id="20200805T0800_add_widget_A">
    <description>Adding widget A</description>
    <location>20200805T0800_add_widget_A</location>
    <parent>_root</parent>
  </migration>
  <migration id="20200805T0900_add_widget_B">
    <description>Adding widget B</description>
    <location>20200805T0900_add_widget_B</location>
    <parent>20200805T0800_add_widget_A</parent>
  </migration>
```

```xml
  <migration id="20200805T0800_add_widget_A">
    <description>Adding widget A</description>
    <location>20200805T0800_add_widget_A</location>
    <parent>_root</parent>
  </migration>
  <migration id="20200805T1000_add_widget_C">
    <description>Adding widget C</description>
    <location>20200805T1000_add_widget_C</location>
    <parent>20200805T0800_add_widget_A</parent>
  </migration>
```

3. Take special note that the last two lines are identical for both changes that are made.

**Expected behavior**

In the previous version of Sublime Merge, the merge tool would highlight all five lines of the changes for both branches.

Branch A
```xml
  <migration id="20200805T0900_add_widget_B">
    <description>Adding widget B</description>
    <location>20200805T0900_add_widget_B</location>
    <parent>20200805T0800_add_widget_A</parent>
  </migration>
```

Branch B
```xml
  <migration id="20200805T1000_add_widget_C">
    <description>Adding widget C</description>
    <location>20200805T1000_add_widget_C</location>
    <parent>20200805T0800_add_widget_A</parent>
  </migration>
```

With this scenario, the conflict resolution process was:

1. Click the right-hand arrow button (pulling the remote change into the file)
1. Click the left-hand arrow button (pulling the local change into the file)
1. Copy the correct parent, update the lowest <parent> object value

With this new algorithm, only the mismatching changes are highlighted:

Branch A
```xml
  <migration id="20200805T0900_add_widget_B">
    <description>Adding widget B</description>
    <location>20200805T0900_add_widget_B</location>
```

Branch B
```xml
  <migration id="20200805T1000_add_widget_C">
    <description>Adding widget C</description>
    <location>20200805T1000_add_widget_C</location>
```

The new process has become:

1. Click the right-hand arrow button (pulling the remote change into the file)
1. Click the left-hand arrow button (pulling the local change into the file)
1. Highlight, copy, and paste the bottom two lines of the XML object into the middle of the resulting blob

```xml
  <migration id="20200805T0800_add_widget_A">
    <description>Adding widget A</description>
    <location>20200805T0800_add_widget_A</location>
    <parent>_root</parent>
  </migration>
  <migration id="20200805T0900_add_widget_B">
    <description>Adding widget B</description>
    <location>20200805T0900_add_widget_B</location>
  <migration id="20200805T1000_add_widget_C">
    <description>Adding widget C</description>
    <location>20200805T1000_add_widget_C</location>
    <parent>20200805T0800_add_widget_A</parent> // Copy these two lines
  </migration> // Copy these two lines
```

```xml
  <migration id="20200805T0800_add_widget_A">
    <description>Adding widget A</description>
    <location>20200805T0800_add_widget_A</location>
    <parent>_root</parent>
  </migration>
  <migration id="20200805T0900_add_widget_B">
    <description>Adding widget B</description>
    <location>20200805T0900_add_widget_B</location>
    <parent>20200805T0800_add_widget_A</parent> // Lines pasted here
  </migration> // Lines pasted here
  <migration id="20200805T1000_add_widget_C">
    <description>Adding widget C</description>
    <location>20200805T1000_add_widget_C</location>
    <parent>20200805T0800_add_widget_A</parent>
  </migration>
```

4. Then copy the correct parent, update the lowest <parent> object value

```xml
  <migration id="20200805T0800_add_widget_A">
    <description>Adding widget A</description>
    <location>20200805T0800_add_widget_A</location>
    <parent>_root</parent>
  </migration>
  <migration id="20200805T0900_add_widget_B">
    <description>Adding widget B</description>
    <location>20200805T0900_add_widget_B</location>
    <parent>20200805T0800_add_widget_A</parent>
  </migration>
  <migration id="20200805T1000_add_widget_C">
    <description>Adding widget C</description>
    <location>20200805T1000_add_widget_C</location>
    <parent>20200805T0900_add_widget_B</parent>
  </migration>
```

If you'd like screenshots of the current behavior with this sort of change, I can generate this upon request. I can't show the previous behavior because I've already updated my installed application.

**Comment by dpjohnst** [comment]
Hi @jjackson-pixel,

Thank you for sharing this feedback - we can clearly do better in this case, and well be investigating some adjustments to the merge algorithm to improve this situation.

Stay tuned,
\- Dylan

**Comment by srbs** [comment]
related: #312, #613, #620

**Comment by dpjohnst** [comment]
Hi @jjackson-pixel,

The merge algorithm has been updated as of build 2034 (development build) to resolve this issue.

Thanks,
\- Dylan

**Comment by jjackson-pixel** [comment]
Hi Dylan,

I've seen this come in with the new update - thank you for resolving my very specific use case!

Joshua
