### ISSUE TITLE
Navigate to HEAD

### ISSUE THREAD

**Issue by jorticus** [sublimehq/sublime_merge#855]
**Problem description**

It would be nice to have a command that can navigate to the current HEAD.

This would be especially useful with submodules which are usually pinned to specific commits, and in repositories with large amounts of branches where HEAD can be hard to find. (There does not seem to be an easy way except for scrolling through the large list of commits, or closing/re-opening Sublime Merge)

**Preferred solution**

Similar in functionality to 'Navigate to commit', but it automatically picks the HEAD commit

**Alternatives**

N/A

**Screenshots**

**Comment by dpjohnst** [comment]
Hi @jorticus,

Good news - this functionality already exists.

Either access it from `Navigate > Go to HEAD` or use the keybinding `ctrl + 0` (`cmd + 0 on MacOS`).

Let me know if you have any further questions regarding this functionality.

Thanks,
\- Dylan

**Comment by jorticus** [comment]
Thanks! I wasn't looking in the right place (expecting to find it in the command palette along with 'Navigate to commit'), but I see it now.

Closing issue
