### ISSUE TITLE
New context variable $commit_message in Commit.sublime-menu

### ISSUE THREAD

**Issue by overlord** [sublimehq/sublime_merge#858]
Please, add new context variable `$commit_message` in `Commit.sublime-menu`.

It will allow us to construct custom "Copy commit message" menu item.

For example like this (`...\Sublime Merge\Data\Packages\User\Commit.sublime-menu`):
```json
[
	{
		"caption": "-",
	},
	{
		"caption": "Copy '$commit_message'",
		"command": "copy_to_clipboard",
		"args": { "text": "$commit_message" }
	}
]
```

**Comment by overlord** [comment]
I saw an update "BUILD 2034 - 25 September 2020" yesterday.
There was a new feature - _selector arguments to custom git commands_.
Unfortunately, I could not find out how to use these selectors.
Can you tell, whether it can be used to create a "Copy commit message" command?

**Comment by srbs** [comment]
@overlord, that new feature does not help you with this issue. What you can do with it is to add object-selectors to custom commands, like so:

```
[
    {
        "caption": "Switch to Branch…",
        "command": "git",
        "args": { "argv": ["switch", "$select_local_branch"] }
    }
]
```

Note: commands like this only support a single `$select_*`/`$text` argument.

**Comment by overlord** [comment]
We are very sad without this functionality. Is it possible to get it since it is marked as trivial?

**Comment by overlord** [comment]
Is it still possible to add this small enhancement?

**Comment by stinos** [comment]
+1 on this. Sample usage (apart from the obvious reusing of commit messages): when constructing a `blame.ignoreRevsFile` and wanting the commit header as comment in it, it would be pretty convenient to be able to copy the messages in the commit list in the blame view in in SM.

**Comment by srbs** [comment]
@overlord, @stinos, looks like this was added in dev build 2055!

**Comment by stinos** [comment]
Nice, can confirm this works as expected.

**Comment by overlord** [comment]
OMG! It works. Thanks a lot!

**Comment by dpjohnst** [comment]
Hi all,

Thanks for the feedback - always appreciated!
As @srbs mentioned this was added in dev build 2055 - I'm going to go ahead and close this request now.

Cheers,
- Dylan
