### ISSUE TITLE
Scale up display cause extra horizontal scroll bar at the bottom

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#86]
**Version info**

 - OS: Windows 10
 - Build: Dev Build 1067

**Description**

High DPI display from notebook with Windows scale up cause extra horizontal scroll bar at the bottom

**Steps to reproduce**

1. Windows display setting to >100%
2. Move Sublime Merge windows to the scale up display

**Expected behavior**

There should be no extra horizontal scroll bar at the bottom

**Screenshots**
Scale 150%
![image](https://user-images.githubusercontent.com/4518597/46599067-cf28a080-cb18-11e8-9997-513a9a3e7c03.png)

Scale 100%
![image](https://user-images.githubusercontent.com/4518597/46599106-ee273280-cb18-11e8-93f6-ec8fb817a285.png)

**Comment by jskinner** [comment]
Thanks for the report. This is fixed in dev build 1073.
