### ISSUE TITLE
'Stage lines' isn't working.

### ISSUE THREAD

**Issue by trlorenz** [sublimehq/sublime_merge#865]
**Version info**

Ubuntu 18.04 and 20.04; Sublime Merge 2028

**Description**

'Stage lines' isn't working. Selecting a line and attempting to stage it generally results in 'Failed to apply patch: no modified lines selected'.

**Steps to reproduce**

* Modify two adjacent lines in some file.
* In the hunk, select one line.
* Click 'Stage lines'.

**Expected behavior**

I'd expect the selected line(s) to be staged. This appears to be new (mis)behavior, although I can't say when it was introduced. I've been using 'Stage lines' since... whenever Sublime Merge first came out... without issue.

**Screenshots**

![2020-08-14](https://user-images.githubusercontent.com/1243377/90288070-f398e680-de2d-11ea-8c01-52f6c205688f.png)

**Comment by srbs** [comment]
Seems to be working fine for me on macOS.

@trlorenz, does it fail every time or just that particular changeset?

**Comment by trlorenz** [comment]
Hey @srbs. Been fiddling with it. The problem does seem to depend on the nature of the changeset.

So far it's been 100% reproducible for me if the changeset contains only changes of existing lines. I've tried probably a couple dozen different files.

But line-staging adds or deletions isn't always a problem, and the presence of adds in a file seems to affect whether line-staging a change will succeed or not. There's a pattern to it, I'm sure, but I haven't nailed it down yet.

Initial commit of file:

![2020-08-14 (1)](https://user-images.githubusercontent.com/1243377/90294905-7163ee80-de3c-11ea-944e-281f6d307220.png)

Added a line 'NEW' and changed the middle 'TEST' lines to 'TESTx'.

Trying to stage the 'NEW' line:

![2020-08-14 (2)](https://user-images.githubusercontent.com/1243377/90294983-9fe1c980-de3c-11ea-9b57-28734e752dcb.png)

Trying to stage the first 'TESTx' line:

![2020-08-14 (3)](https://user-images.githubusercontent.com/1243377/90295007-b12ad600-de3c-11ea-906c-d0e9a195b195.png)

Trying to stage the second 'TESTx' line, and succeeding (but not sure if the staged result looks right):

![2020-08-14 (4)](https://user-images.githubusercontent.com/1243377/90295094-e6cfbf00-de3c-11ea-8550-0f7d87ea2a41.png)

**Comment by dpjohnst** [comment]
Hi @trlorenz,

Thanks for reporting this - we're actively investigating this issue, and I'll keep you updated as things progress.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @trlorenz,

We've just released Sublime Merge development build 2028. Could you update to this version when you have a chance, and confirm if the issue is resolved.

Thanks,
\- Dylan

**Comment by trlorenz** [comment]
Yep, looks like you nailed it. Thanks, Dylan.

**Comment by dva** [comment]
Still reproducible with latest 2032 build.

**Comment by dpjohnst** [comment]
Hi @dva,

Thanks for reporting this. When you have a chance, could I get you to open a new issue to describe the issue you're facing.

Thanks,
\- Dylan

**Comment by dva** [comment]
@dpjohnst #881
