### ISSUE TITLE
Preview support for WebP images

### ISSUE THREAD

**Issue by Nohus** [sublimehq/sublime_merge#867]
**Problem description**

Sublime Merge shows previews for image files, however it does not work for WebP images.
WebP is an image format made by Google for lossless and lossy image compression. WebP images are smaller than both PNG and JPEG images, at the same quality levels. More information: https://developers.google.com/speed/webp

Due to the size savings, it is popular among web developers and Android developers, where the Android Studio IDE suggests converting images to WebP, so many app projects are using it.

It would help if Sublime Merge showed previews for it, currently it just displays the `<binary file changed>` message.

**Preferred solution**

Official tools and libraries for handling WebP images are available on the official website: https://developers.google.com/speed/webp

**Comment by Nohus** [comment]
@dpjohnst Any movement on this? As you can see above, when I reported the same issue on a free Git client made by one volunteer, it got fixed the same day. Here I didn't even get a response after almost 3 years, on a piece of software I am paying for. :/

**Comment by dpjohnst** [comment]
Hi @Nohus,

Thank you for your patience while this was implemented. This was added in Sublime Merge 2084 (and will be available in the next stable build too)!

Kind regards,
\- Dylan from Sublime HQ

**Comment by Nohus** [comment]
Thank you.

**Comment by Nohus** [comment]
@dpjohnst Is there a timeframe for 2084 being released? I was happy for this to be available but 4 months later it's still not released. :(

**Comment by themilkman** [comment]
@Nohus  2084 was released in march (see: https://www.sublimemerge.com/dev ), maybe you're currently on the "stable" release channel (https://www.sublimemerge.com/download)? If so, you may switch over to dev builds (if I see it correctly even without license, but at very least with) by installing the dev build over the stable.

**Comment by Nohus** [comment]
Yes I'm using the stable version. I'm aware a dev build exists but I was waiting for a stable version.
