### ISSUE TITLE
Version Tags are not ordered properly

### ISSUE THREAD

**Issue by jasonycw** [sublimehq/sublime_merge#87]
**Version info**

 - OS: Windows 10
 - Build: 1067

**Description**

The Tags with version is not ordered properly

**Steps to reproduce**

1. Open repository with many tags with something like 1.1, 1.2, 1.19, 1.20
2. Expand the Tags section
3. It will order: 1.1, 1.19, 1.2, 1.20

**Expected behavior**

Order by properly: 1.1, 1.2, 1.19, 1.20

**Screenshots**
![image](https://user-images.githubusercontent.com/4518597/46600012-6e4e9780-cb1b-11e8-804d-c0d25d13c444.png)

**Comment by jskinner** [comment]
Implemented in 1076
