### ISSUE TITLE
Error popup hangs around forever

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#871]
**Version info**

 - OS: Windows 10 x64 2004
 - Build: 2028

**Description**

At some point if git refuses to perform an action, the error popup apears and stays forever. It doesn't happen each time and I don't know how to reproduce, but I've seen that quite often .

**Steps to reproduce**

???

**Expected behavior**

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/90548626-836fc500-e18d-11ea-91e1-0143c1e07eeb.png)

**Comment by deathaxe** [comment]
Behavior got better with ST 2034.

What I still see is the error popup to stay visible after switching to another repo. I can't dismiss the popup then except by switching back to the tab which it was created by.

With regards to the screenshot it means.

1. Select `Packages_CSS` tab
2. Do something wrong, which causes the error popup to be displayed
3. Switch to `Packages_Ruby` tab _(popup stays visible, can't hide it)_
4. Switch back to `Packages_CSS` _(popup disapears)_

**Comment by deathaxe** [comment]
Situation has improved with SM 2046 as switching repos via tabs seems to hide the popup.

**Comment by srbs** [comment]
@deathaxe , this should be fixed in dev build 2051 or stable build 2054.
