### ISSUE TITLE
Sublime Text 4 crashes when using the function goto_symbol_in_project

### ISSUE THREAD

**Issue by choallin** [sublimehq/sublime_merge#873]
**Version info**

 - OS: Ubuntu 20.04
 - Build: 4083

**Description**
Whenever I try to call the command goto_symbol_in_project in a PHP or Ruby Projcet - which are the only languages I currently develop in - the editor completly crashes and is shut down

**Steps to reproduce**
I bind the command to the keyboard shortcut ctrl+shift+r. I press this key and then the app crashes

**Expected behavior**
It should show the popup where I can search for a symbol in my project

**Comment by srbs** [comment]
@choallin, this is the Sublime Merge issue tracker, please close this & recreate in https://github.com/sublimehq/sublime_text/issues.
