### ISSUE TITLE
Allow copying current branch name to clipboard

### ISSUE THREAD

**Issue by motine** [sublimehq/sublime_merge#874]
**Problem description**

I often have to paste the current branch name into forms. I would love to be able to copy the branch name right from Sublime Merge instead of having to go via the console. 

**Preferred solution**

Add a "Copy Branch Name" in the [...] button next to [magnifying glass] in the header.

**Screenshots**

![image](https://user-images.githubusercontent.com/1439041/90753360-cab69c80-e2d8-11ea-9780-bf5e0fa01e8f.png)

**Comment by srbs** [comment]
You can currently copy branch names by right clicking on the branch in the locations side bar or the commit graph (on the branch's HEAD commit).

As for that menu, you can modify the menus at will ([docs](https://www.sublimemerge.com/docs/menus#available_menus)). For your request, you can add the below to `User/Action.sublime-menu`:
```
[
    {
        "caption": "Copy '$head'",
        "command": "copy_to_clipboard",
        "args": { "text": "$head" }
    }
]
```

**Comment by motine** [comment]
Great feedback. Thanks for the tips (in hindsight I should have looked in other menus too, sorry).
