### ISSUE TITLE
Win OS: File Mode Change Bug

### ISSUE THREAD

**Issue by tajmone** [sublimehq/sublime_merge#875]
**Version info**

 - OS: Windows 10 x64
 - Build: 2030

**Description**

After changing file mode of a shell script to executable, SM keeps it the stage area even if the file was renamed after staging it's mode changes.

SM GUI still shows the (now renamed) file in the stage area:

```
File mode changed:
Normal File → Executable File
```

I'm not sure if this is a SM or Git bug (or even if it's a bug at all), but in any case SM could handle similar situations in a smarter way (even if it was due to Git for Windows).

**Steps to reproduce**

I'm not sure how I got there and how to reproduce it, but this is most likely how I got to the problem in the first place.

I have create a new shell script (let's call it `myscript.sh`) then changed it's file mode to executable and staged the changes (most likely, only the mode changes, not the file itself).

Then I renamed the file (e.g. to `newname.sh`) and staged it, but `myscript.sh` is still showing in the stage area as:

```
File mode changed:
Normal File → Executable File
```
although it's no longer available in the repository — and neither in the stage area, except for the detected mode change (i.e. no contents shown in the diff anywhere).

**Comment by tajmone** [comment]
Ignore the report. I finally realized what went wrong locally, and it's not a bug in SM nor Git.

**Comment by srbs** [comment]
@tajmone, in case someone else is looking for an answer for this, what went wrong?

**Comment by tajmone** [comment]
> what went wrong?

the script shown in SM had indeed changed file mode — it was just a case of two scripts with same name in different folders, and because I gave for granted that all previous scripts were already set to executable I was assuming that the file mode change being detected was on the newer script, which was not the case.

Because file modes don't have a real impact under Windows, it's easy to get entangled with their mode settings — which are being set on the repository only for the sake of non-Windows users.

I often overlook file paths in SM and mix up same-named files with different paths due to accessibility problems — i.e. the Dark theme doesn't provide enough contrast between text and background colors, and the font is too small, so it's a strain on my eyes for me to read the full paths and I tend to merely glance at them and fill in gaps with expectations.
