### ISSUE TITLE
Scrolling performance degraded in build 2031

### ISSUE THREAD

**Issue by myzeiri** [sublimehq/sublime_merge#876]
**Version info**

 - OS: Windows 10
 - Build: Dev build 2031

**Description**

Scrolling through the commit tree and opening/collapsing merge commits has gotten much laggier in the latest dev build. As an extreme example, scrolling from the very first commit and back to the top with ctrl-0 is very choppy now while the stable build is buttery smooth. Dev build 2030 seems good as well.

**Steps to reproduce**

1. Open repository
2. Scroll down to the first commit by hitting End
3. Hit ctrl-0 to navigate back to the top
4. Commit tree view stutters noticeably 

**Expected behavior**

Scrolling performance should be as smooth as the stable build.

**Other notes:**

Hardware acceleration is disabled.

**Comment by dpjohnst** [comment]
Hi @myzeiri,

Thank you for reporting this issue - so far I haven't had much luck replicating the issue.

It's odd that build 2030 doesn't see the issue too, as there are minimal changes between 2030 and 2031.
Do you have any antivirus software installed? Often it will cause performance degradation in legitimate applications.
 
Could you also confirm whether the performance issue goes away when OpenGL rendering is enabled?

Thanks,
\- Dylan

**Comment by myzeiri** [comment]
@dpjohnst 

The problem went away after I reinstalled Sublime Merge from scratch. I'm on a corporate laptop so yes, there's antivirus and other monitoring installed. That's must have been what caused the slowness.

Thanks for looking into it for me. I'll go ahead and close the issue. Loving all the new features btw. 👍
