### ISSUE TITLE
Incorrect result display when reverting line fails

### ISSUE THREAD

**Issue by stinos** [sublimehq/sublime_merge#878]
**Version info**

 - OS: Windows 10
 - Build: 2031

**Description**
There's 2 contradicting messages when a line cannot be reverted: one says `failed: Revert Hunk` and the other one says `Reverted succesfully`.

**Steps to reproduce**
1. Open repository, click on a commit
2. Select a line in the diff which cannot be reverted because later commits change the same line
3. Click on the `Revert lines` button

**Expected behavior**

Display an unambiguous result.

**Screenshots**
<img width="276" alt="Untitled" src="https://user-images.githubusercontent.com/1902997/91149639-9d446700-e6bb-11ea-8677-f662341851e5.png">

**Comment by srbs** [comment]
probably related to #866

**Comment by dpjohnst** [comment]
Hi all,

Just a quick update - this has been resolved in the latest development build (2034) and will be available in the next stable build.

Kind regards,
\- Dylan

**Comment by stinos** [comment]
Thanks, works for me.
