### ISSUE TITLE
Pressing Alt results in tab header row being shown twice

### ISSUE THREAD

**Issue by stinos** [sublimehq/sublime_merge#879]
**Version info**

 - OS: Windows 10
 - Build: 2031

**Description**

Pressing Alt shows the menu bar but also renders the tab headers twice.

**Screenshots**

<img width="429" alt="Capture" src="https://user-images.githubusercontent.com/1902997/91150175-54d97900-e6bc-11ea-8ada-874dbcd1548c.PNG">

**Comment by dpjohnst** [comment]
Hi @stinos,

This is likely due to a known driver bug with Intel HD 600 series GPUs.
The best work-around for the time-being is to disable OpenGL hardware rendering via the preferences dialog.

Thanks,
\- Dylan

**Comment by stinos** [comment]
> disable OpenGL hardware rendering

@dpjohnst yes, that works, thanks.
