### ISSUE TITLE
Add Image Diff support for Photoshop documents

### ISSUE THREAD

**Issue by strawlink** [sublimehq/sublime_merge#880]
**Problem description**

I love being able to see image diffs, but most of the images we use are stored and committed as PSDs (with GIT LFS enabled). Sublime Merge does not currently show image diffs for this filetype.
Photoshop image diffing is supported by [GitHub](https://github.blog/2014-06-05-psd-viewing-diffing/) and [BitBucket](https://jira.atlassian.com/browse/BCLOUD-12457).

**Preferred solution**

Use the existing image diff functionality, but add support for also diffing Photoshop documents.

**Comment by dpjohnst** [comment]
Hi @strawlink,

This was added in Sublime Merge build 2042!
