### ISSUE TITLE
Allow spaces in creating new branch name. Transform spaces to `-`.

### ISSUE THREAD

**Issue by nikitavoloboev** [sublimehq/sublime_merge#883]
When creating a new branch:

![unknown](https://user-images.githubusercontent.com/6391776/91318452-871dd000-e7bb-11ea-9c1c-d95095551f3f.png)

It would be nice if above worked and created a branch with name `extend-dashboard`. Essentially allowing spaces in creating of branch names that will get converted to `-` after.

**Comment by dpjohnst** [comment]
Hi @nikitavoloboev ,

This is now available in the latest builds (2037 dev / 2038 stable)!

Cheers,
\- Dylan
