### ISSUE TITLE
Expose $branch variable in command palette

### ISSUE THREAD

**Issue by nikitavoloboev** [sublimehq/sublime_merge#884]
Currently in order to copy active branch you have to right click on the branch name in sidebar. It would be great if it was one of the actions accessible in main command palette.

**Comment by Ultra-Instinct-05** [comment]
This would be easy to add via the following entry to the `Default.sublime-commands` file in `User`.
```json
{
	"caption": "Copy branch name",
	"command": "copy_to_clipboard",
	"args": {
		"text": "$branch"
	},
}
```
but it doesn't work because, I guess Merge doesn't expose the `$branch` variable from the command palette.

**Comment by nikitavoloboev** [comment]
I reworded the issue. Adding such variable would indeed be very valuable.

**Comment by srbs** [comment]
Use `$head`. Turns out it is available within the command palette even though it's only mentioned in the [menu docs](https://www.sublimemerge.com/docs/menus#available_menus).

**Comment by Ultra-Instinct-05** [comment]
```json
{
	"caption": "Copy branch name",
	"command": "copy_to_clipboard",
	"args": {
		"text": "$head"
	},
}
```
This works as expected, thanks to @srbs

**Comment by dpjohnst** [comment]
Hi all,

Thanks for sharing this feedback.

I'm going to go ahead and close this, as there is the `$head` variable available.
That being said, we'll also be updating the command palette documentation to list the available variables.

Kind regards,
\- Dylan from Sublime HQ
