### ISSUE TITLE
Add `drop stash` command

### ISSUE THREAD

**Issue by nikitavoloboev** [sublimehq/sublime_merge#886]
If I selected a stash in the left sidebar and am looking at the diffs of it. I would love if there was a command to `drop stash`. Currently you are forced to right click on the stash in left sidebar and delete it (which requires a mouse).

**Comment by srbs** [comment]
see also related stash command requests: #545, #570

**Comment by dpjohnst** [comment]
Hi all ,

This is now available in the latest builds (2037 dev / 2038 stable)!

Cheers,
\- Dylan
