### ISSUE TITLE
Solo branch (ALT+Click branch) does not work for current branch

### ISSUE THREAD

**Issue by pdanpdan** [sublimehq/sublime_merge#89]
**Version info**

 - Windows 7 x64
 - Build: 1068

**Description**

Hide all branches except the clicked one works by clicking the eye icon while holding ALT.
But current local branch has no eye icon, so I cannot hide all branches except current one.

**Steps to reproduce**

1. Open a repo with multiple branches
2. Make sure one local branch is checked out
3. There is no eye icon in the Location Bar (and ALT+Click on branch name does not work)

**Expected behavior**

Either ALT+Click to work on branch name or the eye icon to be visible.

**Comment by jskinner** [comment]
Thanks for the report - this is not supported in 1069
