### ISSUE TITLE
Status tooltip after Pull does not disappear

### ISSUE THREAD

**Issue by luc4s** [sublimehq/sublime_merge#894]
**Version info**

 - OS: Windows 10
 - Build: 2032

**Description**

After pulling a branch, the tooltip indicating the file changes sometimes does not disappear.

**Steps to reproduce**

1. Pull any remote branch? (unfortunately, seems to be nondeterministic)

**Expected behavior**

It should fade away after a short time. And if possible, it would be nice to shorten it when many changes are pulled (as it covers the whole screen when it's big).

**Screenshots**
![image](https://user-images.githubusercontent.com/688731/91717818-83f75b00-eb92-11ea-8b1b-079a0d0627c5.png)

**Comment by srbs** [comment]
This should have been fixed in dev build 2051 / stable build 2054. as seen in #1111.

**Comment by dpjohnst** [comment]
Hi @luc4s,

Sublime Merge 2086 (development build) has been released which fixes this.
This fix will also be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ
