### ISSUE TITLE
Search open Merge tabs 

### ISSUE THREAD

**Issue by nikitavoloboev** [sublimehq/sublime_merge#895]
If for example these four tabs are open:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/6391776/91738895-71d8e500-ebb1-11ea-9d43-2fe442775a6a.png">

The action would allow to search over active tabs and on return, open the tab.

**Comment by wbond** [comment]
If you are looking to search over the repository names, which is what is displayed in the tabs, you can use the *Switch Repository* feature. It will focus the tab if the repository is open, or open a new tab with the repository.

**Comment by nikitavoloboev** [comment]
Oh right, I knew of the feature but didn't think it would switch over to active tab instead of overwriting current one. Thanks @wbond

**Comment by srbs** [comment]
> or open a new tab with the repository

@wbond, _Switch Repository_ doesn't do that, it overwrites the current tab if not open.

**Comment by wbond** [comment]
> Switch Repository doesn't do that, it overwrites the current tab if not open.

Ah, good point!
