### ISSUE TITLE
The 'clone repository' UI box should focus to [Source URL] text control on opening, allow keyboard navigation

### ISSUE THREAD

**Issue by mamift** [sublimehq/sublime_merge#896]
**Problem description**

Hello, currently, when cloning a repository, the UI that displays does not automatically focus on any control (text, button or otherwise) and using TAB or Enter doesn't seem to do anything.

To paste a URL into the [Source URL] text box requires moving the mouse, clicking in it and then using the keyboard to paste copied text (CTRL+V).

I clone repos quite regularly (on a weekly basis) and implementing full keyboard control + navigation in this UI box would go a long way to speeding up my workflows.

**Preferred solution**

* The **Clone repository** UI should auto focus on the [Source URL] text box on opening
* Allow full keyboard navigation in the **Clone repository** UI

Secondary things:

* Also allow dismissing the **Clone repository** UI via the ESC key.
* In addition to auto focusing on the [Source URL] text box, if Sublime Merge detects a fully qualified URL in the clipboard, it should auto complete to that URL.

**Alternatives**

None.

**Screenshots**

![image](https://user-images.githubusercontent.com/2508444/91769836-763de600-ec23-11ea-98fd-100bddc05a94.png)

Test in the following Sublime Merge version:
![image](https://user-images.githubusercontent.com/2508444/91770267-3b887d80-ec24-11ea-97df-2defe0f563bb.png)

**Comment by dpjohnst** [comment]
Hi @mamift,

Just a quick update - this has been resolved in the latest development build (2034) and will be available in the next stable build.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge Build 2039
