### ISSUE TITLE
Allow upstream to be changed to a different remote

### ISSUE THREAD

**Issue by bendilley** [sublimehq/sublime_merge#897]
**Version info**

 - OS: macOS 10.15.6
 - Build: 2032

**Description**

The changelog for build 2032 says “Improved `--set-upstream` behaviour” but now I can no longer switch my upstream branch once it has been set. I work with multiple remotes and my workflow often requires that I switch my local branch to push to a different remote, setting it as the new upstream.

Perhaps the logic should be to present the `--set-upstream` option unless the proposed remote branch is already the upstream? At the moment it looks like the option is simply removed once it’s set, i.e. it cannot be _changed_.

**Steps to reproduce**

1. Set up a repo with two remotes
2. create a new branch
3. push the branch to one of the remotes, choosing `--set-upstream`
4. push the branch again, but to the other remote...

**Expected behavior**

I expect the `--set-upstream` option to be available for the other remote, since it's not the current upstream for my local branch.

**Actual behaviour**

The option isn't available. It only seems to be available while the upstream is not set. As soon as the upstream is set it cannot be _changed_ via Sublime Merge.

**Comment by bendilley** [comment]
This appears to be fixed in Build 2038

**Comment by srbs** [comment]
@bendilley, feel free to close this issue!
