### ISSUE TITLE
Image Diff feature renders all still frames of animated GIFs correctly except for 1 image.

### ISSUE THREAD

**Issue by nathanhere** [sublimehq/sublime_merge#898]
**Version info**

 - OS: macOS 10.14
 - Build: 2032

**Description**

Love the image diff feature. It rendered still frames of all my animated GIFs except for one that was **22.2 MB**.

**Steps to reproduce**

1. Commit GIFs
2. View Commit

**Expected behavior**

All GIF stills to render.

**Screenshots**

Screenshot below (see the very last section of that screenshot showing W:0 H:0).
---
![Screen Shot 2020-09-03 at 11 21 34 AM](https://user-images.githubusercontent.com/1151667/92141239-cbbaf400-edd7-11ea-8f31-47020f6e9f4b.png)

**Comment by dpjohnst** [comment]
Hi @nathanhere,

Thanks for reporting this! I'll be investigating this further.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @nathanhere,

Just a quick update - this has been resolved in the latest development build (2034) and will be available in the next stable build.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @nathanhere,

This is now fixed in the latest stable build (2038) - thanks again for helping report this issue.

Cheers,
\- Dylan
