### ISSUE TITLE
Stash failing

### ISSUE THREAD

**Issue by willrowe** [sublimehq/sublime_merge#90]
**Version info**

 - OS: macOS 10.12.6
 - Build: 1068
 - Git: "bundled" /Applications/Sublime Merge.app/Contents/Resources/Git/bin/git version 2.18.0

**Description**

I run `Stash` from the command palette and it does not stash any changes and displays an error message:

```
usage: git stash list [<options>]
   or: git stash show [<stash>]
   or: git stash drop [-q|--quiet] [<stash>]
   or: git stash ( pop | apply ) [--index] [-q|--quiet] [<stash>]
   or: git stash branch <branchname> [<stash>]
   or: git stash [save [--patch] [-k|--[no-]keep-index] [-q|--quiet]
		       [-u|--include-untracked] [-a|--all] [<message>]]
   or: git stash clear
```

 - I thought that maybe it was an issue with the git version since I was previously using `"system"` as the value for `git_binary` (v2.10.1 is intalled on the OS). However, I checked that preference and it was set to `null`, which I assumed would using the bundled version. After looking at 'Debug Information' though, it was still using the system version of git.
 - Since I wasn't sure what the value was supposed to be by default, I tried a value of `"bundled"` which then caused the 'Debug Information' to return the value in 'Version info' above.
 - Even after doing all of this it is still not working though. I even tried to run the `git stash push -q`  command directly using the bundled version of git, but I still got the same error message.

**Steps to reproduce**

1. Open any repository with un-committed changes.
2. Run command `Stash` from the command palette.

**Expected behavior**

The un-committed changes should be in a new stash entry.

**Screenshots**
![stash](https://user-images.githubusercontent.com/7152423/46626887-abf4f580-cb06-11e8-8ef2-e088fce31966.png)

**Comment by jskinner** [comment]
Thanks for the report, this should be working in 1069 now - please reopen this if it's not.

git 2.10.1 is too old to have `git stash push`, which is what Sublime Merge uses. 1069 now uses `git stash save` where possible, which will work with 2.10.

1069 also addresses the issue of `git stash` not working when using the bundled version of git.

**Comment by willrowe** [comment]
I can confirm this is now working 1069. Thank you so much for your work on this!

**Comment by Teeed** [comment]
Hi,

got similar problems with build: 1116, sublimemerge tries to execute "git stash push -q --include-untracked --keep-index" which results in the git usage info... Executing "git stash  -q --include-untracked --keep-index" works fine..

git version 2.7.4
