### ISSUE TITLE
Build 2032 hangs when moderate numbers of very large files change

### ISSUE THREAD

**Issue by jaroslov** [sublimehq/sublime_merge#902]
**Version info**

 - OS: macOS Catalina 10.15.6
 - Build: 2013

**Description**

I have a project with a large number (dozens) of very long C++ files. Many of them in the multiples of 100klocs. Prior to this build, when I had such an outstanding diff, I'd get Sublime Merge's moral equivalent of the beach ball, but the application was still usable (I'd ignore the diffs).

Now, the GUI becomes entirely locked up. Unless I can 'hide' the diffs, the entire program becomes stuck *indefinitely* (I tried waiting up to 24 hours).

**Steps to reproduce**

1. Create a large repository with a large number of large files.
2. Create changes in (say) 12 files of 5000-10000 lines, each.
3. Enjoy.

If you force-quite Sublime Merge and restart it, it hangs way less often. This only happens when Sublime Merge is already open.

**Expected behavior**

Less completely locking up.

**Comment by dpjohnst** [comment]
Hi @jaroslov,

Thank you for reporting this issue.

Could you confirm roughly how many hunks are visible (i.e. is it a few large changed hunks, or many small changed hunks per file)?

We have a known performance issue with many small changed hunks for large files, which we are currently investigating.

Kind regards,
\- Dylan

**Comment by jaroslov** [comment]
Thousands of small hunks.

**Comment by jaroslov** [comment]
This issue is resolved in dev build 2033. (Actually, there's a noticeable improvement in responsiveness in 2033, even when the issue scales to >100,000 hunks.)

Thanks!
