### ISSUE TITLE
File changes summary doesn't scroll all the way to the bottom of the list

### ISSUE THREAD

**Issue by andyp123** [sublimehq/sublime_merge#904]
**Version info**

 - OS: Windows 10
 - Build: 2033 (issue has been present for a while - maybe forever?)

**Description**

The scroll bar of the file changes summary panel doesn't scroll all the way to the bottom of the list when the change details are expanded (which is the default state), so the last entry gets cut off.

**Steps to reproduce**

1. Open repository with a lot of file changes
2. Try scrolling to the bottom of the list of files without collapsing the details

**Expected behavior**

The scroll bar should allow me to scroll all the way down and see all the file changes and preferably give a little bit of padding at the bottom so everything is not squished up against the bottom and it's clear there are no more changes in the list.

**Screenshots**

![sublime_merge_scroll_issue](https://user-images.githubusercontent.com/1097744/92351829-9ab02b80-f117-11ea-82c5-8e65c83f412b.PNG)

**Comment by dpjohnst** [comment]
Hi @andyp123,

Thank you for reporting this issue! 

I've been able to replicate this issue and will be investigating this further.
This looks like an issue with multiple binary files present.

I'll keep you updated as we progress through this bug.

Kind regards,
\- Dylan

**Comment by jasonycw** [comment]
Same thing happens in my repo when I rename the project and cause a lot of file changes.
![image](https://user-images.githubusercontent.com/4518597/92876794-14f4ee80-f43d-11ea-9eec-39c727c55749.png)

Also Build 2033

**Comment by dpjohnst** [comment]
Hi all,

Just a quick update - this has been resolved in the latest development build (2034) and will be available in the next stable build.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

This is now fixed in the latest stable build (2038) - thanks again for helping report this issue.

Cheers,
\- Dylan
