### ISSUE TITLE
Show Branch... doesn't do anything

### ISSUE THREAD

**Issue by nikitavoloboev** [sublimehq/sublime_merge#907]
**Version info**

 - OS: 10.15.6
 - Build: 2033

**Description**

Show Branch... command does nothing for me.

<img width="112" alt="image" src="https://user-images.githubusercontent.com/6391776/92490370-3c577b80-f1f1-11ea-85a6-3a28a9cb1aee.png">

It should jump to the commit of the branch I have selected in commit tree but it does nothing.

**Comment by srbs** [comment]
All it does it show/hide branches. However, sometimes if the branch is within a collapsed merge commit it may not show up. If you want to navigate/jump to the branch, use the `Navigate to Branch...` command.

**Comment by dpjohnst** [comment]
@srbs is indeed correct!

To remove any ambiguity, I'm going to be investigating renaming this command to "Show Hidden Branch...".

**Comment by nikitavoloboev** [comment]
Thank you. Navigate branch is indeed what I wanted.
