### ISSUE TITLE
Immediate crash after start

### ISSUE THREAD

**Issue by rderimay** [sublimehq/sublime_merge#908]
**Version info**

 - OS: macOS BigSur beta 11
 - Build: 2032

**Description**

When started, Sublime Merge displays its window for about 1 second and immediately crashes.

**Steps to reproduce**

1. Open
2. Nothing else :-)

I already tried to delete the preference plist with no luck

**Console log info**

Sep  9 16:57:16 MacBook-Pro-RD com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.sublimemerge.54657417.54657589(501)> [969]

Sep  9 16:57:19 MacBook-Pro-RD com.apple.xpc.launchd[1] (application.com.sublimemerge.54657417.54657589[44259]): Service exited with abnormal code: 5

**Comment by dpjohnst** [comment]
Hi @rderimay,

Thanks for reporting this issue!

Could you confirm whether starting Sublime Merge in safe mode solves this issue.
You can start Sublime Merge in safe mode via the following:
* Run `smerge --safe-mode` via the terminal
or
* while holding the `alt` key, start Sublime Merge

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @rderimay,

Just wanted to follow up to see if the issue resolved on your end?

Kind regards,
\- Dylan
