### ISSUE TITLE
Push/Pull buttons are not always working

### ISSUE THREAD

**Issue by BercziSandor** [sublimehq/sublime_merge#911]
**Version info**

 - OS: [Windows 10]
 - Build: [2032]

**Description**

The push/pull buttons are not active at some situations.
There is a workaround: **after resizing of the window, the buttons can work as expected**.

**Steps to reproduce**

I couldn't find the exact root cause, but I am sure: the bug came with the version 2032. I use Merge for years, but this is a new "feature".

**Expected behavior**

The buttons must work: on mouse over, the buttons must be a bit lighter. 

**Screenshots**

Not working:
![image](https://user-images.githubusercontent.com/1443421/93068705-2298b700-f67d-11ea-8229-f98c80f7dc6f.png)

Working:
![image](https://user-images.githubusercontent.com/1443421/93068421-b5852180-f67c-11ea-8dbe-b1db622afccc.png)

**Comment by dpjohnst** [comment]
Hi @BercziSandor,

Thank you for reporting this.

Could you confirm the following:
* Whether you're using OpenGL rendering (You can check this under `Preferences > Advanced`)
* Whether the Sublime Merge window is focused when the issue occurs
* Whether the button can still be clicked despite the hover state, or whether the button is fully disabled

Kind regards,
\- Dylan

**Comment by BercziSandor** [comment]
_Whether you're using OpenGL rendering (You can check this under Preferences > Advanced)_
OpenGL: On
_Whether the Sublime Merge window is focused when the issue occurs_
Yes
_Whether the button can still be clicked despite the hover state, or whether the button is fully disabled_
No

**Comment by dpjohnst** [comment]
Hi @BercziSandor,

Just following up on whether this issue still persists for you in Sublime Merge build 2039 (the latest stable build)?

Kind regards,
\- Dylan
