### ISSUE TITLE
Shortcut to toggle between "show only current branch" / "show all branches"

### ISSUE THREAD

**Issue by rchl** [sublimehq/sublime_merge#914]
**Problem description**

There are ways to show only the current branch and all branches using the context menu but there is no keyboard shortcut to do that.

**Preferred solution**

Either include a keyboard shortcut that does that or support creating a custom shortcut.

**Alternatives**

Currently one can create a shortcut to show only the current branch:

```js
    {
        "keys": ["ctrl+h"],
        "command": "hide_all_refs_except",
        "args": {
            "ref": "refs/heads/$head"
        },
    },
```

And there is a `show_all_refs` command to show all refs but there doesn't seem to be a way to create a toggle shortcut.

There would need to be some state exposed that the shortcuts could check to enable them conditionally.
The extra state that would help here could mean "true if any ref is hidden".

Or there could just be an additional command that does what is requested.

**Comment by srbs** [comment]
Use the `Hide All Branches Except...`command in the palette. The default branch is the current branch, so you would only have to press enter.

**Comment by rchl** [comment]
The point is to have a single shortcut to toggle between all and the current branch. Having to open command palette, search for the command, confirm it and then use a separate command or shortcut to do the opposite is nowhere near as simple as one shortcut.

**Comment by dpjohnst** [comment]
Hi @rchl,

This was added in Sublime Merge Build 2057 (Dev) / 2059 (Stable)!
You can toggle focus using `Ctrl + 8` (`Cmd + 8` on MacOS).

Cheers,
\- Dylan from Sublime HQ

**Comment by rchl** [comment]
Very nice.

The only thing that is IMO missing is having this exposed in either or all:
 - Main menu
 - Command Palette

It's easy to forget what the shortcut is and it's not exposed anywhere right now.
The fact that SM doesn't show the list of built-in key bindings on selecting "Edit Key Bindings..." also doesn't help.
