### ISSUE TITLE
Wrong Product and File Version numbers on Windows.

### ISSUE THREAD

**Issue by RealKindOne** [sublimehq/sublime_merge#916]
**Version info**

 - OS: Windows 7
 - Build: 2033

**Description**

Wrong version number.

**Steps to reproduce**

1, Right click the EXE
2, Click "Properties"
3, Click "Details" Tab

See: File Version: 1.1.1.6
See Product Version: 1116

**Expected behavior**

Show 2033.

![sm_bug](https://user-images.githubusercontent.com/20209685/93276900-de95d700-f78e-11ea-90a3-8c71354c94b1.png)

**Comment by dpjohnst** [comment]
Thanks for reporting!

Fixed in the latest dev and stable builds.

Kind regards,
\- Dylan
