### ISSUE TITLE
Visual artefacts in suse linux 15.1 with fvwm

### ISSUE THREAD

**Issue by brandy125** [sublimehq/sublime_merge#920]
**Version info**

 Suse Linux 15.1 running inside Parallels (16.0.1) on a Mac with Catalina 10.15.6
 Window Manager: fvwm
 Sublime Merge Build: 2032
 
**Description**

Visual artefacts in the GUI
![Screenshot_2020-09-17 18 33 32_qtiMJV](https://user-images.githubusercontent.com/59102584/93530709-678a4b00-f914-11ea-93af-d569df6817dd.png)

In addition, when the mouse hoovers over an item it changes the color from dark to bright. 
Fonts are not sharp. They seem to have a "ghost".

**Steps to reproduce**

1. start sublime_merge
2. hoover with the mouse over an item

**Expected behavior**

Appearance like it was some versions ago.

**Screenshots**

![Screenshot_2020-09-17 18 38 02_YCsBFT](https://user-images.githubusercontent.com/59102584/93531034-f72ff980-f914-11ea-9f66-9695e5cc5aad.png)
![Screenshot_2020-09-17 18 38 27_MI1PJe](https://user-images.githubusercontent.com/59102584/93531073-057e1580-f915-11ea-8dcd-9045d8b644e1.png)
![Screenshot_2020-09-17 18 40 11_pQaBUG](https://user-images.githubusercontent.com/59102584/93531237-437b3980-f915-11ea-9d7b-02b943eb7aba.png)

**Comment by brandy125** [comment]
Hardware acceleration is not enabled because if I enable it sublime_merge starts with following message:
![Screenshot_2020-09-18 08 27 53_BDbguN](https://user-images.githubusercontent.com/59102584/93592633-e3be7600-f988-11ea-81a8-433b153916ee.png)

**Comment by BenjaminSchaaf** [comment]
Honestly no clue what's going on there. There's very clearly only one main function in each shader and they're working on a fair number of devices without issue. My only guess is that something's corrupted.

**Comment by brandy125** [comment]
How should I proceed? I already uninstalled and installed sublime-merge.
What else can I try?

**Comment by BenjaminSchaaf** [comment]
Can you do an `md5sum` of the executable?

**Comment by brandy125** [comment]
2e9ab1d3eadc21bb08c61483f27e3810  sublime_merge

**Comment by BenjaminSchaaf** [comment]
8f027d61b17db434b18dd656ce015d95  sublime_merge is what I get for build 2032.

**Comment by brandy125** [comment]
How can this be?
Installing: sublime-merge-2032-1.x86_64
![Screenshot_2020-09-18 09 22 10_hRx5kM](https://user-images.githubusercontent.com/59102584/93596873-79113880-f990-11ea-81d8-024369555725.png)
![Screenshot_2020-09-18 09 26 26_64XEgb](https://user-images.githubusercontent.com/59102584/93597222-15d3d600-f991-11ea-9bec-a3a4de8d2b29.png)

I think I found already the glitch with the ugly fonts and the ghosts.
I removed ~/.config/sublime-merge and now the fonts are ok.

Still the problem with OpenGL. If you have any further idea on what I can try let me know.

**Comment by BenjaminSchaaf** [comment]
Not sure. You could try debugging with something like [renderdoc](https://renderdoc.org/) but otherwise OpenGL in VMs without GPU pass-through generally isn't great to begin with. I'm closing the issue as you seem to have fixed the artefacts.
