### ISSUE TITLE
Integrating terminal in sublime

### ISSUE THREAD

**Issue by urvishjoshi** [sublimehq/sublime_merge#921]
Its been 32 years since sublime was found and I personally using sublime for 5 years, and it been great working on this awesome editor.

But there's a limitation like Terminal command typing interface like another editor VS code integrated, it will be perfect if developers add a terminal to sublime so that we don't have to frequently switch over two windows...

Hope this is a serious issue here and I have been waiting since long thinking it will be added in next update but no news I see as in of now.

**Comment by stinos** [comment]
> using sublime

You have created an issue in the issue tracker for `Sublime Merge` but your description sounds like you wanted `Sublime Text`. Which already has plugins for integrating a terminal (e.g [Terminus](https://packagecontrol.io/packages/Terminus)). So this can be closed probably.

**Comment by urvishjoshi** [comment]
Oh.. my focus was on the body, didn't saw at head.. lol

**Comment by srbs** [comment]
@urvishjoshi, please close this issue and create in [sublime_text](https://github.com/sublimehq/sublime_text/issues) if needed
