### ISSUE TITLE
"Hardware Accelaration" is listed twice in Preferences.

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#926]
**Version info**

 - OS: Windows 10
 - Build: 2034

**Description**

The "Hardware Accelaration" is listed twice in Preferences.

**Expected behavior**

One should be enough.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/16542113/94277779-52cc3980-ff4a-11ea-9b89-182434197b2e.png)

**Comment by kpowick** [comment]
This exists as well on macOS.

<img width="702" alt="Screen Shot 2020-09-25 at 12 31 02" src="https://user-images.githubusercontent.com/1646753/94293454-4507bb80-ff2c-11ea-8f9a-30176c297e51.png">

**Comment by dpjohnst** [comment]
Hi all,

Thank you for reporting this issue - this will be fixed in the next build of Sublime Merge.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @deathaxe ,

This has been resolved in Sublime Merge Build 2035.

Thanks,
- Dylan
