### ISSUE TITLE
Commit dialog tabs do not match displayed diff

### ISSUE THREAD

**Issue by istudyatuni** [sublimehq/sublime_merge#927]
**Version info**

 - OS: Manjaro, Release: 20.1 (info from `$ lsb_release -a`
 - Build: 2032

**Description**

(first, English is not my first lang)

When I watching changes for commit, and tap to mini tabs (for view single files), names on this tabs not equal really file's names. This behavior persist even after restart app

How can i help? may be some logs, or session file?

**Steps to reproduce**

oh, i don't know, how to reproduce it, maybe it my local bug, but i record a video

**Expected behavior**

file names displayed correctly

**Display capture**

[2020-09-25_18-43-58.zip](https://github.com/sublimehq/sublime_merge/files/5283890/2020-09-25_18-43-58.zip)

**Comment by istudyatuni** [comment]
After commit this behavior saves

**Comment by srbs** [comment]
Looks like the order of files in the tab bar is the same as the Summary (renames last), but the shown files is tree-alphabetical (renames inline).

**Comment by istudyatuni** [comment]
Hmm. Shown (no in tabs): package.json, HitSmall, MissSmall, Cell, Indicator, Ship, Shipsboard. No alphabetical

Tree-alphabetical - how files are shown in summary? Or not?

![screenshot](https://user-images.githubusercontent.com/43654815/94297183-c67f3e00-ff6c-11ea-91b8-d6f214ed7aae.png)

**Comment by dpjohnst** [comment]
Hi @istudyatuni,

Thank you for reporting this issue - I'll be investigating this and will reach out again when we have an update.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @istudyatuni,

Thanks for reporting this issue - it has been resolved in Sublime Merge Build 2035 (development build) and will be fixed in the next stable build.

Thanks,
\- Dylan

**Comment by dpjohnst** [comment]
Closing as this was fixed in Sublime Merge Build 2038 (stable)
