### ISSUE TITLE
[Diff] Symbol with SymbolTransformation ignored as diff context

### ISSUE THREAD

**Issue by TheClams** [sublimehq/sublime_merge#93]
**Version info**

 - OS: Windows 10
 - Build: 1069

**Description**

For each hunk there is a context indicator on the top left side giving the closest symbol. This is extremely useful but symbols defined with a SymbolTransformation are ignored

**Steps to reproduce**

1. Open repository https://github.com/sublimehq/Packages
2. Open file Markdown/syntax_test_markdown.md and remove one character line 10
3. In SublimeMerge no context indicator are available

**Expected behavior**

Expecting "Second Heading" to appears for this modification.

**Screenshots**

![symbol_transform](https://user-images.githubusercontent.com/5270125/46697825-d08bc300-cc15-11e8-8f04-bafd1e901842.png)

**Comment by jskinner** [comment]
Sublime Merge currently uses indexed symbols to lookup hunk descriptions, which means you need to set `showInIndexedSymbolList` to 1 and use `symbolIndexTransformation` over `symbolTransformation`.

I'm not sure that using the regular symbols would result in high quality output: a lot default packages transform symbols in a manner that's only meaningful when shown as part of a list in Goto Symbol.

**Comment by TheClams** [comment]
Ok so this is not a bug, I miss-understood how the feature works ;)

I think using symbol instead of indexedSymbol (whether you use the transformed one or not) would improve quite a lot the result: in general most non-indexed symbol are not indexed because they are not relevant globally, but locally they help navigates in the code (I think the markdown I used in the example shows that quite well with headings), and so would also help when you looking at the diff. 
But here it is mostly a design choice more than anything else ;)
