### ISSUE TITLE
Left Border Drawn on Condensed Refs

### ISSUE THREAD

**Issue by wbond** [sublimehq/sublime_merge#934]
**Version info**

 - OS: macOS 10.15.7
 - Build: 2034

**Description**

Condensed ref names in the commit list get a left border drawn, whereas fully expanded refs don't. I think that condensed ones shouldn't.

**Steps to reproduce**

1. Open a repository where a commit has multiple refs, such as a local branch name and remote branch name
2. Shrink the width of the commit list until the remote ref is condensed

**Expected behavior**

Only the left-most ref should have a colored border.

**Screenshots**

<img width="369" alt="Screen Shot 2020-09-28 at 8 32 35 PM" src="https://user-images.githubusercontent.com/41734/94499390-90d79080-01ca-11eb-95fb-4574108bb351.png">

**Comment by dpjohnst** [comment]
Hey Will, thanks for the feedback!

The reason I added this was that I wanted a way to differentiate between condensed refs and a regular ref (i.e. a branch called `1` vs the condensed ref count). To do that, I kept the left border on condensed refs as I thought it actually looked quite nice.

That being said, I'm open to changing this if people don't like it.

**Comment by dpjohnst** [comment]
Hey Will,

As you know, this has been resolved in Sublime Merge Build 2035.

Cheers,
\- Dylan
