### ISSUE TITLE
File diff viewer stuck on "Loading"/Application Not Responding

### ISSUE THREAD

**Issue by bamse16** [sublimehq/sublime_merge#935]
**Version info**

 - OS: macOS 10.15.7
 - Build: 2032

**Description**

The file diff viewer (the panel where you can discard/stage hunks) gets stuck on "loading" showing the "mastercard" animation (those two dots animating).

**Steps to reproduce**

In one of the node.js repositories, I edit some code (make some changes), then run `npm run build`. After the `npm run build` script completes, I see a list of modified files (with the M icon), but I can't see what's changed in each of them (to stage/discard hunk). macOS's "Activity Monitor" shows the app as using 100% CPU.

`npm run build`, deletes some node.js files, then creates them again (TypeScript compile phase). The app correctly shows which files were deleted (M and that trash can icon), but you can't see what changed. Also, selecting any previous commit, you can see what files were changed, but you can't expand individual files.

The app does not respond to "Quit". The only way to get it to work again is to "Force Quit" (from Activity Monitor) and restart it.

**Expected behavior**

The "discard/stage (hunk)" panel should be available and show the correct info (for staged files and for previous commits).

**Screenshots**

Attached "Loading images" and [spindump.txt](https://github.com/sublimehq/sublime_merge/files/5296681/spindump.txt) (from Activity Monitor).

<img width="689" alt="mastercard-1" src="https://user-images.githubusercontent.com/147856/94517318-072bcf80-026b-11eb-9ac2-560d7d997e7a.png">
<img width="647" alt="mastercard-2" src="https://user-images.githubusercontent.com/147856/94517322-08f59300-026b-11eb-95f3-3f8b1a3d4b3f.png">

**Comment by srbs** [comment]
Likely duplicate of #917 which appears fixed in dev build 2034. Presumably this line indicates the fix:
> Syntax Definitions: fixed infinite loop bug

**Comment by bamse16** [comment]
I confirm it seems fixed in 2034. Thank you!
