### ISSUE TITLE
Spacing between commit tree and labels sometimes too big

### ISSUE THREAD

**Issue by deathaxe** [sublimehq/sublime_merge#940]
**Version info**

 - OS: Windows 10 x64 2004
 - Build: 2034

**Description**

Every here and then I see commit labels not having correct distance to the commit tree. It looks like SM thinks there is still another branch line to be rendered. I am not quite sure when this exactly happens, but the last time I saw that was after rebasing - especially squashing two selected commits which required some conflicts to be resolved during rebasing.

There may be other triggers, too.

**Steps to reproduce**

1. Open a repository
2. Create a simple commit
3. Select this and an older commit
4. Call _Edit Commit / Squash Selected Commits ignoring Commit Messages
5. Manually resolve conflicts during rebasing.

**Expected behavior**

Commit labels should always have correct distance to commit tree lines.

**Screenshots**

State directly after rebasing:

![grafik](https://user-images.githubusercontent.com/16542113/94988841-74dc4200-0570-11eb-87c4-e75b246c8fde.png)

State after restarting SM:

![grafik](https://user-images.githubusercontent.com/16542113/94988851-87567b80-0570-11eb-903a-e5713636f56e.png)

**Comment by dpjohnst** [comment]
Hi @deathaxe,

Thanks for reporting this issue - it has been resolved in Sublime Merge Build 2035.

I'm going to go ahead and close this issue, but please feel free to re-open if you experience the issue again.

Thanks,
\- Dylan

**Comment by deathaxe** [comment]
> I'm going to go ahead and close this issue

Thats a good strategy to see/track progress and the build when an issue is resolved.
