### ISSUE TITLE
Show file changes of a commit as a tree

### ISSUE THREAD

**Issue by FichteFoll** [sublimehq/sublime_merge#949]
**Problem description**

Having long file paths in a repostiory makes the "Files" tab ("Changes" mode) unusable for review, as none of the paths will be readable and everything is an unclear mess of letters.
The "Tree" mode only shows all files in the repository and isn't useful to me at all for this repository.

**Preferred solution**

Show files changed as a tree, ideally with collapsed folders if they only have a single child folder, as is done in Java.
A description of what changes should be made to Sublime Merge to solve the problem.
Following is a screenshot of the Bitbucket pull request review view, which is significantly easier to navigate.

![2020-10-08_14-16-29](https://user-images.githubusercontent.com/931051/95457396-1f89a180-0971-11eb-8b05-c100bc86d8cc.png)

**Alternatives**

Since this may be redundant for small repositories, although there will be plenty of vertical space to be used in that case, the current behavior could remain as a switch. I initially assumed clicking on "Tree" would show me the file tree of the files in that project, but that was obviously not the case. I even knew that a while ago, but it appears I quickly forgot and still ended up wondering why the tree view contained so many files.

**Screenshots**

![2020-10-08_14-13-47](https://user-images.githubusercontent.com/931051/95457046-95d9d400-0970-11eb-919c-f245ca1f6d31.png)

**Comment by srbs** [comment]
duplicate of #689, #418 
see also #461

**Comment by FichteFoll** [comment]
Diferent although strongly related to #689, which I found, but does seem like a duplicate of #418.

**Comment by srbs** [comment]
Good point, I probably just copied them backwards.
