### ISSUE TITLE
Not all possible system gitconfig paths are checked on Windows

### ISSUE THREAD

**Issue by nikopere** [sublimehq/sublime_merge#951]
**Version info**

 - OS: Windows 10
 - Build: 2035

**Description**

When I get debug information it has the following:
```
=== Our Config Information ===
Git Config Path Information
Using config path: /C/ProgramData/Git/config
Using config path: /C/Program Files/Git/mingw64/etc/gitconfig
Using config path: /C/Users/<user_name>/.config/git/config
Using config path: /C/Users/<user_name>/.gitconfig
Using config path: /C/<project_path>/.git/config
```
Problem is that there's no file `/C/Program Files/Git/mingw64/etc/gitconfig` but there is file `/C/Program Files/Git/etc/gitconfig`.
I believe when you install Git for Windows, depending on the options you choose during install, `gitconfig` file could be placed on the latter path, which is what happened to me.

This is the output of `git config --system -l --show-origin` command:
```
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=input
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=true
file:C:/Program Files/Git/etc/gitconfig pull.ff=only
```

**Steps to reproduce**

1. Install Sublime Merge on Windows
2. Install Git for Windows
3. Choose external git binary in Sublime Merge settings `C:\Program Files\Git\cmd\git.exe`
4. Run Help -> Debug Information

**Expected behavior**

`/C/Program Files/Git/etc/gitconfig` should also be read

**Comment by dpjohnst** [comment]
Hi @nikopere,

Thank you for reporting this issue - I'll be investigating this further and will provide an update shortly.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi @nikopere,

This issue has been resolved in Sublime Merge Build 2036.

Kind regards,
\- Dylan
