### ISSUE TITLE
Sublime merge freeze after update to build 2035

### ISSUE THREAD

**Issue by matteosist** [sublimehq/sublime_merge#952]
**Version info**

 - OS: macOS 10.15.7 (19H2)
 - Build: 2035

**Description**
After update every action cause a freeze of application

Here the report

[Sublime merge issue.txt](https://github.com/sublimehq/sublime_merge/files/5363996/Sublime.merge.issue.txt)

**Comment by dpjohnst** [comment]
Hi @matteosist,

Thank you for reporting this issue. Could you clarify what you mean by every action? Does it freeze when you perform a Git operation, or simply opening Sublime Merge?

Additionally, does the freeze occur when opening Sublime Merge in safe mode? (`smerge --safe-mode`).

Thanks,
\- Dylan

**Comment by mseagrief** [comment]
+1 here - although under Windows 10. 

What I've seen:

- On startup I can get into the menus / change options.
- Sometimes I can switch tabs
- Clicking on commits freezes almost all times
- Occasionally one or two commits can be viewed before the interfaces freezes.

Starting in safe mode appears to be fine.

Is a memory dump from Visual Studio any use?

**Comment by dpjohnst** [comment]
Hi all,

Thanks for the additional information. Are either of you using OpenGL hardware rendering (enabled by default on MacOS)? If so, could you try disabling it via `Preferences > Preferences... > Advanced`.

If you cannot access the preferences menu, you can manually edit the settings file located in the Sublime Merge User directory (`~/Library/Application Support/Sublime Merge/Packages/User` for MacOS and `%APPDATA%\Sublime Merge/Packages/User` for Windows). 

Thanks,
\- Dylan

**Comment by matteosist** [comment]
Hi Dylan, thanks for quick reply.

The issue still present also starting sublime merge in safe mode or with OpenGL disabled.

Below the reports for both cases

[Sublime merge issue with OpenGL disabled.txt](https://github.com/sublimehq/sublime_merge/files/5364454/Sublime.merge.issue.with.OpenGL.disabled.txt)
[Sublime merge issue with safe mode.txt](https://github.com/sublimehq/sublime_merge/files/5364455/Sublime.merge.issue.with.safe.mode.txt)

**Comment by dpjohnst** [comment]
Hi all,

Thank you for your patience while we investigate this. In the meantime, feel free to revert back to build 2034 (https://download.sublimetext.com/sublime_merge_build_2034_mac.zip for MacOS and https://download.sublimetext.com/sublime_merge_build_2034_x64_setup.exe for Windows).

I'll provide a further update shortly.

Thanks,
\- Dylan

**Comment by mseagrief** [comment]
Same here with Windows 10 the freeze is present with and without hardware acceleration.

> In the meantime, feel free to revert back to build 2034

Will do, thanks.

**Comment by dpjohnst** [comment]
Hi all,

A quick update - we've identified the issue and have resolved it. I will reach out again once the fix has been released.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Hi all,

Thank you for your patience.

This was fixed in Sublime Merge Build 2036, which has just been released.
Could you confirm that the issue is resolved on your side?

Thanks,
\- Dylan

**Comment by jnns** [comment]
Thank you very much @dpjohnst for fixing and thanks to @matteosist for reporting it. 

After updating yesterday, I was only experiencing this issue this morning, and thanks to you all I can already install an update. :heart:

**Comment by mseagrief** [comment]
Yup, all fixed! Awesome work 👍

**Comment by matteosist** [comment]
Fixed also for me. Many thanks @dpjohnst.
