### ISSUE TITLE
Sublime_text 4088 Unable to load gdk_wayland_display_get_type from libgdk-3.0.so

### ISSUE THREAD

**Issue by CheyenneWills** [sublimehq/sublime_merge#953]
**Version info**

 - OS: Linux - Gentoo (maintained at current levels)
 - Build Dev build 4088

**Description**

On a gentoo system with the default setup for the gtk+ package am receiving the following when starting sublime_text 
    Unable to load gdk_wayland_display_get_type from libgdk-3.0.so

This appears to be a change in library dependencies from previous versions of Sublime_text 

I was able to resolve the problem by rebuilding x11-libs/gtk+ with wayland enabled (though wayland support is off by default on gentoo sytems).

Either document that sublime_text requires wayland support in gtk+ or update sublime_text to handle the detection wayland in a fashion that does not fail. 

**Steps to reproduce**

1. - gentoo system with gtk+ built without the wayland USE setting (e.g: in /etc/portage/package.use have an entry for: x11-libs/gtk+ -wayland)
2. Install sublime_text 4088
3. sublime_text
4. Fails immediately with: Unable to load gdk_wayland_display_get_type from libgdk-3.0.so

**Comment by srbs** [comment]
This is the Sublime Merge issue tracker, please recreate this issue in the Sublime Text [issue tracker](https://github.com/sublimehq/sublime_text/issues) & close this one.

**Comment by CheyenneWills** [comment]
> This is the Sublime Merge issue tracker, please recreate this issue in the Sublime Text [issue tracker](https://github.com/sublimehq/sublime_text/issues) & close this one.

Woops.. sorry about that.  Opened #3692 over in sublime-text

**Comment by CheyenneWills** [comment]
Just removed the wayland support options to test the latest sublime_text with the fix for this, but now sublime_merge is failing with the same error.
