### ISSUE TITLE
Very frequent beachballs on macOS

### ISSUE THREAD

**Issue by btisdall** [sublimehq/sublime_merge#955]
**Version info**

 - OS: MacOS Catalina 10.15.6 (19G2021)
 - Build: Dev channel, 2036 (also tried with stable version as at 2020-10-15)

**Description**

Clicking on a sidebar item frequently makes the application unresponsive for 30 seconds or more.

**Steps to reproduce**

1. Open repository
2. Click on an item in the sidebar such as a branch (local or remote) or a tag. It may be necessary to repeat this once or twice.
3. The macOS beachball appears and the application is unusable for 30s or more.

**Expected behavior**

Nothing, beyond the selection of the item.

**Notes**

Repo contains 131 files totalling ~6MB. I could *not* reproduce the issue with a clone of git@github.com:kubernetes/kubernetes.git which is orders of magnitude larger.

Here's the output from the `git-sizer` tool run on the problematic repo:

```
▶ git-sizer -v
Processing blobs: 1359
Processing trees: 1491
Processing commits: 288
Matching commits to trees: 288
Processing annotated tags: 78
Processing references: 84
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Overall repository size      |           |                                |
| * Commits                    |           |                                |
|   * Count                    |   288     |                                |
|   * Total size               |   169 KiB |                                |
| * Trees                      |           |                                |
|   * Count                    |  1.49 k   |                                |
|   * Total size               |   404 KiB |                                |
|   * Total tree entries       |  10.9 k   |                                |
| * Blobs                      |           |                                |
|   * Count                    |  1.36 k   |                                |
|   * Total size               |  44.0 MiB |                                |
| * Annotated tags             |           |                                |
|   * Count                    |    78     |                                |
| * References                 |           |                                |
|   * Count                    |    84     |                                |
|                              |           |                                |
| Biggest objects              |           |                                |
| * Commits                    |           |                                |
|   * Maximum size         [1] |  1.71 KiB |                                |
|   * Maximum parents      [2] |     2     |                                |
| * Trees                      |           |                                |
|   * Maximum entries      [3] |    20     |                                |
| * Blobs                      |           |                                |
|   * Maximum size         [4] |  2.21 MiB |                                |
|                              |           |                                |
| History structure            |           |                                |
| * Maximum history depth      |   285     |                                |
| * Maximum tag depth      [5] |     1     |                                |
|                              |           |                                |
| Biggest checkouts            |           |                                |
| * Number of directories  [6] |    40     |                                |
| * Maximum path depth     [6] |     5     |                                |
| * Maximum path length    [6] |    86 B   |                                |
| * Number of files        [6] |   117     |                                |
| * Total size of files    [7] |  5.11 MiB |                                |
| * Number of symlinks         |     0     |                                |
| * Number of submodules       |     0     |                                |

[1]  44066ac90e9f9eebc7c331e54980a0d2a00ff2f0
[2]  852ecf0fb5438e7643cf6e798b13c6289abc80b8 (refs/stash)
[3]  4ba00afcf983a0a6057eca746d99601e1c85facd (62fe36b0ebc2d258b1e7839ad0c37049e188bdfc^{tree})
[4]  73751aeca376b6f13f3cb1c48b0f21d102ef8aee (59447337d26696dc900725c50fbc0fe988d14137:src/test/data/voi-vehicles.1.json)
[5]  b67e3b38b80efa95e16096b44f98859d60b4563f (refs/tags/deploy-PROD-1-2018-11-05T09.19.02Z)
[6]  d34dfd0754566794a2a94e98404ce70744a9c2a7 (refs/heads/MSI-438-qr-codes^{tree})
[7]  bbb1d33b494b4ec398fae8b4d38a79fe1de45717 (59447337d26696dc900725c50fbc0fe988d14137^{tree})
```

**Comment by btisdall** [comment]
[sublime_merge_2020-10-15-122608_karla.cpu_resource.diag.txt](https://github.com/sublimehq/sublime_merge/files/5384433/sublime_merge_2020-10-15-122608_karla.cpu_resource.diag.txt)

**Comment by dpjohnst** [comment]
Hi @btisdall,

Thank you for the additional information - when you get a chance, would you also mind sharing the debug information from Sublime Merge? This can be found under `Help > Debug Information`

Once copied to clipboard, please take a moment to strip it of any data you feel is sensitive (paths, user.email config etc).

It would be great if you could also share the common file types in the repository (i.e. if it's mainly c++ files, or javascript files etc)

Thanks,
\- Dylan

**Comment by btisdall** [comment]
Hi Dylan!

[debug.txt](https://github.com/sublimehq/sublime_merge/files/5389680/debug.txt)

This is a typescript project with 75/117 files being `.ts`, the rest all JSON or other text files too. I tried the following things to see if it made any difference:

- Blowing away all complied files and `node_modules/`
- Not having the repo open in VS Code at the same time.

Problem still occurred.

**Comment by dpjohnst** [comment]
Hi @btisdall,

Thank you for the additional information - I haven't had any success replicating the issue so far unfortunately. When you have a chance, could you check the following:

* Does disabling OpenGL Hardware Acceleration solve the issue (you can disable this via Preferences > Preferences... > Advanced)?
* Is it correct that you've tried `smerge --safe-mode` without success?
* Would you be able to list any Sublime Text packages installed on your machine (just to rule out external packages potentially interfering)

Thanks for your help,
\- Dylan

**Comment by btisdall** [comment]
Hi @dpjohnst.

* I can't recall if I tried disabling OpenGL Hardware Acceleration so will get back to you tomorrow when I have access to the computer in question again.
* I have never tried Sublime Text on the machine.
* I have tried safe mode to no avail.
* One other piece of information I can share now is if I blow away the `.git` folder then reinitialize the repo the problem goes away which does suggest there's something unusual with the internals. That said, I've evaluated many other git clients and none seemed to have a problem with the repo.

**Comment by btisdall** [comment]
I'm no longer able to reproduce this with the latest version. I'm not certain it was this change that fixed things but I think this ticket can be closed now.

**Comment by dpjohnst** [comment]
Hi @btisdall,

Thanks for letting me know - that's great news.
If it does pop up again please feel free to reopen this issue!

Kind regards,
\- Dylan

**Comment by btisdall** [comment]
Thanks for all your help @dpjohnst !
