### ISSUE TITLE
[GTK] Open Repository is broken on Linux

### ISSUE THREAD

**Issue by ratijas** [sublimehq/sublime_merge#956]
**Version info**

 - OS: Arch Linux
 - gtk2: 2.24.32-2
 - gtk: 1:3.24.23-4
 - Build: 2032

**Description**

Open Repository doesn't let me select existing directory by entering its full path into the Location field.

**Steps to reproduce**

1. New Tab.
2. Click 'Open repository' either as a button or a File menu. Doesn't matter.
3. Standard 'Select Folder' panel appears, showing 'Recent' items by default.
3. Enter "Ctrl+L" shortcut to reveal the Location field (for some reason is it hidden there).
4. Type or paste the full path to any of your cloned repositories.

**Expected behavior**

At this point, user should be able to press 'Enter' key or 'Open' button to actually open a repository in Sublime Merge.

**Actual behavior**

Pressing Enter key seems to have no effect. 'Open' button at the bottom right is also disabled.

**Screenshots**

![Select Folder panel](https://user-images.githubusercontent.com/6737986/96371895-c5f15600-116c-11eb-82c2-626584add54c.png)
It may not seem like it, but the 'Recent' location is active at this screenshot.

**Additional information**

It seems like it only ever happens on at the 'Recent' location. It might as well be a bug in GTK or whatever is responsible for that system panel.

Naturally, the workaround is to switch to any other Location (e.g. Home, Desktop, Documents etc.) before entering the path and clicking 'Open'. But that kinda defeats the purpose of "Ctrl+L", i.e. avoid using keyboard as much as possible.

**Comment by dpjohnst** [comment]
Hi @ratijas,

Thank you for reporting this issue - this is indeed a bug with the system file/folder picker, for which we unfortunately don't have any control over. I suggest submitting a bug report to the relevant maintainers. 

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
Note: I believe the best place to submit the bug report would be [here](https://gitlab.gnome.org/GNOME/gtk/)

**Comment by ratijas** [comment]
Hi @dpjohnst,

Thanks for your reply.  Yeah, most likely, that's the case. I moved the issue there: https://gitlab.gnome.org/GNOME/gtk/-/issues/3277.
