### ISSUE TITLE
sublime_merge 2036 fails without wayland support in gtk+

### ISSUE THREAD

**Issue by CheyenneWills** [sublimehq/sublime_merge#957]
Version info

OS: Linux - Gentoo (maintained at current levels)
Build Dev build 2036
Description

On a gentoo system with the default setup for the gtk+ package am receiving the following when starting sublime_merge
Unable to load gdk_wayland_display_get_type from libgdk-3.0.so

This appears to be a change in library dependencies from previous versions of Sublime_merge

I was able to resolve the problem by rebuilding x11-libs/gtk+ with wayland enabled (though wayland support is off by default on gentoo sytems).

This problem was also present in sublime_text and was just fixed in sublime_text w/build 4089.

Steps to reproduce

gentoo system with gtk+ built without the wayland USE setting (e.g: in /etc/portage/package.use have an entry for: x11-libs/gtk+ -wayland)
Install sublime_merge 2036
sublime_merge
Fails immediately with: Unable to load gdk_wayland_display_get_type from libgdk-3.0.so

**Comment by step-** [comment]
relevant sublime_text issue https://github.com/sublimehq/sublime_text/issues/3692

**Comment by dpjohnst** [comment]
This should be resolved in Sublime Merge Build 2037/2038.

Closing, but please don't hesistate to re-open the issue if the problem persists.

**Comment by CheyenneWills** [comment]
The problem has been resolved.  Thank you.
