### ISSUE TITLE
Copy Branch Name option

### ISSUE THREAD

**Issue by rajohns08** [sublimehq/sublime_merge#96]
I love this feature in [Fork](https://git-fork.com/):

![screen shot 2018-10-09 at 9 40 23 pm](https://user-images.githubusercontent.com/2711642/46710064-f9a75600-cc0b-11e8-9601-f0da3e46a403.png)

It simply copies the name of the branch to clipboard for easy pasting.

**Comment by jskinner** [comment]
This is in the recently release build 1070 btw
