### ISSUE TITLE
Can't view full file path 

### ISSUE THREAD

**Issue by respel** [sublimehq/sublime_merge#963]
**Version info**

 - OS: 10.15.7
 - Build: 2032

**Description**

If the file path is too long, we cannot see the full file path in the "Summary" window.

**Steps to reproduce**

Choose a long enough file path and you should be able to see what I'm talking about.

**Expected behaviour**

We should be able to access the full file path in some way. Either it should be wrapped if too long, or be viewable on hover or able to be copied.

**Screenshots**

![image](https://user-images.githubusercontent.com/30291673/97339264-a6e87780-1882-11eb-9df1-e58fb3d239ae.png)

**Comment by srbs** [comment]
Workaround: you can use the `Copy File Path` block seen here: https://github.com/sublimehq/sublime_merge/issues/178#issuecomment-433111449

**Comment by respel** [comment]
Thanks for the workaround @srbs. However, viewing the paths in case of a file rename would still be an issue.

**Comment by srbs** [comment]
@respel, how about this for a workaround, these commands will print out log details for a given commit/commit+path into the git console log which can then be viewed & copied from at will.

In `File.sublime-menu` (& `Diff Context.sublime-menu` if wanted):
```
[
    {
        "caption": "Show File Commit Info…",
        "command": "git",
        "args": {"argv": ["log", "--stat=2000", "-1", "$commit", "--", "$path"]}
    }
]
```

In `Commit.sublime-menu`:
```
[
    {
        "caption": "Show Commit Info…",
        "command": "git",
        "args": {"argv": ["log", "--stat=2000", "-1", "$commit"]}
    }
]
```

**Comment by respel** [comment]
@srbs Seems like a good temporary solution. Thanks for that. 
Personally, I would just switch to another git client for times when I need to access the path.

**Comment by srbs** [comment]
@respel I agree that it needs to be fixed. However, I do enjoy trying to find workarounds for others and usually keep the solutions for my own use as well.

**Comment by dpjohnst** [comment]
This was fixed in Sublime Merge development build 2041, and will also be fixed in the next stable build.

**Comment by dpjohnst** [comment]
Hi all,

Just following up that this is now resolved in the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan
