### ISSUE TITLE
Status popup after successful Push never goes away

### ISSUE THREAD

**Issue by retifrav** [sublimehq/sublime_merge#965]
**Version info**

 - OS: Windows 10.0.18363.1139
 - Build: 2032

**Description**

When Push operation is finished with success, it shows a status popup. Sometimes this popup never goes away and there is no way to get rid of it other than restart the application.

The popup is visible even if you switch to another tab/repository.

Might be related to #871.

**Steps to reproduce**

1. Push some commit to a remote repository
2. Status popup appears and never goes away

It does not reproduce always, just happens sometimes.

**Expected behavior**

Status popup should auto-close after a while or close on-click.

**Screenshots**

![popup](https://user-images.githubusercontent.com/6904927/97592232-b55c9d80-1a00-11eb-8843-fdb96ff61874.png)

**Comment by srbs** [comment]
Does clicking on the `>✓` to the left of the branch name work?

**Comment by retifrav** [comment]
It shows the commands history, but popup doesn't go away still.

**Comment by dpjohnst** [comment]
Hi @retifrav,

Thank you for reporting this issue.

Rest assured we're definitely looking for the source of this issue (as I've seen this issue before too). We'll have a fix as soon as possible, and I'll comment on here when we have an update to share.

Kind regards,
\- Dylan

**Comment by retifrav** [comment]
Not complaining or anything like that, just wanted to let you know: the issue is still present in the latest **2049** build:

![ss-1](https://user-images.githubusercontent.com/6904927/110922235-bd6a0980-831f-11eb-8834-17ebd24e1f64.png)

Also (*not sure if it's useful*) I've noticed that if I resize SM window, the popup fails to calculate(?) its position correctly and ends up like this:

![ss-2](https://user-images.githubusercontent.com/6904927/110922249-c0fd9080-831f-11eb-9072-5cad90fc4613.png)

**Comment by srbs** [comment]
@dpjohnst, see #1111 for (hopefully) the full behavior & reproduction steps.

**Comment by srbs** [comment]
@retifrav, this should be fixed in dev build 2051 or stable build 2054.

**Comment by dpjohnst** [comment]
Hi @retifrav,

As @srbs mentioned (thanks!), we've addressed this in the latest builds.

Let me know if this has been resolved on your end, and I can go ahead and close the issue.

Thanks,
\- Dylan

**Comment by retifrav** [comment]
Yeah, I've read about it in the changelog yesterday, awesome!

But as this problem was occurring randomly and rather rarely, I can't confirm it being solved right away. So I think we can just close the issue, and then if I get it re-appearing some time later, I'll report it here.

**Comment by retifrav** [comment]
I've never had hanging status popup ever again, but today I've got a similar issue with confirmation tooltip. I was aborting a cherry-pick operation and got this tooltip to click again to confirm the operation, but then this tooltip never disappeared:

![tooltip-1](https://user-images.githubusercontent.com/6904927/120460554-842ebc00-c399-11eb-9ba0-8bc87ea50357.png)

It also behaves similar to #982 - if I make Sublime Merge window smaller and move it somewhere, then the tooltip remains visible outside the window area:

![tooltip-2](https://user-images.githubusercontent.com/6904927/120460572-8a249d00-c399-11eb-89f3-ccc295df36b1.png)

That is with version 2056.

Would you say this is still related to this issue, or should I create a new one?

**Comment by srbs** [comment]
@retifrav, probably a new issue, but I think #1180 might cover your issue
