### ISSUE TITLE
Ctrl+Enter without staged files behaves unexpectedly

### ISSUE THREAD

**Issue by fschoenm** [sublimehq/sublime_merge#97]
**Version info**

 - OS: Windows 10
 - Build: 1070

**Description**

If no files are staged, pressing Ctrl+Enter in the commit message field adds a newline.

**Steps to reproduce**

1. Open repository ...
2. Run command ...
3. Click on ...

**Expected behavior**

Ctrl+Enter should not behave differently if no files are staged. Instead, there could be a warning what is wrong.

**Comment by dae** [comment]
I have a related suggestion - in the nothing-staged case, how about automatically staging everything ala 'commit -a' instead? Combined with focusing in the commit area by default, this would make it easier to quickly review and commit small changes to a branch, and if the user does it accidentally it's easy to revert to the previous head.

**Comment by javaJake** [comment]
I disagree that Ctrl+Enter should trigger the same action as Ctrl+Shift+A. That means that the meaning of Ctrl+Enter is as unclear as it is now, as it could do one of two things.

Ctrl+Enter should do exactly one thing, and I think that is ultimately what this bug is about.

**Comment by dpjohnst** [comment]
Hi all,

Closing as Ctrl+Enter no longer adds a newline when no files are staged.

Kind regards,
\- Dylan
