### ISSUE TITLE
sublimehq.com is not loading CSS

### ISSUE THREAD

**Issue by feed4rz** [sublimehq/sublime_merge#972]
**Version info**

Any browser, macOS 10.15.7

Headers:
Referer: https://www.sublimehq.com/
sec-ch-ua: "Chromium";v="86", "\"Not\\A;Brand";v="99", "Google Chrome";v="86"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

**Description**

The website does not load stylesheet.

**Steps to reproduce**

Not sure how to properly reproduce it.

My first guess it was maybe the location I was requesting from (Russia), so I tried using VPN but it still did not work.

**Expected behavior**

I expect the website to load the stylesheet.

**Screenshots**

![image](https://user-images.githubusercontent.com/13008534/97878122-3d0f1880-1d2f-11eb-93d7-bc466149a650.png)

![image](https://user-images.githubusercontent.com/13008534/97878596-df2f0080-1d2f-11eb-9bb1-10c995cf0240.png)

![image](https://user-images.githubusercontent.com/13008534/97878066-2c5ea280-1d2f-11eb-89c4-ddd5fe8fdd9d.png)

**traceroute**

Thought it might be useful to provide traceroute to sublimehq.com:
```sh
traceroute to sublimehq.com (45.55.41.223), 64 hops max, 52 byte packets
 1  192.168.1.1 (192.168.1.1)  2.600 ms  1.106 ms  0.897 ms
 2  212.119.208.121 (212.119.208.121)  2.321 ms  3.239 ms  2.395 ms
 3  mx01.frankfurt.gldn.net (79.104.235.74)  46.875 ms
    mx01.frankfurt.gldn.net (79.104.235.66)  82.699 ms
    mx01.frankfurt.gldn.net (79.104.235.74)  44.236 ms
 4  nyc2edge1.digitalocean.com (206.82.104.9)  120.981 ms  116.679 ms  120.279 ms
 5  138.197.244.35 (138.197.244.35)  121.174 ms  120.941 ms  116.782 ms
 6  * * *
 7  * * *
 8  45.55.41.223 (45.55.41.223)  125.006 ms  119.526 ms  120.038 ms
```

**Comment by dpjohnst** [comment]
Hi @feed4rz,

Thank you for reaching out.

Do you have any ad blockers installed? If so, it's likely the case that you have an overexcited ad blocker.
The stylesheet is shared between domains, and thus some ad blockers can end up blocking it.

Kind regards,
\- Dylan

**Comment by dpjohnst** [comment]
CC'ing you in @wbond

**Comment by feed4rz** [comment]
> Hi @feed4rz,
> 
> Thank you for reaching out.
> 
> Do you have any ad blockers installed? If so, it's likely the case that you have an overexcited ad blocker.
> The stylesheet is shared between domains, and thus some ad blockers can end up blocking it.
> 
> Kind regards,
> - Dylan

I do have Adblock and DuckDuckGo extensions installed, I tried disabling both of them and it didnt help.

**Comment by dpjohnst** [comment]
Hi @feed4rz,

Thank you for the additional information!

Could you try running the following from the command line and share the output?

* `curl https://www.sublimehq.com/`
* `curl https://www.sublimetext.com/sublime_v3.css`

Thanks,
\- Dylan

**Comment by feed4rz** [comment]
> Hi @feed4rz,
> 
> Thank you for the additional information!
> 
> Could you try running the following from the command line and share the output?
> 
> * `curl https://www.sublimehq.com/`
> * `curl https://www.sublimetext.com/sublime_v3.css`
> 
> Thanks,
> - Dylan

```sh
<!doctype html>
<html class="hq">
<head>
    <title>Sublime HQ - Remarkable Software</title>
    <link rel="stylesheet" type="text/css" href="https://www.sublimetext.com/sublime_v3.css?d=200310">
    <link rel="stylesheet" type="text/css" href="/store/store.css">
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=yes">
</head>
<body > 
        <header>
        <section>
            <a id="logo" href="/">
                <img src="/images/logo.svg" alt="Sublime HQ">
            </a>

            <nav>
                <a href="/">Products</a>
                <a href="/buy">Buy</a>
                <span class="vr"></span>
                <a href="https://www.sublimetext.com/blog/">News</a>
                <a href="https://forum.sublimetext.com/">Forum</a>
            </nav>
        </section>
    </header>

    <main>
        <div id="masthead">
            <section>
                <div class="tagline">
                    <span>We produce remarkable software</span>
                </div>

                <div class="product_icons">
                    <a href="https://www.sublimetext.com">
                        <img src="/images/sublime_text.png" alt="Sublime Text" title="Sublime Text">
                        <span>Sublime Text</span>
                    </a>
                    <a href="https://www.sublimemerge.com">
                        <img src="/images/sublime_merge.png" alt="Sublime Merge" title="Sublime Merge">
                        <span>Sublime Merge</span>
                    </a>
                </div>
            </section>
        </div>
    </main>
    <footer>
        <section>
            © Sublime HQ Pty Ltd

            <p>Woollahra, Sydney.
        </section>
    </footer>
</body>
</html>
```

```sh
curl: (7) Failed to connect to www.sublimetext.com port 443: Connection refused
```

**Comment by dpjohnst** [comment]
Hi @feed4rz,

Thank you for the additional information.

Could you try running `ping www.sublimetext.com` from the terminal?

Thanks,
\- Dylan

**Comment by feed4rz** [comment]
> Hi @feed4rz,
> 
> Thank you for the additional information.
> 
> Could you try running `ping www.sublimetext.com` from the terminal?
> 
> Thanks,
> - Dylan

```sh
PING www.sublimetext.com (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.057 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.090 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.079 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.092 ms
64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.092 ms
64 bytes from 127.0.0.1: icmp_seq=5 ttl=64 time=0.108 ms
64 bytes from 127.0.0.1: icmp_seq=6 ttl=64 time=0.080 ms
64 bytes from 127.0.0.1: icmp_seq=7 ttl=64 time=0.092 ms
64 bytes from 127.0.0.1: icmp_seq=8 ttl=64 time=0.082 ms
64 bytes from 127.0.0.1: icmp_seq=9 ttl=64 time=0.096 ms
64 bytes from 127.0.0.1: icmp_seq=10 ttl=64 time=0.129 ms
^C
--- www.sublimetext.com ping statistics ---
11 packets transmitted, 11 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.057/0.091/0.129/0.017 ms
```

**Comment by dpjohnst** [comment]
Hi @feed4rz,

Thanks for the info.

It looks as if www.sublimetext.com has been mapped to an incorrect ip address locally.

I would suggest browsing your hosts file to check there isn't an override in place:
1. Open terminal and run `sudo subl /etc/hosts` (you can also replace subl with any editor of your choice such as `nano`)
2. Inspect the file for any www.sublimetext.com overrides
3. Remove the override and save the file

Kind regards,
\- Dylan

**Comment by feed4rz** [comment]
> Hi @feed4rz,
> 
> Thanks for the info.
> 
> It looks as if [www.sublimetext.com](http://www.sublimetext.com) has been mapped to an incorrect ip address locally.
> 
> I would suggest browsing your hosts file to check there isn't an override in place:
> 
> 1. Open terminal and run `sudo subl /etc/hosts` (you can also replace subl with any editor of your choice such as `nano`)
> 2. Inspect the file for any [www.sublimetext.com](http://www.sublimetext.com) overrides
> 3. Remove the override and save the file
> 
> Kind regards,
> - Dylan

My bad, closing the issue
