### ISSUE TITLE
commits not shown

### ISSUE THREAD

**Issue by br4nnigan** [sublimehq/sublime_merge#974]
**Version info**

 - OS: Win 10
 - Build: 2037 (I've had this in an older version aswell)
 - the local repo is inside a wsl2 section, but I believe I've had this before

**Description**

Sometimes commits (of other authors) are not shown.

**Steps to reproduce**

I push a commit. 
a merge conflict arises, it is auto resolved
I push the merge
I inspect the commits pane, and it reads:

\<the merge commit>
\<my commit>
\<an older merge commit>
\<an older commit of mine>

What the hell did I merge my commit with?
I hit ctrl+f and search for the author of the commit that went into my merge and it shows up
I close the search view
and <ins>now the missing commit does show up</ins> in the commits pane before my commit

This is pretty damning

**Comment by dpjohnst** [comment]
Hi @br4nnigan,

This sounds like it could be the case of dangling commits. 

To confirm, could you run `git log --graph` to confirm whether the commits you are expecting to see are present in Git itself?

If not, you have a case of dangling commits (commits hidden due to no branches or refs pointing at them anymore) and we can look into resolving that.

Kind regards,
\- Dylan

**Comment by br4nnigan** [comment]
I will, the next time this happens.

**Comment by srbs** [comment]
@br4nnigan, is there an empty square on the left of the merge commit? If so, does clicking on it show your missing commits?

**Comment by br4nnigan** [comment]
@srbs @dpjohnst 

yes, clicking the empty square revealed the merged commits! Thanks!

What does this mean?

**Comment by srbs** [comment]
@br4nnigan, collapsing/expanding merge commits is one of the features of Sublime Merge (I think it's trying to minimize the amount of information shown). SM will preserve the expanded/collapsed commits in your session, and you can change the default state in the preferences: `General` -> `Merge Commit Display` -> `Expand by default`.
