### ISSUE TITLE
Fails to find make a signed commit (seems like it is unable to find the GPG binary)

### ISSUE THREAD

**Issue by davidbonnet** [sublimehq/sublime_merge#977]
**Version info**

 - OS: macOS 10.15.7 (19H15)
 - Build: 2038

**Description**

A description of what the bug is.

**Steps to reproduce**

1. Setup signed commits
2. Make some file changes
2. Commit
4. Error:
```
error: cannot run gpg: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
```

Also, all previously signed commits are marked as "invalid":
<img width="383" alt="image" src="https://user-images.githubusercontent.com/297345/98355976-30d2d600-2023-11eb-8f0c-e51ba93dd5a6.png">

**Expected behavior**

Note that it worked fine in a previous build, without making an OS upgrade.

* Previous validly signed commits are marked as valid
* Adding a commit does not error

**Comment by dpjohnst** [comment]
Hi @davidbonnet,

Thank you for reporting this issue. It does look like both Git and Sublime Merge are failing to find the gpg installation (the first error likely coming from Git itself and the Invalid label coming from Sublime Text).

Could you run the following command from your terminal and report the output:
`which gpg`

Kind regards,
\- Dylan

**Comment by davidbonnet** [comment]
@dpjohnst Result of `which gpg` gives: `/usr/local/bin/gpg`

Note that running `git commit -m "Message…"` in the terminal does what's expected (it adds a signed commit message). And Github correctly sees these commits as signed.

**Comment by davidbonnet** [comment]
This is quite a bummer and makes the whole app useless.

**Comment by dpjohnst** [comment]
Hi @davidbonnet,

Thank you for your reply - I've been investigating this issue but will need a few more things from you.

When you get a chance, would you mind sharing Sublime Merge's debug information (Found via `Help > Debug Information`).
Take a moment to strip it of any information you feel is sensitive (email, paths etc). In particular, I'd like to see the  Git Version Information`, `Git Config Information`, and `Our Config Information` sections.

Kind regards,
\- Dylan

**Comment by davidbonnet** [comment]
Thanks @dpjohnst for looking into this. Just upgraded to build 2039 and the problem vanished. Nothing in the changelog is mentioning that fix (closest is a macOS fix about batching long git commands). Apart from upgrading Sublime Merge, nothing changed in my system setup.

Unrelated: would be great if we could select and copy/paste excerpts from the release notes.

**Comment by dpjohnst** [comment]
Hi @davidbonnet,

Thanks great to hear - I'm truly baffled at what could have fixed this issue between 2038 and 2039, but I'm glad it's resolved!

Kind regards,
\- Dylan
