### ISSUE TITLE
Staging large numbers of untracked files fails without output

### ISSUE THREAD

**Issue by personalnadir** [sublimehq/sublime_merge#978]
**Version info**

 - OS: macOS 10.15.7
 - Build: 2038

**Description**

I have a project created with Unity that I would like to version control. After initialising the project Sublime Merge lists that it has 23368 untracked files. In order to use Git LFS I am using the system binary. Staging individual files works fine. Attempting to stage all of them fails and a message saying "git failed with exit code 1" pops up. The central command pane disappears (see screenshot).

Examining the command history shows that Sublime Merge seems to be generating a single command 1.9 million characters long. The command shows no output.

**Steps to reproduce**

1. Open repository with thousands of untracked files
2. Select Stage All by right clicking the Untracked Files header in the files pane

**Expected behavior**

Either a warning that a limit has been exceeded or the task to be broken up so that Sublime Merge can complete the task.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/559503/98392914-78bc2200-2050-11eb-97d3-8bd92a7ca0e9.png)

**Comment by dpjohnst** [comment]
Hi @personalnadir,

Thanks for reporting this!

By default we already batch large commands, though it looks as if there is a bug in this for MacOS.
We'll be investigating this further - stay tuned.

Kind regards,
\- Dylan

**Comment by personalnadir** [comment]
Thanks for fixing this, I can confirm Build 2039 let me stage the files.
