### ISSUE TITLE
Regression: Showing tags for all branches despite branch visibility limited to single branch

### ISSUE THREAD

**Issue by BenSluis** [sublimehq/sublime_merge#979]
**Version info**

 - OS: Windows 10
 - Build: 2038

**Description**

When setting the branch visibility to a single branch and then enabling the visibility of the tags, all branches are shown in the 'Commits' pane.  This is a regression in version 2038.  The previous version, 2032, would continue to respect the branch visibility and only show the tags on the currently visible branches.

**Steps to reproduce**

1. Clone https://github.com/BenSluis/tags_regression
2. Open repository in Sublime Merge
3. Checkout the master branch
4. Right click on master branch and select 'Hide All Branches Except master'
5. Click on the visibility icon for the 'TAGS' to show all tags

**Expected behavior**

I expect to see only the commits and tags on the master branch.
I actually see all tags from all branches (master and featureA in this example).

**Screenshots**
Screenshot from Sublime Merge 2032:
![branch_filter_master_only_build_2032](https://user-images.githubusercontent.com/67653254/98402877-e0587a00-201c-11eb-95b6-0838b6267557.png)

Screenshot from Sublime Merge 2038:
![branch_filter_master_only_build_2038](https://user-images.githubusercontent.com/67653254/98402887-e3536a80-201c-11eb-9c40-30d604345a33.png)

**Comment by srbs** [comment]
see also #932

**Comment by BenSluis** [comment]
This is covered by bug https://github.com/sublimehq/sublime_merge/issues/932 and enhancement request https://github.com/sublimehq/sublime_merge/issues/933
