### ISSUE TITLE
Crashes on trying to push to remote when pre-recieve hook is declined

### ISSUE THREAD

**Issue by moccy** [sublimehq/sublime_merge#98]
**Version info**

 - OS: Windows 10
 - Build: 1070

**Description**

I attempted to push to a remote, but instead found that Sublime Merge crashed to desktop. I later found out by using git from a command line that the remote declined the push due to a pre-recieve hook decline. It would be nice to see an error message describing why the push to remote failed rather than it crashing to desktop. 

**Steps to reproduce**

1. Open repository with a pre-release hook defined to decline pushes to a certain branch.
2. Try to push commits to the remote branch that should decline the push.

**Expected behavior**

An error message is displayed such as

`! [remote rejected] <branch> => <remote-branch> (pre-receive hook declined)`

**Comment by jskinner** [comment]
Thanks for your report. This may be fixed now in Dev Build 1076 at https://www.sublimemerge.com/dev
