### ISSUE TITLE
Opening S-Merge from S-Text: Foo doesn't look like a git repository

### ISSUE THREAD

**Issue by z-aki** [sublimehq/sublime_merge#981]
**Version info**

 - OS: macOS 10.14
 - Build: 2038

**Description**

Opening Sublime Merge from the context menu in Sublime Text creates annoying popups in Sublime Merge.

**Steps to reproduce**

- Open a file (that is under version control) in Sublime Text.
- Right click > blame file....
- See popups:
  - "blame doesn't look like a git repository. (OK button)"
  - "path/to/file doesn't look like a git repository. (OK button)"
  - "28<line number> doesn't look like a git repository. (OK button)"
- Press OK three times and then finally see the blame.

**Expected behavior**
No popups.

**Comment by dpjohnst** [comment]
Cc'ing you in here @BenjaminSchaaf

**Comment by BenjaminSchaaf** [comment]
@z-aki I can't reproduce this with the steps you've provided. Does this happen with all repositories? Do you have any other repositories open in Sublime Merge other than the one in which you're blaming the file? How are your applications installed, ie. are they in `/Applications`? Can you check whether either Sublime Text or Sublime Merge are quarantined (run `xattr /Applications/Sublime\ Text.app` and check for `com.apple.quarantine`)?

**Comment by z-aki** [comment]
> Does this happen with all repositories? 

yes

>  Do you have any other repositories open in Sublime Merge other than the one in which you're blaming the file?

Are you asking if I have any Sublime merge windows open ? no, the app is fully quit, and no window is open when I do the steps.

I have opened several repositories in the past, so they show up in recents if that's what you're asking.

>  How are your applications installed, ie. are they in /Applications?

Sublime Text is in /Applications. Sublime Merge is in ~/Applications.

> Can you check whether either Sublime Text or Sublime Merge are quarantined (run xattr /Applications/Sublime\ Text.app and check for com.apple.quarantine)?

Sublime Text has the attribute, Sublime Merge doesn't.

**Comment by z-aki** [comment]
@BenjaminSchaaf  My bad. I've set sublime_merge to `.....Contents/MacOS/sublime_merge` instead of `.....Contents/SharedSupport/bin/smerge`. That fixed it.
