### ISSUE TITLE
On-hover file name tooltip doesn't go away

### ISSUE THREAD

**Issue by retifrav** [sublimehq/sublime_merge#982]
**Version info**

 - OS: Windows 10.0.18363.1139
 - Build: 2038

**Description**

When you hover mouse pointer over a file name in Tree view at Files tab, a tooltip with the full name appears. In some cases this tooltip doesn't go away when mouse pointer no longer hovers over it.

**Steps to reproduce**

1. Open any repository
2. Select any commit
3. Click on Files tab
4. Go to Tree view
5. Hover mouse pointer over any file - a tooltip appears
6. Move the mouse pointer away from it
7. Tooltip might not disappear

**Expected behavior**

Tooltip should disappear. And it does in most cases, but sometimes it doesn't, and you can even spawn several "permanent" or "frozen" tooltips like that.

**Screenshots**

Here I have one tooltip already "frozen" (`App.xaml`) and another one about to (`MainWindow.xaml.cs`):

![scr-1](https://user-images.githubusercontent.com/6904927/98464885-213fc280-21c6-11eb-9c6e-c712f89f4a21.png)

Here they are with completely collapsed file tree:

![scr-2](https://user-images.githubusercontent.com/6904927/98464886-21d85900-21c6-11eb-8b47-b0777df67abb.png)

And if I resize the application window, they can even go outside of window boundaries:

![scr-3](https://user-images.githubusercontent.com/6904927/98464887-2270ef80-21c6-11eb-9d7a-1a014960a3f0.png)

**Comment by dpjohnst** [comment]
Hi @retifrav,

Sublime Merge 2086 (development build) has been released which fixes this.
This fix will also be available in the next stable build.

Kind regards,
\- Dylan from Sublime HQ
