### ISSUE TITLE
Can not delete file named :q

### ISSUE THREAD

**Issue by shawjef3** [sublimehq/sublime_merge#984]
**Version info**

 - OS: macOS 10.15.7
 - Build: 2032 or 2038

**Description**

If I have an untracked file named `:q` in my repo and I tell SublimeMerge to delete it, it disappears and then reappears in the UI.

**Steps to reproduce**

1. `touch ':q'`
2. tell SublimeMerge to delete `:q`

**Expected behavior**

Delete `:q` on the filesystem.

**Comment by dpjohnst** [comment]
Hi @shawjef3,

Thanks for reporting this.

As mentioned in the other bug report, we've got a fix for this coming in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Comment by shawjef3** [comment]
Still present in 2039.

**Comment by dpjohnst** [comment]
Hi @shawjef3,

Rest assured there is a fix that will be available in the next development build - soon after that the build will be promoted to a stable build.

I'll reach out again once the development build has been released.

Thank you for your patience,
\- Dylan

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge build 2040 (development build)

**Comment by dpjohnst** [comment]
Closing as this fix is now available in the stable channel (Sublime Merge Build 2047)
