### ISSUE TITLE
Deleting a file named : deletes all untracked files

### ISSUE THREAD

**Issue by shawjef3** [sublimehq/sublime_merge#985]
**Version info**

 - OS: macOS 10.15.7
 - Build: 2038

**Description**

I have an untracked file named `:` in my repo. When I tell SublimeMerge to delete it, instead of deleting just `:` it deletes all untracked files.

**Steps to reproduce**

1. `touch : a`
2. tell SublimeMerge to delete `:`

**Expected behavior**

Delete `:` on the filesystem, but not other files, such as `a`.

**Comment by dpjohnst** [comment]
Hi @shawjef3,

I'd like to apologise that this issue has affected you, and also thank you for bringing it to our attention.
We've addressed the issue internally, and it will be fixed in the next build of Sublime Merge.

Kind regards,
\- Dylan

**Comment by shawjef3** [comment]
Still present in 2039.

**Comment by dpjohnst** [comment]
Fixed in Sublime Merge build 2040 (development build)

**Comment by dpjohnst** [comment]
Hi @shawjef3,

Just following up that the fix for this was released to the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan
