### ISSUE TITLE
Per-Repository Previous Commit Message History

### ISSUE THREAD

**Issue by michaelalandawson** [sublimehq/sublime_merge#986]
**Problem description**

Currently, the "Use previous commit message" feature remembers previous messages for all repositories.  Can this be changed so that previous messages are remembered per repository?  When working on multiple repositories, you can quickly "lose" a previous message.  If this feature remembered messages per repository, I would have a better chance of finding a relevant previous message.

**Preferred solution**

When a repository is opened in Sublime Merge, it would be beneficial to offer previous commit messages that were used only in that particular repository and not globally within Sublime Merge.

**Comment by dpjohnst** [comment]
Thanks for the feedback - fixed in development build 2042!

**Comment by themilkman** [comment]
Hi @dpjohnst !

I liked the old behaviour because I often do some bulk-like commits in different project repositories.
Could there be an option key added for this, please?

Cheers!

**Comment by dpjohnst** [comment]
Hi all,

Just following up that this was released to the stable channel (Sublime Merge Build 2047).

Regarding your feedback @themilkman, it would be much appreciated if you could open a new enhancement request for this.

Cheers,
\- Dylan
