### ISSUE TITLE
Bold Full Branch Path

### ISSUE THREAD

**Issue by utahwithak** [sublimehq/sublime_merge#987]
**Problem description**

It would be nice if the full branch path was bolded. When dealing with various folders it can be hard to navigate to the currently checked out branch and can lead to expanding all the folders and looking for the bold one. 

If you have gitflow enabled and check out various peoples branches for testing or hacking on it can be really hard to find which branch your on in the browser. 

**Preferred solution**

A change to make each portion of the current branches path bold would be very helpful in side bar navigation.

**Alternatives**

Possibly a command to navigate and select/jump to current branch in the side bar.

**Screenshots**
In this example it would nice if cw and fm were bolded as well.
<img width="248" alt="Screen Shot 2020-11-16 at 1 17 27 PM" src="https://user-images.githubusercontent.com/2365192/99291600-144a5100-280e-11eb-9f1c-733ecf6cce02.png">

**Comment by dpjohnst** [comment]
Thanks for the feedback - added in development build 2042

**Comment by dpjohnst** [comment]
Hi @utahwithak,

Just following up that this was released to the stable channel (Sublime Merge Build 2047)

Cheers,
\- Dylan
