### ISSUE TITLE
Improve failure handling when setting preferences

### ISSUE THREAD

**Issue by onecrayon** [sublimehq/sublime_merge#99]
**Problem description**

Currently when setting preferences via the Command Palette, you must format your values using what appears to be JSON logic (e.g. strings must be wrapped in double quotation marks). However, this is not explicitly noted anywhere in the interface, and if you do not use JSON formatting, hitting enter just silently fails (no feedback of any sort; not even an error beep).

**Preferred solution**

Sublime Merge should handle user input without the user needing to worry about the underlying storage format. So if I try to change my `font_face` and enter something without string delimiters, Merge should add them for me when it commits the change. Or if I use single quotes, it should convert them to double quotes, escape existing double quotes (as unlikely as that is), etc.

This is my preferred approach because other portions of the app that use this identical UX do not care about formatting strings as strings (for instance, entering a stash or tag message does not require proper string formatting; that's handled when the app converts it to a command line argument).

**Alternatives**

Alternately, Merge should teach me how to use it. So if I enter a string without quotation marks (or any other invalid input), the app should give me feedback that explicitly tells me why it is not committing my changes and how to successfully enter strings and so forth.

**Comment by srbs** [comment]
FYI, build 1083 added support for unquoted preferences.

**Comment by dpjohnst** [comment]
Hi all,

Closing, as I feel the original issue has been sufficiently addressed. Please feel free to reopen if you feel it hasn't been.

Kind regards,
\- Dylan
