### ISSUE TITLE
Home/End buttons do not work in the commit message box

### ISSUE THREAD

**Issue by ryanjackman** [sublimehq/sublime_merge#997]
**Version info**

 - OS: MacOS Catalina 10.15.7
 - Build: 2039

**Description**

Pressing the Home or End buttons on the keyboard while writing a commit message has no effect. This would be helpful when writing longer commit messages, especially with more complex plaintext formatting.

Additionally, Shift+Home/End has the same behavior as Shift+PageUp/PageDown which is to select from the cursor position to the beginning/end of the commit (beginning of the first line or end of the last line). 

**Steps to reproduce**

1. Begin writing a commit message. Place cursor in the middle of a line.
2. Press Home or End on the keyboard
3. Observe nothing happens
4. Press Shift+Home or Shift+End
5. Observe the same behavior as pressing Shift+PageUp/PageDown

**Expected behavior**

Pressing Home should move the cursor to the beginning of the line.
Pressing End should take the cursor to the end of the line.

Pressing Shift+Home should select from the cursor to the beginning of the line.
Pressing Shift+End should select from the cursor to the end of the line.

Optionally, Home could first move the cursor to the first non-whitespace character on the first press and to the beginning of the line on the second press. Similar to VS Code behavior.

**Comment by srbs** [comment]
The `home` & `end` keys do not behave this way on macOS. The existing behavior is correct and expected on macOS and you'll see the same behavior in Sublime Text.

What you're looking for is `cmd+left` & `cmd+right`, with `+shift` for selection. If you want the Windows-like behavior, you are more than welcome to add your own keybindings: https://www.sublimemerge.com/docs/key_bindings

**Comment by ryanjackman** [comment]
@srbs Ahh... right. I guess I got used to other programs overriding the default behavior.

I don't think this can be done with keybindings in Sublime Merge though. I couldn't find any commands to move the cursor or selection.
Info I found online shows that the keybindings in macOS can be changed to work like Windows so I will probably go that route.

I'm closing this as it seems unreasonable to override the system defaults.

**Comment by srbs** [comment]
These key bindings should work:

```
[
    {
        "keys": ["home"],
        "command": "move_to", "args": {"to": "bol", "extend": false},
        "context": [{ "key": "control", "operator": "equal", "operand": "text_control" }]
    },
    {
        "keys": ["end"],
        "command": "move_to", "args": {"to": "eol", "extend": false},
        "context": [{ "key": "control", "operator": "equal", "operand": "text_control" }]
    },
    {
        "keys": ["shift+home"],
        "command": "move_to", "args": {"to": "bol", "extend": true},
        "context": [{ "key": "control", "operator": "equal", "operand": "text_control" }]
    },
    {
        "keys": ["shift+end"],
        "command": "move_to", "args": {"to": "eol", "extend": true},
        "context": [{ "key": "control", "operator": "equal", "operand": "text_control" }]
    }
]
```

**Comment by ryanjackman** [comment]
Thanks! This is exactly what I was looking for.
